### ISSUE TITLE
Integrate ssz-js into the needed portions of the beacon chain

### ISSUE THREAD

**Issue by Mikerah** [ChainSafe/lodestar#10]
Development of ssz-js (https://github.com/ChainSafeSystems/ssz-js) is underway with the help of Darren Langley from Rocket Pool. 

After the ssz is mostly done with tests and submitted to npm so that everyone can easily use it, we need to integrate it into this repository.

**Comment by wemeetagain** [comment]
Closing as we're currently using ssz
