### ISSUE TITLE
Update labeler

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1017]
Our labeler action is quite outdated. 
I would suggest following labels:
- StateTransition - packages/lodestar-beacon-state-transition, packages/spec-test-runner, packages/lodestar-spec-test-util
- CLI - packages/lodestar-cli
- Types - packages/lodestar-types
- Config - packages/lodestar-config, packages/lodestar-params
- Validator - packages/lodestar-validator
- Api - packages/lodestar/src/api
- Network - packages/lodestar/src/network, packages/lodestar/src/sync
- Eth1 - packages/lodestar/src/eth1

cc @wemeetagain

**Comment by wemeetagain** [comment]
This looks good to me
