### ISSUE TITLE
Rename chain getBlockAtSlot to getCanonicalBlockAtSlot

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1018]
Currently, we have getBlockAtSlot() in chain but it only return 1 block on the same chain to head or null.
In reality, for single slot we may have multiple blocks staying on multiple chains of fork choice. We may need to implement getBlocksAtSlot() to return all blocks of that slot and check if we want/should call getBlocksAtSlot() instead of getBlockAtSlot().

**Comment by dapplion** [comment]
Who would consume the method `getBlocksAtSlot()`?

**Comment by twoeths** [comment]
This comes from https://github.com/ChainSafe/lodestar/pull/1005#pullrequestreview-431274541

We need to review all places that use `getBlockAtSlot()` and call `getBlocksAtSlot()` if applicable

**Comment by wemeetagain** [comment]
Rename `getBlockAtSlot` to `getCanonicalBlockAtSlot`
