### ISSUE TITLE
Convert api query params to camel case

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1021]
**Is your feature request related to a problem? Please describe.**

According to api spec, query params are snake-case which means in our api controllers we have to deal with snake case params which are against eslint rule. 

**Describe the solution you'd like**

Fastify uses ajv schemas to validate and coerce data. Ideally, there would be some way to automatically convert query params to camel case.

**Describe alternatives you've considered**

We could write fastify plugin that would intercept query params and convert them to snakeCase

**Additional context**

**Comment by wemeetagain** [comment]
Alternative solution:
Handle snake_case variables at the REST API layer w/o run-time translation, use file-wide eslint-disable to disable camelcase rule for each affected file.

**Comment by mpetrunic** [comment]
I think we could add to eslint to ignore this rules for all files in /api/rest directory?

**Comment by dapplion** [comment]
Should this be pursued or closed?
