### ISSUE TITLE
Handle stream api closing

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1029]
On our stream endpoints we have following logic:
- register event listener
- convert event listener into async generator
- convert generator into stream

That works until api consumer closes connection in which case we get:
`2020-06-18 12:10:48  [API]              warn: response terminated with an error with headers already sent `
and we are left we dangling event listener.

Solution:
From stream api implementation should return callback which can be invoked once `fastifyRequest.raw.on("close")` occurs which in term should stop EventIterator and unregister event listener.

**Comment by dapplion** [comment]
The listener that leaks is the subscription to the chain event emitter?
https://github.com/ChainSafe/lodestar/blob/bbe4654080fd05803b92d5f40543fb67c39b9e1a/packages/lodestar/src/api/impl/beacon/beacon.ts#L96

**Comment by mpetrunic** [comment]
> The listener that leaks is the subscription to the chain event emitter?
> https://github.com/ChainSafe/lodestar/blob/bbe4654080fd05803b92d5f40543fb67c39b9e1a/packages/lodestar/src/api/impl/beacon/beacon.ts#L96

yes it also generates warn messages because EventIterator that wraps it pushes new event after connection is closed.
