### ISSUE TITLE
Remove the deprecated lodestar cli

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1031]
Part of moving to the new `lodecli` cli:

Previously, we had a cli named `lodestar`, being replaced with a `lodecli` cli, which is more organized.
We want to:
1. remove old `lodestar` cli code
2. reorg `lodecli` code (by pulling it out of its own `lodecli/` directory)
3. replace any references to the old `lodestar` cli

4. Optionally, up for discussion, @ChainSafe/eth2-0  should we rename `lodecli` to `lodestar` ?

**Comment by twoeths** [comment]
yeah having cli as `lodestar` seems to be more natural to me
