### ISSUE TITLE
Syncing Witti: Cannot stop beacon node when there is no peer

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1038]
This log keeps printing when there is no peer:
```
2020-06-22 14:17:33  [SYNC]             warn: Current peerCount=0, required = 2
2020-06-22 14:17:36  [SYNC]             warn: Current peerCount=0, required = 2
2020-06-22 14:17:39  [SYNC]             warn: Current peerCount=0, required = 2
2020-06-22 14:17:42  [SYNC]             warn: Current peerCount=0, required = 2
```

**Comment by 3xtr4t3rr3str14l** [comment]
@tuyennhv do you have any thoughts for what should be done instead of continaully printing the log?  to me, it seems like it would make sense to keep putting the log to show that there is no peer, but maybe it would also be good to show something that the user can act on.  for me, i'm currently running into this error, and i don't have a firewall up, so i'm not sure why it is happening.  and the logs from the client don't give me any insight other than what you posted above.

**Comment by 3xtr4t3rr3str14l** [comment]
for the record, this also happens for me when trying to run lodestar against the Altona testnet

**Comment by twoeths** [comment]
Ah sorry I forgot to mention that I could not stop the console, and this only happens a couple of times.

**Comment by 3xtr4t3rr3str14l** [comment]
@tuyennhv do you know if it's because it's just taking some time to connect to a peer?  also, do you mean that we should have an option to suppress these messages via a keyboard combo or similar?

**Comment by twoeths** [comment]
@3xtr4t3rr3str14l Normally our network detects new peer through `peer:connect` event from libp2p/discv5 and it'll do handshake (send/receive/compare status messages) in order to create a new peer. If a new peer does not have expected Status message, we'll disconnect that peer. I guess that's the end of Witti period and our bootstrap peers switched to Altona already, so we need to try again to reproduce the issue with Altona.

> also, do you mean that we should have an option to suppress these messages via a keyboard combo or similar?

I just mean we should be able to do `Ctrl + C` to stop the process, normally we can do that nicely.

I'll post Altona configuration here so that you can sync Altona and see if the issue still happens.

**Comment by twoeths** [comment]
I think this document from @wemeetagain is great to sync Altona https://hackmd.io/2wNvrO77RQ6BWc2ZA7M0Cg?both , you can start from there.
Genesis state file can be fetched from https://github.com/eth2-clients/eth2-testnets/blob/master/shared/altona/genesis.ssz , you can also remove the `genesisStateFile` option and detect genesis state yourself.

**Comment by wemeetagain** [comment]
Resolved
