### ISSUE TITLE
Cannot convert undefined to a BigInt

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1040]
At the time my server is starting, accessing `/node/syncing` gives me this response:
```
{"statusCode":500,"error":"Internal Server Error","message":"Cannot convert undefined to a BigInt"}
```

**Comment by dapplion** [comment]
How exactly are you running the server? I'm not getting this error by doing
```bash
lion@lion:lodestar$ yarn run cli dev --dev.genesisValidators 1 --dev.reset
```
and immediately
```bash
lion@lion:lodestar$ curl http://127.0.0.1:9596/node/syncing
{"starting_block":"0","current_block":"0","highest_block":"0"}
```

**Comment by dapplion** [comment]
Same as https://github.com/ChainSafe/lodestar/issues/1358 ?

**Comment by twoeths** [comment]
@dapplion I deployed to my heroku server running witti at that time, not maintained that for a while.
When I restart the server and issue that api in my browser, I got the error.

**Comment by mpetrunic** [comment]
Closing as duplicate of #1358 and there are more logs there
