### ISSUE TITLE
Continuous deployment / common server for testnet

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1049]
See https://discordapp.com/channels/593655374469660673/593655641445367808/725551465451749457

We should have some continuous deployment of lodestar, configured to sync a testnet, so we can ensure we don't regress.

I'm not familiar with all the options for how/what that can/should look like, we can discuss here.

**Comment by wemeetagain** [comment]
I'm thinking something like this:

- phase 1
  - testcases to be run in a kube cluster
  - a single testcase, to be run run daily
  - testcase has metrics and logs scraped from all running nodes (lodestar or not)
  - metrics and logs get exported to an elasticsearch database, running separately, for later analysis, accessible to lodestar team, publicly if its not easily attackable/dos-able
- phase 2
  - dashboard(s) attached to elasticsearch
  - testcases triggered by lodestar push/pr webhook
  - additional testcases detailed and developed, added to scheduled runs
- phase 3
  - dashboard customized/tailored to show relevant high-level statistics
  - hook into github checks API to push testcase results to lodestar PR statuses
  - additional testcases!

Start with simple testcases, spinning up small ephemeral testnets. The purpose of these tests is to quickly catch errors and measure baseline performance in "live" scenarios:
1. baseline lodestar test
- start N lodestar bn+vc, run for 10 minutes
2. baseline interop sync and chain follow
- start N lighthouse bn+vc, run 5 minutes. start 1 lodestar bn, let sync and run for 5 minutes

**Comment by dapplion** [comment]
After adding the multi-client test and its subsequent problems, it might be worth to revisit this issue and agree and what to implement next to bring the most value without stalling the tests or making them too brittle

**Comment by wemeetagain** [comment]
Right. My hope with this was that this could be something we can let be a "longer running test" that is entirely decoupled from our PR CI. These tests would true e2e tests where lodestar nodes are run via the cli on separate hosts to test out real-world scenarios. "Test feedback" would be given thru metrics collection + log aggregation, and would be more than simply a :heavy_check_mark: / :x: , rather we would be provided with raw data and dashboards for deeper analysis.

**Comment by philknows** [comment]
@dapplion Do we want to use this issue to address the setup of a continuous deployment server for production code monitoring? Or was the purpose of this issue to be used for something else? I can just create a brand new issue if req'd.

**Comment by dapplion** [comment]
We have this implemented now for Prater
