### ISSUE TITLE
Save ENR to disk on ENR update

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1053]
See https://discordapp.com/channels/593655374469660673/593655641445367808/725848665327140917

We should save the ENR to disk whenever it updates.
It may be difficult to have ENR extend EventEmitter (as it currently already extends Map), but we may find another way to keep the ENR updated on disk.
A strawman proposal:
Extend ENR with a subclass which accepts a path in its constructor, overrides `set` to save to disk after updating.

**Comment by dapplion** [comment]
@wemeetagain Is this solved with the recent ENR changes?

**Comment by 3xtr4t3rr3str14l** [comment]
resolved in #1694
