### ISSUE TITLE
Render swagger-ui on root endpoint in rest api

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1060]
It would be nice instead of 404 to render swagger-ui on http://localhost:<post> to load swagger-ui with our server as primary server url.

Until we release spec, we should probably bundle spec into single file and ship it along.
There is some fastify plugin for that probably

**Comment by dapplion** [comment]
Do you want to bundle up with the beacon chain code the swagger UI, or add it to our CI pipeline publicly like https://api.prylabs.network/ ?

**Comment by mpetrunic** [comment]
I think it would be useful to bundle it. cc @wemeetagain

**Comment by wemeetagain** [comment]
My preference is to not bundle it, or somehow only optionally bundle it for debugging.
This is likewise to not bundling graphiql during production, but using it during development/debugging scenarios.

**Comment by dapplion** [comment]
Other clients don't bundle it up. Should this still be pursued? If we follow https://github.com/ethereum/eth2.0-APIs strictly is it necessary to maintain our own swagger UI?

**Comment by mpetrunic** [comment]
As I compromise, we could add redirect from lodestar api base url to https://github.com/ethereum/eth2.0-APIs .

It would be REALLY nice if we could pass server url somehow. That said, we are missing /eth prefix on all routes
for https://github.com/ethereum/eth2.0-APIs to be effective

**Comment by wemeetagain** [comment]
Would like this feature behind a CLI flag.

**Comment by wemeetagain** [comment]
Resolved with #5970
