### ISSUE TITLE
Passing cors "*" to rest api doesn't work

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1062]
If you pass "*" cors doesn't allow every origin.

Solution:
Figure out how to support multiple origin splitted by "," as well as regex.

**Comment by jahosh** [comment]
I’d like to take a crack at this, is it still open?

**Comment by mpetrunic** [comment]
yes, ill assign you

**Comment by dapplion** [comment]
@jahosh Let us know if you found any roadblocks on this issue.

**Comment by g11tech** [comment]
is this still open?

**Comment by dapplion** [comment]
> is this still open?

Most likely, could you verify locally to check if still an issue?

**Comment by g11tech** [comment]
Ok

**Comment by g11tech** [comment]
we use fastify?

**Comment by wemeetagain** [comment]
Yeah, most/all of the code is currently here: https://github.com/ChainSafe/lodestar/tree/master/packages/lodestar/src/api/rest

**Comment by g11tech** [comment]
cors setup is already there: (if opts.cors is set to be an array of urls/regex that would also work)
![image](https://user-images.githubusercontent.com/76567250/112674050-75a0c180-8e8b-11eb-9312-daad530a6431.png)

without passing anything, its already building options of *

![image](https://user-images.githubusercontent.com/76567250/112674150-9832da80-8e8b-11eb-9f32-9464f3dd0c29.png)

also tested the http headers returning *:
![image](https://user-images.githubusercontent.com/76567250/112674254-b26cb880-8e8b-11eb-95d8-89e115636933.png)

I guess issue is no more relvant and can be closed

**Comment by wemeetagain** [comment]
Thanks!
