### ISSUE TITLE
Remove PouchDB

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1067]
Currently, we have two levels of abstraction in our "database".
`DatabaseController<Buffer, Buffer>`, with a generic low level kv interface
`Repository<K, V>`, with a high level kv database, operating and indexed by eth2 consensus objects, occasionally subclassed for different reasons.

This low-level abstraction is in place to support different database backends, and currently we have support for leveldb and pouchdb.

It seems that in practice, we've been using leveldb, and our pouchdb implementation is constantly in a half-working or broken state. It's also likely to be less efficient, considering there is an additional level of byte <-> string conversion happening there. The latest issue is that its a major source of ts-ignore, as its type declarations are out of date.

We can move forward in a few different ways:
1. fix/maintain pouchdb implementation
Keep the status quo, patch pouchdb implementation as needed

2. remove the pouchdb implementation
Simply delete the pouchdb file and pouchdb tests.

3. remove the abstract DatabaseController, use leveldb directly (includes 2. removing pouchdb implementaiton)
This would go a step further than simply removing the pouchdb implementation and remove the DatabaseController abstraction entirely. Instead, a level instance would be used directly in our `Repository`s. 

I'm currently leaning towards 2.

Argument in favor of 2:
Pouchdb uses leveldb in node, and indexeddb in the browser. This gives us no discernable benefit over leveldb, which uses a native adapter in node and indexeddb in the browser. This leaves only the downsides, chiefly extra code to maintain.

**Comment by dapplion** [comment]
@wemeetagain What's the priority for this proposal?
