### ISSUE TITLE
Document supported ES versions

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1068]
The bulk of lodestar assumes ES2020 support, though some of our repos support ES5 or ES6.
We might note the minimum version we support in each repo, and/or add a column showing that to this document: https://hackmd.io/CcsWTnvRS_eiLUajr3gi9g

**Comment by 3xtr4t3rr3str14l** [comment]
resolved.  ES and node versions now documented in lodestar and it's other ChainSafe-specific dependencies
