### ISSUE TITLE
Searching blocks by parentRoot property

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1069]
**Is your feature request related to a problem? Please describe.**

In api, we need to be able to filter blocks by parentRoot.
Ref: https://ethereum.github.io/eth2.0-APIs/#/Beacon/getBlockHeaders

**Describe the solution you'd like**

Finalized blhttps://ethereum.github.io/eth2.0-APIs/#/Beacon/getBlockHeadersocks (block archive):
- store references parentRoot => slot (since finalized blocks are indexed by slot)

NonFinalized blocks:
- quick solution would be to just iterate all blocks and search mannually (they are already in memory)
   - could be problematic in long periods of non finalization

**Describe alternatives you've considered**

**Additional context**

**Comment by wemeetagain** [comment]
Both of those solutions seem good.

Definitely wouldn't bother with anything fancier for non-finalized blocks until/unless we do something more advanced for the cases of non-finalization. Likely worth tackling as a separate issue once it arises.
