### ISSUE TITLE
Get finalized block by root

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1070]
**Is your feature request related to a problem? Please describe.**

When fetching block by block id ("head", slot, root, "genesis" etc), we should resolve block id to root.
When we do that, we cannot fetch finalized blocks since they are indexed by slot.

**Describe the solution you'd like**

Store root => slot references for finalized blocks.

**Describe alternatives you've considered**

Make function to resolve block id into root if not finalized and slot if finalized. I Think this alternative will make code quicke complex and we would propagate this complexity trough a lot of code.

**Additional context**

**Comment by wemeetagain** [comment]
:+1:
With this and #1069 we will be able to retrieve finalized blocks by slot, root, or parentRoot.
We likely should expose helpers on our forkchoice/chain to retrieve non-finalized blocks by slot, root, or parentRoot, to mirror.
