### ISSUE TITLE
Stop BeaconNode startup if REST API port is taken

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/lodestar#1072]
**Describe the bug**

It seems thats the logged error didn't impact the node from running, but there were some errors logged.

**Expected behavior**

No error :smile: 

**Steps to Reproduce**

Ran off master, followed the installation instructions (git clone) and followed the local [testnet instructions](https://chainsafe.github.io/lodestar/usage/local/)

**Screenshots**

![Screenshot from 2020-06-28 22-09-11](https://user-images.githubusercontent.com/16929357/85966031-971c5d80-b98c-11ea-82fa-de837f641552.png)

**Desktop (please complete the following information):**
 - OS:  ubuntu
 - Version:  20
 - Branch:  Master
 - Commit hash:  7f69a144

**Comment by mpetrunic** [comment]
You have something runnung on rest server port?

**Comment by GregTheGreek** [comment]
@mpetrunic I believe the top node is using it by default?

**Comment by mpetrunic** [comment]
Seems so, I might have enabled rest api by default

**Comment by mpetrunic** [comment]
Seems like we have multiple options here how to proceed:
1. disable rest in dev command
2. start them at random ports
3. add flag to second command in docs to start api on different port (best option in my opinion)

@GregTheGreek wdyt we should choose?

**Comment by GregTheGreek** [comment]
I also like option 3, does the rest server failing to start sound like something we should panic out of? I know @dapplion brought it up earlier this week

**Comment by mpetrunic** [comment]
We didn't panic, we just reported error that api server failed to start though :smile:

**Comment by GregTheGreek** [comment]
Right right!
I'm thinking it might make sense to panic?

**Comment by GregTheGreek** [comment]
or rather, gracefully shutdown :sweat_smile:
