### ISSUE TITLE
Finalized block when restarting chain

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1078]
**Describe the bug**
When restarting change, chance is that we can't get finalized block in `block` database due to the change we have in #1077 

**Expected behavior**
Should find finalized block from either `block` or `archivedBlocks` database depending on if `ArchiveBlock` run already or not

**Comment by mpetrunic** [comment]
But `ArchiveBlock` happens on every finalized epoch, if node is killed before `ArchiveBlock` for last finalized epoch happens, it shouldn't really matter as we will just resync from last stored finalized block?

**Comment by twoeths** [comment]
When we restart, we need both finalized block and finalized state and we start from the latest finalized state (aka `lastKnownState`). I'd order the `ArchiveBlocks` then `ArchiveState` in `TasksService` so that when we restart we're sure to get the finalized block from `ArchiveBlock` database.

> it shouldn't really matter as we will just resync from last stored finalized block?

I think we resync from the finalized block respective to the last stored finalized state

**Comment by wemeetagain** [comment]
Is this issue the same as https://github.com/ChainSafe/lodestar/issues/1046 ?

**Comment by twoeths** [comment]
Yeah this should resolve that issue.
