### ISSUE TITLE
Validator CLI

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1085]
**Is your feature request related to a problem? Please describe.**
We need a validator CLI to run validators from the command line.

**Describe the solution you'd like**
A validator CLI with:
- ability to run N validators at once
- the big task here will be handling on-disk persistence, managing keys, user secrets, etc and passing them successfully to the validator nodes
- safely handle user secrets
- we likely only need to handle 'keystores', rather than 'walletstores'
- consistent code style, building off the current `beacon` command. Eg: Create a `validator` command, in the same way
- implementation following community standards and community discussion
  - ideally following closely with other client decisions, picking the best ideas and using them

**Describe alternatives you've considered**
No CLI? :sob: 

**Additional context**
Related to the validator CLI we may need a wallet CLI command. Depending on judgement, that may be completed in parallel or as a prerequisite.

[EIP-2335](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2335.md)
https://github.com/ethereum/eth2.0-pm/issues/161
See other clients validator clients:
https://github.com/sigp/lighthouse/tree/master/validator_client
https://github.com/PegaSysEng/teku
https://github.com/prysmaticlabs/prysm/
https://github.com/status-im/nimbus
https://github.com/ethereum/trinity/tree/master/eth2

See Eth2 R&D #key-management discord for important discussion on validator key management

**Comment by dapplion** [comment]
Do you imagine it being close to `ethdo` https://github.com/wealdtech/ethdo/blob/master/docs/usage.md ?

**Comment by wemeetagain** [comment]
I think that would be more related to an `account`/`wallet` command, which would manage the on-disk keystores, in a lodestar-opinionated way.

The `validator` cli command would read on-disk keystores, as configured via cli and on-disk configuration, and use those to init `Validator`s from `lodestar-validator`.

**Comment by wemeetagain** [comment]
resolved with #1093
