### ISSUE TITLE
monorepo build:watch

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1089]
**Is your feature request related to a problem? Please describe.**
It's frustrating when eg: Running the cli from `lodestar-cli`, after updating code in `lodestar`, we must run `yarn build` from the lodestar package, for `lodestar-cli` to pick up the changes.

The typescript source is not used by other downstream monorepo packages, only the transpiled javascript is used.

**Describe the solution you'd like**
Maybe we can have something along the lines of `babel --watch && tsc --watch` running in each monorepo package, which will pick up any typescript file changes and automatically update the transpiled JS. This way, we won't need to be constantly be manually re-building each package.
If we can package this into something that we can run via `lerna`, we can get auto-building for the whole monorepo at once, very nice.

**Describe alternatives you've considered**
write a custom thing with https://github.com/paulmillr/chokidar with a nice glob that targets only what we need

**Additional context**
https://babeljs.io/docs/en/babel-cli#compile-files
https://www.typescriptlang.org/docs/handbook/configuring-watch.html

**Comment by mpetrunic** [comment]
fyi I usually just run `lerna run build - - scope @chainsafe/<package>` to compile only package i changed
