### ISSUE TITLE
Add typechecks when using a dynamic key in an object

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1092]
**Describe the bug**
This statement will throw a TypeError if `blockProposerIndex` is not in state. `blockProposerIndex` is an uncontrolled API request parameter, so it can happen
```js
state.validators[blockProposerIndex].pubkey
```

**Expected behavior**
It should throw a nice error like `unknown proposer index`

**Steps to Reproduce**
Call the getProposerDuties endpoint with a random `blockProposerIndex`

---

## Todo

Similar errors can exist in other parts of the codebase, review

**Comment by dapplion** [comment]
After investigating the issue, the use of arbitrary keys is extremely extensive in the codebase. Adding a check such as
```js
      const validator = state.validators[blockProposerIndex];
      if (!validator) throw Error(`validator ${blockProposerIndex} not in state`);
      duties.push({slot, proposerPubkey: validator.pubkey});
```
is completely unfeasible.

I see that the desired behavior will be that accessing key without a value throws an error immediately, instead of breaking the code downstream for some random reason. Will ES6 Proxies add some value here?

**Comment by wemeetagain** [comment]
In this case, the state object is actually already a `Proxy`, created in the ssz library, wrapping a binary merkle tree, exposing the `BeaconState` interface. Any subsequent getters that return non-primitive values also return Proxy objects. Eg: `state.validators[x]`

The ssz library _should_ already be throwing an error for an invalid access, ie to a node in the tree that does not exist or should not be accessible. Such as the case when an invalid validator index is accessed in `state.validators`.

**Comment by dapplion** [comment]
@wemeetagain You changed it from throwing an error to returning undefined in `v0.6.7` https://github.com/ChainSafe/ssz/commit/f94ad9db979d4b9b5895b8b7721f98d92d4f5be9#diff-6bfccd37008feef12ddec272c9e10203L82

Can you remember the reasoning?

**Comment by wemeetagain** [comment]
Yeah, the reasoning was to align `TreeBacked` object behavior to that of `ObjBacked` objects.
Ofc this is exactly the issue you're bringing up. The `Object` interface doesn't handle null checks well XD
