### ISSUE TITLE
Decompose IEth1Notifier into parts

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1103]
I think we can (eventually) decompose this `IEth1Notifier` into a few parts, that can be run on-demand, rather than started globally. If we want to reuse resources, we could keep the provider and keep that around (it could be started/stopped in node.ts). Decomposing the functionality will lead to increased maintainability (each thing can be in its own file) and flexibility in how we can use this:
```typescript
type BlockTag = string | number

/**
 * Thin wrapper around ethers provider, tailored for the deposit contract
 */
interface IEth1Provider {
  /**
   * initialize contract, error if it doesn't exist or is invalid
   */
  start(): Promise<void>;
  stop(): Promise<void>;

  getBlock(blockTag: BlockTag): Promise<Block>;
  getDepositEvents(fromBlockTag: BlockTag, toBlockTag?: BlockTag): Promise<IDepositEvent[]>;

  // event for new blocks
  on(event: 'block', block: Block): void;
  off(event: 'block', block: Block): void;

  // event for module stopping, allows for event consumers to gracefully shut down
  on(event: 'stop'): void;
  off(event: 'stop'): void;
}

interface IBatchDepositEvents {
  depositEvents: IDepositEvent[];
  blockNumber: number;
}

/**
 * Stream of deposit events, batched by block number.
 * Includes blocks with 0 deposit events
 */
function getHistoricalDepositEventsStream(provider: IEth1Provider, from: blockNumber, to: blockNumber): Promise<Pushable<IBatchDepositEvents>>;

/**
 * Abortable stream of batched deposit events
 * data starting at `from`, continues at ETH1_FOLLOW_DISTANCE until aborted or IEthProvider stops
 */
function getFollowDepositEventsStream(provider: IEth1Provider, from: blockNumber): Promise<Pushable<IBatchDepositEvents>>;
```

From there we've separated how the data is consumed, database storage concerns, whether a stream has a single or multiple consumers, etc. We should write up a design doc determining what we store, when we store, which modules manage storage, etc. Likely, we will have a strategy for genesis and a strategy for proposing.

Eth1Data processing requires a depositData tree, either fetched from the db module, or managed by the genesis builder.
```typescript
/**
 * Create an Eth1Data based on a block and a deposit data root tree
 */
function getEth1Data(block: Block, depositDataRootTree: TreeBacked<Root<DepositData>[]>): {timestamp: number, eth1Data: Eth1Data};
```

IMO building out good primitives like this will help everything else fall into place.

_Originally posted by @wemeetagain in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NDM1NDkxODM1/pull_request_reviews/more_threads_

**Comment by wemeetagain** [comment]
With the machinery above, the _genesis builder_ can control when to get blocks / eth1 data:

pseudocode for a stateless genesis builder:
- constructor takes eth1 provider and beacon config
  - create and manage an empty deposit tree
  - create and manage an empty genesis state
  - start from some known block number
- use getFollowDepositEventsStream to handle batched deposit events for each block
  - incrementally build genesis state and deposit tree
  - once the state has min_validators
    - begin fetching eth1 data and timestamp w/ provider.getBlock and getEth1Data
    - optionally: if fetched timestamp is before min_genesis_time, don't fetch eth1 data again 'until necessary'
  - if a valid genesis is found, abort stream
- throw error if managed state is invalid (eth1 provider stopped before genesis processed)
- return genesis state, deposit tree, last processed block number on success, if managed state is valid

Note1: This can be run entirely without the db, which is great for keeping things simple.
Depending on how fast this is, we likely don't even need to store pre-genesis deposits to db, but only store to db after a valid genesis state is returned -- outside of the scope of genesis builder.
Or we can 'save our progress' to the db by having genesis builder accept a starting deposit tree and block number, return the processed deposit tree and last processed block number in the 'error case', to be saved to db on shutdown.

Note2: Because we use the state.validators.length to compare against min_validators, we don't run into the issue of fetching eth1 data "too soon" as we do now when comparing # of deposit events against min_validators. :)

**Comment by dapplion** [comment]
Agree on the vision for this. Meta-assigning this issue to self

**Comment by twoeths** [comment]
Need to support restarting chain while detecting genesis state. Current it's like
```
2020-08-03 17:50:39  [ETH1]          verbose: Processing 1 deposit events of eth1 block 3086571
 ✖ Error: Invalid deposit merkle branch
    at Object.true (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar-utils/lib/assert.js:16:13)
    at processDeposit (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar-beacon-state-transition/lib/block/operations/deposit.js:27:29)
    at /Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/chain/genesis/util.js:79:55
    at Array.forEach (<anonymous>)
    at applyDeposits (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/chain/genesis/util.js:69:15)
    at /Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/chain/genesis/genesis.js:87:35
    at async GenesisBuilder.waitForGenesis (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/chain/genesis/genesis.js:72:19)
    at async BeaconChain.waitForState (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/chain/chain.js:395:15)
    at async BeaconChain.start (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/chain/chain.js:148:19)
    at async BeaconNode.start (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/node/nodejs.js:157:5)
```
