### ISSUE TITLE
GENESIS_FORK_VERSION copied incorrectly from template-config-file

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1108]
**Describe the bug**
When using a template config file eg: `lodestar beacon init --template-config-file foo.json`
If the template file contains a hex string, it will be copied incorrectly, converted to a number, and copied as a number.

**Expected behavior**
It copies hex string unmodified.

**Steps to Reproduce**
Follow instructions here: https://hackmd.io/2wNvrO77RQ6BWc2ZA7M0Cg
inspect generated beacon.config.json

Related to https://github.com/ChainSafe/lodestar/issues/977

**Comment by 3xtr4t3rr3str14l** [comment]
resolved in #1136
