### ISSUE TITLE
Altona: Finalized/Justified Checkpoint Root is last block of previous Epoch

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1115]
**Describe the bug**
It happens to both justified epoch and finalized epoch when the start slot of epoch is missed. This is what I get
```
Epoch 2 is justified at root 0x04e951bd1a58c7f52e26a07b475b7e59bac3f3d80f2c0baac2748545c7886f80!
```

This is the log at end of Epoch 1 and start of Epoch 2
```
2020-07-08 15:37:29  [CHAIN]            info: Processed new chain head newChainHeadRoot=0xeba3c7dec48fe9ad8a2392f46b6a871fb5355550e73d5b5b28a5fac44c0845eb, slot=62, epoch=1
2020-07-08 15:37:29  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x04e951bd1a58c7f52e26a07b475b7e59bac3f3d80f2c0baac2748545c7886f80, slot=63, epoch=1
2020-07-08 15:37:31  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x471e17ac8d154a1cf982804140f1841477b024b6fa6c8d20064428642dfce13a, slot=65, epoch=2
```
We can see that block 64 is missing.
**Expected behavior**
The justified block of epoch 2 should be `0x471e17ac8d154a1cf982804140f1841477b024b6fa6c8d20064428642dfce13a` which is the first slot of Epoch 2 (slot 65)

**Steps to Reproduce**
+ Print roots at https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/chain/blocks/post.ts#L68 - `newJustifiedEpoch` and `newFinalizedEpoch` functions.
+ Sync Altona until Epoch 3/4 to see the logs.

**Comment by twoeths** [comment]
Details of Epoch 2 can be seen in https://altona.beaconcha.in/epoch/2

**Comment by twoeths** [comment]
Looking at the implementation of `processSlots`, it seems to me that's the intended behavior, at least with the current spec because this function passes spec tests of 0.12.1.

**Comment by twoeths** [comment]
Not a bug as explained by proto:
```
that's normal
Or occasionally, at least
It refers to the first block in  an epoch. If there's a skip slot at the first slot in that epoch, it will refer to the last known block in the chain
This is also the reason why checkpoint types are "block root + epoch". Checkpoints can continue, even though there may not be any blocks
```

**Comment by wemeetagain** [comment]
:+1: fixed a bug in chain restoration related to this here: https://github.com/ChainSafe/lodestar/pull/1112
