### ISSUE TITLE
--template-config-file does not copy logger options

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1132]
**Describe the bug**
`beacon init --template-config-file` doesn't copy logger level options from the template to the copied config.

**Expected behavior**
It should copy all options, including any log levels set

**Steps to Reproduce**
- Create a template config.json with log levels set
- run `beacon init --template-config-file` pointing to template
- inspect the new, built config file

**Screenshots**
https://discordapp.com/channels/593655374469660673/593655641445367808/731091039372312627

**Comment by 3xtr4t3rr3str14l** [comment]
looks like this is resolved now.  i'm seeing the logger options in the built config after running `yarn run cli beacon init --template-config-file altona.json`.  where altona.json has logger options.   can you retest @wemeetagain ?
