### ISSUE TITLE
Altona: Cannot detect new peers upon restart

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1141]
**Describe the bug**
After we initialize a beacon folder and sync Altona, we can always detect peers very quickly. But upon a restart, sometimes we can detect peers, sometimes we cannot and we end up with setting up a new beacon folder by `beacon run init`.

**Expected behavior**
We can detect new peers at any time

**Comment by twoeths** [comment]
This is an issue of discv5 since it never emit a "peer" event to libp2p. When we send random requests to peers, most of them do not response us except for 1-2 peers with below log:
```
discv5:service Sending lookup. Id: 1, Iteration: 1, Node: 13027eca868692747ffd93324fbf38f4d1f435d4d950ed92b326138b3c862eb8 +1ms
  discv5:sessionService No session established, sending a random packet to: 13027eca868692747ffd93324fbf38f4d1f435d4d950ed92b326138b3c862eb8 on /ip4/18.223.219.100/udp/5000 +1ms
discv5:sessionService Sending authentication message: { type: 3, id: 1740388084140610451n, distance: 255 } to node: 13027eca868692747ffd93324fbf38f4d1f435d4d950ed92b326138b3c862eb8 on /ip4/18.223.219.100/udp/5000 +1ms
discv5:sessionService Message timed out with node: 13027eca868692747ffd93324fbf38f4d1f435d4d950ed92b326138b3c862eb8 +237ms
```

The above node/peer did response us with WhoAreYou message and we response back with an authentication message. However, handshare stops from then and then it's timed out.

**Comment by twoeths** [comment]
do you have any ideas @wemeetagain ?

**Comment by wemeetagain** [comment]
Not sure :thinking: I've also seen lots of immediate disconnections from peers we _do_ find.

**Comment by mpetrunic** [comment]
Lighthouse peers ban us for 30s after we send goodbye request

**Comment by mpetrunic** [comment]
So that might be disconnects

**Comment by twoeths** [comment]
This happens regularly even through I leave it hours before I restart so it's not a 30s thing.

One of the issue is https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/sync/reqResp/reqResp.ts#L68

On start, the getPeers() only returns peers which have connection while initially we have no connection so it returns no peer.

I tried to get all peers without the connections and do a connect/dial but got ECONNREFUSED error (even thru the peerStore already have multiaddrs for those peers as I can see ip address and port), don't know why.

**Comment by twoeths** [comment]
If we don't save ENR in `run.ts`, this issue does not happen and we can always detect peers upon a restart so it's always good with a fresh `enr.json` file.
This is what's logged for a fresh `enr.json`

```
  discv5:sessionService No session established, sending a random packet to: 98b7a0b9d86ab6d90f30a032bc96385b36d8019c644f39c2e235b48ca1f1ed42 on /ip4/54.212.201.2/udp/9000 +1ms
discv5:sessionService Sending authentication message: { type: 3, id: 734128736736639294n, distance: 255 } to node: 98b7a0b9d86ab6d90f30a032bc96385b36d8019c644f39c2e235b48ca1f1ed42 on /ip4/54.212.201.2/udp/9000 +14ms
discv5:sessionService Session established with node from updated: 98b7a0b9d86ab6d90f30a032bc96385b36d8019c644f39c2e235b48ca1f1ed42 +267ms
discv5:sessionService Sending request: { type: 1, id: 2104988989080359569n, enrSeq: 3n } to 98b7a0b9d86ab6d90f30a032bc96385b36d8019c644f39c2e235b48ca1f1ed42 on /ip4/54.212.201.2/udp/9000 +1m
discv5:sessionService Message received: NODES from: 98b7a0b9d86ab6d90f30a032bc96385b36d8019c644f39c2e235b48ca1f1ed42 on /ip4/54.212.201.2/udp/9000 +1ms
```

**Comment by twoeths** [comment]
This is what's logged for a modified `enr.json` which does *not* work:
```
discv5:sessionService No session established, sending a random packet to: 98b7a0b9d86ab6d90f30a032bc96385b36d8019c644f39c2e235b48ca1f1ed42 on /ip4/54.212.201.2/udp/9000 +1ms
discv5:sessionService Sending authentication message: { type: 3, id: 7161530636072610744n, distance: 251 } to node: 98b7a0b9d86ab6d90f30a032bc96385b36d8019c644f39c2e235b48ca1f1ed42 on /ip4/54.212.201.2/udp/9000 +2ms
discv5:sessionService Message timed out with node: 98b7a0b9d86ab6d90f30a032bc96385b36d8019c644f39c2e235b48ca1f1ed42 +210ms
```

We can see that the same node 98b7a0b9d86ab6d90f30a032bc96385b36d8019c644f39c2e235b48ca1f1ed42 did reply authentication message of a fresh`enr.json` but did not do that for the modified `enr.json`, so there's probably an issue with authentication message after we save to `enr.json`. 

The surprise thing is it does not always happen for every modified `enr.json` file. If I immediately restart my node, the `enr.json` is modified but it still can detects new peers. But it seems that if I leave my .altona folder for about 2h then restart, it can't detect new peers...

**Comment by twoeths** [comment]
I think I found the root cause, open an issue in discv5 https://github.com/ChainSafe/discv5/issues/72
