### ISSUE TITLE
CLI: genesisStateFile appears as undefined Option in CLI help instead of as a Command

### ISSUE THREAD

**Issue by ltfschoen** [ChainSafe/lodestar#1148]
**Describe the bug**

In these instructions https://chainsafe.github.io/lodestar/usage/local/, the command that's shown uses command  `--chain.genesisStateFile ./dev/genesis.ssz`, where the path of that file is relative to the root directory that you define with option `--rootDir`  (which is `./.lodestar` by default).

When you clone the latest 'master' branch and run `yarn run cli dev --help` it shows 
```
Command used to quickly bootstrap beacon node and validators

dev
  ...

Options:
  ...
  --undefined                   Genesis state in ssz-encoded format   [string]
```

Notice how it's missing the following, and just shows it as `--undefined` in the Options section, whereas I think it should instead be shown as a Command as shown below
```
chain
  --chain.genesisStateFile
```

**Expected behavior**

```
chain
  --chain.genesisStateFile    Genesis state file in ssz-encoded format. File location relative to Lodestar root directory.        [string] [ default: "" ]
```

**Steps to Reproduce**

1. Clone the latest Lodestart repo `git clone https://github.com/ChainSafe/lodestar`
2. Switch to a version of Node.js that's later than v12 (requirement of package.json) e.g. `nvm use 14.4.0`
3. Build from source `yarn install; yarn run build`
4. View CLI dev help `yarn run cli dev --help`
5. See error

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Version:
```
$ yarn run cli --version
0.9.0
```
 - Branch: master
 - Commit hash: 26a935ce7973c95d58570ef55c71ebc8a18bb61b

**Comment by dapplion** [comment]
Fixed in current master. Thanks for reporting!
