### ISSUE TITLE
Broken link to genesis file in instructions to connect to Witti testnet 

### ISSUE THREAD

**Issue by ltfschoen** [ChainSafe/lodestar#1151]
**Describe the bug**

I tried to follow the instructions here to run the Witti testnet https://chainsafe.github.io/lodestar/usage/witti/, but when i try to fetch the genesis file that they say to fetch here https://chainsafe.github.io/lodestar/usage/witti/#initialize-beacon-configuration with `wget https://github.com/goerli/witti/raw/master/lighthouse/genesis.ssz` it returns 404 broken link
```
ls @ ~/code/src/ltfschoen/lodestar - [master] $ wget https://github.com/goerli/witti/raw/master/lighthouse/genesis.ssz
--2020-07-13 19:52:29--  https://github.com/goerli/witti/raw/master/lighthouse/genesis.ssz
Resolving github.com (github.com)... 52.64.108.95
Connecting to github.com (github.com)|52.64.108.95|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/goerli/altona/raw/master/lighthouse/genesis.ssz [following]
--2020-07-13 19:52:29--  https://github.com/goerli/altona/raw/master/lighthouse/genesis.ssz
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 404 Not Found
2020-07-13 19:52:29 ERROR 404: Not Found.
```
**Expected behavior**

I expected it to download a "genesis.ssz" file, instead of returning a 404 not found

**Steps to Reproduce**

1. Go to https://chainsafe.github.io/lodestar/usage/witti/#initialize-beacon-configuration
2. Run in terminal `wget https://github.com/goerli/witti/raw/master/lighthouse/genesis.ssz`, as you're instructed to do
3. Observe a `404 Not Found` error.

**Desktop (please complete the following information):**
 - OS: OSX Mojave
 - Version: 0.9.0
 - Branch: master
 - Commit hash: 26a935ce7973c95d58570ef55c71ebc8a18bb61b

**Comment by 3xtr4t3rr3str14l** [comment]
hey there!  we have moved on to use the Altona testnet instead of the Witti testnet.  you can find our updated instructions here:
https://chainsafe.github.io/lodestar/usage/altona/

**Comment by q9f** [comment]
Altona config is currently broken, #1299

**Comment by dapplion** [comment]
Issue fixed with latest patches.
