### ISSUE TITLE
Prometheus and Grafana setup instructions to view Beacon Chain metrics

### ISSUE THREAD

**Issue by ltfschoen** [ChainSafe/lodestar#1152]
**Is your feature request related to a problem? Please describe.**

There's a Prometheus configuration, but no instructions on whether it works or not, or whether it works on "local" testnet, or only on "witti" testnet, and it doesn't mention what data it makes available (you have to search for it in the source code), and it doesn't mention how to visualise it (e.g. with Grafana)

**Describe the solution you'd like**

I'd like some Prometheus and Grafana setup instructions for viewing Beacon Chain metrics to be added to the documentation.

I just tried running a Local Testnet and Prometheus (without Docker) by running in two terminal windows:
- terminal 1: yarn run cli dev --dev.genesisValidators 8 --dev.reset
- terminal 2: ./scripts/prometheus --config.file="./prometheus.yml"

I then installed and ran Grafana https://grafana.com/docs/grafana/latest/installation/mac/ and configured Grafana by following these instructions https://prometheus.io/docs/visualization/grafana/#installing (e.g. setting the Prometheus Server URL to `http://localhost:9090/`). I then created a dashboard that used the Prometheus configuration that I'd set. It showed data, but I'm not sure where that was coming from , and I was recommended to check metrics starting with `beaconchain_` and `nodejs`.

<img width="811" alt="Screenshot 2020-07-13 at 7 21 34 pm" src="https://user-images.githubusercontent.com/6226175/87339686-42114780-c547-11ea-8fe0-794dd24e22ec.png">

I understand based on this file that metrics are emitted every 5s https://github.com/ChainSafe/lodestar/blob/master/prometheus.yml

When i run a "local" node, it doesn't output to the terminal anything about metrics. Whereas in the "witti" node docs https://github.com/ChainSafe/lodestar/blob/master/docs/usage/witti.md#run-a-beacon-node it shows that if you run a "witti" node it should output `[METRICS]          info: Starting metrics HTTP server on port 5000`

Also, in the code here https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/metrics/beacon.ts#L12 it shows the different metrics available, and their associated names (e.g. `beaconchain_peers`) https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/metrics/beacon.ts#L34

But if i add a Query and i enter that `beaconchain_peers` for the "Metric", it doesn't return anything

<img width="476" alt="Screenshot 2020-07-13 at 7 46 43 pm" src="https://user-images.githubusercontent.com/6226175/87340299-278b9e00-c548-11ea-8eda-7c5815faa654.png">

**Comment by 3xtr4t3rr3str14l** [comment]
hey!  sorry, thought i had posted this here, but we made a docs page to setup Prometheus/Grafana.  thanks for pointing this out!

https://chainsafe.github.io/lodestar/usage/prometheus-grafana/
