### ISSUE TITLE
Refactor beacon config param parsing in CLI

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1155]
We will want a way to override params, like in beacon run.
Especially important here is GENESIS_FORK_VERSION.
So the chain.params will need to be an input here.

The direction I've been thinking lately is to do something like:
- [x] create a IBeaconParams ssz type, `createIBeaconParams` to create IBeaconParams from a `Record<string, unknown>` / `Json` #1136 
- [x] Use it to help create yargs `Options` if needed. All Options are `type: "string"`, will be parsed using `createIBeaconParams`
- [x] Have a cli-wide params file. (should be copy-pastable from eg: https://github.com/eth2-clients/eth2-testnets/blob/master/shared/altona/config.yaml)
- [x] Have all lodestar cli commands rely on this separate config file - Likely _every_ command needs the same IBeaconParams.
- [x] First `lodestar-cli` bootup should require a config file, or have `lodestar init` to create it, or other similar behavior.

_Originally posted by @wemeetagain in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjgxMzExNjg4OnYy/pull_request_review_threads/discussion_

**Comment by 3xtr4t3rr3str14l** [comment]
just merged #1136

**Comment by 3xtr4t3rr3str14l** [comment]
#1136 resolves not only first bullet point, but also the second one regarding yargs `Options`
