### ISSUE TITLE
Remove ALL_FORKS from lodestar-params

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#1158]
I noticed in `/lodestar/packages/lodestar-params/src/interface.ts` that we have an object called ALL_FORKS, but this object is not in the mainnet or minimal configs (e.g. https://github.com/ethereum/eth2.0-specs/blob/dev/configs/mainnet/phase0.yaml)

Maybe we should remove ALL_FORKS so the interface and beacon chain params can be consistent and up-to-date with the spec/config?  Or move it somewhere else, if it's something we definitely need?  

Thoughts?

Related PR (where ALL_FORKS was created):
https://github.com/ChainSafe/lodestar/pull/843

**Comment by dapplion** [comment]
So `ALL_FORKS` should be removed to be on par with the spec? Searching master there are some uses in multiple lodestar packages.

**Comment by wemeetagain** [comment]
We will need somehting like `ALL_FORKS` to handle scheduled forks and for the scheduled forks API.
We should move `ALL_FORKS` out of `IBeaconParams`. 
Forks will likely require a new lodestar release and code changes.

**Comment by wemeetagain** [comment]
Remove `ALL_FORKS` for now. Revisit when scheduled forks become a thing.

**Comment by dapplion** [comment]
unstale

**Comment by dapplion** [comment]
ALL_FORKS is used in `processForkChanged()` in the beacon state transition function. What should happen with that function upon removing `ALL_FORKS`?

**Comment by wemeetagain** [comment]
No longer using `ALL_FORKS` to determine forking, rather, using `IBeaconConfig` to group fork info
