### ISSUE TITLE
Pubsub not started e2e error

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1160]
Seems like we broke something lately, seems like on random occasion  we get pubsub not started error.
I wonder how that happens. We should also at least catch those errors.
 
![image](https://user-images.githubusercontent.com/8836210/87516633-fe6d2980-c67d-11ea-98b9-d99537ee5f4b.png)

**Comment by wemeetagain** [comment]
Likely started happened from after #1117 Now we only start gossipsub after initial sync is finished.

**Comment by wemeetagain** [comment]
Should be resolved. Feel free to reopen if it continues
