### ISSUE TITLE
Dev command

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1180]
**Describe the bug**
Dev command seems to be broken, it just prints "0.10.0" or "0.10.2", need to investigate ...

**Comment by wemeetagain** [comment]
I think we can remove the dev command entirely. Going forward, we'll want to exercise the beacon and validator commands since those are intended to be used in production.
E2e tests can give us the functionality of the dev command.

**Comment by dapplion** [comment]
This issue was fixed with https://github.com/ChainSafe/lodestar/pull/1181.
Opening dev removal discussion in issue https://github.com/ChainSafe/lodestar/issues/1261.
