### ISSUE TITLE
genesisStateFile not being copied over to beacon.config.json during beacon init

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#1188]
**Describe the bug**

when i run `yarn run cli beacon init --template-config-file altona.json --chain.genesisStateFile=genesis.ssz --rootDir .altona` (or if I omit the cli parameter and include chain.genesisStateFile as `"genesisStateFile": "genesis.ssz",` in my altona.json), I don't see the genesisStateFile parameter copied over in the resultant beacon.config.json

**Expected behavior**

the genesisStateFile parameter should be copied over to the resultant beacon.config.json both when passed as a cli option and when specified in the altona.json

**Comment by dapplion** [comment]
@3xtr4t3rr3str14l Is this issue still happening in master? If resolved, please feel free to close it

**Comment by 3xtr4t3rr3str14l** [comment]
just tested.  it's still happening in master.  when I run `yarn run cli init --testnet medalla --genesisStateFile testGen.ssz` I would expect to see `testGen.ssz` in the beacon.config.json, but I do not.  Instead, I see the default was provided via the `--testnet` option

**Comment by 3xtr4t3rr3str14l** [comment]
the same happens when I run `yarn run cli init --genesisStateFile testGen.ssz` (the same as above, but without the `--testnet` option
