### ISSUE TITLE
strategy for splitting network agnostic code from nodejs / browser specific code

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1202]
I guess a bigger issue is figuring out a strategy for splitting network agnostic code from nodejs / browser specific code. We have done some work towards that end, eg: with a nodejs-specific libp2p bundle, but it there likely will be a need for better organization.

_Originally posted by @wemeetagain in https://github.com/ChainSafe/lodestar/pull/1192#discussion_r459113177_

**Comment by dapplion** [comment]
We can revisit this once adding p2p capabilities to the lightclient
