### ISSUE TITLE
validator graffiti 

### ISSUE THREAD

**Issue by ColinSchwarz** [ChainSafe/lodestar#1219]

**Comment by 3xtr4t3rr3str14l** [comment]
```
graffiti - 32 bytes for validators to decorate as they choose with no defined in-protocol use
```
(as specified for `BeaconBlockBody` here:
https://notes.ethereum.org/@djrtwo/Bkn3zpwxB?type=view#BeaconBlockBody)

Is this something that we should do inside the `validator` command of the cli or maybe in the `beacon` command of the cli? I see prylabs uses it as a validator param (https://docs.prylabs.network/docs/prysm-usage/parameters/#validator-parameters) while lighthouse uses it as a beacon node param (https://github.com/sigp/lighthouse/blob/21bcc8848d3009cc8116c356993c91f1c0e454ba/beacon_node/src/cli.rs#L249)

**Comment by mpetrunic** [comment]
Can be in both commands but validator should have priority. Beacon command param for graffiti is suppose to be default value if nothing is submitted
