### ISSUE TITLE
Update lodestar-params with medalla params

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#1224]
Once medalla testnet is live, we need to update `lodestar/packages/lodestar-params/src/presets/mainnet.yaml` and `lodestar/packages/lodestar-params/src/presets/mainnet.yaml` with the latest params from spec

mainnet (with diff from previous testnet) can be found here:
https://gist.github.com/q9f/941b2621214d05ef8759abde30e4f9ef

General medalla testnet info:
https://github.com/goerli/medalla/tree/master/medalla

**Comment by wemeetagain** [comment]
Resolved with #1242
