### ISSUE TITLE
CLI variables rename

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1226]
Change some variable names to a more descriptive name:
- `network.multiaddrs` to `network.localMultiaddrs`
- `network.bootnodes` to `network.bootMultiaddrs`

Make sure that its use in all components is changed consistently

**Comment by 3xtr4t3rr3str14l** [comment]
Can we also change `api` to not nest it's options within the `rest` subcategory?
Currently, we are required to configure `api` options like this:
```
"api": {
    "rest": {
      "enabled": true,
      "namespaces": ["beacon", "validator"],
      "host": "127.0.0.1",
      "port": 9596,
      "cors": {
        "origin": "*"
      }
    }
  },
```

but i think we should structure them like this:
```
  "api": {
    "enabled": true,
    "namespaces": ["beacon", "validator"],
    "host": "127.0.0.1",
    "port": 9596,
    "cors": {
      "origin": "*"
    }
  },
```

**Comment by mpetrunic** [comment]
It will be awkward if we introduce rpc or graphql at some point^^

**Comment by 3xtr4t3rr3str14l** [comment]
@mpetrunic yeah I see what you mean.  If that's something we think we will have in the future (or some other API type besides what we currently have), then might be worth leaving as is.

**Comment by dapplion** [comment]
All code in the `lodestar` subpackage expects that option type so it would be best to not change it.
