### ISSUE TITLE
Add network.discv5.enabled flag

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1227]
Add the enabled flag to https://github.com/ChainSafe/lodestar/blob/ef106219d8d15c6cfa0f863df3a7e55da43cc8ab/packages/lodestar/src/network/nodejs/bundle.ts#L70
May also require a change in `ChainSafe/discv5` https://github.com/ChainSafe/discv5/blob/master/src/libp2p/discv5.ts#L9

**Comment by dapplion** [comment]
Motivation:
https://github.com/ChainSafe/lodestar/blob/00012384f2fefe57805e368d815c6677214baf05/packages/lodestar-cli/src/testnets/altona.ts#L25-L29

**Comment by 3xtr4t3rr3str14l** [comment]
the ts-ignores still need to be removed when discv5 version bump happens that includes https://github.com/ChainSafe/discv5/pull/104

**Comment by dapplion** [comment]
@3xtr4t3rr3str14l Is the code ready now to remove those ts-ignores?

**Comment by 3xtr4t3rr3str14l** [comment]
yes, 

> @3xtr4t3rr3str14l Is the code ready now to remove those ts-ignores?

yes, i believe so.  discv5 was upgraded to 0.5.0 in mid-November with the changes from https://github.com/ChainSafe/discv5/pull/104

**Comment by 3xtr4t3rr3str14l** [comment]
i'm on it
