### ISSUE TITLE
Change CLI default root-dir

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1232]
**Is your feature request related to a problem? Please describe.**
The current default root-dir is `./.lodestar` in the current working directory when running `lodestar`.
Using a local root-dir has been convenient for development/debug purposes, but its not standard behavior for systemwide-installed programs.

**Describe the solution you'd like**
Brainstorm / implement a better default root-dir path. Some possible options:
- $HOME/lodestar
- Something following the XDG standard: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#basics
- ??

**Comment by dapplion** [comment]
+1 to follow the XDG standard. Otherwise, default to `$HOME/lodestar`

**Comment by dapplion** [comment]
unstale

**Comment by dapplion** [comment]
@wemeetagain If we implement this should there be any migration? How would it deal with existing DBs?

**Comment by wemeetagain** [comment]
IMO we shouldn't provide tooling (code) for this but rather add a migration guide markdown document that includes directions like:
```bash
# Move the lodestar directory to XYZ
mv .lodestar ~/XYZ
```
