### ISSUE TITLE
Regular Sync: some peers are out-of-sync

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1234]
**Describe the bug**
In my environment, I can sync to gossip parent blocks 5-6 times. However there are 1-2 times I cannot do that because we sent `beacon_block_by_range` requests to out-of-date peers. 
```
2020-07-26 21:56:28  [SYNC]             info: Requesting blocks from slot 194977 to slot 195131
2020-07-26 21:56:28  [NETWORK]       verbose: sending beacon_blocks_by_range request to 16Uiu2HAmUghihDaHutopxWPoxjUedJZBLVuuP1NBDq2LfpQZTnad requestId=3fb6e9d3489b0875, encoding=ssz_snappy
2020-07-26 21:56:28  [NETWORK]       verbose: sending beacon_blocks_by_range request to 16Uiu2HAm2BfJQmNSNdAtGfJLH1CyQKKRVr425uJgrSq9ps8TLJe2 requestId=c618c049d122bcee, encoding=ssz_snappy
...
2020-07-26 21:56:29  [NETWORK]       verbose: receive beacon_blocks_by_range response with 0 chunks from 16Uiu2HAmUghihDaHutopxWPoxjUedJZBLVuuP1NBDq2LfpQZTnad requestId=3fb6e9d3489b0875, encoding=ssz_snappy, body={"startSlot":194977,"step":1,"count":78}
2020-07-26 21:56:31  [NETWORK]       verbose: receive beacon_blocks_by_range response with 52 chunks from 16Uiu2HAm2BfJQmNSNdAtGfJLH1CyQKKRVr425uJgrSq9ps8TLJe2 requestId=c618c049d122bcee, encoding=ssz_snappy, body={"startSlot":195055,"step":1,"count":77}
```

Since the 1st peer above returned 0 chunk because it's not up to date, we cannot process any blocks. So we have to filter to up-to-date peers only.

There are 2 ways I can think of:
+ Filter based on headSlot of Status message, send status messages at init time of regular sync. This maybe does not work if peers have `headSlot` not equal to `currentSlot`
+ Find a way to keep peerIds of gossip blocks and just get peers based on that - but a peer's chain may not be up to date even it published gossip blocks

**Comment by twoeths** [comment]
Since `headSlot` in `Status` message is not a guarantee to help us find peers to get blocks up to `currentSlot`, I found that using `step` in `beacon_block_by_range` may help us (and that's probably what it's designed for)

Given 3 peers, we can query by interleaving way, assuming we want to get block 10 to 20 for regular sync:
Round 0
+ Peer 0: start_slot=10, step=3 => return 10,13,16,19
+ Peer 1: start_slot=11, step=3 => return 11,14 - this peer is out-of-sync because expected latest slot=20
+ Peer 2: start_slot=12, step=3 => return null - error querying this peer - timeout for example
=> bestPeer=peer has `max(lastSlot)`=peer 0

Round 1 - fallback
+ Query bestPeer with start_slot=17, step=3
+ Query bestPeer with start_slot=12, step=3

Then merge/sort blocks and return. In the case of missing blocks (some slots don't have blocks), it's addressed by Round 1.

**Comment by wemeetagain** [comment]
I don't think we should be relying _entirely_ on `beacon_block_by_range` in regular sync.
Regular sync is when we've synced up to (what we believe is) up to / past the finalized checkpoint. After that we don't yet have a linearized version of history, but instead have a tree. This is what we're tracking in our fork choice.

```
Genesis                         Finalized                  Head
                                        /------------------o
   o--------       ...       -------o--<
                                        \---<
                                             \------
```
We can retry requests from good peers, do some syncing by range, if it helps us get closer to the head, thats cool. But ultimately I don't think its what is intended.

I think a more robust and complete approach would have us using gossip + block by root to sync from the tips of the network backwards block by block to meet up with our current head.
This is what is what is meant by `a client MAY queue blocks for processing once the parent block is retrieved` from the spec, in validation of blocks w/o an existing parent block. If we send those blocks to the chain for processing, it may resolve the need to have a complex "regular sync" strategy at all.

**Comment by mpetrunic** [comment]
> I don't think we should be relying _entirely_ on `beacon_block_by_range` in regular sync.
> Regular sync is when we've synced up to (what we believe is) up to / past the finalized checkpoint. After that we don't yet have a linearized version of history, but instead have a tree. This is what we're tracking in our fork choice.
> 
> ```
> Genesis                         Finalized                  Head
>                                         /------------------o
>    o--------       ...       -------o--<
>                                         \---<
>                                              \------
> ```
> 
> We can retry requests from good peers, do some syncing by range, if it helps us get closer to the head, thats cool. But ultimately I don't think its what is intended.
> 
> I think a more robust and complete approach would have us using gossip + block by root to sync from the tips of the network backwards block by block to meet up with our current head.
> This is what is what is meant by `a client MAY queue blocks for processing once the parent block is retrieved` from the spec, in validation of blocks w/o an existing parent block. If we send those blocks to the chain for processing, it may resolve the need to have a complex "regular sync" strategy at all.

Tried that, you get banned quickly because you are spamming block by Root requests.

We actually do that if received block is less that 5 slots ahead

**Comment by wemeetagain** [comment]
> Tried that, you get banned quickly because you are spamming block by Root requests.

Can we spread out requests across our peers? Throttle requests to N / second / peer?
This seems like a good compliment to whatever forward-sync strategy we determine.

**Comment by wemeetagain** [comment]
This is an interesting resource: https://github.com/sigp/lighthouse/blob/master/beacon_node/network/src/sync/range_sync/range.rs
Look under "head chain sync"

**Comment by twoeths** [comment]
`beacon_block_by_range` should return blocks of the same chain up to head.

should we just select a best peer and issue `beacon_block_by_range` for it only?

**Comment by wemeetagain** [comment]
> should we just select a best peer and issue beacon_block_by_range for it only?

I think we should go that direction. Will be simpler and more in line with batch-processing, which we will eventually want to do.

**Comment by twoeths** [comment]
## Latest issue

Restore chain
```
2020-08-02 08:28:29  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x3bd4f8518971d022f01e60cff1fe542b4260662b4b23c9f35a152bf9c698fdc4, slot=237728, epoch=7429
2020-08-02 08:28:30  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x74332574cf13a236c57efc822a64686e899b0deb53a501014a4e6b4682965f76, slot=237732, epoch=7429
```

```
2020-08-02 08:29:33  [SYNC]          verbose: Regular Sync: Found best peer 16Uiu2HAm7NAPSL46rXBSmjZQKX8pvU99iRpQJNMDY3o89XUzZBrM, headSlot=241496
2020-08-02 08:29:33  [SYNC]             info: Regular Sync: Setting target newTargetSlot=237752
2020-08-02 08:29:33  [SYNC]             info: Regular Sync: Requesting blocks from slot 237733 to slot 237752
2020-08-02 08:29:34  [SYNC]             info: Imported blocks for slots: 237735,237738,237739,237740,237743,237744,237749,237750
```
not received "processedCheckpoint" because all of the received blocks already exists, meaning our `lastSlot` is greater than `headSlot` and when we start Regular Sync, we always start from `headSlot` -> we receive existing blocks in our chain -> not passed `packages/lodestar/src/chain/blocks/validate.ts` -> `processedBlock` not emitted -> Regular Sync suspended.

**Comment by twoeths** [comment]
with the latest master, we do emit `processedBlock` event when a block existed so this should not be an issue anymore
