### ISSUE TITLE
CLI flag documentation

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1238]
**Is your feature request related to a problem? Please describe.**
The lodestar docs have CLI usage pages, but nothing detailing the available CLI flags.

**Describe the solution you'd like**
We should have generated docs showing all available CLI options per command.
Teku does a good job of this here: https://docs.teku.pegasys.tech/en/latest/Reference/CLI/CLI-Syntax/

**Describe alternatives you've considered**
Direct users to run `--help` for option discovery.

**Comment by 3xtr4t3rr3str14l** [comment]
For any options that have missing descriptions, I will also add those to the corresponding cli options object.

**Comment by 3xtr4t3rr3str14l** [comment]
closed via #1241
