### ISSUE TITLE
Structured logs

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1249]
I know it was designed that way, I do think we should minimize nested structures when we can. 
I'm just trying to make our logs more machine readable, and handling arbitrary `Json` IMO is part of the process, especially for debug or verbose-level logs.

IMO, in an ideal setting, we would output logs to JSON-LD format in production, or with a certain "productionized logs" flag.
We would still have a pretty-printer, like in this file, for daily use, but the underlying representation is simply `Json`. This will allow us to easily ingest logs into log aggregators and do more advanced analytics on logs. This is how logging will be used in production settings.
Logs that look like `[CHAIN] "Attestation ${X} processed at epoch ${Y}"` should be refactored into `[CHAIN] "processed attestation", {attestationRoot, epoch}`. Which has a machine representation of `{timestamp: 9999999, module: "chain", message: "processed attestation", attestationRoot, epoch}`

_Originally posted by @wemeetagain in https://github.com/ChainSafe/lodestar/pull/1240#discussion_r461631285_

**Comment by dapplion** [comment]
Could all mantainers of Lodestar agree or disagree to 
- consistently follow this proposal
- not follow this proposal

Otherwise, we would continue our current state of different log styles all over the place
