### ISSUE TITLE
Consider removing CLI dev command

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1261]
I think we can remove the dev command entirely. Going forward, we'll want to exercise the beacon and validator commands since those are intended to be used in production.
E2e tests can give us the functionality of the dev command.

_Originally posted by @wemeetagain in https://github.com/ChainSafe/lodestar/issues/1180#issuecomment-665983603_

**Comment by mpetrunic** [comment]
I tend to use dev command to quickly setup devnet for trying out api or various sync experiments.
E2e tests doesn't help with that as I need to wait for justified epoch every time

**Comment by dapplion** [comment]
Closing since it has good use cases
