### ISSUE TITLE
Remove obsolete CLI flags - eth1

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1302]
**Describe the bug**
Eth1 deposit contract & chain id are now used from IBeaconParams, but there are CLI flags still hanging.

**Expected behavior**
Remove the obselete CLI flags

**Comment by dapplion** [comment]
Which options specifically are still hanging?

**Comment by 3xtr4t3rr3str14l** [comment]
@wemeetagain bump

**Comment by wemeetagain** [comment]
deposit contract & chain id
