### ISSUE TITLE
Brittle VC<=>BN interaction

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1326]
2020-08-04 03:51:41  []                error: Failed to obtain genesis time Error: undefined hitting the same now
restarting the validator client fixed it
I think that if the VC can't reach the beacon node at that moment, it gets that error

See https://discordapp.com/channels/593655374469660673/593655641445367808/740055094908944435

**Comment by mpetrunic** [comment]
It seems like we don't catch error when polling so it probably breaks our interval check
