### ISSUE TITLE
Stop fetching unnecessary eth1 proposing data

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1329]
**Describe the bug**
This is before genesis time, we pass eth1 block that form eth2 genesis and keep fetching eth1 block to save proposing data
```
2020-08-04 15:20:00  [ETH1]          verbose: Processing proposing data of eth1 block 3154952
2020-08-04 15:20:02  [ETH1]          verbose: Processing proposing data of eth1 block 3154953
2020-08-04 15:20:03  [ETH1]          verbose: Processing proposing data of eth1 block 3154954
2020-08-04 15:20:05  [ETH1]          verbose: Processing proposing data of eth1 block 3154955
2020-08-04 15:20:06  [ETH1]          verbose: Processing proposing data of eth1 block 3154956
2020-08-04 15:20:08  [ETH1]          verbose: Processing proposing data of eth1 block 3154957
2020-08-04 15:20:08  [ETH1]          verbose: Processing 1 deposit events of eth1 block 3154958
2020-08-04 15:20:10  [ETH1]          verbose: Processing proposing data of eth1 block 3154958
2020-08-04 15:20:10  [ETH1]          verbose: Processing 1 deposit events of eth1 block 3154959
2020-08-04 15:20:11  [ETH1]          verbose: Processing proposing data of eth1 block 3154959
2020-08-04 15:20:13  [ETH1]          verbose: Processing proposing data of eth1 block 3154960
2020-08-04 15:20:14  [ETH1]          verbose: Processing proposing data of eth1 block 315496
```

**Expected behavior**
Need to base on periodStart
```
export function votingPeriodStartTime(config: IBeaconConfig, state: TreeBacked<BeaconState>): number {
  const eth1VotingPeriodStartSlot = state.slot -
    state.slot % (config.params.EPOCHS_PER_ETH1_VOTING_PERIOD * config.params.SLOTS_PER_EPOCH);
  return computeTimeAtSlot(config, eth1VotingPeriodStartSlot, state.genesisTime);
}
```
and how we query eth1Data to include in Block body:
```
const validEth1Data = (await db.eth1Data.values({
    gte: periodStart - config. params.SECONDS_PER_ETH1_BLOCK * config.params.ETH1_FOLLOW_DISTANCE,
    lte: periodStart - config. params.SECONDS_PER_ETH1_BLOCK * config.params.ETH1_FOLLOW_DISTANCE * 2,
  })).filter((eth1Data) => eth1Data.depositCount >= state.eth1Data.depositCount);
```

to fetch/store eth1Data only when needed

**Comment by twoeths** [comment]
so based on `max(current_time, config.params.MIN_GENESIS_TIME)`, we calculate `periodStart` and minimum eth1BlockNumber for proposing data to get block/proposing data or not

**Comment by dapplion** [comment]
@tuyennhv Is this related or duplicated of https://github.com/ChainSafe/lodestar/issues/1354 ?

**Comment by twoeths** [comment]
@dapplion this happens at pregenesis time while the other one happens after genesis

**Comment by twoeths** [comment]
@dapplion  you're right, it has same root cause

**Comment by dapplion** [comment]
@tuyennhv if I understand the issue correctly: After genesis, blocks with a timestamp prior to
```
periodStart - config. params.SECONDS_PER_ETH1_BLOCK * config.params.ETH1_FOLLOW_DISTANCE * 2
```
are useless right?

But without having access to state, can you compute `periodStart`? Would it be possible just by having access to the clock to compute the lowest possible `periodStart` given the current time?

**Comment by twoeths** [comment]
@dapplion yes and yes, you are all right :D

The main point is not to query useless blocks at pregenesis time and after genesis time.
+ Pregenesis time: as described in the issue description, we formed genesis state already but keeps querying eth1 block while waiting for genesis time (due to GENESIS_DELAY). I believe it's not an issue anymore.
+ After genesis: as you said, we don't need blocks before `periodStart - config. params.SECONDS_PER_ETH1_BLOCK * config.params.ETH1_FOLLOW_DISTANCE * 2`. Also, when we are syncing, we don't need to query eth1 block to form eth1 data too.

**Comment by dapplion** [comment]
Got it. In the current `Eth1ForBlockProduction` the constructor has no access to state
https://github.com/ChainSafe/lodestar/blob/16e88384332ce3074da00fdba14d50405a432072/packages/lodestar/src/eth1/eth1ForBlockProduction.ts#L36-L42

How do you think would be the nicest way to have access to `periodStart` or the state to compute it at the constructor of `Eth1ForBlockProduction`?

**Comment by twoeths** [comment]
I think we can use `getGenesisTime()` from chain and `currentSlot` from clock  instead of a state to calculate `periodStart`   at the constructor of `Eth1ForBlockProduction`.

**Comment by dapplion** [comment]
Once we get `periodStart` what range of blocks do you start to query from? The client should guess a block number from the lower-bound timestamp `periodStart`?

**Comment by dapplion** [comment]
Is this an optimization worth pursuing or too niche?

**Comment by dapplion** [comment]
> Is this an optimization worth pursuing or too niche?

Too niche
