### ISSUE TITLE
Validator client expects secrets without 0x prefix

### ISSUE THREAD

**Issue by dangerousfood** [ChainSafe/lodestar#1348]
Validator client expects secrets without a 0x prefix but importing keys prefixes secrets file with 0x
<img width="788" alt="Screen Shot 2020-08-04 at 10 11 06 PM" src="https://user-images.githubusercontent.com/4099038/89368740-df245380-d6a1-11ea-8c50-d00bdebee831.png">

**Comment by dapplion** [comment]
What version commit of Lodestar are you running? This issue should be fixed by https://github.com/ChainSafe/lodestar/pull/1332

**Comment by dapplion** [comment]
Issue fixed by #1332. Please re-open if it happens again, thanks for reporting!
