### ISSUE TITLE
Dockerizing Lodestar

### ISSUE THREAD

**Issue by Mikerah** [ChainSafe/lodestar#135]
In order to use some of the tools that WhiteBlock provides, we will need to get Lodestar to a point in which we can dockerize it.

Here are examples of the format of the docker file for blockchain clients that WhiteBlock provides:
https://github.com/zscole/blockchain-dockerfiles

CC'ing @zscole

**Comment by zscole** [comment]
[Try this out.](https://github.com/zscole/blockchain-dockerfiles/blob/master/ethereum/lodestar/Dockerfile)
