### ISSUE TITLE
Node v12- v14 support

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1370]
**Describe the bug**
Lodestar does not work, either hangs, or hits errors when using newer versions of node.

**Expected behavior**
Lodestar runs flawlessly on newer versions of node

**Steps to Reproduce**
Install node v12.13.x, v13, v14
run the beacon chain

**Context**
See https://discordapp.com/channels/593655374469660673/593655641445367808/741637064810037258
https://github.com/ChainSafe/lodestar/issues/1320

**Comment by dapplion** [comment]
Could we recap in this issue the specific errors or reasons why Lodestar breaks in higher versions?

- Issue fixed downgrading to Node v12 https://github.com/ChainSafe/lodestar/issues/1320: `TypeError: Cannot perform %TypedArray%.prototype.set on a detached ArrayBuffer`

**Comment by wemeetagain** [comment]
v12, later minor versions: Lodestar hangs on boot
v14, detached Arraybuffer error

**Comment by wemeetagain** [comment]
I just tried running off latest master with v12.18.3, didn't have any problems. Can anyone else confirm?

**Comment by dapplion** [comment]
We should revisit this. It would be a valuable experiment to try to the current release in Node v14 and see what happens

**Comment by dapplion** [comment]
I've pushed a branch running the sim tests with Node 10,11,12,13,14,15 https://github.com/ChainSafe/lodestar/runs/2138730025 and the results are
- 10: :heavy_multiplication_x: js-libp2p declares Node >= v12 in the package.json
- 11: :heavy_multiplication_x: js-libp2p declares Node >= v12 in the package.json
- 12: :heavy_check_mark: 
- 13: :heavy_check_mark: 
- 14: :heavy_check_mark: 
- 15: :heavy_check_mark: 

I've also run the Docker-ized setup with the `node:14-alpine` image and works fine.

If you can please test Lodestar in more environments with v14 and we can consider lifting the restriction

**Comment by wemeetagain** [comment]
Woohoo! I guess the issues we were seeing have just vanished from dependencies being updated over time?

Definitely time to move to v14 once we can: https://nodejs.org/en/about/releases/
v12 no longer 'active', just in maintenance. v14 is the new active LTS.
