### ISSUE TITLE
Benchmarking strategy

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1377]
Once Lodestar is stable to sync to Medalla it would be the right time to have a benchmarking framework in place

Early work has already added a baseline https://github.com/ChainSafe/lodestar/pull/344 and issues https://github.com/ChainSafe/lodestar/issues/303, https://github.com/ChainSafe/lodestar/issues/302, https://github.com/ChainSafe/lodestar/issues/301 track adding benchmarks epoch processing, ssz and block processing.

I'm opening a new unique issue to discuss first how to tackle benchmarking specifically. 
- what's the best way or reporting it,
- do we want to compare different implementations of ours, 
- compare against other clients numbers,
- what has the most priority, 
- is it possible to run these modules in isolation, etc.

**Comment by dapplion** [comment]
@tuyennhv Your performance tests are a great step in this direction. Do you think it's possible to add them as part of CI and at least produce a report that can be reviewed if necessary?

**Comment by twoeths** [comment]
> @tuyennhv Your performance tests are a great step in this direction. Do you think it's possible to add them as part of CI and at least produce a report that can be reviewed if necessary?

yeah surely we can do that, there are 2 things:
+ investigate/improve the performance test data there since it does not match the current situation of pyrmont
+ to get a correct benchmark, we may need to run all tests several time and get the average run time

**Comment by dapplion** [comment]
We have a very solid benchmarking strategy now
