### ISSUE TITLE
Ensure VC knows of BN syncing status

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1380]
**Describe the bug**
See https://discordapp.com/channels/593655374469660673/593655641445367808/742254419156009072

The validator never realizes that the beacon node is still syncing. Leads to confusing logs and beacon node errors.

**Expected behavior**
Validator API responses are tailored / conditional on syncing status
Validator is aware of syncing status

**Comment by twoeths** [comment]
this is related to #1391 : node is syncing and validator checks attester duties and we have to process a lot of slots.
