### ISSUE TITLE
Lack of random subnet subscription

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1382]
**Describe the bug**

We don't track how many active validators are attached to node so we are always to subscribed to one random subnet.

**Expected behavior**

Use validator duties or attestation publish to track how many active validators we have and subscribe to appropriate number of random subnets.

**Steps to Reproduce**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Version: 
 - Branch: 
 - Commit hash:

**Comment by twoeths** [comment]
unstale
