### ISSUE TITLE
Refactor Sync onUnknownBlockRoot

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1388]
The current approach uses a while and maybe prone to infinite loops as reported by @wemeetagain.
https://github.com/ChainSafe/lodestar/blob/096ea27a9dd12b1db5fded62b0cc9688780e86c4/packages/lodestar/src/sync/sync.ts#L171-L174

----

oh yeah, because someone changed peerBalalncer to loop around. I changed that in regular sync v2.
So we have two options, either reset RoundRobinArray to return null if all peers are discarded or reduce maxAttempts here to this.getPeers().length x 2 (so we try each peer twice).

if you have 10 peers and block doesn't exists this will surely make you banned from those 10 peers

_Originally posted by @mpetrunic in https://github.com/ChainSafe/lodestar/pull/1378_

**Comment by mpetrunic** [comment]
unstale

I think it's resolves with #1655 cc @tuyennhv

**Comment by 3xtr4t3rr3str14l** [comment]
can this issue be closed?

**Comment by dapplion** [comment]
Yeah
