### ISSUE TITLE
Fork choice: Block slot N is not on the same chain

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1392]
**Describe the bug**
![](https://cdn.discordapp.com/attachments/593655641445367808/742906989796917308/unknown.png)
Cannot progress the chain after this

**Comment by twoeths** [comment]
this is duplicate to #1381 , does he run latest master?

one thing to note is once we get the issue, we cannot recover and have to start sync from scratch.

**Comment by wemeetagain** [comment]
Closing this
