### ISSUE TITLE
discussion: global precommit hook for eslint via husky

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#1414]
I'm curious if we can add a precommit hook for `yarn run lint` in lodestar via this package husky.  Is this something that we would want to have implemented in the repo?  Or do people think this is annoying?

Here's an example of the usage via husky here (which hooks in directly to the package.json scripts section):
https://medium.com/netscape/git-hooks-with-husky-8b98f2556363

**Comment by wemeetagain** [comment]
Closing in favor of individual dev git hooks
