### ISSUE TITLE
Use a more descriptive way to communicate different opt modes of the state transition fn

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1421]
It will provide better readability than the current approach
```ts
fn(true, false, true)
```

Inspired by Lighthouse's 
```rust
/// The strategy to be used when validating the block's signatures.
pub enum BlockSignatureStrategy {
    /// Do not validate any signature. Use with caution.
    NoVerification,
    /// Validate each signature individually, as its object is being processed.
    VerifyIndividual,
    /// Verify all signatures in bulk at the beginning of block processing.
    VerifyBulk,
}
```
https://github.com/sigp/lighthouse/blob/b73c497be2bf70715327654eb3bf5ff4df9aaab8/consensus/state_processing/src/per_block_processing.rs#L41

**Comment by wemeetagain** [comment]
I think we could/should convert the `fn(..., true, false, false)` into
`fn(..., {verifyStateRoot: true, verifyProposer: true, verifySignatures: true})`

I don't think the above `BlockSignatureStrategy` behavior should be handled by our `lodestar-beacon-state-transition` code, but rather by the direct consumer, eg: a [`ChainProcessor`](https://hackmd.io/jS7QMXR2Q4Os-JS-ZFHBAQ?view#Chain-Processor) module. We would be able to determine the signature strategy based on the "job" metadata and whether the processor receives a single block or a chain segment.

**Comment by dapplion** [comment]
named arguments would work too!
