### ISSUE TITLE
Validate GOSSIP_MAX_SIZE on published messages

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#1426]
As per the p2p spec (https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/p2p-interface.md#topics-and-messages):

```Each gossipsub message has a maximum size of GOSSIP_MAX_SIZE. Clients MUST reject (fail validation) messages that are over this size limit. Likewise, clients MUST NOT emit or propagate messages larger than this limit.```

As far as I can tell, we are only checking for GOSSIP_MAX_SIZE on incoming messages, but we don't do it for outgoing messages.  We should be doing both.

**Comment by wemeetagain** [comment]
All published gossip messages are validated by current ssz limits
