### ISSUE TITLE
Change default level for profiling logs

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1436]
In winston logger, `logger.profile`, if level is not explicitly set, set to verbose.

**Edit:**
Log profiling logs to verbose, not info.

**Comment by dapplion** [comment]
What is the reasoning for it? The default people expect is `info` when not setting a specific level

**Comment by mpetrunic** [comment]
Makes no sense to clutter logs with performance logs?

Its not meant for regular users

**Comment by dapplion** [comment]
At what level are performance logs logged to? Our current default is info?

**Comment by mpetrunic** [comment]
Currently, defaults to info, but it should default to verbose. I think something like this inside WinstonLogger:
`this.winston.profile(name, {level: LogLevel.verbose})`

**Comment by dapplion** [comment]
Not necessary since we don't use profile in anywhere else than tests
