### ISSUE TITLE
Bring back type checking in CI

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1441]
cc @wemeetagain @tuyennhv Are we intentionally not running check types in ci anymore?

@mpetrunic I prefer bringing it back, it was removed when we optimize CI last time as I remember, need to check with @wemeetagain

_Originally posted by @tuyennhv in https://github.com/ChainSafe/lodestar/pull/1431#issuecomment-679028782_

**Comment by wemeetagain** [comment]
We already check types when we build
