### ISSUE TITLE
Validator timing out block waiting in tests

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1446]
![image](https://user-images.githubusercontent.com/8836210/91169293-5c5a4b80-e6d7-11ea-847f-7872a5e0a059.png)

From logs it would seem that block came in time. It could be because short slot time, so it timesout before it gets deserialized and checked

**Comment by dapplion** [comment]
@wemeetagain: "It's real! Investigate more"

**Comment by mpetrunic** [comment]
unstale

Side note: gonna update to new events soon which should be lighter and faster which might resolve this isuees

**Comment by dapplion** [comment]
@mpetrunic Is this still an issue?

**Comment by mpetrunic** [comment]
No idea. I guess not
