### ISSUE TITLE
Check peer liveness

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1448]
Goal: remove peers that timeouts often

- add peer liveness check service:
   - periodically send ping request to peers
   - store ping responses in peer store metadata book
   - disconnect peers not responding to ping

Additional measures if those are timeouts only on block by range requests (my suspicion that these are shut down peers that aren't detected on libp2p side).

**Comment by dapplion** [comment]
Can you ping peers as much as you want without that affecting your peer score?

**Comment by mpetrunic** [comment]
Depends on client, I don't think we should spam it every few seconds though

**Comment by mpetrunic** [comment]
closed with #1428
