### ISSUE TITLE
Start from Weak Subjectivity State

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1451]
**Describe the solution you'd like**
Lodestar should be able to boot from a trusted BeaconState that is not genesis. See Weak Subjectivity doc for motivation.

**Additional context**
https://notes.ethereum.org/@adiasg/weak-subjectvity-eth2

**Comment by wemeetagain** [comment]
This should be ready for mainnet launch.

**Comment by twoeths** [comment]
So I suppose this helps save a lot of time for Initial Sync.

Does this include calculating Weak Subjectivity Checkpoint States and export it somewhere through Rest api for example?

**Comment by wemeetagain** [comment]
no, i think storage/retrieval should be tackled separately

**Comment by wemeetagain** [comment]
#1455 updates chain initialization, tweaks `chain.initForkChoice` and others, will be helpful for this
