### ISSUE TITLE
Limit state count in StateContextCache

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1456]
**Is your feature request related to a problem? Please describe.**
Memory exhaustion occurs in periods w/o finality, mostly from many states / epoch ctxs stored in the StateContextCache.

**Describe the solution you'd like**
We should prune the StateContextCache when it gets past a certain size. (pruning the oldest states first, perhaps with a few exceptions)

This likely must be done in tandem with two additional features:
- state recreation - when pruned states are requested, they must be recreated from most recent available state. We can walk the fork choice block dag to retrieve ancestor state roots / block roots.
- checkpointed states - replaying many blocks across many epochs to recreate a state may be "too slow". We should keep 1 state per N epochs per fork either in memory or on disk.

**Comment by mpetrunic** [comment]
closed with #1494
