### ISSUE TITLE
Attestations should be weighted by fc justified state balances

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1457]
**Describe the bug**
According to the spec https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/fork-choice.md#get_latest_attesting_balance
Attestations should be weighted by the balance at the justified state. Currently we're using the balance at the target state.

**Expected behavior**
Attestations should be weighted by the balance at the justified state.
Possibly wait until https://github.com/ChainSafe/lodestar/tree/cayman/separate-fork-choice/packages/lodestar-fork-choice is ready. In this implementation, attestations are fed to fork choice w/o weights, and all validator weights are updated at once whenever the justified state changes.

**Steps to Reproduce**
See https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/chain/attestation/processor.ts#L60
which uses the state fetched here: https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/network/gossip/utils.ts#L101

**Comment by dapplion** [comment]
unstale

**Comment by mpetrunic** [comment]
closed via #1702
