### ISSUE TITLE
Phase1 Params + Types

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1458]
**Is your feature request related to a problem? Please describe.**
If we want to prototype any phase1-related work, we will need the new phase1 params and types.
Ph1 params only add additional params.
Ph1 types, on the other hand, both extend existing types and add additional types.

Whatever solution we choose, we should be mindful of backwards compatibility.

**Describe the solution you'd like**
One solution would be to namespace our types by phase:
```typescript
import {phase0, phase1} from "@chainsafe/lodestar-types";
const v: phase0.Validator = {...};
const vv: phase1.Validator = {...};
```
Every extended type would simply be a new type definition, and we would be able to retain all existing types. All untouched types can 

The config would be similarly namespaced:
```typescript
import {config} from "@chainsafe/lodestar-config";
config.types.phase1.Validator.toJson({...});
```

**Describe alternatives you've considered**
- Separate repos for different phases
- Rename types to include phase in the name eg: Phase1Validator or ValidatorPhase1

**Additional context**
See https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase1/beacon-chain.md

**Comment by dapplion** [comment]
With this approach
```ts
const v: phase0.Validator = {...};
const vv: phase1.Validator = {...};
```
will the code be working for both phases? I imagine there will be a lot of overlapping code between phases

**Comment by wemeetagain** [comment]
For now, keep phase1 types in `config.types.phase1`. Keep phase0 types as-is.

**Comment by dapplion** [comment]
unstale
