### ISSUE TITLE
Prune attestation target checkpoint states

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1459]
- once per epoch prune attestation target checkpoint states
- use clean task

https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/db/api/beacon/stateContextCheckpointsCache.ts

**Comment by dapplion** [comment]
unstale

**Comment by dapplion** [comment]
Could this be implemented now or is it blocked by something else?

**Comment by twoeths** [comment]
this class was changed in Sep 14 to have auto-pruned and prune by finalized checkpoint so we don't have to implement it anymore.
