### ISSUE TITLE
Track peer block provider score

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1460]
- peer scores should be stored in peerstore metabook
- we can have something simple to start:
   - every peer starts with score 1
   - every block_by_root or block_by_range successfully requests adds 0.1
   - every bad response or response timeout reduces score by 0.2
- in sync sort peers by score and take best N

Later on we can add more complex stuff like score decay over time so we give peers another chance after some time etc.

**Comment by wemeetagain** [comment]
```typescript
interface ScoreTracker {
  addScore(peer: string, score: ScoreEnum): void;
}
```
