### ISSUE TITLE
[Inital sync] submit blocks for processing as received to reduce wait time

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1461]

**Comment by twoeths** [comment]
I'm attaching the proposal I had last time, feel free to modify or proposal another one

![Screen Shot 2020-08-28 at 16 33 50](https://user-images.githubusercontent.com/10568965/91546228-51f4b780-e94c-11ea-9456-da37976a89a8.png)

**Comment by mpetrunic** [comment]
My point was not to wait for entire range to be fetched (if we have block whos parent is our head, pass entire chunk immediatelly, otherwise buffer them).

**Comment by twoeths** [comment]
so ignore the above diagram, it's a different strategy

**Comment by mpetrunic** [comment]
unstale

**Comment by dapplion** [comment]
@tuyennhv Is this already implemented in your ORAsync?

**Comment by twoeths** [comment]
this goes with the current initial sync strategy. If we go with the new ORA sync I guess it's even better.

**Comment by dapplion** [comment]
@tuyennhv So can we close this issue?

**Comment by twoeths** [comment]
closing this as we'll go with the new strategy anyway in https://github.com/ChainSafe/lodestar/issues/1921
