### ISSUE TITLE
Consider doing BLS ops is a worker thread

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1463]
BLS ops are currently very expensive. Research if it's worth it to offload some ops to a worker thread.
Pros:
 - BLS is currently synchronous, so it can block and delay time-sensitive operations
 - Consider validating deposits beforehand in group and storing the result to be consumed by the state transition.
Cons:
 - State transition function would have to become async.
 - With native bindings, the improvements might be enough.

**Comment by wemeetagain** [comment]
A few more thoughts:
- Offloading bls to a worker may be useful when we're doing batch verification too
- If we prevalidate deposits, we won't _need_ to make state transition function async, we will likely run batch verification as a pre-state transition step.
- Not all bls ops _need_ to be worker-ized

**Comment by dapplion** [comment]
unstale

**Comment by dapplion** [comment]
We have to wait to safely thread BLST https://github.com/supranational/blst/issues/64#issuecomment-798160680

However it would be valuable to start prototyping with WASM

**Comment by dapplion** [comment]
Implemented in https://github.com/ChainSafe/lodestar/pull/2328
