### ISSUE TITLE
Block state transition in worker thread

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1464]
Currently the state transition is a synchronous function, this leads to problems when many epochs are processed at once, since we cannot perform any other tasks (eg: respond to network requests).

Create a worker thread that will process the state transition if block.message.slot - state.slot > MAX_SYNC_SLOTS.

**Comment by dapplion** [comment]
After introducing `await sleep(0)` statements between state transition fn runs we can survive as a stable node in both Mainnet and Pyrmont. It is very unlikely that we implement this until we refactor how we our TreeBacked / SSZ infra works. Closing for now let's revisit once that happens
