### ISSUE TITLE
Track open handles on close

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1466]
Currently, the beacon node hangs on close because several handles are still open. This is happening because some of our modules to not exit cleanly. (Either event handlers, open promises, etc)

We should use `wtf-node` or similar to track open handles, document all open handles, and ensure we're closing everything properly.

**Comment by dapplion** [comment]
Are all open handlers closed for good on multiple modes of operation of the CLI?

**Comment by mpetrunic** [comment]
probably not, it got autoclosed when I've dragged pr into closed column

**Comment by 3xtr4t3rr3str14l** [comment]
it's been a long time since i've ran `wtf-node` on the codebase, but i guess this isn't an issue anymore since we aren't using `yarn` to run the beacon node anymore?

**Comment by wemeetagain** [comment]
We rearranged how the node is started/stopped. No longer a problem, we have a clean stop.
