### ISSUE TITLE
Harden API to User Input

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1468]
The api code is very ... optimistic with user input. Each endpoint needs to sanitize input and more readily throw errors on invalid data.

**Comment by mpetrunic** [comment]
Should we maybe break this down into issue for each endpoint adding constraints it should check?

**Comment by 3xtr4t3rr3str14l** [comment]
@mpetrunic i think that's a good idea.  just FYI, i already added some validation for the blocks and attestations part of the api so far in #1709

**Comment by dapplion** [comment]
> Should we maybe break this down into issue for each endpoint adding constraints it should check?

@mpetrunic Would it make sense to ask a checklist of validations to use somewhere (this issue for a lack of a better place) of others to take on the task?

**Comment by mpetrunic** [comment]
Sorry, not sure I understand your question?

**Comment by dapplion** [comment]
API respects spec schema for input arguments
