### ISSUE TITLE
Develop a BeaconBootnode class

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1469]
`BeaconNode` start sequence makes network not start until genesis. Bootnode requires a different start sequence so develop a parallel class specific for bootnode needs

- [ ] Research what other teams are doing with bootnodes
- [ ] Make sure this is the optimal solution to solve this

From https://github.com/ChainSafe/lodestar/issues/1216

@wemeetagain Can you spec and select what functionality should be included? And if it needs some extra non-existing features.

**Comment by dapplion** [comment]
unstale

**Comment by 3xtr4t3rr3str14l** [comment]
@wemeetagain @dapplion is this something that has been spec'd out any further since this issue was created?

**Comment by dapplion** [comment]
No but it should be done if it's not too time-consuming

**Comment by dapplion** [comment]
@wemeetagain Should we close this?
