### ISSUE TITLE
Implement Slashing Protection Import/Export

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1471]
**Is your feature request related to a problem? Please describe.**
There's a standard format for slashing protection for importing validators. We should implement this so that we may safely migrate lodestar validators to other implementations, and vice-versa.

**Describe the solution you'd like**
Implement the standard described here: https://hackmd.io/@sproul/Bk0Y0qdGD
and expose via cli

**Additional context**
relevant lighthouse PR - https://github.com/sigp/lighthouse/pull/1544

**Comment by dapplion** [comment]
unstale
