### ISSUE TITLE
Add fork choice tests

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1472]
**Is your feature request related to a problem? Please describe.**
A more rigorous fork choice test suite may uncover lurking bugs and provide us more confidence of the correctness of our code.

**Describe the solution you'd like**
Add the tests found here: https://github.com/ethereum/eth2.0-spec-tests/issues/17
to the spec-tests package so they may be run along with other spec tests in CI

**Comment by twoeths** [comment]
waiting for the tests to be merged to the official eth2.0-spec-tests npm package

**Comment by dapplion** [comment]
unstale

**Comment by dapplion** [comment]
> waiting for the tests to be merged to the official eth2.0-spec-tests npm package

@tuyennhv have those been merged already?

**Comment by twoeths** [comment]
@dapplion it's not officially merged yet, still in some personal branches

**Comment by dapplion** [comment]
> @dapplion it's not officially merged yet, still in some personal branches

@tuyennhv  Could you link those branches here to track them?

**Comment by twoeths** [comment]
They stay in https://github.com/txrx-research/eth2.0-spec-tests/tree/fork_choice_integration_tests_v012_2/tests/minimal/phase0/fork_choice/integration_tests and https://github.com/txrx-research/eth2.0-spec-tests/tree/fork_choice_integration_tests_v012_2_optional_checks/tests/minimal/phase0/fork_choice/integration_tests

I'm not sure the difference between them.

**Comment by dapplion** [comment]
Thanks! Are other clients using this tests?

**Comment by twoeths** [comment]
I'm not sure but guess they not yet to do since it hasn't become official yet

**Comment by 3xtr4t3rr3str14l** [comment]
unstale

**Comment by dapplion** [comment]
> I'm not sure but guess they not yet to do since it hasn't become official yet

@tuyennhv What's the current status?

**Comment by twoeths** [comment]
> > I'm not sure but guess they not yet to do since it hasn't become official yet
> 
> @tuyennhv What's the current status?

it's still not merged to the official spec tests

**Comment by twoeths** [comment]
so after https://github.com/ethereum/eth2.0-specs/pull/2202 , `get_head` test format is available at https://github.com/ethereum/eth2.0-specs/tree/master/tests/formats/fork_choice

still don't see the tests in `eth2.0-spec-tests` repository.

**Comment by wemeetagain** [comment]
fork choice tests should now be available in our downloaded tests with the update to v1.1.0-alpha.3 :100:

**Comment by dapplion** [comment]
Close after adding specs for Altair. Are those ready @tuyennhv ?

**Comment by twoeths** [comment]
@dapplion  I think we do have forkchoice spec for `merge` but not for `altair`

**Comment by wemeetagain** [comment]
altair and phase0 fork choice tests are currently merged :+1:
