### ISSUE TITLE
BLS Batch Verification

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1473]
**Is your feature request related to a problem? Please describe.**
BLS verification is a bottleneck in state transition processing. We should support batch processing.

**Describe the solution you'd like**
Batch processing involves collecting all attestation (and optionally proposer) signatures from a single / multiple blocks, and verifying them all at once. The boolean result will show that either all signatures are valid, or at least one is invalid. In most cases, signatures will be valid, and this is a big performance win. 
In initial sync, peers sending invalid messages should be quickly blacklisted. In gossip, peers gossiping invalid messages will quickly be pruned from the mesh.

For inspiration here is relevant lighthouse code: https://github.com/sigp/lighthouse/blob/master/beacon_node/beacon_chain/src/block_verification.rs#L299

They create a `Verifier` that can `includeAllSignatures` from a block, then finally `verify`.

**Additional context**
Research post decsribing the algorithm: https://ethresear.ch/t/fast-verification-of-multiple-bls-signatures/5407
prysm imlementation: https://github.com/prysmaticlabs/prysm/pull/6479

**Comment by dapplion** [comment]
unstale

**Comment by twoeths** [comment]
At regular sync we lose a lot of peers because it's too slow to process slot/epoch.

```
2020-10-30 13:32:14 [SYNC]             info: Peer status activePeers=2, syncPeers=2, unknownRootPeers=2
2020-10-30 13:32:51 [SYNC]             info: Peer status activePeers=2, syncPeers=0, unknownRootPeers=0
2020-10-30 13:33:27 [SYNC]             info: Peer status activePeers=2, syncPeers=0, unknownRootPeers=0
2020-10-30 13:34:04 [SYNC]             info: Peer status activePeers=2, syncPeers=2, unknownRootPeers=2
```

if I ignore signature verification, I normally get 10-15 sync peers. Hopefully this issue help resolve it.

**Comment by dapplion** [comment]
Implemented
