### ISSUE TITLE
Beacon Node Doesn't Return Errors When Invalid Flags Are Passed

### ISSUE THREAD

**Issue by SeaMonkey82** [ChainSafe/lodestar#1485]
**Describe the bug**
When the beacon node is launched, any flags can be passed to it and it will run without producing an error.  I noticed this because I realized after a long time that I had misspelled one of my flags.

**Expected behavior**
Return error when invalid flag is passed.

**Steps to Reproduce**
Launch beacon node with an invalid flag.  Here's my default with --invalidFlag=null added.
```
node --trace-deprecation --stack-size=6000 --max-old-space-size=4096 ./packages/lodestar-cli/bin/lodestar beacon --rootDir=/home/seamonkey/.eth2/lodestar --metrics.enabled=true --metrics.serverPort=8010 --testnet medalla --network.discv5.bindAddr='/ip4/0.0.0.0/udp/13430' --network.multiaddrs='/ip4/0.0.0.0/tcp/13430' --api.enabled=true --enr-ip='1.2.3.4' --logFile=/home/seamonkey/.eth2/lodestar/lodestar.log --network.maxPeers=1000 --api.port=9596 --invalidFlag=null
```

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version: 20
 - Branch: Master
 - Commit hash: 1349b13e93cf1eb057c70bf53232fc79fcf1f5d3

**Comment by wemeetagain** [comment]
Related:
See previous fix  https://github.com/ChainSafe/lodestar/pull/1339
and reversion https://github.com/ChainSafe/lodestar/pull/1345

**Comment by dapplion** [comment]
Current version has strict options enabled
