### ISSUE TITLE
Investigate wrong hashTreeRoot value

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1489]
**Describe the bug**
This is the state of slot 671 I used to test
[state671.zip](https://github.com/ChainSafe/lodestar/files/5153778/state671.zip)

Unzip it and load to a state like:
```
const state = config.types.BeaconState.tree.deserialize(
      await fs.promises.readFile(filePath)
    );
```
then
```
console.log("@@@ stateRoot cache", toHexString(state.hashTreeRoot()));
```
returns correct value as
```
@@@ stateRoot cache 0x48e855dbf5e40ae0a76be586ca4215938ae5b266f4f548b921dc6d5fc25972a4
```
while
```
this.config.types.BeaconState.hashTreeRoot(state)
```
returns incorrect value as 0x6e4abd3714137b71a79550260e40ac4f3ff1a957469bba31f75e1ae70a3b643a

**Expected behavior**
Result should be 0x48e855dbf5e40ae0a76be586ca4215938ae5b266f4f548b921dc6d5fc25972a4 as in https://www.beaconcha.in/block/99ad36b7c857c00c461987fca2230723a31606fb8deb7686f7ba861f0bd0761c

**Steps to Reproduce**
1. Download file and unzip
2. This returns incorrect value
```
const state = config.types.BeaconState.tree.deserialize(
      await fs.promises.readFile(filePath)
    );
console.log(toHexString(this.config.types.BeaconState.hashTreeRoot(state)));
```

**Comment by wemeetagain** [comment]
I couldn't reproduce this locally, I got the correct value using both `state.hashTreeRoot()` and `BeaconState.hashTreeRoot(state)`

**Comment by twoeths** [comment]
thanks, so maybe it's just my environment issue.
assigning to my self to investigate when I have time.

**Comment by twoeths** [comment]
this is because I did not `clone()` before modifying `stateRoot` of `latestBlockHeader` ^^
