### ISSUE TITLE
Update Validator API Syncing Check

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1492]
**Describe the bug**
The validator API checks the syncing status before every method. This check is important to ensure that validator duties/blocks/attestations are not retrieved/submitted unless the chain is 'synced up' enough.

**Expected behavior**
Current behavior and implementation need to be revisited. We can't allow a completely unsynced chain to provide (incorrect) duties to a validator. But we also need to allow duties to be found in cases of many skip slots.

The implementation can also be cleaned up, code-wise.

**Comment by dapplion** [comment]
unstale

**Comment by dapplion** [comment]
The BeaconNode's validator API runs 
```ts
await checkSyncStatus(this.config, this.sync);
```
before every check. Would that satisfy this issue?

**Comment by yorickdowne** [comment]
Along those lines, changing Lodestar so it does not worry the user with error messages while consensus client is still syncing would be excellent.

```
consensus_1             | Jul-02 08:55:08.118 [API]             error: Req req-3 getProposerDuties error message=Node is syncing, headSlot 7040 currentSlot 726875
consensus_1             | Error: Node is syncing, headSlot 7040 currentSlot 726875
consensus_1             |     at notWhileSyncing (/usr/app/node_modules/@chainsafe/lodestar/src/api/impl/validator/index.ts:124:17)
consensus_1             |     at Object.getProposerDuties (/usr/app/node_modules/@chainsafe/lodestar/src/api/impl/validator/index.ts:182:7)
consensus_1             |     at Object.handler (/usr/app/node_modules/@chainsafe/lodestar-api/src/server/utils/server.ts:70:29)
consensus_1             |     at preHandlerCallback (/usr/app/node_modules/fastify/lib/handleRequest.js:124:28)
consensus_1             |     at preValidationCallback (/usr/app/node_modules/fastify/lib/handleRequest.js:107:5)
consensus_1             |     at handler (/usr/app/node_modules/fastify/lib/handleRequest.js:70:7)
consensus_1             |     at handleRequest (/usr/app/node_modules/fastify/lib/handleRequest.js:18:5)
consensus_1             |     at runPreParsing (/usr/app/node_modules/fastify/lib/route.js:422:5)
consensus_1             |     at next (/usr/app/node_modules/fastify/lib/hooks.js:158:7)
consensus_1             |     at handleResolve (/usr/app/node_modules/fastify/lib/hooks.js:175:5)
```

**Comment by dapplion** [comment]
> Along those lines, changing Lodestar so it does not worry the user with error messages while consensus client is still syncing would be excellent.
> 
> ```
> consensus_1             | Jul-02 08:55:08.118 [API]             error: Req req-3 getProposerDuties error message=Node is syncing, headSlot 7040 currentSlot 726875
> consensus_1             | Error: Node is syncing, headSlot 7040 currentSlot 726875
> consensus_1             |     at notWhileSyncing (/usr/app/node_modules/@chainsafe/lodestar/src/api/impl/validator/index.ts:124:17)
> consensus_1             |     at Object.getProposerDuties (/usr/app/node_modules/@chainsafe/lodestar/src/api/impl/validator/index.ts:182:7)
> consensus_1             |     at Object.handler (/usr/app/node_modules/@chainsafe/lodestar-api/src/server/utils/server.ts:70:29)
> consensus_1             |     at preHandlerCallback (/usr/app/node_modules/fastify/lib/handleRequest.js:124:28)
> consensus_1             |     at preValidationCallback (/usr/app/node_modules/fastify/lib/handleRequest.js:107:5)
> consensus_1             |     at handler (/usr/app/node_modules/fastify/lib/handleRequest.js:70:7)
> consensus_1             |     at handleRequest (/usr/app/node_modules/fastify/lib/handleRequest.js:18:5)
> consensus_1             |     at runPreParsing (/usr/app/node_modules/fastify/lib/route.js:422:5)
> consensus_1             |     at next (/usr/app/node_modules/fastify/lib/hooks.js:158:7)
> consensus_1             |     at handleResolve (/usr/app/node_modules/fastify/lib/hooks.js:175:5)
> ```

Agree our validator client is extremely verbose there. We should tone it down

**Comment by dapplion** [comment]
Closing since this should no longer be an issue. Please re-open if it happens again
