### ISSUE TITLE
choose between emitter.removeListener and emitter.off

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#1493]
There are parts of the code that use both `emitter.removeListener` and `emitter.off` when we should just choose one and change the places where we are using the other (I think `off` is probably better since we already use `on`)

**Comment by dapplion** [comment]
Agree with this, if there's no benefit to using `removeListener` we should use `off` for consistency

**Comment by 3xtr4t3rr3str14l** [comment]
closed in #1947
