### ISSUE TITLE
Sync not abortable

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1499]
Both regular and initial sync doesn't contain code required to abort. Especially problematic if there are missing peers since it contains loop and sleep.

Solution:
When sync stop is called make sure to abort all long running tasks via abort controller, abort iterator and abortable sleep

**Comment by dapplion** [comment]
Is this fixed already?

**Comment by mpetrunic** [comment]
No idea. I don't think we abort block fetching from peers.

**Comment by dapplion** [comment]
With the review from https://github.com/ChainSafe/lodestar/pull/2164 I would consider this issue closed. When stopping the node libp2p.stop() closes the streams of all open connections which should abort all active ReqResp requests including fetching blocks from peers
