### ISSUE TITLE
Sync requests future blocks

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1506]
**Describe the bug**
Syncing does not respect the clock slot, will request future blocks under certain circumstances.

**Expected behavior**
Sync should never request future blocks, always limit by the clock slot.

**Screenshots**
https://discordapp.com/channels/593655374469660673/593655641445367808/751090740087488553
https://gist.github.com/uvizhe/5187035fd0cb27f9f1f866d55c84bb8a

**Comment by dapplion** [comment]
@tuyennhv Do you think this issue is still relevant?

**Comment by twoeths** [comment]
I think it's not. We have new Regular Sync and a stable Initial Sync.
