### ISSUE TITLE
stuck in peer disconnect/reconnect cycle after epoch 3239

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#1509]
**Describe the bug**

When running the beacon chain, if I start from a last known finalized checkpoint of epoch 2289, I can sync up to epoch 3239 and then I get locked into a cycle of disconnecting (via goodbyes) and reconnecting from peers, which also causes sync to stall (even though the disconnects/reconnects still keep me around 20 or 25 peers, well above the minimum required number of peers).  I waited for about 15 minutes and sync never recovered and I quit the node.  Upon restart, the same results happen.  

My log from one of those restarts is attached here:
[testlog.txt](https://github.com/ChainSafe/lodestar/files/5171819/testlog.txt)

**Expected behavior**

Not lose peers and continue syncing

**Comment by twoeths** [comment]
I got issue #1511 when I restore my db so have to work on that first

**Comment by dapplion** [comment]
@3xtr4t3rr3str14l If logs are not humongous https://pastebin.com/ is a great tool to share logs

**Comment by 3xtr4t3rr3str14l** [comment]
Here's another log from a run I did last night.  Same results as above, except on different epochs

[testlog3.txt](https://github.com/ChainSafe/lodestar/files/5176027/testlog3.txt)

**Comment by 3xtr4t3rr3str14l** [comment]
It's also worth noting that fairly often I go through the disconnect/reconnect process when starting the beacon chain from scratch (i.e. starting at slot 0).  I'm not sure if this is connected to this issue directly, but maybe it is a sign of some improvements that could be made to our peering.  Just an observation/hunch.

**Comment by twoeths** [comment]
should be resolved by peer scoring work in #1545

**Comment by 3xtr4t3rr3str14l** [comment]
haven't been seeing this happen for some months now.  closing
