### ISSUE TITLE
Restore Chain: need to make it minimal

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1526]
**Is your feature request related to a problem? Please describe.**
After syncing medalla and restart, we have to load 8000 unfinalized blocks and reprocess which takes time and memory, it's redundant because:
+ After chain is started, initial sync redownload same blocks again
+ Some unfinalized blocks are even not in the finalized chain so it's redundant to restore

This leads to some weird issues like head slot is way behind latest slot when I restart.

**Describe the solution you'd like**
When we restart, we only need to feed forkchoice with last known state:
+ Justified and finalized nodes are ones from the last known (finalized) state 
+ Get respective blocks and feed to forkchoice: 1 for head, 1 for justified, 1 for finalized
+ Continue with initial sync and regular sync

need confirmation from @wemeetagain @mpetrunic

**Comment by wemeetagain** [comment]
> After chain is started, initial sync redownload same blocks again

Why does initial sync redownload the same blocks again? Do we always sync starting from our finalized checkpoint?

> When we restart, we only need to feed forkchoice with last known state:

We have to initialize the fork choice with the finalized state / finalized block, and feed blocks, one-by-one starting there.

IMO the solution I'd like to see is persisting/restoring our fork choice information. Then, on restore, we'd have the full block tree w/o needing to feed all blocks thru the processor. (Perhaps we could always regenerate the head state, seeding our state caches, in anticipation of continuing from there, or near there).

**Comment by twoeths** [comment]
> Why does initial sync redownload the same blocks again? Do we always sync starting from our finalized checkpoint?

In unfinalized period, I sync to slot 110000 and it's crashed. When I restart, we have to reprocess from block 73249 until 110000, then at initial sync we start from our finalized block which is 73248. So its a duplicate.

Another example, last time I came to regular sync and proceeded a little bit after that then I stop, get some unfinalized blocks. After ~ 2 weeks, when restart I have to reprocess these blocks but it turns out these blocks are not in the finalized chain, that's redundant. This lead me to weird situation where head block is way behind latest block as described.

> We have to initialize the fork choice with the finalized state / finalized block, and feed blocks, one-by-one starting there.

~My proposal is only feed forkchoice with 3 blocks: finalized block, justified block and head block (last finalized block) then we finish the chain restore and go to initial sync. Is that enough?~
My proposal is initialize the forkchoice with the finalized state / finalized block and justified block, finalized block of that state and reprocess other remaining finalized blocks (if we have it) through block processor, there are just few of them

> IMO the solution I'd like to see is persisting/restoring our fork choice information. Then, on restore, we'd have the full block tree w/o needing to feed all blocks thru the processor.

~Yeah, we don't need to touch the block processor. But I think we only need to do that with 3 blocks and let initial sync build the full block tree again through block processor.~

We also need state cache so still need the block processor, but we don't reprocess unfinalized blocks, just reprocess finalized blocks in order to have both forkchoice and state cache, then at initial sync we'll start at the last finalized block.

The main thing is not to touch unfinalized blocks upon restart since it's not necessary so I don't think we want to persist forkchoice just to have information of these unfinalized blocks.

**Comment by twoeths** [comment]
#1517  will resolve this issue
