### ISSUE TITLE
Implement forkChoice:reorg event

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1588]
In case we switch to another parallel chain, we should emit forkChoice:reorg event
with old head block summar, new head block summary and depth which is number of slots to common ancenstor block of those two chain heads.

**Comment by wemeetagain** [comment]
> number of slots to common ancenstor block of those two chain heads

Counting from the old head? or the new head?

**Comment by mpetrunic** [comment]
> > number of slots to common ancenstor block of those two chain heads
> 
> Counting from the old head? or the new head?

old :)

**Comment by mpetrunic** [comment]
resolved via #1596
