### ISSUE TITLE
libp2p 0.29: Handle dialProtocol timeout

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1597]
**Describe the bug**
Sync stalled due to a request timeout does not throw Error.
This happens to me a couple of times with libp2p 0.29: during initial sync/regular sync, peers get disconnected after we called dialProtocol but it did not trigger an error when timeout
```
2020-09-28 19:37:35  [SYNC]             warn: Failed to obtain chunk {"start":395488,"end":395551} from peer 16Uiu2HAmEPBjHgMH4YZeNMFsMC6wrGWKcJR6uFL5j8oahyG2NKzz
2020-09-28 19:37:35  [NETWORK]       verbose: sending beacon_blocks_by_range request to 16Uiu2HAmEPBjHgMH4YZeNMFsMC6wrGWKcJR6uFL5j8oahyG2NKzz requestId=5c42cd4fd33136f3, encoding=ssz_snappy
2020-09-28 19:37:35  [NETWORK]       verbose: peer disconnected 16Uiu2HAmEPBjHgMH4YZeNMFsMC6wrGWKcJR6uFL5j8oahyG2NKzz
```

**Expected behavior**
Network req/resp should throw error for sync to handle

One candidate to fix is #1277

**Comment by mpetrunic** [comment]
Quote from Vasco
> The issue might be: you add the peer's addresses to the AddressBook, which will result in autoDial to kick in and dial your peer. In parallel, you do a manual dial and it will wait for the previous one without using the abort signal:

**Comment by mpetrunic** [comment]
@tuyennhv Could this be it?

**Comment by twoeths** [comment]
it's not the case for us, I notice the same peer was used a couple of times (in earlier log which I did not catch) before the issue happen.

> The issue might be: you add the peer's addresses to the AddressBook

I think libp2p handles that part, lodestar doesn't do that

**Comment by mpetrunic** [comment]
> it's not the case for us, I notice the same peer was used a couple of times (in earlier log which I did not catch) before the issue happen.
> 
DEfault timeout is 60s so within 60s of adding peer all dialProtocol signals won't work. Are you saying we got some response from peer before?

> 
> I think libp2p handles that part, lodestar doesn't do that

It gets added there from discv5 for example.

**Comment by twoeths** [comment]
> Are you saying we got some response from peer before?

yes

> It gets added there from discv5 for example.

just check that discv5 doesn't use libp2p addressBook, this is how discv5 send a "peer" event to libp2p https://github.com/ChainSafe/discv5/blob/master/src/libp2p/discv5.ts#L91
then libp2p has to add multiaddr to its addressBook himself.

**Comment by mpetrunic** [comment]
> just check that discv5 doesn't use libp2p addressBook, this is how discv5 send a "peer" event to libp2p https://github.com/ChainSafe/discv5/blob/master/src/libp2p/discv5.ts#L91
> then libp2p has to add multiaddr to its addressBook himself.

https://github.com/libp2p/js-libp2p/blob/bb59b518f142065d9f40852aa9089d73ac7a7cdc/src/index.js#L502

**Comment by twoeths** [comment]
yeah libp2p add addresses to addressBook there, lodestar and discv5 don't use that.

> In parallel, you do a manual dial and it will wait for the previous one without using the abort signal:

we don't do a manual dial and the peer were used to query beacon blocks by range/root successfully a couple of times until it disconnected and the last request failed without throwing timeout error in `dialProtocol` then it cause sync stalled.

**Comment by mpetrunic** [comment]
> yeah libp2p add addresses to addressBook there, lodestar and discv5 don't use that.
> 
Yes we do, this method gets called once you emit peer event from discv5.
https://github.com/libp2p/js-libp2p/blob/bb59b518f142065d9f40852aa9089d73ac7a7cdc/src/index.js#L565

> > In parallel, you do a manual dial and it will wait for the previous one without using the abort signal:
> 
> we don't do a manual dial and the peer were used to query beacon blocks by range/root successfully a couple of times until it disconnected and the last request failed without throwing timeout error in `dialProtocol` then it cause sync stalled.

Every dialProtocol is manual dial to peer. Automatic dial happens when discovery service (discv5 in our case) find peer, we dial to get peer libp2p metadata (supported protocols for example)

**Comment by twoeths** [comment]
> Every dialProtocol is manual dial to peer. Automatic dial happens when discovery service (discv5 in our case) find peer, we dial to get peer libp2p metadata (supported protocols for example)

Agree, but in our case, I believe we have a connection to peer already since we got a lot of successful requests, we call `dialProtocol` just to get a stream with same connection.

> The issue might be: you add the peer's addresses to the AddressBook, which will result in autoDial to kick in and dial your peer. In parallel, you do a manual dial and it will wait for the previous one without using the abort signal:

I don't think this is the scenario we face since we have a couple of successful requests/responses already, I guess `autoDial` only works if we have no connection to peer https://github.com/libp2p/js-libp2p/blob/bb59b518f142065d9f40852aa9089d73ac7a7cdc/src/index.js#L521

I notice the issue happens because the peer disconnected us and dialProtocol was called right before that and did not trigger Error timeout after all.

**Comment by mpetrunic** [comment]
Do you think we can create test case for that so libp2p guys can help us?

**Comment by twoeths** [comment]
yeah it's a good idea, not easy to reproduce with our sync but I'll give it a try

**Comment by mpetrunic** [comment]
> yeah it's a good idea, not easy to reproduce with our sync but I'll give it a try

I don't think you need to do it in sync, just use raw dialProtocol and disconnect other peer, maybe

**Comment by twoeths** [comment]
I couldn't reproduce this in libp2p test case, if I do `dialProtocol` and disconnect peer in the middle, it threw `Error: stream ended before 1 bytes became available` instead of being suspended like in this issue.

**Comment by mpetrunic** [comment]
You could try with https://github.com/libp2p/js-libp2p/pull/764 and see if it maybe fixes, otherwise let's wait for libp2p0.29 and see if it still happening.

**Comment by twoeths** [comment]
Recently I only try everything in my libp2p 0.29 branch but it's good to know they are working on something related to the issue

**Comment by mpetrunic** [comment]
There is also PR with same changes for 0.29 version
