### ISSUE TITLE
Consider moving beacon-state-transition/fast to separate package

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1624]
Create a new package `beacon-state-transition-fast` and move the fast specific code there. Current setup has ugly name clashes and forces large parts of the codebase to import from `/lib/*`.

**Other options**

Use a more structured fs in a single package `beacon-state-transition`
- naive
- fast
- util

**Comment by dapplion** [comment]
Bump @wemeetagain

**Comment by wemeetagain** [comment]
See https://github.com/ChainSafe/lodestar/pull/1873#discussion_r542619731

**Comment by mpetrunic** [comment]
https://github.com/ChainSafe/lodestar/pull/1886#issuecomment-745083813

It's a huge change so we should weigh in pros and cons before implementing.

This would also resolve #1462

wdytk @dapplion @wemeetagain @tuyennhv?

**Comment by dapplion** [comment]
Your suggestion of namespacing `phase0.fast.processBlock` would remove the need to import from deep inside lib which was the main driver behind this issue. The difference between both solutions is to separate code inside the same package or in different packages. I don't have a strong opinion on either direction and would love to know your pros and cons of each path

**Comment by mpetrunic** [comment]
> Your suggestion of namespacing `phase0.fast.processBlock` would remove the need to import from deep inside lib which was the main driver behind this issue. The difference between both solutions is to separate code inside the same package or in different packages. I don't have a strong opinion on either direction and would love to know your pros and cons of each path

I guess biggest reason is that it would be easier to import because if we have phase0 namespace in both packages everywhere you use both original utilities and fast stuff you would have to manually rename import (`import {phase0 as phase0Fast}` or something).

**Comment by twoeths** [comment]
> #1886 (comment)

yeah I prefer this setup to have both the original and fast state transition stay inside lodestar-beacon-state-transition, they are all about state transition in the end. Imagine if we have another type of state transition, I prefer to have it stay inside lodestar-beacon-state-transition than having another separate package for it.
