### ISSUE TITLE
Consider publishing lodestar monorepo under @lodestar namespace

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1625]
**Is your feature request related to a problem? Please describe.**
Current naming is verbose.
`import {...} from "@chainsafe/lodestar-config"`
`import {...} from "@chainsafe/lodestar-types"`
`import {...} from "@chainsafe/lodestar-beacon-state-transition"`
`import {...} from "@chainsafe/lodestar-cli"`
etc.

**Describe the solution you'd like**
`import {...} from "@lodestar/config"`
`import {...} from "@lodestar/types"`
`import {...} from "@lodestar/beacon-state-transition"`
`import {...} from "@lodestar/cli"`
etc.

I think its clear (from community knowledge, copyright notices, github organization, etc) that ChainSafe owns and manages lodestar. We likely don't need the additional explicit reminder in the package name, itself.

A more concise package name is generally a good thing for memorability and usability.
We may also shorten each monorepo directory name (eg: `./packages/lodestar-validator` -> `./packages/validator`)
Having simpler naming may make it more convenient to add more monorepo packages w/o incurring the pain of searching thru a long list of `lodestar-*` packages/directories.

**Describe alternatives you've considered**
leave as-is

**Comment by GregTheGreek** [comment]
Chatted with Cayman about this a bit yesterday.

I can resonate with the intention, but at the end up the day its just a one liner in your cli, and (hopefully :laughing:) your edditor  has auto-complete making your interaction with the prefix itself almost non-existent. Sticking with the ChainSafe branding for the time being makes the most sense for the time being. If some astronomically odd case opens up I'm happy to re-ignite this conversation.

**Comment by 3xtr4t3rr3str14l** [comment]
so i guess we're not going to do this anymore?  should this issue be closed?
