### ISSUE TITLE
Eth1Notifier init from deposit contract

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#163]
**Is your feature request related to a problem? Please describe.**
If Eth1Notifier is started after Deposit/Eth2Genesis events happens it will have wrong depositCount and chainStarted props and thus won't process events further.

**Describe the solution you'd like**
On start function, filter Deposit events from block at which contract is deployed, store them in db, store count in depositCount prop. Filter Eth2Genesis event, store in db and set chainStarted to true.

**Comment by GregTheGreek** [comment]
This is logical, we should definitely track them in a db and not in memory

**Comment by mpetrunic** [comment]
@GregTheGreek If Eth1Notifier is started after Eth2Genesis event is fired, should he on start emit eth2genesis or just set chainStarted to true  and save Eth1Data and deposits into database?

**Comment by GregTheGreek** [comment]
What we should do is start looking for logs at the block that the contract was deployed to and then increment forward from there collecting all the logs until `chainStrart` is fired.

That way we don't need to even think about before or after

**Comment by mpetrunic** [comment]
Yeah, I'm implementing that, but once I encouter Eth2Genesis event should I fire event from Eth1Notifier or just set chainStarted to true? Not sure what consequences does it have to the rest of code. I assume it's best to check if database has beacon chain initialized and depending on that emit event?

**Comment by GregTheGreek** [comment]
Oh I see

I think emitting an event from `Eth1Notifier` would make sense, and then have the `BeaconChain` class capture it would make sense to me?

I think `EthersEth1Notifier.processEth2GenesisLog` currently does exactly that

**Comment by mpetrunic** [comment]
Hmm but if chain is already initialized and synced, it would reset chain head to genesis. I think I will add condition in `initializeChain` to initialize only if chain head is null

**Comment by GregTheGreek** [comment]
Ahhh, so you're saying if the DB already has entries?

**Comment by mpetrunic** [comment]
Yeah in case node restarts.

**Comment by mpetrunic** [comment]
Ignore this, beacon chain doesn't listen on eth2genesis event if it'0s initialized, my bad haha
