### ISSUE TITLE
Not yet implemented methods from official spec

### ISSUE THREAD

**Issue by Spacesai1or** [ChainSafe/lodestar#1662]
While developing the [web3.js beacon chain API wrapper](https://github.com/ethereum/web3.js/tree/wyatt/eth2-refactor/packages/web3-eth2-beaconchain), here are some of the routes listed in the [official spec](https://ethereum.github.io/eth2.0-APIs/#/) that `404`:

**NOTE** I tested using the latest docker image as of `10/13/2020` based off commit [32127c4](https://github.com/ChainSafe/lodestar/tree/32127c4570a960ca3076cab74589935a3474e560)

- [ ] [/eth/v1/beacon/states/{state_id}/root](https://ethereum.github.io/eth2.0-APIs/#/Beacon/getStateRoot)
- [ ] [/eth/v1/beacon/states/{state_id}/fork](https://ethereum.github.io/eth2.0-APIs/#/Beacon/getStateFork)
- [ ] [/eth/v1/beacon/states/{state_id}/finality_checkpoints](https://ethereum.github.io/eth2.0-APIs/#/Beacon/getStateFinalityCheckpoints)
- [ ] [​/eth​/v1​/beacon​/states​/{state_id}​/validators](https://ethereum.github.io/eth2.0-APIs/#/Beacon/getStateValidators)
- [ ] [/eth/v1/beacon/states/{state_id}/validators/{validator_id}](https://ethereum.github.io/eth2.0-APIs/#/Beacon/getStateValidator)
- [ ] [/eth/v1/beacon/states/{state_id}/validator_balances](https://ethereum.github.io/eth2.0-APIs/#/Beacon/getStateValidatorBalances)
- [ ] [/eth/v1/beacon/states/{state_id}/committees/{epoch}](https://ethereum.github.io/eth2.0-APIs/#/Beacon/getEpochCommittees)
- [ ] [​/eth​/v1​/beacon​/blocks](https://ethereum.github.io/eth2.0-APIs/#/Beacon/publishBlock)
- [ ] [/eth/v1/beacon/pool/attestations](https://ethereum.github.io/eth2.0-APIs/#/Beacon/submitPoolAttestations)
- [ ] [/eth/v1/beacon/pool/attester_slashings](https://ethereum.github.io/eth2.0-APIs/#/Beacon/getPoolAttesterSlashings)
- [ ] [/eth/v1/beacon/pool/attester_slashings](https://ethereum.github.io/eth2.0-APIs/#/Beacon/submitPoolAttesterSlashings)
- [ ] [/eth/v1/beacon/pool/proposer_slashings](https://ethereum.github.io/eth2.0-APIs/#/Beacon/getPoolProposerSlashings)
- [ ] [/eth/v1/beacon/pool/proposer_slashings](https://ethereum.github.io/eth2.0-APIs/#/Beacon/submitPoolProposerSlashings)
- [ ] [/eth/v1/beacon/pool/voluntary_exits](https://ethereum.github.io/eth2.0-APIs/#/Beacon/getPoolVoluntaryExits)
- [ ] [/eth/v1/beacon/pool/voluntary_exits](https://ethereum.github.io/eth2.0-APIs/#/Beacon/submitPoolVoluntaryExit)

---

These two methods seem to be implemented, but only return an empty array or an array of `null`s:

- [ ] [/eth/v1/beacon/blocks/{block_id}/attestations](https://ethereum.github.io/eth2.0-APIs/#/Beacon/getBlockAttestations)
- [ ] [/eth/v1/beacon/pool/attestations](https://ethereum.github.io/eth2.0-APIs/#/Beacon/getPoolAttestations)

**Comment by mpetrunic** [comment]
Hey, we already have issues for those:
- #1058
- #1057 
- #1615 - `POST  ​/eth​/v1​/beacon​/blocks`

I'm hoping I can take care of those by next week.
