### ISSUE TITLE
Add `network.discv5.enabled` to the `IDiscv5DiscoveryInputOptions` type

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1681]
See
https://github.com/ChainSafe/lodestar/blob/00012384f2fefe57805e368d815c6677214baf05/packages/lodestar-cli/src/testnets/altona.ts#L25-L29

**Comment by 3xtr4t3rr3str14l** [comment]
this issue is also being tracked here:
#1227

**Comment by dapplion** [comment]
True, duplicate
