### ISSUE TITLE
Improve / unify branding across monorepo

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1695]
**Is your feature request related to a problem? Please describe.**
The readmes of each individual package in the monorepo do not adequately link back to ChainSafe and Lodestar.
Each readme doesn't convey the context that the package is part of something bigger, nor does it mention ChainSafe.

**Describe the solution you'd like**
- Include a header in each package in the monorepo, consistently placed, something like:

> This package is part of [ChainSafe's Lodestar](https://lodestar.chainsafe.io) project

- Include a link/reference to ChainSafe & chainsafe.io in the footer, perhaps with the license:

LGPL-3.0 [ChainSafe Systems](https://chainsafe.io)

**Describe alternatives you've considered**
Add a ChainSafe / Lodestar badge?

**Additional context**
See how lodestar-types README is rendered / viewed by a newcomer coming across lodestar via npm or github
- https://www.npmjs.com/package/@chainsafe/lodestar-types
- https://github.com/ChainSafe/lodestar/tree/master/packages/lodestar-types

**Comment by 3xtr4t3rr3str14l** [comment]
@wemeetagain  can this issue be closed?

**Comment by dapplion** [comment]
Should be good for now, re-visit when reviewing Lodestar branding as a whole
