### ISSUE TITLE
Cli option to start validator

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#172]
**Is your feature request related to a problem? Please describe.**
Currently cli cannot start validator client and thus after beacon chain initialization it doesn't propose new blocks.

**Describe the solution you'd like**
- expose cli command (something like `./bin/lodestar gen validator`) to generate bls private and public key for validator. (Implementation should be stubbed because we don't have proper bls implementation).
- add to `beacon command, in cli, option `--validator <privateKey<`, generate public key from private key and submit along with rpc url to validator options.

**Describe alternatives you've considered**

**Additional context**

**Comment by wemeetagain** [comment]
Might make sense to start up the validator with a `validator` command,
eg: `./bin/lodestar validator --key $KEY --rpc $RPC`

**Comment by mpetrunic** [comment]
> Might make sense to start up the validator with a `validator` command,
> eg: `./bin/lodestar validator --key $KEY --rpc $RPC`

But you have to start beacon chain and rpc to use validator so it might be simpler to be able to start both at once.
Nevertheless, for now is better to have separate command because of js performance but we could start forking processes later.

**Comment by wemeetagain** [comment]
Oh, I see, I thought you were talking about the validator in "standalone" mode.

I think both configurations will be useful in production to different users.

Beacon+Validator bundle:
- less configuration -- easier config for single-validator users
- potentially lower overhead rpc (if we write the memory rpc transport)

Beacon independent of Validator
- more flexible -- start/stop new validators independent of beacon node, use remote beacon node

**Comment by GregTheGreek** [comment]
Yeah I've been thinking it may be worth distributing multiple bundles to npm as well... Eth2 types, beacon chain, validator and the bundle
