### ISSUE TITLE
Forkchoice head getting stuck at an orphaned block

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1727]
**Describe the bug**
This is the latest head I have
```
2020-11-03 01:18:25 [CHAIN]         verbose: New chain head headSlot=622522, headRoot=0x8778d4254b41f48534757e7a1fd1f9b82471494d3f1765b5f7b3f003de43405a
```
I notice that's an orphaned block
**Expected behavior**
Head should move forward during the sync.

**Steps to Reproduce**
Sync Medalla to head

**Comment by twoeths** [comment]
The forkchoice `getHead()` does not seem right. Previously we do `syncChanges()` to apply weight change for each node when we call `getHead()` and the head can move forward thanks to that, now we don't do any weight changing actions when we call `getHead()`. Refer to https://github.com/ChainSafe/lodestar/blob/v0.11.0/packages/lodestar/src/chain/forkChoice/arrayDag/lmdGhost.ts#L335

Currently when we add a block, I think it'll all have 0 weight by default and the head moves forward solely based on parent-child relationship until it reaches an orphaned block. At that time, it'll try to resolve best child/best descendant based on `maybeUpdateBestChildAndDescendant` and it'll finally come to tie break condition where it based on hex root comparison (bc most of blocks have 0 weight) and then it gets stuck there.

**Comment by twoeths** [comment]
other clients avoid this issue by making sure imported chain segment is linear (all blocks should have known parent and child), we need to do that too.

**Comment by 3xtr4t3rr3str14l** [comment]
just curious, how do we get orphaned blocks in the first place?
