### ISSUE TITLE
Protection best practices

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1733]
From https://github.com/ethereum/eth2.0-specs/pull/2082/files#diff-e3f50f31ab8c39b7d634a722cdbdf3575c0ae70c787da2007b4ab5ae24a6b3eaR613

> 3) Recovered validator -- Recovering a validator from a private key will result in an empty local slashing db. Best practice is to import (from a trusted source) that validator's attestation history. See [EIP 3076](https://github.com/ethereum/EIPs/pull/3076/files) for a standard slashing interchange format.
> 4) Far future signing requests -- A validator client can be requested to sign a far into the future attestation, resulting in a valid non-slashable request. If the validator client signs this message, it will result in it blocking itself from attesting any other attestation until the beacon-chain reaches that far into the future epoch. This will result in an inactivity leak and potential ejection due to low balance. 
A validator client should prevent itself from signing such requests by: a) keeping a local time clock if possible and following best practices to stop time server attacks and b) refusing to sign, by default, any message that has a large (>6h) gap from the current slashing protection database indicated a time "jump" or a long offline event. The administrator can manually override this protection to restart the validator after a genuine long offline event.

**Comment by dapplion** [comment]
Is point (4) something we want to implement eventually?

**Comment by dapplion** [comment]
@mpetrunic  What's your opinion on the value of implementing this protections in lodestar-validator?

**Comment by mpetrunic** [comment]
nice to have, I would prefer if there is option to override this stuff from code as well.

**Comment by dapplion** [comment]
Our current implementation follows this recommendations
