### ISSUE TITLE
Regular Sync keeps using a bad peer

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1734]
**Describe the bug**
I keep seeing this same log from the same peer
```
failed to send request a8c5340ce568fc72 to peer 16Uiu2HAm889yCc1ShrApZyM2qCfhtH9ufqWoTEvcfTowVA9HRhtw method=beacon_blocks_by_range, reason=response timeout
```

**Expected behavior**
+ PeerScore system should update score when it see error like that
+ Regular Sync should pick other best peer

All code seems to be logical, need to add more log to figure out.

**Comment by twoeths** [comment]
so everything works according to what was designed. `beacon_blocks_by_range` timeout happens after 4-5 minutes, during that time, there are some `beacon_blocks_by_root` responses and we add 5 score each and that make peer eligible for the next round. Most of the time it switches best peer successfully.

Probably we should add score based on number of blocks returned too. Right now each `beacon_block_by_root` response is treated with 5 score while it returns only 1 block.

**Comment by mpetrunic** [comment]
yeah, feel free to tweak scoring and test out how it works.
