### ISSUE TITLE
rename Libp2pNetwork.metadata -> metadataController or similar

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#1741]
Can we rename metadata in Libp2pNetwork (https://github.com/ChainSafe/lodestar/blob/00c828fb55a9a0a5916a7b50cac5a03baeea75df/packages/lodestar/src/network/network.ts#L41) to metadataController or something like that so we don't have to do metadata.metadata?

- e.g. in onMetadata (this.network.metadata.metadata) (https://github.com/ChainSafe/lodestar/blob/00c828fb55a9a0a5916a7b50cac5a03baeea75df/packages/lodestar/src/sync/reqResp/reqResp.ts#L258)

**Comment by mpetrunic** [comment]
you could change metadata getter to be just "get" or "all" instead of "metadata"
