### ISSUE TITLE
Command line option to switch between hobbits and libp2p

### ISSUE THREAD

**Issue by Mikerah** [ChainSafe/lodestar#175]
As PR #154 gets ready to close, I realized that @GregTheGreek's concurrent work in hobbits won't be easily integrated. In order to use hobbits since the libp2p work is still in progress, I propose that we have a command line flag in order to run the lodestar client with either networking protocol. It will make it easy to test with Artemis and any other team that has a working libp2p implementation.

**Comment by GregTheGreek** [comment]
Totally agree! Better yet, because @wemeetagain and @mpetrunic spend a lot of time abstracting everything, we should be able to have cli arguments for DB and P2P to allow us to choose what we want

**Comment by Mikerah** [comment]
Closing since refactoring for this change has been done.
