### ISSUE TITLE
Improve validator exit process

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1761]
**Describe the bug**
It takes so much time to process blocks with validator exits, we need to improve it

<img width="751" alt="Screen Shot 2020-11-16 at 19 35 02" src="https://user-images.githubusercontent.com/10568965/99253256-02cf6c00-2843-11eb-8115-dd6989a1f203.png">

it showed that processing this method may take up to 6s

**Comment by twoeths** [comment]
<img width="785" alt="Screen Shot 2020-11-16 at 19 37 24" src="https://user-images.githubusercontent.com/10568965/99253372-34e0ce00-2843-11eb-99f4-70303695c4df.png">

**Comment by dapplion** [comment]
Right I saw that readOnlyMap over the entire validator set when studying the spec code. Is this how other clients do it?

**Comment by twoeths** [comment]
`readOnlyMap` is just the map for our TreeBacked structure, but it's more expensive due to the way we access leaf nodes in Tree.
Other clients should loop through validator array in state too. I think the way to improve is just to loop only 1 time for all validator exits included in a block.
