### ISSUE TITLE
CLI option for configuration file

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#177]
Thinking about the different configuration options of lodestar and the potential for adding many more in the future, it will be useful to allow for full configuration from a file as an additional option.

eg:
```bash
# create a default configuration file
./bin/lodestar create-config -o my_lodestar_config.toml
# use configuration file in beacon node
./bin/lodestar beacon -c my_lodestar_config.toml
```

I'm hoping that there may be some libraries available to help unify the different configuration options available, so we won't have to maintain each independently.

**Comment by GregTheGreek** [comment]
Oh this is interesting...
