### ISSUE TITLE
Partition long running operations

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1770]
**Describe the bug**
Except for signature verification, the only long running operation I found is `processEpoch`. It can be up to 4s-5s, exceptional ones can be up to 10s. The consequence of this is:
+ Some status requests/responses are timed out at the same time
+ Beacon_block_by_root, Beacon_block_by_range are timed out at the same time which cause peer score reduced
+ Cannot finish handshake process with some incoming peers
+ Some peers disconnect us (goodbye code = 129) because we have the worse score

While #1464 takes the approach of using a worker thread to process state transition, we should also explore partitioning `processEpoch()` into smaller steps and make it async.

https://nodejs.org/en/docs/guides/dont-block-the-event-loop/

**Expected behavior**
Should not make network requests/responses time out just because of long-running operations.

**Steps to Reproduce**
Sync Medalla

**Comment by dapplion** [comment]
@tuyennhv We've implemented this and works quite well, should we close?

**Comment by twoeths** [comment]
> @tuyennhv We've implemented this and works quite well, should we close?

we haven't implemented it yet, we want to add some more `await sleep(0);` inside lodestar-beacon-state-transition

**Comment by dapplion** [comment]
I have never observed event loop lag over 1s in months. However if the main thread is busy things will timeout, regardless of how many sleep(0) we add everywhere.
