### ISSUE TITLE
Integrate BLST

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1771]
Following the work in https://github.com/chainsafe/blst-ts and https://github.com/chainsafe/bls integrate into lodestar

**Comment by dapplion** [comment]
BLST already integrated in current master :tada: 

https://github.com/ChainSafe/lodestar/blob/4ca5a760c928c1257172bb4bf1033de2f60e6f3d/packages/lodestar-cli/src/util/bls.ts#L3-L10

**Comment by twoeths** [comment]
oh I thought we want to process a chain segment (check linear chain first) in this issue. Something like:
+ do not change `lodestar-beacon-state-transition`
+ lodestar side: new `runMultipleStateTransition(..., jobs: IBlockJob[])`. Consumers would be initial sync and regular sync.
+ Accumulate signatures and use `bls.verifyMultiple()` to verify signatures beforehand
+ Run `fastStateTransition()` directly or the old `runStateTransition()` for each job/blocks without signature verification

@ChainSafe/eth2-0  can someone confirm if we plan to do it, and we want to do this in this issue or another one?

**Comment by dapplion** [comment]
Yes this will be implemented soon. The tracking issue is https://github.com/ChainSafe/lodestar/issues/1473 and this PR is the first step for that https://github.com/ChainSafe/lodestar/pull/1821

In terms of speeding up signature verification, it has 3 steps
- Change herumi for BLST, x10 speed increase :heavy_check_mark: 
- Use batch verification x2 speed increase :hourglass: 
- Multi-thread x2-x8 speed increase :question:
