### ISSUE TITLE
Code Explanation

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1775]
- Explaining non-obvious design decisions in top-level comments
- Guiding thru the overall structure/architecture
- Adding typedocs to every public interface/constant/class/etc

Current Progress (checked indicates that documentation/comment polishing for that package has been merged into master):

- [x] benchmark-utils
- [x] lodestar
- [x] lodestar-beacon-state-transition
- [x] lodestar-cli
- [x] lodestar-config
- [x] lodestar-db
- [x] lodestar-fork-choice
- [x] lodestar-params
- [x] lodestar-spec-test-util
- [x] lodestar-types
- [x] lodestar-utils
- [x] lodestar-validator
- [x] spec-test-runner

**Comment by 3xtr4t3rr3str14l** [comment]
I'm starting this off by making sure we have our comments covered in `lodestar-cli`.  I'm thinking it's probably a good idea to break this up into chunks so we don't have a massive diff, if we end up needing a lot of more comments, so I will probably make a PR just for the lodestar-cli comment updates.

**Comment by 3xtr4t3rr3str14l** [comment]
I'm moving on to continue this process for the `lodestar-validator` package

**Comment by 3xtr4t3rr3str14l** [comment]
I just added the list of checkmarks above in @wemeetagain 's original comment.  I figured it might less less unwieldy than having an issue for every package.  If enough people disagree, I'll make issues for each package, but for now, if anyone starts working on this effort for a particular package, just say so.  That way we don't accidentally step on each others toes :)

**Comment by 3xtr4t3rr3str14l** [comment]
i'm starting on `lodestar-beacon-state-transition` next

**Comment by 3xtr4t3rr3str14l** [comment]
moving on to `lodestar-fork-choice` next

EDIT: `lodestar-fork-choice` is already pretty well-documented/commented, but I'll probably add some high-level things to the README

**Comment by 3xtr4t3rr3str14l** [comment]
calling this done
