### ISSUE TITLE
Logger is not an interface

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/lodestar#179]
**Describe the bug**

The logger is defined as a class, but should be defined as an interface.

Reference: 
Interface: https://github.com/ChainSafe/lodestar/blob/master/src/logger/interface.ts
Class: https://github.com/ChainSafe/lodestar/blob/master/src/logger/winston.ts

**Comment by mpetrunic** [comment]
I think I mean't to implement info, warning and other methods to invoke single abstract method (exmpl. `log`) to make it easier to implement some log processing

**Comment by GregTheGreek** [comment]
hmmm, ok that makes sense -- we can put it on the back burner

**Comment by GregTheGreek** [comment]
#241
