### ISSUE TITLE
Drop the "alternative" part in the headlines

### ISSUE THREAD

**Issue by holgerd77** [ChainSafe/lodestar#18]
Hi @Mikerah, every time I am looking at this repo, I am irritated by the "alternative" parts in the headlines, as it suggests to me that you are doing an alternative implementation in the sense of "an alternative/different approach" - similar to the Casper FFG vs CBC research directions.

I assume that is not what you are intending and you just try to implement the (evolving) specifications in JavaScript (or do you want to indeed follow different paths than e.g. done in the Prysmatic Labs repo)?

Then I would suggest to drop the "alternative" in the header title and the initial section of the README and just state "provide an implementation of the beacon chain in JavaScript".

Cheers
Holger

**Comment by Mikerah** [comment]
@holgerd77 , You are right. We are indeed trying to implement the evolving specification in JS and is not meant to mean that we are doing something completely different a la FFG vs CBC.
