### ISSUE TITLE
Separate mainnet cli flag from testnet cli flag?

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#1808]
Currently, (as per #1806 ), we do `--testnet mainnet` to run lodestar on mainnet.  I did this for convenience so i didn't have to restructure the current --testnet logic.  Said current current logic (i.e. much of the architecture of `lodestar-cli`) is centered around the assumption that we have a `--testnet` flag passed in order to bootstrap us to a valid eth2 environment.  

This issue proposes to allow the user to bootstrap to mainnet without the `--testnet` flag (i.e. like `node lodestar beacon` instead of `node lodestar beacon --testnet mainnet`.

Or maybe some feel it's not a big deal to leave as is (i.e. running as `--testnet mainnet`)?  Would be interested to hear everyone's thoughts.

**Comment by dapplion** [comment]
What are other clients doing?

**Comment by 3xtr4t3rr3str14l** [comment]
lighthouse doesn't call it `--testnet` but `--network` instead
https://lighthouse-book.sigmaprime.io/testnet-validator.html#become-a-testnet-validator

i feel like that approach makes sense
