### ISSUE TITLE
Switch away from Master

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/lodestar#181]
**What is your question?**

Although we're not at a release just yet, we should begin looking at switching away from master, and follow a development -> master strategy

**Comment by mpetrunic** [comment]
I think it's best to do it after first release.

**Comment by GregTheGreek** [comment]
Perhaps we should define what a first release looks like?

**Comment by mpetrunic** [comment]
Once we start our testnet, that version should be hotfixed while further developing on dev branch I guess

**Comment by GregTheGreek** [comment]
I'd prefer to keep master as a nighlty branch, and move releases to dedicated branches?
