### ISSUE TITLE
Success parameters for stable Lodestar client 

### ISSUE THREAD

**Issue by ColinSchwarz** [ChainSafe/lodestar#1811]
Stable beacon node
- [x] Lodestar can run on **Mainnet** for 7 days without crashing 
- [x] Lodestar can run on **Pyrmont** for 7 days without crashing 
- [x] Lodestar can perform 2 consecutive syncs on **Pyrmont** without crashing or stalling 

Stable validating beacon node
- [ ] Lodestar validator can run for at least 7 days with near 100% inclusion 
- [ ] All Lodestar validator blocks that are proposed get included

**Comment by twoeths** [comment]
> Lodestar can fun on mainnet for 7 days without crashing

I'd like to see Lodestar to be that stable for Pyrmont too since the number of validators there is much higher than in mainnet. As  number of validators in mainnet keeps increasing, I think we should be prepared for that.

**Comment by dapplion** [comment]
Adding sync speed of other clients here as a reference
![Screenshot from 2020-12-09 12-31-57](https://user-images.githubusercontent.com/35266934/101766769-2badee80-3adb-11eb-911f-7ab29c6a04b6.png)

According to @tuyennhv on Prymont we are at ~2 slots/s

**Comment by wemeetagain** [comment]
an anecdotal datapoint:
I've been running a Pyrmont node for 9 days with no issues.
Also been running a mainnet node for 9 days with no issues.

**Comment by dapplion** [comment]
> an anecdotal datapoint:
> I've been running a Pyrmont node for 9 days with no issues.
> Also been running a mainnet node for 9 days with no issues.

For Pyrmont are you running a validator or only Beacon node?

**Comment by dapplion** [comment]
Lodestar is running in Mainnet with average performance. I would consider Lodestar productionized at this point with still work to do to be as performant as other popular clients
