### ISSUE TITLE
Consider using standard commits for PR titles

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1812]
- We want the release changelog to be auto-generated
- Following standard commits is too annoying

What if we use standard commits syntax but for PR titles. It's a smaller burden and allows editing until it's merged. For example Prysm release changelogs are based on PRs and look very clean and compact https://github.com/prysmaticlabs/prysm/releases/tag/v1.0.0

- Research tooling to automate changelog generation from PR titles
- Research tooling to enforce PR titles follow standard commits syntax

**Comment by dapplion** [comment]
@mpetrunic Would this help and / or be possible with our current release automation?

**Comment by mpetrunic** [comment]
Current release picks pr titles automatically. No idea if it would make much difference
