### ISSUE TITLE
Implement Deposit proof checking

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#182]
**Is your feature request related to a problem? Please describe.**
We don't store or verify deposit proof (merkle tree root).
**Describe the solution you'd like**
Check if hash tree root is calculating proper deposit proofs or implement progressive tree as described [here](https://github.com/ethereum/research/blob/master/beacon_chain_impl/progressive_merkle_tree.py)

**Comment by GregTheGreek** [comment]
On it :)

**Comment by mpetrunic** [comment]
@GregTheGreek I just remembered, the error might occur because of [this](https://github.com/ChainSafe/lodestar/blob/master/src/eth1/wallet.ts#L29).

**Comment by GregTheGreek** [comment]
Yeah thats what i actually want to implement, is that not what this issue is about?

**Comment by mpetrunic** [comment]
TBH, we thought we were missing proper `verifyMerkleBranch` implementation, but I guess we were missing deposit arguments from start :smile:

**Comment by GregTheGreek** [comment]
> TBH, we thought we were missing proper `verifyMerkleBranch` implementation, but I guess we were missing deposit arguments from start 😄

Yeah, this is what I was asking about on the gitter 😆 . So what do you think ahahha

**Comment by mpetrunic** [comment]
https://github.com/ChainSafe/lodestar/blob/master/src/eth1/impl/ethers.ts#L207 this was missing, this is problematic took awhile to remember

**Comment by mpetrunic** [comment]
2nd paragraf explains it:  https://github.com/ethereum/eth2.0-specs/blob/v0.6.0/specs/validator/0_beacon-chain-validator.md#deposits

**Comment by GregTheGreek** [comment]
FYI this is taking me a lot longer than I wanted
