### ISSUE TITLE
Ignore CodeClimate output

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1828]
Is it possible to still run CodeClimate and get the output added to the PR but not count towards the overall PR OK or NOTOK?

**Comment by wemeetagain** [comment]
its marked as "not required", so an :x: vs :heavy_check_mark:  shouldn't count towards mergeability.

**Comment by mpetrunic** [comment]
https://docs.codeclimate.com/docs/github-pull-requests#section-pull-request-review-comments

So we could remove it from ci and just have report as pr comment^^

**Comment by dapplion** [comment]
> https://docs.codeclimate.com/docs/github-pull-requests#section-pull-request-review-comments
> 
> So we could remove it from ci and just have report as pr comment^^

Oh!! That's exactly what we need

**Comment by dapplion** [comment]
> https://docs.codeclimate.com/docs/github-pull-requests#section-pull-request-review-comments
> 
> So we could remove it from ci and just have report as pr comment^^

@wemeetagain Can you set this up since you have permissions?

**Comment by wemeetagain** [comment]
Ok, I believe it's updated properly, will wait until confirmation before closing out the issue

**Comment by 3xtr4t3rr3str14l** [comment]
are we good here to close this out?

**Comment by wemeetagain** [comment]
:+1:
