### ISSUE TITLE
Use tsdoc instead of jsdoc

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#183]
**Is your feature request related to a problem? Please describe.**
Our documentation is lacking, and we haven't identified a direction to go to generate documentation.

**Describe the solution you'd like**
Use [tsdoc](https://github.com/Microsoft/tsdoc)/[typedoc](https://typedoc.org/guides/doccomments/) to generate documentation from the code. It generates documentation directly from the typescript code, and can be supplemented by additional comments.

This would require slight modifications from our current jsdoc comments, but would probably be more powerful in the long run.

**Describe alternatives you've considered**
Use jsdoc and generate documentation from the transpiled javascript code.
This leaves more room for error, doesn't fully leverage our typescript codebase, and makes more work for us.

**Additional context**
https://blog.cloudflare.com/generating-documentation-for-typescript-projects/

**Comment by GregTheGreek** [comment]
Can you find any hosted examples of typedoc?

**Comment by wemeetagain** [comment]
See also: https://github.com/Microsoft/tsdoc

Will look for some hosted examples.

**Comment by wemeetagain** [comment]
from the tsdoc readme, found https://docs.microsoft.com/en-us/javascript/api/sp-core-library?view=sp-typescript-latest
