### ISSUE TITLE
Rename 'this' to chain in eventHandlers

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1874]
Here 
https://github.com/ChainSafe/lodestar/blob/b787fe3cbcb670f1e0d52140540cc33a045313dc/packages/lodestar/src/chain/eventHandlers.ts#L57
`this` is used as a variable name which at least to me appears confusing. Could it be renamed to `chain`? Opening an issue first to know your opinion

**Comment by mpetrunic** [comment]
It's not variable/param, it's keyword. It type hints that `this` context is of type BeaconChain. That typescript syntax is used on methods expected to be used as `handleChainEvents.bind(chain)`.

Tldr cannot be renamed.
