### ISSUE TITLE
Network questions

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1875]
I'm reading the lodestar network code and I have some questions that may be easier to answer with code blocks here in Github.

**eth2RequestEncode serialize error**

`eth2RequestEncode()` is used exclusively here
https://github.com/ChainSafe/lodestar/blob/b787fe3cbcb670f1e0d52140540cc33a045313dc/packages/lodestar/src/network/reqresp/reqUtils.ts#L76
Where the source will have always 1 request max. Then if that single request fails to be serialized the `eth2RequestEncode` will call continue and on the source and what would happen then? Will that request be ignored? Would there be an error downstream? Is that request considered ok, failed or just disappears?

https://github.com/ChainSafe/lodestar/blob/b787fe3cbcb670f1e0d52140540cc33a045313dc/packages/lodestar/src/network/encoders/request.ts#L24-L30

**Comment by dapplion** [comment]
**dialProtocol unreachable clearTimeout**

Here
https://github.com/ChainSafe/lodestar/blob/b787fe3cbcb670f1e0d52140540cc33a045313dc/packages/lodestar/src/network/util.ts#L162-L173

Seems that the finally {} block will never be reached since try {} returns and catch {} throws. Is that correct? Will the timer leak then?

**Comment by mpetrunic** [comment]
We will close output stream and receive bad request (if request method expects request body) on input stream from peer. 

If we would throw error instead of continue, it would make error handling and stream closing a bit more complex.
