### ISSUE TITLE
Refresh Lodestar User Guide

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1881]
**Is your feature request related to a problem? Please describe.**
Documentation page is out of date

Refresh user guide for content and style
Add FAQ / usecases
Add dev guide / ecosystem packages
Add motivation / architecture descriptions / diagrams

**Additional context**
https://docs.ethermint.zone/

**Comment by 3xtr4t3rr3str14l** [comment]
i'm gonna start heading in this general direction

**Comment by 3xtr4t3rr3str14l** [comment]
open to suggestions if anyone has anything more specific or different than what is listed above

**Comment by dapplion** [comment]
User guides were updates 2 months ago and are fairly updated
