### ISSUE TITLE
beacon pool attestations 400 on post

### ISSUE THREAD

**Issue by BeroBurny** [ChainSafe/lodestar#1889]
**Describe the bug**

[submitAttestation](https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar-validator/src/api/impl/rest/beacon/pool.ts) should post array not a single object to enpoint `/eth/v1/beacon/pool/attestations`, as part of [eth2 rest spec](https://ethereum.github.io/eth2.0-APIs/#/Beacon/submitPoolAttestations)

**Steps to Reproduce**
1. start the beacon node on `lighthouse`
2. start HTTP validator to use `lighthouse` beacon node

**Comment by dapplion** [comment]
@mpetrunic Is this still an issue?

**Comment by mpetrunic** [comment]
> @mpetrunic Is this still an issue?

yes, lodestar api is inconsistent with spec there (we should accept array of attestations):
https://ethereum.github.io/eth2.0-APIs/#/Beacon/submitPoolAttestations

**Comment by dapplion** [comment]
> > @mpetrunic Is this still an issue?
> 
> yes, lodestar api is inconsistent with spec there (we should accept array of attestations):
> https://ethereum.github.io/eth2.0-APIs/#/Beacon/submitPoolAttestations

If you are aware of more inconsistencies with the spec could you drop them here or on a new issue? To tackle them all at once

**Comment by mpetrunic** [comment]
That's only one I know of.

**Comment by dapplion** [comment]
Fixed now
