### ISSUE TITLE
Implement one-range-ahead strategy for initial sync

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1921]
One range ahead for regular sync (ORARegularSync) turns out to be good in terms of performance and more maintainable code.

We should implement the same strategy for Initial Sync and maybe refactor ORARegularSync code a little bit to have some common code for both.

**Comment by dapplion** [comment]
Could it be N-range-ahead? Lighthouse uses 4 if I remember.

**Comment by twoeths** [comment]
there is `maxSlotImport` option, we can configure it dynamically and have a suitable default value (64 currently)

**Comment by dapplion** [comment]
Implemented in https://github.com/ChainSafe/lodestar/pull/1961
