### ISSUE TITLE
Implemented hard fork compatible db

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1927]
Since we store everything in ssz format to db, we could end up being unable to read pre fork data.
As suggested in chat, we could add `getTypesByEpoch` method to BeaconConfig. This assumes only time anchored types would change (contains slot or epoch) otherwise we would need another repository.

**Comment by mpetrunic** [comment]
Discord discussion:

wemeetagain12/18/2020
If the fork epoch is part of the params, then the db will have what it needs to serialize/deserialize the right type (at least for state archive)(edited)
[9:59 PM]
we could develop some helper methods on IBeaconConfig / types to return the right type given an epoch:
config.getTypesByEpoch(epoch).BeaconState
(edited)

Marin Petrunić (mpetrunic)12/18/2020
Hmm that's true, gonna experiment with that soon. We will have type issues though. Like what would be return type of getTypesByEpoch 

Marin Petrunić (mpetrunic)Yesterday at 9:19 AM
Yeah, about that, my attempt to modify existing repositories to use different ssz types depending on fork hit a wall. I don't think that approach is good. Values stream and iteration and decode value cannot be adjusted since they work  with raw buffers and they don't and can't have access to time anchor.

I was thinking maybe better way would be to introduce fork version into db keys and have like top level BlockRepository that holds reference to GenesisBlocksRepository, LightclientBlockRepository etc while providing single api to fetch block and depending on fork version it can decide from what repo to request block. When iterating values it would combine streams from all repositories. What do you think?
If you would like, I can move this convo to github discussion?

protoYesterday at 4:44 PM
regarding DB: yes, it definitely makes sense to me to essentially just have different tables of data for each fork, since we are not stuck to a fork forever, it is nice to keep different types of data nicely separated

**Comment by dapplion** [comment]
> LightclientBlockRepository etc while providing single api to fetch block and depending on fork version it can decide from what repo to request block. When iterating values it would combine streams from all repositories.

Is it really necessary to be able to satisfy blocksByRange requests that span multiple forks? Can we force other clients to request from `forkSlot - 64, forkSlot -1`, then `forkSlot, forkSlot +64`?

**Comment by mpetrunic** [comment]
Well you could always open PR on spec but it's not certain it's gonna be accepted. But there are other awkward situations like handling unfinalized blocks which are indexed by root so you would have to ask root -> slot map for every action. 

With approach that I've suggested it ain't gonna be problem anyways

**Comment by dapplion** [comment]
> Well you could always open PR on spec but it's not certain it's gonna be accepted. But there are other awkward situations like handling unfinalized blocks which are indexed by root so you would have to ask root -> slot map for every action.

You right, too many possibilities best to support them
