### ISSUE TITLE
Implement Altair fork transition

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1928]
We should extract running state transition to separate method witch should decide from what fork should state transition be ran.
Since lightclient state transition doesn't have fast implementation for now, we should create stubbed one like:
```ts
fastStateTransition(epochCtx: EpochCtx, state: LightClient.BeaconState): {epochCtx: EpochCtx, state: LightClient.BeaconState} {
   state = runStateTransition();
   epochCtx.loadState(state);
   return {state, epochCtx}
}
```

**Comment by twoeths** [comment]
@mpetrunic are there any obstacles to use fast state transition for lightclient? If it's just a matter of time, I can look into it.

**Comment by mpetrunic** [comment]
> @mpetrunic are there any obstacles to use fast state transition for lightclient? If it's just a matter of time, I can look into it.

You would have to update epochctx balance on couple of places and it would make it harder to follow changes in spec. It really makes no sense to do that as there is no benefit (speed on <100 validator is irrelevant).

At some point (once lightclient spec is solid) there will be updated fast spec we can follow (imo)

**Comment by twoeths** [comment]
I don't see EpochContext manages balance and if we go with the fast state transition, it'd be mostly a 1-1 mapping to the spec. I think there are some benefit:
+ we don't have to call `getActiveValidatorIndices()` which is slow as it's available in the EpochContext/IEpochShuffling
+ when `processSyncCommittee()`, we don't have to call `getSyncCommitteeIndices()` again as we can use `pubkey2index` inside EpochContext and `state.currentSyncCommittee.pubkeys`, and this is per block processing

> At some point (once lightclient spec is solid) there will be updated fast spec we can follow (imo)

we can wait for it but I guess to go with the fast state transition, mainly we keep the same flow and query available data inside EpochContext whenever possible 

@wemeetagain should know better than me, could you also have a look?

**Comment by mpetrunic** [comment]
Spec will probably change rapidly in coming weeks, I really don't see a benefit in maintaining both slow and fast state transition when speed is not relevant factor until there is spec freeze

**Comment by dapplion** [comment]
Altair code fully implemented
