### ISSUE TITLE
Store state only every N epochs

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1931]
**Is your feature request related to a problem? Please describe.**
Currently lodestar takes a lot of disk space, because it stores every new finalized state to disk.

**Describe the solution you'd like**
An alternative would be to store states to disk every N epochs, or at most every N epochs. (I think some clients store as few as 1 state per 8196 epochs)

There's some discussion to be had around how specifically this should/could be accomplished. Here are two ideas.

Proposal 1:
Track epoch of latest stored state in `stateArchive`
On new finalized state: if newEpoch - latestStoredEpoch > N, store new state in `stateArchive`

On boot (eg: inside `BeaconNode#init`) feed any additional archived blocks into the chain.

Proposal 2:
Create a new db bucket or special entry `latestFinalizedState`
On new finalized state, always overwrite `latestFinalizedState`
Track epoch of latest stored state in `stateArchive`
On new finalized state: if newEpoch - latestStoredEpoch > N, store new state in `stateArchive`

On boot, use `latestFinalizedState` as anchor state to init the node.

--
Would like to get feedback / consensus on a direction before implementation.

**Comment by twoeths** [comment]
I would go with proposal 2 as it causes less change to how it works now and we always know the latest finalized state we have, it also makes the reboot process more simpler.

**Comment by dapplion** [comment]
Proposal 2 sounds great. I would go for a mix of both where we store definitively to disk every 8196 epochs and write to this new bucket the latest finalized epoch every 16 epochs. Best of both worlds :)

**Comment by twoeths** [comment]
Right now it takes time to store finalized state (mainly to serialize to `Buffer`), like in Pyrmont: `Archive States epoch #1362  - duration=1012ms` - this is almost the time of an epoch transition . If we don't have to save finalized state regularly it'll definitely help the sync speed.

**Comment by twoeths** [comment]
my latest Pyrmont sync takes 247GB!
