### ISSUE TITLE
Broken links in documentation page

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1935]
**Describe the bug**
Navigate to https://github.com/ChainSafe/lodestar/blob/master/docs/usage/index.md and click on the links, it all lead to 404

**Expected behavior**
It should render respective page/content.

**Comment by dapplion** [comment]
These links are meant to work in MkDocs context https://chainsafe.github.io/lodestar/usage/
If we use the actual name of the file the links break there
