### ISSUE TITLE
Finalized State Upload Script

### ISSUE THREAD

**Issue by ColinSchwarz** [ChainSafe/lodestar#1940]
Using the beacon node API (finalized event and debug state endpoint),
Create a script that fetches every new finalized state, signs and uploads it to S3 or some public space.

 We can then start using these states to launch our beacon node and bypass having to sync from genesis.

**Comment by mpetrunic** [comment]
By script, I meant it could be cli command :)

**Comment by mpetrunic** [comment]
To make it more secure, we can create BeaconState envelope (SignedBeaconState `{message: BeaconState, signature: BLSSignature}`) so that we can have some trusted Chainsafe bls key signing those and we can hardcode that key it in lodestar client so we can verify downloaded state is really produced by Chainsafe.

**Comment by dapplion** [comment]
Update on progress:

https://github.com/ChainSafe/beacon-state-upload

**Comment by mpetrunic** [comment]
> Update on progress:
> 
> https://github.com/ChainSafe/beacon-state-upload

oh, how come it's not part of cli?

**Comment by dapplion** [comment]
> > Update on progress:
> > https://github.com/ChainSafe/beacon-state-upload
> 
> oh, how come it's not part of cli?

I think the goal it to have a script client-agnostic that all clients can run on their CI. So I guess the end goal would be for it to be in bash not JS

**Comment by mpetrunic** [comment]
Don't think that's suppose to be ran in ci 😄

**Comment by dapplion** [comment]
> Don't think that's suppose to be ran in ci

Right I meant some (cloud) instance on a cron job

**Comment by wemeetagain** [comment]
linked with #2177

**Comment by dapplion** [comment]
See https://github.com/ChainSafe/beacon-state-upload

**Comment by 3xtr4t3rr3str14l** [comment]
closing due to favored strategy in #2571
