### ISSUE TITLE
Lightclient db and repositories

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1943]
In light-client package instantiate database using lodestar-db and create repositories for:
- https://github.com/ethereum/eth2.0-specs/blob/dev/specs/lightclient/sync-protocol.md#lightclientsnapshot - single value I guess
- https://github.com/ethereum/eth2.0-specs/blob/dev/specs/lightclient/sync-protocol.md#lightclientupdate

Alternatively we can have one repo for https://github.com/ethereum/eth2.0-specs/blob/dev/specs/lightclient/sync-protocol.md#lightclientstore since we will probably keep it in memory and saving periodically?!

**Comment by dapplion** [comment]
I'm not sure if we want to use a full level-db client for the lightclient consumer. In the short-term we want to run it in a browser or extension and use something like localStorage.

**Comment by mpetrunic** [comment]
> I'm not sure if we want to use a full level-db client for the lightclient consumer. In the short-term we want to run it in a browser or extension and use something like localStorage.

level db can work in browser too. We should probably use indexdb storage instead of localstorage
https://github.com/Level/awesome#stores
