### ISSUE TITLE
Apply gossip attestations to forkchoice

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1949]
As noted in https://github.com/ChainSafe/lodestar/pull/1939#issuecomment-759604120

Currently we don't pass gossip attestations to forkchoice, we need to do it.

**Comment by dapplion** [comment]
Do other client do this @tuyennhv ? Also important to keep in mind that in Prater our node is only able to process about 30% of the total aggregates received through gossip.

**Comment by twoeths** [comment]
yes, lighthouse does that https://github.com/sigp/lighthouse/blob/95ca4ed8f3aea123b44f8cb7cf8deb336bb12766/beacon_node/network/src/beacon_processor/worker/gossip_methods.rs#L110
