### ISSUE TITLE
Slashing offence from API may not be valid after a while

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1957]
If the node operator adds a slashing offense via the API and the node is greedy, when there the node has a chance to propose the slashing offense may no longer be valid. Verify that we re-check validity when building a block and that it doesn't stall the process.

**Comment by 3xtr4t3rr3str14l** [comment]
unstale

**Comment by dapplion** [comment]
Fixed with https://github.com/ChainSafe/lodestar/pull/3134
