### ISSUE TITLE
Introduce app bucket to db

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1964]
We have bucket defined in lodestar-db so all project using lodestar-db shares bucket space and has to edit lodestar-db files.

We could have 1byte app prefix like:
```
enum AppBucket {
   bn = 1;
   validator = 3;
   lightclient = 2;
}
```

So db key would be: `app (1 byte) + repository (4 byte) + id (x bytes)`

That way, each app could share same db and maintain it's own repository buckets without interference.

**Comment by dapplion** [comment]
Wouldn't it be best for bn and validator to have separate db instances (with their own db schemas)? Maybe for the lightclient it makes sense

**Comment by mpetrunic** [comment]
Probably, but accidents happens (or in dev is handy to keep just one db maybe), and if we use same bucket id we would corrupt data

**Comment by dapplion** [comment]
@wemeetagain @mpetrunic Did we reached a conclusion on this?

**Comment by wemeetagain** [comment]
imo the app bucket shouldn't be necessary, for the reason you described (applications with their own db instances), but also because the applications use the same enum for bucket ids (which would prevent overlapping).

**Comment by mpetrunic** [comment]
> imo the app bucket shouldn't be necessary, for the reason you described (applications with their own db instances), but also because the applications use the same enum for bucket ids (which would prevent overlapping).

Se should probably let every app to use own enumerated though

**Comment by dapplion** [comment]
Closing since we are not following this proposal on the Altair code so far. Please re-open if you think it should still be pursued
