### ISSUE TITLE
Add voluntary exit functionality to the CLI

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1970]
Nice to have to clean-up after testing Pyrmont.

**Comment by 3xtr4t3rr3str14l** [comment]
do you mean that you'd want a flag or something like that to add as an option to perform a voluntary exit once the node process is quit?  or maybe just something to perform a voluntary exit in general regardless of when it would be ran?  just trying to clarify the intent here

**Comment by dapplion** [comment]
> do you mean that you'd want a flag or something like that to add as an option to perform a voluntary exit once the node process is quit? or maybe just something to perform a voluntary exit in general regardless of when it would be ran? just trying to clarify the intent here

You can take a look at the Pyrsm CLI which has this functionality. It should be done upon express intention of the users with a command similar to
```
lodestar accounts voluntary-exit
```
