### ISSUE TITLE
Run Validators on Pyrmont

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1971]
**Is your feature request related to a problem? Please describe.**
We want to add lodestar validators to Pyrmont to test out validator capabilities (#1811)

**Describe the solution you'd like**
- [ ] sync 2 pyrmont beacon nodes
- [ ] submit 32 deposits
- [ ] run 16 validators per node
- [ ] Monitor included attestations + blocks

**Describe alternatives you've considered**
- Ask someone in eth2 community for a few exported validators

**Comment by dapplion** [comment]
On going effort
