### ISSUE TITLE
Run unit tests in parallel

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1977]
Currently lerna runs in ci unit tests from every package sequentially. To improve CI times, we should add `--parallel` flag to `test:unit` and `lint` script in root package.json

**Comment by dapplion** [comment]
That blows up my laptop hahaha gets frozen immediately and requires a forced reset

**Comment by mpetrunic** [comment]
really?!  Works fine with me and on couple of other projects. Gonna push to see how CI handles it

**Comment by mpetrunic** [comment]
## Results:
### test:unit
```
Old:
real    1m51,055s
user    4m33,545s
sys     0m7,528s

New:
real    2m18,850s
user    3m43,648s
sys     0m4,859s
```

### lint:
```
Old:
real    1m42,276s
user    4m7,565s
sys     0m8,743s

New:
real    1m8,999s
user    4m59,701s
sys     0m10,773s
```

**Comment by dapplion** [comment]
> really?! Works fine with me and on couple of other projects. Gonna push to see how CI handles it

Same for other js projects, not only Lodestar. I actually have to build the source with `--concurrency 1` or I have a 25% chance of freezing my laptop.

Would be cool to have some way to configure lerna in each environment so you can run with full parallelization and me with none without modifying a committed file

----

For context, my laptop
```
NAME="Linux Mint"
VERSION="19.1 (Tessa)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.1"
VERSION_ID="19.1"
VERSION_CODENAME=tessa
UBUNTU_CODENAME=bionic
```
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               142
Model name:          Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
Stepping:            10
CPU MHz:             800.030
CPU max MHz:         3400,0000
CPU min MHz:         400,0000
BogoMIPS:            3600.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            6144K
NUMA node0 CPU(s):   0-7

```

**Comment by mpetrunic** [comment]
@dapplion maybe some kernel bug, do you have latest?

**Comment by dapplion** [comment]
> @dapplion maybe some kernel bug, do you have latest?

Updated yesterday to latest `5.4.0-64-generic` and so far it hasn't crashed :+1: 

However, the interlaced output is not pretty and may make things harder to debug if a test fails. I didn't noticed a significant speed increase overall running with --parallel. The units tests in lodestar package just dominate always

**Comment by mpetrunic** [comment]
Maybe it would be better if we ran all tests except lodestar in parallel. Like:
```json
   "test:unit": "lerna run --parallel --except @chainsafe/lodestar test:unit && lerna run --scope @chainsafe/lodestar test:unit"
```

**Comment by dapplion** [comment]
How many seconds would we save with that?

**Comment by mpetrunic** [comment]
> How many seconds would we save with that?

13s (1m22s vs 1m35s)

**Comment by dapplion** [comment]
> > How many seconds would we save with that?
> 
> 13s (1m22s vs 1m35s)

In my subjective opinion, it's not worth it
