### ISSUE TITLE
Separate profiling from logging

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1981]
**Is your feature request related to a problem? Please describe.**
Currently we're using a feature of `winston` logger to profile block and state archival. Unfortunately this is not very customizable and always pollutes the logs. It is also not easy to export these profiles to other places, eg: metrics.

**Describe the solution you'd like**
Do profiling separately from logging, using separate tooling.
We can then log the results under a high logging level and create/populate additional metrics that track profiling results.

**Comment by dapplion** [comment]
I would consider this fixed. All logger.profile have been removed and we have a decent amount of metrics timing ops. If we happen to need to time a specific thing open an issue will add metrics to it
