### ISSUE TITLE
Convert Throws to logger.fatal

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/lodestar#199]
**What is your question?**

Currently we are using `throw()` by default for critical errors. I'm proposing that we add a `fatal` method to the logger and use `logger.error` +  `process.exit(1)`. 

Not sure if this have any unforeseen issues, happy to discuss.

**Comment by wemeetagain** [comment]
I don't think there are many exceptions thrown where we want to exit the process.
It makes sense in certain scenarios though.

**Comment by GregTheGreek** [comment]
Hmm I'm just thinking, from my experience with geth/parity there's quite a few places where we would.

- database doesn't save a value, we most definitely want to exit.
- During the CLI process
- perhaps even collecting deposits, if we miss one we might want to throw and restart the chain, at least in an early version of Lodestar

**Comment by mpetrunic** [comment]
process.exit(1) is a bit weird since we need to call `stop` method on everything.

**Comment by GregTheGreek** [comment]
We could try and stopp everything? then process.exit?
I'm not sure what that would look like

**Comment by mpetrunic** [comment]
Maybe something like this.
https://stackoverflow.com/questions/14031763/doing-a-cleanup-action-just-before-node-js-exits

Although that would be best if it were in commander library
