### ISSUE TITLE
Requesting future duties

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1998]
https://github.com/NodeFactoryIo/ChainGuardian/issues/454

I wonder if someone has some idea why lodestar-validator would request duties in the future. Didn't we change it to wait for block?

**Comment by morrigan** [comment]
Hey guys, any info on this?

**Comment by BeroBurny** [comment]
> [NodeFactoryIo/ChainGuardian#454](https://github.com/NodeFactoryIo/ChainGuardian/issues/454)
> 
> I wonder if someone has some idea why lodestar-validator would request duties in the future. Didn't we change it to wait for block?

notice this is happening when the hardware is under load, which is pretty weird why validator is going in the future :man_shrugging: 
can someone explain why is this happening

**Comment by dapplion** [comment]
@mpetrunic Is this still happening?

**Comment by mpetrunic** [comment]
We don't have hardware under load anymore so not. Seems like when under high pressure, clock gets screwed.
