### ISSUE TITLE
Add validator client metrics

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#2007]
We do have validator monitor metrics, related to performance of validators in the Eth2.0 protocol (profitability, attestation performance)

However this issue refers to validator client metrics, which may include:

- VM stats: CPU, RAM, event loop lag, GC runs
- Signer metrics: total signed items, signature errors
- API client metrics: response times, timeouts, error count
- Slashing protection DB metrics

**Comment by mpetrunic** [comment]
pretty sure this is resolved

**Comment by dapplion** [comment]
> pretty sure this is resolved

We do have validator monitor metrics, related to performance of validators in the Eth2.0 protocol (profitability, attestation performance)

However this issue refers to validator client metrics, which may include:
- VM stats: CPU, RAM, event loop lag, GC runs
- Signer metrics: total signed items, signature errors
- API client metrics: response times, timeouts, error count
- Slashing protection DB metrics

etc

**Comment by dapplion** [comment]
Relevant items to track in the validator:
- Is the connected beacon chain too busy / slow?
- Is the validator client too busy signing that it's delayed? May happen when it has attached a large number of keys
- Is there any config issue such that the beacon chain rejects signatures?
