### ISSUE TITLE
Lodestar Roadmap 2021 🌟

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#2026]

**Comment by ColinSchwarz** [comment]
## Output
1. Have light client prototype with the following deliverables
    - Merkle proof generation (`Type.getMerkleProof(value: T, paths: Path[]): Proof`)
    - Merkle proof consumption (`Type.fromMerkleProof(proof: Proof): T`)
    - Simple network req/resp protocol to get merkle proofs (either libp2p req/resp or rest) `(root, paths) => proof`
    - Maintain light client state in "light client", wrap req/resp protocol + inject state to return ssz partials
    - nice to have: Proper handling of ssz extentions (both generation and consumption) (eg: navigating through multiple objects)
4. Implement light client hard fork
6. Enable signature verification and do what is needed for system to continue to function correctly 
8. Improve docs starting with most used such as BLS, gossipsub, SSZ, user docs for 
9. Update docs flow to optimize for teaching new eth2 typescript  devs 

## Outcome 
- Run at least a single Lodestar beacon node and validator on mainnet
- Resolve or mitigate light client open questions including: 
    - monitization research including zolt's
    - language for requesting proofs
    - proof serialization
    - networking 
    - peer discovery
    - end-user light client UX issues
    - end-user light client incentive issues
    - eth2 consensus data vs L2 data
    - What are the differences between an end-user light client and a consensus-level light client?
    - How to kate commitments / data availability relate to end-user light clients?
- Possibly: expand website offerings
    - Modified simplified Lodestar nodes that allows users to inspect the beacon state as it is updated. Semi-interactive block explorer based on our node.
    - Light client demo: app is block explorer that uses light client proofs 
- Participate in specing light client 
- Investigate usage of BLST in browser and choose between BLST and Herumi 
- investigate and prototype KZT commitments/proofs 
- keep up to date with entire spec 
- establish and collect more metrics

**Comment by wemeetagain** [comment]
closing in favor of #2044
