### ISSUE TITLE
Add eslint rule require-await

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#2031]
Add https://eslint.org/docs/rules/require-await in a subsequent PR

_Originally posted by @dapplion in https://github.com/ChainSafe/lodestar/issues/2030#issuecomment-775288815_

**Comment by dapplion** [comment]
I think we should not adopt this rule. In many places we want to return a always return a promise for API requirements but don't actually use await. The other rules around await work great for now.
