### ISSUE TITLE
Run permanent node in cloud with Alerts

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2035]
- [x] Fix dockerhub image builds, build on master and tag
- [x] Setup a node + validator on Pyrmont to Contabo
- [x] Setup watchtower to update automatically
- [x] Setup Grafana alerts to Discord

**Comment by 3xtr4t3rr3str14l** [comment]
got a beacon node running on contabo-2.  trying to get the validator set up on there too

**Comment by dapplion** [comment]
Just setup a node at contabo-1. If you want  @3xtr4t3rr3str14l  you can setup a validator there, right now there's only the node

**Comment by 3xtr4t3rr3str14l** [comment]
@dapplion  sure, i'll set it up there instead.

**Comment by mpetrunic** [comment]
I have no idea how this reopened 😄
