### ISSUE TITLE
Address eslint/await-thenable warnings

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2043]
Remove `await` from unnecessary statements. Run `yarn lint` and look for 
```
warning  Unexpected `await` of a non-Promise (non-"Thenable") value  @typescript-eslint/await-thenable
```

Then change the level of `@typescript-eslint/await-thenable` to error

**Comment by mpetrunic** [comment]
resolved with https://github.com/ChainSafe/lodestar/pull/2066
