### ISSUE TITLE
Code style: Omit public modifier

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2070]
To make our codebase consistent, should we omit the `public` modifier since it's the default? 

YES: Respond :+1: 
```ts
class Example {
  num: number
}
```

NO: Respond :-1: 
```ts
class Example {
  public num: number
}
```

Ref: https://www.typescriptlang.org/docs/handbook/classes.html#public-by-default

**Comment by mpetrunic** [comment]
Im quite divided on that.
On one hand if there isnt modifier I always assume "protected" (no idea why)

On other hand, less code.
