### ISSUE TITLE
Code style: Arrow function in tests

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2071]
To make our codebase consistent, should we use arrow functions in tests when it's not necessary to access `this`?

YES: Respond :+1: 
```ts
it("example", () => {
  ...
})
```

NO: Respond :-1: 
```ts
it("example", function () {
  ...
})
```

Ref: https://www.typescriptlang.org/docs/handbook/classes.html#public-by-default

**Comment by mpetrunic** [comment]
Probably wrong link, but mocha recommends not using arrow functions since 'this.timeout' wont work

Ref: https://mochajs.org/#arrow-functions

**Comment by dapplion** [comment]
> Probably wrong link, but mocha recommends not using arrow functions since 'this.timeout' wont work
> 
> Ref: https://mochajs.org/#arrow-functions

That's the point on this issue, only use function when you need to access `this`

**Comment by mpetrunic** [comment]
wouldn't not using arrow functions in tests at all make our codebase more consistent?

**Comment by dapplion** [comment]
> wouldn't not using arrow functions in tests at all make our codebase more consistent?

We can be consistent to the rule: "Use arrow functions except when this is needed". Accessing this.timeout is rare in tests and the `function` keyword adds more cognitive load

**Comment by 3xtr4t3rr3str14l** [comment]
i've almost always used arrow functions in mocha tests, but i didn't know about the `this` problem.  personally, i'd prefer consistency and deal with the negligible cognitive load.

**Comment by dapplion** [comment]
> Probably wrong link, but mocha recommends not using arrow functions since 'this.timeout' wont work
> 
> Ref: https://mochajs.org/#arrow-functions

I've tried and if you use `this.timeout` with arrow functions Typescript won't compile so the recommendation only affects non-Typescript projects

**Comment by dapplion** [comment]
Closing for lack of support
