### ISSUE TITLE
Use `config.getTypes` where applicable

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#2075]
**Is your feature request related to a problem? Please describe.**
After #2073, lodestar explicitly uses `phase0` types everywhere.
There's an exercise that needs to be done to make lodestar HF-ready.
IMO should wait until we've merged the `lightclient` branch into master and actually have multiple versions of types.

**Describe the solution you'd like**
Wherever multiple versions of an object may be in use, use `config.getTypes` instead of `config.types.phase0`.

eg: in API, returning a `BeaconState` (in the debug API), wherever it said `config.types.phase0.BeaconState.toJson(state)`, replace that with `config.getTypes(state.slot).BeaconState.toJson(state)` (This may require the return types of the API to also change)

**Comment by dapplion** [comment]
@wemeetagain What's the progress with this?

**Comment by dapplion** [comment]
Done
