### ISSUE TITLE
Extract test utilities to separate private package

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#2076]
**Is your feature request related to a problem? Please describe.**
`lodestar-validator` tests depend on `lodestar` test utilities.

**Describe the solution you'd like**
Extract test utilities to a private package, eg: `test-utils`

**Describe alternatives you've considered**
Keep as is

**Additional context**
See https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar-validator/test/unit/services/block.test.ts#L4

**Comment by dapplion** [comment]
@wemeetagain How would the dependency graph look like? Do this utils depend on `lodestar`?

**Comment by wemeetagain** [comment]
I'd like the utils to just rely on `lodestar-beacon-state-transition`. These utils would aid in creating different test chains, chain objects, etc.
