### ISSUE TITLE
Multi-thread sim tests - random node falls behind in sync

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2081]
Often when running the multi-thread sim tests one of the four nodes falls behind and never recovers. Why does this happen?

```
2021-02-21 15:38:15 [NODE 0]           info: Synced - finalized: 0 0x0000…0000 - head: 35 0x21bb…fe78 - peers: 3
2021-02-21 15:38:15 [NODE 3]           info: Synced - finalized: 0 0x0000…0000 - head: 1 0xb53c…c95f - peers: 3
2021-02-21 15:38:15 [NODE 1]           info: Synced - finalized: 0 0x0000…0000 - head: 35 0x21bb…fe78 - peers: 3
2021-02-21 15:38:15 [NODE 2]           info: Synced - finalized: 0 0x0000…0000 - head: 35 0x21bb…fe78 - peers: 3
```

Attached, are logs from a failed sim test

[8_Simulation multi thread test.txt](https://github.com/ChainSafe/lodestar/files/6018025/8_Simulation.multi.thread.test.txt)

**Comment by dapplion** [comment]
Related to https://github.com/ChainSafe/lodestar/pull/2067#issuecomment-782867909

**Comment by twoeths** [comment]
I see some `BLOCK_ERROR_PARENT_UNKNOWN` errors in the log.
@dapplion what's the reason to remove `getMissingAncestor` in https://github.com/ChainSafe/lodestar/pull/2099?

**Comment by dapplion** [comment]
> I see some `BLOCK_ERROR_PARENT_UNKNOWN` errors in the log.
> @dapplion what's the reason to remove `getMissingAncestor` in #2099?

The error contains the parentRoot, so it's not necessary to retrieve it
```ts
const parentRoot = err.type.parentRoot;
```
I understand that was the purpose of that method.

**Comment by twoeths** [comment]
`pendingBlocks` maybe a chain segment like block b, b+1,..., b+n . So when the next block comes at the end, we want to get parent of block b, which is the missing ancestor of the chain segment, instead of block `b+n` which we already have. And `getMissingAncestor()` was for that purpose.

**Comment by twoeths** [comment]
for the root cause of this issue, I think it's because Node 3 (in the log) got stuck at orphaned block 1, similar to what we see in the unit test https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/test/unit/chain/forkChoice/forkChoice.test.ts#L28

It seems to me that we did add attestations to forkchoice but initially we did not initial justified balances correctly and they are all 0 https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/chain/forkChoice/forkChoice.ts#L40

**Comment by twoeths** [comment]
Reproduced with the debug log 
[multiThread.debug.log](https://github.com/ChainSafe/lodestar/files/6129621/multiThread.debug.log)
