### ISSUE TITLE
HF TODOs

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#2085]
With HF code safely namespaced and #1862 merged, we can incrementally (and safely) add HF support to `master`.

Some items RE forking that are left TODO (Somewhat in dependency order)
- RE state transition library
  - [x] Finish naive lightclient state transition (#2045)
  - [x] Add fast lightclient state transition (will require slightly extending fast utils)
  - [x] Integrate lightclient spec tests
  - [x] Create top-level naive + fast state transition (something that works for all forks)
- RE lodestar + validator
  - [x] Replace relevant `phase0` interface input/output with `allForks` types
  - [x] Replace relevant ssz types with `getType` (#2075)
  - [x] Use multi-bucket db repositories + create any additional (they exist, not currently in use)
  - [x] Replace phase0 state transition w 'top-level' fast state transition
  - [x] Update validator interaction (block/attestation/etc production) + validator side
  - [x] Add gossip validation + handlers for lightclient fork
- RE whole project
  - [x] Once the lightclient patch HF gets a name, we might find/replace `lightclient`/`Lightclient` throughout the project and rename.

_Originally posted by @wemeetagain in https://github.com/ChainSafe/lodestar/issues/1862#issuecomment-783480523_

**Comment by dapplion** [comment]
Part of https://github.com/ChainSafe/lodestar/issues/2388

**Comment by dapplion** [comment]
Completed
