### ISSUE TITLE
Use PascalCase for type namespaces

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#2091]
Currently we export type namespaces as camelcase as well as beacon state transition which casues name conflicts when importing. I would propose to use PascalCase for type exports so we can avoid that and it's more clear what is imported.

**Comment by wemeetagain** [comment]
My current thought (which is currently implemented for `phase0`) is to re-export the types in the state transition package.
```ts
import {phase0} from "@chainsafe/lodestar-beacon-state-transition";
const x: phase0.BeaconState;
phase0.fast.stateTransition(...);
```

**Comment by mpetrunic** [comment]
Seems confusing still though and we would need to be careful to import phase0 from correct package

**Comment by wemeetagain** [comment]
> Seems confusing still though and we would need to be careful to import phase0 from correct package

IMO its not been confusing in practice. Been using it and loving it.
I think using the same name, treating them as philosophically same namespace, is actually quite ergonomic. Its the same name, _everywhere_, just with an option to import a smaller subset (just types) if required. (It's somewhat similar to the ergonomics of the pyspec, but with more published packages)

It's also been quite convenient for refactoring. eg: "find and/or replace in file/folder/entire-project/etc phase0". "Add the phase0 state transition import, code stays the same".

IMO the subtlely different names creates a difference, but I'm not sure what we get from the tradeoff. One one hand, we're able to immediately detect that a variable comes from a specific package. But we lose the unity of the fork names being used everywhere.

Also not sure that pascal case is enough of a difference to quench the confusion. `Phase0` vs `phase0`, the confusion about which import to use gets replaced with confusion about what's different between the two cases, which to use in which case, and why one is pascal case vs camel case.

**Comment by dapplion** [comment]
I'm okay with `phase0`, despite not complying with standard type casing Typescript will ensure we don't miss use the variable

**Comment by dapplion** [comment]
Closing since we have sticked to this approach for a while. Please feel free to re-open if some issue arises or you strongly disagree
