### ISSUE TITLE
Dangerous try / catch all in lodestar-db

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2139]
Lodestar-db has a try / catch that swallows all errors, without doing any triage first. Is this expected? Can we define what types of errors do we want to ignore and catch only those?

https://github.com/ChainSafe/lodestar/blob/a5973ea9551e3feae25a9c53d04d73616fe1d770/packages/lodestar-db/src/abstractRepository.ts#L54-L56

**Comment by wemeetagain** [comment]
We probably can remove the try/catch entirely.
I think it was originally there to convert "not-found" errors into null. Thats done within the leveldb `IDatabaseController` tho.
