### ISSUE TITLE
Use rimraf instead everywhere / Support developing lodestar on windows

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#2148]
should we use rimraf instead everywhere? It would be nice to support developing lodestar on windows?

_Originally posted by @mpetrunic in https://github.com/ChainSafe/lodestar/pull/2136#discussion_r589644340_

**Comment by g11tech** [comment]
there are a few alternatives: git bash works very well, windows also has a good linux subsystem support now (wsl/wsl2)

**Comment by dapplion** [comment]
We are using rimraf wherever possible now
