### ISSUE TITLE
Add metric to track forking

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#2152]
**Is your feature request related to a problem? Please describe.**
One step towards having a good state cache pruning strategy is tracking the amount of forking that our node is experiencing.
During low-forking situations, our cache may be much smaller. But during high-forking situations, we likely need to keep more states around.

**Describe the solution you'd like**
As a first step, add metric(s) to track the amount of forking we're seeing.
Possibly also metrics tracking the amount of state regen.

**Comment by g11tech** [comment]
@dapplion @wemeetagain  the forking metric will be covered in the fork-choice metric PR (newHead vs newFork) in update head , assign for state regen!

**Comment by dapplion** [comment]
This specific metric is spec-ed. Checkout the eth2.0 spec for metrics to ensure it's ok

**Comment by g11tech** [comment]
@dapplion state regen metric is required for now?

**Comment by dapplion** [comment]
Done
