### ISSUE TITLE
Add eslint rule to enforce _not_ using the public keyword

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#2162]
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-member-accessibility.md

'no-public'

_Originally posted by @mpetrunic in https://github.com/ChainSafe/lodestar/issues/2159#issuecomment-796636686_

**Comment by mpetrunic** [comment]
I thinks its already added to dapplions pr
