### ISSUE TITLE
Remove libp2p-ts types

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#2167]
**Is your feature request related to a problem? Please describe.**

We're maintaining our own hand-crafted types separately from many of the libp2p dependencies.
This is a maintenance burden and leads to problems when the types are subtlely wrong, outdated, or incomplete.
It would be much better if long-term, we use the upstream types, pushing our types upstream as necessary.

**Describe the solution you'd like**

Remove libp2p-ts
Debug and fix type issues as they arise
Push types upstream
Only maintain types locally (within this monorepo) as needed

**Describe alternatives you've considered**

Status quo.

**Additional context**

See things like: https://github.com/ChainSafe/lodestar/pull/2164#discussion_r593330950

**Comment by vasco-santos** [comment]
FYI I am doing a new iteration on libp2p core with the latest developments in aegir https://github.com/libp2p/js-libp2p/pull/904

**Comment by dapplion** [comment]
@vasco-santos 
![12nkvn (1)](https://user-images.githubusercontent.com/35266934/112847005-e96ae600-90a6-11eb-8230-d680a1f27eb3.jpg)
