### ISSUE TITLE
Serve Weak Subjectivity State

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#2177]
**Is your feature request related to a problem? Please describe.**

We would like to upload certain historical states, weak subjectivity states, to the cloud, for use in bootstrapping sync.

**Describe the solution you'd like**

We need to expand our debug/states API endpoint to be able to serve historical checkpoint states at weak subjectivity epochs.
Currently, the endpoint just checks our state cache, 404s if the requested state is not found.

**Additional context**

See https://notes.ethereum.org/@adiasg/weak-subjectvity-eth2#Weak-Subjectivity-Checkpoint

**Comment by twoeths** [comment]
I suppose we can do state regen in a separate Worker Thread.

**Comment by dapplion** [comment]
Week in Ethereum News, March 21, 2021 mentioned this:

- https://github.com/adiasg/eth2-ws-provider
- https://eth2-fork-mon.stokes.io/#nav-ws-data

@wemeetagain is this relevant to this issue's effort?

**Comment by dapplion** [comment]
From https://github.com/ChainSafe/lodestar/pull/2316#issuecomment-812226504

---

> Looks good! @wemeetagain What's the next step now? Where should this function be used?

Depending on the route we go next, we may not need to use this, its just nice to have.

The end goal is to have infrastructure in place to provide syncing by weak subjectivity checkpoint+state "by default" for our beacon node, similar to the experience we currently give for starting from genesis.

Imo we can break the problem down into a few parts: creating the ws state, distributing the ws state, loading the ws state.

As far as creating the state, we use something like https://github.com/adiasg/eth2-ws-provider (which just uses the standard API) or add a custom API endpoint to retrieve the weak subjectivity state.

As far as serving the state, it would be nice to use IPFS or similar to leverage existing ChainSafe Files tooling.

And whatever the distribution, we will need to extend our CLI to do this fetch of the ws state on initial boot.

**Comment by 3xtr4t3rr3str14l** [comment]
@wemeetagain is this function here the only thing we really need for the creation step?
https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/weak-subjectivity.md#calculating-the-weak-subjectivity-period

if so, maybe we just implement that function and then create an API endpoint that calls that function?

**Comment by 3xtr4t3rr3str14l** [comment]
main weak subjectivity sync initialization was merged in #2571 , but we can still do more once we have #2637

**Comment by 3xtr4t3rr3str14l** [comment]
actually, backfill sync is a separate issue, so no need to keep this open since this is only for serving the ws state, which is resolved/finished, as stated previously.
