### ISSUE TITLE
Beacon Blocks Array is retained in Promise

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2180]
**Describe the bug**

This is from a heap snapshot after I sync Pyrmont
<img width="1001" alt="retained_Tree_Array" src="https://user-images.githubusercontent.com/10568965/111411340-f386ff00-870c-11eb-9582-ebd685dd7a1f.png">

**Expected behavior**

The Tree (and handler) and the Promise should not be retained in memory.

**Steps to Reproduce**

+ Sync Pyrmont

**Desktop (please complete the following information):**

- Commit hash: a855a08

**Comment by twoeths** [comment]
the retained Tree Array is actually the Block array
<img width="1129" alt="Screen Shot 2021-03-26 at 13 53 54" src="https://user-images.githubusercontent.com/10568965/112593935-c63bfe80-8e3a-11eb-8846-b1b426cdb101.png">

we should wait for the WeakRef work in persistent-merkle-tree being used in lodestar and check again https://github.com/ChainSafe/persistent-merkle-tree/pull/26#event-4511854100

**Comment by dapplion** [comment]
> we should wait for the WeakRef work in persistent-merkle-tree being used in lodestar and check again ChainSafe/persistent-merkle-tree#26 (comment)

@tuyennhv Could you check again when possible?

**Comment by twoeths** [comment]
hasn't seen that for a while, closing the issue
