### ISSUE TITLE
Tree Object is retained in Promise

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2182]
**Describe the bug**

This is from a heap snapshot after I sync Pyrmont
<img width="1217" alt="retained_Tree_Object" src="https://user-images.githubusercontent.com/10568965/111413032-11099800-8710-11eb-8205-51600a00c1b2.png">

Note that this is a Tree object instead of a Tree Array in #2180 

**Expected behavior**

The Tree object and Promise are not retained in memory

**Steps to Reproduce**

+ Sync Pyrmont and take heap snapshot

**Desktop (please complete the following information):**

- Branch: master
- Commit hash: a855a08

**Comment by dapplion** [comment]
This seems to be fixed completely with https://github.com/ChainSafe/persistent-merkle-tree/pull/26
