### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2209]
At least this util is dead code and could be removed https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/util/io.ts

It would be nice to run [`ts-prune`](https://www.npmjs.com/package/ts-prune) on each package of the monorepo to find and delete dead code

**Comment by sonidhruv** [comment]
hello, i am new to open source. and i wanted to work in open source project. 
can anyone guide me?

**Comment by dapplion** [comment]
Hi @sonidhruv ! For sure, if you are interested in contributing you can take this issue! Feel free to ask any doubts here or in discord  https://discord.gg/yjyvFRP

**Comment by sonidhruv** [comment]
Thanks @dapplion !!!! can you help me to understand this issue?

**Comment by dapplion** [comment]
> Thanks @dapplion !!!! can you help me to understand this issue?

Yes! So after so many months (years) of work there are files and code that's no longer used. The tool `ts-prune` scans the project and find that unused files and functions. Then you could remove them to make the project nicer, cleaner and easier to navigate for upcoming future contributors :+1:

**Comment by elijahhampton** [comment]
@dapplion Looks like no one is assigned to this - I'm pretty open this weekend.  Feel free to assign me to this issue!

**Comment by wemeetagain** [comment]
@elijahhampton I assigned it to you, go for it :)

**Comment by elijahhampton** [comment]
@wemeetagain @dapplion I forgot about this, but recently I've been on and off working on it.  Any suggestions on how to go about cleaning this up?  There are a large amount of file dependencies across the repo.

**Comment by dapplion** [comment]
> @wemeetagain @dapplion I forgot about this, but recently I've been on and off working on it. Any suggestions on how to go about cleaning this up? There are a large amount of file dependencies across the repo.

Just delete anything that's not used I will review each deletion to ensure it's really not needed.

**Comment by dapplion** [comment]
Bump @elijahhampton

**Comment by wslyvh** [comment]
Not sure if this is a great first-issue as you need a good understanding of the codebase and how/where code is used.
Because of the monorepo and imports/references through your packages tools like ts-prune don't work.
It's also impossible to track if (and how) code is used by external parties who've installed your your libraries. 
So any removal would mean breaking changes and major updates?

I'd be happy to dive in tho if you have any suggestions or tips

**Comment by wemeetagain** [comment]
If you want to tackle this issue, I think starting from code with now usage in the monorepo would be a good place to start.
You might link to your findings here and just get confirmation from us whether each is :+1:  or :-1: for removal.

**Comment by philknows** [comment]
Removing dead code should be consistently done throughout interacting with the codebase. Please be aware and remove your own unused/deprecated code.  This issue is too broad.
