### ISSUE TITLE
computeNewStateRoot verifySignature = true ?

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2224]
**Describe the bug**

When running a beacon node with many validators (512) `assembleBlock` appeared slow and doing signature verification. All data used to produce the block should be verified, is it necessary to verify the signatures? Is this a typo? 

```ts
phase0.fast.processBlock(postState, block, true)
                                           ^^^^
```

https://github.com/ChainSafe/lodestar/blob/0bddc7ac75a0fab0356d29ebce6ea14f94a96458/packages/lodestar/src/chain/factory/block/index.ts#L43-L49

![Screenshot from 2021-03-23 10-41-10](https://user-images.githubusercontent.com/35266934/112126238-8966d200-8bc4-11eb-8fe7-13d566ea30db.png)

**Comment by twoeths** [comment]
that's mainly to compute new state root for the produced block so I think we don't have to verify signatures there

**Comment by wemeetagain** [comment]
If all of the the ops have already been verified, we don't need to do it again here. :+1:
