### ISSUE TITLE
toBlockSummary performance

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2226]
**Describe the bug**

Everytime someone requests the head of the chain, 4 32 bytes string have to be converted from string to bytes.

When running a beacon node with many validators (512) 0.8% (400 ms / 45000 ms) of total CPU was spent in `toBlockSummary`. It's not a lot but seems like it a lot of wastefull computations since the head doesn't change that often.

**Proposed solution**

Could we store the head both as strings and bytes and expose the already parsed object?

**Comment by wemeetagain** [comment]
More generally, this is an issue anywhere we're indexing data by root.
Because we can't key objects/maps by Uint8Array, we're forced to convert between Uint8Array and string at the interface boundary.

**Comment by dapplion** [comment]
After optimizing toHexString() we got a x10 improvement. Re-open if toBlockSummary is still an issue now
