### ISSUE TITLE
remove duplicate/erroneous beacon attestation topic grafana metric guage

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#2229]
Under Lodestar Grafana Dashboard under "Gossip Stats"

remove the beacon_attestation metric in this screenshot
![Screenshot from 2021-03-23 09-56-59](https://user-images.githubusercontent.com/32028745/112167214-46a1fb80-8bbe-11eb-8cc8-ad185cb256cb.png)

but keep this one
![Screenshot from 2021-03-23 09-57-19](https://user-images.githubusercontent.com/32028745/112167229-4a358280-8bbe-11eb-8df5-28d6dbd84182.png)

**Comment by dapplion** [comment]
Fixed in current metrics
