### ISSUE TITLE
Add more resolution to log timer

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#2231]
**Is your feature request related to a problem? Please describe.**

Current logs print time with resolution at the second.

**Describe the solution you'd like**

We would like finer resolution (eg: millisecond-level)

`2021-03-22 23:35:27` -> `2011-10-05T14:48:00.000Z`

**Comment by dapplion** [comment]
Lighthouse logs for content, maybe even nicer than ISO string
```
Mar 23 18:17:28.564 INFO Successfully published attestations     type: unaggregated, slot: 1287, committee_index: 34, head_block: 0x046c1c39e2a73666659df995755ce44dc3247bc5a636afa0b20218e2ca50cb92, count: 1, service: attestation
```

**Comment by g11tech** [comment]
I would prefer it to be easily loadable to date object and closer to ISO. how about? 
1) 2021-Mar-23 18:17:28.564 or
2) 2021-03-23 18:17:28.564  
i prefer the 1).
