### ISSUE TITLE
Prater logs - Clock drift - what to do

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2240]
**Describe the bug**

During Prater genesis our Beacon node could not handle the requested load with event loop lag delays between 30-90 seconds.

As a result clock could not keep up. See below genesis was at `15:00:00`, so the clock is about 37 slots late.
```
2021-03-23 15:08:24 [CHAIN]         verbose: Clock slot slot=5
```

What should the node do if this happens? 
- Should it try to auto-correct somehow?
- Should it crash and stop the program?
- Should the clock be strictly sequential or allow to jump ahead multiple slots?

---

Some more fun logs from Prater

```
2021-03-23 15:18:18 [API]              info: Started rest api server address=http://127.0.0.1:9596
2021-03-23 15:18:18 [CHAIN]         verbose: Clock slot slot=89
2021-03-23 15:18:18 [CHAIN]         verbose: Clock slot slot=90
2021-03-23 15:18:18 [CHAIN]         verbose: Clock slot slot=91
```

**Comment by twoeths** [comment]
since we added `await sleep(0)` in our job queue, I guess it's not an issue anymore?

**Comment by dapplion** [comment]
Hopefully not, we'll see when the EF wants to do a testnet with 1048576 validators

**Comment by dapplion** [comment]
After moving BLS verification to a separate thread, there's not much else we can't do. Queues seem to protect us well to when the node becomes too overloaded
