### ISSUE TITLE
Prater logs - ignore block when PARENT_UNKNOWN

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2245]
**Describe the bug**

During Prater genesis I see this log 
```
2021-03-23 15:22:45 [NETWORK]         debug: gossip - Block - ignore code=BLOCK_ERROR_PARENT_UNKNOWN, parentRoot=
```
Do we keep this block for latter of do we throw it away? If so how would we get it eventually if it's a legit block?

**Comment by twoeths** [comment]
we still send that block to chain https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/network/gossip/validator.ts#L85 and later on it becomes a pending block in the db.
At the same time it'll issue `beacon_blocks_by_root` to other peers using an unknown ancestor root, once we got that block we'll probably be able to process the original block if it's legit.

**Comment by dapplion** [comment]
When a block from gossip has not a known parent we have to throw the error two times right?
1. First on gossip validation
2. Then again in the chain on receiveBlock

That seems like doing unnecessary work for an outcome that is already known. Would it be worth it to find another approach?

**Comment by twoeths** [comment]
The 1st throw is for internal handle of gossip validator - we don't care much from other modules, while the main throw is from the chain module, it's the official one and the necessary one in order for other modules to handle `onBlockError` if they want to.

So I think we should keep it as is.
