### ISSUE TITLE
Investigate long epoch transition for Prater and Pyrmont

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2309]
**Prater**

It takes 5s-6s for an epoch transition
<img width="1361" alt="Screen Shot 2021-03-31 at 17 53 07" src="https://user-images.githubusercontent.com/10568965/113133546-fa079180-9249-11eb-9a04-30bd0500130c.png">

CPU profile
[prater_epoch_transition_profile.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/6236012/prater_epoch_transition_profile.cpuprofile.zip)

**Pyrmont**
It takes 1.7s - 2.4s for epoch transition

<img width="1359" alt="Screen Shot 2021-03-31 at 18 02 46" src="https://user-images.githubusercontent.com/10568965/113134683-5323f500-924b-11eb-8956-c41f2a9d3b28.png">

CPU profile
[pyrmont_epoch_transition_profile.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/6236058/pyrmont_epoch_transition_profile.cpuprofile.zip)

These statistics are from same server.

**Comment by twoeths** [comment]
The above was taken from my Contabo server.
I downloaded Prater db and try to run state transition in my local environment, it takes ~2.4s per epoch transition only but when gc runs a lot, it really takes up to 6s with same data - this is a known issue.

This is maybe due to I sync both Prater and Pyrmont in same machine so gc has to run a lot?!

**Comment by dapplion** [comment]
> This is maybe due to I sync both Prater and Pyrmont in same machine so gc has to run a lot?!

You can answer this question connecting the nodes to the metrics. Check how close the heap size is to 2.5GB + the % of CPU time spent garbage collecting. It should be 20-30% max during initial sync, 5-10% when synced.

**Comment by dapplion** [comment]
We are tracking epoch transition times fairly well with performance tests. Let's open dedicated issues for specific improvement strategies
