### ISSUE TITLE
Revisit state transition errors / error messages

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#2311]
**Is your feature request related to a problem? Please describe.**

Some of our state transtion errors / error messages are not very helpful.

**Describe the solution you'd like**

We could revisit the errors returned throughout the state transition package to ensure consistent and helpful error messages.

**Additional context**
https://github.com/ChainSafe/lodestar/pull/2303#discussion_r604557689

**Comment by dapplion** [comment]
State transition errors are exceedingly rare and we have methodologies to debug them like the persisted invalid ssz objects. Current errors have been good enough
