### ISSUE TITLE
Potential performance issue in initiateValidatorExit()

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2342]
**Describe the bug**

Every time `initiateValidatorExit()` is called it iterates over the entire validators array. initiateValidatorExit may be called multiple times per block with the right conditions.

https://github.com/ChainSafe/lodestar/blob/e481a8434c0b658890fcf700cb074ddd5d3cf7cd/packages/beacon-state-transition/src/util/validatorStatus.ts#L37

**Expected behavior**

We should do something smarter and cache this computation

**Comment by twoeths** [comment]
there is a performance test for it https://github.com/ChainSafe/lodestar/blob/393836dcc6a513b5668dbcc1b53557959d45d0cf/packages/beacon-state-transition/test/perf/phase0/fast/block/block.test.ts#L32

**Comment by dapplion** [comment]
@tuyennhv do we have a performance problem? Processing a block with 16 exits is a x100 times slower..

```
Process regular block                                                  172.8628 ops/s      5.784933 ms/op   2581 runs
Process blocks with 16 validator exits                                 1.727984 ops/s      578.7092 ms/op    512 runs
```

**Comment by twoeths** [comment]
> @tuyennhv do we have a performance problem? Processing a block with 16 exits is a x100 times slower..
> 
> ```
> Process regular block                                                  172.8628 ops/s      5.784933 ms/op   2581 runs
> Process blocks with 16 validator exits                                 1.727984 ops/s      578.7092 ms/op    512 runs
> ```

yeah we should definitely improve it
