### ISSUE TITLE
Track validation participation with object of bools

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2346]
Using a compact byte representation of flags to track validator participation is significantly slower (x10) than using a simple object with bools.

```js
      {
        id: "hasMarkers",
        fn: () => hasMarkers(flags, FLAG_PREV_SOURCE_ATTESTER_OR_UNSLASHED),
      },
      {
        id: "Object accessing",
        fn: () => isPrevSourceAttOrUnslashed(flagsObj),
      }

    function isPrevSourceAttOrUnslashed(arg: Flags): boolean {
      return arg.prevSourceAtt && arg.unslashed;
    }
```
```
hasMarkers epoch transition prater: 128.23243138560002 ms
Object accessing epoch transition prater: 11.5576632704 ms
```

For reference Lighthouse uses an object with bools https://github.com/sigp/lighthouse/blob/c6baa0eed131c5e8ecc5860778ffc7d4a4c18d2d/common/eth2/src/lighthouse.rs#L52

We should consider doing the same after computing the memory cost.

**Comment by twoeths** [comment]
this seems like a potential replacement for `hasMaker`. I don't have a concern about memory as it only stays in EpochProcess and could be released by gc right after we use it.

**Comment by dapplion** [comment]
We should review this now that Altair is implemented

**Comment by twoeths** [comment]
when I try to benchmark using our `BenchmarkRunner`, there is no improvement using object of bools:
```
hasMarkers Test
================================================================
hasMarkers                                                              2132196 ops/s      469.0000 ns/op 12593895 runs    10.40 s
using object with properties                                            2277904 ops/s      439.0000 ns/op 13391903 runs    10.44 s
using object with indexed properties                                    2173913 ops/s      460.0000 ns/op 12912546 runs    10.43 s
```

**Comment by dapplion** [comment]
Benchmarks seem to show that this does not improve performance
