### ISSUE TITLE
Remove naive state transition

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#2354]
**Is your feature request related to a problem? Please describe.**

Navigating the state transition package can be frustrating, and it can be confusing determining if/when an implementation is used in production or part of the naive suite. The naive/fast distinction is confusing. The naive code is not used or useful to us.

**Describe the solution you'd like**

Remove naive code entirely.
IMO the naive code is a net detriment and not worth maintaining.
Time spent making naive code more readable can be used making the fast code more readable (eg: with more significant code comments).
Any important exported naive interfaces can be retained by wrapping the fast implementation, if exporting those interfaces is important.

**Describe alternatives you've considered**

Status quo

**Comment by dapplion** [comment]
Agree with above
