### ISSUE TITLE
Validator AttestationService: onHead is not working

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2357]
**Describe the bug**

The node is synced and consistently has new head:
```
Apr-11 07:02:54.011 []                 info: Synced - finalized: 4206 0xe725…e4ee - head: 134714 0x64fb…a101 - peers: 25
Apr-11 07:03:06.208 []                 info: Synced - finalized: 4206 0xe725…e4ee - head: 134715 0xf071…1ca6 - peers: 25
```

but it seems `onHead` is not working at validator side, nothing was logged

**Expected behavior**

Validator should consistently being able to handle "`onHead`" event.

**Comment by dapplion** [comment]
I think @mpetrunic reported a while back that events are broken somehow and the validator client can't feed from them

**Comment by mpetrunic** [comment]
> I think @mpetrunic reported a while back that events are broken somehow and the validator client can't feed from them

yes, but it was suppose to be fixed with https://github.com/ChainSafe/lodestar/pull/2273

**Comment by twoeths** [comment]
`singleNodeSingleThread` e2e test shows that validator does receive `onHead` event but it does not pass this condition https://github.com/ChainSafe/lodestar/blob/3287f5478827a9c3c7f2da4d72a8800f0065f80b/packages/validator/src/services/attestation.ts#L100

i.e. `epochTransition` is always false.

also, it seems we're out of date a little bit regarding events api https://ethereum.github.io/eth2.0-APIs/#/Events/eventstream

we miss `previous_duty_dependent_root` and `current_duty_dependent_root` in our response.

```
event: head\n
data: "{\"slot\": \"10\", \"block\": \"0x9a2fefd2fdb57f74993c7780ea5b9030d2897b615b89f808011ca5aebed54eaf\", \"state\":\"0x600e852a08c1200654ddf11025f1ceacb3c2e74bdd5c630cde0838b2591b69f9\", \"epoch_transition\": false, \"previous_duty_dependent_root\": \"0x5e0043f107cb57913498fbf2f99ff55e730bf1e151f02f221e977c91a90a0e91\", \"current_duty_dependent_root\": \"0x5e0043f107cb57913498fbf2f99ff55e730bf1e151f02f221e977c91a90a0e91\"}"\n
\n
```

**Comment by twoeths** [comment]
server does return `onHead` event with `epochTransition=true`:
```
event: head
data: {"slot":"162048","block":"0xbdedf0efe3339c3e42c74827a664f5d0455bc173af5bb068f83e7f931d113971","state":"0x0a99fdf98d127bb5aa44c77809b125713925529d98d8cb017893123c1d861fe5","epochTransition":true}
```

the issue in e2e has the root cause of #2380
