### ISSUE TITLE
Improve processEth1Data

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2359]
**Describe the bug**
Process eth1 data takes 300ms - 500ms per block which is too much.
<img width="1470" alt="Screen Shot 2021-04-12 at 08 38 23" src="https://user-images.githubusercontent.com/10568965/114329823-8da26180-9b6a-11eb-863b-93ea1735e746.png">

the reason is probably we use `readOnlyValues` which returns structs and we compare that to TreeBacked Eth1Data inside block. 

**Expected behavior**

We should be able to get TreeBacked Eth1Data from `state.eth1DataVotes` and compare TreeBacked values.
[0412_sync_prater_local.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/6293288/0412_sync_prater_local.cpuprofile.zip)

**Comment by twoeths** [comment]
this is strange, the profile shows that we use struct SignedBeaconBlock while it should be TreeBacked.

today I sync master again and don't see that anymore. Most of the time to process block is for processing attestation, around 10ms per block.

**Comment by wemeetagain** [comment]
I think it happens during regen. We should probably deserialize blocks as tree-backed there
