### ISSUE TITLE
Migrate to Typescript

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/lodestar#24]
There seems to be some good discussion around this in the ethereumjs organization, as well as other JS blockchain projects. There is an additional barrier of entry, but it would seem that the benefits are worth it. We would have a huge advantage by making the switch now, although it would certainly could be reconsidered further down the road.

https://github.com/ethereumjs/organization/issues/28
https://github.com/ethereumjs/ethereumjs-client/issues/10
https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html

**Comment by GregTheGreek** [comment]
Love the idea. Let's make a typescript branch.

**Comment by dbkbali** [comment]
Definitely will improve code quality and typescript transpiles to js. So everyone should be happy😁

**Comment by priom** [comment]
Let's migrate the whole project to TS, will be easier to maintain the project and releases.

**Comment by GregTheGreek** [comment]
After having a call with the Ethereum-js /shasper-js team I think it would be best to migrate to typescript. Moving to high priority before the project gets too large.

**Comment by GregTheGreek** [comment]
Update:

New milestone & project setup for this. Currently #34 is being worked on by me to get the `core/state` directory converted. Will move outwards.
