### ISSUE TITLE
Create a beacon config object for run-time configuration

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#240]
Our current solution for "configurable constants" is to edit a file as a precompilation step. See #220.
A more full-featured solution would be to create a `BeaconConfig` object that would store tweaked "constants", ssz types, and misc other things (eg: a logger). (See https://github.com/ChainSafe/lodestar/pull/220#issuecomment-494942476 for more context)

It could look something like:
```typescript
interface Constants {
  SHARD_COUNT: number;
  // ... the rest of the configurable constants
}

interface SSZTypes {
  Fork: AnySSZType;
  // ... the rest of the ssz types
}

interface BeaconConfig {
  constants: Constants;
  ssz: SSZTypes;
  logger: AbstractLogger;
}
```
Then we can pass around the BeaconConfig (created in cli startup or BeaconNode constructor) throughout the project, even down to the more functional bits:
```typescript
// pass in a BeaconConfig to the state transition helpers
executeStateTransition(state, block, config);

// and pass in a config to any functions that use constants, ssz types, need logging, etc.
export function getShardDelta(state: BeaconState, epoch: Epoch, c: BeaconConfig): number {
  return Math.min(
    getEpochCommitteeCount(state, epoch, c),
    c.constants.SHARD_COUNT - intDiv(c.constants.SHARD_COUNT, c.constants.SLOTS_PER_EPOCH),
  );
}
```

**Comment by GregTheGreek** [comment]
+1 to this, big refactor but fairly straightforward of a task

**Comment by mpetrunic** [comment]
I'm usually against passing same config throughout application. I would lean more towards config singleton that can apply different configurations if so desired.

**Comment by wemeetagain** [comment]
I think the biggest downside is the verbosity, and how this effects the ergonomics of calling functions that require the config object, but this comes with subtle benefit over a singleton.

I think it leads to more understandable code. Instead of hiding parameters in global state, parameters are passed in explicitly. We can easily see that functions are reliant on this state by reading the function signature, rather than needing to scan the entire function body.

There are no surprise side-effects. If a function needs to log, it gets passed a logger. If it needs a runtime-constant, it gets passed the constant.

**Comment by mpetrunic** [comment]
TBH, I think most of the time you change constants or something you would run `yarn check-types` to see if everything is aligned. This way introduces a lot of boilerplate code to every method and it's corresponding unit tests (it also goes against codeclimate and number of params method should have -lower is better). From experience, logger and config were always part of global state but I'm respecting your decision :)

**Comment by GregTheGreek** [comment]
I'm very used to geth, where they arguably pass the config around everywhere, it's quite as nice imo

**Comment by GregTheGreek** [comment]
Also it's JavaScript, we could assign it as a global var and not even need to pass it around

**Comment by wemeetagain** [comment]
I agree most of the time constants would be changed before run-time, unfortunately, we can't really expose "compile-time" to end users, we only publish transpiled javascript, so we only have run-time to handle changing the constants. This is one of the major issues with our current file-based approach.

Ultimately, I think its a pretty subjective call. Are these variables actual constants? or are they runtime parameters?
If they're constants, they should just be imported and used as implicit parameters.
If they're runtime parameters, they should be passed in as parameters explicitly.

My current thought is that we should treat many of the constants as runtime parameters, even if mainnet will only use one specific definition of them, with definitions known well ahead of time.
We'll be doing enough testing that non-mainnet configurations will be an important "first-class" usecase.

Realistically, we won't need to add a BeaconConfig to every function everywhere, just functions that require these runtime parameters (mainly top-level modules and a bunch of state transition functions).

Perhaps in the purely functional sections, we can add the config as the first parameter, rather than the last, to avoid issues with defaults.

I'm hopeful we can avoid most of the boilerplate in tests:
```typescript
const conf1: ChainConfig = getMainnetConfig();
expect(funcTested(conf1, arg1)).to.be.foo()
// or
const conf2: ChainConfig = getMinimalConfig();
expect(funcTested(conf2, arg1)).to.be.bar()

// which isn't much different than the ergonomics of a singleton approach
setChainConfig(mainnet);
expect(funcTested(arg1)).to.be.foo();
// or
setChainConfig(minimal);
expect(funcTested(arg1)).to.be.bar();
```

**Comment by mpetrunic** [comment]
Yeah but we can expose config as singleton and therefore every constant will be runtime params. It's javascript so we basically have only runtime params because we can override any export to suit our need which I'm abusing in unit tests. I think the issue we are trying to figure out whether to inject config by importing it or pass it by reference throughout application. I'm leaning towards first as it doesn't require tectonic changes on code and tests and reduces boilerplate code of passing config object reference down the method call chain.

```javascript
import *  as mainet from './constants/mainet';
import * as minimal from './constant/minimal';

class BeaconConfig {
   public SLOT_PER_EPOCH: number;
   
   constructor() {
      this.applyMainet();
   }

   public function applyMainnet() {
      //set properties from mainet
   }

   public function applyMinimal() {
   }

   public function applyCustom(constants);
  
}

export default new BeaconConfig();
```

And in every file:
```javascript
import config from '/config';

config.applyMinimal();
config.SLOTS_PER_EPOCH;
```

**Comment by wemeetagain** [comment]
I definitely see how its a lot less of a code change, and how it could work.

My main concern is more that singletons are process-wide, whereas injected dependencies are only instance-wide.
Singletons are configured by a series of side-effects, whereas injected dependencies are configured by creating a new dependency via constructor or function.
I think dependency injection is just a conceptually cleaner way to build up a big project like this and in this case worth the additional parameterization. Hiding the chain config in a singleton is easy to implement, but it couples everything in a subtle way that I don't think is the best.

Eg: Should a `BeaconConfig` apply to all running `BeaconNode`s? or is the Config unique to the Node that's running?
```typescript
// compare 6 second block time to 2 second block time
config.applyMainnet();
const nodeA = new BeaconNode();
config.applyMinimal();
const nodeB = new BeaconNode();
nodeA.start();
nodeB.start();
// unfortunately, now nodeA and nodeB both follow the minimal config
```
I don't actually think (m)any people will be running multiple beacon nodes with different configs, but this highlights a bit of the reasoning.
I think the config is a product of the running beacon node, rather than a product of the environment in which its running. Using a singleton makes the config a product of the environment.

**Comment by mpetrunic** [comment]
That kinda makes sense. But I don't think we would ever have this case. If we are emulating network, we would want nodes with same config. Users are in every case going to start it in separate terminal so it can have whatever config. Even if we would do scenario like above, we would fork process to utilize CPU properly, I don't think beacon node could run on one thread and even less likely two beacon nodes.

**Comment by aunyks** [comment]
Why pass this as interpretable/executable code? Can we use a JSON or YAML config file at runtime like Geth does?

**Comment by mpetrunic** [comment]
We've implemented configuration using toml for other stuff. Ideally we will have this constants configurable using toml as well but we have a few issue before we sort this out:
- throughout code we used it as read only constants so it's quite a major refactor to allow it to change in runtime
- ssz library types depends on these constants and they are also defined as constants (read only)

Once we can set those params in runtime, it's quite easy to apply toml/json config to them

**Comment by aunyks** [comment]
By read only, are you referring to TypeScript constants?

**Comment by mpetrunic** [comment]
Yeah, they are defined like this:
https://github.com/ChainSafe/lodestar/blob/master/src/constants/mainnet.ts
and imported everywhere, we need to move them to some config object and pass it around

**Comment by aunyks** [comment]
Ah, I see. Thanks for the reference!  

Are all of these constants in the `constants/` folder or are they spread throughout the repo?

**Comment by GregTheGreek** [comment]
My pr for #248 should solve this entirely tbh.
As a seperate node module we should be able to toggle between them. Better yet build the functionality directly into the types repo

**Comment by mpetrunic** [comment]
@aunyks  yeah, they are all there

@GregTheGreek Isn't @wemeetagain working on it as well? haha

**Comment by GregTheGreek** [comment]
Uhhh  well I'm solving one half I guess lol

**Comment by wemeetagain** [comment]
I'm thinking @GregTheGreek means he's working on the lerna infra.
We'll still need the meat of this issue fixed independently, which is what I'm doing.

**Comment by GregTheGreek** [comment]
Now that I have my head on straight, having our types seperated with Lerna partially resolves the BLS SSZ dependencies on lodestar
