### ISSUE TITLE
Move away from singleton logger

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#241]
Currently, we have a singleton logger that is accessible throughout the project.
This has been convenient to use, since the logger is just a part of the global scope.
However, this may ultimately be limiting, as its locks in a single implementation used across the project.

We should instead create a logger instance in cli startup or the node constructor that can be passed through the project. (See #240 for how we can address logging in our functional code)
This will give us more freedom to more easily customize the logging in the future, if we so choose.

**Comment by mpetrunic** [comment]
What would be a use case for different logger configuration in different parts of application?

I can only see if we would like to log different parts on different levels, but the better solution would be to introduce context param to logging methods (info, debug etc) and display logs depending on which context has what level settings

**Comment by wemeetagain** [comment]
Maybe if we want to log only one module for extensive testing. If we wanted to expose that sort of behavior to users, we would want the logger passed in.
We either need to then change all log call sites to verbose/debug or pass in the configuration for that module once.
Practically speaking, for our own purposes, we probably won't want different logger configurations in different parts of the app, at least not most of the time. But it is just cleaner to not rely on a global.

**Comment by mpetrunic** [comment]
I think you misunderstood. I was proposing to do something like
```javascript
logger.debug('some message', Module.Network);
```  
where last param is optional.
I'm saying this because it's quite complicated and ugly to pass logger to some parts of application we might get logged. And as a general rule, the harder it is to log something the less logs we will have.

**Comment by wemeetagain** [comment]
I think the idea in #240 a way forward that is not very complicated. It is verbose, though.

**Comment by mpetrunic** [comment]
True, but I think it only works because we have barely any logs and They are all in top level classes. I don't think a way to go is having extra param on every method to pass logger, it will cause issues later on especially with method with default params and stuff

**Comment by GregTheGreek** [comment]
I'm about confused at your example @mpetrunic, what exactly do we benefit from wrapping the module ?

**Comment by mpetrunic** [comment]
It's not wrapping, `Module.Network` could be enum, We can then set log levels for specific modules (if we wan't to debug networking `./bin/lodestar --logLevels network=debug, rpc=warning)` and we would set those configs in logger singleton. You would check [here](https://github.com/ChainSafe/lodestar/blob/f25f91feed85fc806b8e3a461a0b3989bf80bff2/src/logger/winston.ts#L49) if you need to log that log level based on config.

**Comment by GregTheGreek** [comment]
Oh I see I support this idea, I wish geth had something like this
