### ISSUE TITLE
Pre-aggregate attestations in Aggregation pool

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2415]
In this PR https://github.com/ChainSafe/lodestar/pull/2295/files we introduced an index to efficiently check which attestations have the same data root.

However checking Lighthouse Aggregation Pool https://github.com/sigp/lighthouse/blob/stable/beacon_node/beacon_chain/src/naive_aggregation_pool.rs we could just pre-aggregate attestations and keep a single attestation per data root.

This would substitute the need for the index in the first place and reduce the amount of data we have to keep around.

**Comment by twoeths** [comment]
this looks great 👍 . My understanding is we don't even need the `attestation` repo with the new index by attestation data root?

We may want to do the same thing for altair `SyncCommitteeSignature`.
