### ISSUE TITLE
Better .valueOf()

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2419]
**Describe the issue**

Using `.valueOf() as SomeType` is not type-safe at all and can become dangerous an unmaintainable. 

We are using it for a very specific purpose which is to drop the tree and get the actual internal value without wrappers. This meaning is not easy to get at first glance.

**Proposed solution**

Create a helper function that clearly shows what it does that AND is type safe.

```ts
function dropTree<T>(treeBackedValue: T): T extends ByteVector ? Uint8Array : T {
  return treeBackedValue.valueOf()
}
```

With this code would read like

```ts
const randaoReveal = dropTree(block.body.randaoReveal)
```

instead of 

```ts
const randaoReveal = block.body.randaoReveal.valueOf() as Uint8Array;
```

----

Related to https://github.com/ChainSafe/lodestar/issues/2408

**Comment by wemeetagain** [comment]
:+1: A typesafe wrapper would be really nice. I suggest something like this exported from `@chainsafe/ssz`:
```ts
function toStruct<T extends CompositeValue>(value: T): T extends ByteVector ? Uint8Array : T {
  if (isTreeBacked(value)) {
    return value.toStruct();
  }
  return value;
}
```
A note about the name, its not that we're dropping the tree but rather that we're converting the tree to a "struct", ie a primitive javascript datatype. (our `valueOf` method is an alias for `toStruct`)
