### ISSUE TITLE
Use Event stream in Validator Clock

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#2430]
It's sort of TODO. We should use the event stream here but in a future PR

_Originally posted by @dapplion in https://github.com/ChainSafe/lodestar/pull/2416#discussion_r620653675_

**Comment by dapplion** [comment]
Already done in

https://github.com/ChainSafe/lodestar/blob/2ed2e03d0ca3e2d6e04e503d4e1beb2deedd47a7/packages/validator/src/services/chainHeaderTracker.ts#L22
