### ISSUE TITLE
Handle Altair fork in chain

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2431]
**Is your feature request related to a problem? Please describe.**

1. Form here https://github.com/ChainSafe/lodestar/blob/84a03e020d99d8a3cee681e4d5d90ff5a9407160/packages/lodestar/src/chain/chain.ts#L277

2. Chain should be able return `getForkDigest` and `getForkName` immediately using a cache.
3. Gossip should use `chain.getForkDigest()` instead of computing it itself
4. Get fork based on epoch instead of slot (spec updated `ALTAIR_FORK_EPOCH` instead of `ALTAIR_FORK_SLOT`)

**Comment by dapplion** [comment]
Yes please! I do need that for Altair ReqResp

**Comment by dapplion** [comment]
I would expose the current and also on demand like:

```ts
interface A {
  getCurrentForkDigest(): ForkDigest;
  getForkDigest(forkName: ForkName): ForkDigest;
}
```

**Comment by wemeetagain** [comment]
```ts
Chain {
  getHeadForkName(): ForkName;
  getClockForkName(); ForkName;
  getHeadForkDigest(): ForkDigest;
  getClockForkDigest(): ForkDigest;
```
