### ISSUE TITLE
Our db stream methods won't stop reading as expected

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2434]
**Describe the bug**

Our db stream methods such [`entriesStream`](https://github.com/ChainSafe/lodestar/blob/master/packages/db/src/controller/impl/level.ts#L130) have a serious flaw where the returned AsyncGenerator won't act as such.

If you create an entriesStream with opts such that reads all the keys, and then break out of the for await of loop, it won't actually stop reading. It will continue reading all the keys in the background.

The issue comes from the many layers of wrapping:

1. leveldb abstract down returns an iterator https://github.com/Level/level-js/blob/master/iterator.js
2. levelup wraps that with which returns a readable stream https://github.com/Level/iterator-stream
3. We wrap that with an `it-pushable` subscribing to the readable stream's callback

When we just subscribe to the callbacks the iterator just does whatever in the background. it-pushable instance has no control over it.

**Expected behavior**

If you break early out of `entriesStream` it should stop reading from the DB and cleanup.

**Comment by 3xtr4t3rr3str14l** [comment]
can this be closed now that #2435 is merged?
