### ISSUE TITLE
make `--logLevel` a global CLI option

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#2437]
I noticed `lodestar account validator` does not have the `--logLevel` option, and it got me thinking that maybe we should just have `--logLevel` be a global option for anywhere in the codebase where we may be using more than just `info` logs.

**Comment by dapplion** [comment]
It really only makes sense with beacon validator commands. Validator should have it yeah but probably not global

**Comment by 3xtr4t3rr3str14l** [comment]
I found this potential idea a few months ago and forgot to note exactly where the logger instance was being called (as well as forgetting to make an issue right away), but i had remembered seeing an instance where one of the cli `account` commands had called another lib (possibly `lodestar-validator`) and that package had a deeper log level call than just `info` and it wasn't being logged.  I'll note here if I find the exact spot where that happened.

**Comment by dapplion** [comment]
`account` commands should not use the logger really, if they do is for some usage of a module somewhere as you note.
