### ISSUE TITLE
Block hashTreeRoot is not being cached

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2454]
**Describe the bug**

In Prater our node seems to re-hash a block too much, see CPU profile

![Screenshot from 2021-05-01 15-25-01](https://user-images.githubusercontent.com/35266934/116783890-8b5c6480-aa91-11eb-804f-fbee4e80a2f0.png)

Review the code associated with those stacks and if the block is tree backed

**Expected behavior**

Hash once per block

**Comment by twoeths** [comment]
The only time we don't use TreeBacked is refetching a block from `pendingBlock` repo
