### ISSUE TITLE
forkChoice.getHead() is expensive

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2455]
**Describe the bug**

In Prater calling `chain.getHead()` costs 100ms the times it has shown up in my profiles. @wemeetagain is this cost too much? If this is normal we have to rethink the consumer code of chain because .getHead() is called very often.

EDIT: In a new CPU profile 5.39% of total CPU time is spent in getHead(), that def seems excessive

![Screenshot from 2021-05-01 15-32-32](https://user-images.githubusercontent.com/35266934/116784117-ba270a80-aa92-11eb-8d1a-3331a33666af.png)

**Comment by dapplion** [comment]
Indeed we call .getHead a lot everywhere in `packages/lodestar`. All that calls can trigger a re-computation of the tree. If we feed gossip attestations to the forkChoice that can kill the node.

Todo:
- Add forkChoice metrics to quantify the problem
- Consider caching the head and re-computing the tree only when instructed, not on every getHead call
- If computeDeltas end up still being very expensive, consider optimizing it. Could we use numbers instead of BigInts somehow?

**Comment by 3xtr4t3rr3str14l** [comment]
unstale

**Comment by 3xtr4t3rr3str14l** [comment]
> Indeed we call .getHead a lot everywhere in `packages/lodestar`. All that calls can trigger a re-computation of the tree. If we feed gossip attestations to the forkChoice that can kill the node.
> 
> Todo:
> 
>     * Add forkChoice metrics to quantify the problem
> 
>     * Consider caching the head and re-computing the tree only when instructed, not on every getHead call
> 
>     * If computeDeltas end up still being very expensive, consider optimizing it. Could we use numbers instead of BigInts somehow?

We have the fork choice metrics (via #2664) and head caching (as noted in https://github.com/ChainSafe/lodestar/issues/2747#issuecomment-874926928) and the last item is being tracked in https://github.com/ChainSafe/lodestar/issues/2747#issuecomment-879568043 , so can we close this issue?

**Comment by dapplion** [comment]
Closing for https://github.com/ChainSafe/lodestar/issues/2747#issuecomment-879568043
