### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/lodestar#247]
**What is your question?**
We should assemble a style guide, we'll use this issue to brainstorm different patterns.

Constructors
- should follow the patter of an options object and an object of dependent modules
- `constructor (opts: IExampleOpts, {logger: WinstonLogger, db: LevelDb})`

Interfaces
- all interfaces should follow a patter of prefix a capital I
  - `IExample`

**Comment by wemeetagain** [comment]
We can include linter rules / linter usage

**Comment by mpetrunic** [comment]
Naming of class properties. 

```javascript
private _dirty;
or
private dirty;
```
?

**Comment by GregTheGreek** [comment]
@mpetrunic this is actually I really good point...

**Comment by mpetrunic** [comment]
I think we need to force either " or ' in eslint, currently it's ok to use both

**Comment by wemeetagain** [comment]
PRs should only update a single package
