### ISSUE TITLE
Add validator monitor metrics

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2473]
Reviewed this file and select interesting metrics to add
https://github.com/sigp/lighthouse/blob/stable/beacon_node/beacon_chain/src/metrics.rs

**Validator monitoring (own validators)**

High priority to add these. All metrics are indexed by validator (probably index)

Validator Monitor Metrics (per-epoch summaries)

- [ ] `validator_monitor_prev_epoch_on_chain_attester_hit`: Incremented if the validator is flagged as a previous epoch attester during per epoch processing
- [ ] `validator_monitor_prev_epoch_on_chain_attester_miss`: Incremented if the validator is not flagged as a previous epoch attester during per epoch processing
- [ ] `validator_monitor_prev_epoch_on_chain_head_attester_hit`: Incremented if the validator is flagged as a previous epoch head attester during per epoch processing
- [ ] `validator_monitor_prev_epoch_on_chain_head_attester_miss`: Incremented if the validator is not flagged as a previous epoch head attester during per epoch processing
- [ ] `validator_monitor_prev_epoch_on_chain_target_attester_hit`: Incremented if the validator is flagged as a previous epoch target attester during per epoch processing
- [ ] `validator_monitor_prev_epoch_on_chain_target_attester_miss`: Incremented if the validator is not flagged as a previous epoch target attester during per epoch processing
- [ ] `validator_monitor_prev_epoch_on_chain_inclusion_distance`: The attestation inclusion distance calculated during per epoch processing
- [ ] `validator_monitor_prev_epoch_attestations_total`: The number of unagg. attestations seen in the previous epoch.
- [ ] `validator_monitor_prev_epoch_attestations_min_delay_seconds`: The min delay between when the validator should send the attestation and when it was received.
- [ ] `validator_monitor_prev_epoch_attestation_aggregate_inclusions`: The count of times an attestation was seen inside an aggregate.
- [ ] `validator_monitor_prev_epoch_attestation_block_inclusions`: The count of times an attestation was seen inside a block.
- [ ] `validator_monitor_prev_epoch_attestation_block_min_inclusion_distance`: The minimum inclusion distance observed for the inclusion of an attestation in a block.
- [ ] `validator_monitor_prev_epoch_beacon_blocks_total`: The number of beacon_blocks seen in the previous epoch.
- [ ] `validator_monitor_prev_epoch_beacon_blocks_min_delay_seconds`: The min delay between when the validator should send the block and when it was received.
- [ ] `validator_monitor_prev_epoch_aggregates_total`: The number of aggregates seen in the previous epoch.
- [ ] `validator_monitor_prev_epoch_aggregates_min_delay_seconds`: The min delay between when the validator should send the aggregate and when it was received.

Validator Monitor Metrics (real-time)

- [ ] `validator_monitor_validators_total`: Count of validators that are specifically monitored by this beacon node
- [ ] `validator_monitor_unaggregated_attestation_total`: Number of unaggregated attestations seen
- [ ] `validator_monitor_unaggregated_attestation_delay_seconds`: The delay between when the validator should send the attestation and when it was received.
- [ ] `validator_monitor_aggregated_attestation_total`: Number of aggregated attestations seen
- [ ] `validator_monitor_aggregated_attestation_delay_seconds`: The delay between then the validator should send the aggregate and when it was received.
- [ ] `validator_monitor_attestation_in_aggregate_total`: Number of times an attestation has been seen in an aggregate
- [ ] `validator_monitor_attestation_in_aggregate_delay_seconds`: The delay between when the validator should send the aggregate and when it was received.
- [ ] `validator_monitor_attestation_in_block_total`: Number of times an attestation has been seen in a block
- [ ] `validator_monitor_attestation_in_block_delay_slots`: The excess slots (beyond the minimum delay) between the attestation slot and the block slot.
- [ ] `validator_monitor_beacon_block_total`: Number of beacon blocks seen
- [ ] `validator_monitor_beacon_block_delay_seconds`: The delay between when the validator should send the block and when it was received.

Validator Monitor Metrics (balances, etc)

- [ ] `validator_monitor_balance_gwei`: The validator's balance in gwei.
- [ ] `validator_monitor_effective_balance_gwei`: The validator's effective balance in gwei.
- [ ] `validator_monitor_slashed`: Set to 1 if the validator is slashed.
- [ ] `validator_monitor_active`: Set to 1 if the validator is active.

**Comment by g11tech** [comment]
@dapplion  assign please if you wish to delegate.

**Comment by dapplion** [comment]
@g11in Most (or all) of the metrics are already implemented, review existing before diving in 👍

**Comment by dapplion** [comment]
Implemented
