### ISSUE TITLE
Rotate log files with CLI --logFile

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2477]
**Describe the bug**

From https://github.com/ChainSafe/lodestar/pull/2470 log files can grow big fast. Have some log rotation mechanism. Maybe Winston has something built-in

**Comment by dapplion** [comment]
Consider splitting the files per day, beacon logs grew to 2.7GB in 3 days

**Comment by g11tech** [comment]
@dapplion  @wemeetagain  could you assign this t me

**Comment by dapplion** [comment]
Bump to this. A log file in a machine I use reached 45 GB and filled the drive

**Comment by dapplion** [comment]
Done with https://github.com/ChainSafe/lodestar/pull/2692
