### ISSUE TITLE
Export types as native npm package

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/lodestar#248]
**Is your feature request related to a problem? Please describe.**

Currently there is no intuitive way for accessing the custom types into other libraries (i.e ssz-js)

**Describe the solution you'd like**

Ideally they can be deployed under their own module `@chainsafe/eth2-types` (or similar)

**Comment by wemeetagain** [comment]
Look into [Lerna](https://github.com/lerna/lerna) or [Yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/)

**Comment by mpetrunic** [comment]
I was trying to move my PR to closed but it seems they are linked somehow
