### ISSUE TITLE
Add ReqResp metrics

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2489]
- [ ] Count total requests done per method: `beacon_reqresp_outgoing_requests_total` `{method}`
- [ ] Count total failed requests done per method: `beacon_reqresp_outgoing_requests_error_total` `{method}`
- [ ] Count total responses handled per method: `beacon_reqresp_incoming_requests_total` `{method}`
- [ ] Count total failed responses handled per method: `beacon_reqresp_incoming_requests_error_total` `{method}`
- [ ] Count total dial errors separately too: `beacon_reqresp_dial_errors_total` `{}`

**Comment by g11tech** [comment]
@dapplion  assign please

**Comment by g11tech** [comment]
@dapplion  I think this is a good use case for labels (for attaching method name). Two seperate gauge metrics for total count and errors with the methodname as label dimension on each of them. Let me know how you feel about the same.

**Comment by dapplion** [comment]
> @dapplion I think this is a good use case for labels (for attaching method name). Two seperate gauge metrics for total count and errors with the methodname as label dimension on each of them. Let me know how you feel about the same.

I've updated the description with suggested names for each metric. The first 4 must have exactly one dimension, labeled by method. The total dial errors metrics must have "0 dimensions" no labes.
