### ISSUE TITLE
Move API consumer code to chain class

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2491]
**Feature request**

Basic ops like getBlock or getState and not clearly defined in Lodestar. The code in the API to do that could be moved to BeaconChain class so it can be consumed programatically from there too

**Comment by 3xtr4t3rr3str14l** [comment]
@dapplion i guess since these ops have been moved to the `lodestar-api` package that we can close this issue?

**Comment by dapplion** [comment]
> @dapplion i guess since these ops have been moved to the `lodestar-api` package that we can close this issue?

No, this issue is about moving the code from api/impl to chain
