### ISSUE TITLE
Array.from(readonlyValues(aggregationBits)) performance issue

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2502]
This is from the new performance test in #2501 - it takes almost 1.5s for `Array.from(readonlyValues(aggregationBits))`
<img width="1460" alt="statusProcessEpoch2" src="https://user-images.githubusercontent.com/10568965/117744292-9a31dc80-b232-11eb-860c-0497e90c199e.png">
(notice that the statistic is 1 line shift to the downside somehow)

Currently for  `readonlyValues` of BitList, we return an iterator by yielding each separate bit and then the consumer (lodestar) aggregate them again as `boolean[]`.

We should be able to write an util to access the respective chunks and the consumer can just use that.

**Comment by dapplion** [comment]
The `attestation` is a tree-backed object?

**Comment by twoeths** [comment]
yeah everything inside CachedBeaconState is TreeBacked objects
