### ISSUE TITLE
Cache forkDataRoot

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2505]
**Feature request**

Currently we compute forkDataRoot every time we need to verify a signature. We could compute all `forkDataRoot`s for the known forks after genesis is known, and cache them.

We could even cache the domains as we compute them.

**Proposal**

Expose somewhere an interface like

```ts
export interface IDomainCache {
  getDomainAtSlot(domainType: DomainType, slot: Slot): Buffer;
}
```

----

**EDIT**: Note: I have not data to prove that this is an actual performance issue, it was just an idea that would be nice to de-duplicate work but maybe it has a negligible impact.

One may browse the issues with the performance label which are proven to have a serious impact on the node performance https://github.com/ChainSafe/lodestar/labels/Performance

**Comment by twoeths** [comment]
it's worth to cache domains:
```ts
state = generatePerfTestCachedBeaconState({goBackOneSlot: true});
    const {config} = state;
    let start = Date.now();
    for (let i = 0; i < 10000; i++) {
      state.blockRoots[100];
    }
    console.log("@@@ finish 10000 state.blockRoots[100] in", Date.now() - start, "ms");
    start = Date.now();
    for (let i = 0; i < 10000; i++) {
      state.slot;
    }
    console.log("@@@ finish 10000 state.slot in", Date.now() - start, "ms");
    start = Date.now();
    for (let i = 0; i < 10000; i++) {
      state.currentJustifiedCheckpoint.epoch;
    }
    console.log("@@@ finish 10000 state.currentJustifiedCheckpoint.epoch in", Date.now() - start, "ms");
    start = Date.now();
    for (let i = 0; i < 10000; i++) {
      getDomain(config, state, config.params.DOMAIN_BEACON_ATTESTER);
    }
    console.log("@@@ finish 10000 getDomain", Date.now() - start, "ms");
```
```
@@@ finish 10000 state.blockRoots[100] in 151 ms
@@@ finish 10000 state.slot in 53 ms
@@@ finish 10000 state.currentJustifiedCheckpoint.epoch in 173 ms
@@@ finish 10000 getDomain 798 ms
```

`getDomain` is 5 times slower than `state.blockRoots` and caching block roots could save us 0.5s in epoch transition as in #2528

**Comment by dapplion** [comment]
Then let's do it!

**Comment by twoeths** [comment]
on a node with full attestation subnet subscriptions, `getDomain` takes more than 2% of total time
<img width="1319" alt="Screen Shot 2021-06-24 at 14 39 15" src="https://user-images.githubusercontent.com/10568965/123222641-53562880-d4fa-11eb-942f-e84091d7b2ec.png">
