### ISSUE TITLE
Grafana dashboard showing CPU usage percentages greater than 100%

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#2509]
![Screenshot from 2021-05-11 15-50-05](https://user-images.githubusercontent.com/32028745/117883245-cbc99880-b270-11eb-81da-de512497fdbf.png)

**Expected behavior**
Show 100% or less.

**Comment by 3xtr4t3rr3str14l** [comment]
And just to clarify, I did not modify any of the dashboard on this branch (`P0/ws-cli` as noted in `Lodestar version` in the screenshot).

**Comment by dapplion** [comment]
> Expected behavior
Show 100% or less.

When doing multi-threading the CPU time % can be > 100%. NodeJS does that on its own paralelizing some garbage collection actions. We also do multi-threading on BLS verification
