### ISSUE TITLE
Altair API

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2512]
https://github.com/ethereum/eth2.0-APIs/blob/master/beacon-node-oapi.yaml 

- [ ] `/eth/v1/beacon/states/{state_id}/sync_committees`
- [ ] `/eth/v2/beacon/blocks/{block_id}`
- [ ] `/eth/v2/debug/beacon/states/{state_id}`
- [ ] `/eth/v2/validator/blocks/{slot}`
- [ ] `/eth/v1/validator/sync_committee_subscriptions`

Update by Tuyen on May 13:
- [ ] POST `/eth/v1/validator/duties/sync/{epoch}`
- [ ] POST `/eth/v1/beacon/pool/sync_committees`
- [ ] GET `/eth/v1/validator/sync_committee_contribution`
- [ ] POST `/eth/v1/validator/contribution_and_proofs`

**Comment by 3xtr4t3rr3str14l** [comment]
currently working `/eth/v1/beacon/states/{state_id}/sync_committees`

EDIT: moving on to the others as well

**Comment by dapplion** [comment]
Also working on this item in https://github.com/ChainSafe/lodestar/tree/dapplion/altair-vc let's coordinate our progress
