### ISSUE TITLE
Create IndexedSyncCommittee

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2518]
**Is your feature request related to a problem? Please describe.**

Right now we put indexed data of a sync committee inside EpochContext:
```ts
  currSyncCommitteeIndexes: ValidatorIndex[];
  nextSyncCommitteeIndexes: ValidatorIndex[];
  currSyncComitteeValidatorIndexMap: SyncComitteeValidatorIndexMap;
```
**Describe alternatives you've considered**

My proposal is to put index data inside an `IndexedSyncCommittee`, similar to `IndexedAttestation`
```ts
export interface IndexedSyncCommittee extends SyncCommittee {
  attestingIndices: List<ValidatorIndex>;
  validatorIndexMap: SyncComitteeValidatorIndexMap;
  // add more if needed
}

type SyncComitteeValidatorIndexMap = Map<ValidatorIndex, number[]>;
```

**Additional context**
+ The `IndexedSyncCommittee` is cached inside `CachedBeaconState` (similar to `balances`, `validators`) with the same `currentSyncCommittee`, `nextSyncCommittee` property key
+ Ensure the tree backed data structure is the same
+ When cloning `CachedBeaconState` we can just share the same `IndexedSyncCommittee` instead of doing a real clone

What do you think @wemeetagain @dapplion ?

**Comment by dapplion** [comment]
@tuyennhv Could you detail the pros vs cons of this approach compared to having the data in the epoch context itself?

**Comment by twoeths** [comment]
+ The most benefit of this is single source of truth - we want to manage sync committee data in single place to avoid the issue in https://github.com/ChainSafe/lodestar/issues/2631#issuecomment-857321122
+ Cleaner EpochContext: we'll not have sync committee code in EpochContext any more
+ It's also consistent to the design we have with `CachedBeaconState` for other fields

The down side of this is we need to make change and test everything again, and not sure if we have any obstacles with that?

**Comment by dapplion** [comment]
@tuyennhv Sounds good to me! If performance is the same sounds like a good improvement. When I added the caches I didn't considered other alternatives like yours so it sounds reasonable.
