### ISSUE TITLE
Experiment caching block root in CachedBeaconState

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2528]
**Is your feature request related to a problem? Please describe.**

A simple `const blockRootsAtSlot = new Map<phase0.Slot, phase0.Root>();` at https://github.com/ChainSafe/lodestar/blob/e04410b5704f04738c03a75673efff6b829f1700/packages/beacon-state-transition/src/phase0/epoch/processPendingAttestations.ts#L29

helps save ~0.5s per epoch transition in the performance test (~2.1s in total).

**Describe the solution you'd like**

Cache blockRoots in CachedBeaconState similar to `validators, balances` so that we don't have to go to persistent-merkle-tree to get data, this should help speed up the whole state transition instead of just `processPendingAttestations` in phase0.

**Comment by dapplion** [comment]
This looks like a big performance win at low cost! Nice find

**Comment by twoeths** [comment]
to be clear, the performance test `slots.test.ts` was not stable enough, the difference from caching `blockRoots` in epoch transition is only 100ms-150ms, not 500ms.

and if I cache block roots using `persistent-ts` in CachedBeaconState, the sync time is even slower probably because of the cost of mutating `persistent-ts` leaf (it has to allocate a new array of 32 blockRoots)

**Comment by twoeths** [comment]
This is a profile from a Prater sync, `getBlockRootAtSlot` takes 4% of the time

<img width="1290" alt="Screen Shot 2021-07-14 at 10 53 19" src="https://user-images.githubusercontent.com/10568965/125558567-77575c36-66d7-491d-97c6-e0b4e868809d.png">

Each epoch has 32 * 128 attestations, we really only need to get block roots at 32 slots instead of `32 * 128 = 4096`.
We should apply the cache strategy for both phase0 and altair.

**Comment by dapplion** [comment]
Added local cache in altair attestation processing, closing for now
