### ISSUE TITLE
Error processing finalized checkpoint

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#2533]
**Describe the bug**

When syncing on master ( 7b70ab66 , on both mainnet and prater), I get the following error on almost all, if not all, of the finalized epochs that we try to process:
```
May-18 18:44:30.867 []                 info: Syncing - 1 days left - 3.11 slots/s - finalized: 29195 0x3a79…1e07 - head: 934305 0x898b…58c3 - clockSlot: 1211620 - peers: 5
  May-18 18:44:30.903 [CHORES]          error: Error processing finalized checkpoint epoch=29195 message=No block found for root 0x48390950987358929f6eb8a909fb2b9dd4577047c3f3df1660080bb88e3da5a0
  Error: No block found for root 0x48390950987358929f6eb8a909fb2b9dd4577047c3f3df1660080bb88e3da5a0
      at /usr/app/packages/lodestar/src/tasks/tasks/archiveBlocks.ts:73:19
      at async Promise.all (index 348)
      at ArchiveBlocksTask.processCanonicalBlocks (/usr/app/packages/lodestar/src/tasks/tasks/archiveBlocks.ts:69:7)
      at ArchiveBlocksTask.run (/usr/app/packages/lodestar/src/tasks/tasks/archiveBlocks.ts:50:7)
      at TasksService.processFinalizedCheckpoint (/usr/app/packages/lodestar/src/tasks/index.ts:79:7)
      at Object.job (/usr/app/packages/lodestar/src/tasks/index.ts:74:43)
      at Timeout._onTimeout (/usr/app/packages/lodestar/src/util/queue/index.ts:106:22)
```

Here is a log file with more details (while syncing on mainnet):

[fc-test.txt](https://github.com/ChainSafe/lodestar/files/6504351/fc-test.txt)

**Comment by dapplion** [comment]
@tuyennhv Could it have something to do with the ordering of archiving tasks?

**Comment by twoeths** [comment]
we order the archiving tasks already 
https://github.com/ChainSafe/lodestar/blob/379ad5da7a6e3731dab11406753f978c08400803/packages/lodestar/src/tasks/index.ts#L74

so it's something else ?!

**Comment by twoeths** [comment]
from the log file (mainnet): 
```
epoch=12 message=No block found for root 0x03409dd1ea96a11296515cdf319c2b1c939c99af8de9fec56165f05e1217651e
```

that block is actually a previous finalized checkpoint
```
May-18 15:41:14.962 [CHAIN]         [36mverbose[39m: Fork choice finalized epoch=11, root=0x03409dd1ea96a11296515cdf319c2b1c939c99af8de9fec56165f05e1217651e
```

this is the edge case: the previous finalized block was retained in forkchoice but we deleted in db. The expected behavior is not to delete that block from the previous round to keep it synchronized with forkchoice.
