### ISSUE TITLE
Improve validator HttpClient

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2545]
**Describe the bug**

The HttpClient error handling can be improved.

For example it re-writes 404 errors to endpoint not found but there are more conditions that can return 404
https://github.com/ChainSafe/lodestar/blob/df626ea92a579a5722fa70885e296a5d0c1fc847/packages/validator/src/util/httpClient.ts#L74-L75

It should also display the full error message in all cases regardless of the code

**Comment by wemeetagain** [comment]
Ideally we can pull out the api client into a more feature-complete standalone module. Then the validator can just use the api client, and focus on housing just the validator logic.

**Comment by dapplion** [comment]
Done
