### ISSUE TITLE
Separate preset from config

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#2547]
**Is your feature request related to a problem? Please describe.**

- The `IBeaconConfig` object has become a catch-all object to house many things. Many functions/modules/etc require a config object, and its not immediately clear _why_. 
- The `IBeaconSSZTypes` object is seemingly overly abstract. In practice, we only ever need a single copy of all ssz types, and ssz types don't change. (They only change in testing, when we use the minimal config)
- Our organization, the naming, diverges from the spec. It could be more closely aligned if we try.

**Describe the solution you'd like**

With the introduction of ethereum/eth2.0-specs#2390, we may simplify our code by moving much of the config logic into static imports.

I also recommend using this opportunity to realign our naming with the spec. This will make it much easier for new contributors to pick up our code.

Specifically, we can separate our `IBeaconParams` into two interfaces, eg: `IBeaconPreset` and `IBeaconConfig`
The `IBeaconContig` being the run-time params
The `IBeaconPreset` being the 'compile-time' params
IBeaconPreset may be exposed like:

`preset.ts`
```ts
// Use environment variable or other means to switch presets
if (process.env.LODESTAR_PRESET === "mainnet") {
  exports = require("./mainnet"):
} else ...
```

The preset values can then be accessed like "constants"

```ts
import {SYNC_COMMITTEE_SIZE} from "@chainsafe/lodestar-preset";
...
```

The presets include all variables needed to create SSZ types. So then SSZ types can be exported/imported in the same way:
```ts
import {Root, phase0} from "@chainsafe/lodestar-ssz-types";
Root.equals(...);
phase0.BeaconState.hashTreeRoot(...);
```

This would let us simplify our current `IBeaconConfig` to be `IBeaconConfig & IBeaconForkInfo` or similar.
Note that the types are no longer included here!
eg:
```ts
// Now IBeaconConfig can be the thing named 'config' in the specs, ie the runtime configuration
interface IBeaconConfig {
  SECONDS_PER_SLOT: number;
  ...
}
interface IBeaconForkInfo {
  forks: {[K in ForkName]: IForkInfo};
  getForkInfo(slot: Slot): IForkInfo;
  ...
}

// what was previously called IBeaconConfig can be the union or similar of these two
// Or we can keep them separate? up to us
interface INewIBeaconConfig = IBeaconConfig & IBeaconForkInfo;
```

Many downstream functions pass in a config just do hash/serialize/etc a type, they can all be simplified:
```ts
// before
function getFoo(config: IBeaconConfig, data) {
  config.types.Root.equals(...);
  }

// after
import {Root} from "@chainsafe/lodestar-ssz-types";
function getFoo(data) {
  Root.equals(...);
}
```

The one hiccup here that would need to be worked thru is how ssz types vs typescript types are exported/imported so not to step on one another:
eg:
```ts
import {Root} from "@chainsafe/lodestar-types";
// Root is a typescript type (doesn't actually exist in javascript)
import {Root} from "@chainsafe/lodestar-ssz-types";
// Root is an ssz type (eg: a javascript object with methods)

// how should this naming conflict be resolved??
```

Open discussion items:
- Naming? standardize to spec? eg: "preset", "config", etc
- Packages? unify packages? how to organize code: "preset", "config", "fork", "types" (ts and ssz)
- How to handle import clash between ts and ssz types

**Describe alternatives you've considered**

status quo? This update intentionally limits the flexibility and number of `IBeaconSSZTypes` instantiated in a single javascript process (to 1). If that was an issue for some reason, we wouldn't want to do this.

**Additional context**

ethereum/eth2.0-specs#2390

**Comment by dapplion** [comment]
This is great but I would work by steps:
1. Split params following ethereum/eth2.0-specs#2390, keep using the config object everywhere. Rename following the spec
2. Figure out latter how to deal with the issues you mentioned about name clashing (e.g. `Root`), etc.

**Comment by twoeths** [comment]
> How to handle import clash between ts and ssz types

I prefer `Root` for typescript type and `RootType` (or `RootSSZType`) for ssz type, that should make it easier to understand for new contributors
