### ISSUE TITLE
No BLS public key validation due to validate parameter missing

### ISSUE THREAD

**Issue by dnkolegov** [ChainSafe/lodestar#2555]
**Describe the bug**

To create a public key BLS spec requires first validate the public key bytes. 
To validate the input bytes [fromBytes](https://github.com/ChainSafe/bls/blob/master/src/blst/publicKey.ts#L12) must be called as `fromBytes(bytes, type, true)`.

The following fragments call fromBytes without validation:
- https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/chain/bls/multithread/worker.ts#L39
- https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/chain/bls/multithread/worker.ts#L53
- https://github.com/ChainSafe/lodestar/blob/88e1280632f06891fe1dcd210cf3272609c7729f/packages/light-client/src/utils/utils.ts#L65

**Expected behavior**

The `fromBytes` function should be called with validate = true

**Steps to Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

- OS: 
- Version: 
- Branch: 
- Commit hash:

**Comment by dapplion** [comment]
@dnkolegov thanks for helping proof-read our code! In this case it's not necessary to validate the public key since we already did when adding the public key to the state here
https://github.com/ChainSafe/lodestar/blob/074649e35fe6a20a5aeab8898b67b73dca2e2900/packages/beacon-state-transition/src/phase0/block/processDeposit.ts#L42-L43

I think we should add a comment in the lines you've reference to clarify the intention

**Comment by dnkolegov** [comment]
Make sense. Thanks.
> I think we should add a comment in the lines you've reference to clarify the intention

It would be great.

**Comment by dnkolegov** [comment]
The same approach is used for Signature. 

Signature.fromBytes is called without validation=true:
- https://github.com/ChainSafe/lodestar/blob/88e1280632f06891fe1dcd210cf3272609c7729f/packages/light-client/src/client/validation.ts#L138
- https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/api/impl/validator/validator.ts#L263
- https://github.com/ChainSafe/lodestar/blob/d9bb4e58708878ba86d0979c475c4dcea9a4f655/packages/lodestar/src/db/syncCommittee.ts#L147
- https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/db/syncCommittee.ts#L169

**Comment by wemeetagain** [comment]
Resolved with https://github.com/ChainSafe/lodestar/pull/3277
