### ISSUE TITLE
Add ForkChoice metrics

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2558]
Add fork choice metrics to quantify its performance. The list of metrics below are from Lighthouse. It's not necessary to implement all of them if they don't make sense in our case. Review Lighthouse code to check how each metric can be plug into the ForkChoice module.

- [ ] `beacon_fork_choice_requests_total`: Count of occasions where fork choice has tried to find a head
- [ ] `beacon_fork_choice_errors_total`: Count of occasions where fork choice has returned an error when trying to find a head
- [ ] `beacon_fork_choice_changed_head_total`: Count of occasions fork choice has found a new head
- [ ] `beacon_fork_choice_reorg_total`: Count of occasions fork choice has switched to a different chain
- [ ] `beacon_fork_choice_seconds`: Full runtime of fork choice
- [ ] `beacon_fork_choice_find_head_seconds`: Full runtime of fork choice find_head function - Really imporant! See https://github.com/ChainSafe/lodestar/issues/2455
- [ ] `beacon_fork_choice_process_block_seconds`: Time taken to add a block and all attestations to fork choice
- [ ] `beacon_fork_choice_process_attestation_seconds`: Time taken to add an attestation to fork choice
- [ ] `beacon_balances_cache_hits_total`: Count of times balances cache fulfils request
- [ ] `beacon_balances_cache_misses_total`: Count of times balances cache fulfils request

Part of https://github.com/ChainSafe/lodestar/issues/2468

**Comment by g11tech** [comment]
@dapplion  @wemeetagain  could you assign this to me

**Comment by g11tech** [comment]
@dapplion  regarding `beacon_fork_choice_process_block_seconds`:

 `lodestar_stfn_process_block_seconds` is already implemented as . 

![image](https://user-images.githubusercontent.com/76567250/123519342-3c653100-d6c8-11eb-8703-0e3826dde7a2.png)

![image](https://user-images.githubusercontent.com/76567250/123519350-556de200-d6c8-11eb-8890-260d64c90677.png)

so in this metric `beacon_fork_choice_process_block_seconds`, do we have to time the `forkChoice.onBlock`?

**Comment by g11tech** [comment]
for `beacon_fork_choice_process_attestation_seconds` do we want to time the entire 'processAttestation' fn 
![image](https://user-images.githubusercontent.com/76567250/123520613-1ee79580-d6cf-11eb-89ab-389f8f514bad.png)

or just `forkChoice.onAttestation`?

![image](https://user-images.githubusercontent.com/76567250/123520680-6c640280-d6cf-11eb-9874-5902733327eb.png)

**Comment by dapplion** [comment]
@g11tech I think the metrics we have for the fork choice are good enough for now
