### ISSUE TITLE
Check Validator + BeaconNode Config

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#2573]
**Is your feature request related to a problem? Please describe.**

In a discussion w @dapplion:
> Oh, the node is running minimal, and the validator is running mainnet

We'd like to prevent that scenario from happening.

**Describe the solution you'd like**

Add a check in the validator to ensure that the validator is connecting to a beacon node w the same configuration.
Eg: fetch from the `config.getSpec` endpoint and compare against local values. Throw if the beacon node isn't configured the same as the validator.

**Comment by dapplion** [comment]
Fixed with https://github.com/ChainSafe/lodestar/pull/2574
