### ISSUE TITLE
Validator CLI handler ignores --preset option

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2576]
**Describe the bug**

Working on https://github.com/ChainSafe/lodestar/pull/2575 and due the bug fixed with https://github.com/ChainSafe/lodestar/pull/2574 the validator client was using fork version 0x00000000 when the minimal is 0x00000001.

**Expected behavior**

When running the validator CLI with --preset minimal the fork must be 0x00000001.

**Comment by 3xtr4t3rr3str14l** [comment]
Maybe this should only be allowed under certain conditions?  Should a user be allowed to use a minimal config on mainnet, for example?  Also, as it stands right now, the validator just uses the config that we generate when running `beacon` or `init`.  Even so, the validator currently just uses whatever config we put in our rootDir when running `beacon` or `init`.  I feel like we have a few options:
1) disable `--preset` for the validator command and have it continue to use the config generated in the `beacon` and/or `init` command
2) allow `--preset` for the validator, but overwrite whatever config we may already have in the rootDir when `--preset` is passed to `validator`
3) ???

@dapplion thoughts?

**Comment by dapplion** [comment]
So using mainnet **requires** you to not use minimal. Each network config implicitly chooses a preset. Exposing both --network and --preset is incompatible. You should define one or the other but not both.

@wemeetagain With the recent refactor of the params / config what do you think we should do at the CLI level

**Comment by wemeetagain** [comment]
IMO remove --preset and stop "supporting" different presets explicitly with cli code. Very low priority to add additional code to "make it easier".
If a network/setup requires using a different preset, it can currently be done like:
- set `PRESET_BASE` in config.yaml
- run lodestar with `LODESTAR_PRESET` env variable set to match
