### ISSUE TITLE
altair.processAttestation() performance issue

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2618]
**Describe the bug**

`altair.processAttestation()` calculates the total balance of the validator set for every index of every attestation.

![Screenshot from 2021-06-02 14-47-01](https://user-images.githubusercontent.com/35266934/120482737-b3512780-c3b1-11eb-90da-2c8eaf931e64.png)
![Screenshot from 2021-06-02 14-47-20](https://user-images.githubusercontent.com/35266934/120482749-b5b38180-c3b1-11eb-86ac-a805b6ab6c92.png)

**Expected behavior**

This part should be optimized, and compute that total balance the least number of times possible.

**Comment by twoeths** [comment]
+ We don't have to always call `getBaseRewards` if the participation is good for an epoch (i.e. the participation has timely source + target + head already)
+ Improve getBaseRewards: `getBaseRewardPerIncrement()` should be the same for an epoch so it should be cached in `EpochContext`
