### ISSUE TITLE
Benchmark workflow: no such file or directory

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2634]
**Describe the bug**

From https://github.com/ChainSafe/lodestar/runs/2743727116?check_suite_focus=true

we get through `Run performance test` but failed at `Store benchmark result`

```
Error: Invalid value for 'output-file-path' input: Error: Cannot stat '/home/runner/work/lodestar/lodestar/benchmark-output.txt': Error: ENOENT: no such file or directory, stat '/home/runner/work/lodestar/lodestar/benchmark-output.txt'
```

**Expected behavior**

No error

**Comment by dapplion** [comment]
Because the path is relative, and likely the execution context of node is not the same.
