### ISSUE TITLE
Chart view for benchmark result

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2642]
**Is your feature request related to a problem? Please describe.**

Now we have some benchmark data, `github-action-benchmark` supports pushing this data to `gh-pages` branch with a chart.

**Describe the solution you'd like**

+ Enabling `auto-push` input
+ We may want to debug the action by enabling `ACTIONS_STEP_DEBUG` as in https://github.com/actions/toolkit/blob/HEAD/docs/action-debugging.md#step-debug-logs

**Comment by dapplion** [comment]
Yeah that would be nice! Tho we are currently using github pages for the docs, so we'll have to do something a bit custom to render everything at once

**Comment by twoeths** [comment]
the current gh page works well until now
