### ISSUE TITLE
Insufficient BLS signature validation for lodestar+bls/herumi

### ISSUE THREAD

**Issue by asanso** [ChainSafe/lodestar#2645]
The Lodestar's [BLS signature validation](https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/chain/bls/index.ts#L26) when used in combination with [bls/herumi](https://github.com/ChainSafe/bls/blob/master/src/herumi/signature.ts#L20) is not sufficient.

The code assumes

``` 
   // Signatures all come from the wire (untrusted) are all bytes compressed, must be:
    // - Parsed from bytes
    // - Uncompressed
    // - subgroup_check
    // - consume in Pairing.aggregate as affine, or mul_n_aggregate as affine
    // Just send the raw signture recevied as bytes to the thread and verify there
```

This assumption is `true` for [bls/blst](https://github.com/ChainSafe/bls/blob/master/src/blst/signature.ts#L13) where the `validate` parameter is used. But not in the [bls/herumi](https://github.com/ChainSafe/bls/blob/master/src/herumi/signature.ts#L20)  case

**Comment by g11tech** [comment]
hi @dapplion, as per my analysis, bls/blst's validate is checking if the signature is a (G2) group point. bls/herumi is checking the order of the signature point w.r.t. G2 order (in signature constructor: isValidOrder ). will continue digging.

**Comment by dapplion** [comment]
> hi @dapplion, as per my analysis, bls/blst's validate is checking if the signature is a (G2) group point. bls/herumi is checking the order of the signature point w.r.t. G2 order (in signature constructor: isValidOrder ). will continue digging.

@g11tech Can you try to validate this test vector?

```js
export const POINT_NOT_IN_G2 = Buffer.from(
  "8123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
  "hex"
);
```

**Comment by g11tech** [comment]
this point fails sigValidate of bls/blst but passes isValidOrder of bls/herumi, which i guess is only checking the order of the point and not its group membership (of G2). 

On further digging bls/herumi uses "bls-eth-wasm" under the hood to wrap the bls functionality in webassembley. however its signature class doesn't export any group validation method, just the order validation:

https://github.com/herumi/bls-eth-wasm/blob/master/src/bls.js#L550-L580

I will further keep digging through.

**Comment by dapplion** [comment]
> this point fails sigValidate of bls/blst but passes isValidOrder of bls/herumi, which i guess is only checking the order of the point and not its group membership (of G2).
> 
> On further digging bls/herumi uses "bls-eth-wasm" under the hood to wrap the bls functionality in webassembley. however its signature class doesn't export any group validation method, just the order validation:
> 
> https://github.com/herumi/bls-eth-wasm/blob/master/src/bls.js#L550-L580
> 
> I will further keep digging through.

From Antonio's messages:


this is how prysm used to do [group verification] (when they had support for herumi)

https://github.com/prysmaticlabs/prysm/blob/develop/shared/bls/herumi/init.go#L13

**Comment by g11tech** [comment]
ok, this looks easy solve:

accidentally tried the POINT_NOT_IN_G2  test vector  in the lodestar repository and realized that fromBytes was throwing error there for herumi as well, tried comparing the installed node_module's @chainsafe/eth with the @chainsafe/eth codebase. 
finally figured out that yarn.lock of lodestar is using 0.4.8 (while package has ^0.4.4)
![image](https://user-images.githubusercontent.com/76567250/134160979-ee514383-741b-47f7-8dbe-a0f9aea2a8e4.png)

 while chainsafe/eth code base's yarn.lock is using 0.4.4. 
![image](https://user-images.githubusercontent.com/76567250/134161083-53ca23f8-5b60-496e-8881-e7a0cb177974.png)



digging through the releases of bls-eth-wasm and figured out that that the underlying bls code was updated in bls-eth-wasm's 0.4.8.
![image](https://user-images.githubusercontent.com/76567250/134160711-e3157f1d-9060-4ae1-a97a-28ba0862e3e0.png)

 locally updated the package to 0.4.8 in chainsafe/bls and now the fromBytes of chainsafe/bls also starts throwing error on the wasm's signature deserialize call:
previously in chainsafe/bls codebase (bls-eth-wasm: 0.4.4) which accepted this signature point:
![image](https://user-images.githubusercontent.com/76567250/134161657-394aa33a-2c95-4b4a-be3a-996ec58bcd39.png)

**post: yarn-upgrade bls-eth-wasm trying to build signature from this signature point throws error**
![image](https://user-images.githubusercontent.com/76567250/134161221-679fc5c3-0ed2-4a64-923d-fbcac63b8b87.png)

will send a PR to update the yarn.lock and add this test in testcases in @chainsafe/bls

**Comment by asanso** [comment]
thanks @g11tech  .
Question are you also passing `validate =true` or is it the default in https://github.com/ChainSafe/bls/blob/master/src/interface.ts#L42

**Comment by g11tech** [comment]
for bls/herumi this param is not even used and its signature deserialize request from the provided data itself fails (on updated bls-eth-wasm 0.4.8 which chainsafe/bls package uses)  so it seems its always being validated inside the wasm module in the updated version:

![image](https://user-images.githubusercontent.com/76567250/134166656-1e2f2545-7eba-4aed-b1c0-5a45c9aabf6b.png)

in previous bls-eth-wasm version of 0.4.4 this call was success returning the signature.

**Comment by asanso** [comment]
>so it seems its always being validated inside the wasm module in the updated version

well this is nice from the security point of view but it might break the semantic of the method (what if you pass `validate=false` or omit the parameter that AFAIK defaults to `false`?)

**Comment by g11tech** [comment]
> > well this is nice from the security point of view but it might break the semantic of the method (what if you pass `validate=false` or omit the parameter that AFAIK defaults to `false`?)

unfortunately herumi bls-eth-wasm API doesn't provide this option. But imho, semantically if not in G2 implies not a signature (for eth) and hence shouldn't be loadable into the signature structure. 

Do you think there is a use of loading an invalid Signature point? my guess is not doing validation would be for the purposes of speed where one is sure of the correctness of signature.

**Comment by asanso** [comment]
>Do you think there is a use of loading an invalid Signature point? 

no but at this point i would remove the boolean from the signature of the method otherwise is a bug

**Comment by g11tech** [comment]
I can make it to default true, those who would want to skip validation could be explicit to pass false but will make it throw error in herumi and hence only work in blst

@dapplion also,  let know what you would think interface/behavior should be?

(updated herumi wasm  always does validation)

**Comment by asanso** [comment]
>I can make it to default true, 

nice this will also solve stuff like https://github.com/ChainSafe/lodestar/issues/2555

**Comment by g11tech** [comment]
@asanso PR for the above resolution in the chainsafe/bls package. Have also added a test point for invalid signature for not in G2.
https://github.com/ChainSafe/bls/pull/106

Will create send another one for lodestar post merge of above for package update and making the validation flag to explicit true for readability purposes.  :+1:
