### ISSUE TITLE
[Hobbits] - add RPC call

### ISSUE THREAD

**Issue by ajoydas** [ChainSafe/lodestar#265]
Implement [hobbits](https://github.com/deltap2p/hobbits) wire protocol for `lodestar`. The implementation is divided into 2 phases. 
* Implement the RPC message protocol described in the [rpc-messages.md](https://github.com/deltap2p/hobbits/blob/master/specs/rpc-messages.md).
* Implement the Gossip protocol described in the [gossip.md](https://github.com/deltap2p/hobbits/blob/master/specs/gossip.md).

This issue is for implementing the RPC message protocol  in `lodestar`.

**Comment by GregTheGreek** [comment]
Please add description to issue

**Comment by GregTheGreek** [comment]
Closing as this is not a priority.
