### ISSUE TITLE
Update to spec 1.1.0-alpha.6

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#2660]
**Is your feature request related to a problem? Please describe.**

We're inconsistently between alpha.5 and alpha.6. This is not currently exposed because we _aren't_ currently running the altair mainnet spec tests.

**Describe the solution you'd like**

Ensure all aspects of alpha.6 have been implemented.
Implement the altair mainnet spec tests.

**Comment by twoeths** [comment]
Spec 1.1.0-alpha.7 just released 10h ago
