### ISSUE TITLE
Batch BLS verification for attestations

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2686]
**Is your feature request related to a problem? Please describe.**

Very promising optimization, it has been very successful in Nimbus and Lighthouse. See results here: https://github.com/sigp/lighthouse/pull/2399. We struggle to process all attestations and aggregates in Prater, this will help a lot.

**Describe the solution you'd like**

https://github.com/sigp/lighthouse/pull/2399

**Comment by g11tech** [comment]
@dapplion kindly assign, could take a look at it  and study lighthouse implementation while crunching metrics

**Comment by dapplion** [comment]
Taking it myself since it's time-sensitive. I do recommend to take in less wide reaching complex tasks just to get a better handle on the lodestar package, gossip, etc.

**Comment by dapplion** [comment]
After thinking about it for while the best to put this is in the BLS queue itself.

- Buffer submitted work for some time (~10-100ms)
- Then construct packets of work that will be verified in batch, if some re-verify all individually. This logic should happen in the worker side to reduce communication.
- We can add logic to only allow this behaviour on certain work packets.
- The BLS queue should not apply this strategy to work with a lot a signature sets, only to those with fewer than 3-5 (aggregates + attesations)

Still WIP: How to efficiently force buffering without slowing processing when it's necessary? I.e. we don't want to slow syncing or block processing.
- Def we should only buffer objects that request than. The gossip att and agg functions should pass a flag to the bls verifier
- The BLS verifier can have two arrays (a, b) where it places objects depending on the current time.
```ts
onWork(work) {
  if (work.shouldBuffer) {
    if (now % 100 < 50) {
      a.push(work)
    } else {
      b.push(work)
    }
  } else {
    submitWork(work)
  }
}

when(now % 100 === 0, () => submitWork(a))
when(now % 100 === 50, () => submitWork(b))
```

**Comment by dapplion** [comment]
@ChainSafe/level

**Comment by dapplion** [comment]
> @ChainSafe/lextlevel
