### ISSUE TITLE
Replace ActiveState and CrystallizedState with BeaconState

### ISSUE THREAD

**Issue by Mikerah** [ChainSafe/lodestar#27]
In order to simplify the protocol, a recent change was made to the specification to combine both the active state and crystallized state into a single state. 

We will need to remove the active state and crystallized state classes and make a new beacon state class. Here's the reference in the spec: https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#beacon-chain-state

**Comment by GregTheGreek** [comment]
Closing no longer relevant due to #39 .
