### ISSUE TITLE
SSE events api not supporting cors settings

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#2712]
**Describe the bug**

**Expected behavior**

**Steps to Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

- OS: 
- Version: 
- Branch: 
- Commit hash:

**Comment by 3xtr4t3rr3str14l** [comment]
@mpetrunic can you provide more details in the issue description?

**Comment by mpetrunic** [comment]
> @mpetrunic can you provide more details in the issue description?

When using raw stream, headers from other plugins aren't being set (which means we don't get cors headers set). In my SSE plugin, I've handled that: https://github.com/NodeFactoryIo/fastify-sse-v2/pull/22/files#diff-57716bc53661ccdb4571d571f1a5493294848965ae6068dbb3d9a1167d2cc1a6R11

**Comment by g11tech** [comment]
Assign pls, would like to take a look

**Comment by g11tech** [comment]
seems like the issue doesn't exist anymore. The curl inspection of the options of the events endpoint indicates that `access-control-allow-origin` header was correctly set (to `example1.com` as provided in the cli param)

![image](https://user-images.githubusercontent.com/76567250/137965295-57fae529-08c7-4b05-ae27-3dd9466fb669.png)
