### ISSUE TITLE
Too many closures retained in heap memory

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2720]
**Describe the bug**

When I run benchmark for `processInactivityUpdates` I found that there are too many closures retained
<img width="1265" alt="Screen Shot 2021-06-18 at 09 32 20" src="https://user-images.githubusercontent.com/10568965/122497752-1da3d200-d018-11eb-8e00-1574f0e8d564.png">

Most of them are from the hook when we get sub tree
<img width="1231" alt="Screen Shot 2021-06-18 at 09 32 56" src="https://user-images.githubusercontent.com/10568965/122497820-38764680-d018-11eb-8db3-7ac1a1f7bcdc.png">

**Expected behavior**
+ Since the hook is important to update the parent tree, I'd think if it's possible to create `getSubTreeReadonly` to avoid the hook? That should work for some use cases.
+ Find and avoid the below pattern to avoid accessing a property inside state too frequently
```ts
for (let i = 0; i < process.statuses.length; i++) {
    const status = process.statuses[i];
    if (hasMarkers(status.flags, FLAG_ELIGIBLE_ATTESTER)) {
      if (hasMarkers(status.flags, FLAG_PREV_TARGET_ATTESTER_OR_UNSLASHED)) {
        state.inactivityScores[i] -= Math.min(1, state.inactivityScores[i]);
      } else {
        state.inactivityScores[i] += Number(INACTIVITY_SCORE_BIAS);
      }
      if (!inActivityLeak) {
        state.inactivityScores[i] -= Math.min(Number(INACTIVITY_SCORE_RECOVERY_RATE), state.inactivityScores[i]);
      }
    }
  }
```
in the example above, we should get `state.inactivityScores` only 1 time and assign to a separate variable.
**How to reproduce**
Run `processInactivityUpdates` benchmark

**Comment by dapplion** [comment]
@tuyennhv Once we merge all the memory related improvements we should do another round of heap snapshots to validate the improvements. Then we can review this issues :+1:

**Comment by dapplion** [comment]
Bump

**Comment by dapplion** [comment]
@tuyennhv Would be nice get a heap snapshot of latest version and compare. With recent ssz bump there's should be no more closures for to tree hooks

**Comment by dapplion** [comment]
Closing issues for specific incidents on old versions of Lodestar, please re-open if it happens with latest stable
