### ISSUE TITLE
Add e2e testing support for browsers

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2723]
**Is your feature request related to a problem? Please describe.**

We have no assurance in CI that code doesn't break in the browser, and it does.

**Describe the solution you'd like**

Add Karma like in bls repo with sample webpack config https://github.com/ChainSafe/bls/blob/master/karma.conf.js

**Comment by nazarhussain** [comment]
@dapplion I found the [Cypress](https://www.cypress.io/) more appealing and feature rich for the browser testing. So I am updating the issue accordingly and opening the PR.

**Comment by dapplion** [comment]
> @dapplion I found the [Cypress](https://www.cypress.io/) more appealing and feature rich for the browser testing. So I am updating the issue accordingly and opening the PR.

Sounds good! :+1:
