### ISSUE TITLE
Missed blocks -  can't produce blocks on time

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2726]
**Describe the bug**

Watching our Prater validators, all blocks produced with Lodestar are orphaned:
- https://prater.beaconcha.in/validator/200983#blocks (node with 1 validator)
- https://prater.beaconcha.in/validator/200984#blocks (node with 16 validators)

I tracked a missed block proposal in the REST API metrics and got:
- produceBlock: 4.01s
- publishBlock: 64.1ms

**Expected behavior**

Blocks must be produced way faster. Otherwise we won't get attestations on it and the network will ignore it. Other clients produce blocks in ~ 100ms tops if I recall.

- [ ] Add benchmark to produceBlock
- [ ] Debug and improve performance

**Comment by twoeths** [comment]
the produceBlock itself may not be an issue as when I call that api in my server without any validator, it returned immediately.

a lot of apis takes ~4s as in http://167.86.102.209:3000/d/lodestar/lodestar?orgId=1&refresh=30s, for example `getAttesterDuties` or `produceAttestationData`

we need to improve out node in general, it's most likely it's the attestation gossip tasks as shown below from a node with full attestation subscriptions
<img width="1301" alt="Screen Shot 2021-06-24 at 15 05 39" src="https://user-images.githubusercontent.com/10568965/123226284-b7c6b700-d4fd-11eb-8d11-11b1c2eac4c8.png">
[0624-prater-full-attestation-subscriptions.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/6707467/0624-prater-full-attestation-subscriptions.cpuprofile.zip)

**Comment by dapplion** [comment]
> we need to improve out node in general, it's most likely it's the attestation gossip tasks as shown below from a node with full attestation subscriptions

I worry if it's that too, however some API calls take very little time. Maybe we should have a script next to the node that calls a free API method like version every second and plot response times through a full epoch.

**Comment by 3xtr4t3rr3str14l** [comment]
Regardless of what the cause may be, I have updated the #2746 to include the (mostly, a few stubs here and there) full test with benchmark results for `produceBlock` so we can at least easily know how it's performing.

**Comment by dapplion** [comment]
Recent metrics across all our infra show that we produce all blocks in time
