### ISSUE TITLE
Slasher client

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#2744]
There is work currently being done by lighthouse to implement a "slasher" to monitor the network for slashable offenses.  It looks like it is still somewhat of a work in progress, but maybe this is something we can keep an eye on and implement ourselves at some point.

https://lighthouse-book.sigmaprime.io/slasher.html

**Comment by dapplion** [comment]
I don't think we should implement a slasher. It's a very resource intensive operation and very far from the "light" real we are moving towards
