### ISSUE TITLE
Replace .map instances with for loops in Repository class (abstractRepository.ts)

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#2749]
When I use the following benchmark to compare `for` loops and maps:

```typescript
import {BenchmarkRunner} from "@chainsafe/lodestar-utils/test_utils/benchmark";

describe.only("", () => {
  it("", async () => {
    const runner = new BenchmarkRunner("produce block", {
      minMs: 1000,
      runs: 1024,
    });
    
    const length = 100000;
    const data = Array.from({length})
    await runner.run({
      id: "for loop",
      run: async () => {
        const values = [];
        for (let i = 0; i < length; i++) {
          values.push(data[i])
        }
      },
    });
    await runner.run({
      id: "map",
      run: async () => {
        data.map(i => i)
      },
    });
  })
})
```

I get the following results:

```
for loop    527.2788 ops/s      1.896530 ms/op   1025 runs    1.950 s
map         320.8606 ops/s      3.116618 ms/op    640 runs    2.001 s
```

We are currently using `.map` in `keys()`, `values()`, `entries()`.  Maybe we can optimize by replacing the .maps with for loops.

**Comment by dapplion** [comment]
The time difference is only relevant when looping over large arrays. If the length i less than 1000 it really doesn't matter unless it's a super hot path. Try to analyze how frequently something is looped, if it's a hot path then we should 100% switch to raw for loops

**Comment by dapplion** [comment]
Most hot paths looping over the entire validator set have been covered with https://github.com/ChainSafe/lodestar/pull/3760
