### ISSUE TITLE
Use reversed shuffled list in validator duties retrieval

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#2764]
Would it make sense to keep a reverse shuffled list to speed this even more?

If the shuffled array looks like `[3,0,2,1]` the reverse array would be `[1,3,2,0]`. Given a validator index you could get its postion in the shuffled array in O(1) time. From there with modulos you can figure out the slot, committee and index.

Would that be worth it the extra memory? At 250_000 validators x 8 bytes = 2MB

_Originally posted by @dapplion in https://github.com/ChainSafe/lodestar/issues/2717#issuecomment-869968368_

**Comment by 3xtr4t3rr3str14l** [comment]
@dapplion to clarify, what do you mean by "reversed" exactly?  Should the reversed array in your example by `[1, 2, 0, 3]`?

**Comment by dapplion** [comment]
> @dapplion to clarify, what do you mean by "reversed" exactly? Should the reversed array in your example by `[1, 2, 0, 3]`?

So it's not literally reversed, but an array showing the position of validator {i} in the shuffled list.

**Comment by dapplion** [comment]
After this many months, I don't believe this is necessary or won't provide tangible benefits
