### ISSUE TITLE
metrics server starts even without --metrics.enabled flag

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#2775]
As reported by a discord member in the lodestar channel.
![image](https://user-images.githubusercontent.com/76567250/123904364-fb9e3e00-d98d-11eb-9b4d-8575b973a432.png)

**Describe the bug**

**Expected behavior**

**Steps to Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

- OS: 
- Version: 
- Branch: 
- Commit hash:

**Comment by dapplion** [comment]
I've seen that too, we should review and ensure it's not run nor we log that message then

**Comment by g11tech** [comment]
@dapplion  this is coming from: https://github.com/ChainSafe/lodestar/blob/4639d98fe99bdbb5b01998e8d106f79f533f09fc/packages/cli/src/networks/index.ts#L60-L77 
when beacon node options are created.
https://github.com/ChainSafe/lodestar/blob/4639d98fe99bdbb5b01998e8d106f79f533f09fc/packages/cli/src/config/beaconNodeOptions.ts#L27

I think we should only build eth1 options data in the `getNetworkBeaconNodeOptions` and remove the others: `metrics`,`api`, `network` as if any default is required they should come from defaultOptions.

**Comment by dapplion** [comment]
> getNetworkBeaconNodeOptions

Yeah it's odd, we should remove from that function lines

https://github.com/ChainSafe/lodestar/blob/4639d98fe99bdbb5b01998e8d106f79f533f09fc/packages/cli/src/networks/index.ts#L64
https://github.com/ChainSafe/lodestar/blob/4639d98fe99bdbb5b01998e8d106f79f533f09fc/packages/cli/src/networks/index.ts#L69

And add the flag to the default docker-compose files
