### ISSUE TITLE
Implement REST api

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#278]
REST was defined as replacement standard for rpc in frozen spec.
Definition: https://github.com/ethereum/eth2.0-specs/blob/v0.8.0/specs/validator/0_beacon-node-validator-api.md

Other related tasks:
- adjust configuration
   - user should be able to configure api type - rpcOverHttp, rpOverWs, rest
   - all api types should have configurable host, port and which api group to expose (beacon, validator for now)

**Comment by mpetrunic** [comment]
i would recommend something like https://github.com/fastify/fastify for fast and secure api server

**Comment by GregTheGreek** [comment]
From call:

- Can we ensure in browser support?
