### ISSUE TITLE
CLI git command - don't log to stdout

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2780]
**Describe the bug**

This line logs output to stdout

https://github.com/ChainSafe/lodestar/blob/5173df2453acd6f62b1c152980049e6c7fe4ec8a/packages/cli/src/util/gitData.ts#L59

> Reported by Discord user YorickDowne (he/him), thanks!
```
yorick@ethlinux:~/eth-docker-devel$ docker-compose run --rm consensus
Creating network "eth-docker-devel_default" with the default driver
fatal: not a git repository (or any of the parent directories): .git
Jun-30 09:23:16.939 []                 info: Lodestar version=0.25.1 master 88b23663, network=prater
Jun-30 09:23:17.543 [DB]               info: Connected to LevelDB database name=/var/lib/lodestar/consensus/chain-db
```

**Expected behavior**

Don't log errors nor output to stdout / stderr

**Steps to Reproduce**

Run main docker image

**Comment by g11tech** [comment]
@dapplion  assign pls
