### ISSUE TITLE
Add unknown block attestation cache

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2788]
We want to eventually re-add the unknown block attestation cache. We could use this PR as reference, the cache strategy is pretty solid and sufficiently DOS resistant https://github.com/sigp/lighthouse/pull/2319

Note that given that Lodestar is a minority client this change is **not a priority**. Adding this cache benefits large stakers that send eager attestations. Since Lodestar always waits for the 1/3 mark in Lodestar only devnets it won't have much effect either.

_Originally posted by @dapplion in https://github.com/ChainSafe/lodestar/issues/2754#issuecomment-872936247_

**Comment by dapplion** [comment]
Related to this, @tuyennhv suggested to send the attestations early to increase the chances of getting an inclusion distance of 1

**Comment by twoeths** [comment]
we already implemented this feature https://github.com/ChainSafe/lodestar/blob/v1.11.3/packages/beacon-node/src/network/processor/index.ts#L271
