### ISSUE TITLE
Do attack node tutorial

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2789]
In order to get more people interested in Eth2.0 in general but specially in strengthening its security it would be great to prepare a simple tutorial to modify Lodestar into an attack node to demonstrate a simple vulnerability. The vulnerability could also be manually introduced in the tutorial as part of the exercise.

A goal would be to show that Eth2.0 is accessible to Typescript developers, and become a fun entry-point for those more advanced users wanting to get into the rabbit hole

**Comment by 3xtr4t3rr3str14l** [comment]
@dapplion do you have any examples already in mind for potential attack vectors to demonstrate?

**Comment by dapplion** [comment]
> @dapplion do you have any examples already in mind for potential attack vectors to demonstrate?

Not really

**Comment by philknows** [comment]
This might be a lot of work and requires a lot of context. It might be better for us to spend time working on documentation to improve the codebase. Let the EF bug bounty cover this. Won't fix
