### ISSUE TITLE
Implement REST api client in validator

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#279]
- create REST API client to consume #278 - should implement client interface (might need adjustment)
- adjust validator to choose which api client to use (rpc, rest)

**Comment by GregTheGreek** [comment]
From call:

- Can we ensure in browser support?

**Comment by mpetrunic** [comment]
On validator side, it will definitely work in browser, I mean every page can make http requests. I think this comment belongs in #278  :)

**Comment by twoeths** [comment]
I'm really interested in implementing REST api consumption for validator, can someone assign me to this issue?

**Comment by twoeths** [comment]
For http client library, I'd go with https://github.com/axios/axios because:
+ It supports both browser and NodeJS
+ Built-in typescript
+ Widely used with very high github star

@mpetrunic @GregTheGreek let me know if you have other ideas.

**Comment by GregTheGreek** [comment]
I loved axios back when I used to write full stack web apps. I'm just wondering if it's too bloating?

**Comment by twoeths** [comment]
Yeah .. If you prefer more lightweight candidates then here's what I can come up with:
+ https://github.com/matthew-andrews/isomorphic-fetch
+ https://github.com/visionmedia/superagent

Both are more lightweight and work in both Browser and NodeJS. What do you think?

**Comment by mpetrunic** [comment]
@GregTheGreek I think axios is fine, it has just two small dependencies. Fetch is cool alternative as well but it needs some adjustment for error handling

**Comment by twoeths** [comment]
Ok I'll write a wrapped `httpClient.ts` so that switching from one library to another is not a big deal.

**Comment by twoeths** [comment]
Implementation is done
