### ISSUE TITLE
Improper nonce handling in Noise handshake

### ISSUE THREAD

**Issue by dnkolegov** [ChainSafe/lodestar#2796]
**Describe the bug**
Improper Noise's nonce handling leading to a potential overflow.
The bug was found and created in [js-libp2p-noise](https://github.com/NodeFactoryIo/js-libp2p-noise/issues/102). This bug is suggested for notification and tracking. Please see [js-libp2p-noise](https://github.com/NodeFactoryIo/js-libp2p-noise/issues/102) for more information.

**Comment by dapplion** [comment]
@mpetrunic bump

**Comment by dapplion** [comment]
Thanks for reporting @dnkolegov . Closing since it has a clear path to resolution in https://github.com/ChainSafe/js-libp2p-noise/issues/102 and it's not urgent
