### ISSUE TITLE
Yeerongpilly: Handle SYNC_COMMITTEE_CONTRIBUTION_ERROR_ALREADY_KNOWN

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2797]
**Describe the bug**

This error happens a lot in our log:
```
(node:1) UnhandledPromiseRejectionWarning: Error: SYNC_COMMITTEE_CONTRIBUTION_ERROR_ALREADY_KNOWN
    at aggregateContributionInto (/usr/app/packages/lodestar/src/db/syncCommitteeContribution.ts:146:15)
    at SyncCommitteeContributionCache.add (/usr/app/packages/lodestar/src/db/syncCommitteeContribution.ts:63:7)
    at Eth2Gossipsub.<anonymous> (/usr/app/packages/lodestar/src/network/gossip/handler.ts:116:39)
```

**Expected behavior**

That error happens in gossip handler, meaning it passed gossip validation function.
Investigate why gossip validation function does not detect these messages as `ALREADY_KNOWN`

**Comment by twoeths** [comment]
indexInSubCommittee is undefined
```
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 34732)
(node:1) UnhandledPromiseRejectionWarning: Error: Already aggregated SyncCommitteeMessage - subCommitteeIndex=3 indexInSubCommittee=undefined
    at aggregateSignatureInto (/usr/app/packages/lodestar/src/db/syncCommittee.ts:144:11)
    at SyncCommitteeCache.add (/usr/app/packages/lodestar/src/db/syncCommittee.ts:79:7)
    at GossipHandler.onSyncCommitteeSignature (/usr/app/packages/lodestar/src/network/gossip/handler.ts:131:27)
```

**Comment by dapplion** [comment]
> indexInSubCommittee is undefined
> 
> ```
> (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 34732)
> (node:1) UnhandledPromiseRejectionWarning: Error: Already aggregated SyncCommitteeMessage - subCommitteeIndex=3 indexInSubCommittee=undefined
>     at aggregateSignatureInto (/usr/app/packages/lodestar/src/db/syncCommittee.ts:144:11)
>     at SyncCommitteeCache.add (/usr/app/packages/lodestar/src/db/syncCommittee.ts:79:7)
>     at GossipHandler.onSyncCommitteeSignature (/usr/app/packages/lodestar/src/network/gossip/handler.ts:131:27)
> ```

Probably due to this awful hack 
https://github.com/ChainSafe/lodestar/blob/2685d2fb053975ea026ec1ffa3d8c0ad86677e71/packages/lodestar/src/network/gossip/handler.ts#L130

It's gone with https://github.com/ChainSafe/lodestar/pull/2803
