### ISSUE TITLE
Add --configFile to validator

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#2814]
**Is your feature request related to a problem? Please describe.**
From discord (@stefa2k):

Q: Hi, I'm getting keystoresDir /opt/app/.local/share/lodestar/mainnet/keystores does not exist but I set keystoresDir: /opt/app/keystores in the config yaml via --paramsFile /opt/app/validator.yaml
Am I missing something?

A: it looks the paramsFile only supports the testnet/mainnet params (the ones from the eth2 spec)
our beacon node lets you override all of the cli options via a file --configFile but it doesn't look like the validator supports that
We should add the same thing to the validator, but for now, you'd have to add --keystoresDir via cli

**Describe the solution you'd like**

Allow for validator cli options to be specified in a file, like is possible for the beacon node

**Comment by g11tech** [comment]
@wemeetagain assign/add to my bucket pls
