### ISSUE TITLE
Move DB Bucket definitions to consumer packages

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#2820]
**Is your feature request related to a problem? Please describe.**

DB Bucket entries are all defined in the db package. Some of these entries are used in the beacon node (lodestar package), some are used in the validator (validator package).
The db package should really only be used to define the abstract db logic, and doesn't need to know which buckets exist for all downstream db consumers.

**Describe the solution you'd like**

Move bucket entries to the lodestar and validator packages.

**Describe alternatives you've considered**

Leave as is

**Additional context**

See https://github.com/ChainSafe/lodestar/blob/master/packages/db/src/schema.ts#L8-L70

**Comment by dapplion** [comment]
Sounds good, we can add a test in the lodestar and validator repos to ensure the Buckets don't overlap
