### ISSUE TITLE
Run benchmark in self hosted runner

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2825]
**What is your question?**

Our benchmarks are not stable enough in Github runners. Set up a self hosted runner and test stability there https://docs.github.com/en/actions/hosting-your-own-runners

First it would be worth it to just run the benchmark 10 times in one of our machines to check if they are actually stable there

**Comment by twoeths** [comment]
This test failed randomly when I run it

```
  1 failing

  1) api / impl / validator
       "before all" hook for "getPubkeys - index2pubkey - req 1 vs - 200000 vc":
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/root/lodestar/packages/lodestar/test/perf/api/impl/validator/attester.test.ts)
      at processImmediate (internal/timers.js:461:21)
```

**Comment by dapplion** [comment]
I've running the benchmarks in our servers and they are very unstable too on some benchmarks :thumbsdown: Soo setting up a self-hosted runner may not fix the problem.

This is the code running the benchmark
```ts
    const startNs = process.hrtime.bigint();
    await opts.fn(input);
    const endNs = process.hrtime.bigint();
```

What can cause so much variability? Frequent GC runs? Tho some benchmarks that are x4 times slower run for 100_000 times

**Comment by dapplion** [comment]
We are doing fine with GA runners, and don't have evidence that self-hosted would fix the issue. JS benchmarks are inherently unstable do to GC and other factors
