### ISSUE TITLE
Investigate and implement tooling to ensure README files are accurate across all packages

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#2828]
Do this for all lodestar-relevant codebases (i.e. all inside monorepo as well as externals that are related such as ssz, bls-*, etc).

> Would be great to have tooling to ensure the readme is up to date. I think rust has something like that to ensure code snippets compile

from:
https://discord.com/channels/593655374469660673/605818244036821012/862719541838348318

**Comment by dapplion** [comment]
This tool looks promising https://github.com/bbc/typescript-docs-verifier
