### ISSUE TITLE
Broken metrics

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2839]
**Describe the bug**

ForkChoice, ReqResp and Block Production metrics are broken in a recent deployment of our docker-compose with latest master. All other metric rows work fine.

@g11tech 

**Expected behavior**

There should be data associated with those metrics

**Steps to Reproduce**

Checkout latest master and docker-compose up

**Screenshots**

![Screenshot from 2021-07-14 13-36-30](https://user-images.githubusercontent.com/35266934/125615848-f4e6e083-7181-4c8c-b9a1-606cd4b2fc2d.png)

![Screenshot from 2021-07-14 13-36-41](https://user-images.githubusercontent.com/35266934/125615845-ab2661ef-a923-4fd0-8f02-d4511f8209e3.png)

![Screenshot from 2021-07-14 13-36-53](https://user-images.githubusercontent.com/35266934/125615840-a3a66fe8-dfb6-4c6f-a0d0-397d9a0eaa86.png)

**Comment by dapplion** [comment]
On an older machine there are fork choice metrics, will investigate more

![Screenshot from 2021-07-14 14-30-20](https://user-images.githubusercontent.com/35266934/125622285-fc024317-5277-4c9f-92cb-1ce7dcc85d79.png)

**Comment by g11tech** [comment]
@dapplion  on my local build (rebased with master couple of hours ago) its showing up 🤔 

![image](https://user-images.githubusercontent.com/76567250/125653835-c869fa8a-a28f-4cb0-aaa1-e13ecce76248.png)

![image](https://user-images.githubusercontent.com/76567250/125654003-99e845ec-7f2e-4f9f-b1af-51126402218a.png)

**Comment by dapplion** [comment]
During altair-devnet-1 all nodes had metrics on these charts. So likely no metrics were output for those charts in the first node I reported from
