### ISSUE TITLE
Investigate prev epoch HEAD miss ratio metric

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2847]
**Describe the bug**

At some points, 30% of our attestations are missed due to incorrect head in previous epoch
http://161.97.179.213:3000/d/V0c7Qyink/lodestar2?orgId=1&refresh=30s

<img width="824" alt="Screen Shot 2021-07-15 at 20 44 32" src="https://user-images.githubusercontent.com/10568965/125799379-828a0ec4-c3bf-44b9-8917-98584f559ad0.png">

**Expected behavior**

Should be as small as possible

**Steps to Reproduce**

Run altair-devnet-1

**Comment by dapplion** [comment]
Notice that devnet forked to altair at ~20:10 (in the timezone of the chart above).

All 5 nodes we are running showed the same uptick in HEAD miss ratio on those epochs. Note that there was an issue with Prysm that destabilize the network a bit.

**Comment by twoeths** [comment]
there is an issue that we receive gossip blocks so late although validator published it on time, see https://github.com/ChainSafe/lodestar/issues/2908#issuecomment-893930201

this seems to be the root cause

**Comment by twoeths** [comment]
duplicated to #3084
