### ISSUE TITLE
Wrong preset choices for cli option in dev command

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#2854]
**Describe the bug**

When I append `-h` for CLI option help, I noticed the choices in the `preset` option for the dev command are currently: `[choices: "mainnet", "minimal", "mainnet", "minimal"]`

**Expected behavior**

The choices should be be `[choices: "mainnet", "minimal"]` just like the `beacon` command.

**Comment by q9f** [comment]
Closely related to #2594 - where I suggest that we remove `preset` altogether and instead let the network configurations handle this. I cannot think of any use case where you would want to run a certain testnet with a different preset.

**Comment by dapplion** [comment]
> Closely related to #2594 - where I suggest that we remove `preset` altogether and instead let the network configurations handle this. I cannot think of any use case where you would want to run a certain testnet with a different preset.

+1 to remove the preset option. I've only used it for local devnets, and in that scenario I can craft a config.

**Comment by q9f** [comment]
You can still use `LODESTAR_PRESET` after #2995
