### ISSUE TITLE
Enable rest api by default

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#2862]
Somehow the `--api.rest.enabled` CLI flag is now defaulting to `false` when it needs to be defaulting to `true.

**Comment by dapplion** [comment]
Why should it default to true?

**Comment by dapplion** [comment]
@q9f Do you think the rest api should be enabled or disabled by default in the beacon node?

**Comment by q9f** [comment]
It's really a matter of taste. Bitcoin nodes have it off by default (afair) whereas most Ethereum nodes have it enabled by default.

I would lean to enable it but it really doesn't matter. Doesn't the validator need it? Or is it bundled into one?

**Comment by dapplion** [comment]
> It's really a matter of taste. Bitcoin nodes have it off by default (afair) whereas most Ethereum nodes have it enabled by default.
> 
> I would lean to enable it but it really doesn't matter. Doesn't the validator need it? Or is it bundled into one?

It is mandatory for the validator
