### ISSUE TITLE
Improve altair state transition

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2872]
**Is your feature request related to a problem? Please describe.**

In altair, processing attestation and sync aggregate takes so much time due to the update to BeaconState tree frequently
<img width="1169" alt="Screen Shot 2021-07-22 at 17 11 42" src="https://user-images.githubusercontent.com/10568965/126623691-96d793c7-2cb6-497b-8929-d256703bc3f2.png">

+ For attestation, we update the participation status of every attesters to the tree
+ For sync aggregation, we update the balance of all sync committee participants

Sometimes the time to process a block is even bigger than an epoch, I imagine it'd be not a small issue when we upgrade prater to altair.
[0721_sync_altair_devnet_1.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/6861548/0721_sync_altair_devnet_1.cpuprofile.zip)

**Describe the solution you'd like**

+ No solution right now, need to write performance test for processing a block first.

**Comment by dapplion** [comment]
```
altair processBlock - 250000 vs - 7PWei normalcase | 92.840 ms/op
altair processBlock - 250000 vs - 7PWei worstcase | 252.62 ms/op 
```

We are good now :+1:
