### ISSUE TITLE
Initialize a beacon node (optional) command produces Unknown argument: init error

### ISSUE THREAD

**Issue by KBryan** [ChainSafe/lodestar#2874]
**Describe the bug**

Following the installation instructions on `https://chainsafe.github.io/lodestar/usage/testnet/` Initialize a beacon node (optional) and using the following command `./lodestar beacon init --network $NETWORK_NAME` produces Unknown argument: init error.

**Expected behaviour**
The command should run without error and I'm assuming give you an option for mainnet or testnet. Seems to default to mainnet without the option to select testnet option

**Steps to Reproduce**

<!--Steps to reproduce the behaviour:
1. Go to 'https://chainsafe.github.io/lodestar/usage/testnet/'
2. Follow initialize a beacon mode optional mode.
3. See an error in the console

**Screenshots**

![Screen Shot 2021-07-22 at 9 31 11 AM](https://user-images.githubusercontent.com/681817/126660141-96ac0386-5781-4c86-aabf-20fd598becf9.png)

**Comment by dapplion** [comment]
Would you mind reviewing the docs with fresh eyes? It's not necessary to run init at all now

**Comment by KBryan** [comment]
Everything is working and `init` flag is no longer needed. I did see something referring to bigint: Failed to load bindings. It doesn't seem to stop the process. Here's a screenshot.

![lodestar_installation_test](https://user-images.githubusercontent.com/681817/134223847-d05098ed-85ee-4395-9faa-9b71252fb0ce.png)

**Comment by dapplion** [comment]
@KBryan Could you try running npm run rebuild? Without native bindings the performance of your node may suffer

**Comment by KBryan** [comment]
@dapplion sorry for the late response. Yes, all good works like a charm. I just wanted to mention it.
