### ISSUE TITLE
Group attestations by target checkpoint

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2877]
**What is your question?**

With https://github.com/ChainSafe/lodestar/pull/2876 I've been able to check that most of the attestations and aggregates in the queue point to the same target (in good network conditions).

Our validation function is split into three sections: pre state, post state, and signature verification. If we could group attestations by target we could run the validation "once" for a group of attestations which may be good for performance and reduce load on the event loop with less promises. This is just an idea and may not improve performance, but it may be worth it if https://github.com/ChainSafe/lodestar/pull/2801 fails to deliver the expected performance gains.

It is possible to efficiently extract the target checkpoint from an uncompressed attestation or aggregates bytes, like how we do with blocks to read their slot.

```ts
const targetCheckpointOffset =
  4 + // SignedAggregateAndProof.message offset
  96 + // SignedAggregateAndProof.signature
  8 + // AggregateAndProof.aggregator_index
  4 + // AggregateAndProof.aggregate offset
  96 + // AggregateAndProof.selection_proof
  4 + // Attestation.aggregation_bits offset
  8 + // AttestationData.slot
  8 + // AttestationData.index
  32 + // AttestationData.beacon_block_root
  8 + // AttestationData.source.epoch
  32; // AttestationData.source.root

// 0x64000000
//   984572953cce4590f22b96ca08a80f0c15f46f5f8d26323f37e567e29d6869e8adcb8f0da223b5cd30cef0cf1a86cb9b02eb5b53705094ccce4d9100f292286d7322918e4bc80430251e83b6324aaddb2a3e75338d26053bbff9e0185ea07d5a
//   2ae0010000000000
//   6c000000
//   94b839db17d09c3474a74497f6bf5315cb4b7806ae1b1c87b817dc413efd60e6d870722e6d6b24dcccb3f2b5165f82070c96f1ed5b927da447fdb5c6577deabf7cc818eaf714087cdc067999ff1f1546b61b1de0bbc03a9fe177761c11fc7cba
//   e4000000
//   829e190000000000
//   1600000000000000
//   2eb9af4323a8b996e5b2c990e712d94f2e5c11a454e5c064c908305f77ce67ca
//   f3cc000000000000
//   bc05b20fd366e57d42a899178727b50fc3f17130ea55042a89308da562ab9239
//   f4cc000000000000
//   aa4ec5eb76d15c1e9531b03648afb5f34d0679c8c65b3b0f4c7849a79acd193f
//   ab8ac7f1c90074bd2706cd89bcead9088c15fc7f64f195c14b3d5321c1d2384199c5ccdb9ab2b680306d2649b40df4aa14389c00094a54181299d0472cb3e86dc76f2c7ac7a220e0ffc54725deea489051d2e6bb1a1e34c0cbbcf3ad6bb4b6ff
//   ffffffffffffffffffffffffffffffff03
```

**Comment by wemeetagain** [comment]
resolved by https://github.com/ChainSafe/lodestar/pull/5896
