### ISSUE TITLE
lodestar --version should indicate release track

### ISSUE THREAD

**Issue by q9f** [ChainSafe/lodestar#2950]
**What is your question?**

Given a binary build from latester:

```
~/lodestar master user@errai
❯ ./packages/cli/bin/lodestar --version
0.28.0

~/lodestar master user@errai
❯ git log -n1 | head -3                
commit 0add9d11d619e8f096d5dbf54ec40a6cf7b14f8f
Author: Lion - dapplion <35266934+dapplion@users.noreply.github.com>
Date:   Wed Aug 11 09:58:29 2021 +0200
```

Couple of issues:
- it does not indicate release track (stable/beta/nightly...)
- it does not indicate code version (git commit, from a release, "dirty"/unstable...)
- in this case, it provides a wrong version number (because master is already ahead of `0.28.0` right?)

Happy to take this one.

**Comment by dapplion** [comment]
I agree with the suggestions! We just let `yargs` cli library handle the version for us. But it's time to print more info. We already do than on the first log line when running the beacon or validator cmds. We could do the same for --version
