### ISSUE TITLE
Light Client Planning 

### ISSUE THREAD

**Issue by ColinSchwarz** [ChainSafe/lodestar#2986]
## Light Client Community Building 
Community and consensus building around a vision for eth2 light clients is our top priority
- Create a new PR on the eth2 spec repo
- Cayman will write proposal for our vision for LCs and submit for community review 
- Some in the community have suggested a separate node to serve light clients, something to think about further 
    - Step 1 ideate on this
    - Step 2 build out some code and see what sticks
    - Step 3 look at incentives 
- Open question: assuming Discv5 can be made light client ready, what records in ENR need to be added? 

## LC Implementation 
Improving the prototype is the second priority
- add ability to sync to the head of the chain rather than last finalized block 
- look into different networking possibilities such as libp2p for req/res
- look into peer discovery using web sockets as transport 

## LC Demo
- Add link to our LC Discord channel on the demo UI
-  Merge PR for DOS protection

**Comment by wemeetagain** [comment]
Linking #3077 #3078 #3079

**Comment by philknows** [comment]
Deprecating issue for #3469.
