### ISSUE TITLE
Releases not uploaded to Dockerhub

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2999]
**Describe the bug**

At least version 0.28.0 is not uploaded to Dockerhub. The publish to Dockerhub action failed. https://github.com/ChainSafe/lodestar/runs/3255490028

```
Step 5/12 : ENV VERSION=$VERSION
 ---> Running in ce678a409691
Removing intermediate container ce678a409691
 ---> 47fbf0c68360
Step 6/12 : RUN npm install @chainsafe/lodestar-cli@$VERSION
 ---> Running in eade1e96c7d9
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @chainsafe/lodestar-cli@0.28.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-05T18_50_04_526Z-debug.log
The command '/bin/sh -c npm install @chainsafe/lodestar-cli@$VERSION' returned a non-zero code: 1
```

I think the problem is a race condition with NPM. We have a prior action that uploads that version to NPM, then run the Dockerfile that installs from NPM. Since the timing is tight, it may happen that NPM doesn't acknowledge the existence of that version.

**Expected behavior**

All releases should be uploaded to Dockerhub

**Comment by q9f** [comment]
It stopped working 2 months ago apparently but the nightly builds still make it to Docker hub. I'll check the scripts.

**Comment by q9f** [comment]
It was potentially broken in ~~#2667~~ or #2672 or ~~#2705~~

**Comment by q9f** [comment]
Releases are delayed for 10-15 minutes https://github.com/npm/npm/issues/20056

https://npm.community/t/newly-published-packages-have-a-delay-before-they-are-consumable/952

Can't really tell why nightly is working though. (lucky us?)

**Comment by dapplion** [comment]
I think the easiest solution now is to:
1. Add a wait and pause step to ensure it's available before attempting the docker build
2. Restructure the skip checks such that re-running the workflow still attempts to build the image again even if the tag exists. Skipping only the publish to NPM step
