### ISSUE TITLE
Add Lodestar to Staking Launchpad

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#3008]
For when we're confident enough:

open an issue/pr at https://github.com/ethereum/staking-launchpad
we may need some intro like: https://launchpad.ethereum.org/en/prysm

**Comment by philknows** [comment]
https://github.com/ethereum/staking-launchpad/issues/430

**Comment by philknows** [comment]
Complete. Please use https://chainsafe.typeform.com/lodestar to sign up for the mailing list.

**Comment by philknows** [comment]
PR has been updated here: https://github.com/ethereum/staking-launchpad/pull/436#issuecomment-1385869077
Getting ready to close this after we release v1.4.0!

**Comment by nflaig** [comment]
Closing as Lodestar has been added to the staking launchpad a while ago (https://launchpad.ethereum.org/en/lodestar, https://launchpad.ethereum.org/en/select-client)
