### ISSUE TITLE
Perf tests OOM

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3011]
**Describe the bug**

Perf test OOM quite frequently. I haven't been able to take a heap snapshot so I'm still on the black.

Latest time in CI it happened here, right after the `badcase_full_deposits` case

https://github.com/ChainSafe/lodestar/blob/99369b137a3575b2edd6aeb31c35f2bc134a461a/packages/beacon-state-transition/test/perf/phase0/epoch/processRegistryUpdates.test.ts#L41

```
  phase0 processRegistryUpdates
    ✓ phase0 processRegistryUpdates - 250000 normalcase                   12536.04 ops/s    79.77000 us/op   x0.283      76605 runs   14.0 s
    ✓ phase0 processRegistryUpdates - 250000 badcase_full_deposits        187.7203 ops/s    5.327073 ms/op   x0.462         59 runs   6.85 s

<--- Last few GCs --->

[2269:0x4b76cd0]   824055 ms: Mark-sweep (reduce) 4093.3 (4101.6) -> 4092.5 (4102.9) MB, 4576.8 / 0.0 ms  (average mu = 0.070, current mu = 0.001) allocation failure scavenge might not succeed
[2269:0x4b76cd0]   828392 ms: Mark-sweep (reduce) 4093.5 (4101.9) -> 4092.8 (4102.9) MB, 3798.6 / 0.0 ms  (average mu = 0.098, current mu = 0.124) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

**Expected behavior**

Not OOM

**Comment by q9f** [comment]
All my PRs fail with this error now....

**Comment by dapplion** [comment]
> All my PRs fail with this error now....

Do you have any experience debugging memory leaks in NodeJS? If you want to try to get a heap snapshot I have the feeling it might be easy to pin point the cause.

**Comment by dapplion** [comment]
Fixed with https://github.com/ChainSafe/lodestar/pull/3026
