### ISSUE TITLE
 Fix failed phase0 minimal spec tests

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3020]
:warning: Some phase0 minimal tests are skipped, should be fixed in a new PR. The error is there because we were **not** running those test

https://github.com/ChainSafe/lodestar/blob/6a0d022a9eb432e23e4ca2c141c6be3e8eac9379/packages/spec-test-runner/test/spec/phase0/epoch_processing.test.ts#L58-L72

https://github.com/ChainSafe/lodestar/blob/6a0d022a9eb432e23e4ca2c141c6be3e8eac9379/packages/spec-test-runner/test/spec/phase0/fork_choice.test.ts#L113-L120

_Originally posted by @dapplion in https://github.com/ChainSafe/lodestar/issues/3017#issuecomment-905546326_

**Comment by g11tech** [comment]
this issue seems to have already been  been resolved.
