### ISSUE TITLE
Don't store full pubkey in pubkey2index map

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3039]
**Describe the feature**

We don't need to store the full pubkey since the collision probability is low enough with just a few bytes. Note that ethereum addresses use 20 bytes only.

Check a safe minimum byte count and create a map that can extend the size of the key if it detects a collision. Keep an array of key bytes, starting at [10] for example, and if there's a collision extend to [11] and write new keys with 11 bytes. Then to check slice to 11 check, slice to 10 check.

**Comment by dapplion** [comment]
pubkey2index map is retaining 320MB in Prater (220_000 validators) which averages 1454 bytes per pubkey :exploding_head: 

![Screenshot from 2021-09-07 12-15-05](https://user-images.githubusercontent.com/35266934/132328103-4151715e-72f0-4248-ac57-cc1563307cf2.png)

**Comment by dapplion** [comment]
Proposal:

- Use only the first N bytes of the pubkey (i.e. 4) and encoded as `base64url` to have a very short key. Use `base64url` since it has no padding and saves 2 characters
- The Map value will be an array of indices that start with that pubkey prefix.

Since the goal of this Map is to speed up lookup by pubkeys narrowing down from 250_000 to ~10 instead of 1 is good enough.

Analysis of probabilities should pick an appropriate byte length. Also must check that BLS pubkeys have a sufficient random distribution of the first N bytes.

**Comment by dapplion** [comment]
After doing some research today:

- The bulk of the memory usage is cause by this awful concatenated strings. With https://github.com/ChainSafe/lodestar/pull/3561 the memory usage of the map is reduced by 10x from 350MB to 35MB.

- With non-concatenated strings, using less bytes has marginal benefits being able to reduce 2.5x extra. However that's an absolute reduction of ~19MB for the entire application so not a lot. Also, using shorter keys adds non-trivial complexity to ensure keys are not known. To do that indexed sync committees MUST not rely of the pubkey2index map but for the first indexation.

- Using hex, base64 or base64url has not effect of the total memory usage of the Map

WIP branch: https://github.com/ChainSafe/lodestar/tree/dapplion/pubkey2index-short-key

**Comment by dapplion** [comment]
The real cause of the memory inefficiency is the concatenated strings as shown here https://github.com/ChainSafe/lodestar/issues/3446

The current size of the Pubkey2Index map is 45.5MB for 275496 validators. We could consider reducing the pubkey length but now it's not that prioritary

![Screenshot from 2022-02-04 17-33-07](https://user-images.githubusercontent.com/35266934/152526839-035d9829-f71f-43cb-91c5-425ec6b6cf99.png)

**Comment by philknows** [comment]
Is this a worthy optimisation for memory? Need to investigate further.

**Comment by wemeetagain** [comment]
- closing in favor of https://github.com/ChainSafe/lodestar/pull/7091
