### ISSUE TITLE
Beacon node notifier says (empty) but head is progressing

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3061]
**Describe the bug**

In Prater fork, with many missing blocks this print happened

```
beacon_node_1  | Sep-02 12:37:18.011 []                 info: Synced - block: 1173186 0x99e0…6711 - head: 1173186 0x99e0…6711 - finalized: 1173120 0x24ad…eb79 (36660) - peers: 2
beacon_node_1  | Sep-02 12:37:30.000 []                 info: Synced - block: 1173187 0x9cd8…e232 - head: 1173187 0x9cd8…e232 - finalized: 1173120 0x24ad…eb79 (36660) - peers: 2
beacon_node_1  | Sep-02 12:37:42.001 []                 info: Synced - block: 1173188   … (empty) - head: 1173187 0x9cd8…e232 - finalized: 1173120 0x24ad…eb79 (36660) - peers: 3
beacon_node_1  | Sep-02 12:37:54.012 []                 info: Synced - block: 1173189   … (empty) - head: 1173188 0xf3a3…c8a3 - finalized: 1173120 0x24ad…eb79 (36660) - peers: 3
beacon_node_1  | Sep-02 12:38:06.001 []                 info: Synced - block: 1173190   … (empty) - head: 1173189 0x8790…cef6 - finalized: 1173120 0x24ad…eb79 (36660) - peers: 4
beacon_node_1  | Sep-02 12:38:18.001 []                 info: Synced - block: 1173191   … (empty) - head: 1173189 0x8790…cef6 - finalized: 1173120 0x24ad…eb79 (36660) - peers: 4
beacon_node_1  | Sep-02 12:38:30.000 []                 info: Synced - block: 1173192 0xb2a5…1163 - head: 1173192 0xb2a5…1163 - finalized: 1173120 0x24ad…eb79 (36660) - peers: 4
beacon_node_1  | Sep-02 12:38:42.001 []                 info: Synced - block: 1173193 0xdf9f…da7f - head: 1173193 0xdf9f…da7f - finalized: 1173120 0x24ad…eb79 (36660) - peers: 4
beacon_node_1  | Sep-02 12:38:54.002 []                 info: Synced - block: 1173194   … (empty) - head: 1173193 0xdf9f…da7f - finalized: 1173120 0x24ad…eb79 (36660) - peers: 4
```

**Expected behavior**

Review (empty) tag logic

CC: @q9f

**Comment by q9f** [comment]
That's because it assumes that blocks are arriving at clock slots. Reasons can be manifold: local clock out of sync, block processing internally takes longer than expected, block propagation in the network takes longer than expected.

I know we just print out the `synced` logger message right on the clock slot (right on the second) where as it might be better to couple it with some internal events that eventually are more close to actual block processing (and only print "empty" if there is nothing happening for `1/2 * SECONDS_PER_SLOT`)... Let me know if you have any ideas or preferences and I can try to revise this.

**Comment by q9f** [comment]
> it might be better to couple it with some internal events that eventually are more close to actual block processing (and only print "empty" if there is nothing happening for `1/2 * SECONDS_PER_SLOT`)... Let me know if you have any ideas or preferences and I can try to revise this.

Just checked, we are already waiting for half a slot:

```
      // Log halfway through each slot
      await sleep(timeToNextHalfSlot(config, chain), signal);
```

So, basically this means this is not a logger issue but rather something else, why would it take more than 6 seconds to receive and process a block?

Unless it's a clock issue?

**Comment by dapplion** [comment]
That was taken in very bad network conditions so blocks were arriving at random times + had to trigger a backwards search of previous blocks before being able to insert them. Definitely not the norm, but wondering if (empty) communicates what's actually going on

**Comment by twoeths** [comment]
right now we have a weird behavior that gossip block does not come on time, I think this is the root cause https://github.com/ChainSafe/lodestar/issues/3084#issuecomment-914876394

**Comment by q9f** [comment]
> Definitely not the norm, but wondering if (empty) communicates what's actually going on

No, it's an assumption that there should be a block available in less than half a slot time. I lack a deeper understanding of the internal block processing routes to propose an alternative here. But maybe it's just fine for the notifier for now.

**Comment by dapplion** [comment]
No recent complains on the UX of this log
