### ISSUE TITLE
Find attestation slashings

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#307]
Find slashable attestations and add to OpPool. Condition: https://github.com/ethereum/eth2.0-specs/blob/v0.7.1/specs/core/0_beacon-chain.md#is_slashable_attestation_data

Note1: Should not be done during initial sync.
Note2: Could be bottleneck, we need some optimized solution.

**Comment by mpetrunic** [comment]
https://github.com/ethereum/eth2.0-pm/issues/63

**Comment by dapplion** [comment]
Since we are not pursuing a slasher can we close this?

**Comment by dapplion** [comment]
Closing since this does not align with our roadmap and priorities
