### ISSUE TITLE
Reorg-capable light client

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#3078]
Ideally a light client is able to sync to the head of the beacon chain, rather than sync only to the finalized block.

Investigate current light client reorg mechanisms.
Help build consensus, write specifications, implement pocs, etc to push this feature towards standardization and production.

**Comment by philknows** [comment]
Does the latest light client demo solve this issue? Otherwise, the other tasks seem like they can be broken down into some of the other ones we may already have in the Light Client Tracker (#3469). cc: @wemeetagain

**Comment by dapplion** [comment]
Fixed by https://github.com/ChainSafe/lodestar/pull/3461
