### ISSUE TITLE
Light client API standardization

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#3079]
The light client syncing API should be standardized and available as a REST API.

Build consensus, write specifications, implement pocs, etc to bring the syncing API to standardization and production.

**Comment by philknows** [comment]
Create buy-in for other clients to implement. Link to the PR.

**Comment by philknows** [comment]
Reference: https://github.com/ethereum/beacon-APIs/pull/181

**Comment by philknows** [comment]
It has been identified in the March 29 call and recently on [Twitter ](https://twitter.com/ClaraVanStaden/status/1509416105558822914?s=20&t=Iwyy04Db3EilFdm840DAGA)that we need should tweak the API to allow for syncing to finalized or to head. cc: @wemeetagain @dapplion

**Comment by philknows** [comment]
Can we close this for #3952 @wemeetagain ?
