### ISSUE TITLE
altair processAttestations performance issue

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3080]
**Describe the bug**

Looking at the metrics for our altair nodes processing a block takes way longer (300ms) than what the performance tests say (100ms).

Taking a profile shows that all the time is spent on processing attestations

![Screenshot from 2021-09-03 18-40-18](https://user-images.githubusercontent.com/35266934/132040200-2ae11cf5-dbdb-428d-b8a2-37eec8d7d463.png)

**Expected behavior**

Should not take so long

------

Note: this CPU profile was taken in an overloaded contabo node.

Running the altair block performance benchmarks in my laptop do

```
  altair processBlock
    ✓ altair processBlock - 250000 vs - 7PWei normalcase                  10.01820 ops/s    99.81831 ms/op        -         33 runs   17.2 s
    ✓ altair processBlock - 250000 vs - 7PWei worstcase                   4.261845 ops/s    234.6401 ms/op        -         26 runs   7.50 s
```

While running the same in that contabo's host

```
  altair processBlock
    ✓ altair processBlock - 250000 vs - 7PWei normalcase                  7.083636 ops/s    141.1704 ms/op   x0.601         14 runs   20.8 s
    ✓ altair processBlock - 250000 vs - 7PWei worstcase                   2.356299 ops/s    424.3943 ms/op   x0.629         24 runs   12.1 s
```

And Github CI does

```
altair processBlock - 250000 vs - 7PWei normalcase | 103.91 ms/op | 97.787 ms/op | 1.06
altair processBlock - 250000 vs - 7PWei worstcase  | 261.36 ms/op | 265.06 ms/op | 0.99
```

**Comment by dapplion** [comment]
The performance issue comes from having to traverse the tree many times to persist each single new status. If I comment this line out

https://github.com/ChainSafe/lodestar/blob/43972fb1b0d0e0d44c4244541b7a1c0e958d68e1/packages/beacon-state-transition/src/altair/block/processAttestation.ts#L81

the cost of processing the entire block goes from 100ms -> 23.1ms.

We must apply all the changes in batch at the end of processAttestations(). Maybe with https://github.com/ChainSafe/persistent-merkle-tree/pull/53 ? Also do some pre-aggregate the statuses that will end-up in the same chunk or some bit manipulation magic.

**Comment by philknows** [comment]
Note to tag this issue with SSZ refactor PR when it's ready.
