### ISSUE TITLE
processEth1Data performance issue

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3082]
**Describe the bug**

processEth1Data takes more time than it should (5-6ms, 25% of phase0 block processing times). Looks like iteration takes signficant time + it has to convert the root of each entry from hashObject to Uint8Array and then compare. A bit stupid when it could just use the hashObject numbers

![Screenshot from 2021-09-03 19-29-31](https://user-images.githubusercontent.com/35266934/132045070-59834a4a-9e37-4a4f-a88e-8bff1e5464dd.png)

![Screenshot from 2021-09-03 19-29-52](https://user-images.githubusercontent.com/35266934/132045080-59c5fc4d-36d8-4c97-9b87-f42dd88766f7.png)

----

> From duplicate issue https://github.com/ChainSafe/lodestar/issues/2453

In Prater our node spends 1400 ms processing Eth1Data. This happens on every block when there's no majority vote.

![Screenshot from 2021-05-01 15-20-47](https://user-images.githubusercontent.com/35266934/116783770-f194b780-aa90-11eb-9e3b-711932af3bdc.png)

Same cost every block

![Screenshot from 2021-05-01 15-22-05](https://user-images.githubusercontent.com/35266934/116783785-01140080-aa91-11eb-88fb-87ec68275390.png)

detail of the stack

![Screenshot from 2021-05-01 15-23-11](https://user-images.githubusercontent.com/35266934/116783819-34568f80-aa91-11eb-9d2b-6bf259d73930.png)

- [ ] Add a dedicated performance test
- [ ] Optimize

**Comment by dapplion** [comment]
@wemeetagain noted that the performance test should use a TreeBacked block which makes equality cheaper in our current SSZ implementation. However this function may take a struct or a TreeBacked block. In both cases the code should be fast.

**Comment by dapplion** [comment]
See https://github.com/ChainSafe/lodestar/issues/2453 for more detailed CPU profiles

**Comment by philknows** [comment]
Note to tag this issue with SSZ refactor PR when it's ready.

**Comment by dapplion** [comment]
- Fixed with https://github.com/ChainSafe/lodestar/pull/3760
