### ISSUE TITLE
Incorrect attestations submitted by lodestar validator in prater

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3084]
**Describe the bug**

Validator consistently submit incorrect source/target checkpoints and head block in prater after altair launched

<img width="1566" alt="Screen Shot 2021-09-06 at 08 15 46" src="https://user-images.githubusercontent.com/10568965/132147628-16ea32a8-5f41-4209-9bb0-5a2729b0fee9.png">

**Expected behavior**

Validator should submit correct attestations most of the time

**Comment by twoeths** [comment]
this is due to the performance of gossip block, we tend to receive gossip block from previous epoch

```
Sep-08 03:06:48.298 [CHAIN]           debug: Block pools:  pendingBlocks=68, currentSlot=1213534
Sep-08 03:06:51.349 [NETWORK]       verbose: Received gossip block slot=1213534, root=0x69ee…50a6
Sep-08 03:06:52.091 [NETWORK]       verbose: Received gossip block slot=1213502, root=0xf2b8…74ad
Sep-08 03:07:01.220 [CHAIN]           debug: Block pools:  pendingBlocks=68, currentSlot=1213535
Sep-08 03:07:03.186 [NETWORK]       verbose: Received gossip block slot=1213503, root=0x6f01…e57e
Sep-08 03:07:03.237 [NETWORK]       verbose: Received gossip block slot=1213535, root=0xdc10…51a8
Sep-08 03:07:12.480 [CHAIN]           debug: Block pools:  pendingBlocks=68, currentSlot=1213536
Sep-08 03:07:15.868 [NETWORK]       verbose: Received gossip block slot=1213504, root=0x80a8…6d7e
Sep-08 03:07:15.954 [NETWORK]       verbose: Received gossip block slot=1213536, root=0xcd73…240e
...
```

+ at slot 1213434, we do receive gossip block 1213434
+ at slot 1213435, we receive `old/wrong` gossip block 1213403
+ at slot 1213436, we do receive gossip block 1213436
+ at slot 1213437, we receive `old/wrong` gossip block 1213417
+ at slot 1213438, we receive `old/wrong` gossip block 1213406
+ at slot 1213539, we do receive both gossip block 1213539 and `old` gossip block 1213507

also pendingBlocks size of 68 means that we have some missing parent blocks

**Comment by twoeths** [comment]
with #3186 we can receive gossip blocks more regularly but some blocks come quite late (>4s) after the slot starts
```
Sep-17 06:32:12.008 [CHAIN]         verbose: Clock slot slot=1279361
Sep-17 06:32:19.861 [NETWORK]       verbose: Received gossip block slot=1279361, root=0xb80b…1207, curentSlot=1279361
...
Sep-17 06:33:24.001 [CHAIN]         verbose: Clock slot slot=1279367
Sep-17 06:33:29.952 [NETWORK]       verbose: Received gossip block slot=1279367, root=0x55af…4c5d, curentSlot=1279367
...
Sep-17 06:34:48.002 [CHAIN]         verbose: Clock slot slot=1279374
Sep-17 06:34:52.096 [NETWORK]       verbose: Received gossip block slot=1279374, root=0x3282…7f16, curentSlot=1279374
```

**Comment by dapplion** [comment]
> with #3186 we can receive gossip blocks more regularly but some blocks come quite late (>4s) after the slot starts
> 
> ```
> Sep-17 06:32:12.008 [CHAIN]         verbose: Clock slot slot=1279361
> Sep-17 06:32:19.861 [NETWORK]       verbose: Received gossip block slot=1279361, root=0xb80b…1207, curentSlot=1279361
> ...
> Sep-17 06:33:24.001 [CHAIN]         verbose: Clock slot slot=1279367
> Sep-17 06:33:29.952 [NETWORK]       verbose: Received gossip block slot=1279367, root=0x55af…4c5d, curentSlot=1279367
> ...
> Sep-17 06:34:48.002 [CHAIN]         verbose: Clock slot slot=1279374
> Sep-17 06:34:52.096 [NETWORK]       verbose: Received gossip block slot=1279374, root=0x3282…7f16, curentSlot=1279374
> ```

With metrics we can easily track the time elapsed between block slot time -> block received in gossip, then block slot time -> block processed

**Comment by twoeths** [comment]
> metrics we can easily track the time elapsed between block slot time -> block received in gossip, then block slot time -> block process

@dapplion  I'll implement this

**Comment by twoeths** [comment]
with #3209, gossip blocks are processed on time (<4s)

![Screen Shot 2021-09-21 at 13 32 48](https://user-images.githubusercontent.com/10568965/134122800-ae30f997-d13f-4703-9a01-ed51dd61856f.png)

but our validators still miss some block heads

![Screen Shot 2021-09-21 at 13 34 31](https://user-images.githubusercontent.com/10568965/134122894-c78ea9a2-42dc-4d29-abac-62b64bacfd08.png)

**Comment by twoeths** [comment]
There are a lot of changes since then, when the node does not have a memory issue, validators perform quite well for example https://prater.beaconcha.in/validator/200978

Closing the issue.
