### ISSUE TITLE
v0.29.3 docker syncing gets stuck at head 385215

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#3089]
Running docker image v0.29.3 and starting beacon chain sync from genesis. Syncing gets stuck at head: 385215. Last finalized is stuck at head: 385120.

Lodestar should sync right to current head.

**Steps to Reproduce**

**Screenshots**

![Screenshot from 2021-09-06 14-16-34](https://user-images.githubusercontent.com/58080811/132255952-6c5c7151-c324-44e3-bc7b-611b74c30ce4.png)

Logs: https://drive.google.com/file/d/1nd5VY1FHdggp6c8gOsm4tvCOCTgSS5UE/view?usp=sharing

**Desktop (please complete the following information):**

- OS: Ubuntu Server 20.04  
- Version: 0.29.3 
- Branch: Master
- Commit hash: 846f802

**Comment by twoeths** [comment]
Thanks @philknows for the sync, I'm looking into the issue

**Comment by philknows** [comment]
I should also mention if I haven't already that I was trying to sync with prater.

**Comment by twoeths** [comment]
I cannot reproduce the issue in my local environment with my latest version `392b3d26`

```
node --inspect lib/index.js beacon --network prater --root-dir ~/.local/share/lodestar/prater-2s --weakSubjectivitySyncLatest --weakSubjectivityCheckpoint 0xcfa9f3adacab45c3a455e079752a38fedf4ebbdac17c2db107ccd46a055d4ed6:12037

Sep-08 08:56:53.634 []                 info: Lodestar version=v0.29.3/master/+9/392b3d26 (git), network=prater

Sep-08 08:56:53.657 []                 info: Fetching weak subjectivity state from https://eth2-beacon-prater.infura.io/eth/v1/debug/beacon/states/385184
Sep-08 08:57:29.849 []                 info: Initializing beacon state from anchor state slot=385184, epoch=12037, stateRoot=0x09c20e6f28f88ac28874aefb628bf3581bb953e3a892bf05798897ac44e67325

Sep-08 09:00:18.004 []                 info: Syncing - 22 hours left - 10.2 slots/s - head: 386431 0x78fb…9ee1 - finalized: 386336 0x12dc…8779 (12073) - clockSlot: 1213201 - peers: 2
```

the sync started from checkpoint 12037 - slot 385184 and can get through slot 385215 normally. I'm syncing from contabo-0 from scratch too, let's see how it works there ...

**Comment by twoeths** [comment]
it doesn't happen with contabo-0 too
![Screen Shot 2021-09-08 at 14 41 26](https://user-images.githubusercontent.com/10568965/132467497-8f55589f-4f47-4974-879d-32e5a17760cf.png)


@philknows could you please pull the latest beacon node image and try again?

**Comment by philknows** [comment]
Interesting. Will try and recreate! Thanks.

**Comment by philknows** [comment]
@tuyennhv I definitely did not include `--weakSubjectivitySyncLatest --weakSubjectivityCheckpoint 0xcfa9f3adacab45c3a455e079752a38fedf4ebbdac17c2db107ccd46a055d4ed6:12037` when running it. This would be the proper way for any new users to start running the client?

**Comment by dapplion** [comment]
> @tuyennhv I definitely did not include `--weakSubjectivitySyncLatest --weakSubjectivityCheckpoint 0xcfa9f3adacab45c3a455e079752a38fedf4ebbdac17c2db107ccd46a055d4ed6:12037` when running it. This would be the proper way for any new users to start running the client?

Noo, tuyen used this flag to go directly to the block that you said causes your node to get stuck.

**Comment by philknows** [comment]
Closing this. Can't concretely reproduce. Thanks for the help!
