### ISSUE TITLE
Reference cached beacon states with WeakRefs

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3094]
Teku does it with good results. Since the cache memory size is technically unbounded this strategy is great for preventing OOMs.

- [ ] The head state should be kept separately with a strong reference.
- [ ] Test how JS chooses to garbage collect multiple WeakRef. By age? By least used?
- [ ] Test performance of WeakRef.unref() if it's called very often (attestation processing)
- [ ] Consider adding a shufflings cache to mitigate the risk of a key state getting dropped
- [ ] Don't regen for attestation verification if the head state already has the correct shuffling

Note: this is a huge en-devour with uncertain payoff. Teku has had issues in the past with this approach as all states disapears and the node death spirals

- Also see https://github.com/ChainSafe/lodestar/pull/3420

**Comment by philknows** [comment]
Refer to #6008 . May not be required anymore.

**Comment by wemeetagain** [comment]
@twoeths I don't think this is necessary anymore after n-historical-states?

**Comment by twoeths** [comment]
yes, block state cache is bounded by max size and checkpoint state cache is bounded by max epoch count
