### ISSUE TITLE
Add total synced blocks metrics

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3112]
Add block count metrics per sync type:

- [ ] Total count of block synced by unknown parent block sync
- [ ] Total count of block synced with head sync
- [ ] Total count of block synced with finalized sync

**Comment by wemeetagain** [comment]
We have `lodestar_import_block_by_source_total`, which counts each 'source':
api, gossip, req_resp_by_range, req_resp_by_root
