### ISSUE TITLE
Node stops getting gossip block due to error

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3132]
**Describe the bug**

This happens in my local environment with "tuyen/peer-score-params" branch. Node stays synced with good gossip block, after a while I got his error

```
996048 Sep-14 15:14:21.076 [API]             ^[[31merror^[[39m: uncaughtException: cb is not a function
996049 TypeError: cb is not a function
996050     at /Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@motrix/nat-api/index.js:324:16
996051     at /Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@motrix/nat-api/lib/upnp/index.js:24:23
996052     at Timeout._onTimeout (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@motrix/nat-api/lib/upnp/index.js:193:7)
996053     at listOnTimeout (node:internal/timers:557:17)
996054     at processTimers (node:internal/timers:500:7) message=cb is not a function
996055 TypeError: cb is not a function
996056     at /Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@motrix/nat-api/index.js:324:16
996057     at /Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@motrix/nat-api/lib/upnp/index.js:24:23
996058     at Timeout._onTimeout (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@motrix/nat-api/lib/upnp/index.js:193:7)
996059     at listOnTimeout (node:internal/timers:557:17)
996060     at processTimers (node:internal/timers:500:7)
```

I haven't received any gossip blocks since then.

I'll validate if we have this same issue in other environments and `master`.

**Expected behavior**

No error

**Comment by dapplion** [comment]
Stack trace points to this line https://github.com/alxhotel/nat-api/blob/e404453ebca7e386fbd20f8dd7d86b8c9611058e/index.js#L324

I didn't knew libp2p was messing with UPnP by default! Should this be enabled by default??

**Comment by q9f** [comment]
> `uncaughtException: cb is not a function`

ref #2996

**Comment by dapplion** [comment]
Probably both items are unrelated, gossip problems are now mostly fixed and opened and issue to track libp2p cb issue https://github.com/ChainSafe/lodestar/issues/3215
