### ISSUE TITLE
High GC rate and slow processing during altair blocks sync

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#3175]
Machine:
Intel Core i5-11400
32 GB DDR4 3200mhz RAM
2TB WD Black SN850 M.2 2280 PCIe Gen4 NVMe SSD

Specs:
- OS: Ubuntu 20.04.3 
- Version: 0.29.3
- Branch: master/+24
- Commit hash: 2c9ebf74

Tested on Prater: After starting Altair sync roughly 1900hrs, notice the changes in above screenshots for GC. Slower processing of post-Altair blocks. Sync completes around 0000hrs.

**Screenshots**

<img width="1677" alt="Screen Shot 2021-09-14 at 11 52 10" src="https://user-images.githubusercontent.com/58080811/133359981-4011e50e-0546-48c9-a689-fdcaf1a5ca63.png">
<img width="1676" alt="Screen Shot 2021-09-14 at 11 51 18" src="https://user-images.githubusercontent.com/58080811/133360015-ca76cd0c-3206-48d8-aaff-bbaea8332d55.png">

**Comment by dapplion** [comment]
- Fixed with https://github.com/ChainSafe/lodestar/pull/3760 :tada:
