### ISSUE TITLE
Don't use other module's functions and constants in long loops

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3180]
**Is your feature request related to a problem? Please describe.**

This is from https://github.com/ChainSafe/lodestar/pull/3178#issue-996944825

If we use functions and constants of other modules in a for loop, tsc would compile it from

```ts
for (let i = 0; i < statuses.length; i++) {
    const status = statuses[i];
    if (hasMarkers(status.flags, FLAG_ELIGIBLE_ATTESTER)) {
```
to
```js
for (let i = 0; i < statuses.length; i++) {
        const status = statuses[i];
        if ((0, util_1.hasMarkers)(status.flags, util_1.FLAG_ELIGIBLE_ATTESTER)) {
            let inactivityScore = inactivityScores[i];
```
as we can see, it keeps accesing `util_1.*` in a for loop and it makes the code slow, we should instead import functions/constants outside of the for loop
```ts
// this avoids importing FLAG_ELIGIBLE_ATTESTER inside the for loop, check the compiled code
    const { FLAG_ELIGIBLE_ATTESTER, FLAG_PREV_TARGET_ATTESTER_OR_UNSLASHED, hasMarkers } = constants;
    for (let i = 0; i < statuses.length; i++) {
        const status = statuses[i];
        if (hasMarkers(status.flags, FLAG_ELIGIBLE_ATTESTER)) {
```

in the case of `processInactivityUpdates`, this gives a 10% improvement

**Describe the solution you'd like**

We should apply the same fix to other places in `beacon-state-transition` and check the performance gain there

**Comment by dapplion** [comment]
Beacon state transition has been reviewed in depth, fixing multiple issues including this one
