### ISSUE TITLE
Go full ESM modules

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3182]
**Describe the bug**

As a more sustainable alternative to https://github.com/ChainSafe/lodestar/issues/3180 we can consider switching Lodestar from using comonJS modules to ESM modules.

As an example of how to migrate and the implications for downstream consumers read this doc by find-up mantainer https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

- [x] Proof viable in Lodestar monorepo
- [ ] Research performance implications on monorepo and libraries
- [x] Implement everywhere, create epic

**Comment by philknows** [comment]
Epic created. Tracking migration under #3863.

**Comment by dapplion** [comment]
- Closing for https://github.com/ChainSafe/lodestar/issues/3863
