### ISSUE TITLE
Handle fork change

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#320]
In case of fork we should handle reverting blocks:
- emit fork change event along with added/removed blocks
- opPool should listen on those events and :
   - add attestations, deposits etc from removed blocks
   - remove attestations, deposits etc from added blocks

**Comment by GregTheGreek** [comment]
This is actually really interesting. How do we want to handle peers, drop the ones on the different fork or allow them to try and switch?

**Comment by mpetrunic** [comment]
unstale

**Comment by twoeths** [comment]
This is interesting, not sure why this is not part of the spec.

**Comment by mpetrunic** [comment]
Spec is just consensus, fork change is client implementation detail

**Comment by twoeths** [comment]
unstale

**Comment by wemeetagain** [comment]
unstale

**Comment by wemeetagain** [comment]
unstale

**Comment by dapplion** [comment]
Could this be spec-ed first so it can be implemented? Related to https://github.com/ChainSafe/lodestar/issues/715

**Comment by mpetrunic** [comment]
@wemeetagain I think we already have a lot of this if not all implemented?

@dapplion for endpoint, we have "forkChanged" or something emitted from chain, but tbh, I think we should implement standardized single event stream endpoint instead of having specific ones.

**Comment by dapplion** [comment]
@mpetrunic  This single event stream endpoint is spec somewhere? What exact events should emit, in what format, etc

**Comment by mpetrunic** [comment]
> @mpetrunic This single event stream endpoint is spec somewhere? You exact events should emit, in what format, etc

https://docs.google.com/spreadsheets/d/1kVIx6GvzVLwNYbcd-Fj8YUlPf4qGrWUlS35uaTnIAVg/edit#gid=215290094

I'm failing to find time to migrate that to eth2-apis repo :disappointed:

**Comment by wemeetagain** [comment]
I don't see fork on the list? only reorg

**Comment by mpetrunic** [comment]
Well scheduled forks are known in advance:
https://ethereum.github.io/eth2.0-APIs/#/Config/getForkSchedule

I think this issue was also refering to reorg originally
