### ISSUE TITLE
Improve REST API metrics

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3205]
**Describe the bug**

Only successful requests are registered in metrics. Metrics should register incoming requests, then successful / error requests, and timed out requests

**Comment by nflaig** [comment]
All metrics besides timeouts are already tracked and we decided that tracking timeouts does not make sense

Errors

https://github.com/ChainSafe/lodestar/blob/bf5d92b1327264638c49bbe3d9a5048ad4cfc634/packages/beacon-node/src/metrics/metrics/lodestar.ts#L221-L225

Requests total / response times

https://github.com/ChainSafe/lodestar/blob/bf5d92b1327264638c49bbe3d9a5048ad4cfc634/packages/beacon-node/src/metrics/metrics/lodestar.ts#L209-L220
