### ISSUE TITLE
Errors when using brackets with eth1.providerUrls & network.localMultiaddrs flags

### ISSUE THREAD

**Issue by Aren49** [ChainSafe/lodestar#3208]
**Describe the bug**

Docs and command-line options state that `eth1.provider` and `network.localMultiaddrs` flags require brackets however cause errors on the beacon node. To avoid errors, users should input commands without brackets e.g., `--eth1.providerUrls http://localhost:8545` and `--networklocalMultiaddrs /ip4/0.0.0.0/tcp/9000`.

**Comment by dapplion** [comment]
@philknows Would you mind taking a look?

**Comment by philknows** [comment]
Yep, been getting these errors too. Based on the documentation it should be able to handle the array format such as `--eth1.providerUrls ["http://localhost:8545","http://prater.infura.io/v3/blahblah"]`. But getting errors when done in that standard. Right now it only accepts `--eth1.providerUrls http://localhost:8545`

Is the documentation incorrect @dapplion ? Or do we actually want to implement it so it takes an array? I believe Lighthouse is doing an array and allows for that so there are failsafes incase eth1.providersUrl[0] fails.

**Comment by dapplion** [comment]
@philknows Yes the documentation is incorrect, that format won't work. Array arguments must be passed as
```
--flag arg1 arg2
```
