### ISSUE TITLE
ERR_INVALID_ATTESTATION_DOUBLE_VOTE

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3211]
**Describe the bug**

A user in discord reported  https://discord.com/channels/593655374469660673/593655641445367808/889555125448892427

```
error: Error signing attestation slot=1304012, index=17, head=0xdca5…3d80, validator=0xa87e…afb1 code=ERR_INVALID_ATTESTATION_DOUBLE_VOTE, attestation={"sourceEpoch":40749,"targetEpoch":40750,"signingRoot":"0x667cbb5b329650705425bddc216491a059be6e4e4dcab96727b5f1989a7bd847"}, prev={"sourceEpoch":40749,"targetEpoch":40750,"signingRoot":"0x4818486efdecad5d700e2b048c7ca3c4f85132cfbc929fc5f932b85199a952c3"}
```

Lodestar version=v0.30.0 (npm), network=prater
Neither my vc or bn node were restarting. I am running both in cli. I couldn't find any grafana dashboards for metrics. Can you please link it?
I plan on running  lodestar using systemd but will probably do that later on today. Unfortunately, I don't have any saved logs.

Perhaps it's my network settings? I have a lighthouse node running on port 9000 so I switched lodestar to use 9001. These are the settings I'm using. 

```
lodestar beacon --network prater --network.localMultiaddrs /ip4/0.0.0.0/tcp/9001 --network.discv5.bindAddr /ip4/0.0.0.0/udp/9001 --eth1.providerUrls https://goerli.infura.io/v3/XXX --network.targetPeers 50 --network.maxPeers 55
```

**Expected behavior**

Ǹot happen

**Comment by twoeths** [comment]
this happens in our contabo-7 too: 
`grep -e "ERR_INVALID_ATTESTATION_DOUBLE_VOTE" -nr validator*.log`

```
Sep-22 22:12:53.569 []                ^[[34mdebug^[[39m: Signed attestation slot=1320064, index=30, head=0x8ab7…5d87, valida      tor=0xa207…f892
```
that's maybe the wrong assignment for that validator since node can't verify it

```
 Sep-22 22:12:55.862 []                ^[[31merror^[[39m: Error publishing attestations slot=1320064, index=30 message=Intern      al Server Error: ATTESTATION_ERROR_INVALID_SIGNATURE
62005 Error: Internal Server Error: ATTESTATION_ERROR_INVALID_SIGNATURE
62006     at HttpClient.request (/usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/httpClient.ts:91:15)
62007     at runMicrotasks (<anonymous>)
62008     at processTicksAndRejections (internal/process/task_queues.js:95:5)
62009     at HttpClient.json (/usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/httpClient.ts:58:12)
62010     at Object.request [as submitPoolAttestations] (/usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/client.ts:      72:19)
62011     at AttestationService.produceAndPublishAttestations (/usr/app/node_modules/@chainsafe/lodestar-validator/src/services/at      testation.ts:110:9)
62012     at AttestationService.publishAttestationsAndAggregates (/usr/app/node_modules/@chainsafe/lodestar-validator/src/services      /attestation.ts:57:25)
62013     at /usr/app/node_modules/@chainsafe/lodestar-validator/src/services/attestation.ts:43:9
62014     at async Promise.all (index 1)
62015     at AttestationService.runAttestationTasks (/usr/app/node_modules/@chainsafe/lodestar-validator/src/services/attestation.      ts:40:5)
```

however we already push that attestation vote to the slashing protection db, hence when the real/latter assignment come in the same epoch (maybe), it throws double vote error

```
validator4-2021-09-22.log:62507:Sep-22 22:17:05.327 []                error: Error signing attestation slot=1320085, index=23, head=0x8ab7…5d87, validator=0xa207…f892 code=ERR_INVALID_ATTESTATION_DOUBLE_VOTE, attestation={"sourceEpoch":41250,"targetEpoch":41252,"signingRoot":"0xc0b64ed4d44394e904377d184928f9dfa29e2df2848b91e91571c6218bc82d6a"}, prev={"sourceEpoch":41250,"targetEpoch":41252,"signingRoot":"0x928c68b02a9a57111f846534d6d0b72688e3c2078e06fdd0c07bdb93e2470009"}
```

**Comment by twoeths** [comment]
meanwhile due to #3234 our node is not synced to head so maybe the duties is not correct (head is now 1320062 while clock slot is 1,321,087) but validator should be protected itself:
+ should only push to slashing protection db if the publish is a success
+ we want to log validator index in order to debug

**Comment by twoeths** [comment]
Root cause of the issue is the Attester duties were reorged since the node is syncing at that time.
```
61291 Sep-22 22:06:26.619 []                ^[[34mdebug^[[39m: Downloaded attester duties epoch=41252, dep      endentRoot=0x1a8c39e43986b779a2dd1c62a1ba3a5cbd8bb565dedf7370fa492e277d0ebd6b, count=225
```
```
61980 Sep-22 22:12:49.759 []                ^[[34mdebug^[[39m: Downloaded attester duties epoch=41252, dep      endentRoot=0x4637b4b89fb80f59e317c37a6a716e7f5f32c555d2864dce7b79b660748285df, count=225
61981 Sep-22 22:12:49.761 []                 ^[[33mwarn^[[39m: Attester duties re-org. This may happen fro      m time to time priorDependentRoot=0x1a8c39e43986b779a2dd1c62a1ba3a5cbd8bb565dedf7370fa492e277d0ebd6b      , dependentRoot=0x4637b4b89fb80f59e317c37a6a716e7f5f32c555d2864dce7b79b660748285df
```

`0x1a8c39e43986b779a2dd1c62a1ba3a5cbd8bb565dedf7370fa492e277d0ebd6b` is block slot 1320000 and `0x4637b4b89fb80f59e317c37a6a716e7f5f32c555d2864dce7b79b660748285df` is block slot 1320031 which all belongs to epoch 41250

at the same time, the node was syncing

```
11390033 Sep-22 22:00:15.479 [CHAIN]         ^[[36mverbose^[[39m: Block processed slot=1320000, root=0x1a8c39e43986b779a2dd1c62a1ba3a5cbd8bb565dedf7370fa492e277d0ebd6b
11640859 Sep-22 22:06:49.318 [CHAIN]         ^[[36mverbose^[[39m: Block processed slot=1320001, root=0x33f160ddebf9c012aff2322812313305e801acd01ea479b13e27e92ba01ee8fd
...
11682456 Sep-22 22:07:51.088 [CHAIN]         ^[[36mverbose^[[39m: Block processed slot=1320030, root=0x66bcae5caeb9f3bb15db09d3735d1d16b58f5dcdebc31921fc79ae7794f827b2
11684743 Sep-22 22:07:53.346 [CHAIN]         ^[[36mverbose^[[39m: Block processed 
slot=1320031, root=0x4637b4b89fb80f59e317c37a6a716e7f5f32c555d2864dce7b79b660748285df
```

the conclusion is the node was syncing at the time that made the attester duties reorged, the 1st attester assignment was normally wrong and we marked slashing protection db, the 2nd attester assignment in the same epoch was the right one but attester couldn't sign attestation again due to it signed in the same epoch already (and hence double vote error at validator side)

**Comment by twoeths** [comment]
in fact, the 1st getAttesterDuties request to get duties for epoch 41252 while the head at 41250 should be failed, the node should check that it's not reliable to return attester duties at that time.

**Comment by twoeths** [comment]
```
Sep-22 22:00:15.479 [CHAIN]         ^[[36mverbose^[[39m: Block processed slot=1320000, root=0x1a8c39e43986b779a2dd1c62a1ba3a5cbd8bb565dedf7370fa492e277d0ebd6b
...
Sep-22 22:07:53.346 [CHAIN]         ^[[36mverbose^[[39m: Block processed slot=1320031, root=0x4637b4b89fb80f59e317c37a6a716e7f5f32c555d2864dce7b79b660748285df

```
while the 1st attestation duty happened at `Sep-22 22:12:53.569`, attester duties reorg happened at `Sep-22 22:12:49.761` which is quite late (after the slot started)

dependentRoot is the last block of an epoch (`requestedEpoch - 2`), as shown above we should be able to detect attestation duties reorg much sooner
