### ISSUE TITLE
Gossip params may not be applied

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3228]
**Describe the bug**

Gossip params may be ignored by GossipSub class. In the constructor GossipSub computes its own params

```ts
      ...options,
      scoreParams: createPeerScoreParams(options.scoreParams),
```

https://github.com/ChainSafe/js-libp2p-gossipsub/blob/efb8cba0b4f5a56dc0edc323ced0ae2d1bfeed86/ts/index.ts#L163

@tuyennhv does that invalidate the ones passed from Lodestar?

----

Also please @tuyennhv can you do a PR to remove this line? 

https://github.com/ChainSafe/lodestar/blob/0d7121fa38e5fd58250d87542357ca5a41f3d63f/packages/lodestar/src/network/gossip/scoringParameters.ts#L108

it prints a massive wall of text with all params. If you need to get them can you expose them through the Lodestar API?

**Comment by twoeths** [comment]
> @tuyennhv does that invalidate the ones passed from Lodestar?

no, we're good
![Screen Shot 2021-09-23 at 13 56 44](https://user-images.githubusercontent.com/10568965/134465955-7700cf18-f0a2-4072-a256-06818d678f9c.png)

> Also please @tuyennhv can you do a PR to remove this line?

I will remove it, got all params in the unit tests

**Comment by dapplion** [comment]
> no, we're good

@tuyennhv then am I reading the code correctly? Why doesn't the `Gossipsub` override your scores? Please guide me through the source code.

**Comment by twoeths** [comment]
@dapplion yeah from the 1st look it seems like it uses its own score params
```ts
      ...options,
      scoreParams: createPeerScoreParams(options.scoreParams),
```

however `options` is from lodestar GossipSub so `createPeerScoreParams(options.scoreParams)` really get data from lodestar GossipSub

```ts
export function createPeerScoreParams (p: Partial<PeerScoreParams> = {}): PeerScoreParams {
  return {
    ...defaultPeerScoreParams,
    ...p,
    topics: p.topics
      ? Object.entries(p.topics)
        .reduce((topics, [topic, topicScoreParams]) => {
          topics[topic] = createTopicScoreParams(topicScoreParams)
          return topics
        }, {} as Record<string, TopicScoreParams>)
      : {}
  }
}
```
