### ISSUE TITLE
investigate: when multiple validator processes (attached to same bn) call getAttesterDuties in parallel, investigate if epoch transition is processed single or multiple times

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#3246]
context:
#3201
![image](https://user-images.githubusercontent.com/76567250/134715334-4610f8ed-ecae-48bd-8f38-bf5faf27ed52.png)

**Comment by dapplion** [comment]
@g11tech Please link the issue with a link too always so they are hyperlinked in both places

**Comment by g11tech** [comment]
@dapplion  i don't think it is leading to multiple evaluations of the regenFn's getBlockSlotState called by getAttesterDuties as even if validators processes are parallel, they get queued in the jobProcessor which is single threaded with default maxConcurrency of 1.

this is confirmed by the distribution of delta's of duration spend in `getBlockSlotState` during the epoch transitions in both 

16vc prater node:1 validator process, 
![image](https://user-images.githubusercontent.com/76567250/135035201-7f4ef709-19d4-465b-9f31-550e7b18c717.png)


975 prater node : 4 validator processes
![image](https://user-images.githubusercontent.com/76567250/135035259-b6902c1a-4aab-4ea9-ba83-21b7ed0aa6d0.png)

Both look to have the same distribution delta during epoch transitions: 

`delta(regen_fn_call_duration_sum{entrypoint="getBlockSlotState",caller="getDuties"}[$__rate_interval])`, which basically implies that 4 extra validator duties call in epochs are not really causing any extra or duplicate computation.

even if the maxConcurrency is increased, there would be no issue as getBlockSlotState's call might get interleaved, but they will still use each other's results as all is happening on a single thread.
