### ISSUE TITLE
Lodestar Validator Connection Unresponsive

### ISSUE THREAD

**Issue by jeyakatsa** [ChainSafe/lodestar#3249]
**Describe the bug**

After running `lodestar validator --network $NETWORK-NAME` on terminal for all networks "mainnet", "pyrmont", "prater", "altair-devnet-3", error:  `✖ keystoresDir C:\Users\Jeyak\.local\share\lodestar\pyrmont\keystores does not exist`

**Expected behavior**

After running `lodestar validator --network $NETWORK-NAME`, terminal should have shown example:
```
2020-08-07 14:14:24  []                 info: Decrypted 2 validator keystores
2020-08-07 14:14:24  [VALIDATOR 0X8BAC4815] info: Setting up validator client...
2020-08-07 14:14:24  [VALIDATOR 0X8BAC4815] info: Setting up RPC connection...
2020-08-07 14:14:24  []                 info: Checking genesis time and beacon node connection
2020-08-07 14:14:24  [VALIDATOR 0X8E44237B] info: Setting up validator client...
2020-08-07 14:14:24  [VALIDATOR 0X8E44237B] info: Setting up RPC connection...
```
as stated through: [https://chainsafe.github.io/lodestar/usage/testnet/](url)

**Steps to Reproduce**

1. Open terminal
2. Type `lodestar validator --network $NETWORK-NAME`
3. See error (stated above)

**Desktop (please complete the following information):**

- OS: Windows 10
- Version:  🌟 Lodestar: TypeScript Implementation of the Ethereum 2.0 Beacon Chain.
  * Version: v0.30.0 (npm)
  * by ChainSafe Systems, 2018-2021

- Branch: N/A
- Commit hash: N/A

Let me know if you all need anymore information.

**Comment by twoeths** [comment]
@jeyakatsa do you have any validator keystores for pyrmont network? Fyi, you can specify the path to your keystore dir with `--keystoresDir` and `--secretsDir`.

If there is no keystore, the validator won't start, hence it'll throw the above error.

**Comment by jeyakatsa** [comment]
Thanks @tuyennhv will look into that immediately and get back with said results.

**Comment by jeyakatsa** [comment]
@tuyennhv there are no keystores for any of the networks (mainnet or testnets)..
```
✖ keystoresDir C:\Users\Jeyak\.local\share\lodestar\prater\keystores does not exist
✖ keystoresDir C:\Users\Jeyak\.local\share\lodestar\pyrmont\keystores does not exist
✖ keystoresDir C:\Users\Jeyak\.local\share\lodestar\mainnet\keystores does not exist
✖ keystoresDir C:\Users\Jeyak\.local\share\lodestar\altair-devnet-3\keystores does not exist
```

Shouldn't the keystores have installed/downloaded with the npm install or would I have to input them individually (at a later step in the lodestar documentation)? 

Because the lodestar installation documentation doesn't specify this... https://chainsafe.github.io/lodestar/installation/#install-from-npm
After the installation, it guides you straight into testing the mainnet, testnets and validators with no explanation about the keystores: https://chainsafe.github.io/lodestar/usage/testnet/

I'll do some trial and error to try and resolve this while I await your response.

Thanks.

**Comment by twoeths** [comment]
Hi @jeyakatsa, please go with https://launchpad.ethereum.org/en/ to get keystores/secret keys for your validators then import that to lodestar:
+ `./bin/lodestar account validator import --help` for more information
+ once you import your keystores successfully, verify it in the above folders and start using your validators in lodestar

**Comment by jeyakatsa** [comment]
Thanks @tuyennhv getting on this immediately, will get back to you with results.

**Comment by jeyakatsa** [comment]
@tuyennhv seems like I'll need to deposit a certain amount of Eth in order to become a "validator", currently going through the testing phase before jumping into building out a prototype for the Altair fork. Thanks though, it seems that I may not need to become a validator in order to test the prototype. Will open new issue if necessary.
