### ISSUE TITLE
Unstable block processing time

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3267]
**Describe the bug**

After improving `processAttestations`, block processing time is increase~40%, however some block processing time grow significantly compared to others

Contabo-0
<img width="785" alt="Screen Shot 2021-09-29 at 10 52 57" src="https://user-images.githubusercontent.com/10568965/135200535-f94031c0-86de-4087-8b88-dde45e35d475.png">

My node
<img width="789" alt="Screen Shot 2021-09-29 at 10 53 15" src="https://user-images.githubusercontent.com/10568965/135200568-02f20fba-0779-40ca-85a2-ff00fa571d7b.png">

**Expected behavior**
+ Since these 2 nodes are synced, the increased time at some block transition is **not** due to the block data itself
+ We want to see a more consistent block transition time

**Comment by twoeths** [comment]
The `persistent.ts` `Vector.forEach()` is not stable, sometimes it takes only 25ms, sometimes it takes up to 211ms with the same amount of data (the participation flag cache of an epoch)

![Screen Shot 2021-09-29 at 11 07 00](https://user-images.githubusercontent.com/10568965/135201642-0fc656f6-b143-4f36-9c87-a60180ef0e5d.png)

![Screen Shot 2021-09-29 at 11 07 41](https://user-images.githubusercontent.com/10568965/135201699-a53a55e5-1922-466a-92e4-5a2e766fce81.png)

It's most likely that the closure `iterateNodeValues()` causes the issue, we want to avoid using closure in a lot of places in the past anyway

**Comment by dapplion** [comment]
Nice find! Tho @tuyennhv please consider starting working on the new ssz tree view approach which would solve all of this issues

**Comment by dapplion** [comment]
Has not been observed in a while
