### ISSUE TITLE
Improve forkchoice computeDeltas

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3269]
**Describe the bug**

Forkchoice metrics showed that it takes 80ms - 160ms to find head which is too much

<img width="812" alt="Screen Shot 2021-09-29 at 11 43 47" src="https://user-images.githubusercontent.com/10568965/135204625-1e11c66b-e483-4772-abb7-6630c7bf718f.png">

Most of the time is for `computeDeltas()` function
![Screen Shot 2021-09-29 at 11 42 00](https://user-images.githubusercontent.com/10568965/135204552-8d579024-ca8a-4b9b-a98e-77f84c00b735.png)

This is the profiler I got for `computeDeltas()`
![Screen Shot 2021-09-29 at 11 41 27](https://user-images.githubusercontent.com/10568965/135204445-f8b121f2-dea2-41c0-b9b9-6329c66c0b57.png)

**Comment by twoeths** [comment]
<img width="780" alt="Screen Shot 2021-09-30 at 09 06 24" src="https://user-images.githubusercontent.com/10568965/135374436-fa55acab-f405-4d27-91ca-720170cc8638.png">

**Comment by dapplion** [comment]
Nice gain!
