### ISSUE TITLE
E2E tests for checking our client implementation

### ISSUE THREAD

**Issue by Mikerah** [ChainSafe/lodestar#33]
In Prague, there was a working group that was charged with standardizing testing clients in ETH2.0. Prysmatic Labs has just posted an uncompleted spec of this in their repo: https://github.com/prysmaticlabs/prysm/tree/master/beacon-chain/chaintest

We need to work on implementing these tests into Lodestar before the project gets to big.

**Comment by ansermino** [comment]
Official Spec [WIP]: https://github.com/ethereum/eth2.0-specs/blob/master/specs/test-format.md

**Comment by mpetrunic** [comment]
solved in #237
