### ISSUE TITLE
Deprecate accounts CLI

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3300]
After merging https://github.com/ChainSafe/lodestar/pull/3296 the accounts CLI is not really necessary anymore. Consider deprecating it or at least removing it from documentation

Lighthouse did already deprecate it and it has been successful among users. Everyone uses Launchpad generated keystores

**Comment by philknows** [comment]
Also some solutions like https://github.com/stake-house/wagyu-key-gen and other interfaces coming online to make it easier to generate keys.
