### ISSUE TITLE
Disallow if coercion

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3324]
**Describe the bug**

Coercing values in if statements can be problematic if the variable can be a 0 which should be truthy:

```ts
let num: number | null;
if (num) {}
```

Require

```ts
let num: number | null;
if (num !== null && num > 0) {}
```

Check: https://eslint.org/docs/rules/no-implicit-coercion

**Comment by twoeths** [comment]
@dapplion I don't see that rule helps this case, could you have a look at `@typescript-eslint/strict-boolean-expressions` rule? https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/strict-boolean-expressions.md

**Comment by dapplion** [comment]
> @dapplion I don't see that rule helps this case, could you have a look at `@typescript-eslint/strict-boolean-expressions` rule? https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/strict-boolean-expressions.md

Oh! Yeah this rule if much better. I didn't checked if the rule I linked would help at all

**Comment by filipesmedeiros** [comment]
why not both? 😄

edit: i really hate coercion lol

**Comment by filipesmedeiros** [comment]
i left this cooment! https://github.com/ChainSafe/lodestar/pull/3364/files#r729188667

too late now but oh well ahah
