### ISSUE TITLE
running on a raspberry pi

### ISSUE THREAD

**Issue by filipesmedeiros** [ChainSafe/lodestar#3334]
**What is your question?**

in the official docs, i can find the minimum/recommended specs, but they only mention x86/intel processors.

has the client been tested on arm? more specifically, on raspberry pis? i'd love to run a node at home, but don't want to buy the pi if it won't work at all (i think i work through some quirks if necessary)

thanks in advance!

**Comment by dapplion** [comment]
Hey @filipesmedeiros ! I haven't tried myself but I don't see why not. Lodestar runs in the M1 macbooks and NodeJS has good support for arm. I case it doesn't run in your arm setup due to an unavoidable problem your purchase won't be wasteful since other implementations also can run in arm

**Comment by filipesmedeiros** [comment]
perfect! i've bought a pi and will report back (maybe i can use this issue?)

> I case it doesn't run in your arm setup due to an unavoidable problem your purchase won't be wasteful since other implementations also can run in arm

yeah a pi always has use cases eheh thanks!

**Comment by dapplion** [comment]
Yes please! Update us here, would love to know how it goes and help troubleshoot. 

For reference @mpetrunic has had experience building Lodestar on arm. Please Marin stay subscribed to this issue if you can

**Comment by filipesmedeiros** [comment]
nice. i actually have an m1 macbook (on which i use node every day), so maybe i'll also use it as an initial feeling of how to go. although macos has rosetta which might make everything a bit confusing... not sure!

**Comment by filipesmedeiros** [comment]
just for future reference, both: `lodestar account wallet create --name primary --passphraseFile primary.pass` and

```bash
./lodestar dev --startValidators 0:0 \
  --genesisStateFile ./dev/genesis.ssz \
  --network.localMultiaddrs /ip4/127.0.0.1/tcp/30607 \
  --sync.minPeers 1
```

threw a `seg fault` on my first try

**Comment by philknows** [comment]
Hey @filipesmedeiros! Just wondering if you happened to have an update on this. Would love to hear about how it went. Luckily after merging in #3296 you won't need to deal with the account CLI anymore, we are planning to deprecate that. Just put the keystore JSONs in a folder with the password.txt and link them via `--importKeystoresPath` and `--importKeystoresPassword` 

Thanks!

**Comment by filipesmedeiros** [comment]
Heyo! I tried to but failed because of reasons I couldn't understand. I have the Pi with me still, and will try to rebuild Lodestar in the next few days, and will let you know!

**Comment by dapplion** [comment]
Thanks for the update @filipesmedeiros ! Please feel free to share more details of what went wrong, including logs or screen captures

**Comment by filipesmedeiros** [comment]
Hey! I tried this again and got a `Segmentation fault` error. With nothing else 😢
<img width="942" alt="Screenshot 2022-02-16 at 19 12 46" src="https://user-images.githubusercontent.com/26208850/154338520-69e531e3-2870-44e9-97ed-d320f6245f1c.png">

With that said, I'm (sadly) leaving the Ethereum community (at least for now), so I won't be able to help you guys with this one anymore (not that I helped a lot lol)

Hope everything goes well!!! Wanna see lodestar succeed greatly one day 😄

**Comment by dapplion** [comment]
>  won't be able to help you guys with this one anymore (not that I helped a lot lol)

Thank you so much for trying it out, your input was valuable! Have fun on your next journey, curious where it will be :eyes:

**Comment by filipesmedeiros** [comment]
Not gonna shill here but it's still crypto ahah I really hope ether can have better UX some day, because in everything else it's an amazing project! I hope you guys succeed in bringing decentralized web to the masses ❤️ 

EDIT: autocorrect lol
