### ISSUE TITLE
Broken Readme Links

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/lodestar#3350]
**Describe the bug**

The Readme links on the following lines seem to be broken: 

    ⚙️ Follow the installation guide to install Lodestar.
    🌐 Run lodestar on the Eth2 mainnet or on a public testnet.
    💻 Quickly try out the whole stack by starting a local testnet.
    🗒️ View the lodestar CLI commands and options.
    🤓 View the TypeDoc code documentation.

**Expected behavior**

Links should go to the appropriate documentation.

**Comment by wemeetagain** [comment]
Thanks for reporting this :heart: Looks like the github pages broke.... Should be fixed now!
