### ISSUE TITLE
State for currentJustifiedCheckpoint not available

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3358]
**Describe the bug**

Got this error while syncing:

```
Oct-13 06:18:06.629 [CHAIN]           error: State for currentJustifiedCheckpoint not available, using closest state checkpointEpoch=1230, checkpointRoot=0xd91739c32a919ec322926368a5c34155f1492578876c282dc505ca341f5dc0e9, stateSlot=9841, stateRoot=0x169e6840c5e75878689b5344c085b749dba1a444ede326979cae542fd7dfad00
```

**Expected behavior**

No error

**Comment by twoeths** [comment]
This is because we don't store checkpoint state for epoch with skipped slot in the current implementation, it's implemented here https://github.com/ChainSafe/lodestar/blob/v0.30.0/packages/lodestar/src/chain/blocks/stateTransition.ts#L79

Whenever we pass checkpoint, we should store it in the checkpoint state cache because that checkpoint state may become justified/finalized state later and we need it.

@dapplion could you confirm this?

**Comment by dapplion** [comment]
@tuyennhv When I finish with the SSZ refactor I'll go for a review a regen that should tackle that. You can see the WIP branch here https://github.com/ChainSafe/lodestar/tree/dapplion/regen-blackbox

**Comment by dapplion** [comment]
Closing for https://github.com/ChainSafe/lodestar/issues/4005

This specific case is mitigated by a flexible fn that tolerates that specific state not being avail

https://github.com/ChainSafe/lodestar/blob/fd6f7020a048e624b6567d46d50d3011afdd55e7/packages/lodestar/src/chain/blocks/importBlock.ts#L267
