### ISSUE TITLE
endpoint `node/syncing` has missing data

### ISSUE THREAD

**Issue by BeroBurny** [ChainSafe/lodestar#3362]
**Describe the bug**

endpoint `/eth/v1/node/syncing` return what is wrong by spec https://ethereum.github.io/beacon-APIs/#/Node/getSyncingStatus

```json
{
  "data": {
    "head_slot": "1",
    "sync_distance": "1"
  }
}
```

**Expected behavior**

endpoint `/eth/v1/node/syncing` should return

```json
{
  "data": {
    "head_slot": "1",
    "sync_distance": "1",
    "is_syncing": true
  }
}
```

**Steps to Reproduce**

1.  Run Beacon Node
2. get request on `{api}/eth/v1/node/syncing`

**Desktop (please complete the following information):**

- OS: ubunto 20, docker
- Version: 0.31.1

**Comment by g11tech** [comment]
hi @BeroBurny , this field has been added in merged PR, https://github.com/ChainSafe/lodestar/pull/3345
Kindly rebuild (clean & build) from the latest master or wait for versioned release (or use lodestar:next)
