### ISSUE TITLE
Invalid `ETH1_ADDRESS_WITHDRAWAL_PREFIX` value in params package

### ISSUE THREAD

**Issue by mortimr** [ChainSafe/lodestar#3366]
Hey !

You might have an issue with one of your params right here https://github.com/ChainSafe/lodestar/blob/57c0c87325a4a264d081b72f895bc704718ef99f/packages/params/src/index.ts#L90

It should be 1, right ?

I can raise a PR if that's the case just tell me

**Comment by dapplion** [comment]
Yes please! Thanks for taking a look into the code, will review your PR :+1:
