### ISSUE TITLE
lodestar validator interop with other clients beacon nodes

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#3368]
## Status against clients
  > Lighthouse 
   - [x] Manual interfacing 
     - [x] Local testnet setup with client beacons and validators forming fully functional chain
     - [x] Interfacing/connection with the beacon node
     - [x] API Interoperability
       - [x] request  and process api responses from beacon chain

   - [x] Functionality
     - [x] Publish Attestations
     - [x] Publish Block
     - [x] Get the finality going ( 2/3 of validator set only with lodestar)
     - [x] Recover the finality ( join 1/2 of validator set after multi epoch finality delay and nodes achieve finality)
   - [ ] Interop tests integrated
     - [ ] Docker Setup for the local testnet of client beacons
     - [ ] API endpoints in spec
     - [ ] Functionality Tests

### Progress /Outstanding Issues
> Subtasks/issues
 - [x]  casingMap to match the case
 - [x] A way to Deal with fields yet not operation and hence mightnot be in the beacon response for config (like merge fields:  `TERMINAL_TOTAL_DIFFICULTY`, `MERGE_FORK_VERSION` ...), are not available in stable branch  of lighthouse, and can't be assumed to be available untill the respective fork date #3369
 - [x] `produceBlock` api call from validator to lighhouse beacon is not working #3370

**Comment by g11tech** [comment]
linked issue: https://github.com/ChainSafe/lodestar/issues/3018

**Comment by hiromaily** [comment]
I'm curious about current progress of `Docker Setup for the local testnet of client beacons`
Does anyone know that?

**Comment by g11tech** [comment]
> I'm curious about current progress of `Docker Setup for the local testnet of client beacons` Does anyone know that?

You can now find the way to setup local testnet with other clients (both EL/CL) in our sim framework: https://github.com/ChainSafe/lodestar/blob/unstable/packages/cli/test/sim/multi_fork.test.ts

**Comment by g11tech** [comment]
Closing the issue as the cross validator interop is basically functional with other clients and can be further looked on depending on use cases
