### ISSUE TITLE
investigate: weak subjectivity checkpoint improper use

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#3385]
The weak subjectivity seems to be not being properly used. As per my understanding of the code, following are the issues:

1. when `weakSubjectivityStateFile` is being used, `isWithinWeakSubjectivityPeriod` check will almost always pass doesn't matter hold old the state if starting from blank block db (first time use)
2. Beacon should init from the db's last (biggest height) checkpoint instead from the provided checkpoint if db's last checkpoint height is more (forkChoice rule: build on top of the last seen checkpoint). In this case however point 4 check should be made
~~. `isWithinWeakSubjectivityPeriod` check should be done when the node gets into `Synced` state for the first time since being started. This check should be done irrespective of weak subjectivity flags provisioning, and should be checked against last anchor checkpoint state from where the sync started (even if the node was previously synced but went out of sync for any reason)~~
3. If a checkpoint is provided, and db's last save checkpoint > than the provided checkpoint, there needs to be a strict check made that provided checkpoint is a  ancestor of db's checkpoint from where the state is being fetched (apart from early check of being with the wss period).
4. documentation on `weakSubjectivitySyncLatest` always fetching the weak subjectivity checkpoint on starts/restarts.

Resolution: fix if any issue is deemed correct upon discussion.

TRACKER:
~~-  When the node syncs to chain head for the first time after starting or falling out of sync, the weak subjectivity checks should be done. This might not be an issue  in normal operation but an attacker could devise scenarios to server just borderline checkpoints which on sync might be out of sync. or in extreme scenarios where the validator set shrinks so much that the wss period is small.~~
~~Check the anchor state's checkpoint is the parent of the finalized checkpoint when the chain syncs for first time to head else panic~~

- [x] In case finalized state from DB is ahead of the provide wss state, make the check that checkpoint is parent of db's finalized and then move forward else again start from the wss checkpoint 
- [x] rectify check on wss's subjectivity period of the anchor state w.r.t. the clockSlot while initializing the chain
- [x] if the wss state is  before db's archieved state, then validate if the wss checkpoint is the ancestor of the db's state (https://github.com/ChainSafe/lodestar/pull/3384)
- [ ] Documentation

**Comment by g11tech** [comment]
@wemeetagain @dapplion @tuyennhv @philknows

**Comment by dapplion** [comment]
Good points! Thanks for reviewing the spec in this regard, super valuable!

**Comment by g11tech** [comment]
Closing the issue as currently we seemed to be covered on various points, forward sync with checkpoint is not really effective for syncing and hence not really used by the users
