### ISSUE TITLE
Investigate performance issue in pithos testnet

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3390]
**Describe the bug**

The total state transition takes so much time in lodestar-geth instance of pithos network
```
Oct-25 09:26:49.206 [CHAIN]         verbose: Clock slot slot=78409
Oct-25 09:26:49.208 [NETWORK]       verbose: Received gossip block slot=78409, root=0x961a…0d3a, curentSlot=78409
Oct-25 09:26:51.338 [CHAIN]         verbose: Block processed slot=78409, root=0x961acd847841288c4584419e3f0530cee625779160c729821f3fa273f60c0d3a
Oct-25 09:27:00.623 [CHAIN]         verbose: Clock slot slot=78410
Oct-25 09:27:02.152 [NETWORK]       verbose: Received gossip block slot=78410, root=0xd888…5d09, curentSlot=78410
Oct-25 09:27:12.025 [CHAIN]         verbose: Clock slot slot=78411
Oct-25 09:27:13.964 [NETWORK]       verbose: Received gossip block slot=78411, root=0x5ac8…8ad4, curentSlot=78411
Oct-25 09:27:15.908 [CHAIN]         verbose: Block processed slot=78410, root=0xd888b52b3ac5089ba6ad7630592a6e956b8c29c1f0254c29be6b3c09dd645d09
Oct-25 09:27:24.076 [CHAIN]         verbose: Clock slot slot=78412
Oct-25 09:27:24.185 [NETWORK]       verbose: Received gossip block slot=78412, root=0x398b…5f83, curentSlot=78412
Oct-25 09:27:25.557 [CHAIN]         verbose: Block processed slot=78411, root=0x5ac82b0192fa834a322e10f7d3542dcdc16e65f65fa23ad9122f436e61898ad4
Oct-25 09:27:26.267 [CHAIN]         verbose: Block processed slot=78412, root=0x398b5d8b077289c2828ad9ee22cae0ae344394d0f32f77482234d8072d775f83
Oct-25 09:27:36.024 [CHAIN]         verbose: Clock slot slot=78413
Oct-25 09:27:37.965 [CHAIN]         verbose: Block processed slot=78413, root=0xe30594ab7157bf1d360bb094c28e1246fe112550ef31f93f92d35c80aea2221e
```

The contabo-3 instance shows the same
<img width="1595" alt="Screen Shot 2021-10-25 at 16 37 37" src="https://user-images.githubusercontent.com/10568965/138672327-d7ee30d3-06fe-443f-ac37-bc546dff0660.png">

however the consensus state transition looks good
<img width="1569" alt="Screen Shot 2021-10-25 at 16 38 14" src="https://user-images.githubusercontent.com/10568965/138672438-615800e5-d05b-4673-839a-07bff8a9b57f.png">

so I suspect the geth state transition takes so much time?

**Expected behavior**

+ Should be consistently less than 2s (at least) so that validator can submit timely head attestation
+ Run both state transtion in parallel?

**Steps to Reproduce**

Sync lodestar-geth in pithost

**Comment by twoeths** [comment]
+ Debug logs from geth shows that it really does not take time to process an execution block
+ Restart contabo-3 with no validator and `subscribeAllSubnets` flag and it has no issue
+ It's more likely the node can't handle 1000 validators in pithos network

**Comment by dapplion** [comment]
@tuyennhv Can you take a cpu profile of the pithos node to learn what is the bottleneck?

**Comment by twoeths** [comment]
After some days, the issue does happen on contabo-3 too which has no validator.
Was able to profile the lodestar-geth instance in contabo-3 
[1101_pithos_contabo_3.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/7451788/1101_pithos_contabo_3.cpuprofile.zip)

at least there is a performance issue when we handle PONG message of discv5
<img width="1573" alt="Screen Shot 2021-11-01 at 15 33 27" src="https://user-images.githubusercontent.com/10568965/139644800-4d6b18c8-a9be-4878-b6ad-ed2989e45f45.png">

details of the `best` function
<img width="1663" alt="Screen Shot 2021-11-01 at 15 24 45" src="https://user-images.githubusercontent.com/10568965/139644900-cc6a5634-c53a-489a-a472-e0af8e274703.png">

note that `this.tallies` is an object of > 34000 keys and we have to loop through them when handling a PONG message

root cause may be due to https://github.com/ChainSafe/discv5/blob/8efdb533e1a5e349ab72e38566bdb7e7fae877bf/src/service/addrVotes.ts#L12

where we want to call `removeVote()` instead of `removeTally()`

**Comment by twoeths** [comment]
pithos is over and don't see this issue any more, closing the issue

**Comment by dapplion** [comment]
Should be fixed with https://github.com/ChainSafe/lodestar/pull/3642
