### ISSUE TITLE
Convert core/state to typescript

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/lodestar#34]
While converting the code to typescript I will also be checking to ensure that we are still up-to-date with the current [spec](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md).

**EDIT :: 25/11/18**  - Since the spec has been changed quite a bit (noted by: @Mikerah & @ansermino) the primary focus will be to ensure that the spec is up-to-date as stated above, while also converting to typescript.

~~**Note:**~~
~~- I will be working alphabetically (descending) through `core/state`.~~
~~- Checked items are currently being worked on in the branch `greg/typescript-conversion`.~~

~~Currently working on:~~

~~- [x] Interfaces :: A collection of all the eth2.0 data structures~~

~~Completed:~~
~~none~~

Just going through the spec and re-implementing ground up!

**Comment by Mikerah** [comment]
Before this continues, the spec has changed a lot and thus the code in this repo is out of date. In order to not have duplicate work, check the spec for the data structures that have stayed the same. Currently, ActiveState and CrystallizedState have been merged into a single state.

**Comment by GregTheGreek** [comment]
@Mikerah - @ansermino informed me of this.. That's fine, I was just laying out my plan before moving forward. As stated, I will be using this to update the spec. In reality I'll probably re-write everything but use the existing code as a reference (when applicable)
