### ISSUE TITLE
 Kintsugi 🍵 (the Merge November sprint)

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3410]
## Kintsugi 🍵 milestones

Ref: https://notes.ethereum.org/@djrtwo/kintsugi-milestones

- [x] M0: Implementation started
- [x] M1: Spec Implemented https://github.com/ChainSafe/lodestar/pull/3418
- [x] M2: 1-to-1 Interop – One EL and one CL team pair off for basic interop testing (:heavy_check_mark:  Geth, :heavy_check_mark:   Nethermind)
- [x] M3: Many-to-Many Interop – 2 or more EL and CL teams perform interop testing
- [x] M4: Weekly devnet – Weekly devnet build for more in depth testing (https://github.com/ChainSafe/lodestar/issues/3452)
- [x] M5: All-to-All persistent testnet – All ready EL and CL teams create a long-lived devnet first week of december
- [ ] M6: Kintsugi🍵 code released – lients release Kintsugi🍵 code for public consumption

## Kintsugi 🍵 TODO

Spec versions https://hackmd.io/@n0ble/kintsugi-spec

- [x] Consensus specs PR to implement. See https://github.com/ChainSafe/lodestar/issues/3076
  - [x] https://github.com/ethereum/consensus-specs/pull/2617
  - [x] https://github.com/ethereum/consensus-specs/pull/2621
  - [x] https://github.com/ethereum/consensus-specs/pull/2682
  - [x] https://github.com/ethereum/consensus-specs/pull/2683
  - [x] https://github.com/ethereum/consensus-specs/pull/2684
  - [x] https://github.com/ethereum/consensus-specs/pull/2686
  - [x] https://github.com/ethereum/consensus-specs/pull/2687
  - [x] https://github.com/ethereum/consensus-specs/pull/2698
  - [x] https://github.com/ethereum/consensus-specs/pull/2699
  - [x] https://github.com/ethereum/consensus-specs/pull/2711
- [x] #3483
  - [x] https://github.com/ethereum/consensus-specs/pull/2720
  - [x] https://github.com/ethereum/consensus-specs/pull/2728
  - [x] https://github.com/ethereum/consensus-specs/pull/2738
  - [x] https://github.com/ethereum/consensus-specs/pull/2719
- [x] Polish optimistic sync, only attest and build blocks on fully verified execution payloads
  - Very helpful resources [Optimistic Sync Homepage](https://hackmd.io/Ic7VpkY3SkKGgYLg2p9pMg)
  - [Optimistic Sync: Which is the right head for the job?](https://hackmd.io/xsk9_feiQ3SIYz2yRa1z7Q)

----

![360_F_395687776_8reIYev9jpL6l3hvKCWMdTbIgbCQr05p](https://user-images.githubusercontent.com/35266934/140315365-bbab8196-5dfc-4663-86e5-1ddce46f7215.jpg)

> Kintsugi is the unique and traditional Japanese art of repairing broken, chipped and cracked pottery using lacquer and gold.

**Comment by philknows** [comment]
Closing this tracking issue for Kintsugi focused on the November Sprint. New issues relating to the testnet will be tracked under #3452.
