### ISSUE TITLE
Performance issue with subscribeAllSubnets flag

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3416]
**Describe the bug**

If we start a node with `--network.subscribeAllSubnets` flag, it may take up to 40s to process a gossip block

<img width="1614" alt="Screen Shot 2021-11-05 at 17 20 57" src="https://user-images.githubusercontent.com/10568965/140495988-0d371776-3fd5-4128-b545-818f66547caf.png">

**Expected behavior**
No performance issue with  `--network.subscribeAllSubnets` flag

**Comment by twoeths** [comment]
[1105_contabo_1_subscribeAllSubnets.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/7482539/1105_contabo_1_subscribeAllSubnets.cpuprofile.zip)

**Comment by twoeths** [comment]
Looks like it's a memory issue that cause the node pause more frequently due to gc

<img width="1587" alt="Screen Shot 2021-11-08 at 15 06 31" src="https://user-images.githubusercontent.com/10568965/140705791-234e56d9-30f2-4fe8-a651-69df703ce0c9.png">

gc pause time is almost 15% while it's 8.5% on normal node

**Comment by twoeths** [comment]
one other issue was with throwing GossipActionError as noted in #3402, it took > 4% just to throw that

<img width="1481" alt="Screen Shot 2021-11-08 at 16 21 20" src="https://user-images.githubusercontent.com/10568965/140716138-f0452e38-43b4-42de-9699-7402a4ed2703.png">

**Comment by dapplion** [comment]
@tuyennhv In the profile that you posted there's an insane amount of CPU time spent with async hook
- `registerDestroyHook`
- `promiseInitHookWithDestroyTrackinginternal`

![Screenshot from 2021-11-08 14-56-15](https://user-images.githubusercontent.com/35266934/140754439-079f034c-513f-449d-9561-d7df55b81780.png)


Could you investigate what's going on there?

**Comment by twoeths** [comment]
> @tuyennhv In the profile that you posted there's an insane amount of CPU time spent with async hook
> registerDestroyHook
> promiseInitHookWithDestroyTrackinginternal

@dapplion  this is internal code of nodejs https://github.com/nodejs/node/blob/8d6a02583f51368a76f4244584351b2e5d061e2a/lib/internal/async_hooks.js#L328, I really don't see them in a healthy node. In the `subscribeAllSubnets()` node, there are a lot of rejected promises in the call of `validateGossipAttestation()` and `validateGossipAggregateAndProof()` that may cause this, could be linked to #3402 too

**Comment by twoeths** [comment]
in the last 12h, the performance is back to normal, most of gossip blocks are processed within 4s 
<img width="1593" alt="Screen Shot 2021-11-10 at 16 47 16" src="https://user-images.githubusercontent.com/10568965/141090230-1ea9cfe8-c240-4df2-a4ef-5bcf6c847708.png">

Active requests metric shows that "TCPConnectWrap" drops significantly. What I read is "TCPConnectWrap" is the number of tcp connections wrapped between javascript and C layer
<img width="801" alt="Screen Shot 2021-11-10 at 16 49 32" src="https://user-images.githubusercontent.com/10568965/141090473-7ffdc693-1419-42aa-886a-1ae1b404db78.png">

Prometherus duration was very high during the busy time
<img width="793" alt="Screen Shot 2021-11-10 at 17 05 38" src="https://user-images.githubusercontent.com/10568965/141093125-fba52b6a-e290-43d8-8284-8eb10d48baca.png">


"Requested peers to connect" is high during the time
<img width="790" alt="Screen Shot 2021-11-10 at 16 55 18" src="https://user-images.githubusercontent.com/10568965/141091530-17dfbca3-a339-448e-8130-c993dc88d4de.png">

FINDNODES requests tend to high during that time too
<img width="797" alt="Screen Shot 2021-11-10 at 16 56 55" src="https://user-images.githubusercontent.com/10568965/141091723-289f56f2-1833-43f2-8003-9e6d282581ec.png">


There are a lot of Ping requests & Goodbye requests and Dial Errors
<img width="804" alt="Screen Shot 2021-11-10 at 16 58 18" src="https://user-images.githubusercontent.com/10568965/141091984-07d4acf0-d4bc-4035-856c-30954d71373b.png">

Peer Stats panel shows the busy time too
<img width="1573" alt="Screen Shot 2021-11-10 at 17 00 23" src="https://user-images.githubusercontent.com/10568965/141092301-e8c22198-8842-400b-925e-9e011dfaeeec.png">

**Comment by dapplion** [comment]
Thanks for looking into it. Maybe worth to go more in depth on that NodeJS code to understand when that can be a problem, it's really bad!

Meanwhile I'll prioritize #3402

**Comment by twoeths** [comment]
[1120_subscribeAllSubnets_prater.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/7574296/1120_subscribeAllSubnets_prater.cpuprofile.zip)

part of the issue is `AttestationError` was thrown a lot, it takes 4% of the cpu time, see #3448

**Comment by twoeths** [comment]
was able to catch a profile where we run ~~8~~ 6 epoch transitions within more than 2 minutes, we should work on this issue #3276 first

[1209_subscribeAllSubnets_Too_Many_Epoch_Transition.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/7684130/1209_subscribeAllSubnets_Too_Many_Epoch_Transition.cpuprofile.zip)

<img width="786" alt="Screen Shot 2021-12-09 at 17 41 11" src="https://user-images.githubusercontent.com/10568965/145381641-fb7160bd-3b12-4d45-ad4d-42b712cd5a18.png">

**Comment by twoeths** [comment]
not an issue anymore with new gossipsub + ssz + a lot of improvements
