### ISSUE TITLE
Add and Remove keys on active Validator

### ISSUE THREAD

**Issue by BeroBurny** [ChainSafe/lodestar#3422]
**Is your feature request related to a problem? Please describe.**

From developer standpoint when I initialize validator
``` ts
import {Validator} from "@chainsafe/lodestar-validator";

const validator = new Validator({...})
```

I'm able to `.start()` and `.stop()` it, but if i want to add another key (or remove existing one) to be part of validator I'm forced to stop current process delete validator object and initialize new one with another key what is not great solution on active one as user can miss attestation or block proposal.
To avoid this situation perfect solution is to add or remove dynamically private key on validator.

**Describe the solution you'd like**

Think that best way is to implement 2 methods

```ts
addSecretKey(secretKey: SecretKey): Promise<void>
```
think this is pretty staid forward what shroud do

<hr />

```ts
removeSecretKey(publicKey: string): {abortSignal: AbortSignal, wait(): Promise<void>}
```

calling this method should wait to finish all tasks in queue (in case of incoming block proposal we dont want to have unopposed blocks in network) and unsubscribe from sync committee (or stop subscribing not 100% sure how this part should work)
and there is `abortSignal` to imidietly stop validating for that key (image floppy disk and you pull it out), and `.wait()` if as developer want to do after gracefully removing key from active validator

**Describe alternatives you've considered**

Alternatives are only for removing secret keys

```ts
gracefullyRemoveSecretKey(publicKey: string): Promise<void>
```

```ts
immediatelyRemoveSecretKey(publicKey: string): Promise<void>
```

**Comment by dapplion** [comment]
@BeroBurny Would this API support your needs? https://github.com/ethereum/beacon-APIs/pull/151

We will implement it soon and it should also be available programatically

**Comment by dapplion** [comment]
Implemented in the keymanager API, keys can be removed now programmatically and via the HTTP API
