### ISSUE TITLE
kintsugi geth interop runGethPreMerge's execute payload api error "total difficulty not reached yet"

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#3427]
on the kintsugi branch of geth:
the `runGethPreMerge` scenario gives the error as documented:

https://github.com/ChainSafe/lodestar/blob/9239af8a9d1f7dfeba00d550cffaea0c0612068b/packages/lodestar/test/sim/merge-interop.test.ts#L481-L494

However it works fine with geth side ttd set to 0 in geth's pre-merge gensis (while lodestar's ttd is still > 0)

Resolution:

Figure out and fix the issue and have the successful run with geth's ttd >0 as well.

priminary investigation points that the geth is checking ttd on the terminal pow's parent, issue has been raised on discord

https://github.com/MariusVanDerWijden/go-ethereum/blob/kintsugi-spec/eth/catalyst/api.go#L466-L489

**Comment by MariusVanDerWijden** [comment]
Should be fixed by now

**Comment by g11tech** [comment]
> Should be fixed by now

thank you! :smile:
