### ISSUE TITLE
Light client updater: Incorrect finalized state

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#3428]
**Describe the bug**

See https://discord.com/channels/593655374469660673/621838504955084830/907737187288743956

https://github.com/ChainSafe/lodestar/blob/master/packages/light-client/src/server/LightClientUpdater.ts#L170

It appears that our finalized state, passed to `onFinalized` is always dialed to the epoch, rather than the post-state of the finalized checkpoint block.
So when there's skip slot(s) at the end of the epoch, we're going to be proving from a different state. The next sync committee branch will be wrong.

**Expected behavior**

The next sync committee branch should be created against the post-state of the finalized checkpoint block.

**Comment by philknows** [comment]
Let's double check to see if this persists.

**Comment by wemeetagain** [comment]
The light client updater code no longer relies on a finalized state.
See https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/chain/lightClient/index.ts#L194
