### ISSUE TITLE
Long block proposing times

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3442]
**Describe the bug**

Block proposing times are unstable causing missed proposed blocks

Prater:
![Screenshot from 2021-11-18 17-28-22](https://user-images.githubusercontent.com/35266934/142455950-bd1bd4ed-431f-42a3-bf06-d0889aaaf1df.png)

Mainnet:
![Screenshot from 2021-11-18 17-22-22](https://user-images.githubusercontent.com/35266934/142455983-bd5de520-6956-4215-a05e-96d73a568362.png)

**Expected behavior**

Propose blocks strictly in under 3 seconds. Ideally in less than 1 second always

**Todo**

First we need to understand better what's slow about proposing a block
- [ ] Add more histogram metrics on each step of proposing a block. See Lighthouse as a good example

**Comment by dapplion** [comment]
Could be related to https://github.com/ChainSafe/lodestar/issues/4002

We need to time proper metrics for:
- beacon node side strict block production times
- publish block delay time

**Comment by twoeths** [comment]
the issue was opened in a very old release, it's not an issue in 0.35.0

<img width="801" alt="Screen Shot 2022-05-11 at 08 41 06" src="https://user-images.githubusercontent.com/10568965/167751846-83715af0-3423-4ba7-b1f4-7517f9bb7b8c.png">

these statistics are consistent across mainnet nodes
