### ISSUE TITLE
Sync Committee attendance performance issue

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3443]
**Describe the bug**

In prater, when any validators join sync committee period, the performance is very bad. This maybe related to #3416 where we subscribe to all sync committee subnets with `subscribeAllSubnets` flag

On Nov 17, some validators joined the sync committee
<img width="1580" alt="Screen Shot 2021-11-19 at 10 06 08" src="https://user-images.githubusercontent.com/10568965/142558181-323cf971-0752-455c-b090-24cf9ff56cd8.png">

More FINDNODES dscv5 query were issues, more dial rate
<img width="1620" alt="Screen Shot 2021-11-19 at 10 09 18" src="https://user-images.githubusercontent.com/10568965/142558452-2d3333a0-b297-48ae-910e-e12303bfcb3b.png">

At the same time, there are a lot of Goodbye sent/received, a lot of ping/metadata/status request/response too
<img width="1621" alt="Screen Shot 2021-11-19 at 10 10 25" src="https://user-images.githubusercontent.com/10568965/142558579-6b0d38a1-f9f2-4f1c-bc6d-07eed286c0f9.png">

Gossip block is delayed a lot
<img width="1586" alt="Screen Shot 2021-11-19 at 10 07 07" src="https://user-images.githubusercontent.com/10568965/142558260-13022f7a-9105-4fd1-90ea-3d800060dc41.png">

**Expected behavior**

No performance issue

**Comment by twoeths** [comment]
This could also be linked to #2490 

When we dial a lot of peers, it's more likely we have to serve `beacon_blocks_by_range`

<img width="799" alt="Screen Shot 2021-11-19 at 15 37 07" src="https://user-images.githubusercontent.com/10568965/142591944-1984fa13-0f49-4601-a6ae-ab652b335fca.png">

**Comment by dapplion** [comment]
> This could also be linked to #2490
> 
> When we dial a lot of peers, it's more likely we have to serve `beacon_blocks_by_range`

Could be but I'll be surprised it had such an impact on performance, would be worth it to stay vigilant of our nodes and whenever we get selected again to participate in a sync committee take a CPU profile

**Comment by twoeths** [comment]
> vigilant

we can just do a hard code to always subscribe all sync committees and deploy to one of our servers

**Comment by twoeths** [comment]
issue is too old, lodestar can publish sync committee messages well with v1.2.1
