### ISSUE TITLE
Name objects and arrays where possible

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3445]
**Describe the bug**

When taking heap snapshots most of the memory is retained by literal objects and arrays. Where possible we should use classes or object constructors such that the object has a name. I did some tests and there's no extra memory cost

![Screenshot from 2021-11-19 22-29-45](https://user-images.githubusercontent.com/35266934/142694002-6c846192-ae8f-4dd4-97c2-b2aaf3ddda86.png)

**Expected behavior**

Help identify memory issues faster

**Comment by philknows** [comment]
This is a valuable improvement for debugging memory. Please assign @dapplion

**Comment by wemeetagain** [comment]
this is valuable information for debugging but this issue is not actionable as it is written
