### ISSUE TITLE
Architecture page out of date

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#3449]
**Describe the bug**

The "Beacon Node Module Architecture" page is outdated:

https://chainsafe.github.io/lodestar/design/architecture/

**Expected behavior**

It contains relevant information or is deleted.

**Comment by dapplion** [comment]
@wemeetagain I would be in favor of completely deleting it

**Comment by philknows** [comment]
Is there any benefit to updating it for new docs? Or should this just be scrapped completely?

**Comment by dapplion** [comment]
> Is there any benefit to updating it for new docs? Or should this just be scrapped completely?

I would scrape completely, if you agree please go ahead

**Comment by philknows** [comment]
Closing. Fixed with #3675.
