### ISSUE TITLE
Can't announce ENR udp and tcp port simultaneously

### ISSUE THREAD

**Issue by skylenet** [ChainSafe/lodestar#3462]
**Describe the bug**

Can't overwrite  TCP and UDP port on ENR when used together. There seems to be some problem when I use `--enr.udp`. The ENR record just becomes broken and doesn't  include the IP/TCP/UDP fields. If I just use `--enr.tcp` It will just announce the TCP port as expected. 

Running a node with the following flags:

```
--enr.ip=1.2.3.4
--enr.udp=40000
--enr.tcp=40000
```

**Expected behavior**

I would expect the ENR record of that node to have: 

```
ip: 1.2.3.4
udp: 40000
tcp: 40000
```

**Steps to Reproduce**

Run a node with the following flags and verify that the ENR record is set correctly:

```
--enr.ip=1.2.3.4
--enr.tcp=40000
```

Now run the same, but add the `--enr.udp=40000` flag, and verify that the ENR record is broken.

I've used the beacon api to get the ENR info: `/eth/v1/node/identity`

**Version**: 
Lodestar version=v0.32.0/master/+2/0f5ee0e5 (git), network=mainnet

**Comment by wemeetagain** [comment]
https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/network/nodejs/util.ts#L37-L38

~cc @dapplion do you know why we have this?~
It's from this: https://github.com/ChainSafe/lodestar/pull/1192

**Comment by skylenet** [comment]
Fixed via https://github.com/ChainSafe/lodestar/pull/5399
