### ISSUE TITLE
Use faster Ed25519 impl for gossip crypto

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3465]
@achingbrain has identified alternative implementations of Ed25519 crypto. This issue is a tracker to ensure we timely upgrade our deps once a faster impl lands. See benchmarks in https://github.com/libp2p/js-libp2p-crypto/pull/211

I don't have data right now to show but historically gossip crypto has appeared in CPU profiles taking ~5% of total CPU time in the main thread

TODO:
- [ ] Libp2p releases `libp2p-crypto`
- [ ] Bump dependency in `libp2p-noise` and release https://github.com/ChainSafe/js-libp2p-noise
- [ ] Bump dependency in Lodestar

**Comment by dapplion** [comment]
@mpetrunic does libp2p-noise must use libp2p-crypto to comply with some interface or can we just import any implementation that we want?

**Comment by paulmillr** [comment]
libp2p decided to drop switch to ed-wasm, see discussion here: https://github.com/libp2p/js-libp2p-crypto/pull/215

**Comment by dapplion** [comment]
> libp2p decided to drop switch to ed-wasm, see discussion here: [libp2p/js-libp2p-crypto#215](https://github.com/libp2p/js-libp2p-crypto/pull/215)

If I follow correctly the result has been to drop all PRs and stay on the pure-js impl right?

We should count how many ops Lodestar does per second since this has been a bottleneck for us.

**Comment by achingbrain** [comment]
For the record I'm not against switching to a WASM ed25519 implementation in the future, it's just that in the testing I did, it didn't seem to be a bottleneck.

If @dapplion is seeing evidence to the contrary then this is certainly something we can re-evaluate if some benchmarks can be created that reflect realistic workflows so we can measure the difference in implementations.

**Comment by dapplion** [comment]
Now we can use a faster implementation thanks to plug-gable crypto here https://github.com/ChainSafe/js-libp2p-noise/pull/133

**Comment by dapplion** [comment]
Sample impl of native version from @ShogunPanda

> If you want, I have sample implementation with sodium-native in https://github.com/web3-storage/ipfs-elastic-provider-bitswap-peer/blob/main/src/noise-crypto.js

**Comment by twoeths** [comment]
the current js implementation is way faster than `sodium-native` (probably due to the cost of calling native layer)

```
stablelib decrypt x 268,550 ops/sec ±1.05% (90 runs sampled)
sodium-native decrypt x 45,880 ops/sec ±2.47% (88 runs sampled)
stablelib encrypt x 259,846 ops/sec ±0.70% (92 runs sampled)
sodium-native encrypt x 39,432 ops/sec ±3.09% (82 runs sampled)
```

see https://github.com/ChainSafe/js-libp2p-noise/pull/161

**Comment by dapplion** [comment]
We are using a dedicated implementation for noise
