### ISSUE TITLE
libp2p-mplex decode performance issue

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3467]
**Describe the bug**

+ With `subscribeToAllSubnets()` flag, it takes 5% of cpu time to decode libp2p-mplex chunks

<img width="1484" alt="Screen Shot 2021-11-30 at 14 52 57" src="https://user-images.githubusercontent.com/10568965/144007214-c1752706-01e9-44b9-9a3f-bf8f032550f7.png">

+ 90% of the time was used to throw RangeError
<img width="890" alt="Screen Shot 2021-11-30 at 14 54 14" src="https://user-images.githubusercontent.com/10568965/144007375-d88a9eb5-445d-412c-bba6-05c5a9c812c1.png">

[1130_lodestar_subscribeAllSubnets_local.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/7623908/1130_lodestar_subscribeAllSubnets_local.cpuprofile.zip)

**Comment by dapplion** [comment]
Oh interesting, could you check the metrics to see if there were many invalid messages during the time that the CPU profile was taken? How could it be that we get sent so many invalid messages? Or the consumer code of this library is doing something strange and passing bad data to the decoder?

**Comment by twoeths** [comment]
@dapplion  it's by design, after decoding a chunk's header successfully, the `buffer` is consumed the whole length, and it has 0 length, and `varint.decode()` will just throw `RangeError` in that case. This happens 50% of the time `libp2p-mplex` uses `varint.decode()` in that function

<img width="1127" alt="Screen Shot 2021-11-30 at 15 04 52" src="https://user-images.githubusercontent.com/10568965/144009244-1fa5b047-e7b3-4279-959e-eecdcc67dc2f.png">

this could be a simple fix, will create a PR for it
