### ISSUE TITLE
Find proper types

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/lodestar#35]
We need to find proper typescript types for (or write them ourselves):
- [ x ] uint's
- [ x ] bits 
- [ x ] hash32

[David's library](github.com/ansermino/fixed-sized-numbers-ts/) should do the trick for uints. ~As for hash32 bits and bytes unsure.~

**Comment by Mikerah** [comment]
These types are not "native" types in any programming language as in most programming languages that are being used for sharding have to check inputs and outputs and define these types themselves. If you look at the ssz codebase (https://github.com/ChainSafeSystems/ssz-js), this is what was done. 

Note that hash32, in particular, is effectively bytes but with some caveats. Again, look through the ssz code.

**Comment by ansermino** [comment]
I have been experimenting with how we can enforce these types in typescript [here](https://github.com/ansermino/fixed-sized-numbers-ts). it's really just a wrapper for BigNumber that enforces size. Still early days but I think a construct like this is achievable and could make our lives easy. It could also be extensible for types like `hash32`.

**Comment by aunyks** [comment]
May seem ugly but I think an alias to `Array<Boolean>` would suffice for a `Bits` type.

**Comment by GregTheGreek** [comment]
@aunyks were discussing this in the currently open pr

**Comment by GregTheGreek** [comment]
I think we can close this per #62 which is now closed?
