### ISSUE TITLE
Chain params/constants generation/checking

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#351]
-write script to generate params file from
   - https://github.com/ethereum/eth2.0-specs/blob/dev/configs/constant_presets/mainnet.yaml
   - https://github.com/ethereum/eth2.0-specs/blob/dev/configs/constant_presets/minimal.yaml
- write unit test to check if current param values matches values in files

**Comment by mpetrunic** [comment]
@GregTheGreek @wemeetagain any better idea?

**Comment by wemeetagain** [comment]
Remove unused params
Make sure names match between yaml and our params

**Comment by ajoydas** [comment]
Updated links:
- https://github.com/ethereum/eth2.0-specs/blob/dev/configs/mainnet.yaml
- https://github.com/ethereum/eth2.0-specs/blob/dev/configs/minimal.yaml

**Comment by mpetrunic** [comment]
unstale

**Comment by mpetrunic** [comment]
unstale
