### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#3519]
**Is your feature request related to a problem? Please describe.**

We don't explicitly support Windows and we should!

**Describe the solution you'd like**

Lodestar likely works on Windows out of the box, or with minimal tweaking.
We should add e2e tests on Windows to ensure compatibility going forward.

**Comment by uink45** [comment]
Hi, I would like to run the lodestar light client demo locally on Windows. Is there a README file on how to run the demo in a local browser?

**Comment by dapplion** [comment]
> Hi, I would like to run the lodestar light client demo locally on Windows. Is there a README file on how to run the demo in a local browser?

Yes, please see the readme here https://github.com/ChainSafe/eth2-light-client-demo#consensus-lightclient-browser-demo

**Comment by philknows** [comment]
Users should use WSL on Windows. There is no plan to support Windows native development. We should include a section though on documentation for Windows users though. Please follow up on #5961.
