### ISSUE TITLE
Use memory db instead of libp2p metastore

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3521]
**Describe the bug**

libp2p metastore requires us to serialize and deserialize data to bytes. Since almost all data we persist in the metastore is useless after a restart, there's no need in persistence beyond memory.

It also causes https://github.com/ChainSafe/lodestar/pull/3520

**Comment by wemeetagain** [comment]
Aren't our peers' scores useful after a restart?

**Comment by dapplion** [comment]
> Aren't our peers' scores useful after a restart?

Hmm, right do we usually connect to the same set of peers we were connected previously? Would be nice to do some tests

**Comment by dapplion** [comment]
> Aren't our peers' scores useful after a restart?

Another approach would be to keep everything in memory and persist in bulk every once in a while and very shutdown.

**Comment by dapplion** [comment]
Current db is somewhat smart about when to flush to disk. If excessive serialization becomes an issue open an issue for that.
