### ISSUE TITLE
ETH1 Deposits as an npm package

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/lodestar#353]
Currently the deposit contract functionality works within the lodestsar repo. We have received a few requests on "how to use it", it's probably worth separating it out into its own repository and npm package.

**Comment by mpetrunic** [comment]
i  think it also needs a bit of love as currently it makes deposit for multiple validators from mnemonic. Would be better if it accepted keystore (unlocked with password)

**Comment by GregTheGreek** [comment]
That would be a great feature once we pull it out imo. I would hold features until we pull it out
