### ISSUE TITLE
Proposer LMD Score Boosting

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3535]
**Is your feature request related to a problem? Please describe.**

This is part of spec 1.1.6, see https://github.com/ethereum/consensus-specs/releases

**Describe the solution you'd like**

Follow https://github.com/ethereum/consensus-specs/pull/2730

**Comment by dapplion** [comment]
@g11tech Should be tackling this already.

Part of https://github.com/ChainSafe/lodestar/issues/3438
Part of https://github.com/ChainSafe/lodestar/issues/3506

**Comment by twoeths** [comment]
thanks for clarification 👍 , closing as it's part of other issues already
