### ISSUE TITLE
CL<>EL interop: Peers are getting downscored when EL errors on payload execution

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#3537]
While importing blocks, EL errors with various kind of errors (bad merkle state, internal error etc) as well as possible timeout/connection refused error.

The treatment of all these currently is that that block verification errors and the peer is downscored, which leads to downscoring/banning of peer and soon making lodestar loosing all peers and going out of sync! The lodestar doesn't find peers till the peerstore directory is removed and then the same cycle happens again (based on EL again erroring)

Expected:
The EL executePayload call should be try catched for these errors, and a separate status responded from executionEngine, which should log the error, but lodesstar shouldn;t penalize these peers and also accept this blocks with syncing.

However there is debate in the devnet debug group is that CLs should try discriminate these error (like treat merkle state error as invalid). Waiting till that discussion resolves.

Observed with: lodestar <> nethermind

**Comment by dapplion** [comment]
Oh good points! With downgrade do you mean downscore?

**Comment by g11tech** [comment]
> Oh good points! With downgrade do you mean downscore?

yes :slightly_smiling_face:

**Comment by twoeths** [comment]
lodestar<>geth could not maintain a good number of peers too

<img width="812" alt="Screen Shot 2022-01-05 at 12 13 36" src="https://user-images.githubusercontent.com/10568965/148163933-bda8908a-bbcd-4994-9ecb-7acf670fb0dc.png">

the main reason is lodestar sent goodbye requests to other nodes with "peer score too low"

<img width="804" alt="Screen Shot 2022-01-05 at 12 14 33" src="https://user-images.githubusercontent.com/10568965/148164071-5ae52e34-f32d-4e23-8ff8-4d6a5cf5b311.png">

@g11tech is this the same issue or not, do I need to search for any specific logs to confirm?

**Comment by g11tech** [comment]
@tuyennhv  yes, this is the same issue, I have cleared peerstore and restarted nodes, they seem to now have good peer count. Once this PR https://github.com/ChainSafe/lodestar/pull/3545 gets merged, peers shouldn't get penalized for EL malfunctions.
