### ISSUE TITLE
Migrate to libp2p-gossipsub and libp2p

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3548]
**Is your feature request related to a problem? Please describe.**

In libp2p-gossipsub 0.12.x, we have some improvement regarding caching peer score, accepting messages without computing peer score, fast message id cache and we want to use it in lodestar soon

**Describe the solution you'd like**

As a preparation for that:

+ Migrate libp2p from 0.32.4 to 0.35.x
+ Migrate libp2p-gossipsub from 0.11.1 to 0.12.x
+ Migrate libp2p-interface from 1.1.0 to 2.0.x

**Comment by twoeths** [comment]
https://github.com/libp2p/js-libp2p/issues/1073

**Comment by dapplion** [comment]
Warning! We must make sure that our gossip queues don't have conflicts with the native queues introduced in `libp2p-gossipsub` + `libp2p-interface`

**Comment by twoeths** [comment]
> Warning! We must make sure that our gossip queues don't have conflicts with the native queues introduced in libp2p-gossipsub + libp2p-interface

I suppose we continue overriding `_processMessages()` and `_processRpc()` to only use our own queues so that it does not have a performance impact to us

@dapplion  also as discussed in discord (maybe not part of this issue), I'd like to wrap `_processRpcMessage()` instead of `validate()` in our queues so that we don't waste time uncompressing message, getting message id and drop it in the end (when we have a performance issue, we drop 80% messages in our queue and it's redundant to compute `getMsgId()` there)

**Comment by dapplion** [comment]
> @dapplion also as discussed in discord (maybe not part of this issue), I'd like to wrap _processRpcMessage() instead of validate() in our queues so that we don't waste time uncompressing message, getting message id and drop it in the end (when we have a performance issue, we drop 80% messages in our queue and it's redundant to compute getMsgId() there)

Yeah let's do that

**Comment by twoeths** [comment]
Latest build issue: https://github.com/libp2p/js-libp2p/issues/1088

**Comment by twoeths** [comment]
The above issue is gone with latest libp2p master branch
