### ISSUE TITLE
Build docker image in CI

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#355]
We want our docker image built when the master branch gets updated.
Ideally it will not effect normal CI times.

**Comment by mpetrunic** [comment]
@GregTheGreek suggested we use automated dockerhub builds. I have ready branch iwth circleci if that doesn't work for some reason

**Comment by mpetrunic** [comment]
issue is still valid, image needs to be built in dockerhub rather than in ci
