### ISSUE TITLE
Gossip fast message id cache time

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3552]
**Is your feature request related to a problem? Please describe.**

Once we migrate to gossipsub 0.12.x and this is done https://github.com/ChainSafe/js-libp2p-gossipsub/issues/170, consider using fast message id cache time to 33 slots and study its memory usage as in lighthouse https://github.com/sigp/lighthouse/blob/fff01b24ddedcd54486e374460855ca20d3dd232/beacon_node/eth2_libp2p/src/config.rs#L36

**Comment by dapplion** [comment]
@tuyennhv Is this still relevant after Gossipsub refactor (close otherwise)? What param are we using now?

**Comment by twoeths** [comment]
@dapplion  right now lodestar follows the spec to have `seenTTL` as 385s (`=550 * 0.7s`) https://github.com/ChainSafe/lodestar/blob/1f1ef67a06a9332db1b524ad1ac1f2a1ae05c2bf/packages/beacon-node/src/network/gossip/gossipsub.ts#L104

that's equivalent to `32 slots (propagation range)` * `12 SECONDS_PER_SLOT` + `2 * MAXIMUM_GOSSIP_CLOCK_DISPARITY_SEC (0.5s)` which is perfect to filter duplicate gossip attestations in the last 32 slots
