### ISSUE TITLE
Add cli option to read bootnode ENRs from file

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3558]
The functionality is there but only triggered for known networks. Expose option to read and parse bootnode ENRs file.

**Spec**

Add flag `--bootnodesFile` in the beacon command, specifically here https://github.com/ChainSafe/lodestar/blob/240085facb5e542defd8d190d5d2a0abbc574ecf/packages/cli/src/cmds/beacon/options.ts#L156

This flag's path must be processed with the same path manipulation logic from `getBeaconPaths()` https://github.com/ChainSafe/lodestar/blob/240085facb5e542defd8d190d5d2a0abbc574ecf/packages/cli/src/cmds/beacon/paths.ts#L29

Parsing logic may be based on https://github.com/ChainSafe/lodestar/blob/240085facb5e542defd8d190d5d2a0abbc574ecf/packages/cli/src/networks/index.ts#L67

and be able to parse any of this file formats
```
### Ethereum Node Records
- enr:-KG4QOWkRj
```
```
### Ethereum Node Records
- "enr:-KG4QOWkRj"
```
```
enr:-KG4QOWkRj
```
```
"enr:-KG4QOWkRj"
```

Parsed bootnode ENRs must be "injected" into the beacon option `network.discv5.bootEnrs` like done here https://github.com/ChainSafe/lodestar/blob/240085facb5e542defd8d190d5d2a0abbc574ecf/packages/cli/src/networks/index.ts#L50

If `bootnodesFile` is specified it MUST overwrite the bootnodes injected by https://github.com/ChainSafe/lodestar/blob/240085facb5e542defd8d190d5d2a0abbc574ecf/packages/cli/src/networks/index.ts#L41

**Tests**

- Test parsing of sample files with at least the four formats outlined above
- Ensure param overwrite rules work as expected and the resulting `beaconNodeOptions` object contains the target bootnode ENRs

**Comment by Evalir** [comment]
Happy to take on this issue! Will be working on a PR 👍
