### ISSUE TITLE
Investigate possible EventEmitter memory leak

### ISSUE THREAD

**Issue by dadepo** [ChainSafe/lodestar#3569]
**Describe the bug**

While trying to run lodestar on local testnet following the documentation [here](https://chainsafe.github.io/lodestar/usage/local/), I ran into complications which led to me to create this issue [here](https://github.com/ChainSafe/lodestar/issues/3568).

Part of what I noticed, while trying to get Lodestar running in the logs was this error:

> (node:15159) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 chainHead listeners added to [ValidatorEventEmitter]. Use emitter.setMaxListeners() to increase limit

On a quick investigation, the issue seems to be coming from [this part](https://github.com/ChainSafe/lodestar/blob/c384b36a1b52d8607842b363e1f07f6ccc5d6004/packages/validator/src/services/attestation.ts#L50) of the code.

Two promises are being raced. One of the promises `this.waitForBlockSlot(slot)`, sets event listeners. As can be seen [here](https://github.com/ChainSafe/lodestar/blob/c384b36a1b52d8607842b363e1f07f6ccc5d6004/packages/validator/src/services/attestation.ts#L64). 

On my local, it seems the promise with the event listener never wins this race, and never is the one that gets resolved, hence the listener is never removed, hence leads to the the warning message that pops up in the log.

**Expected behavior**

Preferably not have the EventEmitter memory leak warning. 

Hence:

- Confirm if this is indeed an issue
- Confirm if this can only practically show up in the local testnet - hence severity will be low
- If need be, see how this can be resolved.

**Comment by dapplion** [comment]
Marking as high as we should start taking very seriously our log hygiene if we want any adoption. 

Lodestar logging

> (node:15159) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 chainHead listeners added to [ValidatorEventEmitter]. Use emitter.setMaxListeners() to increase limit

**IS NOT ACCEPTABLE**, Either use https://nodejs.org/api/events.html#emittersetmaxlistenersn or change to a different pattern
