### ISSUE TITLE
Cannot dial peers due to number of addresses

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3576]
**Describe the bug**

During the non-finality time of prater, I see we have some strange req dial errors

```
dial with more addresses than allowed
```

or
```
The dial request has no valid addresses
```

All of these errors come from our `beacon_blocks_by_root` requests and it'll decrease peer score -10 each time

**Expected behavior**

No error

**Comment by twoeths** [comment]
We can reach some peers prior to the error, for example with peer `16...6C1Q4E`:

```
5179:Jan-06 03:37:12.735 [NETWORK]       verbose: Req  error method=beacon_blocks_by_root, encoding=ssz_snappy, client=Lighthouse, peer=16...6C1Q4E, requestId=1844 code=REQUEST_ERROR_TTFB_TIMEOUT
5190:Jan-06 03:37:12.741 [NETWORK]       verbose: Req  error method=beacon_blocks_by_root, encoding=ssz_snappy, client=Lighthouse, peer=16...6C1Q4E, requestId=1845 code=REQUEST_ERROR_TTFB_TIMEOUT
5201:Jan-06 03:37:12.748 [NETWORK]       verbose: Req  error method=beacon_blocks_by_root, encoding=ssz_snappy, client=Lighthouse, peer=16...6C1Q4E, requestId=1846 code=REQUEST_ERROR_TTFB_TIMEOUT
```

then after some minutes
```
5292:Jan-06 03:44:14.770 [NETWORK]       verbose: Req  error method=beacon_blocks_by_root, encoding=ssz_snappy, client=Lighthouse, peer=16...6C1Q4E, requestId=1861 code=REQUEST_ERROR_DIAL_ERROR, error={"message":"dial with more addresses than allowed"}
```
then
```
5564:Jan-06 03:44:14.889 [NETWORK]       verbose: Req  error method=beacon_blocks_by_root, encoding=ssz_snappy, client=Unknown, peer=16...6C1Q4E, requestId=1870 code=REQUEST_ERROR_DIAL_ERROR, error={"message":"The dial request has no valid addresses"}
```

looks like we add/remove peer addresses in the libp2p address store during that time

**Comment by dapplion** [comment]
That's so weird, might be useful to dig into libp2p source

**Comment by wemeetagain** [comment]
https://github.com/libp2p/js-libp2p/blob/master/src/dialer/index.js#L219

**Comment by dapplion** [comment]
What's `maxAddrsToDial` in our case? How it can be more than 1?

**Comment by wemeetagain** [comment]
By default, its https://github.com/libp2p/js-libp2p/blob/master/src/constants.js#L7
I think we're using the default

**Comment by dapplion** [comment]
Closing issues for specific incidents on old versions of Lodestar, please re-open if it happens with latest stable
