### ISSUE TITLE
Fix changelog generation in releases

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3581]
**Describe the bug**

Current generated changelogs appear very broken, see https://github.com/ChainSafe/lodestar/releases/tag/v0.33.0
- Only one closed issue is included
- No PRs are included

**Expected behavior**

Changelog generator should print a useful changelog like https://github.com/ChainSafe/lodestar/releases/tag/v0.30.0

- Display all closed issues between releases
- Included all closed PRs between releases
- New: Since we moved to our new release strategy, the release commit is not in the master branch. Maybe the changelog generator has issues handling that
- New: Since we now tag beta versions we don't want the changelog to display changes split into beta and non-beta tags. All items should appear under a single header `v0.33.0 (data)`

**Comment by philknows** [comment]
Our new release process is detailed within #3036 for your reference as well @dadepo
