### ISSUE TITLE
牛来速归

### ISSUE THREAD

**Issue by zhubinsheng** [ChainSafe/lodestar#3582]
**Describe the bug**

**Expected behavior**

**Steps to Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

- OS: 
- Version: 
- Branch: 
- Commit hash:

**Comment by philknows** [comment]
![146453557-e13fc642-0721-48ca-bc9f-5f7fdc0f299b.jpg](https://images.zenhubusercontent.com/60eef82e1a0a36f72c3e76a4/49bdfd47-9cfe-4b3d-8846-2025f2d5fccf)
