### ISSUE TITLE
Do not downscore peers due to timeout error if node is busy

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3584]
**Is your feature request related to a problem? Please describe.**

When our node is super busy, we can't even handle `ping` message on time:

```
grep -e "message=Timeout" -rn beacon*-05.log  | grep "Resp error method=ping" | wc -l
122
```

at that time, our clock is drift, it's our own issue and we should not downscore peers if our p2p requests return timeout error. Found a lot of request timeout errors from our log:

```
grep -e "code=REQUEST_ERROR_DIAL_TIMEOUT" -rn beacon*-05.log | wc -l
138
grep -e "code=REQUEST_ERROR_TTFB_TIMEOUT" -rn beacon*-05.log | wc -l
25
grep -e "code=REQUEST_ERROR_RESP_TIMEOUT" -rn beacon*-05.log | wc -l
6
grep -e "code=REQUEST_ERROR_REQUEST_TIMEOUT" -rn beacon*-05.log | wc -l
29
```

which result in losing a lot of peers

<img width="787" alt="Screen Shot 2022-01-07 at 14 24 44" src="https://user-images.githubusercontent.com/10568965/148507498-b6bd7aa2-dab4-488e-b311-5db2fb51297f.png">

**Describe the solution you'd like**

+ If we can't handle ping requests on time, don't penaltizing peers for request timeout errors in the next x minutes.

**Describe alternatives you've considered**

+ Detect clock drift issue in the node and don't penaltizing peers for request timeout errors at that time

**Additional context**

This issue happens during prater non-finality time, some nodes have only 2 peers and have to wait for 1 day to get more peers to recover.

**Comment by dapplion** [comment]
This is one is very tricky because we need to differentiate between a real timeout and a timeout caused by us. Measuring our internal delay may be a good option but still a bit sketchy.

The real question is: Why did the node get so busy in the first place?

**Comment by twoeths** [comment]
> The real question is: Why did the node get so busy in the first place?

one reason is the high memory usage at that time causing long epoch transition

<img width="804" alt="Screen Shot 2022-01-07 at 16 46 50" src="https://user-images.githubusercontent.com/10568965/148525743-1c029c73-4455-4dcc-aa75-8a9e29c8b54f.png">

**Comment by dapplion** [comment]
Probably part of the I/O lag issue

**Comment by dapplion** [comment]
Closing as we are working on reducing node load. Won't be easy to differentiate malicious behavior from us being overloaded
