### ISSUE TITLE
Performance issue with discv5 Lookup service

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3588]
**Describe the bug**

This happens in contabo-19 with `subscribeAllSubnets` flag: the Lookup service onSuccess takes 55% of cpu time after taking a profile in 5 minutes

<img width="1275" alt="Screen Shot 2022-01-08 at 13 50 42" src="https://user-images.githubusercontent.com/10568965/148634871-aa212ead-f47d-4782-8d02-cb9293c1833d.png">

Specifically, it's the sort function just to get the closest peer:
<img width="950" alt="Screen Shot 2022-01-08 at 13 52 48" src="https://user-images.githubusercontent.com/10568965/148634914-0434c681-ef41-40ca-88db-065e2a7bd7ad.png">

at this time, it's a map with 3504 entries

**Expected behavior**
+ Do a single for loop to get closest peer
+ Not sure if it's an issue in new discv5

**Steps to Reproduce**

+ Run node with `subscribeAllSubnets` flag and take profile

**Comment by twoeths** [comment]
on the other regular node without `subscribeAllSubnets` flag, it takes 6.7 % cpu time at the same line of code mentioned above

**Comment by dapplion** [comment]
CC @wemeetagain Discv5 needs benchmark testing asap

**Comment by wemeetagain** [comment]
Thats from an older version of discv5, current master precalculates closestPeers
https://github.com/ChainSafe/discv5/blob/master/src/kademlia/lookup.ts#L150

**Comment by dapplion** [comment]
> Thats from an older version of discv5, current master precalculates closestPeers https://github.com/ChainSafe/discv5/blob/master/src/kademlia/lookup.ts#L150

Can you make sure that fix landed in Lodestar master?

**Comment by twoeths** [comment]
on a regular node with low peer count, this issue takes 24% of the cpu time
<img width="1476" alt="Screen Shot 2022-01-20 at 09 54 20" src="https://user-images.githubusercontent.com/10568965/150263885-3b9b190f-fc19-4561-932b-6aa0853979f0.png">
