### ISSUE TITLE
balances are not populated after genesisBuilder

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3592]
**Describe the bug**

Running Gnosis Beacon Chain and building the state from genesis the resulting state was incorrect because state.balances was empty. Apparently pushing to state.balanceList the changes are not propagated to state.balances. May they refer to different trees?

**Expected behavior**

Populate 

**Steps to Reproduce**

- Run Gnosis Beacon Chain from Genesis, guide to TBD

or

- In a unit test, create an empty CachedBeaconState
- push to state.balanceList and
- query state.balances

**Comment by twoeths** [comment]
@dapplion can you look into PR #3602, there should be some different setup to reproduce the issue?

**Comment by dapplion** [comment]
@tuyennhv Yeah I haven't had time to create a reproducible scenario, can you try with running the genesis code?

**Comment by dapplion** [comment]
genesisBuilder code has been refactored since this issue
