### ISSUE TITLE
Using Lerna for package management

### ISSUE THREAD

**Issue by Mikerah** [ChainSafe/lodestar#36]
As we are converting this repository to typescript (and our other repos) and as we continue to build out the tooling necessary to implement our client, we will see an increase in the usage of packages in this repository. Currently, the repo is small and we have few (if any) outside packages in use and is not much of a concern. However, I think starting a discussion and thinking about what tools we can use to improve managing libraries early is important so that we have less surprises down the road.

I discovered this tool called [Lerna](https://github.com/lerna/lerna) that is being used for js-libp2p for managing JS projects with multiple packages.

Any thoughts?

CC'ing @GregTheGreek, @priom, @ansermino

**Comment by GregTheGreek** [comment]
@Mikerah Familiar with Lerna, what packages are you thinking of adding into the project, SSZ? Do we want to mono repo this?

**Comment by Mikerah** [comment]
In the future, SSZ, BLS-js, Gossipsub-js. The reasoning is we will have these separate repos as their own packages but managing all of them will be a hassle as this gets bigger. The main reasons for why we wouldn't want to monorepo this, in my opinion, is for maintenance and onboarding others.

If we do decide we don't want to monorepo then this tool is not useful. I just want to start this discussion early so that we can easily add appropriate documentation.

**Comment by ansermino** [comment]
Also makes sense for solidity vs beaconChain!

**Comment by GregTheGreek** [comment]
Not sure we really need lerna?

**Comment by Mikerah** [comment]
I think at this point, by looking at how we have decided to work, it doesn't seem useful. I am closing this issue. If someone wants to open it again, feel free to do so.
