### ISSUE TITLE
Suppress non-harmful error logs of the backfill sync

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#3605]
A user raised an alarm in discord regarding some harmless network sync logs. Upon reflection it was decided to suppress some of these logs:

https://discord.com/channels/593655374469660673/593655641445367808/930449615340339231.

Desired outcome: Silence some of the non-critical logs of the Backfill sync in line with the above discord communication.

**Comment by dapplion** [comment]
Closing until refactoring backfill sync
