### ISSUE TITLE
Remove I prefix from types that are not really interfaces

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3652]
A linting rule has forced many types into having an I prefix when they don't represent a class interface. Overall this I pattern in a legacy approach ported from Java that doesn't really help too much in the current paradigm of lodestar

**Todo**:
- [ ] Remove lint rule forcing I prefix
- [ ] Search and replace type names prefixed by I that do NOT have a class representation. For example: remove from `IBeaconConfig` do NOT remove from `IBeaconChain`

**Comment by philknows** [comment]
@dapplion, although this is something we are working towards, can I remove this style requirement from `contribution.md` then?

**Comment by dapplion** [comment]
> @dapplion, although this is something we are working towards, can I remove this style requirement from `contribution.md` then?

Oh, yes please

**Comment by nflaig** [comment]
Resolved by https://github.com/ChainSafe/lodestar/pull/5145
