### ISSUE TITLE
Website Relaunch Planning

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#3653]
This issue is to collect and collaborate on ideas to include with our new website relaunch for ~April with the help of ChainSafe's design team. During the January 21 planning meeting, some ideas were brought forward:

- Node operators running Lodestar
- Some additional metrics
- What are some of our unique propositions compared to the other clients?
- Accessibility of Typescript (browser-friendliness/compatibility, large community of developers)
- Light client focus (browser-based decentralized applications)

**Comment by wemeetagain** [comment]
I'd suggest we try to get an update on this so we're on track for syncing this with our v1.0 if possible

**Comment by philknows** [comment]
[New website is launched](https://lodestar.chainsafe.io). Feedback can be fed off Github issues or created per implementation.
