### ISSUE TITLE
Skip serializing blocks when persisting to db

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3657]
**Is your feature request related to a problem? Please describe.**

A profile from contabo-17 which has low peer count shows that it takes 8% to serialize blocks due to Backfill sync:
<img width="1224" alt="Screen Shot 2022-01-22 at 17 09 02" src="https://user-images.githubusercontent.com/10568965/150634274-2773834b-4f8b-482f-bae8-06cb524e78f8.png">

**Describe the solution you'd like**

When fetching blocks from p2p, we already have binary data, we should be able to use that to persist to db without having to serialize() again

**Comment by twoeths** [comment]
it also takes 9% of cpu time to do `hashTreeRoot()`
<img width="1250" alt="Screen Shot 2022-01-22 at 17 17 23" src="https://user-images.githubusercontent.com/10568965/150634508-b46bd5b1-8342-41a3-8790-345480a242ec.png">

[ 0122_contabo_17_backfill_serialize.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/7918107/0122_contabo_17_backfill_serialize.cpuprofile.zip)

**Comment by dapplion** [comment]
To mitigate this issue we could slow down Backfill sync, such that only N blocks are hashed every X seconds to even out the load.

Also keeping the binary blob around to prevent re-serialization is a very nice trick easy to implement now

**Comment by g11tech** [comment]
> To mitigate this issue we could slow down Backfill sync, such that only N blocks are hashed every X seconds to even out the load.

should we expose this as a configurable param with a hidden cli arg?

**Comment by twoeths** [comment]
> should we expose this as a configurable param with a hidden cli arg?

year I prefer that. Also should we run this in a separate worker thread?

**Comment by dapplion** [comment]
> Also should we run this in a separate worker thread?

Actually maybe! I think this is a completely independent process that given the initial initial conditions it does not require communication with the main thread at all. However, is our database thread safe? Can it handle multiple writes from different workers?

**Comment by twoeths** [comment]
there are other Backfill Sync performance issues mentioned in https://github.com/ChainSafe/lodestar/issues/3732#issuecomment-1032323266

**Comment by g11tech** [comment]
should i remove the bytes caching bit from this PR (which we can add once ssz v2 PR is in): https://github.com/ChainSafe/lodestar/pull/3669, it will save the costs of doing hashTreeRoot for parent/child relationship validation (about 8% CPU as previously profiled by @tuyennhv ).
Also one will be able to specify the batchSize on the terminal to reduce any adverse impact of backfill
