### ISSUE TITLE
Use `node:*` import protocol for safer module resolution

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3664]
See https://nodejs.org/api/esm.html#esm_node_imports

Forces a specific import to be loaded exclusively as a built-in NodeJS library. Current imports `"fs"` can be overwritten by a malicious party if it manages to add a node_modules package with the same name.

:+1: security

**Comment by johnomarkid** [comment]
This looked like a good first issue so I put up a PR [here](https://github.com/ChainSafe/lodestar/pull/3667). However, looks like I need approval for the workflows to run. Would also love any feedback 👍

**Comment by ghost** [comment]
This looked like a good first issue so I put up a PR [here](https://github.com/ChainSafe/lodestar/pull/3667). However, looks like I need approval for the workflows to run. Would also love any feedback 👍
