### ISSUE TITLE
Revisit peer discovery related configurations

### ISSUE THREAD

**Issue by dadepo** [ChainSafe/lodestar#3673]
**Is your feature request related to a problem? Please describe.**

While working on issue #3568, I noticed a couple of things not consistent or confusing regarding how some peer discovery settings are configured and used. 

For example:

- We configure the libp2p node to use Bootstap and MDN as peer discovery mechanism but we essential switch it off by setting both `peerDiscovery.autodial` and `connectionManager.autodial` to off. Is it not better (less confusing) to remove the peer discovery configurations, if it is not going to be used and handle discovery and peer dialling in code as we are doing in the `discover.ts`?
- It seems `network.discv5.enabled` is not being used in the code (at least I could not find where it is being used) Confirm if it is used. If not, should it be used to determine if to connect to peers based on `network.discv5.bootEnrs`? or it has another purpose?
- What is the difference between `network.bootMultiaddrs` and `network.discv5.bootEnrs`. Is `network.bootMultiaddrs` now redundant? and can it be removed?

**Describe the solution you'd like**

Look into the questions raised above, and work on any follow up tasks if required (code changes, update to documentation etc)

**Comment by dapplion** [comment]
Good points! I think all the inconsistencies come from consecutive updates which never fully cleaned up the options. Feel free to propose a new set of options that are tidy and make sense, it's confusing even to me.

- `network.bootMultiaddrs`: initial libp2p connections.
- `network.discv5.bootEnrs`: initial discv5 connections.

**Comment by dapplion** [comment]
Not applicable after 2022 refactors
