### ISSUE TITLE
Implement CL spec 1.1.9 - `Semantic Dispute`

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#3677]
A new spec code named [`Semantic Dispute` (version `1.1.9`)](https://github.com/ethereum/consensus-specs/releases/tag/v1.1.9) is out

Implement the same in lodestar.
- [x] Bellatrix changes
  - [x]  https://github.com/ethereum/consensus-specs/pull/2808 (Already implemented for previous 0.0.5 spec of EL engine
  - [x]  https://github.com/ethereum/consensus-specs/pull/2817
  - [x] Optimistic Sync spec 
    - [x] https://github.com/ethereum/consensus-specs/pull/2770 
    - [x] https://github.com/ethereum/consensus-specs/pull/2820
- [x] Light client
  - [ ] Tidying light client specs 
    - [x] https://github.com/ethereum/consensus-specs/pull/2798
    - [x] https://github.com/ethereum/consensus-specs/pull/2797
  - [x] https://github.com/ethereum/consensus-specs/pull/2796

**Comment by dapplion** [comment]
@g11tech Can you link the PRs instead of just referencing the numbers? Helps to navigate quicker to the context
