### ISSUE TITLE
Add good full coverage beacon API tests

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3682]
**What is your question?**

Current tests for the beacon API are of sub-optimal quality:
- Very limited coverage
- No assurance that all and future new endpoints are tested
- Require import stubbing
- Extensive use of brittle stubs: which require big diffs when modifying unrelated cost.

In my subjective opinion the current test suite has a very high cost of maintenance with very little return in ensuring the API is correct.

**Proposed solution**

Proper tests for a the beacon API should:
- Have full coverage
- Ensure programmatically that all endpoints current and future are tested
- Be tested against a full BeaconChain instance without stubbing and with real data. We are already doing this for BeaconChain validation and such data is extremely fast to produce and to run tests against.

**Comment by dapplion** [comment]
More disabled tests

https://github.com/ChainSafe/lodestar/blob/5d086b58a20f57c69f1d2cc90d5bf785f851f535/packages/lodestar/test/unit/api/impl/beacon/state/fork.test.ts#L9-L10

https://github.com/ChainSafe/lodestar/blob/5d086b58a20f57c69f1d2cc90d5bf785f851f535/packages/lodestar/test/unit/api/impl/beacon/pool/pool.test.ts#L25-L26

https://github.com/ChainSafe/lodestar/blob/5d086b58a20f57c69f1d2cc90d5bf785f851f535/packages/lodestar/test/unit/api/impl/debug/index.test.ts#L20-L21

https://github.com/ChainSafe/lodestar/blob/5d086b58a20f57c69f1d2cc90d5bf785f851f535/packages/lodestar/test/unit/chain/factory/block/blockAssembly.test.ts#L21-L22

**Comment by wemeetagain** [comment]
We now have oapi schema compliance tests that ensure validity of request/response data shapes and proper support of headers, status codes, etc. This is a good halfway solution.
Closing this for now
