### ISSUE TITLE
Docker containers on Docker Hub for x64, arm64, and with a single multi-arch manifest that contains both

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#3692]
**Is your feature request related to a problem? Please describe.**

Required for Rocketpool implementation.

**Describe the solution you'd like**

Docker containers on Docker Hub for x64, arm64, and with a single multi-arch manifest that contains both.

**Comment by philknows** [comment]
We need to upstream changes from blst-ts before closing.

**Comment by dapplion** [comment]
> We need to upstream changes from blst-ts before closing.

Linking current blocker https://github.com/ChainSafe/blst-ts/pull/59

**Comment by philknows** [comment]
Was merged. Ready to close @dapplion ?

**Comment by dapplion** [comment]
Changes still not live in lodestar. Requires a release in blst-ts then a version bump here in the mono-repo. @dadepo could you do the PRs if avail?

**Comment by dadepo** [comment]
Sure. I'll get to it today
