### ISSUE TITLE
Implementing and calling prepare_beacon_proposer and providing `suggestedFeeRecipient` to the BN

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#3693]
Beacon node needs to provide suggestedFeeRecipient which could be a validator specific field. Since [timing preparePayload](https://github.com/ChainSafe/lodestar/issues/3488 ) could be an independent operation from produceBlock api call by the validator, the BN needs to be aware.

How this can be achieved is in a bit of flux with the debate over if its Beacon/Validator driven. A [`prepare_beacon_proposer endpoint`](https://github.com/ethereum/beacon-APIs/pull/178) has been suggested for the same.. However some issues/race conditions have come up(https://github.com/ethereum/beacon-APIs/issues/187)

Track and discuss how to best implement this in lodestar.

**Comment by philknows** [comment]
Leaving a reference here for the current two implementations by Lighthouse and Teku:

Teku implementation: https://github.com/ConsenSys/teku/pull/4894
Lighthouse implementation: https://github.com/sigp/lighthouse/pull/2924
