### ISSUE TITLE
Beacon HTTP API slow response times

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3694]
**Describe the bug**

The Beacon HTTP API takes always > 2 sec to complete any request even for endpoint that don't require any processing.

We must investigate what is causing this delay:
- Node to busy?
- Some logic bug?
- Fastify?
- NodeJS itself?

**Expected behavior**

Respond to API requests in < 100ms times

**Steps to Reproduce**

Run lodestar beacon

```
time curl localhost:9596/eth/v1/beacon/headers/head
```

**Comment by twoeths** [comment]
the state transition takes 1s-2s depending on the node so at least it'll take that amount of time for the node to finish the api when that happens

**Comment by dapplion** [comment]
- Likely caused by https://github.com/ChainSafe/lodestar/issues/4002

**Comment by dapplion** [comment]
Non actionable issue directly. We are working on reducing main thread load an watching REST times closely
