### ISSUE TITLE
Remove the network cli option from the dev command 

### ISSUE THREAD

**Issue by dadepo** [ChainSafe/lodestar#3695]
**Is your feature request related to a problem? Please describe.**

In the PR #3672, @g11tech suggested that may be `network` option can be removed from the dev cli options, so that it will throw error if someone even tries to specify. Which makes sense because using the `network` option in local devnet, does nothing.

**Describe the solution you'd like**

As suggested: Remove the `network` option from dev cli, and throw error if someone even tries to specify.

**Comment by dapplion** [comment]
> Remove the network option from dev cli, and throw error if someone even tries to specify.

Both options sound good to me. but since network is a global option it's not easy to remove (I think)
