### ISSUE TITLE
Distributing WS checkpoints

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#3696]
On a tele discussion thread with lighthouse team, it surfaced that to make the network safer and robust (from a long range attack perspective), ws checkpoints should be distributed by the clients team

- published on the client websites
- available through announcement channels on discord/twitter
- baked into clients releases which could be "forward synced"/validated even when user syncs from genesis without providing any checkpoint

Easy way to setup would be to host such a mechanism: https://github.com/adiasg/eth2-ws-provider to act as the source.

**Comment by philknows** [comment]
IRT this discussion, it would be good to liaise with some of the other client teams to see how we can go about doing this. 

- Publishing checkpoints on our domain or other trusted channels (Discord/Twitter) seem to be a good idea to ensure we're all using correct checkpoints. 

- Not much consensus on baking checkpoints here as we shouldn't be making the determination of a "correct chain" for our users. 

- Not entirely sure about utilizing a eth2-ws-provider as it's another vector of attack. Can use more discussion on this one and how it works so we can mitigate any centralized points of failure. 

- We can have some non-default flag like `--trust-lodestar-ws-checkpoint` as suggested by @wemeetagain

**Comment by dapplion** [comment]
After trying for +1y we don't have bandwidth for this currently
