### ISSUE TITLE
Missing bellatrix spec tests

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3699]
**Describe the bug**

At least the transition tests for bellatrix are not run

https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/test/spec/bellatrix/transition.test.ts

Was this file created to skip the coverage detection? If so our current coverage tracker for spec tests is too weak

**Expected behavior**

- Run all spec tests
- Better coverage detection for spec tests

**Comment by dapplion** [comment]
@g11tech Please if you can add coverage immediately for bellatrix tests and I can work on the coverage tracker

**Comment by g11tech** [comment]
> @g11tech Please if you can add coverage immediately for bellatrix tests and I can work on the coverage tracker

Already had this in kitty: https://github.com/ChainSafe/lodestar/issues/3541, let me pick this up on priority :+1: :slightly_smiling_face:

**Comment by dapplion** [comment]
Duplicate of https://github.com/ChainSafe/lodestar/issues/3541
