### ISSUE TITLE
Using Renovate for keeping packages up to date

### ISSUE THREAD

**Issue by Mikerah** [ChainSafe/lodestar#37]
This isn't much of an issue at the moment, but any dependencies that we will be adding to this repo will need to be updated regularly. The Prysmatic Labs team uses Renovate to keep their packages up to date. The main issue I have with this is that it may break the code due to API changes,etc of a particular package.

Should we manually update packages in order to easily spot code breaks or should we use something like Renovate to automatically do it for us?

CC'ing @GregTheGreek, @priom, @ansermino

**Comment by GregTheGreek** [comment]
This should be done manually. 

A tool to let us know theres a new version may be handy.

**Comment by GregTheGreek** [comment]
Thoughts? @priom @wemeetagain @GregTheGreek @ansermino
