### ISSUE TITLE
Investigate: Startup behaviour of other CL clients especially in a post-merge world

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#3717]
Lodestar restarts from last finalized state written on DB, which could be multi epoch behind the last head it synced. This has lead to some invalidation of our assumptions on how CL <> EL interactions work.
For e.g. lodestar's fcU calls "resets/reverts" the connected EL's head to hundereds of blocks behind which caused some [eth1 tracker issues](https://github.com/ChainSafe/lodestar/issues/3674).

Investigate the behavior of other CLs on restart and if possible mechanisms they use to achieve the same.

**Comment by dapplion** [comment]
Closing for https://github.com/ChainSafe/lodestar/issues/4000
