### ISSUE TITLE
Remove deepmerge util

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3758]
**Describe the bug**

Unnecessary and breaks things since ssz types can't be YOLO modified the way deepmerge does

**Comment by dapplion** [comment]
Also introduces the risk of prototype pollution

**Comment by wemeetagain** [comment]
@nflaig is this still relevant?

**Comment by nflaig** [comment]
> ssz types can't be YOLO modified the way deepmerge does

not clear what code this is/was referencing, but we are not using deepmerge on ssz types right now and we don't use it on untrusted data, so prototype pollution is not a big issue

The only place I can see we run this on user input is in the CLI

https://github.com/ChainSafe/lodestar/blob/0d87c28aedb2e0556b027fc0714349542ff17542/packages/cli/src/config/beaconNodeOptions.ts#L38-L41

But not that we only run it on plain objects, this should prevent any security concerns + cli is trusted input by the user.

Other than that, we only use it in some tests / helpers
