### ISSUE TITLE
Gossip should support 10MB messages in Bellatrix

### ISSUE THREAD

**Issue by jtraglia** [ChainSafe/lodestar#3776]
Currently, Lodestar has a 1MB max message size (in master & kintsugi branches):

https://github.com/ChainSafe/lodestar/blob/0e47cd31af0d9d43e89335401b74a64af6b5a8eb/packages/lodestar/src/constants/network.ts#L43-L46

For Bellatrix, the spec states that the maximum gossip message size is 10MB:

https://github.com/ethereum/consensus-specs/blob/dev/specs/bellatrix/p2p-interface.md#configuration

I suggest creating new `GOSSIP_MAX_SIZE_BELLATRIX` and `MAX_CHUNK_SIZE_BELLATRIX` constants.

**Comment by dapplion** [comment]
Thanks for noting this @jtraglia :heart:

**Comment by g11tech** [comment]
thanks @jtraglia  for bringing this up! :slightly_smiling_face: we have this tracked here: https://github.com/ChainSafe/lodestar/issues/3486. Current plan is to raise the limit in a release just before merge :+1:

**Comment by jtraglia** [comment]
Tracked elsewhere. Closing.
