### ISSUE TITLE
Limit computational cost of beacon node API calls

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3780]
**Describe the bug**

At least here

https://github.com/ChainSafe/lodestar/blob/c12dc8aa980e26399ffceeebe7e6a56048d7f0bd/packages/lodestar/src/api/impl/beacon/state/index.ts#L77-L79

This call triggers an expensive loop that is not really used in practice. Also related https://github.com/ChainSafe/lodestar/issues/3683

Calling any API endpoint should require limited resources to process to prevent DOS vectors. Expensive calls should only be possible under some flag like `--enable-debug-routes`

**Comment by wemeetagain** [comment]
@nflaig what do you think about this suggestion? (Adding a flag) Is it necessary or should we just close this as "wontfix"?

**Comment by nflaig** [comment]
The question is what kind of DoS vectors are we talking about here and what nodes do we wanna protect?

Stakers are not supposed to have their api exposed and if they do, DoS is the least they have to worry about, e.g. someone can steal their block rewards via `prepareBeaconProposer` api and even if we could somehow get rid of those expensive calls and disable them by default, even a simple script calling `getPeers` can bring down the node as is, we don't have any rate limiting to prevent this.

So what nodes do we wanna protect, it makes sense for public nodes we host ourselves but I don't see how we can protect those against a targeted DoS attack, but we might be able to prevent someone from accidentally crashing the node by requesting state validators or state as JSON via https://github.com/ChainSafe/lodestar/issues/6838.

And for infrastructure providers, they can run their own caching layer, load balancer, rate limiter, WAF, etc. to protect against target DoS attacks.


> (Adding a flag) Is it necessary or should we just close this as "wontfix"?

I do think what's noted in this issue in combination with https://github.com/ChainSafe/lodestar/issues/6838 for our public nodes so people don't accidentally kill them.

**Comment by wemeetagain** [comment]
Ok, I agree.
- Closing in favor of #6838

**Comment by nflaig** [comment]
> Closing in favor of

well we can still try to avoid running these costly computations, it's just not a factor that will instantly blow up the node like return JSON state or validator does

**Comment by wemeetagain** [comment]
How can we avoid running the costly things?

**Comment by nflaig** [comment]
> How can we avoid running the costly things?

e.g. for state validators, not allow to query all of them, limit to 100 keys or something

**Comment by nflaig** [comment]
or even 10k keys
