### ISSUE TITLE
Error: attestedData not available

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3788]
**Describe the bug**

Found this error when syncing node using `ssz-v2` branch

```
Feb 25 09:50:01 contabo-13 beacon_run.sh[678974]: Error: attestedData not available
Feb 25 09:50:01 contabo-13 beacon_run.sh[678974]:     at LightClientServer.onSyncAggregate (/usr/src/lodestar/packages/lodestar/src/chain/lightClient/index.ts:430:15)
Feb 25 09:50:01 contabo-13 beacon_run.sh[678974]:     at LightClientServer.onImportBlock (/usr/src/lodestar/packages/lodestar/src/chain/lightClient/index.ts:207:10)
Feb 25 09:50:01 contabo-13 beacon_run.sh[678974]:     at importBlock (/usr/src/lodestar/packages/lodestar/src/chain/blocks/importBlock.ts:235:31)
Feb 25 09:50:01 contabo-13 beacon_run.sh[678974]:     at processBlock (/usr/src/lodestar/packages/lodestar/src/chain/blocks/index.ts:65:5)
Feb 25 09:50:01 contabo-13 beacon_run.sh[678974]:     at JobItemQueue.runJob (/usr/src/lodestar/packages/lodestar/src/util/queue/itemQueue.ts:90:22)
Feb 25 09:50:06 contabo-13 beacon_run.sh[678974]: Feb-25 09:50:06.001[]                 info: Synced - slot: 2439250 - head: 2439250 0x288e…00df - fi
```

**Expected behavior**

No error

**Comment by dapplion** [comment]
When did this happen? At the very start of running the node? Or at a random slot?

The slot in the log is https://prater.beaconcha.in/block/2439250

Where
- 2439250 - OK https://prater.beaconcha.in/block/2439250
- 2439249 - SKIPPED https://prater.beaconcha.in/block/2439249
- 2439248 - SKIPPED https://prater.beaconcha.in/block/2439248
- 2439247 - OK https://prater.beaconcha.in/block/2439247

So could related to two slots skipped in a row

**Comment by twoeths** [comment]
> When did this happen? At the very start of running the node? Or at a random slot?

It happened when the node was syncing after I restarted the node

**Comment by twoeths** [comment]
this happens very frequently if we sync a node from prater/mainnet genesis

**Comment by 0xcryptoshark** [comment]
It also happens frequently while syncing from Kiln
