### ISSUE TITLE
Huge heap memory after taking heap snapshot

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3789]
**Describe the bug**

On contabo-12, Heap is >3GB, the heapsnapshot file taken was ~1.4GB, then Heap becomes ~9GB

<img width="820" alt="Screen Shot 2022-02-24 at 11 06 24" src="https://user-images.githubusercontent.com/10568965/155685558-80c671a1-4b30-42c9-ba02-0cc09734efc7.png">

The Heap Space Used metric is normal
<img width="805" alt="Screen Shot 2022-02-25 at 15 57 39" src="https://user-images.githubusercontent.com/10568965/155685790-ee430b07-7932-44e8-8985-70ddcaf559c8.png">

**Expected behavior**

After taking a heap snapshot, heap memory should be smaller, normally 2G-2.5G

**Comment by dapplion** [comment]
I've seen this behavior always almost every time I take heap snapshots, so I assume that's what happens in normal cases. Since we shouldn't take snapshots on production nodes this shouldn't be a concern
