### ISSUE TITLE
Improve BLS thread pool - job wait time

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3792]
**Is your feature request related to a problem? Please describe.**

The BLS Thread pool - job wait time is designed to be consistently less than 100ms, however a lot of time it's > 100ms, maybe even up to 500ms.

Note that this metric is important for the gossip Job Wait Time, we want it to be consistently <3s to avoid the gosisp peer penalty due to broken IWANT promises.

**Describe the solution you'd like**

+ The reason is when non-batchable jobs are sent to bls, it forces the worker thread to run and we don't utilize the worker threads at that time. If we only send batchable jobs to worker threads, it works as designed

<img width="811" alt="Screen Shot 2022-02-26 at 14 00 37" src="https://user-images.githubusercontent.com/10568965/155833606-41bf114f-0987-4ce9-901e-60ce2c2f21b5.png">

+ In average, non-batchable signature sets happen only when we validate gossip blocks or run state transition, and it's <2ms in contabo or <1ms in hetzner so it's ok to run them in main-thread
+ Verify batchable signature sets in worker threads

**Comment by twoeths** [comment]
also we face the below chicken-and-egg issue in ssz-v2:
+ We receive few gossip blocks due to few mesh peers due to low gossip peer scores
+ This is due to poor gossip Job Wait Time performance (and it leads to apply penalty for borken IWANT promises)
+ Part of that is due to poor BLS Job Wait Time performance
+ Part of that is due to so many blocks processed in Unknown Block sync which lead to sending non-batchable signature sets to bls
+ That's because of not enough gossip blocks received 
... 
...
(continue the loop)

when this issue happens, cpu time is so low so we should be able to verify block signatures in main thread

**Comment by dapplion** [comment]
I'm not sure I follow your reasoning. The current implementation of the BLS thread pool will send multiple sig sets to a worker event if the jobs are not batch-able.

Let's assume we have a single worker, and the following sequence of events
- request verify sig set 0
- thread pool send job 0 (with sig set 0) to worker 0
- request verify sig set 1, keep in queue
- request verify sig set 2, keep in queue
- worker 0 finishes job 0
- thread pool send job 1 (with both sig set 1 and 2) to worker 0
- worker 0 finishes job 1

So for the first instance this may introduce delay but afterwards all buffered sig sets will be sent in batch on the same job.

What host did you capture the metrics above? You should review the metrics:
- "BLS worker pool - sets per job": if this number is high many different sig sets (both batch-able and non batch-able) are sent in the same job
- "BLS worker pool - sigs per set": gives an idea of what type of jobs it's verifying. Aggregates have 3 sigs, attestations 1, and block ~ 100

![Screenshot from 2022-02-26 16-34-44](https://user-images.githubusercontent.com/35266934/155840827-2c3b9141-c037-4bfc-a3c3-817cf62454ad.png)

**Comment by twoeths** [comment]
Let's assume we have 1 single thread and the following scenario (happens in <100ms):
+ send 5 batchable signature sets to thread pool
+ gossip block comes, send 1 signature set to thread pool
+ thread pool sends 6 signature sets to worker 0
+ send another 5 batchable signature sets to thread pool
+ wait for worker 0 to finish
+ worker 0 finishes
+ thread pool sends the latter 5 batchable signature sets to worker 0

in the above scenario, worker 0 runs 2 times, there are latencies between to/from worker and wait time for the 1st run to finish. If we verify signatures of gossip block in main thread, worker 0 could run only 1 time.

The below metrics are captured from contabo-18: when there are non-batchable signature sets (should be from gossip blocks and unknown block sync), bls job wait time is clearly higher
<img width="778" alt="Screen Shot 2022-02-28 at 15 52 28" src="https://user-images.githubusercontent.com/10568965/155953200-26ad4051-f408-4c20-9ebb-6e6fea01b200.png">

Some reasons for the change:
+ We want good number of mesh peers
+ So Gossip Job Wait Time should be <3s, otherwise gossip peer score is down due to broken IWANT promises penalty
+ So Gossip Validation Time should be low, and this depends on BLS Job Wait Time

that's why we want to keep BLS Job Wait Time low.
The trade-off is that we have to verify gossip blocks' signatures in main thread, and signatures from unknown block syncs too. This change needs to be deployed in a node to prove it's worth for the change.
