### ISSUE TITLE
Fork-choice does not update head during head sync

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3804]
**Describe the bug**

When running Lodestar beacon node on prater with `--weakSubjectivitySyncLatest` the node does not immediately set as head the synced blocks from peers.

The sequence is:
- 1. Node starts with latest finalized
- 2. Node connects with some peers who label as "Advanced" and trigger a head sync
- 3. Do a head sync up to the peer's head. Chain processor logs confirm that all blocks are processed successfully
- 4. However, the node's head is still the initial finalized state
- Repeat 2 -> 4 until for some reason the fork choice actually sets a new head

Range fill metrics show the head sync that completes fast and then all peers are labeled as "Synced" because their head is known to the forkchoice.

![Screenshot from 2022-02-28 16-58-20](https://user-images.githubusercontent.com/35266934/155976117-7b5c1075-0a96-4611-9046-784f64eadcea.png)

Fork-choice metrics show that it is called, but the findHead() isn't actually run

![Screenshot from 2022-02-28 17-00-19](https://user-images.githubusercontent.com/35266934/155976423-be3e0a37-1685-4a89-b105-92cdd85e8e0c.png)

Block processor metrics show all blocks processed

![Screenshot from 2022-02-28 17-00-35](https://user-images.githubusercontent.com/35266934/155976763-5f97e8a3-a743-47f6-a73f-3d412997264c.png)

**Expected behavior**

Update head as the node syncs

**Comment by philknows** [comment]
Issue still persists from Mar 18 planning meeting.

**Comment by wemeetagain** [comment]
No longer happening. Here is a screenshot of a node that is syncing

![Screenshot from 2024-10-10 16-05-32](https://github.com/user-attachments/assets/34574ac8-a195-4dd8-be66-11d204c7d34e)
