### ISSUE TITLE
PeerManager dials same peer multiple times in a row

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3807]
**Describe the bug**

debug logs in a prater beacon node show that PeerManager + Discover modules dial the same peer +30 times in a row. Probably it's not tracking active dials so it believes it's a new peer maybe?

**Expected behavior**

Dial each peer once

**Steps to Reproduce**

Run prater

**Comment by philknows** [comment]
Must dig into libp2p and see what's happening with this one.

**Comment by philknows** [comment]
Is anyone else still seeing this issue post-`v1.0.0` ?

**Comment by dapplion** [comment]
> Is anyone else still seeing this issue post-`v1.0.0` ?

For context: To check if the issue is happening once must analyze debug logs in detail on a node that's just starting and compare aggregate the list of logs "dialing discovered peer <peer-id>"

**Comment by philknows** [comment]
Stale.
