### ISSUE TITLE
Validator fails to start when hex literal value is passed to externalSignerPublicKeys 

### ISSUE THREAD

**Issue by dadepo** [ChainSafe/lodestar#3817]
**Describe the bug**

When an hex literal value (prefixed with 0x) is supplied as the value of `externalSignerPublicKeys`, then the application fails to start. It throws the following error:

```
 ✖ YError: item.split is not a function at Object.runValidation [as _runValidation]
 ```

The reason is that yargs parses the hex literal string to numeric value, which causes the logic in the coerce function [here](https://github.com/ChainSafe/lodestar/blob/de66f0bde6cf37c13da361899d6e4ba93b332c27/packages/cli/src/cmds/validator/options.ts#L76) to throw an exception

**Expected behavior**

Validator should start, even if literal hex value (with the 0x prefix) is supplied as value to the `externalSignerPublicKeys` flag

**Steps to Reproduce**

1. Set the public key with literal hex. Eg: `externalSignerPublicKeys: "0x97b1b00d3c1888b5715c2c88bf1df7b0ad715388079de211bdc153697b69b868c671af3b2d86c5cdfbade48d03888ab4"`
2. Run the validator
3. See error

**Desktop (please complete the following information):**

- OS: ALL
- Version: v0.35.0-beta.0/master/+2/de66f0bd (git)

**Comment by dapplion** [comment]
From https://github.com/yargs/yargs-parser/pull/132 seems there is a way to prevent parsing strings
