### ISSUE TITLE
Add flag to set fee recipient

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3818]
Add free recipient flag. Wait for other client to standardize on the name a bit. Just opening this issue for now so that it's covered when due.

https://github.com/ChainSafe/lodestar/blob/de66f0bde6cf37c13da361899d6e4ba93b332c27/packages/lodestar/src/api/impl/validator/index.ts#L187-L188

@g11tech sorry if this is a duplicate

**Comment by g11tech** [comment]
@dapplion yes its tracked here: https://github.com/ChainSafe/lodestar/issues/3693 :slightly_smiling_face:

**Comment by dapplion** [comment]
Duplicate of https://github.com/ChainSafe/lodestar/issues/3693
