### ISSUE TITLE
v0.34.1 release

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3829]
**Motivation**

Give visibility to the v0.34.1 release. This PR should not be merged, but closed once we release

**Description**

Include only a small fix that prevents proposing blocks when the deposit tracker gets out of sync.

- Make block proposing flow resilient to errors (#3737)

See diff here https://github.com/ChainSafe/lodestar/compare/v0.34.0...v0.34.1-beta.0

**Comment by twoeths** [comment]
closing as v0.34.2 released
