### ISSUE TITLE
PeerManager: prioritize peers to disconnect

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3832]
**Is your feature request related to a problem? Please describe.**

We need a strategy to prioritize peers to disconnect. At least we need to select peers with least long-lived subnets to disconnect, refer to https://github.com/sigp/lighthouse/blob/1829250ee4df6c4e69687ccdcc69ab79d968e986/beacon_node/lighthouse_network/src/peer_manager/mod.rs#L883

**Describe the solution you'd like**

+ Work on this `TODO`: https://github.com/ChainSafe/lodestar/blob/bdeef8dcf52dd19b5598335b302a0ec06fded978/packages/lodestar/src/network/peers/utils/prioritizePeers.ts#L97

+ New metrics to show long-lived subnets of our peers and track it over time to make sure that's an improvement

+ Any changes to the network/peer manager are critical so need to test the work carefully

**Comment by philknows** [comment]
Good follow up step to gossipsub resolution.

**Comment by twoeths** [comment]
close via #3955
