### ISSUE TITLE
Improve message id cache

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3833]
**Describe the bug**

Right now we use `WeakMap` to cache message id and it takes time to cache messages there

<img width="1233" alt="Screen Shot 2022-03-07 at 13 48 33" src="https://user-images.githubusercontent.com/10568965/156984276-5ca14d5b-21e2-4422-affa-6166e3f34256.png">

It seems that after we improve the memory, this map keeps growing and we don't control the max size of it

**Expected behavior**

Find another way to cache that we can control the size of the map

**Comment by twoeths** [comment]
there is similar issue to the UncompressCache, we can just cache the uncompressed message data right inside the message and remove it

<img width="805" alt="Screen Shot 2022-03-09 at 09 57 26" src="https://user-images.githubusercontent.com/10568965/157364370-824cf200-7e1f-4a4d-9594-6f11e086b7c0.png">

**Comment by dapplion** [comment]
> there is similar issue to the UncompressCache, we can just cache the uncompressed message data right inside the message and remove it

Sounds good!
