### ISSUE TITLE
/eth/v1/node/syncing returns wrong types

### ISSUE THREAD

**Issue by timothysu** [ChainSafe/lodestar#3846]
**Describe the bug**
This breaks several external integrations. The following is returned when that endpoint is hit:
```
{"data":{"head_slot":3343898,"sync_distance":0,"is_syncing":false}}
```
with the json types of
```
{
  head_slot: number
  sync_distance: number
  is_syncing: boolean
}
```

**Expected behavior**
Per https://ethereum.github.io/beacon-APIs/#/Node/getSyncingStatus , this is supposed to return a response of the following schema:
```
{
  head_slot: string
  sync_distance: string
  is_syncing: boolean
}
```
so the proper response should be
```
{"data":{"head_slot":"3343898","sync_distance":"0","is_syncing":false}}
```

**Steps to Reproduce**
```
curl http://<lodestar-beacon-node>:9596/eth/v1/node/syncing
```

**Screenshots**
n/a

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04 LTS
- Version: `chainsafe/lodestar:v0.34.1` via docker
- Branch: n/a
- Commit hash: n/a

**Comment by dapplion** [comment]
@dadepo Can you take a look please?
