### ISSUE TITLE
Beacon API peer_count call always returns 0

### ISSUE THREAD

**Issue by tdahar** [ChainSafe/lodestar#3857]
While using the beacon API to get some data from the client, always peer_count call returns 0

curl localhost:9596/eth/v1/node/peer_count
{"data":{"disconnected":0,"connecting":0,"connected":0,"disconnecting":0}}

It would be expected to receive the current amount of peers in each state
curl localhost:9596/eth/v1/node/peer_count
{"data":{"disconnected":10,"connecting":9,"connected":30,"disconnecting":2}}

Running Lodestar with Docker, version 0.34.0

**Screenshots**

- OS: Ubuntu 
- Version: 21.04 
- Image: chainsafe/lodestar:v0.34.0

**Comment by dadepo** [comment]
Thanks for reporting this. The `/eth/v1/node/peer_count` endpoint is yet to be implemented. This is why it always returns 0.  Once priorities allows, it would be implemented. 

In the meantime, maybe you can check `/eth/v1/node/peers`? if it can be used as a workaround?

**Comment by dapplion** [comment]
We should definitely implement this endpoint, sounds easy and aligns us with the api standard
