### ISSUE TITLE
Kiln script fails badly with default Docker settings

### ISSUE THREAD

**Issue by seishun** [ChainSafe/lodestar#3861]
**Describe the bug**

https://github.com/ChainSafe/lodestar/tree/master/kiln/devnets

Docker allocates 2.00 GB of memory by default. That seems to be insufficient since after a while kiln-lodestar exits with exit code 137. When running in-terminal, the container suddenly disappears (due to `--rm`) and when running detached the container keeps restarting from slot 2112 (due to `--restart unless-stopped`).

With 4.00 GB it gets as far as slot 35904, and with 8.00 GB it appears to work fine.

**Expected behavior**

When a container exits abnormally, the script should inform the user. The user should be informed about the memory requirements.

**Desktop (please complete the following information):**

- OS: macOS Monterey
- Branch: master

**Comment by dapplion** [comment]
Thanks for reporting @seishun !

- Right 2GB for the whole process is too low. Current mainnet and prater nodes have a heap size of ~1.5GB total process rss of 3GB. You should allocate at least 4GB.
- I think there's a memory issue with bellatrix fork, I've seen unusual memory spikes abnormal to other networks. @g11tech can you investigate?

**Comment by g11tech** [comment]
Thanks @seishun , will update the requirements in the doc. 🙂

Sounds good @dapplion will investigate what's going on. 👍

**Comment by philknows** [comment]
Created #3866 to focus specifically on the potential memory leak. We can close this issue if the new container memory setting works for you @seishun and the new requirements have been merged to the doc.

**Comment by dapplion** [comment]
In all the shadow-forks I haven't observed memory leaks on Lodestar. Closing for now, please re-open if you have any issues with excessive memory on latest versions
