### ISSUE TITLE
Investigate restrict-size performance issue

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3862]
**Describe the bug**

+ restrict-size is used in libp2p-mplex, it's pretty simple but takes 4.6% of cpu time
<img width="1080" alt="Screen Shot 2022-03-18 at 17 27 00" src="https://user-images.githubusercontent.com/10568965/158986644-6d217a2e-1bc8-403c-ab16-dccc5acc795f.png">

<img width="809" alt="Screen Shot 2022-03-18 at 17 28 29" src="https://user-images.githubusercontent.com/10568965/158986721-b2a10da1-2d57-4307-b41a-44b232bf1cd5.png">

[0318_contabo_20.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/8303721/0318_contabo_20.cpuprofile.zip)

**Expected behavior**

Should be <1%

**Comment by dapplion** [comment]
@tuyennhv Could you run the CPU profile again without async stack traces?

**Comment by twoeths** [comment]
reattaching https://github.com/ChainSafe/lodestar/issues/4603#issuecomment-1263095995 (after libp2p is updated to 0.39.2), this time it shows `restrictSize()` takes 4%

<img width="1448" alt="Screen Shot 2022-10-03 at 08 53 46" src="https://user-images.githubusercontent.com/10568965/193488316-0298a961-bb66-41da-b31c-0bca15d25bc8.png">

Detail

<img width="839" alt="Screen Shot 2022-10-03 at 08 54 10" src="https://user-images.githubusercontent.com/10568965/193488341-dde5c4f5-ce46-40e3-a3d3-e4a4913c2642.png">


I disabled async stack trace so there is no async hook there @wemeetagain 

<img width="220" alt="Screen Shot 2022-10-03 at 08 52 41" src="https://user-images.githubusercontent.com/10568965/193488238-bd028f47-9bd0-447e-86ae-eca4afb54d0c.png">

[0930_multilined_fastMsgId_lg1k_1.2.0.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/9694117/0930_multilined_fastMsgId_lg1k_1.2.0.cpuprofile.zip)

**Comment by twoeths** [comment]
tracked in https://github.com/libp2p/js-libp2p-mplex/issues/205

**Comment by dapplion** [comment]
- Upstream issue fixed https://github.com/libp2p/js-libp2p-mplex/issues/205
