### ISSUE TITLE
Apply Gossipsub Params from the spec

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3865]
**Is your feature request related to a problem? Please describe.**

Refer to https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/p2p-interface.md

```
D (topic stable mesh target count): 8
D_low (topic stable mesh low watermark): 6
D_high (topic stable mesh high watermark): 12
D_lazy (gossip target): 6
heartbeat_interval (frequency of heartbeat, seconds): 0.7
fanout_ttl (ttl for fanout maps for topics we are not subscribed to but have published to, seconds): 60
mcache_len (number of windows to retain full messages in cache for IWANT responses): 6
mcache_gossip (number of windows to gossip about): 3
seen_ttl (number of heartbeat intervals to retain message IDs): 550
```

**Describe the solution you'd like**

+ Apply respective params to lodestar
+ Prefer specifying params in lodestar instead of using the gossipsub default params
+ Probably wait for the new gossipsub work https://github.com/ChainSafe/js-libp2p-gossipsub/pull/206

**Comment by dapplion** [comment]
@tuyennhv https://github.com/ChainSafe/js-libp2p-gossipsub/pull/206 is merged, issue unblocked
