### ISSUE TITLE
Potential memory leak in Bellatrix merge fork

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#3866]
There have been reports from users about unusual memory spikes abnormal to other networks. Issue #3861 addresses the need to increase memory from the default Docker setting of 2.0GB to a minimum recommended minimum setting of 4.0GB.  

This issue will track the issue specifically related to the potential memory leak on our Bellatrix merge tests.

**Comment by g11tech** [comment]
Did some basic investigation with memory dumps and comparing them over 5,10,60 minutes window, didn't find anything weird going on related to merge/post merge. (snapshots size varies ~ 460-560 range)

![image](https://user-images.githubusercontent.com/76567250/159481407-61b69b11-556a-402c-a2e1-1d10e0e95b96.png)

Here is the process heap graph of our own lodestar <> geth setup validation with around ~500 validators:

![image](https://user-images.githubusercontent.com/76567250/159480937-5908fa05-35c2-4c5f-8524-8969c72afe45.png)

Lodestar seems to be using ~1.8GB of heap memory, total setup : lodestar + geth + 2 validator instances running on kiln ~3.2GB:

![image](https://user-images.githubusercontent.com/76567250/159481182-055b5550-45ad-4adc-a4a5-c24cebd626e0.png)


@philknows any specific pointers by the users? to help narrow this down?

**Comment by g11tech** [comment]
closest I have come to is to find a bit of correlation between inbound peer connections and heap. The starting of this graph is just after merge transition (when the metrics collection was started on our kiln testnet server).
Noteworthy thing is: there were chaos around the merge transition as a subset of prysm (i think) related nodes were proposing invalid payloads, which might be resulting into some peer turbulence. 

![image](https://user-images.githubusercontent.com/76567250/159487365-ace7e826-f748-4598-b58f-3a0a9df3898c.png)

**Comment by dapplion** [comment]
Pari's Kiln dashboard had a bad query that plotted data wrong. The reported memory usage was of 95% of 8GB, but it was really 4GB. After manually checking each instance, every Lodestar process takes ~1.8GB max with constant memory through 7 days.

Since there's no hard evidence of a leak anymore, closing
