### ISSUE TITLE
Throw object instead of typed errors

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3890]
**Is your feature request related to a problem? Please describe.**

As tested in #3448, throwing an object is 5x faster than our typed error (for example AttestationError), we should consider this option.

**Describe the solution you'd like**

consider changing from
```typescript
throw new AttestationError(GossipAction.IGNORE, {
    code: AttestationErrorCode.UNKNOWN_BEACON_BLOCK_ROOT,
    root: ZERO_HASH,
  });
```

to
```typescript
throw {
    action: GossipAction.IGNORE,
    code: AttestationErrorCode.UNKNOWN_BEACON_BLOCK_ROOT,
    root: ZERO_HASH,
  };
```

**Comment by dapplion** [comment]
This is only relevant for hot paths, which is gossip validation. Those functions should just return objects instead of throwing errors. Throwing a non-Error type breaks many assumptions in our code.

- Closing for alternative solution https://github.com/ChainSafe/lodestar/issues/3402
