### ISSUE TITLE
Consolidate sim and e2e tests for clarity and scale

### ISSUE THREAD

**Issue by dadepo** [ChainSafe/lodestar#3931]
**Is your feature request related to a problem? Please describe.**

Based on discussion in the PR [here](https://github.com/ChainSafe/lodestar/pull/3909) there is a need to disambiguate and consolidate `sim` and `e2e` tests. Objective is to remove confusion around terminologies while at the same time being efficient with tests that spins up the dev beacon node (since these tests take considerable amount of time to run)

**Describe the solution you'd like**

Suggestions:

- Consider integration tests that does not run the beacon node as `e2e` and have these under `packages/lodestar/test/e2e`
- Consider integration tests that run the beacon node as `sim` and have these under `packages/lodestar/test/sim`
- Move tests within `packages/lodestar/test/e2e` that runs the beacon node to `packages/lodestar/test/sim/singleNodeSingleThread.test.ts` and `packages/lodestar/test/sim/singleNodeSingleThread.test.ts`
- Consolidate tests within `packages/lodestar/test/sim/` based on similarity in configuration. Have as few of these tests as possible with as most assertions as possible. The Idea is to be efficient with tests that spin up the dev beacon node (since these tests take considerable amount of time to run).

**Comment by dapplion** [comment]
Removed `meta-goodfirstissue`, this issue is very complex and requires deep knowledge of the beacon chain

**Comment by nazarhussain** [comment]
Closed with https://github.com/ChainSafe/lodestar/pull/4759
