### ISSUE TITLE
Expose syncing status

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#395]
- for sync module expose methods to obtain startingSlot, currentSlot and highest slot
- use these methods to implement syncying status method in rpc/rest api

See: https://app.swaggerhub.com/apis/spble/beacon_node_api_for_validator/0.3.0#/MinimalSet/get_node_syncing

**Comment by mpetrunic** [comment]
unstale

**Comment by twoeths** [comment]
@mpetrunic I can work on this.

**Comment by mpetrunic** [comment]
Not yet, this issue depends on sync refactoring happening ATM :/
