### ISSUE TITLE
Consider renaming `packages/lodestar`

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#3950]
**Is your feature request related to a problem? Please describe.**

@dadepo mentioned that while learning the codebase, it may be confusing to have the subdirectory `packages/lodestar` named this way.

**Describe the solution you'd like**

Rename directory to `packages/beacon-node`
Rename package to `@chainsafe/lodestar-beacon-node`

**Describe alternatives you've considered**

Keep as is

**Comment by dapplion** [comment]
In that case what would the package `@chainsafe/lodestar` point to?

**Comment by wemeetagain** [comment]
Not sure, maybe we could leave the package name as-is.

**Comment by philknows** [comment]
Suggested changes to restructuring directories by @wemeetagain:

```
api -> @lodestar/api
beacon-state-transition -> @lodestar/beacon-state-transition
beacon-node -> @lodestar/beacon-node
config -> @lodestar/config
db -> @lodestar/db
flare -> @chainsafe/flare
keymanager-server -> @lodestar/keymanager-server
light-client -> @lodestar/light-client
lodestar -> @chainsafe/lodestar
params -> @lodestar/params
spec-test-util -> @lodestar/spec-test-util
types -> @lodestar/types
utils -> @lodestar/utils
validator -> @lodestar/validator
```

**Comment by dadepo** [comment]
maybe?:

```
validator-client -> @lodestar/validator-client
```

**Comment by wemeetagain** [comment]
also
```
state-transition -> @lodestar/state-transition
```
