### ISSUE TITLE
Improve how we keep and process spec configs

### ISSUE THREAD

**Issue by dadepo** [ChainSafe/lodestar#3976]
**Is your feature request related to a problem? Please describe.**

In the discussion in #3973 it was surfaced that the way we handle spec configs can be improved: Some relevant comment:

> So while this PR will fix some issues, the spec still has some params that may change at any time and are not relevant. Like SHARDING_* fork params or any future fork before it's activated. Probably we should whitelist params and test only the active fork params

> In the future forks params there's a high chance of missmatch in the future fairly frequently. While the solution I propose i more maintenance, we must ensure that there are no false positives which kill usability of our software

> My suggestion was to divide the config variables hardwork wise and check for the hardwork epoch if not present set it to infinity value and fill it's other corresponding params with the local defaults

Look into finding a better way to keep and process the spec config that will reduce the chance of mismatch.

**Comment by dapplion** [comment]
No more missmatch issues happened on bn / vc
