### ISSUE TITLE
Investigate Wrong Head Ratio metric

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3985]
**Describe the bug**

With v0.35.0, missed attestations is not a hot issue any more, however we need to figure out why our validator vote for some wrong heads:

<img width="802" alt="Screen Shot 2022-05-07 at 15 47 54" src="https://user-images.githubusercontent.com/10568965/167246835-1b81ea09-3693-40ad-9685-c65d1512152c.png">

**Expected behavior**
No wrong head

**Comment by dapplion** [comment]
Closing issues for specific incidents on old versions of Lodestar, please re-open if it happens with latest stable
