### ISSUE TITLE
Reject importing blocks with many skipped slots 

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3988]
**Describe the bug**

Peers can DOS us by triggering expensive epoch transitions in cases of long non-finality. Lighthouse limits skipped slots to 100, we should do the same.

DOS will happen because we need to get the proposerShuffling. To get the shuffling we have to do a bunch of epochTransitions, the longer the distance between the parent and block, the more we have to do. epochTransitions are expensive ~750ms, so we must limit how many a single bad block can trigger.

Add this to gossip block validation

```ts
  if (blockSlot > parentBlock.slot + chain.importMaxSkipSlots) {
    throw new BlockGossipError(GossipAction.IGNORE, {
      code: BlockErrorCode.TOO_MANY_SKIPPED_SLOTS,
      parentSlot: parentBlock.slot,
      blockSlot,
    });
  }
```

**Comment by dadepo** [comment]
I see in the Lighthouse implementation, they also punish peers that sends `TOO_MANY_SKIPPED_SLOTS`. Should lodestar have similar punishment?

**Comment by dapplion** [comment]
> I see in the Lighthouse implementation, they also punish peers that sends `TOO_MANY_SKIPPED_SLOTS`. Should lodestar have similar punishment?

I think penalizing for invalid blocks is sufficient. A block with `TOO_MANY_SKIPPED_SLOTS` is not malicious per definition, only if it's invalid
