### ISSUE TITLE
Use byteArrayEquals instead of ssz.Root.Equals

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3996]
Many codepaths use ssz.Root for things that are not semantically a Root. I feel it would be more clean to just use `byteArrayEquals` for everything that's always gonna be a Uint8Array. Practically there's not much difference, just a matter of code appearance.

From https://github.com/ChainSafe/lodestar/pull/3760

What do you think? Marking the issue for discussion

**Comment by wemeetagain** [comment]
Yeah agreed, anything thats not a Root, known to be a Uint8Array, should just use byteArrayEquals.

**Comment by philknows** [comment]
Superseded by #5955
