### ISSUE TITLE
Optimize hashing ssz struct values

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3997]
Tracks https://github.com/ChainSafe/ssz/issues/245

> There's a 30% overhead cost converting things back a forth to wasm friendly formats

> For context this is only really noticeable when loading states from disk where the full BeaconState has to be hashed. There the saving are in the order of 1s -> 0.7s. However when signing gossip messages the savings are not too significant. Maybe they will be to hash full large ExecutionPayloads.

From https://github.com/ChainSafe/lodestar/pull/3760

**Comment by philknows** [comment]
Closing. Track optimisation via https://github.com/ChainSafe/ssz/issues/245
