### ISSUE TITLE
Review epochCtx shufflings cache

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3999]
From https://github.com/ChainSafe/lodestar/pull/3760 I noticed that some cached data may be redundant.

All data cached in shufflings cache may not be necessary or could be optimized for better memory efficiency. The maximum possible gains are not significant, so this is a low priority.

**Comment by philknows** [comment]
Likely to be closed in #6030

**Comment by wemeetagain** [comment]
Closing since we've done a lot of work to reduce memory usage here
