### ISSUE TITLE
Use local eth1 / EL node for e2e tests

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4014]
Our current tests for eth1 query an actual Goerli node hosted by an external provider, which adds fragility to our test suite.

- https://github.com/ChainSafe/lodestar/issues/3993

We want to eventually not have external network dependencies in our test so:

- Install some EL node locally (geth, ethereumJS)
- Spin up a local testnet, and populate if necessary
- Test against that local node

FYI that's a significant effort, that's why it hasn't been done yet. But we do need this eventually.

**Comment by wemeetagain** [comment]
We now have tests which spin up an EL, run an ephemeral testnet, and test various assertions.
Closing this.
