### ISSUE TITLE
Review AggregateAndProof op pool

### ISSUE THREAD

**Issue by tuyennhv** [ChainSafe/lodestar#4028]
**Describe the bug**

The blocks proposed by lodestar usually have 68-74 attestations while blocks adjacent to those slots usually have 128 attestations, need to review if we can do better than that

**Expected behavior**
+ Make sure no missed attestations due to our AggregateAndProof op pool
+ Call `produce_block` end point and compare to real data proposed by other clients

**Comment by dapplion** [comment]
@tuyennhv We could add a new metric to track the balance delta of the proposer whenever we propose. That would track profitability of our blocks and give us data to compare with other clients.

**Comment by dapplion** [comment]
Lodestar blocks are fully packed with latest version
