### ISSUE TITLE
Standardize SHA256

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/lodestar#403]
BLS & SSZ should use the same version of SHA256, probably `bcrypto`

**Comment by mpetrunic** [comment]
Everything except SSZ uses as-sha256 because SSZ is used on web and as-sha256 doesnt support web currently

**Comment by mpetrunic** [comment]
on hold until we fix as-sha256 to work sync in browser or make it async everywhere

**Comment by wemeetagain** [comment]
completed, we're using as-sha256 everywhere
