### ISSUE TITLE
Publish beta releases to NPM and Dockerhub

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#4036]
**Is your feature request related to a problem? Please describe.**

In order to aid testing of beta releases, we should be able to replicate production scenarios, specifically, running lodestar via docker.

**Describe the solution you'd like**

Publish the releasee to NPM and Dockerhub.

**Comment by philknows** [comment]
This should be resolved now with [gitflow process](https://github.com/ChainSafe/lodestar/pull/4071) @wemeetagain ?

**Comment by wemeetagain** [comment]
> This should be resolved now with [gitflow process](https://github.com/ChainSafe/lodestar/pull/4071) @wemeetagain ?

Yup resolved with #4071
