### ISSUE TITLE
Web3 Provider 

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/lodestar#404]
Since there now exists a [apis repo](https://github.com/ethereum/eth2.0-apis), this is an opportune time to begin fleshing out a barebones provider. Should perform type validations and proper error handling out of the gate. I'd like to aim for it to be more of a wrapper, at the beginning. Perhaps something that can be imported to ethers or web3.js.

@ricmoo - do you have any thoughts?

**Comment by ricmoo** [comment]
That’s exactly what an ethers Provider has always been... Lowest-common-denominator functionality that all backends can support. It does data sanitization on input parameters (throwing on ambiguous input) and always coerces the output to known, well-defined types.

If there is missing or excessive functionality though, I’d love feedback. :)

AbstractProvider: https://github.com/ethers-io/ethers.js/blob/ethers-v5-beta/packages/abstract-provider/index.d.ts#L106

**Comment by ricmoo** [comment]
It’s also important to note that this can be quite decoupled from the JSON-RPC a node uses. That said, a few wish list items:

The sendTransaction should return the signed transaction, not a hash. The hash is easy to compute from the signed transaction, and this also lets the nonce, gas price, etc that the node filled in. That said, I would also like to see the sendTransaction (not to be confused with sendRawTransaction), signMessage, and other account operations moved out of the node, in general. Basically the same divide ethers makes between the AbstractProvider and AbstractSigner.

A much bigger discussion is a reasonable pagination system for Logs. Like continuing from a given block number and log index, and a maximum number of entries to return. This would also allow for real-time queries.

I’m sure I’ll have more. Lemme think for a while. :)
