### ISSUE TITLE
Re-enable check-readme disabled on #3978

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4041]
Check to disabled in https://github.com/ChainSafe/lodestar/pull/3978, this issue is a reminder to fix when possible.

https://github.com/ChainSafe/lodestar/blob/5d086b58a20f57c69f1d2cc90d5bf785f851f535/.github/workflows/test.yml#L56-L58

**Comment by wemeetagain** [comment]
This is likely blocked by https://github.com/bbc/typescript-docs-verifier/issues/17
