### ISSUE TITLE
Replace stub unit tests

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#4042]
Note: Multiple unit tests have been skipped, search for `TODO remove stub` and fix after merging with non-stubby tests

_Originally posted by @dapplion in https://github.com/ChainSafe/lodestar/issues/3978#issuecomment-1132550898_

**Comment by dapplion** [comment]
Note: API tests may be eventually replaced by https://github.com/ChainSafe/lodestar/issues/3682

**Comment by wemeetagain** [comment]
closing since "TODO remove stub" returns no results
