### ISSUE TITLE
Re-enable support for running metrics via (grafana/prometheus) on macos

### ISSUE THREAD

**Issue by dadepo** [ChainSafe/lodestar#4046]
**Is your feature request related to a problem? Please describe.**

In a previous PR [here](https://github.com/ChainSafe/lodestar/pull/3868), changes were made to allow ability to run metrics infrastructure (grafana /prometheous) locally on macos. 

Main changes in that PR involved not using `network_mode` since it is not supported in MacOS, see [here](https://docs.docker.com/network/host/) where it is stated:

> The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server

The workaround on MacOs is to use port mapping instead.

The PR also introduced using `host.docker.internal` instead of `localhost` as localhost does not work with Docker for Desktop for Mac.

In a follow up PR [here](https://github.com/ChainSafe/lodestar/pull/3905) that de-duplicated files and re-organised the dashboard, the possibility to set needed endpoints via environment variable was introduced. Unfortunately this breaks the ability to run the dashboard on MacOs as it assumes `network_mode: host` works on MacOS

**Describe the solution you'd like**

Make changes to make it possible to run metrics via (grafana/prometheus) on macos again. 
Ensure little duplication of configuration files as possible.

**Comment by dapplion** [comment]
Sorry for breaking compatibility! :pray: Happy to review and merge changes to facilitate your DX

**Comment by dadepo** [comment]
Unfortunately i do not think there is a clean way for doing this without duplication. That is because there is no clean way to conditionally use `network_mode: host` (which does not work on macos) or port mapping (which works on macos). In the meantime, I will be using my linux server for anything related to working with metrics.

I'll close this issue as there is no need to keep it around. If I have any ideas on how to tackle this...I can reopen or create a new issue.
