### ISSUE TITLE
De-duplicate implementation for SeenAttesters, SeenAggregators, SeenAggregatedAttestations, SeenBlockProposers, and SeenSyncCommitteeMessages

### ISSUE THREAD

**Issue by dadepo** [ChainSafe/lodestar#4047]
**Is your feature request related to a problem? Please describe.**

The implementations for `SeenAttesters`, `SeenAggregators`, `SeenAggregatedAttestations`, `SeenBlockProposers`, and SeenSyncCommitteeMessages share same interface (`isKnown`, `add`, and `prune`) with similar internal structure with items kept in custom Map datastructure.

**Describe the solution you'd like**

Look into the possibility of extracting out the core behaviour of these classes instead of the current duplication.

**Comment by dapplion** [comment]
There are subtle but important differences between the classes that could reduce clarity if they were all the same class. Also they are really small so it's not a big concern IMO.

For higher value technical debt issues, the ones labeled would be very helpful improvements! https://github.com/ChainSafe/lodestar/issues?q=is%3Aopen+is%3Aissue+label%3Ameta-technical-debt
