### ISSUE TITLE
Lodestar release unintended version

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4050]
**Describe the bug**

When testing #4048 , I tried `lerna version` without `--no-git-tag-version` flag and release flow was triggered unintentionally with version `chore(release): v0.37.0-dev.ef9528aa59`

**Expected behavior**

Release workflow should validate the tag name, or the branch before creating the release

**Comment by philknows** [comment]
Resolved with new gitflow process: https://github.com/ChainSafe/lodestar/pull/4071
