### ISSUE TITLE
Optimize issuing advance engine fcU for prepare payload

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#4054]
Currently the engine fcU is issued just after a  successful block import (https://github.com/ChainSafe/lodestar/pull/3965), predicting the new head to be the head in the next slot if BN has any beacon proposer. Normally this would work just fine, but this isn't sufficient and the following scenarios needs to be addressed:

- [ ] wait till the last interval of slot before issuing fcU unless the head is already last imported
- [ ] issue the fcU
  - [ ] for skipped slot
  - [ ] for head change

**Comment by twoeths** [comment]
Right now PrecomputeNextEpochTransitionScheduler does not work after the merge due to that. I suppose we should make this work as a separate scheduler like in lighthouse and do precompute next epoch transition in this scheduler too https://github.com/sigp/lighthouse/blob/564d7da656803f5e06e53a303972580be54500bf/beacon_node/beacon_chain/src/proposer_prep_service.rs#L18

**Comment by g11tech** [comment]
> Right now PrecomputeNextEpochTransitionScheduler does not work after the merge due to that. I suppose we should make this work as a separate scheduler like in lighthouse and do precompute next epoch transition in this scheduler too https://github.com/sigp/lighthouse/blob/564d7da656803f5e06e53a303972580be54500bf/beacon_node/beacon_chain/src/proposer_prep_service.rs#L18

my idea is not NOT run `PrecomputeNextEpochTransitionScheduler` but run `PrecomputeNextSlotTransitionScheduler` and do an fcU there if not epoch transition else first do epoch transition and then chain fcU to it. what do you think @tuyennhv ?

or we do slot processing on a copy ?

**Comment by g11tech** [comment]
if you want to take this up @tuyennhv  feel free!

**Comment by twoeths** [comment]
> my idea is not NOT run PrecomputeNextEpochTransitionScheduler but run PrecomputeNextSlotTransitionScheduler and do an fcU there if not epoch transition else first do epoch transition and then chain fcU to it. what do you think @tuyennhv ?

yeah we're on the same page, we only need 1 scheduler, yeah I can take this @g11tech
