### ISSUE TITLE
Sync status rest api method

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#407]
Rest api for fetching sync status is currently mocked.
Sync module should implement proper method for sync status and they should be integrated in rest api.

**Comment by wemeetagain** [comment]
Duplicate of #395

**Comment by mpetrunic** [comment]
@wemeetagain Might be good idea to expand #395 because currently it's just about implementing method in Sync module while this was related to sync status rest api

**Comment by wemeetagain** [comment]
added a link to swaggerhub example in the description
