### ISSUE TITLE
Lodestar downscores peers more from v0.36.0 to v0.37.0

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4084]
Lodestar is downscoring more peers that usual reducing the total count of peers with score > 0

![Screenshot from 2022-05-30 11-01-18](https://user-images.githubusercontent.com/35266934/170918927-e6527aad-3104-4890-8971-5e9ad12a4989.png)

This affects the average mesh size of each topic, below target levels

 
![Screenshot from 2022-05-30 11-01-48](https://user-images.githubusercontent.com/35266934/170918995-727d1530-af81-41cd-94b7-cf9287e15176.png)

This creates more churn and inclusion events as Gossip tries to meet the target levels

![Screenshot from 2022-05-30 11-17-31](https://user-images.githubusercontent.com/35266934/170919038-91655fd9-3cf1-4d53-91e6-6e30cad3a63a.png)

The low scores seem to be caused mainly by p3b weights on beacon_attestation topics. 

![Screenshot from 2022-05-30 11-41-44](https://user-images.githubusercontent.com/35266934/170919088-8cec4d1e-b70a-4986-b8fc-78ca8c1bf990.png)

_Originally posted by @dapplion in https://github.com/ChainSafe/lodestar/issues/4074#issuecomment-1140694465_

**Comment by twoeths** [comment]
From v0.37.0 (18h00), there are more late messages deliveries

<img width="786" alt="Screen Shot 2022-05-31 at 08 49 28" src="https://user-images.githubusercontent.com/10568965/171076959-85b3d06f-b5ac-4e85-a9be-5360fdb0344f.png">

There are also more broken promises

<img width="800" alt="Screen Shot 2022-05-31 at 08 50 35" src="https://user-images.githubusercontent.com/10568965/171077070-f5b0db6b-d822-427c-ad62-6642ffbc5af5.png">

Gossip block process time is higher (this is known after we update to esm module)

<img width="796" alt="Screen Shot 2022-05-31 at 08 54 34" src="https://user-images.githubusercontent.com/10568965/171077447-cffa8a86-5152-4998-8684-8a08db6aedb2.png">

it looks like the I/O lag issue happened more with v0.37.0

**Comment by twoeths** [comment]
it's worth to also mention that state transition is more unstable in v0.37.0

<img width="1567" alt="Screen Shot 2022-05-31 at 09 04 13" src="https://user-images.githubusercontent.com/10568965/171078396-9f9b1daf-43dd-4fe5-a8d5-5933d59a7fa6.png">

**Comment by twoeths** [comment]
So I deployed v0.36.0 to contabo-0 and contabo-20 and compare to v0.41.0 (beta group, contabo-12, contabo-13). Below is number of peers with score > 0 (mesh threshold)

- v036.0, contabo-0

<img width="1242" alt="Screen Shot 2022-07-19 at 09 19 59" src="https://user-images.githubusercontent.com/10568965/179650112-4720d94f-1081-448c-859d-18333a33022a.png">

- v0.36.0, contabo-20
<img width="1243" alt="Screen Shot 2022-07-19 at 09 20 32" src="https://user-images.githubusercontent.com/10568965/179650165-4107f63b-eee0-4e6d-b1a2-5680d6e80273.png">


- v0.41.0, contabo-12

<img width="1259" alt="Screen Shot 2022-07-19 at 09 20 55" src="https://user-images.githubusercontent.com/10568965/179650213-1eb2a8fc-52c6-48d1-b14a-35addb43f2f4.png">

- v0.41.0, contabo-13

<img width="1248" alt="Screen Shot 2022-07-19 at 09 21 21" src="https://user-images.githubusercontent.com/10568965/179650265-f60528cc-7752-4bac-9c4b-6493b7c49098.png">
 
The peer score in v0.41.0 is really not worse than v0.36.0

**Comment by twoeths** [comment]
lodestar changed a lot since v0.37.0
v1.3.0 rc.1 has been great in terms of mesh peers

- a goerli node with 1k validators

<img width="813" alt="Screen Shot 2022-12-26 at 14 23 36" src="https://user-images.githubusercontent.com/10568965/209517667-b4f5e835-4b68-4607-b770-f5125f0c19a3.png">

- a mainnet node subscribing to all subnets
<img width="797" alt="Screen Shot 2022-12-26 at 14 24 53" src="https://user-images.githubusercontent.com/10568965/209517817-08c94006-67b3-480f-aaf5-fb2fef080c26.png">

closing the issue
