### ISSUE TITLE
Correct beacon_aggregate_and_proof meshMessageDeliveriesThreshold scoring params

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4086]
**Describe the bug**

The `meshMessageDeliveriesThreshold` scoring params of `beacon_aggregate_and_proof` topic is 17.15638, the same to v0.36.0 while in v0.37.0 we filter a lot of AggregateAndProof messages due to #4019

**Expected behavior**

Although there is no clear evidence that this downscore peers (#4084) as `beacon_aggregate_and_proof` p3 is fine, we should expect a smaller `meshMessageDeliveriesThreshold` scoring params as 70% of AggregateAndProof messages are filtered

**Comment by dapplion** [comment]
@tuyennhv Tho shouldn't score count messages before the app layer decides it's an IGNORE?

**Comment by twoeths** [comment]
> @tuyennhv Tho shouldn't score count messages before the app layer decides it's an IGNORE?

gossipsub only scores ACCEPT messages. Assuming there are 12 aggregators per slot/index and a peer delivers all of them to us on time. Previously we count 12 messages for this peer to score, but now we count only 2-3 first messages to score.

**Comment by twoeths** [comment]
gossip score is very good as of Nov 2023. Will refer back to this issue if needed.
