### ISSUE TITLE
Convert utils files to typescript

### ISSUE THREAD

**Issue by Mikerah** [ChainSafe/lodestar#41]
We have yet to convert the blake.js and bitfield.js files to typescript. This task is pretty straightforward.

**Comment by aunyks** [comment]
Where are these files in the source tree? I can't find them.  

I was gonna try tackling this if no one picked it up.

**Comment by GregTheGreek** [comment]
@aunyks, thanks for reaching out. Blake is no longer being used, in favour of keccak 256. 

Sorry about that I thought I closed everything relating to blake
