### ISSUE TITLE
Validate input on publish block endpoint

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#410]
Malicious user could start publishing invalid blocks to our endpoint which would cause our node to be block or blacklisted. 

In publish endpoint validation, block should at least check if block is signed with correct proposer and has valid prev state root.

**Comment by twoeths** [comment]
@mpetrunic I'm looking into this, please let me know if it's not ready to work on.

**Comment by mpetrunic** [comment]
@tuyennhv TBH there is so much checks that needs to be done that it would probably be best to run "dummy" state  transition from state new block is referencing. That said I'm pretty sure that if we add third state transition for same block (1. when producing, 2. when publishing, 3. when integrating into chain) our interop simulation would stop working. I'm hopping @ec2 can make state transition run concurently and/or speed up for this?!

**Comment by mpetrunic** [comment]
unstale
