### ISSUE TITLE
Consider using node-proper-lockfile instead of lockfile

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4102]
See https://github.com/moxystudio/node-proper-lockfile there are arguments in favor of switching. (recommended here https://stackoverflow.com/questions/35616281/how-can-i-lock-a-file-while-writing-to-it-asynchronously)

lockfile Github repo is archived too

Tho both libraries rely in https://github.com/tapjs/signal-exit/blob/main/index.js which does ugly tricks to work crossplatform.

Example of a nice implementation in Rust. However they can rely on the drop mechanics, which NodeJS does not have https://github.com/derekdreery/lockfile-rs/blob/master/src/lib.rs

**Comment by wemeetagain** [comment]
Maybe you can help them with converting to typescript / adding types :see_no_evil:

**Comment by dapplion** [comment]
> Maybe you can help them with converting to typescript / adding types see_no_evil

The API of both libraries is extremely simple we can lock version and type ourselves. This is more about how they mess with the process than anything else
