### ISSUE TITLE
Keymanager server does not persist keystore password

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4105]
**Describe the bug**

Reviewing Keymanager server code it seems it does not persist the keystore password. If you do the following actions:
- start validator
- import keystore via API
- restart validator

Does the validator start validating with the imported keystore?

**Expected behavior**

Keymanager server should persist imported data to keep validating after restarts

**Comment by wemeetagain** [comment]
Is this still an issue after https://github.com/ChainSafe/lodestar/pull/4201 ?

**Comment by dapplion** [comment]
Closed by https://github.com/ChainSafe/lodestar/pull/4106
