### ISSUE TITLE
REST api cors

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#411]
- should use some fastify cors middleware to properly implement it

**Comment by twoeths** [comment]
@mpetrunic  Since I had some works regarding REST, I think I can help with this if you're busy.

**Comment by mpetrunic** [comment]
@tuyennhv sure

**Comment by twoeths** [comment]
I suppose we'll do like `--rpccorsdomain` option of geth when starting beacon nodes: ```--rpccorsdomain value  Comma separated list of domains from which to accept cross origin requests (browser enforced)```
@mpetrunic please correct me if I'm wrong. Is this part of the spec somewhere?

**Comment by mpetrunic** [comment]
It's not speced, but yeah we want it like that
