### ISSUE TITLE
Review docs and any usage instructions

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4112]
In preparation for an external audit, our docs and public instructions must be up to date.

Please each Lodestar mantainer should review those and ensure instructions make sense for each one's environment and specific usage patterns.

_Please tick your box to signal the above_

- [ ] @wemeetagain 
- [ ] @tuyennhv 
- [ ] @g11tech 
- [ ] @dadepo 
- [x] @philknows 
- [ ] @dapplion

**Comment by philknows** [comment]
Referencing: https://chainsafe.github.io/lodestar/usage/testnet/#run-a-validator

Are there any other mandatory inclusions required for the validator client post-merge like `--defaultFeeRecipient` and/or `--strictFeeRecipientCheck` @g11tech ?

We should update this section for the additional mandatory parameters when running a validator. Unsure right now if this flag should be specified under `beacon`, `validator` or both?
