### ISSUE TITLE
Do not suggest npm install lodestar in guides, only dockerhub

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4113]
NPM dependencies suffer from supply chain attacks. We protect users against those with locked dependencies on repo installs (yarn.lock) + dependabot updates.

- See https://github.com/ChainSafe/lodestar/issues/3596

Due to this we should encourage users to only run pre-built docker images since those are guaranteed to install a pre-veted set of safe dependencies.

**TODO**

- [x] [Remove instructions to install from npm](https://github.com/ChainSafe/lodestar/pull/4115)
- [x] Add warning note to not install from npm

**Comment by philknows** [comment]
Is the warning note on the documentation itself or are there any other warning methods we should include with NPM installation @dapplion ?

**Comment by dapplion** [comment]
That's good!
