### ISSUE TITLE
Merge Info UX improvements

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#4133]
### UPDATE: Enlarging the scope of the issue to:
- Optimize the merge tracker
- Add merge metrics
- Add merge info logger
**Is your feature request related to a problem? Please describe.**

--------------------------------------------

Reference Lighthouse issue: https://github.com/sigp/lighthouse/issues/3249

This was mentioned in the Eth R&D chats as a beneficial UX opportunity for those running Lodestar awaiting the transition up to the merge. 

Currently Teku has this in their logs:
`teku    | 10:29:18.306 INFO  - TTD ETA: 0 days, 4 hours and 22 minutes (8 Jun 2022 - 14:51:48) - Current Total Difficulty: 0x00000000000000000000000000000000000000000000000000ace84463a84fd1`

**Describe the solution you'd like**

It would be good for Lodestar to periodically log a line that shows:
- Difficulty of last block in a non-hex format
- Total difficulty required to hit merge (re-iterates that the TTD settings are correct)
- ETA if we are able to get the hashrate or total avg difficulty of previous X blocks (whatever metric would be best to estimate)

**Comment by dapplion** [comment]
Sounds good! I support this

**Comment by dapplion** [comment]
Implementation guidelines for implementer

Create a new TimeSeries with more points (100) to track TTD

https://github.com/ChainSafe/lodestar/blob/684c2e3f0474e2558711ae682c940c5c644d59e0/packages/beacon-node/src/node/notifier.ts#L33

ttd should be exposed on a getter on this class

https://github.com/ChainSafe/lodestar/blob/684c2e3f0474e2558711ae682c940c5c644d59e0/packages/beacon-node/src/eth1/eth1MergeBlockTracker.ts#L43

everytime it fetches a block, persist the max TD seen in a variable `this.maxTD`. Then this variable should be re-used in a counter collect fn

**Comment by g11tech** [comment]
working on this now
