### ISSUE TITLE
Drop Validator.stop() feature

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4138]
Allowing classes to stop and start adds complexity that propagates upstream.

The Validator clock and api clients are a bit awkward for that reason, see
- https://github.com/ChainSafe/lodestar/pull/4108

Is there any opposition to dropping this feature? We dropped this intermediary steps in Lodestar classes a long while ago and simplified things a lot.

**Comment by wemeetagain** [comment]
I'm all for it. It simplified the beacon node and imo the same should be applied here.

**Comment by philknows** [comment]
I know ChainGuardian is deprecated at this point (I believe they were using it?), but unsure if anybody else is using this as part of their integrations to Lodestar. @yorickdowne & @stefa2k, does this affect your projects? Either way, I'm in favour of simplicity and would suggest anybody who's using this still to figure a workaround unless there's some hard objections.

**Comment by stefa2k** [comment]
> I know ChainGuardian is deprecated at this point (I believe they were using it?), but unsure if anybody else is using this as part of their integrations to Lodestar. @yorickdowne & @stefa2k, does this affect your projects? Either way, I'm in favour of simplicity and would suggest anybody who's using this still to figure a workaround unless there's some hard objections.

No issues with that, we stopped supporting lodestar in the past but looking into it in the near future with Stereum 2.x

**Comment by philknows** [comment]
Let us know when you're ready to have Lodestar in there again and what requirements we may be missing to make it happen @stefa2k ! Thanks.

**Comment by yorickdowne** [comment]
We are supporting Lodestar and do not use this feature.

**Comment by stefa2k** [comment]
> Let us know when you're ready to have Lodestar in there again and what requirements we may be missing to make it happen @stefa2k ! Thanks.

FYI to keep track with our progress: https://github.com/stereum-dev/ethereum-node/issues/385

**Comment by wemeetagain** [comment]
Resolved this issue with #4178
