### ISSUE TITLE
libp2p-noise handshake performance

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4140]
Investigate why libp2p-noise handshake takes > 7% of cpu time

[0522_contabo_20_subscribe_all_subnets.cpuprofile.zip](https://github.com/ChainSafe/js-libp2p-gossipsub/files/8877992/0522_contabo_20_subscribe_all_subnets.cpuprofile.zip)

<img width="1191" alt="Screen Shot 2022-06-10 at 17 16 09" src="https://user-images.githubusercontent.com/10568965/173044625-fb630603-6b1d-4971-a98a-efc3c3a98198.png">

**Comment by dapplion** [comment]
- @tuyennhv  see https://github.com/ChainSafe/lodestar/issues/3465

**Comment by twoeths** [comment]
this function takes time

<img width="939" alt="Screen Shot 2022-06-20 at 10 08 20" src="https://user-images.githubusercontent.com/10568965/174518361-19545ae9-9a8c-4ba4-8057-6f97e54253ae.png">

**Comment by twoeths** [comment]
@dapplion the hot path is at `chaCha20Poly1305` encrypt/decrypt, not at `x25519.js`

<img width="1274" alt="Screen Shot 2022-06-20 at 10 46 21" src="https://user-images.githubusercontent.com/10568965/174521732-84d7254d-e846-478f-9a5a-48ef24e8a531.png">

<img width="1285" alt="Screen Shot 2022-06-20 at 10 47 22" src="https://user-images.githubusercontent.com/10568965/174521833-a36ab104-5f8c-456c-b511-661511c5c431.png">

**Comment by wemeetagain** [comment]
looks like `nonce` and the DataView can be created once in the constructor and overwritten and returned each time.
not sure if its worth it given chachapoly1305 is the hot path.
Take a look at the last comment in #3465 where someone swaps in a native implementation of chachapoly1305 with our noise implementation.

**Comment by twoeths** [comment]
`nonceToBytes()` takes > 1% of cpu time, it's all most the time we call `as-sha256.digest()` or uncompress gossip messages so I think it's worth to improve it if we can

<img width="1279" alt="Screen Shot 2022-06-21 at 09 58 25" src="https://user-images.githubusercontent.com/10568965/174706989-d5218c17-c92d-41ed-8a9a-738b5c5b287f.png">

<img width="1282" alt="Screen Shot 2022-06-21 at 10 05 55" src="https://user-images.githubusercontent.com/10568965/174707829-4aaa0c10-1f48-40ee-8e8d-82b7528182a9.png">



right now we maintain an uint, call `nonceToBytes()` and increase it every time we encrypt/decrypt. We can instead maintain Uint8Array, no need to call `nonceToBytes()` and do the increasement manually with Uint8Array. Need to write a performance test to see if it's better

**Comment by twoeths** [comment]
> looks like `nonce` and the DataView can be created once in the constructor and overwritten and returned each time.
not sure if its worth it given chachapoly1305 is the hot path.

@wemeetagain yeah that's the best way, even better than we increase Uint8Array by 1 manually
```
Increase nonce from 1e6 to 2e6:

nonceToBytes x 2.20 ops/sec ±1.79% (10 runs sampled)
increaseBytes x 472 ops/sec ±0.49% (89 runs sampled)
maintain same DataView x 679 ops/sec ±0.64% (88 runs sampled)
```

this is the same optimization @dapplion did for ssz where he maintained both Uint8Array and DataView, in our a case we should represent a Nonce as an `uint`, Uint8Array and DataView

**Comment by dapplion** [comment]
> nonceToBytes() takes > 1% of cpu time, it's all most the time we call as-sha256.digest() or uncompress gossip messages so I think it's worth to improve it if we can

Agree it's worth improving it as the fix is really simple :+1:
