### ISSUE TITLE
Grafana Dashboard Tracker

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#4143]
**Is your feature request related to a problem? Please describe.**

We have a lot of metrics that are 'hidden'

**Describe the solution you'd like**

Add missing charts

**Comment by philknows** [comment]
Anything related specifically to https://github.com/ChainSafe/lodestar/issues/2468 ? Should we just keep the list of charts we want to add in there?

**Comment by philknows** [comment]
Repurposing this issue to track adding metrics for dashboard.

**Comment by dapplion** [comment]
- Metrics addition are best tracked with https://github.com/ChainSafe/lodestar/issues/2468
