### ISSUE TITLE
Improve js-wasm time

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4154]
**Describe the bug**

It takes 4.64% of cpu time to call wasm function, the only function we call wasm for now is `digest()` (as-sha256 hash)

<img width="1301" alt="Screen Shot 2022-06-14 at 16 14 29" src="https://user-images.githubusercontent.com/10568965/173541144-e94deea5-cffe-40a8-9bb3-91ce7da894ac.png">

[0614-subscribeAllSubnets-contabo-20.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/8898313/0614-subscribeAllSubnets-contabo-20.cpuprofile.zip)

**Expected behavior**

Find a way to reduce the time for it

**Comment by dapplion** [comment]
@tuyennhv To reduce this time we would need to optimize hashing which is already pretty optimized. This looks like a very hard target to optimize currently.
