### ISSUE TITLE
Add sepolia network

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#4160]
**Is your feature request related to a problem? Please describe.**

Sepolia beacon chain configs have been released:
https://github.com/eth-clients/merge-testnets/tree/main/sepolia

Genesis is set for: Mon Jun 20 2022 14:00:00 UTC

**Describe the solution you'd like**

- Add `--network sepolia` config

**Comment by q9f** [comment]
Is anyone working on this? I wanted to run my validators on Lodestar.

**Comment by q9f** [comment]
Config: https://github.com/eth-clients/merge-testnets/pull/14

**Comment by dapplion** [comment]
@q9f PR race condition hahaha
