### ISSUE TITLE
Fix bad block detection

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#417]
Currently every block that fails state transition is marked as invalid. If block comes too late/too early if will be marked as invalid and we won't be able to include it ever.

Not sure about best solution^^

**Comment by ColinSchwarz** [comment]
Handle out of order blocks. Ignore blocks with unknown/incorrect previous block root
.

**Comment by mpetrunic** [comment]
Check if block.parentRoot matches`signingRoot(state.latestBlockHeader, config.types.BeaconBlockHeader)`?
