### ISSUE TITLE
Edgecase in release process

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#4173]
**Is your feature request related to a problem? Please describe.**

During the release of v0.38.1, some issues arose.

- We wanted a stable release with sepolia config (PR #4164)
- #4164 did not apply cleanly to `stable`, built off changes from other PRs
- Cherry-picking #4164 onto `stable` (branch `rc/v0.38.1`) required fixing merge conflicts
- Finishing the release process, we now cannot merge `stable` back to `unstable` due to merge conflicts - see https://github.com/ChainSafe/lodestar/pull/4172
- `stable` cannot be modified to fix the conflicts, it is ridiculous to modify `unstable` to fix the conflicts

**Describe the solution you'd like**

- only merge `stable` to `unstable` on  major / non-hotfix releases

**Comment by q9f** [comment]
We have discussed this before, I would not merge stable back into unstable. Just archive old release tracks.

**Comment by wemeetagain** [comment]
We recently changed our release process specifically to address the shortcoming(?) that release tracks were not merged back into unstable.  @dapplion 

But if we don't merge back to unstable, we would just need to figure out / document  how / when to bump the versions in package.jsons.
Current flow is:
- create rc branch, bump package.json versions there (eg: v0.37.1 -> v0.38.0)
- eventually the rc branch is merged to stable
- then stable is merged back to unstable, bumping the version there

**Comment by dapplion** [comment]
Fixed the conflicts and merged stable into unstable here https://github.com/ChainSafe/lodestar/commit/2eeb965d24a92c495e8fa93944426505f826e59a

I disabled branch protections temporarily to do the push
