### ISSUE TITLE
Set up public ropsten server

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#4176]
We've got public mainnet, prater, kiln servers. We should have a public ropsten server too.

From discord: https://discord.com/channels/593655374469660673/621838504955084830/988448063523795045
```
Hello! I just wanted to check if there is a Ropsten Lodestar test server yet?
```

**Comment by philknows** [comment]
@claravanstaden the endpoint  https://lodestar-ropsten.chainsafe.io/ has been setup. Currently syncing and we can close this as soon as we confirm the endpoint works! :)

**Comment by claravanstaden** [comment]
@philknows awesome, thank you! I will test it out today. 👌

**Comment by claravanstaden** [comment]
@philknows I tested the server and found this issue so far:

`curl https://lodestar-ropsten.chainsafe.io/eth/v1/light_client/updates\?start_period\=25\&count\=1`

`{"statusCode":500,"error":"Internal Server Error","message":"No partialUpdate available for period 25"}`

If I look at https://ropsten.beaconcha.in/, the current epoch is `6676` / `256` = `26`, so period `25` should give an update. I tried other periods as well, none have worked so far.

**Comment by philknows** [comment]
Are you able to sync from a more recent period at all @claravanstaden ?

**Comment by claravanstaden** [comment]
The current period now is 30 (slot `250,078` / `32` / `256`) and I can't get a committee update for this period, neither for period `29` so perhaps there is a setup issue of some sorts? 🤔 

This is my request:
`curl https://lodestar-ropsten.chainsafe.io/eth/v1/lightclient/committee_updates\?from\=29\&to\=29`

**Comment by philknows** [comment]
Completed.
