### ISSUE TITLE
UX improvement: Log on cli a big more verbose on the slashing protection import/export

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#4184]
A discord user was not able to successfully import the slashing protection db from `teku`.

Try it out fix/file any issues that come up with the functionality

UPDATE: the user was successfully able to import, with the final log dump of (which could take its own sweet time)
```
Export/Import completed successfully
```
A more progress oriented logging could help the user not get confused if the import/export is happening or the cli is just stuck.

**Comment by g11tech** [comment]
UPDATE:
Export and Import on lodestar db works, with just one final message of 
```
Export/Import completed successfully
```

**Comment by dapplion** [comment]
> UPDATE: Export and Import on lodestar db works, missing sufficient logging with just one final messgae of
> 
> ```
> Export/Import completed successfully
> ```

The CLI should log that tho, aren't these messages showing up in stdout?

https://github.com/ChainSafe/lodestar/blob/f15a8a9df45cf4672ee3c131f28e44274625e309/packages/cli/src/cmds/validator/slashingProtection/export.ts#L45

https://github.com/ChainSafe/lodestar/blob/f15a8a9df45cf4672ee3c131f28e44274625e309/packages/cli/src/cmds/validator/slashingProtection/import.ts#L43

**Comment by g11tech** [comment]
> 

only these are coming :slightly_smiling_face: , let me cleanup the description for clarity

**Comment by philknows** [comment]
Would it make more sense for it to say what is being imported/exported? Something like: `Slashing protection DB import/export completed successfully`
