### ISSUE TITLE
Timeout downloading weak subjectivity state

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4190]
**Describe the bug**

Got this error when trying to download a weak subjectivity state:

```
Jun 24 14:40:11 contabo-7 beacon_run.sh[2384756]:  ✖ Error: Unable to fetch weak subjectivity state: Timeout request
Jun 24 14:40:11 contabo-7 beacon_run.sh[2384756]:     at fetchWeakSubjectivityState (file:///usr/src/lodestar/packages/cli/src/networks/index.ts:190:11)
Jun 24 14:40:11 contabo-7 beacon_run.sh[2384756]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Jun 24 14:40:11 contabo-7 beacon_run.sh[2384756]:     at initFromWSState (file:///usr/src/lodestar/packages/cli/src/cmds/beacon/initBeaconState.ts:153:37)
Jun 24 14:40:11 contabo-7 beacon_run.sh[2384756]:     at initBeaconState (file:///usr/src/lodestar/packages/cli/src/cmds/beacon/initBeaconState.ts:94:12)
Jun 24 14:40:11 contabo-7 beacon_run.sh[2384756]:     at Object.beaconHandler [as handler] (file:///usr/src/lodestar/packages/cli/src/cmds/beacon/handler.ts:68:41)
```

**Expected behavior**

Since the state is big, we should be able to increase the timeout at client api when downloading a state

**Steps to Reproduce**

Use below param:
```
weakSubjectivitySyncLatest: "true"
weakSubjectivityServerUrl: "https://some-server.io"
weakSubjectivityCheckpoint: "checkpoint:epoch"
```

**Comment by dapplion** [comment]
What's the current timeout? It should also log the timeout time for better debugging

**Comment by g11tech** [comment]
60 seconds (`60_000`) is the default timeout which is also applicable here as we don't provide any, 

I think its sufficient for for 150/200MB downloading state (and most of time i have seen timeouts happening when server is genrally super slow or network is really very bad).

In this scenario others can offline download it (octect stream) via `curl` and dump into file (we can may be throw the command here) and provide that, may be we can log this message in the timeout error here

Because the issue with really big timeouts with (for really slow networks) would be to log status on the cli else the user wiil go wondering if lodestar is stuck

**Comment by twoeths** [comment]
> I think its sufficient for for 150/200MB downloading state (and most of time i have seen timeouts happening when server is genrally super slow or network is really very bad).

it usually takes more than 60s to download state:
- contabo-20: 1m57s
```
devops@contabo-20:~$ curl -H 'Accept: application/octet-stream' https://***.infura.io/eth/v2/debug/beacon/states/3367104 --output state_3367104.ssz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 49.8M    0 49.8M    0     0   434k      0 --:--:--  0:01:57 --:--:--  884k
```
- hetzner-test0: 3m1s
```
devops@hetzner-test0:~/tuyen/beacon$ curl -H 'Accept: application/octet-stream' https://***.infura.io/eth/v2/debug/beacon/states/3367104 --output state_3367104.ssz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 49.8M    0 49.8M    0     0   281k      0 --:--:--  0:03:01 --:--:--  871k
```
- my localhost: 2m21s
```
Tuyens-MacBook-Pro-16519:Downloads tuyennguyen$ curl -H 'Accept: application/octet-stream' https://***eth2-beacon-prater.infura.io/eth/v2/debug/beacon/states/3367104 --output state_3367104.ssz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 49.8M    0 49.8M    0     0   359k      0 --:--:--  0:02:21 --:--:--  320k
```

> Because the issue with really big timeouts with (for really slow networks) would be to log status on the cli else the user wiil go wondering if lodestar is stuck

this is a valid concern 👍 , I think it's a matter of UX, not with the timeout. One thing we can do is periodically log to the screen while waiting for all state bytes to be downloaded

> In this scenario others can offline download it (octect stream) via curl and dump into file (we can may be throw the command here) and provide that, may be we can log this message in the timeout error here

this is a good idea, we should improve our log to instruct users to do that

**Comment by g11tech** [comment]
@tuyennhv thanks for the stats! is infura super slow generally or have speed rationing? very poor download speeds seems like.

In this case I would propose make kick it to 5 mins. multiple logs will take care of UX.

**Comment by twoeths** [comment]
> @tuyennhv thanks for the stats! is infura super slow generally or have speed rationing? very poor download speeds seems like.

I'm not sure if that's the specific issue of infura or not since the node usually have to regen state (we store state per 1024 epochs)

> In this case I would propose make kick it to 5 mins. multiple logs will take care of UX.

I increased that to 5 mins in the PR 👍
