### ISSUE TITLE
Sepolia release before Jun 29th

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4207]
- [x] Update sepolia TTD to `17000000000000000`
- [x] Update infra with this override
- [x] Have a release before Jun 29th with the value

**Comment by philknows** [comment]
My suggestion at this point with `v0.39.0-rc.0` in beta is we just cherrypick these commits and add them to `v0.39.0-rc.1` for release. And we can consider throwing in a `v0.40.0-rc.0` shortly for all the new stuff getting merged in for the audit @dapplion . For discussion at standup.

**Comment by wemeetagain** [comment]
0.39.0 released with sepolia support and proper ttd
