### ISSUE TITLE
Upgrade fastify to v4.x

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#4219]
Currently at 3.x

The dependencies (fastify-cors, etc) and their types are not great, should all be updated

**Comment by dapplion** [comment]
@wemeetagain is there any specific reason to bump besides the types? Check the changelog if there many changes that we want

**Comment by wemeetagain** [comment]
I had problems during #4114 with their types

**Comment by wemeetagain** [comment]
Also seeing this at startup time:
```
(node:1506517) [FST_MODULE_DEP_FASTIFY-CORS] FastifyWarning.fastify-cors: fastify-cors has been deprecated. Use @fastify/cors@7.0.0 instead.
```

**Comment by philknows** [comment]
We should discuss the priority on this one @dapplion

**Comment by mpetrunic** [comment]
FYI you don't have to update to 4.x to fix that. You have versions here https://github.com/ChainSafe/gavel-server/pull/1/files if you want to stay at version 3.

Not sure how stable 4.x is since they released it a month or two ago and they seem to be pushing a lot of fixes.

**Comment by wemeetagain** [comment]
Already updated to 4.15.0.
