### ISSUE TITLE
export only required public variables - no export *

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4222]
- From https://github.com/ChainSafe/lodestar/issues/3116

export * is too vague, exposes too many items to consumers. The public API should be though of with care and only expose what we expect to be used.

Otherwise it's very hard to mantain semver and ensure no breaking changes if all the internals are exposed like YOLO

**Comment by wemeetagain** [comment]
I think we should still expose internals via subpath exports with a 'use at your own risk' disclaimer and no semver guarantees.
Top-level export would still be curated exports following this issue.
