### ISSUE TITLE
Gateway Time-out downloading beacon state from lodestar-prater server

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4232]
**Describe the bug**

```
devops@contabo-20:~$ curl -H 'Accept: application/octet-stream' https://lodestar-prater.chainsafe.io/eth/v2/debug/beacon/states/3367104 --output state_3367104_v2.ssz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   132  100   132    0     0      2      0  0:01:06  0:01:00  0:00:06    33
```

```
devops@contabo-20:~$ cat state_3367104_v2.ssz
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
```

I can download the state the other time
```
devops@contabo-20:~$ curl -H 'Accept: application/octet-stream' https://lodestar-prater.chainsafe.io/eth/v2/debug/beacon/states/3367104 --output state_3367104_v2.ssz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 49.8M  100 49.8M    0     0   845k      0  0:01:00  0:01:00 --:--:-- 5074k
```

**Expected behavior**

No error in all cases

**Comment by twoeths** [comment]
figured out that the issue happened with contabo and hetzner cloud provider, not with my local environment, so not sure what we can do here. Is it something related to the client network configuration, not the server side 🤔 ?

**Comment by dapplion** [comment]
Should really have the debug route enabled? This is a big DOS vector for unsecured servers like this. @tuyennhv why do you need to pull the state from this node specifically?

**Comment by twoeths** [comment]
> enabled? This is a big DOS vector for unsecured servers like this. @tuyennhv why do you need to pull the state from this node s

I wanted to benchmark the time to download state (in comparison to infura, for example)

**Comment by dapplion** [comment]
Closing issues for specific incidents on old versions of Lodestar, please re-open if it happens with latest stable
