### ISSUE TITLE
docs: FAQ for Common Errors 

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#4233]
**Is your feature request related to a problem? Please describe.**

General users of Lodestar usually inquire in the #troubleshoot channel due to common errors that may show up during setup.

**Describe the solution you'd like**

We can avoid duplicate and individual problem solving which requires resources by providing an FAQ in our documents which cover common errors received by our users. Discord context usually gets lost, so having a page specifically addressing these is more useful and accessible.

**Comment by dapplion** [comment]
Sounds good!

**Comment by philknows** [comment]
Some additional points to add to this document:

Better explain logging output of Lodestar. Explain:
- info: 1 local keystores (means detection of keystore file)
- info: Discovered new validators count=0 (means no newly activated validators that correspond to your local validators were found - You will see `1` when your validator becomes activated by the beacon chain.) 
- Grafana Dashboard: You will not see "validators connected = 1" until that validator activation has happened.
- Add info about how to check your validator status using beaconcha.in

**Comment by philknows** [comment]
Add info about what this means when Eth execution node is not fully synced:

consensus_1             | Error: BLOCK_ERROR_EXECUTION_ERROR
consensus_1             |     at verifyBlockStateTransition (file:///usr/app/node_modules/@lodestar/beacon-node/src/chain/blocks/verifyBlock.ts:286:15)
consensus_1             |     at runMicrotasks (<anonymous>)

**Comment by philknows** [comment]
Superseded by #5961
