### ISSUE TITLE
Trial code freeze during release testing

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4242]
Some pain points of git flow that we are encountering:

- merge conflicts bringing stable into unstable
- merge squash vs regular merge, clicking the wrong button on Github

Both of this issues would not happen if we do a code freeze during beta testing. However we won't be able to
- Merge feature branches during beta testing
- Do parallel releases (minor + patch)
- Do hot-fixes on top of stable (check if this is correct)

We should try this for v0.41.0 or v0.42.0 to check how the pros vs cons feel

**Comment by wemeetagain** [comment]
I think we are happy with our current process. Do you want to close this?
