### ISSUE TITLE
No block found for id 'head'

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4250]
**Describe the bug**

Lodestar can not always server the head block. This logs are captured from a host running a metrics exporter https://github.com/samcm/ethereum-metrics-exporter

- From https://github.com/gnosischain/consensus-deployment-ansible/issues/9

```
error: Req req-1n getBlockV2 error  No block found for id 'head'
error: Req req-1w getBlockHeader error  No block found for id 'head'
error: Req req-1y getBlockHeader error  No block found for id 'head'
error: Req req-1z getBlockV2 error  No block found for id 'head'
```
```
Jun-30 14:00:59.337[API]             error: Req req-e getBlockV2 error  No block found for id 'head'
Error: No block found for id 'head'
    at resolveBlockId (file:///usr/app/node_modules/@chainsafe/lodestar/src/api/impl/beacon/blocks/utils.ts:33:11)
    at Object.getBlockV2 (file:///usr/app/node_modules/@chainsafe/lodestar/src/api/impl/beacon/blocks/index.ts:105:21)
    at Object.handler (file:///usr/app/node_modules/@chainsafe/lodestar-api/src/utils/server/genericJsonServer.ts:39:23)
```

I think it's because it sets the fork-choice head first, then persist the block to DB.

To fix either:
- persist block before setting as head
- keep a db cache recent blocks, or only the head for the case before persisting

**Expected behavior**

Always have the head block available

**Comment by dapplion** [comment]
TODO on another issue:
```
Jul-03 04:44:46.921[API]             error: Req req-m250 getBlockV2 error  No block found for id 'finalized'
```

**Comment by philknows** [comment]
Is this still an issue? I'm not seeing this anymore as of v1.11.3

**Comment by nflaig** [comment]
> persist block before setting as head

Has been implemented, I don't think this is an issue anymore
