### ISSUE TITLE
Multiple simultaneous ping and status requests

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#4252]
**Describe the bug**

Exposed during #4114 

In [`PeerManager#onLibp2pPeerConnect`](https://github.com/ChainSafe/lodestar/blob/unstable/packages/beacon-node/src/network/peers/peerManager.ts#L517), ping and status messages [are triggered](https://github.com/ChainSafe/lodestar/blob/unstable/packages/beacon-node/src/network/peers/peerManager.ts#L548).

When multiple peer:connect events are triggered one after the other, multiple simultaneous pings to a single peer can be executed. This happens because each `peer.lastReceivedMsgUnixTsMs` is checked before executing a ping, and this happens every call to `pingAndStatusTimeouts`. `peer.lastReceivedMsgUnixTxMs` doesn't have a chance to update until after a single ping is completed.

This same thing also happens with status requests for a similar reason.

**Expected behavior**

no simultaneous ping or status requests to a peer.

**Comment by philknows** [comment]
Reopen if it's still an issue. Libp2p has had lots of updates since.
