### ISSUE TITLE
Validator shouldn't try connecting to the beacon node for slashing protection export/import

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#4259]
Tried to export the logs for a db where beacon node was shut down: got this:

```typescript
Use `node --trace-warnings ...` to show where the warning was created)
 ✖ FetchError: request to http://127.0.0.1:9596/eth/v1/beacon/genesis failed, reason: connect ECONNREFUSED 127.0.0.1:9596
    at ClientRequest.<anonymous> (/usr/app/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:527:28)
    at Socket.socketErrorListener (node:_http_client:454:9)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
Investigate and see if we really need this

**Comment by dapplion** [comment]
@g11tech It needs the genesisValidatorsRoot for the export

https://github.com/ChainSafe/lodestar/blob/266f9e2f4418676c9b070bd0f64d1a755cb8e38e/packages/validator/src/slashingProtection/interchange/formats/v5.ts#L13-L18

**Comment by g11tech** [comment]
> @g11tech It needs the genesisValidatorsRoot for the export
> 
> https://github.com/ChainSafe/lodestar/blob/266f9e2f4418676c9b070bd0f64d1a755cb8e38e/packages/validator/src/slashingProtection/interchange/formats/v5.ts#L13-L18

i think for the known networks we know this value https://github.com/ChainSafe/lodestar/blob/unstable/packages/light-client/src/networks.ts, so guess we can skip :thinking: 
(may be with an explicit flag?)

although this isn't high priority, but we can push it as a side UX improvement job

**Comment by dapplion** [comment]
> i think for the known networks we know this value https://github.com/ChainSafe/lodestar/blob/unstable/packages/light-client/src/networks.ts, so guess we can skip thinking

Using known values for common networks is a great idea! Feel free to implement
