### ISSUE TITLE
Incorrect old balances in computeDeltas

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4266]
**Describe the bug**

The `computeDeltas()` function has an old balances and new balances params but right now we always put same justified balances of store to both of them

(https://github.com/ChainSafe/lodestar/blob/v0.39.0/packages/fork-choice/src/forkChoice/forkChoice.ts#L190)

**Expected behavior**

We should keep the own balances (as old balances, what reflect the weights in ProtoArray) somewhere, and forkchoice store should give new justified balances to `computeDeltas()`. The implication is we want to reflect the weight of votes if effective balances of validators get changed.

Refer to lighthouse for a reference implementation.

**Comment by dapplion** [comment]
Right! Notice this also when working on this issue. What are the implications of always passing the same pair of new and old balances?

**Comment by twoeths** [comment]
> Right! Notice this also when working on this issue. What are the implications of always passing the same pair of new and old balances?

the impact is not much because effective balances of a validator are rarely updated per epoch, we also passed forkchoice spec tests for a while

**Comment by dapplion** [comment]
> > Right! Notice this also when working on this issue. What are the implications of always passing the same pair of new and old balances?
> 
> the impact is not much because effective balances of a validator are rarely updated per epoch, we also passed forkchoice spec tests for a while

It's okay to devote most efforts on making Lodestar perform well on good network conditions. But it's equally important to make sure it works correctly under adverse network conditions. Differences in fork-choice logic between clients can be grounds for attack, so everyone must follow the same spec to ensure a safe network
