### ISSUE TITLE
API reference guide links are broken 

### ISSUE THREAD

**Issue by nazarhussain** [ChainSafe/lodestar#4268]
**Describe the bug**

There are few API reference on the documentation sites which have broken links. These links are mentioned on main docs [site](https://chainsafe.github.io/lodestar/packages/). 

Broken Links 

- https://chainsafe.github.io/lodestar/packages/lodestar-cli
- https://chainsafe.github.io/lodestar/packages/lodestar-validator
- https://chainsafe.github.io/lodestar/packages/lodestar-utils
- https://chainsafe.github.io/lodestar/packages/lodestar-types
- https://chainsafe.github.io/lodestar/packages/lodestar-spec-test-util
- https://chainsafe.github.io/lodestar/packages/lodestar-params
- https://chainsafe.github.io/lodestar/packages/lodestar-config

**Expected behavior**

All the links on the website should be live. 

**Screenshots**

<img width="479" alt="image" src="https://user-images.githubusercontent.com/112468/178013262-760886e5-05b5-4473-bc32-c9913fed2885.png">

**Comment by dapplion** [comment]
@wemeetagain should we just delete the typedoc documentation? I have never used it or seen someone using it since 2020

**Comment by wemeetagain** [comment]
Yea i think we can delete for now. I think it would be nice to have some api docs (especially for things like the config, types, api, lightclient, etc). But it might just be better to start from a clean slate.

**Comment by dapplion** [comment]
- Closing for https://github.com/ChainSafe/lodestar/issues/4311
