### ISSUE TITLE
Improve getStateForJustifiedBalances

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4284]
https://github.com/ChainSafe/lodestar/blob/6ed5ae07836be938e2a993fc3a7d6b51aaeb9f4c/packages/beacon-node/src/chain/blocks/importBlock.ts#L351

Returns the closest state to postState.currentJustifiedCheckpoint in the same fork as postState. It's a least-worst solution to make the ForkChoice sync while we don't provide full bounded regen capabilities.

By order of priority `getStateForJustifiedBalances` must return:
- Checkpoint state at justifiedCheckpoint = exact balances
- Some state descendant of justifiedCheckpoint.root at justifiedCheckpoint.epoch = exact balances
- Some state descendant of justifiedCheckpoint.root at an epoch greater than justifiedCheckpoint.epoch
- Some state part of justifiedCheckpoint.root chain at an epoch less than justifiedCheckpoint.epoch

CC: @tuyennhv

**Comment by wemeetagain** [comment]
- @twoeths I believe this was resolved with #4290 ?

**Comment by twoeths** [comment]
yes, we don't need to get justified state in order to get balancers, we cached balances by checkpoint in that PR
