### ISSUE TITLE
Eth2 Key Manager API: ERR_INTERCHANGE_UNSUPPORTED_VERSION

### ISSUE THREAD

**Issue by tdahar** [ChainSafe/lodestar#4295]
**Describe the bug**
When trying to import validators through the API the client answers with "interchange version error"
To run the client:
```
./lodestar validator --network kiln --rootDir="../lodestar-beacondata" --keymanagerEnabled
```
The request is the following:
```
curl --location --request POST 'http://localhost:5062/eth/v1/keystores' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer api-token-0xd4ae5f49b2a0e991b2cc1a970ef80ccf3d1b5a6c68bd41d8a1d5c47882ab5a19' \
--data-raw '{
    "keystores": [
        "{\"crypto\":....
   ],
"password": [ "xxx"]
```

**Expected behavior**

It was expected to receive an "imported" answer or a "success" answer
**Steps to Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu
- Version: v0.39.0
- Branch: unstable
- Commit hash: d84e1d970fd075a9a5747ad3cd5530fa2b9a962c
- Network: kiln

**Comment by dapplion** [comment]
Hey @tdahar thanks for reporting! Could you dump here the full POST data object you are sending to `/eth/v1/keystores` (dropping the keystores crypto). Did you provide any slashing protection data?

**Comment by tdahar** [comment]
Hey, sure this is the JSON body:
```
{
    "keystores": [
        "{\"crypto\": {\"kdf\": {\"function\": \"scrypt\", \"params\": {\"dklen\": 32, \"n\": 262144, \"r\": 8, \"p\": 1, \"salt\": \"xxx\"}, \"message\": \"\"}, \"checksum\": {\"function\": \"sha256\", \"params\": {}, \"message\": \"xxx\"}, \"cipher\": {\"function\": \"aes-128-ctr\", \"params\": {\"iv\": \"xxx\"}, \"message\": \"xxx\"}}, \"description\": \"\", \"pubkey\": \"xxx\", \"path\": \"m/12381/3600/250/0/0\", \"uuid\": \"xxx-xxx\", \"version\": 4}"
    ],
    "passwords": [
        "xxx"
    ],
    "slashing_protection": "{\"metadata\":{\"interchange_format_version\":\"5\",\"genesis_validators_root\":\"xxx\"},\"data\":[{\"pubkey\":\"xxx\",\"signed_blocks\":[],\"signed_attestations\":[{\"source_epoch\":\"27635\",\"target_epoch\":\"27636\"},{\"source_epoch\":\"27636\",\"target_epoch\":\"27637\",\"signing_root\":\"xxx\"}]}]}"
}
```
All the data you can see here is the output of the staking-deposit-cli and the slashin protection is extracted from the delete method when using the Eth2 Key Manager API from another clients.
Please let me know if you need anything else :)
