### ISSUE TITLE
Remove assertCorrectProgressiveBalances cli option

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#4300]
Seems like it could/should just be 'always on'

_Originally posted by @wemeetagain in https://github.com/ChainSafe/lodestar/pull/4294#discussion_r921234311_

**Comment by dapplion** [comment]
Progressive balances are and will always be kinda optional. Since not used for hard consensus making the check always mandatory is extremely dangerous as they could brick networks if our assumptions are wrong.
