### ISSUE TITLE
Separate dashboard for nodes on different networks 

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#4332]
**Is your feature request related to a problem? Please describe.**

This request is to assist with the release candidate process. The problem is being able to easily compare release candidates on Prater/Goerli easily with previous stable releases. 

**Describe the solution you'd like**

A dashboard that allows us to select specific nodes in a specific network would be useful. For example, if we just want to narrow it down to prater nodes to look at release candidate metrics and filter out the noise from everything else, there should be an easy way to do so.

**Comment by dapplion** [comment]
Our dashboard already supports that: just add an adhoc filter `network = prater

![Screenshot from 2022-07-20 12-03-24](https://user-images.githubusercontent.com/35266934/179955802-bd141bf4-3586-4aaa-bfb4-e5eb78b434dd.png)
`
