### ISSUE TITLE
Improve jsonRPC error UX for eth1 + execution

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#4348]
As brought to notice by a discord user `seamonkey`, sometimes because of the nodejs engine intermittent loading or the execution engine's intermittent loading the json rpc api can throw harmless intermittent errors like `UNAVAILABLE`, `TIMEOUT` like these

![image](https://user-images.githubusercontent.com/76567250/181221482-3d5cd828-3f15-4ead-b728-0b4fdee9cc4c.png)

However these give users not so good experience, and hence we need to have an error accumulator for such unavailable errors and log the throw only if counter surpasses.

**Comment by g11tech** [comment]
will be picking this up

**Comment by nazarhussain** [comment]
@g11tech We already have a delay set for such cases of errors. 

https://github.com/ChainSafe/lodestar/blob/6ac8c07023bc72c7ef54a6ea66884790793eda21/packages/beacon-node/src/eth1/eth1DepositDataTracker.ts#L182-L186

And the http errors `UNAVAILABLE` or `TIMEOUT` can actually be fatal. We can increase the wait time which is `1s` right now, so such errors don't show a lot such errors in case the endpoint if momentarily not available. What do you think?

**Comment by g11tech** [comment]
> @g11tech We already have a delay set for such cases of errors.
> 
> https://github.com/ChainSafe/lodestar/blob/6ac8c07023bc72c7ef54a6ea66884790793eda21/packages/beacon-node/src/eth1/eth1DepositDataTracker.ts#L182-L186
> 
> And the http errors `UNAVAILABLE` or `TIMEOUT` can actually be fatal. We can increase the wait time which is `1s` right now, so such errors don't show a lot such errors in case the endpoint if momentarily not available. What do you think?

its not about wait time but sort of debounce the error .... like how we do for engine coming offfline online etc. so 1 error for state change
