### ISSUE TITLE
No "exports" main defined in @chainsafe/lodestar-api/package.json

### ISSUE THREAD

**Issue by oblak1** [ChainSafe/lodestar#4349]
**Describe the bug**
I'm trying to index beacon chain with _@chainsafe/lodestar-api_ version 0.39.0 but I keep getting  this error:
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /node_modules/@chainsafe/lodestar-api/package.json
    at new NodeError (node:internal/errors:372:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:472:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:693:7)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/explorer/multichain-explorer/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

I'm trying to use getClient method. I'm using node v16 with yarn 1.x (monorepo setup) on Ubuntu, running it with ts-node in development mode.

```
import { getClient } from '@chainsafe/lodestar-api';
import { config } from '@chainsafe/lodestar-config/default';
...
  const api = getClient(
    {
      baseUrl: 'eth2-beacon-mainnet.infura.io',
    },
    { config }
  );
```

Interestingly the _import { config } from '@chainsafe/lodestar-config/default';_ works fine.

The exports part of the package.json (lodestar-api) looks like this:

  ```
...
"exports": {
    ".": {
      "import": "./lib/index.js"
    },
    "./beacon": {
      "import": "./lib/beacon/index.js"
    },
    "./beacon/server": {
      "import": "./lib/beacon/server/index.js"
    },
    "./builder": {
      "import": "./lib/builder/index.js"
    },
    "./builder/server": {
      "import": "./lib/builder/server/index.js"
    },
    "./keymanager": {
      "import": "./lib/keymanager/index.js"
    },
    "./keymanager/server": {
      "import": "./lib/keymanager/server/index.js"
    }
  },
...
```
Meaning it has the necessary "exports" paths. Any help is appreciated.

**Comment by wemeetagain** [comment]
Try running with `ts-node --esm`

**Comment by oblak1** [comment]
Hmm, it didn't work, unfortunately. This is the console:

```
[nodemon] starting `ts-node --esm ./src/index.ts`
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in node_modules/@chainsafe/lodestar-api/package.json
```
Is it possible to debug this problem by changing the lib .js / package.json files?

**Comment by oblak1** [comment]
I did a little more testing and found out I have to transform my whole project to ES module type so I can normally import and work with the library. 
So I can't use commonJS as target in tsconfig file? Am I correct?

**Comment by wemeetagain** [comment]
thats right.

The alternative is to import the api as a dynamic import:
```ts
const { getClient } = await import('@chainsafe/lodestar-api')
...
```

**Comment by oblak1** [comment]
Thank you. 

Just one follow up question, if I query the block which has execution payload for example, how do I tell the lodestar client it should apply the correct interface (not allForks.signedBlock but the bellatrix one) so I can get the execution property from object?

**Comment by wemeetagain** [comment]
you can do something like:
`... as bellatrix.SignedBeaconBlock`

**Comment by Stevewu1234** [comment]
> I did a little more testing and found out I have to transform my whole project to ES module type so I can normally import and work with the library. So I can't use commonJS as target in tsconfig file? Am I correct?

Hey, can you share your code? I have met the same error, but all of the solution I found didn't work.

**Comment by wemeetagain** [comment]
Here's a good explainer for handling ESM:
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
