### ISSUE TITLE
Git hooks for linting and formatting

### ISSUE THREAD

**Issue by nazarhussain** [ChainSafe/lodestar#4353]
**Is your feature request related to a problem? Please describe.**

I observed recently that some code was pushed without proper linting to the PR, which result in the failure of the litning task in CI and delayed the response cycle. 

**Describe the solution you'd like**

We can add the Git commit hooks to run the linting and prettier before committing the code. This will cover most of the cases to lint the code and will speed up the development process. 

**Additional context**

https://www.npmjs.com/package/husky
https://www.npmjs.com/package/lint-staged

**Comment by dapplion** [comment]
We use to have this and remove them and it got to invasive. I would leave it to each team member discretion to add git hooks manually to their .git folder. Feel to call me out or someone else if we push bad code to CI too frequently tho

**Comment by wemeetagain** [comment]
Agree with @dapplion 
Closing this issue now, feel free to reopen if we need more discussion
