### ISSUE TITLE
Incorrect version shown in Dashboard

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4358]
**Describe the bug**

<img width="1173" alt="Screen Shot 2022-08-03 at 09 41 09" src="https://user-images.githubusercontent.com/10568965/182512519-9935a8ec-9c8c-46e2-a3fe-e5875a1b8338.png">

**Expected behavior**

Correct version should be `tuyen/update-libp2p-protobufjs` which was forked from `cayman/update-libp2p`

**Comment by nflaig** [comment]
@tuyennhv the issue should be fixed by [this commit](https://github.com/ChainSafe/lodestar/commit/d317aac7f7b90785ff055507e6c62f85c2c78dca)
