### ISSUE TITLE
Bug: keymanager API uses slashingProtection instead of slashing_protection

### ISSUE THREAD

**Issue by yorickdowne** [ChainSafe/lodestar#4381]
**Describe the bug**

On a `DELETE` call of `eth/v1/keystores` Lodestar will return slashing protection data in `slashingProtection`. It should be in `slashing_protection` as per https://github.com/ethereum/keymanager-APIs/blob/master/apis/local_keystores.yaml

**Comment by dapplion** [comment]
@yorickdowne eth-docker is so awesome! :heart: keep up the good work

**Comment by yorickdowne** [comment]
Thank you for the kudos! I am working my way through the key api right now, adding an easy way to interact with it on a VC running inside an eth-docker stack. I have list delete and import. Fee recipient next, then gas.

**Comment by dapplion** [comment]
Awesome, please reach out if you find any other incompatibilities. To use a version immediately with the fix from #4384 pull `chainsafe/lodestar:next`
