### ISSUE TITLE
getEffectiveBalanceIncrementsZeroInactive mutates cache

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4390]
**Describe the bug**

Function `getEffectiveBalanceIncrementsZeroInactive` says

https://github.com/ChainSafe/lodestar/blob/0de01443f1f4cfa6efc12783c5783f0035e4e29f/packages/state-transition/src/util/balance.ts#L57-L58

But immediately after mutates the balances setting them to zero 

https://github.com/ChainSafe/lodestar/blob/0de01443f1f4cfa6efc12783c5783f0035e4e29f/packages/state-transition/src/util/balance.ts#L66-L67

So the .slice() **MUST** copy the array as it will be mutated right? Note that Buffer.slice() does not copy while Uint8Array.slice() copies data. We must ensure that the data is copied.

@tuyennhv do you think this can be an issue?

**Expected behavior**

Don't mutate cache

Instead do

```ts
    // Buffer.prototype.slice does not copy memory, Enforce Uint8Array usage https://github.com/nodejs/node/issues/28087
    const uint8Array = Uint8Array.prototype.slice.call(data, start, end - 1);
```

**Comment by twoeths** [comment]
yeah this is a good finding, it may not be an issue for now but could be in the future if someone want to use Buffer instead (to improve performance, for example)
we should use `Uint8Array.prototype.slice` instead 👍
