### ISSUE TITLE
Configs for Mainnet Merge LFG! 

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#4408]
This issue is required for next release which will configure Lodestar for mainnet readiness. 
Reference: https://blog.ethereum.org/2022/08/12/finalized-no-36/

Bellatrix epoch: `144896`
Mainnet (tentative) TTD: `58750000000000000000000`

TTD is subject to change next week upon observations of hashrate metrics. We can implement a hotfix to change baked-in TTD once more is known.

**Comment by dapplion** [comment]
Given that the TTD value is not final I won't include it for 0.42 release. We can cut a patch on Aug 18th once the value is confirmed

**Comment by philknows** [comment]
Closed by #4429
