### ISSUE TITLE
finality_checkpoints endpoint does not return result

### ISSUE THREAD

**Issue by dadepo** [ChainSafe/lodestar#4415]
**Describe the bug**

Requesting the `eth/v1/beacon/states/state_id/finality_checkpoints` endpoint on `https://lodestar-prater.chainsafe.io` returns 404. But requesting same on infura's beacon node returns a result.

On Infura:

```
➜  ~ curl -X GET https://<u>:<p>@eth2-beacon-prater.infura.io/eth/v1/beacon/states/0xd4002260adc896738a6306f87a525da091f54f4b729cd80571493bc8c7b82f84/finality_checkpoints
{"execution_optimistic":false,"data":{"previous_justified":{"epoch":"114763","root":"0x0667e6ee957a41c0a6c238056f98065b6115be5e4a69d3f94df03ae62f67f666"},"current_justified":{"epoch":"114764","root":"0x5386273280d3ef529673466661e4c9ce7d4d5ea1f88dfb896398be9209ff9a67"},"finalized":{"epoch":"114763","root":"0x0667e6ee957a41c0a6c238056f98065b6115be5e4a69d3f94df03ae62f67f666"}}}%
```

On Lodestar prater:

```
➜  ~ curl -X GET https://lodestar-prater.chainsafe.io/eth/v1/beacon/states/0xd4002260adc896738a6306f87a525da091f54f4b729cd80571493bc8c7b82f84/finality_checkpoints
{"statusCode":404,"error":"Not Found","message":"No state found for id '0xd4002260adc896738a6306f87a525da091f54f4b729cd80571493bc8c7b82f84'"}%
```

Making the request for a more recent slot (3672832) gives the same response. 

**Expected behavior**

`eth/v1/beacon/states/state_id/finality_checkpoints` endpoing on lodestar beacon node should return results

**Comment by dapplion** [comment]
Lodestar does not support arbitrary state regen previous to the finalized checkpoint. Infura does. The slot you are requesting was before or after the finalized slot at the time?

- See https://github.com/ChainSafe/lodestar/issues/4005

**Comment by dapplion** [comment]
Closing issues for specific incidents on old versions of Lodestar, please re-open if it happens with latest stable
