### ISSUE TITLE
Winston log file rotation should clean old .log files

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4419]
**Describe the bug**

In some of our deployed servers there are very old .log files. Seems like the file rotation logic only cleans contiguous files to the expected dates, such that if the server is offline for some days old files won't be cleaned at all.

Log files with debug level can weight 800MB / day on beacon, so this is very significant

**Expected behavior**

Always retain the max number of files specified. Add a garbage collection routine on boot and clean old files

**Comment by twoeths** [comment]
as of Dec 2022 (v1.2.2) the log file is about 133MB per day, the issue is still there, for example

```
-rw-r--r-- 1 devops devops       945 Dec 26 00:00 .log_rotate_audit.json
-rw-r--r-- 1 devops devops  78134097 Nov 12 23:59 beacon-2022-11-12.log
-rw-r--r-- 1 devops devops  70740005 Nov 13 23:59 beacon-2022-11-13.log
-rw-r--r-- 1 devops devops  74233605 Nov 14 23:59 beacon-2022-11-14.log
-rw-r--r-- 1 devops devops  72178266 Nov 15 23:59 beacon-2022-11-15.log
-rw-r--r-- 1 devops devops 133587672 Dec 22 23:59 beacon-2022-12-22.log
-rw-r--r-- 1 devops devops 134221811 Dec 23 23:59 beacon-2022-12-23.log
-rw-r--r-- 1 devops devops 130911699 Dec 24 23:59 beacon-2022-12-24.log
-rw-r--r-- 1 devops devops 131592646 Dec 25 23:59 beacon-2022-12-25.log
-rw-r--r-- 1 devops devops  41074529 Dec 26 07:30 beacon-2022-12-26.log
```
