### ISSUE TITLE
Potential slow memory leak seen in Ropsten nodes

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4423]
**Describe the bug**

Of about 42MB/day, seen in Ropsten nodes in the last 14 days. They run unstable without watchtower so don't update automatically. Versions run through this period:
- 067edc40c4b15fc5558a0e442eeeb67bdb431738 from 07/28
- b34abb7760e011d7ccbf72a9e0bcfa02140a99e3 from 08/03
- v0.41.0 from 08/15

![Screenshot from 2022-08-16 09-29-50](https://user-images.githubusercontent.com/35266934/184823228-8a786efe-d5d0-4545-aa2b-2e976d3bfff5.png)
![Screenshot from 2022-08-16 09-30-00](https://user-images.githubusercontent.com/35266934/184823241-906d4ef5-2ff4-431a-91a5-ce66e8e54fb4.png)

This is also seen in Sepolia node

![Screenshot from 2022-08-16 09-36-06](https://user-images.githubusercontent.com/35266934/184823979-ef072b1c-f749-4e1a-a749-7507bb68b537.png)

**Expected behavior**

Stable memory long term

**Comment by philknows** [comment]
Let's confirm whether or not this is just Ropsten or not.

**Comment by dapplion** [comment]
From the last two days, the leak is clearly visible, with an impact of 75MB / day

![Screenshot from 2022-08-26 10-23-09](https://user-images.githubusercontent.com/35266934/186857715-6b502346-306d-491d-bf6f-3f3a8a605df7.png)

**Comment by philknows** [comment]
Heap memory in `v1.4.x` is stable long term. Closing issue.
