### ISSUE TITLE
voluntary-exit missing from validator

### ISSUE THREAD

**Issue by yorickdowne** [ChainSafe/lodestar#4472]
**Steps to Reproduce**

lodestar v1.x no longer supports `validator voluntary-exit`, and no obvious replacement can be found in the `--help` text for `lodestar` or `lodestar validator`.

This may be a bug, unless removal of voluntary-exit was deliberate.

**Comment by dapplion** [comment]
@yorickdowne The command was removed on purpose. Could you elaborate on the usage on your setup, and if you have alternative tooling that does the job?

- https://github.com/ChainSafe/lodestar/issues/4214

**Comment by yorickdowne** [comment]
@dapplion This is part of the "lifetime of a validator" flow for eth-docker users. They create it, import it, eventually may want to exit it - possibly after withdrawals are live. If they choose Lodestar and cannot exit there, they'd need to delete it from Lodestar, switch CLs, reimport it (with slashing protection DB) into another CL, then sign an exit message.

eth-docker currently relies on each client to sign exit messages, and uses their interface to do so.

There is certainly an alternative, which is to ship ethdo with eth-docker and use it to sign exit messages universally, instead of relying on the clients themselves. I haven't tested that. It's not entirely trivial as it requires importing the key to ethdo first, then signing and transmitting an exit message.

**Comment by dapplion** [comment]
Thanks for the context! Will prioritize for upcoming releases
