### ISSUE TITLE
notifyNewPayload request time

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4477]
**Describe the bug**

`notifyNewPayload` seems to be higher than expected and correlated to node's spec

- hzax41

<img width="1235" alt="Screen Shot 2022-08-25 at 11 16 48" src="https://user-images.githubusercontent.com/10568965/186573681-355f208e-92ad-459f-be5e-4887051b6cbe.png">

- hzcx41

<img width="1237" alt="Screen Shot 2022-08-25 at 11 17 17" src="https://user-images.githubusercontent.com/10568965/186573743-a4f13b6c-ef79-4023-9b9b-80e438e25278.png">

- ctvpsm

<img width="1227" alt="Screen Shot 2022-08-25 at 11 17 54" src="https://user-images.githubusercontent.com/10568965/186573817-917a5749-5a3f-4a4c-9fab-7af5019ca6c7.png">

- ctvpss

<img width="1229" alt="Screen Shot 2022-08-25 at 11 18 34" src="https://user-images.githubusercontent.com/10568965/186573906-19f82ad5-f660-4af1-9afd-27241cc510c6.png">

**Expected behavior**
It needs to be small enough so that "Gossip Block Received Delay" is consistently < 4s (1/3 of slot)

**Comment by twoeths** [comment]
Some first analysis:
- We need to benchmark `serializeExecutionPayload()` considering `MAX_BYTES_PER_TRANSACTION` = 1073741824 and `MAX_TRANSACTIONS_PER_PAYLOAD` = 1048576
- Also `JSON.stringify()` before we call execution engine new payload api

<img width="930" alt="Screen Shot 2022-08-25 at 14 42 24" src="https://user-images.githubusercontent.com/10568965/186606033-e9c4fc07-283a-4c66-87fb-e2f091b0f471.png">

- Need to have a separate metric to know the real time happened at EE side

**Comment by dapplion** [comment]
@tuyennhv You can run a snooper `parithoshj/json_rpc_snoop:v1.0.0-x86` between the EL and CL to log the traffic and their timings. Run the container with command

```
./json_rpc_snoop -p {{eth1_engine_snoop_port}} http://127.0.0.1:{{eth1_engine_port}}
```

Also regarding the metrics, rendering dots is very miss-leading. Please always render lines, not dots. If you want to see how many calls took more than X seconds, use the histogram buckets

**Comment by g11tech** [comment]
actually this could take some at EL end as well because they actually have to execute the block, if the block is full then it could take upto 2-3 seconds to execute on commodity machines with the gas limit.

May be we should also plot #of transactions in that particular block for new payload that we send.

**Comment by g11tech** [comment]
"Gossip Block Received Delay" should be calculated with the block even before we send it for execution  (i guess requirement is for proposer boost)

**Comment by dapplion** [comment]
@tuyennhv Could you prove first that performance is degraded for those servers? Also keep in mind that for `ctvpss` the execution client is in a different data center so roundtrip time will be naturally higher

**Comment by twoeths** [comment]
> @tuyennhv Could you prove first that performance is degraded for those servers? Also keep in mind that for `ctvpss` the execution client is in a different data center so roundtrip time will be naturally higher

Our server can only store metrics for up to 7 days so I don't have premerge metrics for now but:
- this signals that some blocks becomes head after 4s and validator for sure can't vote for correct head (this is from beta lg1k node)

<img width="860" alt="Screen Shot 2022-08-25 at 16 53 41" src="https://user-images.githubusercontent.com/10568965/186634492-c4bdcbb7-f3d4-4baa-a2f0-091904f1e662.png">
 
- take a sample validator from that node we can see clearly that the profit is at least <10% than before https://goerli.beaconcha.in/validator/258155
<img width="960" alt="Screen Shot 2022-08-25 at 16 58 00" src="https://user-images.githubusercontent.com/10568965/186635459-da5515cc-bd17-46e6-a420-f910dec7326a.png">

**Comment by twoeths** [comment]
> @tuyennhv You can run a snooper parithoshj/json_rpc_snoop:v1.0.0-x86 between the EL and CL to log the traffic and their timings. Run the container with command

@dapplion  the snoop tool works very well, it shows that `geth` returns `newPayload` requests immediately

```
Aug 26 11:06:02.353 2022 REQUEST
  "method": "engine_newPayloadV1",
Aug 26 11:06:02.353 2022 RESPONSE
Aug 26 11:06:16.026 2022 REQUEST
  "method": "engine_newPayloadV1",
Aug 26 11:06:16.026 2022 RESPONSE
Aug 26 11:06:25.295 2022 REQUEST
  "method": "engine_newPayloadV1",
Aug 26 11:06:25.295 2022 RESPONSE
```

**Comment by twoeths** [comment]
<img width="1282" alt="Screen Shot 2022-11-24 at 10 54 20" src="https://user-images.githubusercontent.com/10568965/203690341-3e5a25da-16db-4631-a074-1516c789557b.png">

mainnet nodes work fine, closing the issue
