### ISSUE TITLE
Per validaor fee-recipient configuration

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#4485]
Add the ability to supply to validator a "proposer_config" (https://docs.prylabs.network/docs/execution-node/fee-recipient#fee-recipient-json-config-file) which can be used to populate fee recipient,gas against each validator in`validaorStore` by extending `ValidatorRegistrationCache` (from PR https://github.com/ChainSafe/lodestar/pull/4447)

**Comment by philknows** [comment]
WIth #4447 merged, can we close this issue @g11tech ?

**Comment by g11tech** [comment]
yes closing this as we can do now both through file and keymanager apu

**Comment by yorickdowne** [comment]
Is this expected to have made it into 1.1.0? It doesn't appear to work there, yet.

```
Path not found error. Was that the right pubkey? Error: Route GET:/eth/v1/validator/0x8ed78a5495b54d5b6cc8bf170534ecb633b9694fba121ca680744fa9633f1b67cc77c045f88a6f97be781fe6c2867646/feerecipient not found
```

**Comment by g11tech** [comment]
> Is this expected to have made it into 1.1.0? It doesn't appear to work there, yet.
> 
> ```
> Path not found error. Was that the right pubkey? Error: Route GET:/eth/v1/validator/0x8ed78a5495b54d5b6cc8bf170534ecb633b9694fba121ca680744fa9633f1b67cc77c045f88a6f97be781fe6c2867646/feerecipient not found
> ```

i don't think its in 1.1.0 can you try it in `next`? also i am hoping keymanager is enabled using keymanager args

**Comment by yorickdowne** [comment]
Works in `next` thanks!
