### ISSUE TITLE
Pass abort signal from top-level to avoid introducing nodejs specific api in downstream components

### ISSUE THREAD

**Issue by dadepo** [ChainSafe/lodestar#4513]
Shame we have to introduce a nodejs specific api here.

Later we can pass down a signal from the top-level beacon node and avoid creating a new signal here.

_Originally posted by @wemeetagain in https://github.com/ChainSafe/lodestar/pull/4421#discussion_r960877870_

**Comment by dapplion** [comment]
beacon-node leaks more NodeJS specific items. Best to tackle in one go
