### ISSUE TITLE
Better error reporting on bad enr in --bootnodes

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4522]
**Describe the bug**

Running lodestar with `--bootnodes=bad_enr` results in

```
Sep-08 15:43:14.426[]                 info: Initializing beacon state from anchor state slot=0, epoch=0, stateRoot=0xea2855c3a4d341cfc991dcfc3d685347b0a69dbe63b51f1d838248e4cbfa0c1e
 ✖ Error: string encoded ENR must start with 'enr:'
    at Function.decodeTxt (/usr/app/node_modules/@chainsafe/discv5/lib/enr/enr.js:92:19)
    at createNodeJsLibp2p (file:///usr/app/packages/beacon-node/src/network/nodejs/util.ts:56:54)
    at Object.beaconHandler [as handler] (file:///usr/app/packages/cli/src/cmds/beacon/handler.ts:74:15)
```

It's hard to figure out that the cause of the error is a bad enr.

**Expected behavior**

Throw early and with a message: bad ENR formatting supplied as bootnode.

**Comment by nazarhussain** [comment]
We have updated a proper message and fail earlier during the command parsing. This applies to both `beacon` and `bootnode` commands. 

https://github.com/ChainSafe/lodestar/blob/6ac8c07023bc72c7ef54a6ea66884790793eda21/packages/cli/src/options/beaconNodeOptions/network.ts#L119
