### ISSUE TITLE
Running tests fails on MacOs

### ISSUE THREAD

**Issue by dadepo** [ChainSafe/lodestar#4525]
**Describe the bug**

Running tests locally on MacOs fails with:

`du: invalid option -- b`

This is due to the line:

```
const res = execSync(`du -bs ${dbLocation}`, {encoding: "utf8"});
```

That can be found in this test [here](https://github.com/ChainSafe/lodestar/blob/daf2f2821364b4d5ea8b9d5bfa2b8e59f951eba1/packages/db/test/unit/controller/level.test.ts#L140)

Reason this fails is that, apparently the `-b` is not in the `du` spec and not supported on MacOs. This means this will also fail on windows by the way.

**Expected behavior**

The tests should run fine on MacOs (also windows) and should not be dependent on OS.

**Comment by dapplion** [comment]
Closing issues for specific incidents on old versions of Lodestar, please re-open if it happens with latest stable
