### ISSUE TITLE
Enable LogFile by default at dataDir

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4527]
When users submit issues the follow up question is: "Oh can you run your node again with debug logs?". That's a hard ask since some issues are not reproducible.

Lighthouse logs to file by default, and I really think we should do the same. It would be incredibly helpful to debug situtations. Just tell users: "can you please send us this log file you already have?"

Proposed changes:
- [ ] Set logFile to default location relative to dataDir, and enable
- [x] Set logFileLevel to debug by default
- [ ] Enable log rotate by default

**Comment by g11tech** [comment]
:+1: this should be ok if we also have log rotation with logfile limit for default
