### ISSUE TITLE
Web3Signer-Geth CI Sim Test

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#4528]
Suggested in the Sept 9 planning call:

Similar to the sim merge test, we want to create something similar for web3signer to test against Geth for scaling test efforts. 

This sim test should compile Geth in CI and run web3signer against Geth. 
We want to be able to setup Web3Signer locally (docker/binary/etc.), load keys, run a chain to finalization with it.

**Comment by dapplion** [comment]
A simpler first test would be just run the web3signer and request signature for all possible objects. Without actually running the chain to finalization. @dadepo this should be easy to to

**Comment by dadepo** [comment]
This will be implemented as part of the https://github.com/ChainSafe/lodestar/pull/4502 PR

**Comment by dadepo** [comment]
Implemented as part of https://github.com/ChainSafe/lodestar/pull/4502
