### ISSUE TITLE
Enable `trace` log level

### ISSUE THREAD

**Issue by yorickdowne** [ChainSafe/lodestar#4536]
**Is your feature request related to a problem? Please describe.**

eth-docker uses the same log level for all running components. `trace` is an industry standard, but not supported by Lodestar. This causes Lodestar startup to fail when `trace` logging is configured.

**Describe the solution you'd like**

Support a `trace` log level as an alias to `silly`. That way `trace` logging can be enabled for a "stack" consisting of Lodestar, an EL, Grafana, etc.

**Comment by dapplion** [comment]
Sounds good to me :+1:
