### ISSUE TITLE
Low peer count post-merge

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#4549]
A discord user is experiencing a low peer count post merge:

![image](https://user-images.githubusercontent.com/76567250/190365458-715645f5-4170-4dd5-a101-7ae0218cedec.png)

https://discord.com/channels/593655374469660673/593655641445367808/1019901205629108244

**Comment by dubuqingfeng** [comment]
might need to stop lodestar and clear peerstore directory in lodestar root directory

**Comment by philknows** [comment]
Would definitely get them to upgrade to v1.1.0 once released to see if it persists.

**Comment by g11tech** [comment]
i  feel that v1.1.0 has shown auto peer recovery on my installations even after dropping to low double digits because of network turbulence, without requiring me to clear peerstore that i had to do with v1.0.0
