### ISSUE TITLE
Pubsub Message.seqno should be 8 bytes instead of 20

### ISSUE THREAD

**Issue by Nashatyrev** [ChainSafe/lodestar#458]
**Describe the bug**
The pubsub message received from lodestar contains 20-byte `Message.seqno`

**Expected behavior**
The spec requires 8-bytes
https://github.com/libp2p/specs/tree/master/pubsub#the-message

**Screenshots**
![изображение](https://user-images.githubusercontent.com/8173857/64856826-9730b400-d62b-11e9-8261-d43a565fa622.png)

**Relates to**
https://github.com/libp2p/js-libp2p-pubsub/issues/27

**Desktop (please complete the following information):**
 - OS: ----
 - Version: ---
 - Branch: interop
 - Commit hash: ---

**Comment by mpetrunic** [comment]
unstale

@wemeetagain this should be solved in gossipsub-js repo right?

**Comment by wemeetagain** [comment]
@mpetrunic should be solved in js-libp2p-pubsub
libp2p/js-libp2p-pubsub#27

**Comment by mpetrunic** [comment]
closing in favour of https://github.com/libp2p/js-libp2p-pubsub/issues/27

I'll look into opening PR for that
