### ISSUE TITLE
First two slots of altair epoch contains empty sync aggregate

### ISSUE THREAD

**Issue by nazarhussain** [ChainSafe/lodestar#4590]
**Describe the bug**

Observed during the sim tests that first two slots of the altair epoch always contains zero sync committee participation. 

**Expected behavior**

No such behavior is been specified by any of the specs I could found. Logically the sync committee participation should be available from the first slot of altair epoch transition. 

**Steps to Reproduce**
Run sim tests. 

**Screenshots**
Check the last column. 

```
┌─────────┬─────────────┬───────┬───────┬─────────────────┬─────────────────────┬─────────────────────────────────────────────────────────────────────────────┬─────────────────┬─────────────────────────────┐
│ (index) │      F      │  Eph  │ slot  │  Missed Slots   │   Finalized Slots   │                             Attestations Count                              │ Inclusion Delay │      SC Participation       │
├─────────┼─────────────┼───────┼───────┼─────────────────┼─────────────────────┼─────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────┤
│   16    │  'phase0'   │ '1/7' │  15   │     '----'      │   '0 | 0 | 0 | 0'   │                               '4 | 4 | 4 | 4'                               │ '1 | 1 | 1 | 1' │       '0 | 0 | 0 | 0'       │
│   17    │  'phase0'   │   1   │ '---' │ '0 | 0 | 0 | 0' │   '- | - | - | -'   │ '1.00, 1.00, 1.00 | 1.00, 1.00, 1.00 | 1.00, 1.00, 1.00 | 1.00, 1.00, 1.00' │ '- | - | - | -' │       '0 | 0 | 0 | 0'       │
│   18    │  'altair'   │ '2/0' │  16   │     '----'      │   '0 | 0 | 0 | 0'   │                               '4 | 4 | 4 | 4'                               │ '1 | 1 | 1 | 1' │       '0 | 0 | 0 | 0'       │
│   19    │  'altair'   │ '2/1' │  17   │     '----'      │   '0 | 0 | 0 | 0'   │                               '4 | 4 | 4 | 4'                               │ '1 | 1 | 1 | 1' │       '0 | 0 | 0 | 0'       │
│   20    │  'altair'   │ '2/2' │  18   │     '----'      │   '0 | 0 | 0 | 0'   │                               '4 | 4 | 4 | 4'                               │ '1 | 1 | 1 | 1' │       '1 | 1 | 1 | 1'       │
│   21    │  'altair'   │ '2/3' │  19   │     '----'      │   '0 | 0 | 0 | 0'   │                               '4 | 4 | 4 | 4'                               │ '1 | 1 | 1 | 1' │       '1 | 1 | 1 | 1'       │
```

**Further details**
For now this edge case is been avoid in the sim tests. 

https://github.com/ChainSafe/lodestar/blob/8cac35f9ea1d0ba227102e48fd8b5d0d57d97c62/packages/cli/test/utils/simulation/assertions.ts#L223-L226

It's same behavior in the mainnet https://beaconcha.in/slot/2375680, sync aggregate is empty for the first slot of the start of altair epoch. The second slot missed, so not sure about it. 

On goerli its empty for first slot and 53% on second slot. https://goerli.beaconcha.in/epoch/36660

**Comment by philknows** [comment]
Not a high priority because altair fork has already happened on mainnet.

**Comment by philknows** [comment]
Needs investigation for any test networks merged at genesis and sim tests.

**Comment by wemeetagain** [comment]
@nazarhussain this appears to be resolved, can you doublecheck?

**Comment by nazarhussain** [comment]
This seems to be fixed. Now we have data for all slots of altair fork epoch. 
![image](https://github.com/user-attachments/assets/7f2307a8-691c-473c-a205-df17f284e0fd)

https://github.com/ChainSafe/lodestar/actions/runs/11327520713/job/31498904801?pr=7153#step:6:196
