### ISSUE TITLE
Allow using custom presets

### ISSUE THREAD

**Issue by daniildxb** [ChainSafe/lodestar#4598]
Hi,
For CI/CD needs we run a private ETH network that is tuned to speed up network
It doesn't match minimal preset and, sadly, there's no built-in way to customize it or override completely, for now we've used a hacky solution but moving forward would love to have an option to do it in lodestar.

**Describe the solution you'd like**
I'd like to come forward with a PR that adds an ability to use custom preset for chain config, but before starting working on it, would like to confirm with your team that it's something that you'd be willing to accept

**Describe alternatives you've considered**
There's no way to override preset variables in the runtime, so as of now we directly modify them in the source code during build stage.

**Comment by wemeetagain** [comment]
Hey @daniildxb  This is definitely something we'd be willing to accept.

Take a look at https://github.com/ChainSafe/lodestar/blob/unstable/packages/params/src/setPreset.ts
This is my thought at what you could add:
```ts
export let userOverrides: Partial<BeaconPreset> | null = null;

/**
 * @param presetName - the preset to use as a base
 * @param overrides - customized fields
 */
function setCustomPreset(presetName: PresetName, overrides: Partial<BeaconPreset>): void {
  setActivePreset(presetName);
  userOverrides = overrides;
}
```

And then [here](https://github.com/ChainSafe/lodestar/blob/unstable/packages/params/src/index.ts#L86) spread `userOverrides` in.
