### ISSUE TITLE
Improve fastMsgIdFn

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4603]
**Is your feature request related to a problem? Please describe.**

As of v1.2.0 rc.0, fastMsgIdFn takes 1.57% of cpu time since the more mesh peers we have, the more fastMsgIdFn get called

```typescript
export function fastMsgIdFn(rpcMsg: RPC.IMessage): string {
  if (rpcMsg.data) {
    return Buffer.from(digest(rpcMsg.data)).subarray(0, 8).toString("hex");
  } else {
    return "0000000000000000";
  }
}
```
<img width="1315" alt="Screen Shot 2022-09-29 at 11 28 30" src="https://user-images.githubusercontent.com/10568965/192938981-265b3fb0-56af-4716-8602-6d4e7f2c4af6.png">

**Describe the solution you'd like**

Instead of copying to Buffer and convert to hex from there, we can just create String directly from there

```typescript
const hash = digest(data);
String.fromCharCode(hash[0], hash[1], hash[2], hash[3], hash[4], hash[5], hash[6], hash[7]);
```

quick benchmark
```
  encoding.test.ts
    ✔ same to fastMsgIdFn                                              4.564126e+11 ops/s 0.002191000 ns/op   x0.000    3899710 runs   10.0 s
    ✔ new fastMsgIdFn                                                  6.195787e+11 ops/s 0.001614000 ns/op   x0.000    5125581 runs   10.1 s
```

it's ~30% faster

if we don't count the hash, `String.fromCharCode()` is 3x faster
```
✔ Buffer.from(hash).subarray(0, 8).toString                        9.216590e+11 ops/s 0.001085000 ns/op   x0.002    6948395 runs   10.1 s
✔ String.fromCharcode 8 first bytes                                3.134796e+12 ops/s 0.0003190000 ns/op   x0.010   15844892 runs   10.0 s
✔ hash64 bytes                                                     6.570302e+11 ops/s 0.001522000 ns/op        -    5346980 runs   10.0 s
```

**Comment by twoeths** [comment]
[0928_1.2.0_rc.0_lg1k_goerli.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/9670951/0928_1.2.0_rc.0_lg1k_goerli.cpuprofile.zip)

**Comment by dapplion** [comment]
@tuyennhv Can you refactor the code above to be multiline such
```ts
// Multiline to ease tracking performance in profiles by line number
const hash = digest(rpcMsg.data);
const hashBuffer = Buffer.from(hash);
const hashBuffer8B = hashBuffer.subarray(0, 8);
return hashBuffer8B.toString("hex");
```

Then deploy and take another cpu profile?

When taking the profile, navigate to the encodings file and you should be able to see what line is taking more time

**Comment by twoeths** [comment]
The result is quite surprised, this time I took a 15m profile.
- fastMsgIdFn takes 2.7%
<img width="1307" alt="Screen Shot 2022-09-30 at 11 37 09" src="https://user-images.githubusercontent.com/10568965/193191247-6ffaf86b-0277-4f60-9032-cb61a4658281.png">

- it shows a lot of time for Buffer.from() and Buffer.subarray()
<img width="796" alt="multilined_fastMsgIdFn" src="https://user-images.githubusercontent.com/10568965/193191373-ffb3e2e4-bfd0-4178-bd83-24bd641bc591.png">

==> from the above, we could try `msgIdToStrFn()` in the same way too

[0930_multilined_fastMsgId_lg1k_1.2.0.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/9680791/0930_multilined_fastMsgId_lg1k_1.2.0.cpuprofile.zip)

**Comment by dapplion** [comment]
Don't benchmarks by line do not look right, digest() must take most of the time since that's the actual computation of the hash. I've done some benchmarks and conversion to Buffer + subarray is almost free compared to computing a sha256 hash. Maybe the benchmarks are offset by 1 line?

**Comment by twoeths** [comment]
> Don't benchmarks by line do not look right, digest() must take most of the time since that's the actual computation of the hash. I've done some benchmarks and conversion to Buffer + subarray is almost free compared to computing a sha256 hash. Maybe the benchmarks are offset by 1 line?

yeah it's weird, `msgIdToStrFn` still shows correct line

**Comment by twoeths** [comment]
<img width="1434" alt="Screen Shot 2022-10-08 at 17 14 48" src="https://user-images.githubusercontent.com/10568965/194702571-f0473175-a008-49a2-82df-c2a001229b2b.png">

confirm that `fastMsgIdFn` was improved, it takes only 0.38% after we merge the PR

[1008_feat2_1.2.0_rc.0.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/9738963/1008_feat2_1.2.0_rc.0.cpuprofile.zip)

**Comment by dapplion** [comment]
> [1008_feat2_1.2.0_rc.0.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/9738963/1008_feat2_1.2.0_rc.0.cpuprofile.zip)

This CPU profile was taking with async stack traces off?

**Comment by twoeths** [comment]
@dapplion yeah I disabled async stack trace in my setting
