### ISSUE TITLE
SIM tests are unstable and causing delay in CI

### ISSUE THREAD

**Issue by nazarhussain** [ChainSafe/lodestar#4609]
**Describe the bug**

It is observed that SIM tests are unstable and failed randomly. Need to fine tune the configurations to avoid false positives to save CI time. 

**Expected behavior**

The SIM tests should be stable and don't include false positive failures. 

**Steps to Reproduce**
Run sim tests. 

**Referece**
https://github.com/ChainSafe/lodestar/actions/runs/3145578978/jobs/5113039772

**Comment by dadepo** [comment]
Here is one that failed since yesterday: https://github.com/ChainSafe/lodestar/actions/runs/3153878655/jobs/5130853133

**Comment by nazarhussain** [comment]
https://github.com/ChainSafe/lodestar/actions/runs/3157655766/jobs/5138786274
