### ISSUE TITLE
Implement the spec patch that allows light client to verify signatures at period boundary

### ISSUE THREAD

**Issue by dadepo** [ChainSafe/lodestar#4627]
**Is your feature request related to a problem? Please describe.**

The changes to the spec in https://github.com/ethereum/consensus-specs/pull/2805 takes care of scenarios at epoch boundary where it was not clear if an attested_header was signed by the current or next sync committee. The update to the spec introduced `signatureSlot` and updated the light client validator logic.

Signature Slot is being added here https://github.com/ChainSafe/lodestar/pull/4365

This issue is for updating the light clients verification logic to take care of the epoch boundary situation.

**Comment by twoeths** [comment]
closed by https://github.com/ChainSafe/lodestar/pull/4908/files
