### ISSUE TITLE
EIP-4844 Checklist/Tracker

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#4632]
This issue is to track progress on the implementation of EIP-4844:
Eth PM Checklist: https://github.com/ethereum/pm/blob/master/Breakout-Room/4844-readiness-checklist.md
Specs: https://github.com/ethereum/consensus-specs/tree/dev/specs/eip4844

- Takeover branch from Dan: #4774

**Comment by dapplion** [comment]
Closing for https://github.com/ChainSafe/lodestar/issues/4970
