### ISSUE TITLE
Support Content Negotiation for returning Light Client related data as either JSON or SSZ

### ISSUE THREAD

**Issue by dadepo** [ChainSafe/lodestar#4635]
The REST API for light client related data should also be able to return results as SSZ.

Ref: https://github.com/ethereum/beacon-APIs/pull/247
 
> Depending on the `Accept` header it can be returned either as JSON or SSZ-serialized bytes.
**Is your feature request related to a problem? Please describe.**

**Comment by philknows** [comment]
Superseded by #5128
