### ISSUE TITLE
Lodestar Light Client Data Consumer

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#4640]
**Is your feature request related to a problem? Please describe.**

From our October 4 standup discussion, it makes sense for Lodestar to also consume the light client p2p data it produces from its full node (#4365). The beneficial use cases of such an application is to open the doors to other clients and developers to consume light client data for their use case (e.g. A light client CL to get latest blocks for an execution client). We must streamline the development of a standalone light client data consumer which inherits the pieces from light client p2p. 

**Describe the solution you'd like**

Goal: We should develop a lightweight, standalone consumer inheriting light client data from the p2p network. Some additional points to note:
- It should be a separate process so others may bundle this with their application
- It must listen to gossip and get updates from req/res (the challenge with our current libs/modules is getting it to work outside of the beacon node without breaking Lodestar and is safe)
- It will have to use a defined list of bootnodes or discv5 to discover nodes through p2p 

**To Investigate/Research**
- Lodestar can have an advantage for browsers. Can we add a websocket transport for publishing?

**Ideas + Roadmap for Implementation (subject to change)**
Milestone 1: Replicate something similar to our browser demo without going through P2P
Milestone 2: Interop with Nimbus light client via P2P

**Comment by kitkatty** [comment]
A websocket transport for publishing is interesting, a simple way to request data from ABIs of contracts maybe, I think the most useful features has to be to be enabled with Ethers and Web3Js via Http or Ipc, there is also new libraries built with web3py that use Http in a promising way, https://web3js.readthedocs.io/en/v1.2.1/getting-started.html, https://docs.ethers.io/v5/getting-started/#getting-started--connecting-rpc, a lot of dApps are already built on these standards and consuming data from Infura or Alchemy, 
This availability of data request creates a easy way to gather blockchain data without needing full nodes,
The feature of verifying NFT balances is something used for many dApps, 
I am surprised that this client for beacon api seems to be abandoned; 
https://github.com/web3j/web3j-eth2

It is hard to understand how the merge is a technological upgrade, but now a barrier to enabling light nodes,

**Comment by philknows** [comment]
Superceded by #4705
