### ISSUE TITLE
"TypeError: resArr.map is not a function" 

### ISSUE THREAD

**Issue by mikelxc** [ChainSafe/lodestar#4646]
**Describe the bug**
Error updating eth1 chain cache  resArr.map is not a function

**Expected behavior**

**Steps to Reproduce**
`lodestar beacon --dataDir ./data --rest --execution.urls http://127.0.0.1:8551 --rest.address 0.0.0.0 --rest.namespace '*' --metrics --logFile ./logs/beacon.log --logFileLevel debug --logFileDailyRotate 5 --jwt-secret ./jwtsecret --checkpointSyncUrl=https://{myKey}@eth2-beacon-prater.infura.io --network goerli --metrics=true`
It runs flawlessly for a couple days and the error message suddenly appears.
Tried to restart the service, but the error is still there.
It's still synced, but seems to have a problem parsing the log

**Screenshots**
<img width="1920" alt="Screen Shot 2022-10-06 at 1 28 29 PM" src="https://user-images.githubusercontent.com/20431963/194379523-e3834f2f-d385-4fc7-899c-3fb74c8be767.png">

**Desktop (please complete the following information):**

- OS: ubuntu 22.04
- Version: v1.1.0/631b6e7
- Branch: main 
- Commit hash: 631b6e7

**Comment by dapplion** [comment]
What execution client are you running? Is it fully synced? Could you check the logs there too just in case?

Error is here

https://github.com/ChainSafe/lodestar/blob/ca27458b59c66c9d3da7dd95322e479f78407269/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts#L147

it appears the node responded with a JSON payload that's not an array

**Comment by mikelxc** [comment]
I was using akula. I know it's not officially supported. On its console the node is synced, but once it's synced, the error message appears and attestations are failing

**Comment by dapplion** [comment]
Could you do a batched JSON RPC request with multiple getBlockByNumber requests to Akula and paste request + returned JSON here? Let's double check the format is the one expected by Lodestar

**Comment by dapplion** [comment]
Current master guards against it 

https://github.com/ChainSafe/lodestar/blob/8fa4b1fabfb2b1b0dfd15f004ffa8c21413ba9ec/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts#L149-L156
