### ISSUE TITLE
Performance issue with stablelib

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4652]
**Description**
- The js version of chacha20poly1305 takes significant time in lodestar

<img width="1426" alt="Screen Shot 2022-10-08 at 17 29 10" src="https://user-images.githubusercontent.com/10568965/194703050-ab323a25-6a71-486f-97d6-89fffaf55c4a.png">

Need to find a different implementation:
- Try to find a wasm implementation
- Or find a native implementation and do async call there
[1008_feat2_1.2.0_rc.0.cpuprofile.zip](https://github.com/ChainSafe/js-libp2p-noise/files/9738985/1008_feat2_1.2.0_rc.0.cpuprofile.zip)

**Comment by dapplion** [comment]
- @tuyennhv Opened a PR https://github.com/ChainSafe/js-libp2p-noise/pull/224 to add metrics to noise, relevant to this issue is to measure packet rate inbound and outbound so we can understand how expensive noise is relative to benchmarks

**Comment by mpetrunic** [comment]
I don't think it makes sense to track it in this repository as this library allows you to add your own cryptography libraries

**Comment by twoeths** [comment]
This is from v1.2.0-rc.0 goerli lg1k, it shows how `chacha20Poly1305Decrypt()` could cause I/O lag issue

- At 531044 ms

<img width="666" alt="Screen Shot 2022-10-19 at 14 30 13" src="https://user-images.githubusercontent.com/10568965/196625302-2a743d84-d278-4abb-b131-c0c933c26515.png">

- At 531153 ms

<img width="824" alt="Screen Shot 2022-10-19 at 14 31 10" src="https://user-images.githubusercontent.com/10568965/196625510-86a41849-772a-4421-aabd-6dd894a4c174.png">

- At 531207 ms

<img width="624" alt="Screen Shot 2022-10-19 at 14 32 44" src="https://user-images.githubusercontent.com/10568965/196625816-6f09ee20-0954-4862-8d5e-1d2f8ae4b00b.png">

although each call takes only ~6ms, it's significant compared to others
<img width="795" alt="Screen Shot 2022-10-19 at 14 39 18" src="https://user-images.githubusercontent.com/10568965/196627215-e02b2a7c-44e8-47d6-9447-75d2d248ad02.png">

[1019_feat2_lg1k_1.2.0_rc.0.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/9818035/1019_feat2_lg1k_1.2.0_rc.0.cpuprofile.zip)
