### ISSUE TITLE
node can't find peers

### ISSUE THREAD

**Issue by TimDaub** [ChainSafe/lodestar#4657]
Hi I have a lodestar client running that seems to never find peers, shall I create a github issue?

```
Oct-12 00:51:12.642[]                 warn: Low peer count peers=0
Oct-12 00:36:41.000[]                 info: Searching peers - peers: 0 - slot: 4891981 (skipped 4891981) - head: 0 0x4d61…9360 - finalized: 0x0000…0000:0
Oct-12 00:36:53.001[]                 info: Searching peers - peers: 0 - slot: 4891982 (skipped 4891982) - head: 0 0x4d61…9360 - finalized: 0x0000…0000:0
Oct-12 00:37:05.000[]                 info: Searching peers - peers: 0 - slot: 4891983 (skipped 4891983) - head: 0 0x4d61…9360 - finalized: 0x0000…0000:0
Oct-12 00:37:17.000[]                 info: Searching peers - peers: 0 - slot: 4891984 (skipped 4891984) - head: 0 0x4d61…9360 - finalized: 0x0000…0000:0
Oct-12 00:37:29.000[]                 info: Searching peers - peers: 0 - slot: 4891985 (skipped 4891985) - head: 0 0x4d61…9360 - finalized: 0x0000…0000:0
 ```
- branch v1.1.0, but no difference
- how I run it: `/lodestar beacon --data-dir=./data --jwt-secret=../datadir/jwt.hex`
- `name -a
Linux ethnode 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by TimDaub** [comment]
As discussed in Discord, I've now:

- Updated to [v1.2.0-rc.1](https://github.com/ChainSafe/lodestar/releases/tag/v1.2.0-rc.1)
- Added `--logLevel debug` and `DEBUG=*`

Here's what I've got and it looks like there is an error reading the peer list.

[cl.txt](https://github.com/ChainSafe/lodestar/files/9778644/cl.txt)

could be this? https://github.com/libp2p/js-libp2p-mdns/blob/36d68fc819316ec7f7a215a38310d90130770e0f/src/compat/querier.ts#L103

**Comment by TimDaub** [comment]
So I checked the logs and as I said, there is this error showing up:

-  https://github.com/libp2p/js-libp2p-mdns/blob/36d68fc819316ec7f7a215a38310d90130770e0f/src/compat/querier.ts#L103
- And if we look into the implementation of libp2p-mdns, then we can see that it looks for a PTR entry and a SERVICE_TAG: https://github.com/libp2p/js-libp2p-mdns/blob/36d68fc819316ec7f7a215a38310d90130770e0f/src/compat/utils.ts#L12
- This tag seems to be https://github.com/libp2p/js-libp2p-mdns/blob/36d68fc819316ec7f7a215a38310d90130770e0f/src/compat/constants.ts#L1 `_ipfs-discovery._udp`
- But in my logs, here's the entry

```
 {                                                                             
12280     name: '_ipfs-discovery._udp.local',                                         
12281     type: 'PTR',                                                                
12282     class: 'IN',                                                                
12283     ttl: 120,                                                                   
12284     data: '16Uiu2HAmFWHujkipXAACvuqDPUZSmSnuQgZueE1F5usdfnw2F4WS._ipfs-discovery._udp.loca
12285   }
```

note how there is a "local" post-pended.

**Comment by g11tech** [comment]
can you clear `peerstore` directory (in your main `dataDir`) and try again, sometimes this just works and node starts fetching peers

**Comment by TimDaub** [comment]
> can you clear `peerstore` directory (in your main `dataDir`) and try again, sometimes this just works and node starts fetching peers

I had deleted the entire data dir a couple of times and nothing new happened. But I did it again now and it's still trying to find peers now.

**Comment by philknows** [comment]
This seems to be a very isolated issue, potentially something with your environment, which makes it harder to debug. Could you try either `v1.1.1.` or `v1.0.0` and see if you encounter similar issues? Any additional information you can provide about your setup may help.

**Comment by twoeths** [comment]
it was shown in a user's (modulok) console that there is no bootEnrs so discv5 cannot issue FINDNODEs request

![](https://cdn.discordapp.com/attachments/743858262864167062/1057393521339928586/image.png)

https://discord.com/channels/593655374469660673/743858262864167062/1057393521646129262

**Comment by twoeths** [comment]
was able to reproduce the issue by skipping `--network` in the cli, or comment out `network` in rcconfig.yml file.

@TimDaub please add `--network mainnet` to your cli. I'm gonna have a PR to fix this issue too.

**Comment by dapplion** [comment]
@tuyennhv as an extra safe-guard Lodestar could check if discv5 table is empty and the log an error
