### ISSUE TITLE
v1.2.0: missed attestations due to insufficient peers

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4660]
**Describe the bug**

After we deploy v1.2.0-rc.1, there is a missed attestation due to insufficient peers:

```
validator-2022-10-15.log:7224:Oct-15 03:57:26.860[]                error: Error publishing attestations slot=4915185 Internal Server Error: PublishError.InsufficientPeers
```

The sent peers when we publish attestations are actually down compared to v1.1.0

<img width="1245" alt="Screen Shot 2022-10-16 at 17 01 22" src="https://user-images.githubusercontent.com/10568965/196029360-6c955945-6a1f-4afe-b98a-1f962047e472.png">

**Expected behavior**

- Investigate why the sent peers are so low
- It should be the same to v1.1.0

**Comment by twoeths** [comment]
Number of topic peers are actually dropped.

- on a mainnet node with v1.1.0 then v1.2.0.rc-1 (8 validators)

<img width="1218" alt="Screen Shot 2022-10-16 at 17 07 42" src="https://user-images.githubusercontent.com/10568965/196029570-cc8bd65d-9a83-4b02-a835-d1af6cb8214c.png">

- on a node with v1.1.0 only (8 validators)

<img width="1210" alt="Screen Shot 2022-10-16 at 17 08 17" src="https://user-images.githubusercontent.com/10568965/196029596-3e03876c-cc51-4d09-b44f-0475e4e9cec8.png">

**Comment by twoeths** [comment]
"Outgoing request error rate" is so high with v1.2.0

<img width="1219" alt="Screen Shot 2022-10-17 at 14 24 32" src="https://user-images.githubusercontent.com/10568965/196114156-01568a65-5bea-466a-b813-d3a51026ac08.png">

two of them are legacy errors like "stream ended before 1 bytes became available" or "REQUEST_ERROR_EMPTY_RESPONSE"

```
~/beacon$ grep -e "stream ended before 1 bytes became available\|REQUEST_ERROR_EMPTY_RESPONSE" -rn beacon-2022-10-15.log | wc -l
26168
~/beacon$ grep -e "stream ended before 1 bytes became available\|REQUEST_ERROR_EMPTY_RESPONSE" -rn beacon-2022-10-16.log | wc -l
~/beacon$ grep -e "stream ended before 1 bytes became available\|REQUEST_ERROR_EMPTY_RESPONSE" -rn beacon-2022-10-14.log | wc -l
29500
~/beacon$ grep -e "stream ended before 1 bytes became available\|REQUEST_ERROR_EMPTY_RESPONSE" -rn beacon-2022-10-12.log | wc -l
288
~/beacon$ grep -e "stream ended before 1 bytes became available\|REQUEST_ERROR_EMPTY_RESPONSE" -rn beacon-2022-10-11.log | wc -l
746
```

**Comment by twoeths** [comment]
since lodestar peer scores are low, we send goodbye to a lot of peers

<img width="800" alt="Screen Shot 2022-10-17 at 14 40 50" src="https://user-images.githubusercontent.com/10568965/196117579-c0e362d5-d70c-48a8-b026-4de8f90f758d.png">

**Comment by twoeths** [comment]
we also received a lot of goodbye requests for different reasons 

<img width="1271" alt="Screen Shot 2022-10-18 at 09 21 10" src="https://user-images.githubusercontent.com/10568965/196320362-14fab24f-c127-418c-b8b4-e327845e65f7.png">

**Comment by twoeths** [comment]
our I/O was super busy, other nodes disconnected us due to the timeout and we got penalties

<img width="1232" alt="Screen Shot 2022-10-18 at 20 33 17" src="https://user-images.githubusercontent.com/10568965/196444283-f86aead4-65c3-4c7a-a22c-4d5342223af0.png">

**Comment by twoeths** [comment]
it's still an issue in `v1.2.0`:

<img width="1297" alt="Screen Shot 2022-11-09 at 15 18 36" src="https://user-images.githubusercontent.com/10568965/200776068-edb6c1e7-759e-499e-ae9a-e06b411dc072.png">

**Comment by twoeths** [comment]
haven't seen this issue since we deploy v1.2.0 (at least in the 39-validator node). Also the number of topic peers (sent peers) grew up after the 1st 2 days

<img width="805" alt="Screen Shot 2022-11-11 at 08 51 04" src="https://user-images.githubusercontent.com/10568965/201244841-3cfa6d98-7ee4-4906-bcad-42731f84d85b.png">

**Comment by nazarhussain** [comment]
I am seeing lot of these error messages on the `unstable` branch during the sim tests. 

```
Eph 4/4 1.635[node-2-cl-lodestar/api] [31merror[39m: Error on submitPoolAttestations [0] slot=36, index=2 PublishError.InsufficientPeers
Error: PublishError.InsufficientPeers
    at EventTarget.publish (file:///home/runner/work/lodestar/lodestar/node_modules/@chainsafe/libp2p-gossipsub/src/index.ts:1957:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at EventTarget.publishObject (file:///home/runner/work/lodestar/lodestar/packages/beacon-node/src/network/gossip/gossipsub.ts:171:20)
    at EventTarget.publishBeaconAttestation (file:///home/runner/work/lodestar/lodestar/packages/beacon-node/src/network/gossip/gossipsub.ts:213:12)
    at file:///home/runner/work/lodestar/lodestar/packages/beacon-node/src/api/impl/beacon/pool/index.ts:52:31
    at async Promise.all (index 0)
    at Object.submitPoolAttestations (file:///home/runner/work/lodestar/lodestar/packages/beacon-node/src/api/impl/beacon/pool/index.ts:46:7)
    at Object.handler (file:///home/runner/work/lodestar/lodestar/packages/api/src/utils/server/genericJsonServer.ts:41:23)
```

**Comment by dapplion** [comment]
@tuyennhv Would be good to take a look at the sim tests run to understand why network health is bad

**Comment by twoeths** [comment]
@nazarhussain @dapplion I opened https://github.com/ChainSafe/lodestar/issues/4764
