### ISSUE TITLE
Outgoing request error rate

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4661]
**Describe the bug**

Starting from Oct 14, the "Outgoing request error rate" metric spiked on `unstable`

<img width="1238" alt="Screen Shot 2022-10-17 at 14 10 38" src="https://user-images.githubusercontent.com/10568965/196111601-9c27fb74-7851-4e14-b0f9-b3d65f38a074.png">

There are logs like:

```
ct-16 00:00:03.150[network]       ^[[36mverbose^[[39m: Req  error method=ping, encoding=ssz_snappy, client=Unknown, peer=16...1fmVye, requestId=33248 code=REQUEST_ERROR_DIAL_ERROR, error=The dial request has no valid addresses
Error: The dial request has no valid addresses
    at DefaultDialer.dial (file:///usr/app/node_modules/libp2p/src/connection-manager/dialer/index.ts:182:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processTimers (node:internal/timers:499:9)
    at EventTarget.openConnection (file:///usr/app/node_modules/libp2p/src/connection-manager/index.ts:521:26)
    at EventTarget.dial (file:///usr/app/node_modules/libp2p/src/libp2p.ts:382:12)
    at EventTarget.dialProtocol (file:///usr/app/node_modules/libp2p/src/libp2p.ts:396:24)
    at file:///usr/app/packages/beacon-node/src/network/reqresp/request/index.ts:91:22
    at withTimeout (file:///usr/app/packages/utils/src/timeout.ts:19:12)
Error: REQUEST_ERROR_DIAL_ERROR
    at file:///usr/app/packages/beacon-node/src/network/reqresp/request/index.ts:102:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processTimers (node:internal/timers:499:9)
    at sendRequest (file:///usr/app/packages/beacon-node/src/network/reqresp/request/index.ts:88:20)
    at ReqResp.sendRequest (file:///usr/app/packages/beacon-node/src/network/reqresp/reqResp.ts:157:22)
    at ReqResp.ping (file:///usr/app/packages/beacon-node/src/network/reqresp/reqResp.ts:103:12)
    at PeerManager.requestPing (file:///usr/app/packages/beacon-node/src/network/peers/peerManager.ts:348:25)
Oct-16 00:00:03.150[network]       ^[[36mverbose^[[39m: Req  error method=status, encoding=ssz_snappy, client=Unknown, peer=16...1fmVye, requestId=33249 code=REQUEST_ERROR_DIAL_ERROR, error=The dial request has no valid addresses
```

@g11tech this could be related to #4658 as I don't see other commits around this time

**Expected behavior**

No error

**Comment by g11tech** [comment]
checking

**Comment by g11tech** [comment]
Documenting the investigation so far:

log of a peer id where this error was thrown
```typescript
  id: Secp256k1PeerIdImpl [PeerId(16Uiu2HAmVPLt1XZLrafBnTK3i1sKf8qQ5zYTokQyNEm4R581Bbnq)] {
    type: 'secp256k1',
    multihash: Digest {
      code: 0,
      size: 37,
      digest: <Buffer 08 02 12 21 03 f8 94 99 06 b1 3b b6 3c 15 b8 01 7b 25 b5 10 ea d5 43 1b 8a 9d 11 c2 de 6a 7b 76 de 66 21 b2 1a>,
      bytes: [Uint8Array]
    },
    privateKey: undefined,
    publicKey: <Buffer 08 02 12 21 03 f8 94 99 06 b1 3b b6 3c 15 b8 01 7b 25 b5 10 ea d5 43 1b 8a 9d 11 c2 de 6a 7b 76 de 66 21 b2 1a>
  },
  multiaddrs: [],
  dialTarget: {
    id: '16Uiu2HAmVPLt1XZLrafBnTK3i1sKf8qQ5zYTokQyNEm4R581Bbnq',
    addrs: []
  }
}
```
clearly this peerId didn't have gave any multiaddrs and hence there were no addrs to dail,

but on a fetch of the info of the peer via api:
 ```
{"data":{"peer_id":"16Uiu2HAmVPLt1XZLrafBnTK3i1sKf8qQ5zYTokQyNEm4R581Bbnq","enr":"","last_seen_p2p_address":"/ip4/34.221.99.113/tcp/9000/p2p/16Uiu2HAmVPLt1XZLrafBnTK3i1sKf8qQ5zYTokQyNEm4R581Bbnq","direction":"outbound","state":"connected"}}
```

The IP doesn't seem to belong to any of lodestar deployments, so unlikely that #4658 is the cause.

But will observe and see if there is any coherent pattern that can be observed on this error.

**Comment by g11tech** [comment]
UPDATE:
for *unstable lg1* this error rate has come drastically down to previous normals  on container restart it seems 

![image](https://user-images.githubusercontent.com/76567250/196169192-b9098c82-f859-4a37-a990-44abaeee1e73.png)

while feat1 errors on new deployment have since gone up

**Comment by g11tech** [comment]
on *feat 1 lg1* since deployment of unstable, errors seemed to have increased however, but not the dail errors so much (so `no valid addresses` are really the concern for e,g. on 3 instances of such errors like like 4-5 hours)

However status and ping errors really have seemed to increase:
![image](https://user-images.githubusercontent.com/76567250/196173017-4285e793-e667-4042-8e17-5b2f1fd54c62.png)

and looking at the debug log there seems to be some issue

![image](https://user-images.githubusercontent.com/76567250/196173515-721fdb53-e38c-4f0e-bfb6-27b4809c87db.png)

**Comment by g11tech** [comment]
also w.r.t. `no valid addresses error"... it seems that there is a recurring dial out of a single peer which is having this bad data, shouldn't libp2p ban this peer automatically?

![image](https://user-images.githubusercontent.com/76567250/196201044-e38029da-785c-4146-ac4c-d57eed8bbe69.png)

also node doesnt seem to have any data for this particular peer
![image](https://user-images.githubusercontent.com/76567250/196201835-7eb02885-5fa9-4aef-a389-137f8c6554a9.png)

**Comment by g11tech** [comment]
looking at the dial errors (which could also be reason behind status and ping errors) on `feat1 lg1`, just a single peer seems to be the reason of all the trouble (added peerId  console log before throwing)

![image](https://user-images.githubusercontent.com/76567250/196255974-d10793d4-2331-41c5-b59f-623aaaf9b76c.png)

**Comment by twoeths** [comment]
yeah this is the common issue since we upgrade libp2p, same to v1.2.0-rc.1 https://github.com/ChainSafe/lodestar/issues/4660#issuecomment-1280411436

**Comment by twoeths** [comment]
this still happens in v1.2.0

<img width="812" alt="Screen Shot 2022-11-11 at 09 38 48" src="https://user-images.githubusercontent.com/10568965/201250712-8287527d-60aa-4c7a-bd25-b4b626f84a8d.png">

I think the reason is we received many goodbye requests, we also sent out many goodbye requests

<img width="817" alt="Screen Shot 2022-11-11 at 09 39 44" src="https://user-images.githubusercontent.com/10568965/201250829-04b47d44-41f7-47ed-944e-03c24e1d25dd.png">

which lead to 20% Dial error rate

<img width="823" alt="Screen Shot 2022-11-11 at 09 40 16" src="https://user-images.githubusercontent.com/10568965/201250893-69b0b947-713b-4db7-9f1a-f1430c8d557b.png">

- v1.1.0
```
grep -e "REQUEST_ERROR_DIAL_ERROR" -rn beacon-2022-11-08.log | wc -l
2304
```

- v1.2.0
```
grep -e "REQUEST_ERROR_DIAL_ERROR" -rn beacon-2022-11-10.log | wc -l
36534
```

sample log

```
Nov-10 00:00:01.871[network]       ^[[36mverbose^[[39m: Req  error method=ping, encoding=ssz_snappy, client=Teku, peer=16...iK3cxw, requestId=33174 code=REQUEST_ERROR_DIAL_ERROR, error=All promises were rejected
AggregateError: All promises were rejected
Error: REQUEST_ERROR_DIAL_ERROR
    at file:///usr/app/packages/beacon-node/src/network/reqresp/request/index.ts:102:15
    at sendRequest (file:///usr/app/packages/beacon-node/src/network/reqresp/request/index.ts:88:20)
    at ReqResp.sendRequest (file:///usr/app/packages/beacon-node/src/network/reqresp/reqResp.ts:198:22)
    at ReqResp.ping (file:///usr/app/packages/beacon-node/src/network/reqresp/reqResp.ts:104:12)
    at PeerManager.requestPing (file:///usr/app/packages/beacon-node/src/network/peers/peerManager.ts:348:25)
Nov-10 00:00:01.871[network]       ^[[36mverbose^[[39m: Req  error method=status, encoding=ssz_snappy, client=Teku, peer=16...iK3cxw, requestId=33176 code=REQUEST_ERROR_DIAL_ERROR, error=All promises were rejected
AggregateError: All promises were rejected
Error: REQUEST_ERROR_DIAL_ERROR
    at file:///usr/app/packages/beacon-node/src/network/reqresp/request/index.ts:102:15
    at sendRequest (file:///usr/app/packages/beacon-node/src/network/reqresp/request/index.ts:88:20)
    at ReqResp.sendRequest (file:///usr/app/packages/beacon-node/src/network/reqresp/reqResp.ts:198:22)
    at ReqResp.status (file:///usr/app/packages/beacon-node/src/network/reqresp/reqResp.ts:96:12)
    at PeerManager.requestStatus (file:///usr/app/packages/beacon-node/src/network/peers/peerManager.ts:360:27)
    at async Promise.all (index 0)
    at PeerManager.requestStatusMany (file:///usr/app/packages/beacon-node/src/network/peers/peerManager.ts:369:7)
Nov-10 00:00:02.191[network]       ^[[36mverbose^[[39m: Req  done method=status, encoding=ssz_snappy, client=Prysm, peer=16...5TozdR, requestId=33177, numResponse=1
```

**Comment by twoeths** [comment]
This happens with v1.2.1 in mainnet nodes. It happens to a single peer really have no multiaddr somehow, every 10 seconds we got 2 "REQUEST_ERROR_DIAL_ERROR" errors with status request and ping request, the metrics say that's low tolerance error so we should disconnect the peer due to low score but somehow we did not.

**Comment by philknows** [comment]
As of `v1.4.0` some samples from mainnet nodes:

cip-canary-bn
<img width="812" alt="Screenshot 2023-01-31 at 9 35 31 AM" src="https://user-images.githubusercontent.com/58080811/215789792-23884694-f55b-4ed6-acd8-f2c18779194a.png">

beta-mainnet-hzax41
<img width="810" alt="Screenshot 2023-01-31 at 9 34 47 AM" src="https://user-images.githubusercontent.com/58080811/215789992-c7fee7be-faa7-446d-8008-2c08cd06c22b.png">

Moving to v1.5.0 milestone if still required.

**Comment by twoeths** [comment]
this issue was original caused when we keeps dialing to a single peer, does not happen anymore in v1.4.2 (there are a lot of libp2p/network upgrade since we found the issue). Caught some metrics from some nodes:

- Node 7

<img width="1306" alt="Screen Shot 2023-02-15 at 11 17 01" src="https://user-images.githubusercontent.com/10568965/218928607-0c83d234-891e-444f-ac50-241c423f4a0a.png">

- Node 8

<img width="1285" alt="Screen Shot 2023-02-15 at 11 17 28" src="https://user-images.githubusercontent.com/10568965/218928710-d7eaada2-4f8f-45b6-afc9-7798799eb2e8.png">

- Node 9

<img width="1283" alt="Screen Shot 2023-02-15 at 11 17 49" src="https://user-images.githubusercontent.com/10568965/218928762-62bd325e-d923-41bc-ac9c-ccf436f56f19.png">
