### ISSUE TITLE
Feature: Support beaconcha.in client node monitoring endpoint

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#4666]
**Is your feature request related to a problem? Please describe.**

Currently, all of the 4 other consensus clients support [beaconcha.in's mobile app node monitoring](https://kb.beaconcha.in/beaconcha.in-explorer/mobile-app-less-than-greater-than-beacon-node) feature. 

**Describe the solution you'd like**

We should setup a node `--monitoring-endpoint` that is compatible with beaconcha.in's API to display metrics for the node operator.

**Comment by dapplion** [comment]
Assigning to @nflaig

**Comment by nflaig** [comment]
assign to me
