### ISSUE TITLE
v1.2.0: High gc time compared to old libp2p

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4669]
**Describe the bug**

After we migrate libp2p2 0.39.2, the `gc` percentage is higher

- On beta v1.2.0 lg1k

<img width="1238" alt="Screen Shot 2022-10-19 at 17 27 17" src="https://user-images.githubusercontent.com/10568965/196666434-00254162-0151-450f-8d6b-67350c681078.png">

- On stable v1.1.0 lg1k

<img width="1245" alt="Screen Shot 2022-10-19 at 17 24 57" src="https://user-images.githubusercontent.com/10568965/196665927-3f95d978-e7c2-4b9a-abe5-11f9f2e52a95.png">

- On beta v1.2.0 novc

<img width="1221" alt="Screen Shot 2022-10-19 at 17 25 33" src="https://user-images.githubusercontent.com/10568965/196666062-15924ecf-511d-4714-909c-3598707fde76.png">

- On stable v1.1.0 novc

<img width="1238" alt="Screen Shot 2022-10-19 at 17 26 24" src="https://user-images.githubusercontent.com/10568965/196666256-5562796e-d325-4c33-b5e2-dae9b4320b49.png">

This causes a lot of apis to run slower

<img width="570" alt="Screen Shot 2022-10-19 at 17 28 38" src="https://user-images.githubusercontent.com/10568965/196666735-efb0ee46-5fbc-491e-b13a-9e9f62aed330.png">

[1019_feat2_lg1k_1.2.0_rc.0.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/9819579/1019_feat2_lg1k_1.2.0_rc.0.cpuprofile.zip)

This could affect https://github.com/ChainSafe/lodestar/issues/4660

**Expected behavior**

Same gc run time to stable

**Comment by twoeths** [comment]
First effort https://github.com/libp2p/js-libp2p-multistream-select/pull/28

**Comment by twoeths** [comment]
every time we call `chacha20poly1305` it runs gc because we create temporary Uint8Array instances there

<img width="1420" alt="Screen Shot 2022-10-20 at 10 40 32" src="https://user-images.githubusercontent.com/10568965/196850987-06dfdf00-a92b-4ee1-8ef1-c3364429f773.png">

this could be improved if we implement wasm version of this protocol in https://github.com/ChainSafe/lodestar/issues/4652

**Comment by twoeths** [comment]
`as-chacha20poly1305` work does not help much, the issue also happens on a `novc` node (even with a workaround version to use `is-ip` 4.0.0 in #4689). We need to come up with tests of basic node setup to narrow down the issue.

**Comment by twoeths** [comment]
issue is resolved via https://github.com/ChainSafe/lodestar/pull/4699

v1.2.0-rc.1 metrics

- novc

<img width="791" alt="Screen Shot 2022-10-31 at 08 56 16" src="https://user-images.githubusercontent.com/10568965/198915656-a7b35e05-e647-42c0-9cda-4ec1ad8cb068.png">

- lg1k

<img width="807" alt="Screen Shot 2022-10-31 at 08 56 40" src="https://user-images.githubusercontent.com/10568965/198915716-8c87d2c3-9c17-42a8-9654-de18eb999de0.png">

these metrics are the same to stable group (v1.1.1)

**Comment by philknows** [comment]
Adding note for reference, libp2p metrics was causing this. Fixed by disabling here: https://github.com/ChainSafe/lodestar/pull/4699

Followed up for investigation under #4698.
