### ISSUE TITLE
Implement missing ssz generic spec tests

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#467]
Currently our ssz spec tests covers only static tests, our spec-tes-utils package provides spec test directory as param so it's possible to implement generic tests as well.

**Comment by mpetrunic** [comment]
unstale

**Comment by dapplion** [comment]
@mpetrunic Could you detail what tests specifically are lacking?

**Comment by mpetrunic** [comment]
> @mpetrunic Could you detail what tests specifically are lacking?

https://github.com/ethereum/eth2.0-specs/tree/dev/tests/formats/ssz_generic 

I had them implemented but contrainer tests werent passing and meanwhile we removed ssz from lodestar so that branch got deleted :(

**Comment by dapplion** [comment]
@mpetrunic :sweat_smile: So should this issue be moved to the SSZ repo?

**Comment by mpetrunic** [comment]
cc @wemeetagain since he does not want spec tests dep in ssz repo :)

**Comment by dapplion** [comment]
@wemeetagain bump

**Comment by dapplion** [comment]
I've been working on this issue today and there are a lot of errors and very serious on the SSZ side. We must incorporate these tests in the ssz repo and fix the issues asap.
- Numbers being deserialized to `Infinity`
- Strange rounding errors, `13097433917148758497` being deserialized to `13097433917148758000`
- Wrong hash tree roots

Branch WIP https://github.com/ChainSafe/lodestar/compare/dapplion/spec-test-ssz-generic

**Comment by dapplion** [comment]
@mpetrunic I would prefer for some else to take this issue since I'm not that familiar with SSZ internals

**Comment by wemeetagain** [comment]
assigning to myself

**Comment by dapplion** [comment]
Implemented
