### ISSUE TITLE
Rest APIs for light client return invalid response

### ISSUE THREAD

**Issue by eunsoo-icon** [ChainSafe/lodestar#4674]
**Describe the bug**

https://lodestar-mainnet.chainsafe.io/eth/v1/beacon/light_client/finality_update/
https://lodestar-mainnet.chainsafe.io/eth/v1/beacon/light_client/optimistic_update/

There is no "signature_slot" in response.

**Expected behavior**

https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getLightClientFinalityUpdate
https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getLightClientOptimisticUpdate

**Steps to Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

- OS: 
- Version: 
- Branch: 
- Commit hash:

**Comment by eunsoo-icon** [comment]
Found one more bug. The above APIs won't work without the last '/'.

**Comment by wemeetagain** [comment]
Thanks for the report. Both issues should be resolved in #4365

**Comment by dadepo** [comment]
Closing as #4365 has been merged.
