### ISSUE TITLE
verkle trees: add 2 fields to ExecutionData

### ISSUE THREAD

**Issue by gballet** [ChainSafe/lodestar#4681]
With the verge, proofs and witness of the pre-state of an (EL) block execution are included in the blocks.  In order to build a PoS testnet that provides proofs in blocks, it would be great if it were possible to create a branch with the required fields to be added to the `ExecutionData`.

The `ExecutionData` needs to have two more, optional fields:

 * `VerkleProof`, a byte array of variable length
 * `VerkleKeyVals`, an array of (key, value) pairs, in which the key is a 32-byte vector, and value is a byte vector of length either 0 (missing value) or 32.

At the moment, there is no need to support forking as for this testnet, verkle trees are used since the genesis.

If present, these two fields should be propagated over the network with the rest of the ExecutionData so that other clients can inject these fields in their verkle-enabled EL.

**Comment by dapplion** [comment]
This looks doable, should be in some fork tho to fit our type system.

@gballet Will other clients build this ExecutionData on top of bellatrix, capella or eip4844 types? You should clarify the data structure to ensure interop

**Comment by gballet** [comment]
@dapplion That would be on top of Bellatrix.

**Comment by dapplion** [comment]
- Closing issue since there exist a branch with this fix. We won't merge to unstable until considered for inclusion but Lodestar can join devnets now https://github.com/ChainSafe/lodestar/pull/5164
