### ISSUE TITLE
v1.2.0: investigate fromBytes performance issue

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4690]
**Describe the bug**

With v1.2.0, on a node of 1000 keys, `fromBytes()` takes more than 8% of cpu time

<img width="1255" alt="Screen Shot 2022-10-25 at 21 49 27" src="https://user-images.githubusercontent.com/10568965/197806723-6658be0a-748a-43cb-9ac6-963e9c4c75d8.png">
[1025_lg1k_chacha20poly1305_no_mem_alloc.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/9861357/1025_lg1k_chacha20poly1305_no_mem_alloc.cpuprofile.zip)

**Expected behavior**

In v1.1.1, it takes only around 1% with the same type of node

<img width="1277" alt="Screen Shot 2022-10-25 at 21 50 37" src="https://user-images.githubusercontent.com/10568965/197807046-342b495f-7211-497d-98c1-71f6434df089.png">

[0525_lg1k_v1.1.1.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/9861372/0525_lg1k_v1.1.1.cpuprofile.zip)

**Comment by dapplion** [comment]
Unrelated but important, noticed that on [0525_lg1k_v1.1.1.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/9861372/0525_lg1k_v1.1.1.cpuprofile.zip) afterProcessEpoch is run 3 times between 250500 ms and 255500 ms (~5s range)

![Screenshot from 2022-10-25 21-21-59](https://user-images.githubusercontent.com/35266934/197919536-f85dc9d8-6ecd-4070-b5b5-8309eaec54cc.png)

**Comment by twoeths** [comment]
v1.2.0 process more attestation, looking into the number of `aggregateAttestationInto` calls it's 3.3x compared to v1.1

![Screen Shot 2022-10-26 at 11 42 17](https://user-images.githubusercontent.com/10568965/197936402-d785b60a-7b77-413f-85a6-f3443249b7c2.png)

v1.1.0
<img width="1291" alt="Screen Shot 2022-10-26 at 11 42 52" src="https://user-images.githubusercontent.com/10568965/197936474-10074323-ce27-46c3-a364-8fa97031c345.png">

in both nodes it receives the same number of valid attestations per second
<img width="1265" alt="Screen Shot 2022-10-26 at 13 41 05" src="https://user-images.githubusercontent.com/10568965/197953307-6f10c44c-21a3-4bc9-8b0d-cad8e5f80a47.png">

so it could be v1.2.0 receives more attestations in the last 3 slots that causes us to do the preaggregation 3x times

**Comment by dapplion** [comment]
@tuyennhv I've been looking into how to improve this:
- We can not cache "de-serialized" signatures since they are sent to the Workers parsed
- The only trade-off we can do I think is to aggregate the signatures lazily at aggregation time. WIP at https://github.com/ChainSafe/lodestar/compare/dapplion/aggregate-pool-fromBytes

**Comment by twoeths** [comment]
> @tuyennhv I've been looking into how to improve this:
> 
> * We can not cache "de-serialized" signatures since they are sent to the Workers parsed
> * The only trade-off we can do I think is to aggregate the signatures lazily at aggregation time. WIP at https://github.com/ChainSafe/lodestar/compare/dapplion/aggregate-pool-fromBytes

this could help improve the I/O lag issue a bit as doing preaggregate at 0 - 1/3 of slot would make us more busy, let's try doing the aggregation at 2/3 of slot 👍

**Comment by twoeths** [comment]
if we use multistream-select 3.1.1, seems like the p2p are improved and we receive so many attestations which cause `fromBytes` to take 22% of cpu time

<img width="1079" alt="Screen Shot 2022-11-01 at 19 22 00" src="https://user-images.githubusercontent.com/10568965/199231278-c249c8ca-221d-42b5-aa17-6c5b9ff88ba0.png">

[0111_multi_stream_select_3.1.1_lg1k.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/9909725/0111_multi_stream_select_3.1.1_lg1k.cpuprofile.zip)

maybe attestations are aggregated too much which cause `fromBytes` to run so frequently and our peers are out of mesh then aggregated rates are dropped

<img width="1268" alt="Screen Shot 2022-11-01 at 19 26 14" src="https://user-images.githubusercontent.com/10568965/199231949-e15ee778-ba07-4718-b96b-64567588f01d.png">

<img width="757" alt="Screen Shot 2022-11-01 at 19 27 48" src="https://user-images.githubusercontent.com/10568965/199232203-f05509fd-7793-47cf-8381-54328ba380e8.png">

**Comment by dapplion** [comment]
@tuyennhv Closing for now as https://github.com/ChainSafe/lodestar/pull/4838 should make fromBytes calls much cheaper. Once you do another CPU profile in the future please confirm
