### ISSUE TITLE
Release Checklist Dashboard 

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#4724]
As discussed on the Nov 4 planning call, we determined it would be good to have a dashboard to look at very specific parameters of the node to ensure it is safe for release. This will also supplement some sort of standardized way to look at metrics between engineers and allow us to quickly observe critical metrics that will help determine whether or not a release is safe to go out. 

We should figure out the process that each engineer uses to look at metrics data and compile them into a Release Dashboard, which will also serve as a checklist for us.

**Comment by twoeths** [comment]
These are metrics I usually look at before a release:
- Lodestar - validator monitor: prev epoch miss ratio, wrong head ratio
- VM + host: Heap + external memory, process memory, gc, CPU Usage of lodestar
- Lodestar/general: number of peers, average number of mesh peers for attestation subnet topic
- Lodestar - networking: all metrics in summary part, Gossip validation queue: job time, dropped job, Gossip Block Received Delay, Gossip block process time
- Lodestar - debug gossipsub: Peer count per gossip score threshold, Attnet count with >0 mesh peers, Gossip RPCs transmitted / sec
- Lodestar - block processor: Rate of blocks being set as head after 4s

Need inputs from others as well to finalize the list before implementing

**Comment by philknows** [comment]
Thanks for this @tuyennhv. Once we get input from others, can we have a specific dashboard for release metrics which include the suggestions here for a quick glance to determine release decision? Thanks!

**Comment by philknows** [comment]
There are a lot of factors that make this too difficult to combine into a specific dashboard.
