### ISSUE TITLE
1.1 and 1.2 no peer connection on windows

### ISSUE THREAD

**Issue by wiwi0123** [ChainSafe/lodestar#4725]
since update 1.1 but windows test config no longer synchronizes and finds no peer and remains blocked

![image](https://user-images.githubusercontent.com/6229771/200119047-83eb6f30-112c-4da6-90dc-676c96f4b88f.png)

my pc is behind a router and it is nat as you can see in the screen where there are only private ips

but the sync works in 1.0

launch a synchro on a windows pc in a nat

**Steps to Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

- OS: windows
- Version: 10
- Branch: 1.1 and 1.2

**Comment by philknows** [comment]
Can you explain a little bit more about your setup? Is this being run on docker images on windows? The more information to help try to replicate, the better. Thanks!

**Comment by wiwi0123** [comment]
as I am testing I just use npm to install lodestar

**Comment by dapplion** [comment]
Closing issues for specific incidents on old versions of Lodestar, please re-open if it happens with latest stable
