### ISSUE TITLE
Support serving sync committee hashes

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#4733]
**Is your feature request related to a problem? Please describe.**

For light clients, we are experimenting with new ways to ensure we can enable light client sync in the most optimal way possible, with the best assurances of truth. Using https://github.com/lightclients/kevlar for optimistic syncing, we can easily ask for hashes of the sync committee to make comparisons amongst a set of provers. We would just need an easy way to get this information from clients like Lodestar to serve this data through an endpoint.

**Describe the solution you'd like**

To help with the optimistic construction, it would be ideal to add an endpoint to fetch the hashes off the sync committee such as `getCommitteeHash` or `getOptimisticHash` with a route of something similar to `/eth/v1/beacon/light_client/committee_hash`. We should implement this in Lodestar, test it and then push upstream to include it in the beaconAPIs spec. 

**Additional context**

This feature is to help with supporting better syncing methods for software such as Kevlar using the light client protocol.

**Comment by shresthagrawal** [comment]
Thanks, @philknows for creating the initial issue. A small addition to the endpoint structure. It would be good to have support for downloading these hashes in batches. So something like `/eth/v1/beacon/light_client/committee_hash?start_period=x&period_cnt=y`. Feel free to check out the existing prover implementation [here](https://github.com/lightclients/kevlar/blob/main/src/provers/light-optimistic/server.ts#L17)

**Comment by twoeths** [comment]
when it comes to the spec, I think it's more suitable to go with sync committee root instead of hash to compliant to all of the specs in ethereum consensus layer. Also in lodestar, we track sync committee root (not hash).

The PR #4736 still go with committee hash to serve the need of kevlar atm.

what do you think @shresthagrawal ?

**Comment by shresthagrawal** [comment]
@tuyennhv sync committee root should work as well. I guess that would be preferred as we would like to push it to the official spec as well

**Comment by philknows** [comment]
Closed and implemented, but there's more work to be done to get this standardized in the spec. And in the meantime, move this to the Lodestar namespace.
