### ISSUE TITLE
Use standard Github 'good-first' and 'help-wanted' labels

### ISSUE THREAD

**Issue by wslyvh** [ChainSafe/lodestar#4741]
I'd recommend to bring back the default `good-first` and `help-wanted` labels for issues instead of the customized `meta-good-first-issue` or `meta-help-wanted`. Good first and help wanted are 'special' labels within Github itself which can be used as standards across repos, e.g. explorers, queries, etc. like your contribute page
https://github.com/ChainSafe/lodestar/contribute

But also allows 3rd-party website and integrations to query those over Github's API
E.g. https://www.useweb3.xyz/contribute

This would make it a lot easier for first-time contributors to find and explore such issues.

**Comment by philknows** [comment]
Thanks for the feedback!
