### ISSUE TITLE
Validator Client: Track skipped slots

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4749]
**Is your feature request related to a problem? Please describe.**

At validator side, sometimes we skip slots (mainly due to the I/O lag issue) without noticing it

**Describe the solution you'd like**

- Track it metrics
- Add some warn logs

**Comment by dapplion** [comment]
What do mean with validator client skipping a slot?

**Comment by twoeths** [comment]
> What do mean with validator client skipping a slot?

@dapplion in `runAtMostEvery()` of validator clock, it's designed that if a task spans more than a slot, next slot is skipped and it really happened on mainnet

**Comment by dapplion** [comment]
Got it! There is an argument to be made if skipping the slot is the previous runs for too long is actually a good idea. Would be good to have metrics to understand how often that happens and for how much does it overrun the slot

**Comment by nflaig** [comment]
- related discussion https://github.com/ChainSafe/lodestar/issues/5314

**Comment by philknows** [comment]
Closed in favour of #5314
