### ISSUE TITLE
v1.1.x: High Gossip Block Process Time on mainnet

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4750]
**Describe the bug**

This metric tracks the time we process block since the time we receive it

on goerli node of 1000 validators

<img width="1262" alt="Screen Shot 2022-11-11 at 11 19 05" src="https://user-images.githubusercontent.com/10568965/201262369-9aea813b-14de-460c-91cd-9f716a5d067e.png">

however on a mainnet node of 100 validators it's way higher

<img width="1274" alt="Screen Shot 2022-11-11 at 11 19 43" src="https://user-images.githubusercontent.com/10568965/201262440-95523fcc-72fd-4a97-91b9-4551e4b3f3e1.png">

Since we see a lot of time to process block, validators are not able to submit correct head attestations (they vote for previous block instead) and in a lot of cases no aggregator include them, hence attestations are missed

**Expected behavior**

The metrics on mainnet should be like goerli where we see way less missed attestations

**Comment by dapplion** [comment]
This metric is too imprecise, please check a histogram of delay till head to understand how often the block is set as head post 4 seconds

**Comment by twoeths** [comment]
@dapplion  Here's a heatmap representation
- A goerli node of 1000 validators

<img width="1290" alt="Screen Shot 2022-11-14 at 11 23 39" src="https://user-images.githubusercontent.com/10568965/201574869-eaba1510-f17b-4605-98ae-594435b60d15.png">

- A mainnet node of 100 validators - it shows more data at 4s - 6s and 6s - 12s and >12s

<img width="1262" alt="Screen Shot 2022-11-14 at 11 24 33" src="https://user-images.githubusercontent.com/10568965/201574965-4de15d9b-0b7d-4a3b-b900-0fff542bd6b1.png">

**Comment by twoeths** [comment]
same root cause to #4789

right now a gossip block is processed by 2 queues: gossip validation queue then block processor queue and it causes some delay. In a healthy network condition, we could/should process block immediately in order for validator to submit correct head attestations

**Comment by wemeetagain** [comment]
- I think this has been resolved with https://github.com/ChainSafe/lodestar/pull/4858, but will wait for confirmation from @tuyennhv

**Comment by twoeths** [comment]
@wemeetagain  yes it was resolved. Double checked again with v1.4.2 on a 100-validator mainnet node:

<img width="1342" alt="Screen Shot 2023-02-11 at 06 33 01" src="https://user-images.githubusercontent.com/10568965/218221769-f900f7c4-52d4-430f-9c05-e425ff55ee4d.png">
