### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined

### ISSUE THREAD

**Issue by Dimo99** [ChainSafe/lodestar#4753]
When I import `@lodestar/types`. 
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined
**Desktop (please complete the following information):**

- Version: 1.2.0

**Comment by dapplion** [comment]
`@lodestar/types` is an ESM package, which can not be imported from a ComonJS project / module.

If that's the case this blog post gives context on the issue https://blog.logrocket.com/how-to-use-ecmascript-modules-with-node-js/

**Comment by wemeetagain** [comment]
Closing this issue since the solution has been provided
