### ISSUE TITLE
Send sim test logs + metrics to external Prometheus

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4754]
Debugging sim tests is time consuming. Having access to metrics and logs indexing would be a huge productivity boost. I propose:

- Setup a new independent external Prometheus server to collect metrics
- Setup Loki + Prometheus in sim test runs
- Send logs + metrics to external Prometheus with label that's unique to each run. It must include at least `run_id = $GITHUB_RUN_ID_$GITHUB_RUN_NUMBER` and should be prepended by git data like branch name (see ref https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables)

**Comment by philknows** [comment]
It is decided to not have these dashboards due to the lack of sim tests providing useful information in such a short run (~18m).
