### ISSUE TITLE
Run longer sim tests on demand on self-hosted runner

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4758]
**Motivation**

As part of automated testing we want to run longer sim tests at critical moments of our development pipeline.

**Exploration**

_from https://github.com/ChainSafe/lodestar/pull/4756#issuecomment-1312079997_

Self hosted runners operate differently: they don't start from a clean slate but just run on bare metal and **do not clean up**. Instead Github self hosted runners run on fresh VMs that are destroyed after the fact.

From an offline exchange with Pari:

> L: When using Github self hosted runners, every registered runner can run exactly 1 job at a time? Do you know if that can be customized? In your usage of it with kurtosis is there any issue with clean-up after the fact? Being used to Github own runners where you get a fresh environment every time that is destroyed after the fact, using self hosted has some challenges
> P: yeah so you can't customize it - we had the same issue on our system. So the fix is to register multiple runners on the same physical host so you "hack" it in. When no jobs are running, nothing changes about the usage anyway. The correct way to do it would be to use something like:
> - Actuated: https://blog.alexellis.io/blazing-fast-ci-with-microvms/
> - Kubernetes with the autoscaling option to spin up more runners when there are pending jobs
> - Amazon's free autoscaling service for github runners
>
> But in practice, Github makes this hard so incentivize using their runner services. I have an explicit job that cleans up kurtosis post run irrespective of fail/success - so i haven't had any stale file issues there.

IMO we should not run every sim test on the self hosted runner, but instead do:
- Run on Github runners on commit a light version of the sim tests that are okay with low power machines. Sim tests have shown to be very stable with correct business logic
- Run on self hosted runners **only on demand** for key commits on key PRs + on merge to master + before release. This less frequent tests could do much longer runs with more nodes.

This approach makes sense because the workflow must be different:
- Requires more setup phase
- Must assume another test is running in the background, so ports, paths must not conflict
- Requires a tear-down phase

**Comment by nazarhussain** [comment]
The current SIM tests setup take ~9min to execute on Github runners. There is no way we can reduce the time unless we change the number of assertions or the number of epochs to run. 

I believe when SIM tests extends with more use cases, then we have to split those in different scenarios to decrease the execution time and at that time we can think of splitting between Gihub runners and self hosted runners. 

For the team down phase on self-hosted runners, our sim tests uses docker to bootup containers of different clients. So the cleanup is quite easy to just remove all the containers from docker.

**Comment by dapplion** [comment]
@nazarhussain sim tests on commit taking 10-15 min is perfectly okay. The longer runs on demand should be of ~60-90 minutes

**Comment by aktech** [comment]
By the way, if you want a no-maintenance method to achieve that, you can use [cirun.io](https://cirun.io) for the same.

**Comment by nazarhussain** [comment]
> @nazarhussain sim tests on commit taking 10-15 min is perfectly okay. The longer runs on demand should be of ~60-90 minutes

As our sim tests are still in reasonable threshold we don't need self hosted on demand runner. In future if needed we can reopen the issue.

**Comment by nflaig** [comment]
> > @nazarhussain sim tests on commit taking 10-15 min is perfectly okay. The longer runs on demand should be of ~60-90 minutes
> 
> As our sim tests are still in reasonable threshold we don't need self hosted on demand runner. In future if needed we can reopen the issue.

Could be considered for benchmarks, those take 25-30 minutes and produce a lot of false positives all the time.
