### ISSUE TITLE
getUpdates function of lightclient no longer works

### ISSUE THREAD

**Issue by jtguibas** [ChainSafe/lodestar#4763]
Calling the endpoint https://lodestar-goerli.chainsafe.io/eth/v1/beacon/light_client/updates?start_period=484&count=1 no longer works.

Simply goto https://lodestar-goerli.chainsafe.io/eth/v1/beacon/light_client/updates?start_period=484&count=1 in your browser.

It should have returned the best update for period 484. The Goerli network is current on period 526, so the best update here should exist.

Simply goto https://lodestar-goerli.chainsafe.io/eth/v1/beacon/light_client/updates?start_period=484&count=1 in your browser. The error I get is:

```
HttpError: Internal Server Error: No partialUpdate available for period 484
    at HttpClient.requestWithBody (/home/john/zk-light-client/operator/node_modules/@lodestar/api/src/utils/client/httpClient.ts:258:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at HttpClient.json (/home/john/zk-light-client/operator/node_modules/@lodestar/api/src/utils/client/httpClient.ts:128:12)
    at Object.request (/home/john/zk-light-client/operator/node_modules/@lodestar/api/src/utils/client/client.ts:75:21)
    at main (/home/john/zk-light-client/operator/src/helper/step.ts:32:28) {
  status: 500,
  url: 'https://lodestar-goerli.chainsafe.io/eth/v1/beacon/light_client/updates?start_period=484&count=1'
}
```

**Comment by wemeetagain** [comment]
We had to resync our public nodes last week, and they're still syncing :(

```
$ curl https://lodestar-goerli.chainsafe.io/eth/v1/node/syncing
{"data":{"head_slot":"868031","sync_distance":"3448992","is_syncing":true,"is_optimistic":false}}
```

**Comment by jtguibas** [comment]
Actually, I don't think that this is the reason for the issue. I have my own node running that claims that the sync distance is 0. I still get the same error.

Furthermore, if it were just a syncing issue, partial updates for early periods should be available, but they are not.

**Comment by hujw77** [comment]
> We had to resync our public nodes last week, and they're still syncing :(
> 
> ```
> $ curl https://lodestar-goerli.chainsafe.io/eth/v1/node/syncing
> {"data":{"head_slot":"868031","sync_distance":"3448992","is_syncing":true,"is_optimistic":false}}
> ```

May I ask why you need to re-sync lodestar? because I also run a lodestar node.

**Comment by philknows** [comment]
> May I ask why you need to re-sync lodestar? because I also run a lodestar node.

It is due to #4702 which changes the way light client updates are stored. So we had to resync the database since the v1.2.x upgrade.

**Comment by hujw77** [comment]
@philknows May I ask why the lodestar mainnet node re-sync again? I notice the syncing.
```sh
~ curl https://lodestar-mainnet.chainsafe.io/eth/v1/node/syncing
{"data":{"head_slot":"1758802","sync_distance":"3450913","is_syncing":true,"is_optimistic":false}}⏎
```

**Comment by philknows** [comment]
> @philknows May I ask why the lodestar mainnet node re-sync again? I notice the syncing.
> 
> ```shell
> ~ curl https://lodestar-mainnet.chainsafe.io/eth/v1/node/syncing
> {"data":{"head_slot":"1758802","sync_distance":"3450913","is_syncing":true,"is_optimistic":false}}⏎
> ```

It's still syncing from previously. Hasn't completed yet as far as I'm aware. I'm going to get one of our devops to take a further look into this.

**Comment by dapplion** [comment]
Closing issues for specific incidents on old versions of Lodestar, please re-open if it happens with latest stable
