### ISSUE TITLE
Low mesh peers on md64 nodes

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4766]
**Describe the bug**

This happens with v1.2.1 (could be even earlier since we haven't had these `md64` instances for a while)

<img width="1307" alt="Screen Shot 2022-11-15 at 18 07 00" src="https://user-images.githubusercontent.com/10568965/201904854-a16cd5a2-ac43-4ea1-b610-1df3afc5b9f1.png">

not sure why it only happens with `md64` instances

**Expected behavior**

Should be 64 consistently

**Comment by wemeetagain** [comment]
fixed as of 1.8.0, probably much earlier
