### ISSUE TITLE
Kurtosis testing

### ISSUE THREAD

**Issue by nazarhussain** [ChainSafe/lodestar#4772]
**Is your feature request related to a problem? Please describe.**

Complement sim tests by using external tools. 

**Describe the solution you'd like**

Run small devnets for short time but with all other client combinations. Medium level of assertions

**Additional context**

This issue is extracted from the SIM tests Epic https://github.com/ChainSafe/lodestar/issues/4275

**Comment by dapplion** [comment]
Our current test infra supports multi-client so no need for Kurtosis testing at the moment
