### ISSUE TITLE
Hive testing

### ISSUE THREAD

**Issue by nazarhussain** [ChainSafe/lodestar#4773]
**Is your feature request related to a problem? Please describe.**

Complement sim tests by using external tools. 

**Describe the solution you'd like**

Run small devnets for short time but with unusual network conditions. Low level of assertions. https://github.com/ChainSafe/lodestar/issues/4240

**Additional context**

This issue is extracted from the SIM tests Epic https://github.com/ChainSafe/lodestar/issues/4275

**Comment by dapplion** [comment]
Hive tests are currently covered by EF devops deployed tooling, should not be added here
