### ISSUE TITLE
Missed attestations due to delayed block process

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4789]
**Describe the bug**

In the last 3 days, there are 3 missed attestations on mainnet nodes, all of them are due to delayed block process, block came early enough but got processed only after 4s, validator submitted wrong heads and no aggregator/block include them

- Slot 5175706: block is received 2.5s after slot but only became head after 4.4s => it took 1.9s to process

```
Nov-20 08:21:35.000[chain]         ^[[36mverbose^[[39m: Clock slot slot=5175706
Nov-20 08:21:38.263[network]       ^[[36mverbose^[[39m: Received gossip block slot=5175706, root=0xc7b3…8f0a, curentSlot=5175706, peerId=16Uiu2HAmAQLr32DoW9iBiNKdyLp4nCUGWvfCixZSs7eZra3GPk1C, delaySec=2.49399995803833
Nov-20 08:21:39.435[chain]         ^[[36mverbose^[[39m: New chain head headSlot=5175706, headRoot=0xc7b31a3bfa3c435f851e62b0a491489aa33ac05c344982e194889644a2df8f0a, delaySec=4.434999942779541
Nov-20 08:21:39.435[chain]         ^[[36mverbose^[[39m: Block processed slot=5175706, root=0xc7b31a3bfa3c435f851e62b0a491489aa33ac05c344982e194889644a2df8f0a, delaySec=4.434999942779541
```

- Slot 5176963: block was received 2s after the slot but became head only after 4.9s => it took 2.9s to process
```
Nov-20 12:32:59.000[chain]         ^[[36mverbose^[[39m: Clock slot slot=5176963
Nov-20 12:33:01.044[network]       ^[[36mverbose^[[39m: Received gossip block slot=5176963, root=0xa68b…7508, curentSlot=5176963, peerId=16Uiu2HAkuVTNVU2stE4sg71eE8mSs9TNEg126SQbyV9VhGoP68RK, delaySec=1.997999906539917
Nov-20 12:33:03.934[chain]         ^[[36mverbose^[[39m: New chain head headSlot=5176963, headRoot=0xa68bf57f9ec614fcca59c461e25ff5801b585acbe622a540482bf80e62537508, delaySec=4.934000015258789
Nov-20 12:33:03.934[chain]         ^[[36mverbose^[[39m: Block processed slot=5176963, root=0xa68bf57f9ec614fcca59c461e25ff5801b585acbe622a540482bf80e62537508, delaySec=4.934000015258789
```

- Slot 5177951: block was received 3.1s after the slot but became head only after 4.3s => it took 1.2s to process
```
Nov-20 15:50:38.317[network]       ^[[36mverbose^[[39m: Received gossip block slot=5177951, root=0xc6a1…71e5, curentSlot=5177951, peerId=16Uiu2HAkvafBgXW7xdhPk9VJqxAha8bUzA9kyh1AiLjkKB3bhfLo, delaySec=3.0920000076293945
Nov-20 15:50:39.320[chain]         ^[[36mverbose^[[39m: New chain head headSlot=5177951, headRoot=0xc6a161f431cf038c4fb60e67db537467bf32fcc9c8225c0e26ba5cd8f21d71e5, delaySec=4.319999933242798
Nov-20 15:50:39.321[chain]         ^[[36mverbose^[[39m: Block processed slot=5177951, root=0xc6a161f431cf038c4fb60e67db537467bf32fcc9c8225c0e26ba5cd8f21d71e5, delaySec=4.3210000991821
```

**Expected behavior**

Should take less delay time after we receive block to process, make sure all blocks are processed within 4s.

**Comment by twoeths** [comment]
Right now in the queue logic there is either `setTimeout()` or `sleep(0)` code which only trigger a block process only in the next event loop, and it has to finish all micro tasks in the current event loop

@dapplion one thing we could try is to process block immediately without going through the queue if:
- block slot = clock slot
- we have parent root in forkchoice
- optional: within 4s

this is similar to proposer boost, what do you think?

**Comment by dapplion** [comment]
@tuyennhv You should validate your hypothesis first.

- Claim: setTimeout() or sleep(0) code adds some delay of block process
- To proof: Add a metric or console log to track the delay before that sleep and after

If that metric shows some delay, say > 50ms I'm okay with your proposed change

**Comment by twoeths** [comment]
@dapplion  there are 2 queues:

- Gossip validation queue: The job queue for block usually has 1 block maximum at a time so we can use `jobWaitTime` to measure the `setTimeout()` delay, in the worse case it could be up to 1s

(this is from a 100-validator mainnet node)
<img width="1265" alt="Screen Shot 2022-11-22 at 11 14 49" src="https://user-images.githubusercontent.com/10568965/203219845-b6de69f4-18ff-43b8-b34e-d9a360ae95a0.png">

- Block processor queue: similarly

<img width="1276" alt="Screen Shot 2022-11-22 at 11 26 07" src="https://user-images.githubusercontent.com/10568965/203221246-7674f19d-d209-49a9-be98-7afeecc87eec.png">

(I captured by 1m chart to find the worse case scenarios)

that could partially explain for the "wrong head ratio" we have (this is 1h chart for 1 mainnet node in the last 30 days)

<img width="1269" alt="Screen Shot 2022-11-22 at 11 28 39" src="https://user-images.githubusercontent.com/10568965/203221598-eb3f4f4b-6857-4d44-9eec-618793014303.png">

**Comment by dapplion** [comment]
@tuyennhv I've plotted the histogram's buckets to check if the queue wait time is a major contributor to delays. To read the charts below, the query is:
```
12 * rate(lodestar_block_processor_queue_job_wait_time_seconds_bucket[30m])
```
with "Format: heatmap", so each label reads as the "le" value where it's the percent of values that are between that bucket and the next. For example the series labeled as "1" mean the rate of values in the range "0.1 - 1".

Looking below the block consistently takes ~2 seconds to process. Job wait times are high in very rare occasions < 1% of times. Also the peaks in job wait time do not correlate that clearly with wrong head metric and high block processing times.

As next steps:
- First would be important to understand what step of block processing contributes the most. Add histogram metrics on each step of the block processing code paths
- List points in block processing where async code is hit, which could enable the point below
- Understand if queue job wait times are a result of the event loop being busy, for example due to attestation processing

![Screenshot from 2022-11-22 13-03-09](https://user-images.githubusercontent.com/35266934/203309444-a87d5d34-f53a-438f-b1dc-9839f1ef3a0c.png)
![Screenshot from 2022-11-22 13-03-17](https://user-images.githubusercontent.com/35266934/203309441-3a3467fe-7e15-4260-923f-607cad4b7df3.png)

**Comment by twoeths** [comment]
> Looking below the block consistently takes ~2 seconds to process

@dapplion not sure what metrics you used to measure that, the below metrics say it takes only 300ms-700ms to process block most of the time

```
(rate(lodestar_gossip_block_elappsed_time_till_processed_sum[$__rate_interval])/rate(lodestar_gossip_block_elappsed_time_till_processed_count[$__rate_interval]) - (rate(lodestar_gossip_block_elappsed_time_till_received_sum[$__rate_interval])) / rate(lodestar_gossip_block_elappsed_time_till_received_count[$__rate_interval]))
``` 

<img width="1297" alt="Screen Shot 2022-11-24 at 10 23 03" src="https://user-images.githubusercontent.com/10568965/203686936-cd419a24-092b-4924-94e5-77c77316f5a7.png">

that's confirmed by the log

```
Nov-24 03:14:59.955[network]       verbose: Received gossip block slot=5202973, root=0x1151…2cd3, curentSlot=5202973, peerId=16Uiu2HAm5pzYeaL4K2BJgrHivXcTJUFSvKsdLQKsLijpbQoFtVDQ, delaySec=0.937999963760376
Nov-24 03:15:00.374[chain]         verbose: Block processed slot=5202973, root=0x1151a530b912d120dd1cdb3e5c90f7bb76d0cc010df9c3a19c2ac9f6c44d2cd3, delaySec=1.374000072479248


Nov-24 03:15:12.837[network]       verbose: Received gossip block slot=5202974, root=0x6e94…7abf, curentSlot=5202974, peerId=16Uiu2HAm5pzYeaL4K2BJgrHivXcTJUFSvKsdLQKsLijpbQoFtVDQ, delaySec=1.815000057220459
Nov-24 03:15:13.188[chain]         verbose: Block processed slot=5202974, root=0x6e94cf7eab2cfa05148b0c148a163a7f85eeb9404c1ffa7141613ae603ea7abf, delaySec=2.187999963760376

Nov-24 03:15:26.065[network]       verbose: Received gossip block slot=5202975, root=0xb84e…2d01, curentSlot=5202975, peerId=16Uiu2HAm5pzYeaL4K2BJgrHivXcTJUFSvKsdLQKsLijpbQoFtVDQ, delaySec=3.0409998893737793
Nov-24 03:15:26.396[chain]         verbose: Block processed slot=5202975, root=0xb84eee7448ab891386810cdff7469a423f1d79661e2cf5667d2ef3d8755d2d01, delaySec=3.3959999084472656

Nov-24 03:15:38.515[network]       verbose: Received gossip block slot=5202976, root=0xfbdd…2e6c, curentSlot=5202976, peerId=16Uiu2HAm5pzYeaL4K2BJgrHivXcTJUFSvKsdLQKsLijpbQoFtVDQ, delaySec=3.49399995803833
Nov-24 03:15:39.086[chain]         verbose: Block processed slot=5202976, root=0xfbddcd5c1db381428ffd4a094afe9e36d4ff1425d6c4e36b921082aefa2e2e6c, delaySec=4.085999965667725

Nov-24 03:15:49.029[network]       verbose: Received gossip block slot=5202977, root=0x2f2a…d2df, curentSlot=5202977, peerId=16Uiu2HAm5pzYeaL4K2BJgrHivXcTJUFSvKsdLQKsLijpbQoFtVDQ, delaySec=2.007999897003174
Nov-24 03:15:49.330[chain]         verbose: Block processed slot=5202977, root=0x2f2abd6e9dad6c93048ce9b7d04c365f55a399de7f2619ed635ffab0ce44d2df, delaySec=2.3299999237060547
```

so the block process time of ~1.2s to 2.9s in the issue is really just exceptional cases, and we should only debug those exceptional cases.

**Comment by twoeths** [comment]
Deployed `tuyen/timing_block_process` to a mainnet node subscribing to all subnets, found some blocks with significant time to process a block

- Dec-04 23:48:21.310[chain]         verbose: Imported block slot=5281139, recvToImportedBlock=8.513999938964844
  - Dec-04 23:48:12.816[network]       ^[[36mverbose^[[39m: Received gossip block slot=5281139, root=0x9464…b7d9, curentSlot=5281139, peerId=16Uiu2HAm5v688pXE3ppChqdLPF2VzWTomndrvJGi5auBFquSv9tj, delaySec=1.7960000038146973, recvToVal=0.019999980926513672
  - Dec-04 23:48:12.904[chain]         ^[[36mverbose^[[39m: Transitioned gossip block slot=5281139, recvToTransition=0.10800004005432129
  - Dec-04 23:48:12.926[chain]         ^[[36mverbose^[[39m: Verified block signatures slot=5281139, recvToSigVer=0.13000011444091797
  - Dec-04 23:48:17.731[chain]         ^[[36mverbose^[[39m: Verified execution payload slot=5281139, recvToVerifiedExecPayload=4.934999942779541

=> it took ~4.8s to verify execution payload and ~3.6s to import block

- Dec-04 23:57:59.299[chain]         verbose: Imported block slot=5281187, recvToImportedBlock=6.884000062942505
  - Received gossip block slot=5281187, root=0xf597…8a73, curentSlot=5281187, peerId=16Uiu2HAmJsu4168VQNxHmNpDavXPDZo93LVPSZhbe2Q58suByrfz, delaySec=5.414999961853027, recvToVal=2.9070000648498535
  - Transitioned gossip block slot=5281187, recvToTransition=6.325999975204468
  - Verified block signatures slot=5281187, recvToSigVer=6.3480000495910645
  - Verified execution payload slot=5281187, recvToVerifiedExecPayload=6.829999923706055

=> it took 2.9s from receiving the block to verifying it, 3.4s for gossip validation + state transition

- Dec-05 02:56:34.047[chain]         verbose: Imported block slot=5282080, recvToImportedBlock=8.204999923706055
  - Received gossip block slot=5282080, root=0xd65d…b147, curentSlot=5282080, peerId=16Uiu2HAmJhbjjfdguFwx3h3mjadSE8NEVps7QRgjwcfkEJZLuMsC, delaySec=2.8420000076293945, recvToVal=0.01399993896484375
  - Transitioned gossip block slot=5282080, recvToTransition=0.20300006866455078
  - Verified block signatures slot=5282080, recvToSigVer=0.22600007057189941
  - Verified execution payload slot=5282080, recvToVerifiedExecPayload=8.15499997138977

=> almost 8s to verify execution payload

- Dec-05 02:56:45.700[chain]         verbose: Imported block slot=5282081, recvToImportedBlock=9.871999979019165
  - Received gossip block slot=5282081, root=0x0fde…06fc, curentSlot=5282081, peerId=16Uiu2HAm5v688pXE3ppChqdLPF2VzWTomndrvJGi5auBFquSv9tj, delaySec=0.8280000686645508, recvToVal=0.7070000171661377
  - Transitioned gossip block slot=5282081, recvToTransition=3.6459999084472656
  - Verified block signatures slot=5282081, recvToSigVer=3.6669998168945312
  - Verified execution payload slot=5282081, recvToVerifiedExecPayload=9.823999881744385

=> it took 0.7s from receiving the block to verifying it, 2.9s for gossip validation + state transition, ~6.1s for execution payload validation

Note that this only mean the time between tasks, it does not mean a specific task takes time at all. It's most likely the use of `sleep(0)` (at least in job queue) delay the task sometimes

**Comment by twoeths** [comment]
There are some percentage of job wait time >1s when processing a gossip block, ideally they should be all 0

<img width="1302" alt="Screen Shot 2022-12-05 at 15 45 10" src="https://user-images.githubusercontent.com/10568965/205592975-9d20a196-73e2-4e70-bf04-b7b0a69478c8.png">


<img width="1293" alt="Screen Shot 2022-12-05 at 15 45 43" src="https://user-images.githubusercontent.com/10568965/205593071-1bf35339-3b33-418f-af0a-a00db0bff0b3.png">

<img width="1276" alt="Screen Shot 2022-12-05 at 15 46 14" src="https://user-images.githubusercontent.com/10568965/205593156-16c82a1d-f6f6-4dd6-8701-43dd397fced8.png">

<img width="1326" alt="Screen Shot 2022-12-05 at 15 46 48" src="https://user-images.githubusercontent.com/10568965/205593288-8b9d4458-0f9e-4d02-a4ad-b93150431616.png">
