### ISSUE TITLE
Browser tests failed in CI: 

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4795]
**Describe the bug**

In some recent CI runs, Browser tests failed with
```
@lodestar/utils: 21 11 2022 22:37:17.765:ERROR [launcher]: Cannot start FirefoxHeadless
@lodestar/utils: 	Can not find the binary firefox
@lodestar/utils: 	Please set env variable FIREFOX_BIN
@lodestar/utils: 21 11 2022 22:37:17.767:ERROR [launcher]: FirefoxHeadless stdout: 
@lodestar/utils: 21 11 2022 22:37:17.767:ERROR [launcher]: FirefoxHeadless stderr: 
```
for example https://github.com/ChainSafe/lodestar/actions/runs/3518653218/jobs/5897797085

I don't see this error in my local environment

**Expected behavior**

No error

**Comment by nazarhussain** [comment]
The error clearly meant that it's Firefox was not installed on the machine, which is very weird as this never happens before and these tests are stable for couple of months. 

Will try a re-run it once again to see if it's some weird CI runner issue. If it persists then will debug further.
