### ISSUE TITLE
Create block pool

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#481]
- should accept blocks and form chains (might contain multiple chains in case of forks)
- should request parent blocks if missing

**Comment by mpetrunic** [comment]
One solution:
- have a hash map linking blockHash -> block
- array of head blocks?!
- don't run state transition (just put them there)
- in case fork choice throws different head, trace changed blocks from head block in array using block hash map and block.parentRoot
- submit all different blocks from current change to "fork changer" method

**Comment by GregTheGreek** [comment]
> One solution:
> 
> * have a hash map linking blockHash -> block

Agreed
> * array of head blocks?!

Not elegant, but we could make them a priority cue, by adding a weight to them. The weight could be the amount of times we've seen that head over the wire? Probably susceptible to DoS?

> * don't run state transition (just put them there)

Agreed, should run them at a later time
> * in case fork choice throws different head, trace changed blocks from head block in array using block hash map and block.parentRoot

What do you mean?
> * submit all different blocks from current change to "fork changer" method

Got a link to the code?

**Comment by mpetrunic** [comment]
> Not elegant, but we could make them a priority cue, by adding a weight to them. The weight could be the amount of times we've seen that head over the wire? Probably susceptible to DoS?

We actually don't need that. When our fork choice spits out different head than ours. Just go in hashmap of blocks and assemble new chain.

> What do you mean?

Check answer above.
Flow:
1. fork choice returns different head (hash)
2. check if we have that head in block pool (hashmap)
3. if we have, go in hashmap and find block.parentRoot
3. repeat until common block in our current chain

> Got a link to the code?

https://github.com/ChainSafe/lodestar/issues/320 :smile:

**Comment by GregTheGreek** [comment]
Cool that all makes sense...

**Comment by mpetrunic** [comment]
unstale

**Comment by twoeths** [comment]
unstale
