### ISSUE TITLE
Align light client APIs with beacon-APIs

### ISSUE THREAD

**Issue by hujw77** [ChainSafe/lodestar#4812]
https://github.com/ethereum/beacon-APIs/pull/247
```diff
 diff --unified \
      <(curl -s "https://lodestar-goerli.chainsafe.io/eth/v1/beacon/light_client/updates?start_period=500&count=1" | jq) \
      <(curl -s "http://unstable.prater.beacon-api.nimbus.team/eth/v1/beacon/light_client/updates?start_period=500&count=1" | jq)
--- /dev/fd/11  2022-11-25 15:06:10
+++ /dev/fd/12  2022-11-25 15:06:10
@@ -1,12 +1,13 @@
-{
-  "data": [
-    {
+[
+  {
+    "version": "bellatrix",
+    "data": {
       "attested_header": {
-        "slot": "4097055",
-        "proposer_index": "274054",
-        "parent_root": "0x4987da1c0b42cf2633ee2f9b8d690b9040245a92f0fa8befaa3caaca0fc952e7",
-        "state_root": "0xe263d9b02eb03ea6854630d405ba351ffa264c13b5a69fcc83d6f7a6102f42a9",
-        "body_root": "0x74f334bfce2f0bf41c185f602f2761b09add84f249d02a94f85c0d63dc56fb93"
+        "slot": "4097477",
+        "proposer_index": "63871",
+        "parent_root": "0x9d087996c4179d17753af1c78e3c923fea283562f67c756c21db97379552996b",
+        "state_root": "0x6060993d4bed7ef680d181674b368f3ba4826cbf4a917add8b5fd4c6db44fe02",
+        "body_root": "0x1b48df98a57d496a543edddaad2f1efba06a9722b5075b675573dd722c65f8a0"
       },
       "next_sync_committee": {
         "pubkeys": [
@@ -527,31 +528,31 @@
       },
       "next_sync_committee_branch": [
         "0x20383b704227adbd41a2ba5e6344a261fac69faadb37323ab2aa1c4f58bf490e",
-        "0x57e9c5bf57a4210d7d2652e5b2d988f5eb6bea94aad14f7a8936b5eef4930cfd",
-        "0x50112f4a626d6ecd5e4d492ec087649a4bc1e9c5feb3341b5ed265dc7c7f93b5",
-        "0xd5a712758eb28ae961ece9f00530415cfea98ae53d0b2c134338d5afac78292d",
-        "0xac45a2e44099354cea7aa5ca37182a9a17fcbe6239c5d13230b4e47ccbea6993"
+        "0xdb48f8b78bef3096d6672da19c92743baddd1bbbfa44059ffc47f8ab3ba8a791",
+        "0x29719a872f27c9b602ca648daf9bde7f2121aef960683f4cbef8af0924337ee4",
+        "0x0de42b5c575d6a872c01eb8943308c3f9570674677a9b55a7d1e2748bdf602b6",
+        "0xd000cb9ebca43ea71bbc998a613c7ad0dc9c06548b35601f084b7cafb0d1aa5e"
       ],
       "finalized_header": {
-        "slot": "4096960",
-        "proposer_index": "135111",
-        "parent_root": "0x8f55fddf1801a59c9903e93b7de723763525667e77207670d8f7282cfdb67d18",
-        "state_root": "0x1602f6c3c7a024294101485f3dd4da4584176224aea016db9d0595f708e0a216",
-        "body_root": "0x16126bf0285422e60ba3c1926ca7bb21204e59e753738b6db9d90f8436aee6fa"
+        "slot": "4097408",
+        "proposer_index": "40202",
+        "parent_root": "0x0e7ec3696acd3db042c7c8b1c9a216df4e7fc509bb4d77c2ec6ae8cdf31d2eae",
+        "state_root": "0x360abd21d0b179c698dae8bfdb8a2aa1a0cb9279ed8dcd125440e12cb705aedb",
+        "body_root": "0xf1f579f9b5fd334713b9cac285a4ffa0ab5a065309543ce6a5c0a3befc6733ad"
       },
       "finality_branch": [
-        "0x1ef4010000000000000000000000000000000000000000000000000000000000",
+        "0x2cf4010000000000000000000000000000000000000000000000000000000000",
         "0xb9e27e742c646ed456256e87a5dd7d1c9b0806813bcf5417226eb9270a394cd0",
         "0xfa2ee10325d0d3fbb385ea2d1c020d98a2e7ac5e56887f741fb493f6dd5ff503",
-        "0x50112f4a626d6ecd5e4d492ec087649a4bc1e9c5feb3341b5ed265dc7c7f93b5",
-        "0xd5a712758eb28ae961ece9f00530415cfea98ae53d0b2c134338d5afac78292d",
-        "0xac45a2e44099354cea7aa5ca37182a9a17fcbe6239c5d13230b4e47ccbea6993"
+        "0x29719a872f27c9b602ca648daf9bde7f2121aef960683f4cbef8af0924337ee4",
+        "0x0de42b5c575d6a872c01eb8943308c3f9570674677a9b55a7d1e2748bdf602b6",
+        "0xd000cb9ebca43ea71bbc998a613c7ad0dc9c06548b35601f084b7cafb0d1aa5e"
       ],
       "sync_aggregate": {
-        "sync_committee_bits": "0xfbd3dfc7ff5ffff2ff7dddf4fee2f763d6fdfff6ff7fcbf7e2ffdfdf8bbbfefdfffff77ffffb6ff5faffbff7e7ff1eefaf5affbef77ff7febfff9c5ff7defd5d",
-        "sync_committee_signature": "0x99ecf0563b315823799550b35daf8569bd9091c8a4e6f2d4f33ef13fc49c00f524b38a0530f6774d0171b28aae9d005d109df81589618f21530ae5129f243a4dedd5f6b830ab40d39a25d85963a8451a1f84da71d4b6a70637cf91517b58b89f"
+        "sync_committee_bits": "0xfbd3dfc7ff5ffff3ff7dddb4fee2f77fd6fdfff6ff7fcbf7e2ffdfdf8bbbfefdfffff77ffffb6ff5faffbff7e7ff1eefaf5affbef77ff7febfff9c5ff7defd5d",
+        "sync_committee_signature": "0xb58cc16285825dff3e62d254ca5dc8ba58f3c2192b8dee3361eaabd0416eda471384d7ca62f11fc31adfb666988be1a10b82d58ce8c2b2677b037c356d7e74f6d0af970c1dfcc9ffe7770d1790b794edafac8f97b5c47e4cfa1f468f4a2a4c5d"
       },
-      "signature_slot": "4097056"
+      "signature_slot": "4097481"
     }
-  ]
-}
+  }
+]

```

**Comment by dadepo** [comment]
Thanks for opening this issue. It is being worked on as part of https://github.com/ChainSafe/lodestar/pull/4641

**Comment by dapplion** [comment]
> Thanks for opening this issue. It is being worked on as part of #4641

- How is this issue related to https://github.com/ChainSafe/lodestar/pull/4641 ? This issue reports incorrect data between Nimbus and Lodestar

**Comment by wemeetagain** [comment]
Looks like the shape is different. Array of objects vs Object of arrays. Also missing the `"version"` field in each update.

**Comment by dadepo** [comment]
> > Thanks for opening this issue. It is being worked on as part of #4641
> 
> * How is this issue related to [Support content negotiation of light client data served via rest api #4641](https://github.com/ChainSafe/lodestar/pull/4641) ? This issue reports incorrect data between Nimbus and Lodestar

@dapplion On first glance it looked like the issue would build on #4641 specifically changes needed to include the version and also the testing, that it thought it would be duplicated effort implementing it separately.  Once I started the implementation It ended up not overlapping 100%. 

It is implemented now on the branch and I think the most pragmatic thing to do is to move forward with that PR. I don't think spending time to separate into two PR's will be an effective use of time.

Plus that PR has been open for the past 2 months. And as you also mentioned in the comment, it does what it should do. So holding back not reviewing and merging does not give us anything beneficial since the more we wait, the more lodestar API is not compliant with the spec. The technical optimisation can be added later.

**Comment by dapplion** [comment]
> It is implemented now on the branch and I think the most pragmatic thing to do is to move forward with that PR. 

I do not agree with the design decisions of #4641 so if the fix it there it would be delayed unnecessarily. It not a good idea to add bug fixes on feature PR and not split.

> I don't think spending time to separate into two PR's will be an effective use of time.

I just re-wrote the EIP-4844 PR (3,500 lines) into 17 separate PRs (for now) and doing so helped up the code quality significantly plus we are having progress since most are already merged or close to, while the big one is still stuck. I do think it's a great use of time to split PRs when it makes sense even completely re-writing them if necessary.

**Comment by dadepo** [comment]
> I just re-wrote the EIP-4844 PR (3,500 lines) into 17 separate PRs (for now) and doing so helped up the code quality significantly plus we are having progress since most are already merged or close to, while the big one is still stuck. I do think it's a great use of time to split PRs when it makes sense even completely re-writing them if necessary.

Sure. a PR touching 3,500 lines implementing a crucial feature like EIP-4844 should be split. I see the value in that.

But for a PR of 500 lines (20 files), that contains changes that can, for all intents and purposes, be reviewed at once and merged in, safe for your reservation regarding a pre-existing technical limitation? I would go about it differently. And don't get me wrong. It is not as if I believe PRs should not be scoped properly, I already explained why this ended up co-mingled in previous comments.  

But I guess we disagree.

Anyways, here is a separate PR https://github.com/ChainSafe/lodestar/pull/4877 that adds versioning to the LC API. Please help review 🙏
