### ISSUE TITLE
Don't log API errors for 'expected' errors

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#4814]
Currently, we are logging errors for light client partial updates that we cannot serve because the node is still syncing. 

```
Nov-26 15:10:34.905[rest]            error: Req req-1tgi getUpdates error  No partialUpdate available for period XXX
Error: No partialUpdate available for period XXX
    at LightClientServer.getUpdate (file:///usr/app/packages/beacon-node/src/chain/lightClient/index.ts:289:13)
    at async Promise.all (index 0)
    at Object.getUpdates (file:///usr/app/packages/beacon-node/src/api/impl/lightclient/index.ts:49:23)
    at Object.handler (file:///usr/app/packages/api/src/utils/server/genericJsonServer.ts:41:23)
```

Generally, our REST APIs are hit by the validator for things like getting duties. Knowing errors are important, however, using our node as a public endpoint for things like serving partialUpdate for light clients should ideally not log this, especially during sync. 

Solution:
When syncing, these types of errors should not be displayed as an error. Because it's not a user config error or requires action on the part of the user. These errors are triggered from external requests and just requires more syncing time for the error to go away.

**Comment by dapplion** [comment]
A proper solution would be:
- Add flag to enable Beacon node in "public API server mode"
- If that option is true, then API logger should filter errors by their code. The API handlers should type 'expected' errors such as update not available with a dedicated HTTP status error code.

**Comment by philknows** [comment]
Follow logging policy. We're now logging a warning on the error
