### ISSUE TITLE
validator: indicator for loading keys

### ISSUE THREAD

**Issue by q9f** [ChainSafe/lodestar#4823]
Loading more than 100 keys or loading a validator on a low-resource machine lets the user believe the client is "stuck" as it does not indicate any status.

**Describe the solution you'd like**

```bash
10% .. Loaded 10/100 keys (0xbb3d65dd002050ac12d963226f41dd88)
20% .. Loaded 20/100 keys (0xb0f4f2afa59948b642fd831d8dae30c6)
30% .. Loaded 30/100 keys (0x6362f93a37edaa6337ca0eb670872bbc)
40% .. Loaded 40/100 keys (0x9dc4325370645bc9ff1440519db86db3)
50% .. Loaded 50/100 keys (0xe257ca039b831fb548cdc37bd6b35439)
```

**Describe alternatives you've considered**

Getting a drink

**Comment by dapplion** [comment]
> Getting a drink

Getting a drink :rofl: 

- Keeping this issue open and it only requests to display progress. For actually speeding this up, see https://github.com/ChainSafe/lodestar/issues/4179
