### ISSUE TITLE
Consider Including the light client namespace as part of default namespace for beacon node API

### ISSUE THREAD

**Issue by dadepo** [ChainSafe/lodestar#4824]
**Is your feature request related to a problem? Please describe.**

Currently the default beacon node's API namespace are `["beacon", "config", "events", "node", "validator"]`. By default a beacon node won't be able to serve light client related data via the rest api 

**Describe the solution you'd like**

Consider having light client namespace as part of the default namespace. 

Pros:
- Improves availability of light client related data. 

Cons?
- Serving light client related data might not be considered symbiotic.

**Comment by dapplion** [comment]
Now that proofs are not part of the namespace, that's ok to me security-wise
