### ISSUE TITLE
Sim tests: add assertion for missed blocks

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4833]
Add assertion to ensure that test does not pass if blocks are missed. That block for slot N was missed, must be checked at slot N+X, where X is sufficiently big for re-orgs. For example X could = SLOTS_PER_EPOCH.

**Comment by nazarhussain** [comment]
This is been covered with existing sim tests. 
https://github.com/ChainSafe/lodestar/blob/84903697c8fedc96d876aeb3a6631343482d4814/packages/cli/test/utils/simulation/assertions/defaults/missedBlocksAssertion.ts#L6-L7
