### ISSUE TITLE
Create validator pubkey->index mapping

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#486]
Implement validator pubkey->index mapping so it can be used accross application

**Comment by twoeths** [comment]
I'm working on this.

**Comment by mpetrunic** [comment]
unstale

**Comment by twoeths** [comment]
The pubkey->index map is implemented in fast state transition PR https://github.com/ChainSafe/lodestar/pull/931/files#diff-814e2b5dbb5cb9acb7b039ac6dd549d5R20

We should start from there.
