### ISSUE TITLE
Periodically update beacon APIs CHANGES.md

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4860]
beacon APIs tracks new PR support from all clients. For downstream consumers and ourselves, we should on each release align that table with latest version

https://github.com/ethereum/beacon-APIs/blob/master/CHANGES.md

**Comment by nflaig** [comment]
Resolved by https://github.com/ethereum/beacon-APIs/pull/432, will keep in mind to update the changelog at some point in the future again
