### ISSUE TITLE
Optimize state transition

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#488]
- use stuff from https://github.com/protolambda/eth2-impl-design

**Comment by GregTheGreek** [comment]
Array based implementation would benefit highly from Assembly Script

**Comment by ec2** [comment]
Oh, hey! I've been doing research on that last week. Starting to create issues w.r.t. this! 

@GregTheGreek array based implementation of what?

**Comment by mpetrunic** [comment]
@tueric yeah wasn't sure if you are gonna add optimization issues before sprint planning so started adding but figured out that I cannot describe them properly :smile:

**Comment by mpetrunic** [comment]
unstale
