### ISSUE TITLE
[vc] Investigate late attestations published on mainnet

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4881]
**Describe the bug**
- This is about the time we publish attestations compared to 1/3 of slot (so -2 means 1s after slot, +2 means 6s after slot
- On goerli it rarely happens

<img width="1291" alt="Screen Shot 2022-12-07 at 16 00 48" src="https://user-images.githubusercontent.com/10568965/206134702-0473c9ff-f98d-40cd-b245-53271d4e8e45.png">

- However some mainnet nodes (v1.2.x) experienced this issue more

<img width="1285" alt="Screen Shot 2022-12-07 at 16 00 27" src="https://user-images.githubusercontent.com/10568965/206134616-a0d5e9b3-a7fc-4de4-a356-c020d00341b6.png">

**Expected behavior**

Attestations should be published not later than 1/3 of slots

**Comment by twoeths** [comment]
This is because `produceAttestationData` being called after 4s (when vc hasn't received new chain head on time)

<img width="1290" alt="Screen Shot 2022-12-07 at 19 32 37" src="https://user-images.githubusercontent.com/10568965/206180250-9bcef3a4-2092-43b8-8c13-a2634b20389c.png">

and produceAttestationData request time sometimes take >1s or even 5s

<img width="1267" alt="Screen Shot 2022-12-07 at 19 34 21" src="https://user-images.githubusercontent.com/10568965/206180543-a709c19d-560e-4e6f-9add-c114e93b9cc8.png">

root cause is the I/O lag issue

**Comment by twoeths** [comment]
We could try http 1.1 keep-alive (or http 2, that's a longer plan) to reuse http connection

**Comment by philknows** [comment]
> This is because `produceAttestationData` being called after 4s (when vc hasn't received new chain head on time)
> 
> <img alt="Screen Shot 2022-12-07 at 19 32 37" width="1290" src="https://user-images.githubusercontent.com/10568965/206180250-9bcef3a4-2092-43b8-8c13-a2634b20389c.png">
> 
> and produceAttestationData request time sometimes take >1s or even 5s
> 
> <img alt="Screen Shot 2022-12-07 at 19 34 21" width="1267" src="https://user-images.githubusercontent.com/10568965/206180543-a709c19d-560e-4e6f-9add-c114e93b9cc8.png">
> 
> root cause is the I/O lag issue

Referencing #4002

**Comment by twoeths** [comment]
I've tried http 1.1 keep-alive, it does not help while v1.3.0 shows some improvement, see https://github.com/ChainSafe/lodestar/pull/4915#issuecomment-1363582744

**Comment by dapplion** [comment]
Closing issues for specific incidents on old versions of Lodestar, please re-open if it happens with latest stable
