### ISSUE TITLE
No public IP on Multiaddrs

### ISSUE THREAD

**Issue by tmm360** [ChainSafe/lodestar#4885]
**Describe the bug**

I'm running lodestar 1.2.2 on docker compose with gnosis chain.

I've noticed that my node is not able to find any peer, and I decided to investigate.
On logs I see at beginning this Multiaddrs log (omitted Id):
```
Dec-07 16:07:25.957[network]          info: PeerId <myId>, Multiaddrs /ip4/127.0.0.1/tcp/9050/p2p/<myId>,/ip4/172.30.0.6/tcp/9050/p2p/<myId>
```
I see that I've only loopback ip and local docker network ip. A public ip is missing.

Node can reach external network (ping outside works), and port is open.

**Expected behavior**

I should have a public ip on Multiaddrs variable.

**Steps to Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

**Comment by dapplion** [comment]
Hey @tmm360  :wave: Lodestar will learn its own IP after interacting with discv5 peers, and update it's multiaddr. If you want the node to immediately learn its own IP use the flag `--enr.ip <your_ip>`
