### ISSUE TITLE
Add further prometheus counters

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/lodestar#489]
The majority of the prometheus counters are setup, but they aren't being incremented/decremented anywhere (except for slot).

This is a fairly straight forward task, great for exploring the codebase.

**Comment by mpetrunic** [comment]
@GregTheGreek could you link specified counters and/or make a checklist of missing

**Comment by lastmjs** [comment]
Is any work being done on this issue?

**Comment by wemeetagain** [comment]
I don't think anything has been done recently. I think we have only some of the metrics defined here https://github.com/ethereum/eth2.0-metrics
