### ISSUE TITLE
Unstable heap memory issue

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4896]
**Describe the bug**

Memory has been unstable since Dec 06, we need to investigate which PRs caused it

<img width="795" alt="Screen Shot 2022-12-09 at 21 47 04" src="https://user-images.githubusercontent.com/10568965/206727880-3b008aec-1b09-4981-bf2b-da95e1da372c.png">

**Expected behavior**

Memory should be stable like in v1.2.2

**Comment by twoeths** [comment]
Have deployed some branches in feat1/beta, it shows that this has happened since we merges https://github.com/ChainSafe/lodestar/pull/4849

it's also confirmed by `regen` metrics

<img width="816" alt="Screen Shot 2022-12-12 at 08 46 11" src="https://user-images.githubusercontent.com/10568965/206943778-73c77cf6-f23e-4ff8-b64a-5b3f675d8a90.png">

<img width="1613" alt="Screen Shot 2022-12-12 at 08 47 06" src="https://user-images.githubusercontent.com/10568965/206943859-1912ac26-bc62-4025-9900-d87fee533b88.png">

**Comment by twoeths** [comment]
in my opinion, for the release of v1.3.0 we should just revert that PR and comment the edge cases that we may need it. In the long term, it will be resolved if we implement the committee cache which is lightweight compared to the current regen strategy. What do you think @dapplion @wemeetagain ?

**Comment by dapplion** [comment]
@tuyennhv  Ok to me to revert, open an issue and fix properly latter. I would rather wait for a more "proper" solution of regen usage.
