### ISSUE TITLE
Use target checkpoint state to verify attestations

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4900]
**Describe the bug**

Right now we use the attested block root's state to verify attestations, we should use the the target checkpoint state to verify attestations instead.

**Expected behavior**

Already implemented in https://github.com/ChainSafe/lodestar/pull/4849 but due to the memory issue we mark it as a TODO until a 'proper' regen/cache strategy is implemented

**Comment by wemeetagain** [comment]
I think this is a duplicate of https://github.com/ChainSafe/lodestar/issues/4831

**Comment by twoeths** [comment]
duplicated to #4831
