### ISSUE TITLE
Buffer.concat performance regression

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4903]
**Describe the bug**

On NodeJS v18 (merged in https://github.com/ChainSafe/lodestar/pull/4779) Buffer.concat got more expensive.
- Reported by our performance tracker https://github.com/ChainSafe/lodestar/commit/7d662d7951db27edcee15fd7266bed322f0a3882#commitcomment-92810061
- Upstream issue https://github.com/nodejs/node/issues/45802

We decided to accept the regression for now to unblock v18. But must review and consider and mitigate when possible

**Comment by philknows** [comment]
This requires investigation. It may have been fixed by node v20.x.

**Comment by wemeetagain** [comment]
resolved with node 20
