### ISSUE TITLE
Add metrics

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/lodestar#495]
Metrics per the [specification](https://github.com/ethereum/eth2.0-metrics/blob/master/metrics.md).

Interop Metrics:
- [x] libp2p_peers
- [ ] beacon_slot
- [x] beacon_head_slot 
- [ ] beacon_head_root
- [x] beacon_finalized_epoch
- [ ] beacon_finalized_root
- [x] beacon_current_justified_epoch
- [ ] beacon_current_justified_root
- [x] beacon_previous_justified_epoch
- [ ] beacon_previous_justified_root

Additional Metrics:
- [ ] beacon_current_validators
- [ ] beacon_previous_validators
- [x] beacon_current_live_validators
- [ ] beacon_previous_live_validators
- [ ] beacon_pending_deposits
- [ ] beacon_processed_deposits_total
- [ ] beacon_pending_exits
- [ ] beacon_previous_epoch_orphaned_blocks
- [ ] beacon_reorgs_total

**Comment by aunyks** [comment]
How closely is this related to #489, if at all?

**Comment by dapplion** [comment]
All relevant metrics should be implemented now
