### ISSUE TITLE
Update github workflows to avoid `::set-output`

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#4967]
We need to update our github workflows to not use `::set-output`. We have by May 31 2023 to do so.

See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by philknows** [comment]
Will tag this one to a release milestone due to the timeline requirement.

**Comment by twoeths** [comment]
Still get 21 warnings in https://github.com/ChainSafe/lodestar/actions/runs/4040952032
<img width="1220" alt="Screen Shot 2023-01-30 at 13 39 13" src="https://user-images.githubusercontent.com/10568965/215405670-71db5a8f-e5d8-4e26-8459-39e87a2166eb.png">

<img width="1237" alt="Screen Shot 2023-01-30 at 13 39 39" src="https://user-images.githubusercontent.com/10568965/215405726-3c0aad57-2c05-4a85-8a63-fac4d916acf2.png">
