### ISSUE TITLE
When could `@chainsafe/blst` support mac M1, I can not build in M1

### ISSUE THREAD

**Issue by bijianing97** [ChainSafe/lodestar#4971]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AmanRaj1608** [comment]
Installing python locally should solve the issue. Was facing similar issue

linking - https://github.com/ChainSafe/blst-ts/issues/75#issuecomment-1316648765

**Comment by philknows** [comment]
Thanks @AmanRaj1608 , please re-open if you continue to have issues @bijianing97 .
