### ISSUE TITLE
Improve validator UX by deprecating/renaming validator --importKeystores* flags

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#4986]
**Is your feature request related to a problem? Please describe.**

There was a discovery made when wanting to import multiple keystores under different passwords that our validator `--importKeystores*` CLI doesn't actually import keystores and their password using the `--importKeystores` and `--importKeystoresPassword` flags. They act more like "override" or "use only" functionality. It will ignore what was already imported via `validator import`. 

Example: 
If you run `validator import --importKeystores a`, then `validator --importKeystores b`, only keystore b will be used.

**Describe the solution you'd like**

The nomenclature of `--importKeystores*` flags are not accurate and should be renamed. Options include using the word `override` or `use` instead of `import`. 

**Additional context**

For now, documentation has been updated via #4985 for clarity, but this issue should be considered when making a big breaking change to Lodestar.

**Comment by dapplion** [comment]
There's no need to do a breaking change here. Just change the main name of the option so that it shows up in help and docs, while keeping the existing option as an alias.

That's what we do now for this options

https://github.com/ChainSafe/lodestar/blob/5b9a78e63650351f7ae2295facefa2b38be48b29/packages/cli/src/cmds/validator/options.ts#L207-L208

**Comment by philknows** [comment]
Good point. Would definitely advocate for something along the lines of `--overrideKeystores` and `--overrideKeystoresPassword` and temporarily leave the current as an alias for backward compatibility.

**Comment by dapplion** [comment]
- https://github.com/ChainSafe/lodestar/pull/4985 merged
