### ISSUE TITLE
Edelweiss Shapella Tracker

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#5016]
This issue is to track issues and PRs to prepare for and successfully complete the next Ethereum interop.

### Build and run lodestar from source

- Node.js v18 recommended and `yarn` need to be installed, see e.g. [npm docs](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm)
- Clone the lodestar monorepo with `git clone https://github.com/chainsafe/lodestar.git`
- Run `yarn && yarn build` from the root folder to install dependencies and build
- Now the client can be run from from `./lodestar`
- Run `./lodestar --help` for help on the CLI parameters

**Comment by wemeetagain** [comment]
Interop is over
