### ISSUE TITLE
Detect unknown clients

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5022]
**Describe the bug**

This is from a goerli v1.3.0 node and I think it also happens in unstable:

```
Jan-18 00:32:54.803[network]         ^[[34mdebug^[[39m: Req  request sent method=status, encoding=ssz_snappy, client=undefined, peer=16...BBbrtn, requestId=23586
```

The client is logged as undefined a lot of times

```
grep -e "client=undefined" -rn beacon-2023-01-18.log | wc -l
49774
```

maybe a client changed its identity?

**Expected behavior**

- Investigate which client that we can't detect
- If there are a lot of them, log as Unknown

**Comment by wemeetagain** [comment]
should be resolved with https://github.com/ChainSafe/lodestar/pull/5069
