### ISSUE TITLE
Fallback to publishing block when it fails to publish blinded block

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5028]
**Is your feature request related to a problem? Please describe.**

We may fail to publish blinded block and validator misses a block proposal

```
Bad Gateway: Bad Gateway: no successful relay response - Failed to publish block
Error: Bad Gateway: Bad Gateway: no successful relay response - Failed to publish block
    at HttpClient.requestWithBody (file:///usr/app/packages/api/src/utils/client/httpClient.ts:258:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HttpClient.request (file:///usr/app/packages/api/src/utils/client/httpClient.ts:132:12)
    at Object.request [as publishBlindedBlock] (file:///usr/app/packages/api/src/utils/client/client.ts:82:9)
    at BlockProposingService.createAndPublishBlock (file:///usr/app/packages/validator/src/services/block.ts:95:7)
    at async Promise.all (index 0)
```

**Describe the solution you'd like**

Since we have signed block at that time, we should be able to publish it (call `/eth/v1/beacon/block`) to avoid a missed block proposal

**Comment by philknows** [comment]
@tuyennhv We did an investigation with Bloxroute and determined the issue to be relay related. I've previously tested the builder API before and we do fallback to local execution to propose a block currently. But the problem is when we sign a blinded block header and do not receive the payload from the relay. Unfortunately there's not much we can do there because we cannot sign two different blocks.

**Comment by g11tech** [comment]
here we have signed BLINDED block, which we try to publish:
1. to publish it we submit it to the relay which publishes as well as returns full payload
2. which we also use to construct full block on our side and publish on our own (this is an optional step)

However if the api fails at 1. nothing else can be done and the block proposal opprtunity is effectively lost as we run the risk of double signing (relay api could fail even after accepting the block and there is no way to confirm if relay actually didn't accept and publish the block)
