### ISSUE TITLE
Endpoint for VC to show status/connection to currently connected beacon node

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#5061]
**Is your feature request related to a problem? Please describe.**

Currently, if you run a setup with multiple beacon nodes, there isn't an easy way for monitoring tools like Grafana to know exactly which beacon node the validator client is connected to. This would be useful for more sophisticated setups where it isn't a local environment with a 1:1 beacon node <> validator setup, or using remote beacon nodes. This is especially useful if we setup multiple fallback nodes in the `beaconNodes` array.

**Describe the solution you'd like**

A validator endpoint which tells us which beacon node it is currently connected to. Whether that is IP address or if we had a configurable parameter to name beacon-nodes that it would pull the name and/or IP address of what it's connected to so Grafana and other monitoring tools can see the current connection status.

**Comment by nflaig** [comment]
Is this still a requirement? I feel like this should be easy to implement by adding a metric

**Comment by nflaig** [comment]
From Lodestar incentive program user feedback
> Validators use a fallback node, but not sure if they were needed during this period.

I also feel like metrics should be able to answer such questions, maybe also highlight in logs if a fallback is used

**Comment by dapplion** [comment]
There are metrics for it, please check if this provide enough info

https://github.com/ChainSafe/lodestar/blob/724c79a181e4ad53c8faa609147e681ec3ee04e7/packages/validator/src/metrics.ts#L364-L368

**Comment by nflaig** [comment]
> There are metrics for it, please check if this provide enough info

Yes, those will work to answer the question if there were any requests to fallbacks. The [URL score metric](https://github.com/ChainSafe/lodestar/blob/c50db8f7ae47198c76070487a6cfd0009d9bfd39/packages/validator/src/metrics.ts#L371) could be used to figure out which is the currently connected bn  but a simpler solution would be to add a new metric which uses a label to track the URL of the currently connected bn.

**Comment by philknows** [comment]
Right now, for larger setups like ours, I just look at the `rcconfig.yml` to correlate their primary + secondary beacon node. It narrows it down to 2 options really but some calls will go through primary `beaconNodes` and some to secondary and it's not instantly known which of the two paths a call took. Will be even worse if someone had >1 fallbacks.

**Comment by nflaig** [comment]
>  it's not instantly known which of the two paths a call took

If we want that information on a per request basis, I think would be best to include the URL in the logs (per request). Or could also add another label with the URL to `vc_rest_api_client_request_to_fallbacks_total`.
