### ISSUE TITLE
Remove dashboards, prometheus, grafana to a lodestar-metrics repo

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#5066]
We should reduce the PRs and noise in the main repo

cc @dapplion

**Comment by nflaig** [comment]
-1 for moving dashboards, we would lose the ability to atomically rename metrics in a single commit and update the dashboard when adding new metrics in a single MR. 

If we remove dashboards this would also warrant to move the docs to a separate repository which is also not a decoupling I would be in favor of.

To reduce noise for something like release notes could think of a concept similar to [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) to better categorize commits, things like refactoring code, docs, dashboard updates, CI/CD updates, etc. should not show up in the release notes.

**Comment by philknows** [comment]
We had previously discussed moving toward conventional commits around EthDenver in 2022... not sure if this was still a consideration. That would at least organize it better for us in the main repo. Would keep this discussion open for further thoughts, but continued maintenance and ease of workflow for something as critical as metrics should be taken into consideration.

**Comment by dapplion** [comment]
Our dashboards are very specific to us. There are now an unknown number of dashboards that use our metrics. So alreadt we should not change the name of metrics to prevent downstream breaking changes anyway.

**Comment by nflaig** [comment]
Renaming metrics is definitely not ideal and should be avoided.

If we move the dashboards need to also keep in mind tho that there are projects might get the dashboard from this repo, e.g. [eth-docker fetches it from stable branch](https://github.com/eth-educators/eth-docker/blob/1fda509a973b14f5dc7fb1bc78f5c0b7248249aa/grafana/provision-dashboards.sh#L64). There are further unknown amount of references we would probably break but might not be a big deal and would be fixed sooner or later.

Could maybe consider to publish an image (`chainsafe/lodestar-dashboards`) which includes all dashboards and other projects can get them from there. This would also be a possible solution to our local metrics setup as mentioned in [this comment](https://github.com/ChainSafe/lodestar/pull/5123#issuecomment-1426768630).

**Comment by philknows** [comment]
Are there still any strong opinions to support this idea? If not, we should close it.

**Comment by philknows** [comment]
We aren't planning on removing the dashboards.
