### ISSUE TITLE
Discv5 Observable performance issue

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5084]
**Describe the bug**

- Since we introduce Discv5 in worker thread, it takes almost 10% of cpu time on a mainnet node subscribing to all subnets

<img width="1307" alt="Screen Shot 2023-01-31 at 13 12 45" src="https://user-images.githubusercontent.com/10568965/215680881-6d5e3b6e-84aa-4ea3-9689-094c299ae993.png">

[mainnet_node_v1.4.0.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/10543375/mainnet_node_v1.4.0.cpuprofile.zip)

cc @wemeetagain 

**Expected behavior**

- Discv5 should take less cpu to emit a discovered peer to main thread

**Screenshots**

~~This is from a contabo vpss node (v1.3.0 vs v1.4.0)~~ __Update__: ignore the below metric, it's the common situation of all of lodestar nodes on goerli, v1.4.0 has only been deployed since Jan 30

<img width="1265" alt="Screen Shot 2023-01-31 at 13 11 26" src="https://user-images.githubusercontent.com/10568965/215680655-1e8df7c0-ca1a-4eb3-a640-c4713d291ab5.png">

- Version: v1.4.0

**Comment by wemeetagain** [comment]
can you try with https://github.com/ChainSafe/lodestar/pull/5073 applied?

**Comment by twoeths** [comment]
> can you try with #5073 applied?

I will deploy that PR to a node, I will also try using the native thread communication `postMessage` instead of Observable to see if it's better

**Comment by twoeths** [comment]
Further investigation shows that this only happens when we have a lot of discovered ENRs from discv5, somehow this only happens on test mainnet nodes subscribing to all subnets, not on goerli nodes or prod mainnet nodes

we may not need it for v1.4.1

**Comment by twoeths** [comment]
Wasn't able to take same profile, also #5073 should improve it and it was shipped with v1.4.1
