### ISSUE TITLE
Light Client Call #1

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/lodestar#510]
**DATE**: Nov. 6, 14:00 UTC
**DURATION**: 1.5 hours
**LOCATION**: Zoom

### Purpose
Discuss upcoming light client research
Coordinate to bring ethereum light client tech to production

### Audience
Researchers, client developers, wallet developers

### Agenda
1. Introductions (10min)
2. Q/A with Zsolt Felfoldi - Light Client Server Incentivization (40min)
3. Next Steps / Tactics / Open Discussion (40min)

Light client technology holds the promise to vastly improve blockchain UX and provide a foundational level of security --- if only we actually put it to use!
This kickoff meeting will be an exploration in the light client space and the purpose of the working group.
We will discuss the current light client landscape in eth1 and eth2, identify open research issues, and collaboratively determine how to best approach this difficult coordination problem.
We'll hear from Zsolt Felfoldi on his light client server incentivization framework, presented at Devcon, and get a chance to deep dive with questions from the community.

**Comment by johnsBeharry** [comment]
Countdown in your timezone if anyone else wants.
- https://time.is/1400_6_Nov_2019_in_UTC?Light_Client_Call_#1

**Comment by johnsBeharry** [comment]
Zoom link?

**Comment by johnsBeharry** [comment]
Zoom link
- https://zoom.us/j/595267809
