### ISSUE TITLE
Add CLI option to change validator behavior in distributed cluster (DVT)

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#5103]
**Is your feature request related to a problem? Please describe.**

There are compatibility issues running Lodestar VC in a distributed validator cluster due to an [optimization](https://github.com/ChainSafe/lodestar/issues/4687#issuecomment-1291021144).

The problem is that if there are multiple validators in a cluster and there are `N` attester duties in the same slot, then Lodestar queries the attestation data only **once** with the `committee_index` of the first duty and uses  that attestation data for all the validators by overriding the correct `committee_index` internally from the attester duty object for that validator. Other clients query `N` times to get the attestation data for each attester duty.

Distributed validator middleware clients such as [Charon](https://github.com/ObolNetwork/charon) calls [`/eth/v1/validator/attestation_data`](https://ethereum.github.io/beacon-APIs/#/Validator/produceAttestationData) endpoint for each validator public key and there is a slight chance that the `beacon_block_root` (LMD GHOST vote) changes between calls which would cause a conflict between attestations submitted by Lodestar and other VCs in the cluster, resulting in aggregation failure as explained in [this comment](https://github.com/ChainSafe/lodestar/issues/4687#issuecomment-1403716069) and further outlined [here](https://github.com/ObolNetwork/charon-distributed-validator-cluster/issues/23#issuecomment-1308428065).

**Describe the solution you'd like**

The distributed validator middleware requires the actual `committee_index` retrieved from [`/eth/v1/validator/duties/attester/{epoch}`](https://ethereum.github.io/beacon-APIs/#/Validator/getAttesterDuties) to be sent to [`/eth/v1/validator/attestation_data`](https://ethereum.github.io/beacon-APIs/#/Validator/produceAttestationData) which means we need to disable the optimization. Since we only need to do this if the VC is part of a distributed cluster we could introduce a `--distributed` CLI option to achieve this.
This flag will also be useful when Lodestar implements the new DVT specific endpoints introduced in https://github.com/ethereum/beacon-APIs/pull/224.

**Describe alternatives you've considered**

Could completely remove the optimization which we probably don't want to do as it makes sense to do if you directly communicate with the beacon node as `committee_index` is just passed around. 

cc @dB2510

**Comment by wemeetagain** [comment]
Sounds good. We'll also need to implement behavior described here: https://docs.google.com/document/d/1q9jOTPcYQa-3L8luRvQJ-M0eegtba4Nmon3dpO79TMk/mobilebasic
