### ISSUE TITLE
Keystore and password security considerations

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#5113]
This issue can be used to discuss potential solutions to improving the security of how we currently manage keystore and password files.

At the moment, the Lodestar VC creates two folders the `keystores` folder which contains encrypted [BLS12-381 private keys](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2335.md) and the `secrets` folder which contains the plain text passwords to decrypt the keystores. This setup does not provide any additional security for the private keys in the keystores as the encryption keys are stored on the same device and even the same folder in most cases.  The described setup relies on the file system access to be secure which is sufficient security for most setups but we are not getting any benefits from additionally storing user provided passwords in plain text to just storing the keystore files in an unecrypted format. The main concern here is that leaking the user password can have further consequences as a lot of users reuse passwords which might give an attacker further access to the operating system itself or other services.

In an ideal world, we **never** want to store the plain text user password, only the first time the user imports a encrypted keystore, the password should be interactively provided through the CLI or keymanager API. While this should be easily possible we still want to be able to restart the VC in case of a reboot without human interaction.

Possible solutions to this problem

1. store password files on a different device then encrypted keystores and only mount drive if required, we would still store the password but at least get benefits from encrypted the keystores as an attacker would need access to multiple devices
2. use a remote signer/key manager, this solution already exists and seems to be a good option to improve security

Both those options are not really something we can influence on Lodestar directly as **1.** requires an advanced server setup and might not be suitable for most users and option **2.** requires to use another software component such as [web3signer](https://github.com/ConsenSys/web3signer).

Looking forward to further ideas and suggestions on potential solutions we could directly implement in Lodestar itself.

**Comment by nazarhussain** [comment]
It's not related to Etherem or Cryoto, it's a general philosophical pointer. Once must keep balance between security and usability. One should not make a system so secure that it's no more useable. Same applies to context here. 

We want to secure the validator keys but on the same time we knew the softwares can crash and need to restart. And validators would not be bothered to provide password for 100s keys each time that happens. 

Other common approach people mostly used for such scenarios is to use ENV variables instead of files. Based on my experience, that approach is less secure. If an system access is compromised that an attacker accessed to file system, he must already have access to shell and so all env variables. Additionally permissions to the file system can be restricted, but every program running on system have access to system wide env variables.

**Comment by nflaig** [comment]
> It's not related to Etherem or Cryoto, it's a general philosophical pointer. Once must keep balance between security and usability. One should not make a system so secure that it's no more useable. Same applies to context here.

that's definitely true, however my main concern is that we store a user provided password in plain text, if this was a machine generated password it would be a different story

> Other common approach people mostly used for such scenarios is to use ENV variables instead of files. Based on my experience, that approach is less secure. 

can't agree more here, using ENV variables is strictly worse in terms of security whether it is in a containerized environment like kubernetes in the cloud or on a bare metal server

**Comment by wemeetagain** [comment]
> store password files on a different device then encrypted keystores and only mount drive if required, we would still store the password but at least get benefits from encrypted the keystores as an attacker would need access to multiple devices

This can be done with our current implementation (and is the intention behind storing the secrets separately from the keystores), though this usage pattern isn't spelled out anywhere in the user docs.
In practice, we don't do this (for our fleet) because the setup is onerous.

**Comment by dapplion** [comment]
We must support storing plain text secrets since that's expected by many types of users. If storing plain text secrets is not acceptable to an operator of Lodestar, use stdin to provide the passwords or the web3signer

**Comment by nflaig** [comment]
To summarize

- Security-conscious operators have the option to mount the secrets to an external drive which is kept offline and only mounted if required, e.g. on server reboot or restart of VC.
- It is also possible to use  an external signer such as  [web3signer](https://github.com/ConsenSys/web3signer) which supports more advanced storage options such as using [vault](https://github.com/hashicorp/vault).
- Use stdin to provide the passwords instead of providing from password file.
