### ISSUE TITLE
Add CI step to check no warning of unmet dependency

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#5115]
**Describe the bug**

Discord user reported a yarn warning for unmet dependencies. This is harmless to the user but as part of our "log hygiene" effort we must ensure the warnings are not emitted in the happy case.

![](https://cdn.discordapp.com/attachments/743858262864167062/1072789411625963520/image.png)

We should add a new step in CI that ensures that those warnings are not emitted, by either
- Run some yarn command to check unmet dependencies

or (not prefered)
- Capture yarn install output
- Check for unmet dependencies

**Comment by nflaig** [comment]
Reopening as this is an issue again, see https://github.com/ChainSafe/lodestar/pull/6074#discussion_r1420323067
