### ISSUE TITLE
light client get_bootstrap endpoint is failing

### ISSUE THREAD

**Issue by tbraun96** [ChainSafe/lodestar#5129]
This error is getting thrown when calling the `get_bootstrap` function: https://github.com/ChainSafe/lodestar/blob/db612ea82f618c4ab6509ebd88f96631788c93d2/packages/beacon-node/src/chain/lightClient/index.ts#L264

We are passing the blockroot obtained from the route `/eth/v1/beacon/states/finalized/finality_checkpoints` at the json index `["data"]["finalized"]["root"]`.

Note: this issue did not exist for version 1.3, it only started happening since 1.4.x.

The diff in lodestar between version 1.3 and the latest 1.4.x can be found here: https://github.com/ChainSafe/lodestar/compare/031e42cbe8015109e2af6e9cdec1b15dd66fc937...440c59f080165749666639aab32abb72ae570cf8

See comments in photo for continuation of discussion: 
<img width="746" alt="Screenshot 2023-02-10 at 11 48 17 AM" src="https://user-images.githubusercontent.com/38082993/218148603-81b0e86d-43a7-4cb8-9fd6-9147d468f40f.png">

This leads us to believe there is a bug in the one of the aforementioned endpoints.

**Comment by tbraun96** [comment]
To replicate the issue:

```bash
curl https://lodestar-goerli.chainsafe.io/eth/v1/beacon/light_client/bootstrap/`curl https://lodestar-goerli.chainsafe.io/eth/v1/beacon/states/finalized/finality_checkpoints | jq ".data.finalized.root" | tr -d '"'`
```

Note: this same command works but when testing against mainnet:

```bash
curl https://lodestar-mainnet.chainsafe.io/eth/v1/beacon/light_client/bootstrap/`curl https://lodestar-mainnet.chainsafe.io/eth/v1/beacon/states/finalized/finality_checkpoints | jq ".data.finalized.root" | tr -d '"'`
```

Therefore, this issue only occurs on goerli testnet, not the mainnet.

**Comment by g11tech** [comment]
Just tested on the zhejiang which runs our latest lightclient code this doesn't seem to be happening

![image](https://user-images.githubusercontent.com/76567250/218324383-28af1a44-4649-4416-a4bf-02485a03187e.png)

**Comment by g11tech** [comment]
currently seems to be working off goerli public node as well, may be goerli was restarted with a finalized checkpoint at that time leading to no sync committee witness in the db for that checkpoint.

@tbraun96 let know if you are facing this issue currently else recommend to close this issue

**Comment by tbraun96** [comment]
This command still fails:

```bash
curl https://lodestar-goerli.chainsafe.io/eth/v1/beacon/light_client/bootstrap/`curl https://lodestar-goerli.chainsafe.io/eth/v1/beacon/states/finalized/finality_checkpoints | jq ".data.finalized.root" | tr -d '"'`
```

**Comment by wemeetagain** [comment]
seems it happens intermittently

**Comment by g11tech** [comment]
weird, it doesn't look light light client error, but finality checkpoint fetch itself is failing:

![image](https://user-images.githubusercontent.com/76567250/218813015-313eec3e-0102-4ab3-b8f7-df4c12c95c8f.png)

@Faithtosin is our goerli public node synced?

**Comment by g11tech** [comment]
yes as soon as finality checkpoint started returning data, this bootstrap api succeeded. @wemeetagain  we will need to inspect log and see at what instanes finalized state becomes unavailable for a running/synced node (as from the log above)
cc @Faithtosin
