### ISSUE TITLE
Reorg depth counter is incorrect

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#5136]
**Describe the bug**

Recent reorgs are not properly being shown in our metrics. @wemeetagain investigated why our metrics cannot properly show and calculate reorgs and their depths. Reorg depth is currently calculated as `newHead.slot - commonAncestor.slot` 

**Expected behavior**

The reorg depth counter should be able to determine reorgs and at what depth. We need to tweak the calculation with something else. @wemeetagain suggests maybe `Math.max(newHead.slot, oldHead.slot) - commonAncestor.slot` 

Open for discussion/solutions.

**Comment by maschad** [comment]
In the case of a reorg wouldn't the `newHead.slot`  always be greater than the `oldHead.slot` ? I understand the reorg depth as the difference between the _new chain_ and the _old chain_  so therefore:

``` javascript
(newHead.slot - commonAncestor.slot) - (oldHead.slot - commonAncestor.slot)
```

**Comment by wemeetagain** [comment]
Not necessarily.

We had a recent case like so:
- block xxx01 is processed and becomes head
- block xxx03 thru xxx24 is processed and becomes head
- block xxx02 is processed and becomes head

In this case our reorg depth counter registered a reorg of depth 1, even though the reorg went from 24 back to 2

**Comment by wemeetagain** [comment]
Other strange case, in deep reorgs, the shufflings are different, and there can be multiple blocks at the same slot.

**Comment by maschad** [comment]
Using [Prysm's calculation](https://github.com/prysmaticlabs/prysm/blob/c7f0a94b19fe9ebf5a3da6a73162fb683b22c5f8/beacon-chain/blockchain/head.go#L133) it seems like the find the [max](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/max) of the two differences between the new slot, the old slot and the common ancestor slot.

so essentially

```javascript
Math.max((newHead.slot - commonAncestor.slot), (oldHead.slot - commonAncestor.slot))
```
