### ISSUE TITLE
yarn building error snappy

### ISSUE THREAD

**Issue by 3cl1ps** [ChainSafe/lodestar#5148]
Building error, could be snappy, or an other package like bls.
logs https://pastebin.com/0wQJ3J7g

i have this error from the latest zip download or from a git pull stable/unstable

steps to reproduce :
git pull
yarn install --ignore-optional

removing yarn.lock makes yarn install --ignore-optional go without errors but yarn run build will fail :
@lodestar/params: error TS2688: Cannot find type definition file for 'bl'.
@lodestar/params:   The file is in the program because:
@lodestar/params:     Entry point for implicit type library 'bl'

➜  ~ lsb_release -a
Description:    Ubuntu 22.10
➜  ~ npm --version
9.4.0
➜  ~ gcc --version
gcc (Ubuntu 12.2.0-3ubuntu1) 12.2.0

**Comment by dapplion** [comment]
Thanks for appending full stdout, looking at the logs it seems a snappy build error. What's your NodeJS version?

From pastebin above

```
/home/thomas/.cache/node-gyp/19.6.0/include/node/v8-template.h:819:22: note:   no known conversion for argument 7 from ‘Nan::imp::Sig’ {aka ‘int’} to ‘v8::SideEffectType’
  819 |       SideEffectType getter_side_effect_type = SideEffectType::kHasSideEffect,
      |       ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [binding.target.mk:120: Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/data4/lodestar/node_modules/snappy/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/data4/lodestar/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:512:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Linux 5.19.0-31-generic
gyp ERR! command "/usr/local/bin/node" "/data4/lodestar/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /data4/lodestar/node_modules/snappy
```

**Comment by 3cl1ps** [comment]
➜  nodejs --version                                                                                                                                                                                       
v18.7.0
updating to last with : 
➜ sudo n stable
  installing : node-v18.14.2

build OK, you can close ty
