### ISSUE TITLE
Refresh peer hello responses

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#516]
- in sync module, set timer to fetch hello response from each valid peer
   - should do it "in the middle" of every slot

**Comment by mpetrunic** [comment]
unstale

**Comment by aunyks** [comment]
What do you mean by "in the middle"?

**Comment by mpetrunic** [comment]
I actually think we can close this as I noticed while implementing syncing that sour hello/status messages are getting refresh by libp2p internally
