### ISSUE TITLE
Build workflow issues. 

### ISSUE THREAD

**Issue by 0xTylerHolmes** [ChainSafe/lodestar#5163]
**Describe the bug**

On a clean build we get the following error: 

```
In file included from ../../nan/nan.h:180,
                 from ../src/binding.cc:3:
../../nan/nan_callbacks.h:55:23: error: 'AccessorSignature' is not a member of 'v8'
   55 | typedef v8::Local<v8::AccessorSignature> Sig;
      |                       ^~~~~~~~~~~~~~~~~
../../nan/nan_callbacks.h:55:40: error: template argument 1 is invalid
   55 | typedef v8::Local<v8::AccessorSignature> Sig;
      |                      
```

**Steps to Reproduce**

See [docker image](https://gist.github.com/0xTylerHolmes/a838be94c22a98a004a5e46b66836e8f)

On a clean install, clone the package and run a yarn install && yarn build in the root dir.

**Screenshots**

**Desktop (please complete the following information):**

See dockerfile.

**Workarounds**

I have been able on a clean system to use the following [suggestion](https://github.com/electron/electron/issues/35193#issuecomment-1345339714) to get things to build and work as expected.

**Comment by wemeetagain** [comment]
This will install nodejs v12. We don't support it. We recommend node v18.

**Comment by 0xTylerHolmes** [comment]
What is the recommended way to get around this? I am curious how the dockerfile I supplied is not conforming to the expected way to manage this.

**Comment by dapplion** [comment]
> What is the recommended way to get around this? I am curious how the dockerfile I supplied is not conforming to the expected way to manage this.

The nodejs version in ubuntu's repository is 4 years old, see https://github.com/nodejs/release#release-schedule . Installing node that way is not recommended, so you should either use https://github.com/nvm-sh/nvm or the official docker images for NodeJS which have more recent versions available

**Comment by dapplion** [comment]
Closing issues for specific incidents on old versions of Lodestar, please re-open if it happens with latest stable
