### ISSUE TITLE
Gossip beacon_attestation queue always full if subscribe-all-subnets

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#5176]
**Describe the bug**

Running Lodestar beacon node on a very powerful host (https://www.hetzner.com/dedicated-rootserver/ax41-nvme) results in Lodestar dropping a constant % of received attestations. Other system metrics point to the system not being at capacity.

This indicates the gossip queue strategy is not optimal and rejects messages that _could_ be processed. 

_rate of dropped messages on the beacon_attestation topic_

![Screenshot from 2023-02-20 16-41-01](https://user-images.githubusercontent.com/35266934/220057562-09d385b4-a1e1-4c06-8846-b5f6374b207d.png)

_beacon_attestation topic message queue length (always at almost max)_

![Screenshot from 2023-02-20 16-41-14](https://user-images.githubusercontent.com/35266934/220057695-fcb134fa-ff7f-41cd-a6be-275c6ed4f468.png)

The limiting factors are:
- Main thread at capacity
- BLS workers at capacity

_Most BLS worker threads are iddle_

![Screenshot from 2023-02-20 16-33-19](https://user-images.githubusercontent.com/35266934/220058046-f252d80a-8390-4a71-804b-d51140f6d1b5.png)

_The BLS worker manager queue in the main thread is never full_

![Screenshot from 2023-02-20 16-34-49](https://user-images.githubusercontent.com/35266934/220058145-d2709995-d8e2-4d8a-a411-b5537aec25f8.png)

Having the gossip queues have the downside of keeping objects for too long and processing many of them pretty late
![Screenshot from 2023-02-20 16-39-54](https://user-images.githubusercontent.com/35266934/220058425-85e084d7-d2f6-497a-b033-d2af42d60397.png)
![Screenshot from 2023-02-20 16-40-06](https://user-images.githubusercontent.com/35266934/220058441-514aa663-4fa1-46c7-bb7d-75af234cdc1d.png)

The host CPU stats do not show high usage, hinting at idle capacity available to process those attestations

![Screenshot from 2023-02-20 16-43-10](https://user-images.githubusercontent.com/35266934/220058593-e190905d-5c5e-4e4b-a983-fb714dc8b82b.png)

**Expected behavior**

Given enough resources Lodestar should be able to process all attestations

**Comment by twoeths** [comment]
Implemented in above PRs
