### ISSUE TITLE
Lodestar flags nimbus as irrelevant peer on hive runs

### ISSUE THREAD

**Issue by marioevz** [ChainSafe/lodestar#5186]
**Describe the bug**
Lodestar is unable to connect to nimbus on hive runs because it flags it as an irrelevant peer from the very beginning:
Nimbus:

```
Feb-20 17:47:18.322[network]         [34mdebug[39m: Irrelevant peer peer=16...ZKt1is, reason=GENESIS_NONZERO: 0x8f28acc048ba55423989aed22e1cbe56a16218c9decbcd6031d055c315b0dae7
```

Which seems to be this check over here:
https://github.com/ChainSafe/lodestar/blob/e5dabac124933bcadc650d19d6b128dcbfcb6c43/packages/beacon-node/src/network/peers/utils/assertPeerRelevance.ts#L48-L54

**Expected behavior**

Nimbus and lodestar should connect.

**Steps to Reproduce**

Run any hive simulator using lodestar+nimbus. I'm currently testing builder API using this PR branch: https://github.com/ethereum/hive/pull/715
And running:
```
./hive --client "go-ethereum,nimbus-bn,nimbus-vc,lodestar-bn,lodestar-vc" --sim eth2/withdrawals --sim.limit "/test-builders-capella-invalid-withdrawals
" --sim.loglevel 5
```

From the start, both clients will be unable to connect to each other, regardless of whether nimbus is set as bootnode of lodestar or vice-versa.

**Desktop:**

- OS: Ubuntu
- Version: 18.04.6 LTS
- Branch: unstable
- Commit hash: 7a40fab

**Comment by marioevz** [comment]
Nimbus is indeed setting its finalized head to the genesis block root:
```
INF 2023-02-20 17:47:10.345+00:00 Block DAG initialized head=8f28acc0:0 finalizedHead=8f28acc0:0 tail=8f28acc0:0 backfill="(0, \"00000000\")" loadDur=5ms504us summariesDur=63ms246us626ns finalizedDur=127ms654us979ns frontfillDur=88ns keysDur=52us161ns
```

But I don't see why this should be an issue while peering.

**Comment by philknows** [comment]
cc: @tuyennhv Not sure if this relates to your investigation on Nimbus <> Lodestar peering?

**Comment by dapplion** [comment]
- @marioevz Opened PR https://github.com/ChainSafe/lodestar/pull/5199 to drop the condition which is unnecessary

**Comment by twoeths** [comment]
> cc: @tuyennhv Not sure if this relates to your investigation on Nimbus <> Lodestar peering?

@philknows no it's not related to that
