### ISSUE TITLE
Not use the import destructuring for some modules e.g. `path`

### ISSUE THREAD

**Issue by nazarhussain** [ChainSafe/lodestar#5201]
**Is your feature request related to a problem? Please describe.**

It's not a problem and a styling issue and consistent use of it. During the discussion it's raised by @nflaig  and @dapplion  to not use the import destructuring for the modules like `path`. So if we have to use `join` or `resolve` we should always use `path.join` and `path.resolve`. 

It's not a functionality problem, but a styling and it must be enforced by linting rule to have consistent usage. 

**Describe the solution you'd like**

Create a new eslint rule to enforce not use the destructuring for the given list of packages. 

**Describe alternatives you've considered**

Tried to find existing eslint plugins but there is none with such behavior that came up in my search. 

**Additional context**

> highly opinionated (feel free to ignore) but I really don't like just having `join` here, someone has to hover the function to know it from `path` library or scroll up to the imports to see where this is coming from
>
> since path uses such general names for it's functions I generally like to do `path.`, to make it more obvious we are joining paths here
>
> ```suggestion
>     cacheFilePath: path.join(accountPaths.cacheDir, "imported_keystores.cache"),
> ```

_Originally posted by @nflaig in https://github.com/ChainSafe/lodestar/pull/5197#discussion_r1114801898_

**Comment by nflaig** [comment]
wondering if we want to enforce this on all functions or just a subset which use ambiguous names, also I have not found a solution to enforce this on all but can just extend our `no-restricted-imports` rule, the rule below would forbid doing `import {join} from "node:path";`

```diff
diff --git a/.eslintrc.js b/.eslintrc.js
index fefb3cdfd0..5850711e03 100644
--- a/.eslintrc.js
+++ b/.eslintrc.js
@@ -156,6 +156,11 @@ module.exports = {
           {name: "stream", message: "Please use node:stream instead."},
           {name: "util", message: "Please use node:util instead."},
           {name: "url", message: "Please use node:url instead."},
+          {
+            name: "node:path",
+            importNames: ["join", "normalize", "resolve", "dirname", "basename", "extname"],
+            message: "Importing from 'path' using destructuring is not allowed.",
+          },
         ],
       },
     ],

```

**Comment by nflaig** [comment]
looks like it is also possible to disallow this for all imports from `node:path` like this

```diff
diff --git a/.eslintrc.js b/.eslintrc.js
index fefb3cdfd0..eca8085c56 100644
--- a/.eslintrc.js
+++ b/.eslintrc.js
@@ -159,6 +159,13 @@ module.exports = {
         ],
       },
     ],
+    "no-restricted-syntax": [
+      "error",
+      {
+        selector: "ImportDeclaration[source.value='node:path'] ImportSpecifier",
+        message: "Importing from 'path' using destructuring is not allowed.",
+      },
+    ],
     // Force to add names to all functions to ease CPU profiling
     "func-names": ["error", "always"],
 
```
