### ISSUE TITLE
produceBlock takes so much time on mainnet

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5226]
**Describe the bug**

Sometimes it takes 9s to produce block:

```
1047041:Feb-28 19:45:35.129[rest]            debug: Req req-gsso produceBlockV2
1047160:Feb-28 19:45:44.222[rest]            debug: Res req-gsso produceBlockV2 - 200
```

I was not able to find which apis cause time in the log

**Expected behavior**

- Should log the time for `produceBlock`
- Investigate what caused the issue

**Desktop (please complete the following information):**

- Version: v1.4.2
- Network: mainnet

**Comment by twoeths** [comment]
this was caught in the REST api response time on Feb 28

<img width="800" alt="Screen Shot 2023-03-03 at 13 58 00" src="https://user-images.githubusercontent.com/10568965/222652587-d0802ebe-dfa4-4206-a372-fb56f8a04ffe.png">

confirmed in the log, there were 4 `produceBlockV2` calls in total, the last one took almost 10s

```
155000:Feb-28 02:40:47.244[rest]            debug: Req req-foga produceBlockV2
155002:Feb-28 02:40:47.671[rest]            debug: Res req-foga produceBlockV2 - 200
560740:Feb-28 10:14:47.038[rest]            debug: Req req-g35r produceBlockV2
560743:Feb-28 10:14:47.634[rest]            debug: Res req-g35r produceBlockV2 - 200
782386:Feb-28 14:34:59.036[rest]            debug: Req req-gbhq produceBlockV2
782395:Feb-28 14:34:59.644[rest]            debug: Res req-gbhq produceBlockV2 - 200
1038917:Feb-28 19:40:48.058[rest]            debug: Req req-gkj0 produceBlockV2
1039048:Feb-28 19:40:57.945[rest]            debug: Res req-gkj0 produceBlockV2 - 200
```

however block production time were all < 1s

<img width="1290" alt="Screen Shot 2023-03-03 at 14 09 55" src="https://user-images.githubusercontent.com/10568965/222654706-0c9ee035-f39d-40c5-afb3-f0c892dbb9fb.png">

could be something related to block serialization

**Comment by twoeths** [comment]
was able to catch a big execution payload fetch time on rescue node

<img width="1305" alt="Screen Shot 2023-03-03 at 15 01 08" src="https://user-images.githubusercontent.com/10568965/222664694-485c3e3a-176d-4fc1-88b4-2346ff85c485.png">

**Comment by twoeths** [comment]
> could be something related to block serialization

confirm that streaming block json to `vc` takes time sometimes, see https://github.com/ChainSafe/lodestar/issues/5227#issuecomment-1455532452

**Comment by dapplion** [comment]
Closing non-actionable issue
- producing blocks is a sparse action, logs here are good to debug specific incidents https://github.com/ChainSafe/lodestar/pull/5231
- solution 1 https://github.com/ChainSafe/lodestar/issues/5243
- solution 2 https://github.com/ChainSafe/lodestar/issues/5244
