### ISSUE TITLE
Vc delays publishing block for unknown reason

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5227]
**Describe the bug**

When producing blocks, sometimes both builder and execution blocks come but vc keeps delaying for unknown reason

it could be up to 7s as below log
```
validator-2023-02-28.log:84378:Feb-28 20:12:11.005[]                debug: Producing block slot=5899259, validator=0x82c92b72f4f94cc7bac5687f47a5f38da36b78be85c91b75199e6a55af38a822034fa97add11fb744d3dcf0fb1ed864c
validator-2023-02-28.log:84383:Feb-28 20:12:11.660[]                debug: HttpClient response routeId=produceBlockV2
validator-2023-02-28.log:84384:Feb-28 20:12:12.156[]                debug: HttpClient response routeId=produceBlindedBlock
validator-2023-02-28.log:84395:Feb-28 20:12:18.972[]                debug: Produced block slot=5899259, validator=0x82c92b72f4f94cc7bac5687f47a5f38da36b78be85c91b75199e6a55af38a822034fa97add11fb744d3dcf0fb1ed864c, source=builder, blockValue=20238157319785997
```

**Expected behavior**

Vc should publish block right after it fetches both blinded and execution blocks

**Desktop (please complete the following information):**

- Version: v1.4.2
- Network: mainnet

**Comment by twoeths** [comment]
full log

```
Feb-28 20:12:11.004[]                ^[[34mdebug^[[39m: HttpClient request routeId=getProposerDuties
Feb-28 20:12:11.005[]                ^[[34mdebug^[[39m: Producing block slot=5899259, validator=0x82c92b72f4f94cc7bac5687f47a5f38da36b78be85c91b75199e6a55af38a822034fa97add11fb744d3dcf0fb1ed864c
Feb-28 20:12:11.005[]                ^[[34mdebug^[[39m: HttpClient request routeId=produceBlindedBlock
Feb-28 20:12:11.005[]                ^[[34mdebug^[[39m: HttpClient request routeId=produceBlockV2
Feb-28 20:12:11.344[]                ^[[34mdebug^[[39m: HttpClient response routeId=getProposerDuties
Feb-28 20:12:11.344[]                ^[[34mdebug^[[39m: Downloaded proposer duties epoch=184351, dependentRoot=0x8dbc44095781c4273fe5d7b59b6922e9b1038de1ae056a062a35c385d80cf88b, count=1
Feb-28 20:12:11.660[]                ^[[34mdebug^[[39m: HttpClient response routeId=produceBlockV2
Feb-28 20:12:12.156[]                ^[[34mdebug^[[39m: HttpClient response routeId=produceBlindedBlock
Feb-28 20:12:15.000[]                ^[[34mdebug^[[39m: HttpClient request routeId=produceAttestationData
Feb-28 20:12:15.071[]                ^[[34mdebug^[[39m: HttpClient response routeId=produceAttestationData
Feb-28 20:12:15.075[]                ^[[34mdebug^[[39m: Signed attestation slot=5899259, index=36, head=0xdadae736ebf386cc101d2c7d8d5a8da71023a7e733a184de9dfbd700d86ee5e3, validatorIndex=521852
Feb-28 20:12:15.076[]                ^[[34mdebug^[[39m: Signed attestation slot=5899259, index=51, head=0xdadae736ebf386cc101d2c7d8d5a8da71023a7e733a184de9dfbd700d86ee5e3, validatorIndex=521930
Feb-28 20:12:15.078[]                ^[[34mdebug^[[39m: Signed attestation slot=5899259, index=52, head=0xdadae736ebf386cc101d2c7d8d5a8da71023a7e733a184de9dfbd700d86ee5e3, validatorIndex=521971
Feb-28 20:12:15.079[]                ^[[34mdebug^[[39m: Signed attestation slot=5899259, index=5, head=0xdadae736ebf386cc101d2c7d8d5a8da71023a7e733a184de9dfbd700d86ee5e3, validatorIndex=521980
Feb-28 20:12:15.079[]                ^[[34mdebug^[[39m: Signed attestation slot=5899259, index=27, head=0xdadae736ebf386cc101d2c7d8d5a8da71023a7e733a184de9dfbd700d86ee5e3, validatorIndex=522002
Feb-28 20:12:15.079[]                ^[[34mdebug^[[39m: HttpClient request routeId=submitPoolAttestations
Feb-28 20:12:15.470[]                ^[[34mdebug^[[39m: HttpClient response routeId=submitPoolAttestations
Feb-28 20:12:15.470[]                 ^[[32minfo^[[39m: Published attestations slot=5899259, count=5
Feb-28 20:12:18.972[]                ^[[34mdebug^[[39m: Produced block slot=5899259, validator=0x82c92b72f4f94cc7bac5687f47a5f38da36b78be85c91b75199e6a55af38a822034fa97add11fb744d3dcf0fb1ed864c, source=builder, blockValue=20238157319785997
Feb-28 20:12:18.989[]                ^[[34mdebug^[[39m: HttpClient request routeId=publishBlindedBlock
```

**Comment by twoeths** [comment]
It's so weird that we fetched both builder block and execution block at `vc` side but was not able to finish `produceBlockWrapper` (only after 7s), although `submitPoolAttestations` runs in the middle

any ideas @ChainSafe/lodestar ? I'd avoid getting the value from a resolved promise at https://github.com/ChainSafe/lodestar/blob/v1.4.2/packages/validator/src/services/block.ts#L138 , get it from `Promise.all()` instead, but don't think it's the root cause

**Comment by nflaig** [comment]
I can't really explain what took those ~7s, here are just a few observations

1. HttpClient response is actually [logged before](https://github.com/ChainSafe/lodestar/blob/440c59f080165749666639aab32abb72ae570cf8/packages/api/src/utils/client/httpClient.ts#L288) the [request body is parsed](https://github.com/ChainSafe/lodestar/blob/440c59f080165749666639aab32abb72ae570cf8/packages/api/src/utils/client/httpClient.ts#L290), this is also the only operation I found that could potentially take a bit more time between the log `HttpClient response...` and `Produced block...`

Is the response body streamed here?

> The json() method may also need to wait for the response body to be fully downloaded before it can start parsing. If the response is being streamed, for example, the json() method may need to wait for the entire stream to be downloaded before it can start parsing the JSON data.

2. The validator [default timeout is `SECONDS_PER_SLOT`](https://github.com/ChainSafe/lodestar/blob/a4434f75016cf3d85aaececa33fcfd6b8cdb3b52/packages/validator/src/validator.ts#L82) for BN requests, is that correct? If we wait until the slot ends we will never be able to produce the block in time or am I missing something?

3. It is highly questionable that we [wait for both](https://github.com/ChainSafe/lodestar/blob/440c59f080165749666639aab32abb72ae570cf8/packages/validator/src/services/block.ts#L136) the builder and execution block to be resolved without a lower timeout. We only need one of them and should assume builder and execution client are unresponsive, need to define proper cutoff timeout which is much lower than `SECONDS_PER_SLOT`. I have not looked at the PR yet but I think this will be addressed by https://github.com/ChainSafe/lodestar/pull/5223

4. tracing would be really helpful here to exactly see which part of the execution took how long without even having to look at logs and timestamps

**Comment by g11tech** [comment]
yes @nflaig, this PR https://github.com/ChainSafe/lodestar/pull/5223 will take address some of the issues and add a detailed trace to the events

**Comment by nflaig** [comment]
@tuyennhv is it possible to get `lodestar_eth1_http_client_request_time_seconds` metric this specific time span? We have a 5 seconds bucket so should see if what I mentioned in 1. was the problem

**Comment by twoeths** [comment]
> HttpClient response is actually [logged before](https://github.com/ChainSafe/lodestar/blob/440c59f080165749666639aab32abb72ae570cf8/packages/api/src/utils/client/httpClient.ts#L288) the [request body is parsed](https://github.com/ChainSafe/lodestar/blob/440c59f080165749666639aab32abb72ae570cf8/packages/api/src/utils/client/httpClient.ts#L290), this is also the only operation I found that could potentially take a bit more time between the log HttpClient response... and Produced block...

@nflaig  I did some tests and found it's not a lot of time, `vc` was really free and was able to produce attestation datas, sign and submit attestations timely (see the log)

not sure you mentioned `lodestar_eth1_http_client_request_time_seconds` as it's not in `vc` flow

**Comment by nflaig** [comment]
> not sure you mentioned lodestar_eth1_http_client_request_time_seconds as it's not in vc flow

@tuyennhv ah you are right, the metric is `vc_rest_api_client_request_time_seconds`

**Comment by twoeths** [comment]
@nflaig the above metric at `vc` side

<img width="1303" alt="Screen Shot 2023-03-06 at 13 27 28" src="https://user-images.githubusercontent.com/10568965/223034898-87964a6d-2403-4c17-b6bb-19604a7fc355.png">


<img width="1307" alt="Screen Shot 2023-03-06 at 13 28 24" src="https://user-images.githubusercontent.com/10568965/223035068-1e98fa5a-58d6-471f-9499-aa2257c8f6cc.png">

so you're right it's the body streaming time when `vc` received http header 200 but wasn't able to parse the http response until it's fully downloaded

**Comment by nflaig** [comment]
@tuyennhv Thanks for looking into it 👍
