### ISSUE TITLE
Shapella Mainnet Checklist

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#5245]
As discussed on the March 7 standup, this checklist is to ensure remaining items/testing are included for functionality, testing and feature completeness for the the Shapella mainnet upgrade.

TO-DO
- [x] Light client requirements for Capella https://github.com/ChainSafe/lodestar/issues/5102

TO-TEST:
- [x] BLS-to-execution change queue length (UX testing)

**Comment by wemeetagain** [comment]
@g11tech should this be removed?
https://github.com/ChainSafe/lodestar/blob/27feb58689bcef76aab6c79efb1bfd66c4c67254/packages/beacon-node/src/api/impl/beacon/pool/index.ts#L121-L122

**Comment by g11tech** [comment]
> @g11tech should this be removed?
> https://github.com/ChainSafe/lodestar/blob/27feb58689bcef76aab6c79efb1bfd66c4c67254/packages/beacon-node/src/api/impl/beacon/pool/index.ts#L121-L122

Yes we can remove this 👍

**Comment by g11tech** [comment]
> > @g11tech should this be removed?
> > https://github.com/ChainSafe/lodestar/blob/27feb58689bcef76aab6c79efb1bfd66c4c67254/packages/beacon-node/src/api/impl/beacon/pool/index.ts#L121-L122
> 
> Yes we can remove this +1

https://github.com/ChainSafe/lodestar/pull/5261

**Comment by philknows** [comment]
Closing issue. Only 1 remaining item already tagged for next hotfix release discussed on Apr 4 standup. Happy withdrowls! 🦉
