### ISSUE TITLE
v1.6.0-rc.0: Increased block process time

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5247]
**Describe the bug**

This is from the beta mainnet running v1.6.0, Gossip Block Process time has been increased

<img width="1430" alt="Screen Shot 2023-03-08 at 16 04 56" src="https://user-images.githubusercontent.com/10568965/223669978-261f5f49-c0fc-462f-9113-9e32a0337d9f.png">

<img width="1296" alt="Screen Shot 2023-03-08 at 16 05 30" src="https://user-images.githubusercontent.com/10568965/223670091-122250dc-db71-4075-8a86-facef5e4fea7.png">

**Expected behavior**

Gossip Block Process time should be the same to `stable` group (v1.4.2)

**Comment by twoeths** [comment]
Same metric in stable mainnet node

<img width="1298" alt="Screen Shot 2023-03-08 at 16 07 32" src="https://user-images.githubusercontent.com/10568965/223670552-370dbdc0-d83b-4e15-8028-8b5dd297706e.png">

<img width="1300" alt="Screen Shot 2023-03-08 at 16 08 09" src="https://user-images.githubusercontent.com/10568965/223670651-5ada39fd-b8c8-4f77-9afa-abd793fcdda3.png">

**Comment by twoeths** [comment]
this is mainly due to the `notifyNewPayload` engine api call

<img width="1302" alt="Screen Shot 2023-03-08 at 17 15 30" src="https://user-images.githubusercontent.com/10568965/223686019-208446f5-9177-42d7-80ca-9edd2c672207.png">

in the stable mainnet node

<img width="1294" alt="Screen Shot 2023-03-08 at 17 16 29" src="https://user-images.githubusercontent.com/10568965/223686254-d1c8540c-3693-4416-aa8b-dff47ff8540d.png">

**Comment by twoeths** [comment]
CPU time in v1.6.0 increased a lot

<img width="808" alt="Screen Shot 2023-03-08 at 18 17 06" src="https://user-images.githubusercontent.com/10568965/223699639-32b86a83-2800-4057-86eb-7fc93396c926.png">

GC Pause Time Rate tends keeps increasing

<img width="785" alt="Screen Shot 2023-03-08 at 18 20 41" src="https://user-images.githubusercontent.com/10568965/223700398-fdcf8519-7eaf-4cb7-89c1-eaa1bb95806e.png">

Execution engine notifyNewPayload body streaming time is high too

<img width="1301" alt="Screen Shot 2023-03-08 at 18 19 23" src="https://user-images.githubusercontent.com/10568965/223700117-bde9774c-2f4b-40d8-9768-4df7c021aa31.png">

on `beta 1k` node, `submitPoolAttestations` increased significantly
<img width="798" alt="Screen Shot 2023-03-08 at 18 22 55" src="https://user-images.githubusercontent.com/10568965/223700835-88a0c5a3-eaf9-4126-97b7-bc68d9351c17.png">

**Comment by dapplion** [comment]
@tuyennhv can you take a CPU profile to check's what taking cpu time?

**Comment by twoeths** [comment]
[0309_v1.6.0_rc.0_goerli_lg1k.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/10939299/0309_v1.6.0_rc.0_goerli_lg1k.cpuprofile.zip)

@dapplion  I'ts just like each api takes more cpu time since we process more gossip messages
- `validateGossipAttestation` takes 8% cpu time
- adding attestation to pool takes 8% of cpu time (mainly aggregateAttestationInto)
- `executeWork` takes 5% cpu time

This is on goerli, could be worse on mainnet. I think we can reduce the attestation preaggregation time, we should only preaggregate attestations in the clock slot, also there are some late attestations coming to the pool as I see on mainnet

<img width="866" alt="Screenshot 2023-03-10 at 14 39 11" src="https://user-images.githubusercontent.com/10568965/224253260-875ef617-4323-4cab-ad7e-5d73fc13de15.png">

**Comment by twoeths** [comment]
There is I/O lag issue

at validator side
```
Mar-27 06:29:40.504[]                debug: HttpClient request routeId=submitPoolAttestations
Mar-27 06:29:45.932[]                debug: HttpClient response routeId=submitPoolAttestations
```

at beacon-node side
```
Mar-27 06:29:45.383[rest]            debug: Req req-3e4z 127.0.0.1 submitPoolAttestations
Mar-27 06:29:45.956[rest]            debug: Res req-3e4z submitPoolAttestations - 200
```

**Comment by twoeths** [comment]
was able to catch 700ms lag

vc log
```
Mar-27 06:35:37.746[]                debug: HttpClient request routeId=submitPoolAttestations
Mar-27 06:35:39.801[]                debug: HttpClient response routeId=submitPoolAttestations
```

bn log:
```
Mar-27 06:35:38.438[rest]            debug: Req req-3eb2 127.0.0.1 submitPoolAttestations
Mar-27 06:35:39.812[rest]            debug: Res req-3eb2 submitPoolAttestations - 200
```

it shows too many `validateGossipAttestations` in the middle, once it's validated `onValidationResult` was called synchronously
<img width="975" alt="Screenshot 2023-03-27 at 14 26 09" src="https://user-images.githubusercontent.com/10568965/227870208-99358298-771d-47b5-b4f6-ee0497fb2d39.png">

we can check the time between `produceAttestationData` and `submitPoolAttestations` in the attached 7s profile

[0327_feat1_lg1k_gossip_queues.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/11075784/0327_feat1_lg1k_gossip_queues.cpuprofile.zip)

there are also `chacha20poly1305` calls which take time but I've checked that network load is just the same to `stable` group.

**Comment by twoeths** [comment]
This profile from mainnet node shows it takes almost 12% cpu for `validateGossipAttestation()`
<img width="1473" alt="Screenshot 2023-03-31 at 08 43 20" src="https://user-images.githubusercontent.com/10568965/229001573-7e8a5fb9-83c7-4665-a79b-4216be2c224f.png">

Inside `validateGossipAttestation()`, it takes 5.8% for `computeSiningRoot()` and 3.9% for `validateHeadBlockAndTargetRoot()`

<img width="1291" alt="Screenshot 2023-03-31 at 08 44 15" src="https://user-images.githubusercontent.com/10568965/229001694-d3a410c5-8f2c-47eb-9732-c128247e96ba.png">

[0330_new_gossipsub_mainnet_subscribeAllSubnets.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/11117392/0330_new_gossipsub_mainnet_subscribeAllSubnets.cpuprofile.zip)

**Comment by twoeths** [comment]
as tested on mainnet, there are at least 80% of gossip attestations from same clock slot, we can implement some cache to improve `validateGossipAttestation()` to avoid the above functions running over and over for same data

<img width="1302" alt="Screenshot 2023-04-02 at 06 52 48" src="https://user-images.githubusercontent.com/10568965/229323235-96fb9321-fcb7-4b6f-a7bc-d5e064ede051.png">
