### ISSUE TITLE
New metrics to track proposed blocks

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5255]
**Is your feature request related to a problem? Please describe.**

Need new metrics to track blocks proposed by a lodestar node's local validators (same to `beaconcha.in`:
- Blocks proposed and included in canonical chain
- Orphaned blocks
- Missed blocks

**Comment by philknows** [comment]
Adding comment and referencing #5448 for first PR merged. @g11tech will include an update PR which will:
- Make it sync aware (so it doesn't show while syncing)
- Disable if no validators are attached
- Only display in `info` if non-zero. else it goes to `debug`
- Change the word `expected` to `total` to minimize confusion on logger

Reference Discord discussion: https://discord.com/channels/593655374469660673/1105347927548907600/1110563872152236133

**Comment by philknows** [comment]
#5538 was merged, but wanted to clarify if this issue was meant also for it to be tracked in Grafana also @tuyennhv ? If not, should be good to close.

**Comment by dapplion** [comment]
- Completed with https://github.com/ChainSafe/lodestar/issues/5448
