### ISSUE TITLE
Error: JSON RPC error: invalid terminal block hash, engine_exchangeTransitionConfigurationV1

### ISSUE THREAD

**Issue by avenbreaks** [ChainSafe/lodestar#5264]
**Describe the bug**

good day, I've run my custom blockchain with 2 node el (geth) and 2 node cl (lodestar) and it's running already got 1k blocks, but I got an error like this :

logs beacon : 
```
Mar-13 02:55:38.402[api] [31merror[39m: Error on submitPoolSyncCommitteeSignatures [0] slot=25, validatorIndex=0 PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
Error: Multiple errors on publishAggregateAndProofs
Mar-13 02:55:41.376[api] [31merror[39m: Error on submitPoolSyncCommitteeSignatures [0] slot=26, validatorIndex=0 PublishError.InsufficientPeers
```

what i see on lodestar's official github is an unobtrusive error and i can ignore this error, but i don't see this problem is solved or not. and henceforth I want to be a validator on this custom network using another machine by utilizing bootnodes and enr but getting an error like this :

Logs Beacon 2nd Server : 
```
Mar-13 14:47:18.501[] [32minfo[39m: Searching peers - peers: 0 - slot: 14258 (skipped 14258) - head: 0 0x92b4…923c - execution: valid(0x0beb…c0c5) - finalized: 0x0000…0000:0
Mar-13 14:47:21.501[] [32minfo[39m: Searching peers - peers: 0 - slot: 14259 (skipped 14259) - head: 0 0x92b4…923c - execution: valid(0x0beb…c0c5) - finalized: 0x0000…0000:0
Mar-13 14:47:23.004[chain] [33mwarn[39m: Could not validate transition configuration with execution client  JSON RPC error: invalid terminal block hash, engine_exchangeTransitionConfigurationV1
Error: JSON RPC error: invalid terminal block hash, engine_exchangeTransitionConfigurationV1
```
`curl http://localhost:9596/eth/v1/node/identity
`
```
{
    "data": {
        "peer_id": "16Uiu2HAm3YVZ3cah2ntVfSSLxH3a63q6cdrvLQAFG2a2hE8Wxoq6",
        "enr": "enr:-MS4QDxojmA0qTMzQTkefSYoesqLxt4x6TP5qMYcB6URVXi1IXW7CnlIMqTswKPElkz07bMzb-wVg7ajMhP10P_LWREHh2F0dG5ldHOIAAAAAAAAAACEZXRoMpBrsEGqAiAhkf__________gmlkgnY0gmlwhH8AAAGJc2VjcDI1NmsxoQJ4nMWGpQ7EaTc4X-sHfVEg0fiMZCIaEMkyfe6CTi_kZYhzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo",
        "p2p_addresses": [
            "/ip4/127.0.0.1/tcp/9000/p2p/16Uiu2HAm3YVZ3cah2ntVfSSLxH3a63q6cdrvLQAFG2a2hE8Wxoq6",
            "/ip4/172.31.78.113/tcp/9000/p2p/16Uiu2HAm3YVZ3cah2ntVfSSLxH3a63q6cdrvLQAFG2a2hE8Wxoq6"
        ],
        "discovery_addresses": [
            "/ip4/127.0.0.1/tcp/9000",
            "/ip4/127.0.0.1/udp/9000"
        ],
        "metadata": {
            "seq_number": "0",
            "attnets": "0x0000000000000000",
            "syncnets": "0x00"
        }
    }
}
```

**Expected behavior**
Running And Connect to first Nodes. 

**Steps to Reproduce**
Configuration Eth1 : 

```
nohup geth \
--http \
--http.port 8545  \
--http.api=eth,net,web3,personal,miner \
--http.addr=0.0.0.0 \
--http.vhosts=* \
--http.corsdomain=* \
--networkid 1881 \
--datadir "/home/ubuntu/server/testnet-list/gethdata" \
--authrpc.port 8551 \
--port 30303 \
--syncmode full \ 
--bootnodes "enode://0b537a418dd47cea703c3b66bb03b64611f03c9e2ec3b0634946c67b0e6e7d5917ef29f1ffa680fe8b98989ced936787c4b33d1139b3a3aa29dd730ff0b03ec0@139.178.94.227:30303" > ./logs/geth.log 2>&1 &
```
Configuration Eth2 Lodestar : 

```
nohup lodestar beacon \
--suggestedFeeRecipient "0xa71f4093002155457da565acc2598b975306bd21" \
--execution.urls "http://127.0.0.1:8551" \
--jwt-secret "/home/ubuntu/server/testnet-list/gethdata/geth/jwtsecret" \
--dataDir "/home/ubuntu/server/testnet-list/lodestardata" \
--paramsFile "/home/ubuntu/server/testnet-list/eth-network/cartenz/consensus/config.yaml" \
--genesisStateFile "/home/ubuntu/server/testnet-list/eth-network/cartenz/consensus/genesis.ssz" \
--enr.ip 127.0.0.1 \
--rest.port 9596 \
--port 9000 \
--network.connectToDiscv5Bootnodes true \
--logLevel=info \
--bootnodes="enr:-MS4QHlsTrznMo6CNlgjbqev4xwanbfocKYG_trfGYqOfxSMRykba13eohXRXRkjT-ulmP8tACzYhY9afNYVYGS5l0EHh2F0dG5ldHOIAAAAAAAAAACEZXRoMpBrsEGqAiAhkf__________gmlkgnY0gmlwhH8AAAGJc2VjcDI1NmsxoQLJgx8M7rL_WFWdzbN0PeKq16cLw_-VfJI2YtLJHrJFt4hzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo
","enr:-MS4QDrE4FryBl8Mv0Ms_qGXJZFmG0fglb1LT5VD9dCplGdjFQfdByXiXQJ1T90nqU218pntCcHA4Dz8x256I4bificHh2F0dG5ldHOIAAAAAAAAAACEZXRoMpBrsEGqAiAhkf__________gmlkgnY0gmlwhH8AAAGJc2VjcDI1NmsxoQOtfKRyp8AYzC0cKxUiWANcfo3KxasbJDI1xIjhUtU50IhzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIymDdWRwgiMp
" \ > ./logs/beacon.log &
```

**Screenshots**
**LODESTAR FIRST SERVER**
![image](https://user-images.githubusercontent.com/93043826/224756638-bdf939de-19ce-42ad-a280-a16cc5f20cd2.png)
![image](https://user-images.githubusercontent.com/93043826/224756873-0b5014d2-b9b5-4a50-81a5-e5fd24e02bbf.png)

**GETH FIRST SERVER**
![image](https://user-images.githubusercontent.com/93043826/224758034-4774d632-947e-4e4c-a1a1-04925b3a88e1.png)
![image](https://user-images.githubusercontent.com/93043826/224758214-3cf372ec-7012-4b75-918c-193acb89dc0c.png)

**GETH TO CONNECT FIRST SERVER**
![image](https://user-images.githubusercontent.com/93043826/224754446-cd22a8ad-b01a-432e-828a-29040d0661b2.png)
**LODESTAR TO CONNECT FIRST SERVER**
![image](https://user-images.githubusercontent.com/93043826/224754533-d57f618d-2285-4581-8f5e-86600df0bb7e.png)
**VALIDATOR TO CONNECT FIRST SERVER**
![image](https://user-images.githubusercontent.com/93043826/224755050-8fb48670-d791-4ad8-8c85-0c7f94565022.png)

**Desktop (please complete the following information):**

- OS: **AWS Ubuntu c6a.2xlarge**
- Version: **Version: v1.5.0**
- Branch:  **master**
- Commit hash: **6ac7d30**

**Comment by dapplion** [comment]
Hey @avenbreaks :wave: 

I see two different issues there:
1. InsufficientPeers: If you are running in a local devnet configuration it's likely to see those. The second node may appear as peer but not in any of the subnets the first node is publishing to. We are looking into tuning the verbosity of that error.
2. `invalid terminal block hash, engine_exchangeTransitionConfigurationV1` Error: @g11tech can you take a look?

**Comment by avenbreaks** [comment]
> Hai@avenbreaks melambai
> 
> Saya melihat dua masalah berbeda di sana:
> 
> 1. InsufficientPeers: Jika Anda menjalankan konfigurasi devnet lokal, kemungkinan akan melihatnya. Node kedua mungkin muncul sebagai rekan tetapi tidak di salah satu subnet yang diterbitkan oleh node pertama. Kami sedang mencari penyetelan verbositas kesalahan itu.
> 2. `invalid terminal block hash, engine_exchangeTransitionConfigurationV1`Kesalahan:@g11techbisakah kamu melihatnya?

i took the bootnode from the main server then i tried to connect using the second server but it was all the same, unable to connect, i tried the addPeer and addTrustedPeer methods then tried to fund my validator keystore with some faucets then import keystore running 2 beacon nodes and 1 validator node , the peer is always not found. is it because my main server is not opening firewall ports ? or from my own server ?

![image](https://user-images.githubusercontent.com/93043826/226249814-48132f03-7d3b-4c2b-b679-80ec19e5c39f.png)

**Comment by g11tech** [comment]
for `invalid terminal block hash, engine_exchangeTransitionConfigurationV1`  seems like your config.yaml has some TERMINAL_BLOCK_HASH set which mismatches with geth genesis.json, only try setting TOTAL_TERMINAL_DIFFICULTY

for making sure your peer2 connects peer1, have you also provided `--enr.udp` port on peer1?

**Comment by dapplion** [comment]
Closing issues for specific incidents on old versions of Lodestar, please re-open if it happens with latest stable
