### ISSUE TITLE
How to setup lodestar for local test net?

### ISSUE THREAD

**Issue by zydjohnHotmail** [ChainSafe/lodestar#5272]
Hello:
I don't need validator neither goerli test net.  
I just want to setup a local test net, so I can run geth to mine some blocks, before the merge, I don't even need a consensus client.
But with the current geth version, I have to run a consensus client, otherwise, geth simply stops mining.
Please advise how can I do a simplest configuration, so geth current version can run with lodestar as consensus client.
Thanks,

**Comment by dapplion** [comment]
Please check this quickstart guide: https://github.com/ChainSafe/lodestar-quickstart/

For usability issue please reach out in our Discord https://discord.gg/pcZjfekC . Github is meant for issues that require code changes.
