### ISSUE TITLE
VC cannot decrypt keystores with encryption password ending in specific character(s)

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#5276]
**Describe the bug**

The validator client is unable to decrypt a keystore if the encryption password ends in the `|` character. I haven't tried to see if other characters create the same behaviour, but this character triggers it and you will receive the following response in the VC:

```ts
 ✖ Error: Invalid password
    at Object.<anonymous> (/usr/app/node_modules/@chainsafe/bls-keystore/lib/functional.js:86:19)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/app/node_modules/@chainsafe/bls-keystore/lib/functional.js:5:58)
```

*Will update if other characters trigger the same result*

**Expected behavior**

Passwords should be able to use any special character and not encounter errors during decryption.

**Steps to Reproduce**

1. Create a keystore.json file and encrypt it with a password ending in `|` 
2. Run the VC on this keystore
3. Observe `Error: Invalid password` response

**Screenshots**
<img width="1027" alt="Screenshot 2023-03-16 at 5 35 31 PM" src="https://user-images.githubusercontent.com/58080811/225775374-8b1a0387-6e51-4949-b517-079833707a8a.png">

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04.1
- Version: v1.5.1/3d937ee
- Branch: unstable
- Commit hash: 3d937ee6f450967027a3bb47ad2b4ae681420941

**Comment by dapplion** [comment]
@nflaig can you take a look?

**Comment by nflaig** [comment]
@dapplion have it on my list already, will look into it today/tomorrow
