### ISSUE TITLE
Establish logging pattern for non-critical failures

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#5288]
@wemeetagain I want to establish this pattern that for non-critical issues we use the terms "failed"  and "reason" instead of "error" as based on my observations the term "error" scares a lot of users, especially less technical ones.

_Originally posted by @nflaig in https://github.com/ChainSafe/lodestar/pull/5285#discussion_r1143457340_

**Comment by philknows** [comment]
Also some backlogged things we've wanted to get to in regards to UX on #4400. In my opinion, generally, the word `error:` should be reserved for issues where a user misconfiguration or inaction by the user created a problem. Thus, it should only be used as a way to prompt users that they _must_ do something to rectify it.

If it's not something a normal user can fix, it should be more of a warning type of message or something where stacktrace can be logged elsewhere but not saturate the CLI with endless errors a typical user cannot do much with.

**Comment by philknows** [comment]
Related to #5299 to set a standard

**Comment by philknows** [comment]
Closed in favour of #5359
