### ISSUE TITLE
Update state transition to 0.9.0

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#529]
- add new spec tests from 0.8.4 release -  https://github.com/ethereum/eth2.0-specs/pull/1444
- update state transition changes and spec tests from - https://github.com/ethereum/eth2.0-specs/pull/1453

**Comment by twoeths** [comment]
@mpetrunic please assign this to me if this is ready to work on.

**Comment by mpetrunic** [comment]
Ill assign you, but I didn't have time yesterday to push spec tests, I'll do it in an hour and half

**Comment by mpetrunic** [comment]
@tuyennhv 
https://www.npmjs.com/package/@chainsafe/eth2-spec-tests/v/0.9.0-1

**Comment by twoeths** [comment]
Merged to branch 0.9.0.
