### ISSUE TITLE
Default validator HTTP request timeout is too short

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#5315]
At the moment all HTTP requests done by the VC have a timeout of `SECONDS_PER_SLOT` (12 seconds).

https://github.com/ChainSafe/lodestar/blob/f136f952ddb861976b3cc9484914c49a06ee8d90/packages/validator/src/validator.ts#L83-L84

Most of the time the HTTP request timeout does not matter at all as we expect that the BN responds within few milliseconds but there might be unexpected network issues and we should account for this.

It should be allowed to take longer than the current slot for attestation tasks as late submission of attestations is still acceptable, it will just not give as good rewards but it is still better than completely missing the attestation due to the timeout.
See [Rewards and Penalties](https://kb.beaconcha.in/rewards-and-penalties).

The current timeout also does not really make sense, if a HTTP request is sent at 2/3 of the slot to `getAggregatedAttestation` it would mean the timeout happens after the slot is already over (20 seconds).

**Current behavior**

VC has a default HTTP timeout of `SECONDS_PER_SLOT` which could potentially cause missed attestations.

**Expected behavior**

VC should account for network issues and have a higher timeout, potentially something like `SECONDS_PER_SLOT * 5` (60 seconds). Timeout should be chosen based on [Attestation Reward Scale](https://www.attestant.io/posts/defining-attestation-effectiveness/) and technical implications of keeping the HTTP request open for too long.

Related https://github.com/ChainSafe/lodestar/issues/5314

**Comment by dapplion** [comment]
With current approach timeouts have two impacts:
- (most important IMO) reporting to the user something is wrong + metrics
- limit concurrent active requests

Once an HTTP request is sent it's sent. Timeouts should not have a huge impact to normal functioning. If in a specific setup the timeout of SECONDS_PER_SLOT feels short.. I think the setup is not ok, requests must be fast for a validator to function properly. Increasing the timeout just seems like giving bad setups a pass for no clear benefit

**Comment by nflaig** [comment]
12 seconds is definitely not short, I even chose a [shorter timeout (10s)](https://github.com/ChainSafe/lodestar/blob/a2f749a6f08d5b8f6d1c52147b08f71d48f7abe2/packages/beacon-node/src/monitoring/options.ts#L18) for the monitoring which sends data to a remote service which is most of the time not the case for VC  <> BN requests.

But the reasoning behind choosing `SECONDS_PER_SLOT` seems wrong to me, especially because we are not sending http request at the beginning of the slot but rather at 1/3 or 2/3 of the slot.

https://github.com/ChainSafe/lodestar/blob/f136f952ddb861976b3cc9484914c49a06ee8d90/packages/validator/src/validator.ts#L83

For attestations and sync committee messages this comment is just not true, even if we take much longer than the slot it would still be rewarded (see [Attestation Reward Scale](https://www.attestant.io/posts/defining-attestation-effectiveness/)).

I totally agree with what you said but we need to be more precise on why we chose a specific timeout here, I think technical implications should be the priority. Using other parameters such as `SECONDS_PER_SLOT` does not make sense to me, there are other tasks that need to be done during a slot and usually involves multiple HTTP requests.

Finally, what happens if `SECONDS_PER_SLOT` has a lower value due to different chain configuration, lets say 6 seconds, why should http request now timeout ealier? does this change anything related to the setup or network latency?

To conclude, I would be in favor of using a fixed timeout (maybe configurable) here instead of making it dependent on `SECONDS_PER_SLOT`. I would be even fine with 10 seconds to be honest it is just important that we chose the value based on technical implications (metrics, limit concurrent active requests, etc.)

**Comment by nflaig** [comment]
interesting approach used by Lighthouse, they seem to [adjust the timeout based on task](https://github.com/sigp/lighthouse/blob/a53830fd60a119bf3f659b253360af8027128e83/validator_client/src/lib.rs#L294), see https://github.com/sigp/lighthouse/pull/2352. Seems to be mostly relevant when a fallback BN is configured.
And it looks like the also use [slot duration](https://github.com/sigp/lighthouse/blob/a53830fd60a119bf3f659b253360af8027128e83/validator_client/src/lib.rs#L310) as default timeout.

**Comment by dapplion** [comment]
Using SECONDS_PER_SLOT is arbitrary but any number will feel arbitrary. Picking this number is the least random value, as faster networks should have faster values

**Comment by nflaig** [comment]
Thanks @dapplion for the rationale. Sounds good to me 👍
