### ISSUE TITLE
Beacon node exits uncontrolled (too early) during graceful shutdown

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#5317]
**Problem**

Lodestar BN does not wait for [all jobs](https://github.com/ChainSafe/lodestar/blob/d360e62bde4abb566444d71f45fdc4fd74584ae7/packages/beacon-node/src/node/nodejs.ts#L309) to be finished during graceful shutdown.
This is problematic as some operations are not executed such as writing BLSToExecutionChanges to disk (see [discord discussion](https://discord.com/channels/593655374469660673/593655641445367808/1090250663344209983))

**Root cause**

Lodestar uses [threads package](https://www.npmjs.com/package/@chainsafe/threads) which installs [SIGTERM signal listeners](https://github.com/andywer/threads.js/blob/0d1a882f09273cb8482902ae2601fe4ffed6fbab/src/master/implementation.node.ts#L153)  that exit the main process once all workers are terminated, see [terminateWorkersAndMaster](https://github.com/andywer/threads.js/blob/0d1a882f09273cb8482902ae2601fe4ffed6fbab/src/master/implementation.node.ts#L142).

**Related**

- https://github.com/andywer/threads.js/pull/198
- https://github.com/andywer/threads.js/issues/388
- https://github.com/andywer/threads.js/pull/324
- https://github.com/MatrixAI/Polykey-Desktop/issues/79
- https://github.com/andywer/threads.js/pull/329

**Comment by g11tech** [comment]
yes i confirm this to be issue as pointed by @nflaig : https://github.com/andywer/threads.js/blob/0d1a882f09273cb8482902ae2601fe4ffed6fbab/src/master/implementation.node.ts#L142

as soon as i comment out the lines in the local nodemodules, node close follow all close steps (but obviously workers keep going on still), else it seems to be processing this event on the first true async await call (await network.close)

So we might need to export the `terminateWorkerAndMaster` and call it explicity and remove these

```
process.on("SIGINT", () => terminateWorkersAndMaster())
  process.on("SIGTERM", () => terminateWorkersAndMaster())

``

**Comment by nflaig** [comment]
As discussed in Apr 4 standup we want to push a fix for this before the Shapella hardfork to address the BLSToExecutionChanges issue and other possible issues related to not shutting down properly.

For the quickfix we will have to
- [x] release a new version of @chainsafe/threads @wemeetagain 
- [x] explicitly call process.exit after `node.close` succeeds (code: 0) or fails (code: 1) @nflaig
- [x] retest that BLSToExecutionChanges  are correctly persistet, best if @g11tech can confirm this once patch is implemented

In https://github.com/ChainSafe/lodestar/pull/5330 a cleaner solution will be implemented to make sure all active handlers are actually terminated and we don't need to rely on process.exit. I documented how to work with the branch in case anyone is bored and wants to go on an active handles hunt

**Comment by philknows** [comment]
Due to not being able to make the timeline for the Shapella hard fork (wasn't super urgent since other clients were able to handle the load as well), we can wait for #5330 and fix this optimally rather than implementing a workaround.
