### ISSUE TITLE
Align existing logger usage to new policy

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#5320]
- Ensure that all existing logger statements follow the policy defined in https://github.com/ChainSafe/lodestar/pull/5299

Notably:
- Move all verbose statements to debug
- Alias verbose to debug
- Consider what is trace and move from debug to trace

**Comment by philknows** [comment]
Go thru all logger info,warn,error
Ensure that each follows the logging policy

**Comment by wemeetagain** [comment]
Closing this since we've done a lot of work to align the logs to the logging policy
