### ISSUE TITLE
Unable to fetch weak subjectivity state on Gnosis with checkpoint sync

### ISSUE THREAD

**Issue by SpeakinTelnet** [ChainSafe/lodestar#5322]
**Describe the bug**

Trying to sync from checkpoint on the Gnosis network cause lodestar to crash with the following message:

 ```console
Mar-30 08:14:11.084[]                 info: Lodestar network=gnosis, version=v1.7.1/37201f1, commit=37201f103f11d46c5fd47698685118d9da0c29d0
Mar-30 08:14:11.094[]                 info: Connected to LevelDB database path=/home/ansible/.local/share/lodestar/gnosis/chain-db
Mar-30 08:14:11.096[]                 info: Fetching checkpoint state checkpointSyncUrl=https://checkpoint.gnosischain.com
Mar-30 08:14:12.189[]                 info: Download completed stateId=finalized
 ✖ Error: Unable to fetch weak subjectivity state: First offset must equal to fixedEnd 2736633 != 2736653
    at fetchWeakSubjectivityState (file:///opt/lodestar/packages/cli/src/networks/index.ts:177:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at fetchWSStateFromBeaconApi (file:///opt/lodestar/packages/cli/src/cmds/beacon/initBeaconState.ts:185:35)
    at Object.beaconHandler [as handler] (file:///opt/lodestar/packages/cli/src/cmds/beacon/handler.ts:60:41)
```

**Expected behavior**

Lodestar should be able to sync from a checkpoint on the Gnosis network

**Steps to Reproduce**

I run a Nethermind node on localhost and used the following to start lodestar:

```
./lodestar beacon  \
  --network=gnosis \
  --execution.urls=http://10.1.10.93:8551 \
  --jwt-secret=/var/opt/lodestar/jwt.hex  \
  --checkpointSyncUrl=https://checkpoint.gnosischain.com/
```

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04
- Version: Both 1.7.0 and 1.7.1

**Comment by SpeakinTelnet** [comment]
So upon further testing I was able to start syncing from https://checkpoint.gnosischain.com using v1.6.0/efe28ce. Same startup command. Still don't know why 1.7.1 would fail though.

**Comment by nflaig** [comment]
@SpeakinTelnet we broke gnosis in our 1.7.0 release but already got a fixed merged for that https://github.com/ChainSafe/lodestar/pull/5324. We will likely do another patch release with which includes that fix. For now, running v1.6.0 is the only option.

**Comment by SpeakinTelnet** [comment]
Thank you, just tested with the unstable branch and it worked! I'll close this issue.

**Comment by nflaig** [comment]
@SpeakinTelnet Great! thanks for testing, the release is already being prepared so should be out soon

**Comment by nflaig** [comment]
[v1.7.2](https://github.com/ChainSafe/lodestar/releases/tag/v1.7.2) has been released

**Comment by SpeakinTelnet** [comment]
@nflaig Thanks a lot! Appreciate the quick turnaround.
