### ISSUE TITLE
Document getting flamechart of live node

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#5341]
To understand what's affecting Lodestar performance our current strategy is to attach a chromium dev tools instance into a node running with `node --inspect`

Those dev tools can render a stack chart by time, but not a regular flamechart by purely stack occurrences. The information exposed by `node --inspect` _should_ be enough to produce a flamechart.

CC: @matthewkeil @nflaig @tuyennhv 

- [x] Research existing tools that can produce and render a flamechart attaching into a running process; i.e. run process as normal for 1 hour, then capture stacks for 12 minutes, then detach.
- [x] Write reproducible steps + scripts for other contributors

**Comment by nflaig** [comment]
could give [node-clinic](https://github.com/clinicjs/node-clinic) a try, specifically [node-clinic-flame](https://github.com/clinicjs/node-clinic-flame)

flame graph looks like this

![image](https://user-images.githubusercontent.com/38436224/229855183-3150ea12-61d5-4803-b9d1-59ebc678b699.png)

**Comment by dapplion** [comment]
Can it attach to a process live after N time? Docs I've seen appear to capture flamecharts on entire process lifetime

**Comment by nflaig** [comment]
Based on the `clinic flame` flags I don't see an option to do that.

Can be used programmatically as well, then could just call `flame.collect` after N time, see [node-clinic-flame docs](https://github.com/clinicjs/node-clinic-flame#documentation). 

Might have to use [0x](https://github.com/davidmarkclements/0x) directly to get more fine-grained control as this seems to have a `--collect-delay` flag (Specify a delay(ms) before collecting data).

**Comment by matthewkeil** [comment]
All of the libraries I found seem to want to run the node process directly and cannot be turned on and then off again programatically.  After a bit of googling I found [this blog](https://betterprogramming.pub/create-a-flame-graph-for-your-node-app-profiling-nodejs-app-e0a91e5ed585) and noted the flags.  I looked at the `Ox` code and found a few things to better understanding how that library works.

It looks like they are running the process [here](https://github.com/davidmarkclements/0x/blob/8d34f06bce33c287e6e50ee602ef4b1b55175101/platform/v8.js#L27) and [here](https://github.com/davidmarkclements/0x/blob/8d34f06bce33c287e6e50ee602ef4b1b55175101/platform/linux.js#L41) depending on if they are profiling v8 or linux.  

For v8 they are out-putting the isolate data to a log. Then then parse the data into `tick`s [here](https://github.com/davidmarkclements/0x/blob/8d34f06bce33c287e6e50ee602ef4b1b55175101/platform/v8.js#L128) to build the graph data.

For linux they are launching using a system level perf command and passing `--perf-basic-prof` and then turn the trace into `tick`s [here](https://github.com/davidmarkclements/0x/blob/8d34f06bce33c287e6e50ee602ef4b1b55175101/platform/linux.js#L105)

~~Sadly in both situations they use a flag to output perf data.  I am doing a bit more digging to see how it is implemented to try and understand if/what the performance implications will be.~~

There are [4 perf flags](https://github.com/nodejs/node/blob/4166d40d0873b6d8a0c7291872c8d20dc680b1d7/doc/api/cli.md?plain=1#L1964-L1973) that are available and the [node flamegraph docs](https://nodejs.org/en/docs/guides/diagnostics-flamegraph) talk about a few of the details.

I am reading about the [Chrome Debugging Protocol](https://chromedevtools.github.io/debugger-protocol-viewer/v8/) docs that were referred to in the [debugger](https://nodejs.org/en/docs/guides/debugging-getting-started) section of the node docs to see how the protocol works so we can potentially leverage the flag

Updated. ~~I am guessing there will be some degradation so it might not be ideal for prod but will add another comment below when I get further~~

I researched the performance implications of the `--inspect` flag and there is none when a debugger is not attached.  However, when one is attached it is 100x to 300x according to [this thread](https://stackoverflow.com/questions/45379080/does-the-node-inspect-flag-have-any-notable-performance-impact) on SO.

[This post](https://stackoverflow.com/questions/59743800/is-it-a-good-idea-to-enable-inspect-for-nodejs-in-production-kubernetes) elaborates a bit on the security risks but it also mentions that debugging can be flipped on with `kill -usr1 ${PID}` but I have not tested.

**Comment by matthewkeil** [comment]
During my journey I found an interesting video...
https://www.youtube.com/watch?v=Xb_0awoShR8&t=570s

Updated. The speaker talks about `process._debugProcess(pid)` to turn on debugging from outside of a running node instance.  It is what node uses [under the hood](https://github.com/nodejs/node/blob/4166d40d0873b6d8a0c7291872c8d20dc680b1d7/lib/internal/debugger/inspect.js#L319) to turn on debugging incidentally. It and [_debugEnd](https://github.com/nodejs/node/blob/4166d40d0873b6d8a0c7291872c8d20dc680b1d7/lib/internal/bootstrap/switches/is_main_thread.js#L13) are available. 

This is another highlight
https://youtu.be/Xb_0awoShR8?t=682

Updated. The speaker talks about the core debugging protocol and using it for profiling.  See the links below for more detail:
https://nodejs.org/dist/latest-v18.x/docs/api/inspector.html#cpu-profiler
https://chromedevtools.github.io/devtools-protocol/v8/Profiler/

starting to get somewhere notable I think 😄

**Comment by matthewkeil** [comment]
@dapplion I also found the reference that I mentioned on standup, it is a youtube video. It wasn't a blog is why I couldn't find with a google search.  It is a Netflix engineer talking about flame graphs on running node process in prod.

The speaker talks about the `--perf` flags mentioned above in [this video here](https://youtu.be/O1YP8QP9gLA?t=477) and in particular the usage for `--perf-basic-prof-only-functions` to generate the flamegraph. He mentions that it is very low impact on the running process.

They are using a linux library [perf](https://perf.wiki.kernel.org/index.php/Main_Page) and describe how they implement [here](https://youtu.be/O1YP8QP9gLA?t=402).  It is the same library that `Ox` is using for linux.

Netflix is using [brendangregg/FlameGraph](https://github.com/brendangregg/FlameGraph) to generate the flamegraphs.  `Ox` is using a custom implementation that [renders](https://github.com/davidmarkclements/0x/blob/8d34f06bce33c287e6e50ee602ef4b1b55175101/lib/render.js) and bundles an html page that is [in source](https://github.com/davidmarkclements/0x/tree/8d34f06bce33c287e6e50ee602ef4b1b55175101/visualizer).

As a note there was some GREAT other stuff in that video about post mortem debugging with core-dumps that was very interesting.  The whole video is def worth watching.

**Comment by matthewkeil** [comment]
@dapplion checkout a branch diff [here](https://github.com/ChainSafe/lodestar/compare/unstable...mkeil/flamegraph) that has an idea for how to generate the stack traces.  I talked with @Faithtosin about strategies to collect the flamegraph data when not running locally.  Please tell me what you think.

@Faithtosin was asking me about the scope for where and when you would like to run this?  Is it just something contributors will want to run on the cloud nodes or should it run locally?  I have had challenges running on mac.  I have only tried to catch OS level and not v8 level on mac though to mimic what happens on linux

**Comment by dapplion** [comment]
@tuyennhv captures CPU profiles regularly to ensure Lodestar performance profile is good, i.e. So we usually:
- Capture CPU profiles every 2 weeks on latest unstable to understand what's the next target for optimization
- Capture CPU profiles on feature branches to ensure they don't introduce visible regressions

So we always run on demand on specific machines. The goal here it to make it easier so we do it more often. But I'm not sure we should bake it into production code, sounds more like a job for external tooling

It should be run on our test nodes in the cloud

**Comment by matthewkeil** [comment]
@dapplion I added as many references that I could [here](https://github.com/matthewkeil/flamegraph/blob/main/doc/implementation-notes.md). It has most of the breadcrumbs that I found and the libraries that I seriously considered (and looked through the code).  The rest that came up by searching were either not widely used (less that 100 installs weekly) or were very old and hadn't had a commit since 2017
