### ISSUE TITLE
Info log validator index when publishing attestations

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#5346]
**Description**

Currently, there is no info log indicating which validator published an attestation. We just log `info: Published attestations slot=6156403, count=1` since we publish all attestation for the slot at once.

There is a debug log `Signed attestation...` which included the validator index but it's not on info level and enabling the debug logs includes tons of others logs which might not be desired.

Either we can add a feature flag to VC to log the validator index (separate log per published attestation) and/or we implement solution proposed in https://github.com/ChainSafe/lodestar/issues/5336 would log published attestations with validator index on BN side.

**Related**

- https://discord.com/channels/593655374469660673/593655641445367808/1093170377598976072

**Comment by dapplion** [comment]
Please keep in mind that some vc deployments run many keys. Dumping all indexes is too much. Also if you run one key it would be redundant information. This feature seems appealing for medium operators running a few keys. Do other clients do that by default at the info level?

**Comment by philknows** [comment]
Also curious whether other clients will log the index each time if there's one key. I feel like there needs to be some minimum validator threshold for this to be useful? We all like simplicity and cleanliness but there have been times where I feel that this could've been useful for debugging issues when there was > 1 key.

**Comment by nflaig** [comment]
I guess we can all agree that it won't work to have this enabled by default. Adding it to debug also does not make much sense since we already have a log for signing which includes the index and nothing really happens after that until publish so we can assume if a validator successfully signed that it will be published, unless publish runs into an error but would see that log as well.

As this was a feature request by a user we can keep this open as discussion. I rather see this implemented on BN when validator monitor logs are enabled (https://github.com/ChainSafe/lodestar/issues/5336), this also has the advantage that you have a combined view of all your validators if running multiple VCs with a single BN which a lot of users do that have a solo staking setup + rocket pool where you run only a VC in the RP stack (or vice versa).

**Comment by philknows** [comment]
There definitely seems to be more value for it on the BN side. At least for larger node operators, it would lead me to which VC cluster connected is having some sort of issue.

**Comment by nflaig** [comment]
Detailed attestation information can be printed out on the beacon node side at info level if `--validatorMonitorLogs` is set
- https://github.com/ChainSafe/lodestar/pull/6009
