### ISSUE TITLE
High mcache miss rate

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5352]
**Describe the bug**

This is from a test mainnet node subscribing to all subnets.

After #5350 there are high percentage (50% - 75%) of mcache miss, most of them are gossip attestation messages

<img width="803" alt="Screenshot 2023-04-09 at 15 20 18" src="https://user-images.githubusercontent.com/10568965/230762175-f18574bd-a0cc-4037-b14c-a141da86ebf6.png">

So even lodestar was able to process more gossip attestations, it could indicate some waste time because attestations are not processed fast enough to forward to peers

**Expected behavior**

If a message is validated and processed at lodestar, it 's expected to contribute to the network. In the case of gossip attestation messages:
- A lot of messages are not spread to the network
- Some attestations' job wait time is up to 12s which is not beneficial to the aggregation
<img width="889" alt="Screenshot 2023-04-09 at 15 24 54" src="https://user-images.githubusercontent.com/10568965/230762372-0432a3dc-52eb-427b-8910-67996644a2ca.png">

we should improve the performance of gossip validation or increase mcache history (which could make us different from the spec) or it could indicate some waste time processing these messages and then cannot forward to the network due to gossipsub's mcache history is configured as 6 * 0.7s(per heartbeat) = 4.2s per spec. Notice that lodestar also experience I/O lag issue due to more attestations being processed.

cc @dapplion

**Comment by dapplion** [comment]
Let's focus first on understanding the high job process time and addressing it. I'm sure there are multiple optimizations possible we can leverage.

**Comment by twoeths** [comment]
<img width="1292" alt="Screenshot 2023-08-20 at 13 28 21" src="https://github.com/ChainSafe/lodestar/assets/10568965/b8ce4214-d7fc-4283-b4d8-ef20e1862a42">

not an issue with v1.10.0, this is stable mainnet node
