### ISSUE TITLE
Validator db read/write ops too high on first startup with empty db

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#5356]
**Describe the bug**

Validator db read/write ops too high on first startup with empty db which causes I/O lag and instability in VC. After one or two hours the process stabilizes and read/write ops per second drastically decrease.

**Expected behavior**

VC should not be unstable for one or two hours if started with an empty db.

**Steps to Reproduce**

Run VC with a lot of keys (500+) and make sure validator-db is empty. If VC was active before and db was removed, be careful to not get slashed as this also removes the slashing protection db.

**Metrics**

![image](https://user-images.githubusercontent.com/38436224/231142907-383ff81c-c90f-424f-bb06-d7956d389ca9.png)

![image](https://user-images.githubusercontent.com/38436224/231146316-e59d1ad1-1b11-46e2-b803-16f3b557b36e.png)

![image](https://user-images.githubusercontent.com/38436224/231146425-b146d21c-1157-4342-84e3-3b2db3db7843.png)

**Comment by dapplion** [comment]
Can you paste the promquery code for the first metrics screen capture?

**Comment by nflaig** [comment]
I just changed the prom query to use the vc metrics, the rate interval is 1m, would probably have to add bucket labels to further investigate

- `rate(validator_db_read_items_total[$rate_interval])` (top left)
- `rate(validator_db_write_items_total[$rate_interval])` (top right)
- `rate( validator_db_read_req_total [$rate_interval])` (bottom left)
- `rate( validator_db_write_req_total [$rate_interval])` (bottol right)

**Comment by nflaig** [comment]
@dapplion I found the problem, the huge amount of read/writes it due to [minMaxSurround.ts](https://github.com/ChainSafe/lodestar/blob/05c93ba85a4b801c3f220d498e3ddaf45f968536/packages/validator/src/slashingProtection/minMaxSurround/minMaxSurround.ts). `this.maxEpochLookback` is set to `Infinity` meaning [unitlEpoch](https://github.com/ChainSafe/lodestar/blob/05c93ba85a4b801c3f220d498e3ddaf45f968536/packages/validator/src/slashingProtection/minMaxSurround/minMaxSurround.ts#L32) will always be `0`. This results in a [db read](https://github.com/ChainSafe/lodestar/blob/05c93ba85a4b801c3f220d498e3ddaf45f968536/packages/validator/src/slashingProtection/minMaxSurround/minMaxSurround.ts#L36) and a [bulk write](https://github.com/ChainSafe/lodestar/blob/05c93ba85a4b801c3f220d498e3ddaf45f968536/packages/validator/src/slashingProtection/minMaxSurround/minMaxSurround.ts#L44) for each validator pubkey from current epoch until genesis.

![image](https://user-images.githubusercontent.com/38436224/234672794-fcdda2f9-f3c9-4efa-8775-473254134dba.png)

I have to dig into how min-max surround works, likely need to use another value for `maxEpochLookback`.

**Comment by nflaig** [comment]
Based on [Detecting slashing conditions](https://hackmd.io/@n0ble/By897a5sH), it seems like `maxEpochLookback` only needs to be the number of epochs in weak subjectivity period. More details in  [Scanning for surrounding votes](https://hackmd.io/@n0ble/By897a5sH#Scanning-for-surrounding-votes) section.

**Comment by nflaig** [comment]
Slashers default to a period of [4096 epochs](https://lighthouse-book.sigmaprime.io/slasher.html#history-length), which means could be fine to only set `maxEpochLookback` to that period. They might still collect slashable attestations over a longer period, meaning limiting the max lookback might be riksy when using min-max approach.

Maybe could consider setting `maxEpochLookback` to a practically safe enough value to fix the I/O issue for now.

 Alternative would be to implement a different slashing protection strategy like "minimal"/high-watermark strategy as suggested in [Eth R&D discord](https://discord.com/channels/595666850260713488/598292067260825641/1101646917366198272).

**Edit:** It looks like this strategy is also already implemented on top of min-max surround
https://github.com/ChainSafe/lodestar/blob/b60b43c1eb4b918b7641c32c49d5271b90d1a685/packages/validator/src/slashingProtection/attestation/index.ts#L99-L103

**Comment by dapplion** [comment]
Setting maxEpochLookback to 4096 sounds sensible. We can do that plus using the minimal strategy. That has the benefit of producing way smaller exports right?

**Comment by nflaig** [comment]
> That has the benefit of producing way smaller exports right?

No, the slashing export size just depends on data in `AttestationByTargetRepository`, min-max spans are not exported. Setting maxEpochLookback to 4096 would fix the I/O issue and also massively reduce the validator db size. Right now we are creating ~200k (mainnet epochs) min span records per pubkey.

> Setting maxEpochLookback to 4096 sounds sensible.

I think a better value would be weak subjectivity period epochs but we don't have access to that on the VC side. All of these values are quite theoretical though, so might also be fine with 4096 and possibly allow to override via CLI.

**Comment by nflaig** [comment]
> That has the benefit of producing way smaller exports right?

Actually, right now it even affects the size of the slashing protection but this is a bug which will be fixed with https://github.com/ChainSafe/lodestar/pull/5437, it loads keys from other buckets which are not valid pubkeys, for those there will not be any `signed_blocks` or `signed_attestations` but still adds records to slashing protection.

The empty records with invalid pubkeys look like this

```json
{
  "pubkey": "0x47454e455349535f54494d45",
  "signed_blocks": [],
  "signed_attestations": []
},
{
  "pubkey": "0x47454e455349535f56414c494441544f52535f524f4f54",
  "signed_blocks": [],
  "signed_attestations": []
}
```
