### ISSUE TITLE
Upgrade to libp2p/tcp 6.1.5

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#5362]
For our upgrade to @libp2p/tcp 6.1.5 we:

- [ ] Require upgrade libp2p to 0.43.4
- [ ] Require upgrade to multiformat/multiaddr 12.x 
- [ ] Update libp2p/tcp

This issue tracks the updates for Lodestar to upgrade to the latest releases for networking.

**Comment by twoeths** [comment]
closing the issue as we're at @libp2p/tcp@7.0.1 after https://github.com/ChainSafe/lodestar/pull/5506
