### ISSUE TITLE
High rate of rejected voluntary exits

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5371]
**Describe the bug**

Sometimes there are high rate of rejected voluntary exit on mainnet

<img width="1294" alt="Screenshot 2023-04-18 at 11 45 46" src="https://user-images.githubusercontent.com/10568965/232673756-0c95e334-d562-46d4-8f0c-4ffc29dc022b.png">

this happens more frequently on our test mainnet nodes

Right now it's likely we don't use correct state to validate a voluntary exit https://github.com/ChainSafe/lodestar/blob/3ee1d8a5acb09160827b185c79d2ead80442c0e7/packages/beacon-node/src/chain/validation/voluntaryExit.ts#L25

Due to that it may affect gossip score p4 params

**Expected behavior**

- Low rate or 0% rejected voluntary exits on mainnet
- May use state at VoluntaryExit's epoch (may use a metric to see epoch difference against current epoch). Make sure it does not effect performance of our regen module

**Desktop (please complete the following information):**

- Version: v1.7.2

**Comment by dapplion** [comment]
> Right now it's likely we don't use correct state to validate a voluntary exit 

What is the correct state to validate exits according to the spec?

Can you figure out from metrics or Loki logs the reason why those exits are invalid

**Comment by twoeths** [comment]
the spec doesn't mention the correct state. Just double check, the state we use is good based on this comment:

```
// The only condition that is time sensitive and may require a non-head state is
  // -> Validator is active && validator has not initiated exit
  // The voluntaryExit.epoch must be in the past but the validator's status may change in recent epochs.
  // We dial the head state to the current epoch to get the current status of the validator. This is
  // relevant on periods of many skipped slots.
```
the validator_exit is rejected maybe because we hold the message for too long, up to 4 epochs

<img width="1407" alt="Screenshot 2023-04-22 at 13 21 56" src="https://user-images.githubusercontent.com/10568965/233766573-40777382-0a66-4a51-9ffa-bce027e726a4.png">

- I'm not sure rejecting messages are suitable although that's what the spec said, it's our bad holding the message for too long not the peer
- @dapplion since we have few voluntary exit, should we prioritize `voluntary_exit` topic over `beacon_attestation` topic?
