### ISSUE TITLE
Automatically debug missed attestations

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#5376]
While our fleet performance is pretty good there are still some missed attestations sometimes. Some of them are caused by external factors, other for internal ones.

A beacon node has enough information to do a fairly good guess of why an attestation was missed. Usually @tuyennhv performs that process manually but it should be feasible to automate it as part of the validator monitor. That would help us focus efforts and quantitatively measure our efforts in improving Lodestar's performance.

A possible mechanism for this:
- After 32 slot (or some safe reorg distance) observe which validators where expected to attest and if the did so
- If the state claims a missed attestation check:
  - has the attestation been seen?
  - has the attestation been published late?
  - how many peers was the attestation published to?
  - was the attestation seen as part of an aggregate?
  - Is the attestation voting for the correct head and target?

**Comment by philknows** [comment]
I think we should prioritize this within the next couple of releases as we frequently get reports from solo/external stakers using Lodestar and it becomes increasingly difficult to manage with all the variations in people's setup and circumstances.
