### ISSUE TITLE
ReqResp encoded bytes API 

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#5378]
- Issue https://github.com/ChainSafe/lodestar/pull/5229 would benefit greatly from ReqResp dealing with non deserialized SSZ data structures

Since ReqResp requests and responses must cross the worker boundary it's best to just wait to de-serialize them on the main thread. For it the API exposed by the reqresp package must deal exclusively with Uint8Array instead of T representing the deserialized object. For reference of how the API should look like PR https://github.com/ChainSafe/lodestar/pull/5229 is quasi complete reference.

**Comment by nazarhussain** [comment]
Based on discussion with @wemeetagain came up with this diagram to align the understanding for everyone. 

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/112468/235259649-b576b8a0-2aea-4392-8ca6-97bc7b2eba72.png">
