### ISSUE TITLE
High regen queue job wait time

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5384]
**Describe the bug**

With the new gossip flow, the Job Wait Time of regen queue is almost 1s, this is likely one of the reason of I/O lag issue

<img width="1306" alt="Screenshot 2023-04-19 at 13 32 46" src="https://user-images.githubusercontent.com/10568965/232986401-ab0fdc99-d051-4e5e-ad0c-4260075598d4.png">

right now the regen queue length is limited to 16 to accept new gossip work

<img width="1287" alt="Screenshot 2023-04-19 at 13 34 43" src="https://user-images.githubusercontent.com/10568965/232986769-d808bc8c-a74a-4b70-89e1-4f528162c339.png">

**Expected behavior**

- This is from stable (v1.7): regen queue is only 1 or 0 and job wait time is way lower
<img width="1291" alt="Screenshot 2023-04-19 at 13 40 31" src="https://user-images.githubusercontent.com/10568965/232987994-c2864af0-d3cb-4a65-b238-0e1a7a1b989c.png">

<img width="1292" alt="Screenshot 2023-04-19 at 13 40 52" src="https://user-images.githubusercontent.com/10568965/232988070-acc1c838-5c4a-495d-9c63-237667c27f1b.png">

**Question**
- We have a state cache of 96 items, why are there some attestations with block head not in that cache, is it worth to always regen them? maybe we should skip some of them, see https://github.com/ChainSafe/lodestar/blob/3ee1d8a5acb09160827b185c79d2ead80442c0e7/packages/beacon-node/src/chain/validation/attestation.ts#L139
- Consider reducing REGEN_CAN_ACCEPT_WORK_THRESHOLD (right now it's 16) cc @dapplion

**Comment by twoeths** [comment]
when I zoom in, some Job Wait Time is > 4s which is too big

<img width="1287" alt="Screenshot 2023-04-19 at 15 00 19" src="https://user-images.githubusercontent.com/10568965/233008742-20fdf910-d821-4db8-9d46-5517b7c7857a.png">

**Comment by dapplion** [comment]
@tuyennhv for this type of metric is best to capture the histogram to understand the real distribution of values through a longer timeframe. That would allow to answer the question: what % of regen jobs over a day take > 1s

**Comment by twoeths** [comment]
@dapplion it's about 25% of them take >1s

<img width="1321" alt="Screenshot 2023-04-20 at 11 16 35" src="https://user-images.githubusercontent.com/10568965/233256763-910e7d60-496b-455a-bb57-3d4916738639.png">

this issue happens randomly on stable mainnet node but more consistently on unstable mainnet node (could be because unstable likely validate all attestations with the new gossip)

**Comment by twoeths** [comment]
Sometimes `getBlockSlotState()` call of `precomputeEpoch` takes up to 3s

<img width="794" alt="Screenshot 2023-04-20 at 16 09 57" src="https://user-images.githubusercontent.com/10568965/233318119-7bd5f745-b556-4070-a43c-ea1c576f65cf.png">

<img width="799" alt="Screenshot 2023-04-20 at 16 10 05" src="https://user-images.githubusercontent.com/10568965/233318154-adf78a1f-dbf9-4a06-87da-7325f69190de.png">

<img width="822" alt="Screenshot 2023-04-20 at 16 10 19" src="https://user-images.githubusercontent.com/10568965/233318199-35ef2ad9-7003-4b58-9885-77fd7ec65772.png">

update: should investigate the long epoch transition in https://github.com/ChainSafe/lodestar/issues/5409

**Comment by twoeths** [comment]
Latest 1h chart in the last 24h in unstable mainnet node:

<img width="792" alt="Screenshot 2023-04-25 at 05 08 40" src="https://user-images.githubusercontent.com/10568965/234127255-ced12188-8268-46c7-8e87-27d4ba5f02df.png">

vs stable mainnet node

<img width="803" alt="Screenshot 2023-04-25 at 05 09 16" src="https://user-images.githubusercontent.com/10568965/234127339-2f578de4-fb8e-41f5-8ee3-342a32efc685.png">
