### ISSUE TITLE
v1.7: High block processor queue job time

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5391]
**Describe the bug**

On test mainnet node (stable), sometimes the block process time is very high (this is 1m chart)

<img width="1282" alt="Screenshot 2023-04-20 at 15 44 15" src="https://user-images.githubusercontent.com/10568965/233311243-f7a603e9-fed5-4f21-a879-4e0f9aca7b81.png">

It's up to 10% of blocks have process time >1s

<img width="1280" alt="Screenshot 2023-04-20 at 15 47 38" src="https://user-images.githubusercontent.com/10568965/233312099-b947eaf7-b115-496d-9f49-abe6f5326555.png">

This happens more frequently with `unstable` branch
<img width="1317" alt="Screenshot 2023-04-20 at 15 48 44" src="https://user-images.githubusercontent.com/10568965/233312397-2c87bcc6-5764-4696-994d-b1ad2ee3c6f2.png">

**Expected behavior**

Should be <1s consistently

**Desktop (please complete the following information):**

- Version: v1.7

**Comment by twoeths** [comment]
This is mainly the `notifyNewPayload` execution engine call 

<img width="1318" alt="Screenshot 2023-04-20 at 16 02 33" src="https://user-images.githubusercontent.com/10568965/233316150-20e4315e-96fe-4229-baa7-055dd9060ca4.png">

Percentage of `notifyNewPayload` call >1s

<img width="1303" alt="Screenshot 2023-04-20 at 16 03 34" src="https://user-images.githubusercontent.com/10568965/233316399-a0978215-367e-4c7e-a9a0-0da88203d57e.png">

This is not likely the Execution Engine issue, it's the I/O lag issue of lodestar happening mostly on a test mainnet node subscribing to all subnets

**Comment by dapplion** [comment]
Metrics captured from unstable mainnet geth metrics

```
# TYPE rpc_duration_engine_newPayloadV2_success summary
rpc_duration_engine_newPayloadV2_success {quantile="0.5"} 104116.5
rpc_duration_engine_newPayloadV2_success {quantile="0.75"} 132396.75
rpc_duration_engine_newPayloadV2_success {quantile="0.95"} 225751.89999999988
rpc_duration_engine_newPayloadV2_success {quantile="0.99"} 364260.3900000002
rpc_duration_engine_newPayloadV2_success {quantile="0.999"} 1.0846435890000006e+06
rpc_duration_engine_newPayloadV2_success {quantile="0.9999"} 1.090077e+06
```
The 99 percentile time is 350ms so yes, the 5% figure we observe over 1 second is Lodestar's fault most likely

**Comment by twoeths** [comment]
same chart on v1.10.0

<img width="1305" alt="Screenshot 2023-08-20 at 13 18 16" src="https://github.com/ChainSafe/lodestar/assets/10568965/555df72d-6a3d-4592-94e7-e9d14635daf9">

closing the issue
