### ISSUE TITLE
Lodestar generates invalid enr on docker network mode shared

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#5397]
While doing debugging for the peering for 4844 devnet5 with lodestar as bootnode, it was figured that lodestar couldn't seem to generate the correct ENR most probably because Network mode was `shared`

Flags to start lodestar (from docker inspect) :```
"Args": [
            "./packages/cli/bin/lodestar",
            "beacon",
            "--dataDir=/data",
            "--listenAddress=0.0.0.0",
            "--port=9000",
            "--enr.ip=188.166.69.205",
            "--enr.tcp=9000",
            "--rest",
            "--rest.address=0.0.0.0",
            "--rest.port=5052",
            "--jwt-secret=/execution-auth.jwt",
            "--execution.urls=http://ethereumjs:8551",
            "--metrics",
            "--metrics.address=0.0.0.0",
            "--metrics.port=5054",
            "--paramsFile=/network-config/config.yaml",
            "--genesisStateFile=/network-config/genesis.ssz",
            "--network.connectToDiscv5Bootnodes"
        ],
```

generated ENR: ```
enr:-LW4QFTTz_3Q-tVJJRaRUp1LY2eiS5ySkEz_iwwu9C8CQq87NoM5lj7nMGUU60qjBTB7qp2OdXSPGyRGUen_CxyaaAQLh2F0dG5ldHOIAAAAAAAAAACEZXRoMpBSRrDJQEhEBf__________gmlkgnY0iXNlY3AyNTZrMaEDhKvBbQfO2xcsGxsvMq1zpluaUfXhgASnmxlEqH5BNumIc3luY25ldHOIAAAAAAAAAACDdGNwgiMo
```

enr viewer:
![image](https://user-images.githubusercontent.com/76567250/233648339-181dea60-c98c-47b5-a75d-a44b3d70969e.png)

Expected results: ENR should have correct, ip, udp and multiaddrs and peers should be able to connect

cc @skylenet, @parithosh

**Comment by skylenet** [comment]
So this happens on the case of a node that is behind NAT. Currently it seems impossible to announce an IP address that the process isn't seeing on the network interfaces. 

There is another related issue that we discovered some time ago on our kubernetes cluster, where the lodestar processes are also running in containers behind NAT: https://github.com/ChainSafe/lodestar/issues/3462

**Comment by wemeetagain** [comment]
Issue is here https://github.com/ChainSafe/lodestar/blob/e746f9cae45a8b7bb0f51e1400c985c64b189c21/packages/beacon-node/src/network/nodejs/util.ts#L36-L38

**Comment by g11tech** [comment]
thanks @skylenet  for the insights, yes most likely this is the case as we do a cleanup if we scan local interfaces and cleanout ip/udp/multiaddrs if we can't find it:

https://github.com/ChainSafe/lodestar/pull/1192

We will need to figure out how what is the best strategy here, but nodes running behind NAT is not uncommon

**Comment by g11tech** [comment]
@wemeetagain should we have a NAT ip cli arg? it will also provide a way to around the edge cases of us not being able to scan the interfaces

**Comment by wemeetagain** [comment]
> should we have a NAT ip cli arg?

Yeah, like you said its not uncommon. I'd suggest we have a `--nat` cli flag defaulted to false that can prevent the `isLocalMultiAddr` check.
