### ISSUE TITLE
Lighthouse BN subnet discovery warnings when running with Lodestar VC

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#5418]
### Lighthouse BN

At the beginning of the epoch the Lighthouse BN logs the following warning when running with Lodestar VC (likely only if there are duties for the first 2 slots)

```
WARN Not enough time for a discovery search  subnet_id: ExactSubnet { subnet_id: SubnetId(4), slot: Slot(6300288) }, service: attestation_service
WARN Not enough time for a discovery search  subnet_id: ExactSubnet { subnet_id: SubnetId(1), slot: Slot(6300288) }, service: attestation_service
```

On the Lighthouse BN there is a check that a [subnet slot must be greater than or equal the current slot + 2](https://github.com/sigp/lighthouse/blob/693886b94176faa4cb450f024696cb69cda2fe58/beacon_node/network/src/subnet_service/attestation_subnets.rs#L491-L493) or otherwise it will [log the warning](https://github.com/sigp/lighthouse/blob/693886b94176faa4cb450f024696cb69cda2fe58/beacon_node/network/src/subnet_service/attestation_subnets.rs#L509-L512) and not attempt to discover peers for the subscription.

As noted in Lighthouse [`MIN_PEER_DISCOVERY_SLOT_LOOK_AHEAD`](https://github.com/sigp/lighthouse/blob/693886b94176faa4cb450f024696cb69cda2fe58/beacon_node/network/src/subnet_service/attestation_subnets.rs#L29):

> The minimum number of slots ahead that we attempt to discover peers for a subscription. If the
   slot is less than this number, skip the peer discovery process.
   Subnet discovery query takes at most 30 secs, 2 slots take 24s.

### Lodestar VC

Lodestar VC pushes out subscriptions for the current and next epoch (`current_epoch + 1`)

https://github.com/ChainSafe/lodestar/blob/05c93ba85a4b801c3f220d498e3ddaf45f968536/packages/validator/src/services/attestationDuties.ts#L177-L183

Resubscribing for the current epoch likely causes this warning, but due to the fact that the subscription are already done much earlier for this epoch (`current_epoch - 1`) it does not cause any issue, attestations and aggregations work as expected.

It needs to be investigated if resubscribing for the current epoch is correct, the [Lookahead](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/validator.md#lookahead) section in consensus spec notes that it should be called at the start of each epoch to get the assignment for the next epoch (`current_epoch + 1`).

Apparently the same happens when running Lighthouse BN with Teku VC, further investigation will be required.

### Related

From discord: https://discord.com/channels/593655374469660673/593655641445367808/1100407245403066561

**Comment by philknows** [comment]
we aren't planning to change, this is not a functional issue
