### ISSUE TITLE
Publish all attestations on the Beacon API Event stream

### ISSUE THREAD

**Issue by Savid** [ChainSafe/lodestar#5430]
**Is your feature request related to a problem? Please describe.**

It looks like only aggregated attestations from [block imports](https://github.com/ChainSafe/lodestar/blob/7af22d77957214a19481be18011f51c349e585d7/packages/beacon-node/src/chain/blocks/importBlock.ts#L155) are published on the [`/eth/v1/events`](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Events/eventstream) `attestation` topic. 

**Describe the solution you'd like**

Publish all attestations received from currently subscribed subnets on the [`/eth/v1/events`](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Events/eventstream) `attestation` topic.

**Additional context**

Currently we run multiple CL clients and collect attestation data. Would love to also include Lodestar as one of the sources! Apologies if I've missed a CLI flag somewhere and this is already implemented. I also understand there could potential performance issues in implementing this. Thanks

**Comment by dapplion** [comment]
Hey @Savid happy to align Lodestar to other CL implementations. From your experience, do other clients emit attestation events for attestations received either via:
- block import
- gossip aggregated topic
- gossip unaggregated topic
- API post aggregated
- API post unaggregated

**Comment by Savid** [comment]
Awesome @dapplion! I only have experience from gossip/block imports as I haven't tested API. All other CL implementations are at least publishing gossip/block import attestations. 
Naively I would say all of the items you listed are applicable; [`The node has received a valid attestation (from P2P or API)`](https://github.com/ethereum/beacon-APIs/blob/f087fbf2764e657578a6c29bdf0261b36ee8db1e/apis/eventstream/index.yaml#L56), but selfishly I only require gossip/block import.
