### ISSUE TITLE
Implement Attnet revamp - Node-ID Based

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#5482]
- See https://github.com/ethereum/consensus-specs/pull/3312

There's no clear timeline yet on this. The change must be implemented to be backwards compatible so keep the eth2 field for a while.

**Comment by philknows** [comment]
Based on https://github.com/ethereum/consensus-specs/pull/3312#issuecomment-1548973273, it seems like Sig P is ready to startup a testnet with this change. Should we include it as part of a v1.9/1.10 release perhaps to ensure it doesn't get forgotten?

**Comment by wemeetagain** [comment]
Resolved with https://github.com/ChainSafe/lodestar/pull/5704
