### ISSUE TITLE
Teku VC doesn't recognize Lodestar BN is synced

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#5497]
**Describe the bug**

As mentioned by RockLogic in the Discord chat: https://discord.com/channels/593655374469660673/1077978309775863900/1106841372973092928

The Teku VC does not recognize the Lodestar BN v1.8.0 as synced.

**Expected behavior**

Teku VC should be able to detect when a Lodestar BN is synced.

**Comment by nflaig** [comment]
This issue seems to be resolved, Teku VC works pretty well now with Lodestar as beacon node. I can't point to any particular fix on either Teku or Lodestar but might be worth to check with RockLogic if they are still observing this.

**Comment by stefa2k** [comment]
Not observing this issue anymore, looks stable, thanks!

**Comment by nflaig** [comment]
Thanks for the confirmation @stefa2k!
