### ISSUE TITLE
Use proper state to verify attestations

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#5498]
- Now that we have https://github.com/ChainSafe/lodestar/pull/5390, we may be able to re-enable https://github.com/ChainSafe/lodestar/pull/4849
- use `maxSkipSlots` as the parameter to avoid regen rather than just using a state at the wrong epoch (expose via CLI too)
- related https://github.com/ChainSafe/lodestar/issues/4831

**Comment by twoeths** [comment]
I think we don't have to always dial to target epoch, if `targetEpoch - headBlockEpoch === 1` we can just use the state at `headBlock` thanks to 1 epoch look ahead (the `nextShuffling` in state). Teku had this same optimization https://github.com/ConsenSys/teku/pull/7142/files#diff-63983da705fcf1ea1194c2a3e3ee4ede93548b1b7658041bcf9a8d0b47f107b6L73

it means with `maxSkippedSlot=32` it's most likely we don't have to do epoch transition at all

one edge case is if `headBlock` and `targetEpoch` are in different forks (we're at fork transition) then we should dial to target epoch as specified in https://github.com/ChainSafe/lodestar/issues/4831
