### ISSUE TITLE
Logger child is not silenced

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#550]
When creating child instance of winston logger, silent property should be passed aswell

**Comment by aunyks** [comment]
What do you mean by child instance?

**Comment by wemeetagain** [comment]
@aunyks take a look at https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/logger/winston.ts#L101

We create `child` instances that are cheaper than creating entirely new loggers.

**Comment by aunyks** [comment]
Gotcha. Thanks for linking. I'll take it.
