### ISSUE TITLE
Lint and fix unused expressions

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#5505]
Need track of unused expressions to clean up the code and avoid potential bugs.

For example this was missed due to missing lint rule. The assertion error has never been added to the list of errors.

https://github.com/ChainSafe/lodestar/blob/c780a1d450b4def5b1c167f72507881dd9c10eb6/packages/cli/test/utils/simulation/assertions/defaults/missedBlocksAssertion.ts#L36-L42

- [x] add lint rule `"no-unused-expressions": "error"` ([no-unused-expressions](https://eslint.org/docs/latest/rules/no-unused-expressions), [@typescript-eslint/no-unused-expressions](https://typescript-eslint.io/rules/no-unused-expressions/)) 
- [x] clean up or fix issues

Could also consider adding other linters/scanners to CI such as [SonarQube](https://docs.sonarqube.org/latest/).

As discussed in [discord](https://discord.com/channels/593655374469660673/605818244036821012/1108460738672074856)

**Comment by philknows** [comment]
- related to #6011
