### ISSUE TITLE
More gossip broken promises due to network thread

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5508]
**Describe the bug**

This is from a test mainnet node 12h after we merge network thread work, there are lower peers with mesh threshold

<img width="798" alt="Screenshot 2023-05-18 at 10 47 17" src="https://github.com/ChainSafe/lodestar/assets/10568965/06a8d657-4603-452d-865e-0f2badbeedad">

this is mostly due to p7

<img width="790" alt="Screenshot 2023-05-18 at 10 47 42" src="https://github.com/ChainSafe/lodestar/assets/10568965/f01041aa-f556-4b35-b422-938160b59b03">

this is broken promise ratio
<img width="803" alt="Screenshot 2023-05-18 at 10 48 08" src="https://github.com/ChainSafe/lodestar/assets/10568965/9f2be7da-db32-48ae-9cda-8d9df9bcac75">

**Expected behavior**

Same broken promise ratio like with single thread mode

**Comment by twoeths** [comment]
looks like this correlates to number of Nimbus peers

<img width="1296" alt="Screenshot 2023-05-18 at 14 55 19" src="https://github.com/ChainSafe/lodestar/assets/10568965/a684eac1-b658-433c-9ba2-84f74c68723f">

also we start publishing to lightclient topics since we move network to worker thread

<img width="1593" alt="Screenshot 2023-05-18 at 14 58 40" src="https://github.com/ChainSafe/lodestar/assets/10568965/2cb2bb2f-d58e-497d-b9c1-0c6e9a9c45c6">

**Comment by twoeths** [comment]
there is also more late message delivery (this is monitored on beta mainnet node, v1.9.0-rc.0)

<img width="806" alt="Screenshot 2023-05-26 at 14 08 22" src="https://github.com/ChainSafe/lodestar/assets/10568965/ad525082-81de-40fa-8319-8eb38c7dd833">

**Comment by philknows** [comment]
Moving this one forward for milestones as we continue to debug gossip issues when enabling the network thread.

**Comment by twoeths** [comment]
this is a test mainnet node with `useWorker=true`, 2d chart

<img width="1289" alt="Screenshot 2023-08-20 at 13 42 12" src="https://github.com/ChainSafe/lodestar/assets/10568965/1be780b0-daf9-4591-970f-85735a28ffd4">

<img width="1292" alt="Screenshot 2023-08-20 at 13 44 41" src="https://github.com/ChainSafe/lodestar/assets/10568965/1ba65bc5-047b-42cd-a700-e8e12340fa94">

<img width="1298" alt="Screenshot 2023-08-20 at 13 47 14" src="https://github.com/ChainSafe/lodestar/assets/10568965/552366a4-2f2b-4314-8d35-ba870a2bac68">


vs unstable

<img width="1292" alt="Screenshot 2023-08-20 at 13 41 17" src="https://github.com/ChainSafe/lodestar/assets/10568965/7bd45f33-2209-4a56-8b04-fd14480fd850">

<img width="1294" alt="Screenshot 2023-08-20 at 13 45 11" src="https://github.com/ChainSafe/lodestar/assets/10568965/b8d11d8e-b23e-4e0b-b604-00b1a2ee67c4">

<img width="1289" alt="Screenshot 2023-08-20 at 13 47 35" src="https://github.com/ChainSafe/lodestar/assets/10568965/36c2e25c-9f0a-445c-b88f-bc5b63105a88">

it shows network thread has been improved and comparable or better than default mode (`useWorker=false`)
