### ISSUE TITLE
Investigate high block processor time

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5513]
**Describe the bug**

This is on a mainnet node, after capella block processor time is high for some blocks

<img width="1295" alt="Screenshot 2023-05-22 at 09 25 47" src="https://github.com/ChainSafe/lodestar/assets/10568965/d8dc0f51-08f3-4578-a30b-13704d4fa6ec">

is this due to high withdrawals on these blocks?

**Expected behavior**

- Track withdrawals per block in a metric
- If it's not due to withdrawals per block, add more metrics/debugs to figure out the reason
- Make sure block processor time is <100ms consistently

**Comment by dapplion** [comment]
@tuyennhv for this type of issues switch to heatmap and render the % of samples above a certain threshold. The timeline chart of average does not accurately signal the relevance of this issue

**Comment by twoeths** [comment]
@dapplion I get what you mean but this is 1m chart and since we have 12s between blocks and a scrape duration of 10s this chart shows good result to some degree in a very short time :). More over bucket for this metric jump from 0.1s to 1s so you'll see no issue there

on each node it shows high block process time on random slots, number of withdrawals are 16 most of the time it's not likely a performance issue in state transition code, could be `gc` runs during state transition

**Comment by twoeths** [comment]
this is not an issue in current `unstable` since network thread is in

<img width="1291" alt="Screenshot 2023-05-24 at 15 56 24" src="https://github.com/ChainSafe/lodestar/assets/10568965/3f1f42a8-c1d8-47eb-b1c4-a054c72221dc">

and we have way better `gc` metric

<img width="789" alt="Screenshot 2023-05-24 at 15 56 55" src="https://github.com/ChainSafe/lodestar/assets/10568965/a8ce0d35-bc4a-405b-9da9-a70c5969792e">

should be fixed in v1.9
