### ISSUE TITLE
v1.9.0-rc.0: Unstable peers

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5547]
### Describe the bug

Need more time to monitor, but seems like peers don't want to stay long with Lodestar v1.9.0-rc.0 (this is on a test mainnet node)

<img width="800" alt="Screenshot 2023-05-26 at 12 49 11" src="https://github.com/ChainSafe/lodestar/assets/10568965/9260b80b-7765-4ca4-8278-8094ded84a03">

<img width="1287" alt="Screenshot 2023-05-26 at 12 56 20" src="https://github.com/ChainSafe/lodestar/assets/10568965/0e5f1608-79ac-4d43-ad0e-9749296986cd">

more bad behavior reported due to dial error and timeouts

<img width="799" alt="Screenshot 2023-05-26 at 12 50 34" src="https://github.com/ChainSafe/lodestar/assets/10568965/104f701e-bbfa-42ef-b953-1ca279761df6">

more goodbye received
<img width="781" alt="Screenshot 2023-05-26 at 12 50 49" src="https://github.com/ChainSafe/lodestar/assets/10568965/22cdf8b1-dabb-4dc4-8f2f-0b6efce5f77c">

more incoming request handler errors and request/response roundtrip time

<img width="1585" alt="Screenshot 2023-05-26 at 12 53 03" src="https://github.com/ChainSafe/lodestar/assets/10568965/c9cf2b42-de12-4291-a1a8-e787b03d7134">

### Expected behavior

stable peers

### Steps to reproduce

- this happens on mainnet node only, don't see it happens to goerli nodes

### Operating system

Linux

### Lodestar version or commit hash

v1.9.0-rc.0

**Comment by twoeths** [comment]
our peers are banned very frequently, this is 7-day chart on different test mainnet nodes
- on beta (which is deployed 1-2 days)
<img width="1286" alt="Screenshot 2023-05-26 at 14 52 11" src="https://github.com/ChainSafe/lodestar/assets/10568965/42c05c19-18e2-41f4-af0f-f59cfd200a39">

- on unstable
<img width="1323" alt="Screenshot 2023-05-26 at 14 52 36" src="https://github.com/ChainSafe/lodestar/assets/10568965/32cc6b9b-a634-45b5-bf55-bedf0ebb8e90">

- on stable
<img width="1306" alt="Screenshot 2023-05-26 at 14 52 53" src="https://github.com/ChainSafe/lodestar/assets/10568965/d5dde0c3-a066-433b-a1c0-00a832eadfac">

**Comment by twoeths** [comment]
same monitor on topic peers per subnet
- beta (which was deployed 1-2 days ago)
<img width="1303" alt="Screenshot 2023-05-26 at 15 20 25" src="https://github.com/ChainSafe/lodestar/assets/10568965/909bac49-fa43-4e8c-b904-215ca98e56d9">

- unstable
<img width="1301" alt="Screenshot 2023-05-26 at 15 20 55" src="https://github.com/ChainSafe/lodestar/assets/10568965/a5e950db-61d6-476a-8ccb-c713e549464f">

- stable
<img width="1302" alt="Screenshot 2023-05-26 at 15 21 16" src="https://github.com/ChainSafe/lodestar/assets/10568965/ec4fc6d7-dc0a-4f37-b74d-1a56c4798ad3">

**Comment by twoeths** [comment]
there are some percentage of error incoming ping request

<img width="1304" alt="Screenshot 2023-05-30 at 11 35 11" src="https://github.com/ChainSafe/lodestar/assets/10568965/4dd473b5-b3c8-45ae-be71-aeaca8cf7bf7">

while in stable mainnet node we almost don't have this

**Comment by philknows** [comment]
Stale, metrics for v1.9.1 is already looking different.
