### ISSUE TITLE
v1.9.0-rc.0: Memory leak

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5549]
### Describe the bug

rss keeps going up on beta mainnet node

<img width="1295" alt="Screenshot 2023-05-26 at 16 01 45" src="https://github.com/ChainSafe/lodestar/assets/10568965/9739760e-2820-4a99-a83e-823de523371a">

### Expected behavior

expect it to be like stable mainnet node

<img width="1295" alt="Screenshot 2023-05-26 at 16 02 17" src="https://github.com/ChainSafe/lodestar/assets/10568965/1800328b-2c09-40cd-b9c6-104a59c89b42">

### Steps to reproduce

it also happens on all goerli beta nodes

### Operating system

Linux

### Lodestar version or commit hash

v1.9.0-rc.0

**Comment by twoeths** [comment]
looking in to `/proc/${pid}/maps` file and compare to `stable` mainnet node, 2 candidates I found

```
13939:7f9958600000-7f9958601000 r-xp 00000000 09:02 27007162                   /usr/src/lodestar/node_modules/utf-8-validate/prebuilds/linux-x64/node.napi.node   =======> 1st candidate
13961:7f9958a00000-7f9958a02000 r-xp 00000000 09:02 26935736                   /usr/src/lodestar/node_modules/bufferutil/prebuilds/linux-x64/node.napi.node =======> 2nd candidate
```

both point to `web3` dev dependencies of `prover` packages (cc @nazarhussain ), but they should not be loaded in production environment

I reinstalled node modules with `yarn --production` and add `NODE_ENV=production` before our node command, `proc maps` file does not show dev dependencies, will need monitor the issue again

**Update**: still got the issue

<img width="801" alt="Screenshot 2023-05-29 at 11 12 49" src="https://github.com/ChainSafe/lodestar/assets/10568965/e08f7fff-6c80-40dc-abfb-2c0032bf0a35">

**Comment by twoeths** [comment]
another direction is to review metrics in the last 30 days

<img width="798" alt="Screenshot 2023-05-29 at 10 31 44" src="https://github.com/ChainSafe/lodestar/assets/10568965/761e5202-b754-4ffe-8498-8d761a37e660">

the issue happens since May 23, need to investigate commits around that day

```
git log --oneline --since="2023-05-22 00:00" --until="2023-05-23 23:59"
186a5e8899 fix(validator): improve error handling in attestation service (#5511)
4fd72b2b61 refactor: change archiving strategy to always store last finalized (#5520)
42c80973a5 feat: more metrics for sync committee message validation (#5516)
504a9d364f test: update the sim tests to simplify assertion logic (#5501)
```

**Comment by twoeths** [comment]
`42c8097` in the last 24h

<img width="805" alt="Screenshot 2023-05-30 at 11 37 29" src="https://github.com/ChainSafe/lodestar/assets/10568965/a178aae2-5884-49ec-bfa3-437671d10f4e">

`4fd72b2b61` in the last 24h

<img width="803" alt="Screenshot 2023-05-30 at 11 38 21" src="https://github.com/ChainSafe/lodestar/assets/10568965/806d9d37-7c61-4ae1-a086-8db1cd653144">

#5520 is the cause for this issue

**Comment by dapplion** [comment]
- Noting that a user reported a leak on 1.7.2 for mainnet https://github.com/ChainSafe/lodestar/issues/5349

**Comment by twoeths** [comment]
@dapplion this is not the same issue, this issue is merely about rss and node was not crashed while #5349 is related to heap memory

**Comment by twoeths** [comment]
since we revert #5520, this issue does not happen in the final v1.9.0. If we improve any strategies in archiving state, need to refer to this issue
