### ISSUE TITLE
Light Client Task Force #2 - Multiproof Formats & Proof Negotiation

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#555]
**DATE**: Dec. 4, 15:00 UTC
**DURATION**: 1.5 hours
**LOCATION**: Zoom

### Purpose
Discuss upcoming light client research
Coordinate to bring ethereum light client tech to production

### Audience
Researchers, client developers, wallet developers

### Agenda
1. Introductions (10min)
2. Discussion on multiproof formats and proof negotiation (eth2-focused) (50min)
3. Next Steps / Tactics / Open Discussion (optional) (30min)

Proofs are the lifeblood of any light client. We will discuss the landscape of multiproofs. Proof backings / concerns / consumers / request/response interactions / interfaces.

### Background Reading

- [Current SSZ Spec](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/simple-serialize.md) - describes the mechanics of SSZ merkleization
- [SSZ Multiproofs Spec](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/light_client/merkle_proofs.md) - describes generalized indices and multiproofs
- [New SSZ Spec](https://github.com/protolambda/eth2.0-ssz/) - WIP, includes more motivation and detail around the merkleization/proof side of SSZ
- [Summary of SSZ Multiproof concepts / backings](https://github.com/ethereum/eth2.0-specs/pull/1400#issuecomment-534400064) - see "RE multi-proof structure:"
- [SSZ Sparse Merkle Tree (SMT)](https://github.com/ethereum/eth2.0-specs/issues/1472) - discussion about adding SMTs to SSZ
- [EE Multiproof Concerns](https://github.com/quilt/pm/issues/2) - great writeup on the expected EE toolchain
- [Experiments w Merkle Trees/Tree-offset Proof Backing](https://github.com/protolambda/eth-merkle-trees)
- [Discussion on Requesting Multiproofs](https://github.com/ethereum/eth2.0-specs/issues/644)
- [Discussion on SSZ Partials / Classic Proof Backing](https://github.com/ethereum/eth2.0-specs/issues/1303)
- [Turboproof Proof Backing](https://medium.com/@gballet/turboproofs-light-clients-and-saving-private-eth1-487aaa9b386)

### Discussion Ideas

- How can we create a unified infrastructure for requesting / handling proofs across phase 0/1 data and EE data?
- How should proofs can be requested/responded by light clients and servers? Where is the overlap between light clients handling Ph0/1 data proofs and block producers handling EE state proofs?
- [your idea here]

### Previous Meetings
- [Meeting #1](https://www.youtube.com/watch?v=aY4Qsk22IAE&t=1s)(https://medium.com/chainsafe-systems/light-client-task-force-call-1-1aaf559230fb)

**Comment by zmanian** [comment]
Light client proof formats are critical for IBC.
Here is some related work.

https://github.com/confio/ics23

**Comment by protolambda** [comment]
For anyone who is interested in implementing partials, or any kind of specialized data-sharing ssz structure (great for caching hash-tree-root!), I made a write-up about implementing it, with some early results: https://github.com/protolambda/eth-merkle-trees/blob/master/typing_partials.md

**Comment by wemeetagain** [comment]
Recording: https://www.youtube.com/watch?v=h_GeWO0U-bw
Transcript: https://medium.com/chainsafe-systems/light-client-task-force-call-2-bdb3d24d2b2b
