### ISSUE TITLE
Update fork choice to 0.9.1 spec

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#556]
- [ ] bounce attack resistance - ethereum/eth2.0-specs#1465
- [x] decoy flip-flop resistance - ethereum/eth2.0-specs#1466

**Comment by twoeths** [comment]
Refer to:
+ https://github.com/ethereum/eth2.0-specs/pull/1465
+ https://github.com/ethereum/eth2.0-specs/pull/1466

**Comment by twoeths** [comment]
@wemeetagain I remember you have some concern/question regarding this, what is it about?

**Comment by wemeetagain** [comment]
I think our #559 only tackled ethereum/eth2.0-specs#1466, must pointing out we would want to integrate ethereum/eth2.0-specs#1465 too

**Comment by twoeths** [comment]
Oh I thought that 1465 was not applicable to our implementation but maybe I was wrong. Need to look into the 2 implementations and compare ...
