### ISSUE TITLE
Verify database genesis 

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#557]
When lodestar is starting, we aren't detecting if database has same genesis state as defined by cli flags
which sometimes causes weird errors.

Probably ideal would be for chain module to throw error on initialization if state is different from genesis state in database (check should be done before we store new genesis state).

error should be something like "Database contains different genesis state, please clean database"

**Comment by tjkix2006** [comment]
@mpetrunic Is this still needed? This would just be for the `dev` command? Or `beacon` as well?

**Comment by mpetrunic** [comment]
Yes, it's still needed. I don't think it should be related to cli commands. It would probably be best if this check is performed inside chain module

**Comment by aunyks** [comment]
@tjkix2006 Would you like to pick this up? If not, I can take it.

**Comment by tjkix2006** [comment]
@aunyks Yeah, sorry for the delay. Go ahead. I looked at it and am a little confused about the context.

**Comment by aunyks** [comment]
@mpetrunic This is related to the [`beacon`](https://github.com/ChainSafe/lodestar/tree/master/packages/lodestar#starting-lodestar-beacon-chain) subcommand, correct?

**Comment by mpetrunic** [comment]
@aunyks nothing to do with cli, when chain module is starting, we should check if state matches one stored in database
