### ISSUE TITLE
Track rated effectiveness as metric

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#5615]
### Problem description

Track rated effectiveness from here https://www.rated.network/o/ChainSafe%20-%20Lido?timeWindow=7d&network=mainnet as a built-in metric. Also, track the components of the formula to quickly understand what factors as contributing to a score under an expected level.

### Solution description

N/A

**Comment by dapplion** [comment]
Collecting details on Rated.network discord about the exact formula used https://discord.com/channels/905422453218627584/905423981362950214/1116265150022959116

**Comment by dapplion** [comment]
From Discord discussion, I think this summary below has no more doubts

```py
proposer_effectiveness = [non_empty_blocks + empty_blocks * 0.25] / total_proposer_slots_attributed
attester_effectiveness = participation_rate * correctness_score / aggregate_inclusion_delay
validator_effectiveness = [3/8 * proposer_effectiveness] + [5/8 * attester_effectiveness]
```

Where:

After epoch N is finalized, consider exclusively on-chain data, iterate over canonical blocks and:
- `participation_rate(epoch)`: count of attestations found in canonical blocks at `epoch - 1`
- `correctness_score(epoch)`: average `(timely_head as u8 + timely_target as u8 + timely_source as u8) / 3`
- `aggregate_inclusion_delay(epoch)`: `earliest_inclusion_slot - slot`, where `earliest_inclusion_slot` = earliest inclusion of attestation in canonical blocks at `epoch`

**Comment by dapplion** [comment]
A good approximation of the score with proposer effectiveness hardcoded to 0.17%

```
5/8
*
(
  1 -
  sum(rate(validator_monitor_prev_epoch_on_chain_source_attester_miss_total[1d]))
  /
  sum(
    rate(validator_monitor_prev_epoch_on_chain_source_attester_miss_total[1d])
    +
    rate(validator_monitor_prev_epoch_on_chain_source_attester_hit_total[1d])
  )
)
*
(
  (
    1 -
    sum(rate(validator_monitor_prev_epoch_on_chain_head_attester_miss_total[1d]))
    /
    sum(
      rate(validator_monitor_prev_epoch_on_chain_head_attester_miss_total[1d])
      +
      rate(validator_monitor_prev_epoch_on_chain_head_attester_hit_total[1d])
    )
  ) 
  + 
  (
    1 -
    sum(rate(validator_monitor_prev_epoch_on_chain_target_attester_miss_total[1d]))
    /
    sum(
      rate(validator_monitor_prev_epoch_on_chain_target_attester_miss_total[1d])
      +
      rate(validator_monitor_prev_epoch_on_chain_target_attester_hit_total[1d])
    )
  )
  +
  (
    1
    -
    sum(rate(validator_monitor_prev_epoch_on_chain_source_attester_miss_total[1d]))
    /
    sum(
      rate(validator_monitor_prev_epoch_on_chain_source_attester_miss_total[1d])
      +
      rate(validator_monitor_prev_epoch_on_chain_source_attester_hit_total[1d])
    )
  )
) 
*
1/3
*
1/(
  sum(rate(validator_monitor_prev_epoch_on_chain_inclusion_distance_sum[1d]))
  /
  sum(rate(validator_monitor_prev_epoch_on_chain_inclusion_distance_count[1d]))
)
+
3/8 * (1 - 0.17/100)
```

**Comment by nflaig** [comment]
Was looking into calculating proposer effectiveness based on new block proposal metric (https://github.com/ChainSafe/lodestar/pull/5603). Have to use `or vector(0)` as there might be no data points for the selected time range. [Rated docs on proposer-effectiveness](https://docs.rated.network/methodologies/ethereum-beacon-chain/rated-effectiveness-rating/proposer-effectiveness) was helpful but there is no information what value should be used if there are no proposals at all. Could just set the same value for no proposals as if there were no missed proposals.

```
(
  1 -
  sum(rate(validator_monitor_prev_epoch_block_proposal_summary{summary!="canonical"}[1d])) or vector(0)
  /
  sum(rate(validator_monitor_prev_epoch_block_proposal_summary[1d])) or vector(0)
)
```

**Comment by philknows** [comment]
AFAIK, this has been fully implemented into our dashboard metrics. Please reopen if there are any remaining items here that were not actually implemented.

**Comment by nflaig** [comment]
> AFAIK, this has been fully implemented into our dashboard metrics.

Depends on how you define "fully", right now we assume a factor of 1 for block proposals (=no missed proposals). I think this doesn't really matter as we generally don't look at metrics older than 30 days and with high validator count on mainnet, proposals are just too rare to have any statistical impact on the metric.

I was looking into properly tracking proposals (https://github.com/ChainSafe/lodestar/issues/5615#issuecomment-1750801099) but this was problematic because there are no data points most of the time.

I am also curious if rated.network even uses the same formula as block proposals have become significantly less of an impact on validator performance with the increase of total validator count on mainnet.
