### ISSUE TITLE
Issues finding peers in chiado

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#5620]
### Describe the bug

Users have reported Lodestar beacon nodes struggling to find peers on Chiado network. I have tested myself and also run into multiple times where the nodes stay longer than 10 minutes with 0 peers.

I've tested locally running
```
DEBUG=discv5:* ./lodestar beacon --network chiado --rest --rest.address 0.0.0.0 --metrics --logLevel debug --eth1 false --execution.engineMock
```

It enables discv5 logs and shows that discv5 is indeed working but not able to find suitable peers. Needs more investigation

### Expected behavior

Find many suitable peers within the first minute of running

### Operating system

Linux

### Lodestar version or commit hash

Latest unstable ae478384890f9f2fcb7446b1860f84b3f3d5c5cf

**Comment by philknows** [comment]
Is this still widely reported as an issue on our latest release @dapplion ?

**Comment by wemeetagain** [comment]
closing as stale
