### ISSUE TITLE
/eth/v1/beacon/states/head/committees returns incorrect information

### ISSUE THREAD

**Issue by mcdee** [ChainSafe/lodestar#5632]
### Describe the bug

Calling `/eth/v1/beacon/states/head/committees` on the API endpoint always returns committees for slot 0, for example on the current deneb testnet:

```
curl -s 'https://xxx@bn.lodestar-ethereumjs-1.srv.4844-devnet-6.ethpandaops.io/eth/v1/beacon/states/head/committees'| jq -r .data[].slot | sort | uniq -c
     32 0
```

### Expected behavior

Would expect to see the committees for the current epoch, for example:

```
curl -s 'https://xxx@bn.teku-nethermind-1.srv.4844-devnet-6.ethpandaops.io/eth/v1/beacon/states/head/committees'| jq -r .data[].slot | sort | uniq -c
      1 38176
      1 38177
      1 38178
      1 38179
      1 38180
      1 38181
      1 38182
      1 38183
      1 38184
      1 38185
      1 38186
      1 38187
      1 38188
      1 38189
      1 38190
      1 38191
      1 38192
      1 38193
      1 38194
      1 38195
      1 38196
      1 38197
      1 38198
      1 38199
      1 38200
      1 38201
      1 38202
      1 38203
      1 38204
      1 38205
      1 38206
      1 38207
```

### Steps to reproduce

As per above, connected to pre-devnet 6

### Operating system

Linux

### Lodestar version or commit hash

Whatever is running on the servers as mentioned above

**Comment by nflaig** [comment]
Thanks for reporting @mcdee. That's definitely a bug, fix is one the way
