### ISSUE TITLE
Running a commonjs project produced No "exports" error

### ISSUE THREAD

**Issue by RayLvv** [ChainSafe/lodestar#5638]
### Describe the bug

Error:  No "exports" main defined in /${path}/node_modules/@lodestar/types/package.json

Here my code seems like this:
**verify.service.ts**
`import { ssz } from '@lodestar/types';
...
      const signingRoot = computeSigningRoot(
        ssz.phase0.VoluntaryExit,
        parsedExit,
        domain,
      );
...
`
Run following commands and the error occurs:
nest build
nest start

### Expected behavior

The program runs well and no error occurs.

### Operating system

macOS

### Lodestar version or commit hash

v1.8.0

**Comment by RayLvv** [comment]
It seems here is a similar issue, https://github.com/ChainSafe/lodestar/issues/4349
Can I import this module in a nestjs project?

**Comment by nflaig** [comment]
Lodestar packages are pure ESM packages, you can't just use them in a CommonJS project.

Looks like nestjs does not support ESM
- https://github.com/nestjs/nest/pull/8736

There are some workarounds you can use
- https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
- https://stackoverflow.com/a/75287028/10577550 <-- specific to nestjs

**Comment by RayLvv** [comment]
> Lodestar packages are pure ESM packages, you can't just use them in a CommonJS project.
> 
> Looks like nestjs does not support ESM
> 
> * [build: generate multiple formats (cjs, esm) nestjs/nest#8736](https://github.com/nestjs/nest/pull/8736)
> 
> There are some workarounds you can use
> 
> * https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
> * https://stackoverflow.com/a/75287028/10577550 <-- specific to nestjs

Ok, I will take a look at that, thanks for help very much
