### ISSUE TITLE
Spec: Increase the MAX_EFFECTIVE_BALANCE

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#5655]
### Problem description

Track update and implementation of https://ethresear.ch/t/increase-the-max-effective-balance-a-modest-proposal/15801 a proposal to allow network participants to consolidate state and reduce the number of active indexes

### Progress tracker

Active incomplete implementation here https://github.com/ChainSafe/lodestar/compare/dapplion/maxeb?expand=1

**Comment by philknows** [comment]
Reopen when spec is final
