### ISSUE TITLE
Lodestar requested so many peers to connect

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5670]
### Describe the bug

- This happened both on a mainnet node, Lodestar requested so many peers to connect, during that time node received way more aggregate and proof

<img width="821" alt="Screenshot 2023-06-20 at 14 01 51" src="https://github.com/ChainSafe/lodestar/assets/10568965/a30baf04-a20c-4876-b7d3-39d4a9d30959">

- Also way more beacon block

<img width="794" alt="Screenshot 2023-06-20 at 14 02 14" src="https://github.com/ChainSafe/lodestar/assets/10568965/9f9c25cf-3fcf-4015-a623-e773c878d23b">

- CPU usage spiked to an unbelievable number

<img width="796" alt="Screenshot 2023-06-20 at 14 04 49" src="https://github.com/ChainSafe/lodestar/assets/10568965/1aa6c956-b684-41bf-b31a-8e1825960f94">

- Also GC pause time rate

<img width="795" alt="Screenshot 2023-06-20 at 14 05 25" src="https://github.com/ChainSafe/lodestar/assets/10568965/897fe0aa-5d8d-44c5-a834-244fe73aee8c">

### Expected behavior

With maxPeer=55, a node should only request a number of peers less than that

### Operating system

Linux

### Lodestar version or commit hash

v1.8.0

**Comment by twoeths** [comment]
using `increased()` caused the number exaggerate a lot, if I used `rate()` I got the realistic number:

<img width="1290" alt="Screenshot 2023-06-20 at 15 33 15" src="https://github.com/ChainSafe/lodestar/assets/10568965/e1c3d839-b6d1-488a-8df2-c67d9f5a1037">

**Comment by dapplion** [comment]
@tuyennhv this must be a metrics collection bug. The numbers shown here are impossible, such a GC collecting 1 TB / sec of memory :laughing: 

The likely explanation is that there was some downtime in the metrics server such that values at time N, are timestamp and in N + K. Then the delta from N + K to N + K + 1 appears as a huge spike

**Comment by twoeths** [comment]
this issue does not happen on v1.10.0

<img width="1298" alt="Screenshot 2023-08-20 at 13 09 55" src="https://github.com/ChainSafe/lodestar/assets/10568965/dded04b4-c8ff-470c-9c84-8474be436ef2">
