### ISSUE TITLE
Add `finalized` property to HTTP API responses

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#5693]
### Problem description

Latest beacon API spec requires `finalized` property in some HTTP API respones
- https://github.com/ethereum/beacon-APIs/pull/254

### Solution description

Add `finalized` property to the following HTTP API responses:

- https://ethereum.github.io/beacon-APIs/#/Beacon/getBlockAttestations
- https://ethereum.github.io/beacon-APIs/#/Beacon/getBlindedBlock
- https://ethereum.github.io/beacon-APIs/#/Beacon/getBlockV2
- https://ethereum.github.io/beacon-APIs/#/Beacon/getBlockHeaders
- https://ethereum.github.io/beacon-APIs/#/Beacon/getBlockHeader
- https://ethereum.github.io/beacon-APIs/#/Beacon/getBlockRoot
- https://ethereum.github.io/beacon-APIs/#/Beacon/getEpochCommittees
- https://ethereum.github.io/beacon-APIs/#/Beacon/getStateFinalityCheckpoints
- https://ethereum.github.io/beacon-APIs/#/Beacon/getStateFork
- https://ethereum.github.io/beacon-APIs/#/Beacon/getStateRandao
- https://ethereum.github.io/beacon-APIs/#/Beacon/getStateRoot
- https://ethereum.github.io/beacon-APIs/#/Beacon/getEpochSyncCommittees
- https://ethereum.github.io/beacon-APIs/#/Beacon/getStateValidators
- https://ethereum.github.io/beacon-APIs/#/Beacon/getStateValidator
- https://ethereum.github.io/beacon-APIs/#/Beacon/getStateValidatorBalances
- https://ethereum.github.io/beacon-APIs/#/Debug/getStateV2

**Comment by philknows** [comment]
- state endpoints blocked on #6033

**Comment by zilm13** [comment]
Any updates on this? 
Testing Teku VC with Lodestar BN to fix https://github.com/Consensys/teku/issues/8118
And getting error in parsing https://ethereum.github.io/beacon-APIs/#/Beacon/getStateValidators because of missing `finalized` field which is required by the spec https://github.com/ethereum/beacon-APIs/blob/master/apis/beacon/states/validators.yaml#L48

**Comment by nflaig** [comment]
I think @ensi321 wanted to look into this, right now Lodestar is pretty limited in serving finalized data derived from the state as we only keep the unfinalized state in-memory and only persist very few states to load from disk (will be addressed by https://github.com/ChainSafe/lodestar/pull/6033). We could just hard code those to `finalized=false` for now to fix the compatibility issue and be spec compliant.

On the note of cross-client compatibliy, we currently also only support json bodies for all requests but as per spec there are a few APIs that should also support ssz bodies. How does Teku handle this case, do you send the ssz body and if you receive a 415 (unsupported media type) do you resend the request with a json body?

I am working on a overhaul of the API to add first class support for ssz res/resp to (almost) all APIs so this will be addressed soon as well.

**Comment by zilm13** [comment]
@nflaig 
Hmm if it's really not finalized it would be fair as a quick fix.
Yeah, we send it by default in ssz (could be overridden with command line flag), if we receive 415, we fallback to json storing that ssz is not supported, so on next requests we will use json until VC is restarted.

**Comment by nflaig** [comment]
>  if we receive 415, we fallback to json storing that ssz is not supported, so on next requests we will use json until VC is restarted

ah perfekt, this is the ideal behavior I also had in mind because we want to send ssz bodies for almost all APIs even those that don't have it (yet) defined in the spec

**Comment by nflaig** [comment]
> * state endpoints blocked on [feat: add historical state regen #6033](https://github.com/ChainSafe/lodestar/pull/6033)

We can implement this already without the historical state regen, we already can serve some finalized data without it, e.g. finalized blocks or finalized checkpoints.
