### ISSUE TITLE
Implement beacon rewards APIs

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#5694]
### Problem description

Latest beacon API spec requires rewards APIs
- https://github.com/ethereum/beacon-APIs/pull/260
- https://github.com/ethereum/beacon-APIs/pull/262
- https://github.com/ethereum/beacon-APIs/pull/340

### Solution description

Implement the following routes:
- https://ethereum.github.io/beacon-APIs/#/Rewards/getSyncCommitteeRewards
- https://ethereum.github.io/beacon-APIs/#/Rewards/getBlockRewards
- https://ethereum.github.io/beacon-APIs/#/Rewards/getAttestationsRewards

**Comment by ensi321** [comment]
Issue closed since all three reward endpoints has been implemented.

Note that current implementations only support Altair and after. Currently there is no plan to support phase0 reward. If deemed necessary, please open another issue.
