### ISSUE TITLE
Implement deposit snapshot API

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#5697]
### Problem description

Latest beacon API spec requires deposit snapshot API
- https://github.com/ethereum/beacon-APIs/pull/245

### Solution description

Implement the following route:
- https://ethereum.github.io/beacon-APIs/#/Beacon/getDepositSnapshot

**Comment by dapplion** [comment]
- Duplicate of https://github.com/ChainSafe/lodestar/issues/4935
