### ISSUE TITLE
Add `syncing_status` query parameter to health API

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#5702]
### Problem description

Latest beacon API spec requires `syncing_status` query parameter
- https://github.com/ethereum/beacon-APIs/pull/251

### Solution description

Add syncing_status query parameter to health API
- https://ethereum.github.io/beacon-APIs/#/Node/getHealth

**Comment by allwin199** [comment]
I would like to work on this if it is still open.

**Comment by allwin199** [comment]
Can you give more info about this issue?

**Comment by nflaig** [comment]
You can find more information in the spec PR https://github.com/ethereum/beacon-APIs/pull/251 and this issue https://github.com/ethereum/beacon-APIs/issues/147.

This requires to update the api definition here
https://github.com/ChainSafe/lodestar/blob/cdca9fbd589e450bcdb190032e97e16ea4ba0f13/packages/api/src/beacon/routes/node.ts#L141

and further changes on beacon node side
https://github.com/ChainSafe/lodestar/blob/cdca9fbd589e450bcdb190032e97e16ea4ba0f13/packages/beacon-node/src/api/impl/node/index.ts#L69
https://github.com/ChainSafe/lodestar/blob/cdca9fbd589e450bcdb190032e97e16ea4ba0f13/packages/api/src/beacon/server/node.ts#L20

Best to check other routes that use query parameters and see how it is implemented there.

You can find more about the reasoning how the API routes are defined here
https://github.com/ChainSafe/lodestar/blob/cdca9fbd589e450bcdb190032e97e16ea4ba0f13/packages/api/src/beacon/routes/index.ts#L33-L35

The validator client won't use this feature, so no changes required there.

**Comment by allwin199** [comment]
Thanks for the explanation! Will work on it.

**Comment by allwin199** [comment]
I tried fixing this issue, but I am unable to fix it.

If someone fixes this issue, I will learn from it.

Thanks for the opportunity.

**Comment by nflaig** [comment]
> I tried fixing this issue, but I am unable to fix it.

All good, thanks for giving it a try.

It would be great if you could provide some feedback
- what were the obstacles you faced when trying to solve this?
- and is there anything we could do to make it easier to contribute?

**Comment by allwin199** [comment]
To fix the issue, I changed below lines

```
export type ReqTypes = {
   getHealth: {query: {syncing_status?: boolean}};
}
```
```
export function getReqSerializers = {
  getHealth: {
      writeReq: (syncing_status) => ({query: syncing_status || {}}),
      parseReq: ({query}) => [query],
      schema: {query: {syncing_status: Schema.Boolean}},
    },
}
```

Is the flow correct? I have also added type boolean in `Schema.ts`

If the flow is correct,
In the getReqSerializers(), I don't understand this `parseReq` part.
This is where I am stuck.

**Comment by nflaig** [comment]
> Is the flow correct? I have also added type boolean in Schema.ts

First you need to update the types,  this makes it easier to update all the other parts. `syncing_status` is an optional integer value not a boolean so the schema needs to be `Schema.Uint`.

> In the getReqSerializers(), I don't understand this parseReq part.

That just parses the incoming request to the right format expected in the code.
https://github.com/ChainSafe/lodestar/blob/1bc571b8a48c98af8c35a323e3c57f29ec9bb72b/packages/api/src/beacon/routes/node.ts#L178-L182

I found an issue with the current implementation, it always returned 200 even if node is syncing, this made the task also not that great for someone new to codebase.

I opened a PR https://github.com/ChainSafe/lodestar/pull/5790 to implement the new query parameter and fix the issue. @worksofallwin Feel free to give this a review and ask questions if something is unclear.

**Comment by allwin199** [comment]
@nflaig Thanks for the reply. I will go through and I will post If I don't understand anything.
