### ISSUE TITLE
Lodestar receives a lot of gossipsub Prune requests

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5713]
### Describe the bug

This is from a mainnet node

<img width="1291" alt="Screenshot 2023-06-27 at 11 18 23" src="https://github.com/ChainSafe/lodestar/assets/10568965/5c390e1b-8ca1-4181-a826-65fd7b4623f1">

This "Unsubscribed" reason is misleading, it just means we received Prune request from our peer, see https://github.com/ChainSafe/js-libp2p-gossipsub/pull/440

### Expected behavior

Receive small number of prune request

### Operating system

Linux

### Lodestar version or commit hash

v1.9.0

**Comment by twoeths** [comment]
This is one reason https://github.com/ChainSafe/js-libp2p-gossipsub/issues/441

**Comment by twoeths** [comment]
this is from a stable mainnet node v1.10.0

<img width="1302" alt="Screenshot 2023-08-20 at 13 55 43" src="https://github.com/ChainSafe/lodestar/assets/10568965/6f9ff442-1ade-4c88-980d-e381ce6eaba5">

**Comment by dapplion** [comment]
Still 6.8 prunes per second is a lot right?

**Comment by twoeths** [comment]
the network thread should reduce it down to <= 2.5s, this is from #5896 branch

<img width="1271" alt="Screenshot 2023-08-22 at 08 20 53" src="https://github.com/ChainSafe/lodestar/assets/10568965/1247d5c9-17ef-4b59-a96c-2154fcfab23a">

@dapplion  I'm reopening the issue to track 👍

**Comment by philknows** [comment]
Worth reinvestigating now that we only subscribe to 2 subnets

**Comment by wemeetagain** [comment]
![Screenshot from 2024-10-15 12-40-07](https://github.com/user-attachments/assets/10df308a-03c3-4660-b958-520c1d4d1c3c)

Resolved as of now o'clock
