### ISSUE TITLE
Lodestar has more than 55 peers

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5732]
### Describe the bug

After we upgrade to libp2p 0.45.9, there are more than 55 peers

<img width="1310" alt="Screenshot 2023-07-07 at 14 43 48" src="https://github.com/ChainSafe/lodestar/assets/10568965/2c84e03e-e186-403b-928c-a5bf92ff5d3f">

cc @wemeetagain 

### Expected behavior

node should consistently have 50 - 55 peers

### Operating system

Linux

### Lodestar version or commit hash

7280234

**Comment by philknows** [comment]
I don't know if I would consider this an issue anymore @tuyennhv seeing as we want to increase it to 100-110 via #5799, but if it has to do with some issue on the peer manager, we should be more specific about it in this issue.

**Comment by twoeths** [comment]
this issue happens quite randomly, this is on a real mainnet node running almost `v1.10.0-rc.1`, the peers are consistently at around 60 in the last 2 days

<img width="806" alt="Screenshot 2023-08-03 at 09 55 50" src="https://github.com/ChainSafe/lodestar/assets/10568965/a7977bd8-02ee-4a13-8a05-6efb97d41ec5">


topic peers keep increasing, and it's all because of incoming peers

<img width="790" alt="Screenshot 2023-08-03 at 09 57 20" src="https://github.com/ChainSafe/lodestar/assets/10568965/6aeae4df-d900-4b33-b48d-f5e70c0d185a">

<img width="798" alt="Screenshot 2023-08-03 at 09 57 28" src="https://github.com/ChainSafe/lodestar/assets/10568965/2abaaeac-7b28-4711-927c-b539921f7ed1">


it causes event loop lag to keep increasing cc @philknows 
<img width="1590" alt="Screenshot 2023-08-03 at 09 58 41" src="https://github.com/ChainSafe/lodestar/assets/10568965/8827d0ac-9462-4825-af77-4627e66199d1">

**Comment by twoeths** [comment]
Previously we count on libp2p which prune connections per new one connected. Now we count on peer manager heartbeat which run every 30s so we can't get connections to 50-55 peers consistently given peers connected to this node quite frequently

- Peer Manager does good job to remove ~20 peers per minute (= ~10 peers per heart beat, which is 60 - `targetPeers`)

<img width="962" alt="Screenshot 2023-08-03 at 14 45 48" src="https://github.com/ChainSafe/lodestar/assets/10568965/f7ce9185-202f-44c4-aae9-796fb5d5084c">

- However peers want to connect to this node quite frequently (~0/3x per sec = ~20 peers per minute)

<img width="782" alt="Screenshot 2023-08-03 at 14 47 49" src="https://github.com/ChainSafe/lodestar/assets/10568965/1458ad13-5cd2-4d58-9b46-a4a27fa7c5d7">

- libp2p-tcp is supposed not to listen for inbound connections if there are > 55 peers however there is a bug there, see https://github.com/libp2p/js-libp2p/issues/1927

**Comment by philknows** [comment]
![Image](https://github.com/ChainSafe/lodestar/assets/58080811/b7e30f85-a23c-427c-b7ca-22b71ae56ebf)

As of v1.13, it remains at 55 peers pretty consistently. However, I'm not entirely sure if the close server on max connections is resolved. Please close if no longer relevant.

**Comment by twoeths** [comment]
<img width="1311" alt="Screenshot 2023-12-24 at 15 04 10" src="https://github.com/ChainSafe/lodestar/assets/10568965/208fd674-8c88-4e10-9b9d-40fec082331f">

it could be up to 70 peers after v1.13.0 on unstable mainnet node but seems like it does not happen a lot like before, would like to keep this to monitor because this is prerequisite to increase to 100 peers

**Comment by wemeetagain** [comment]
closing since we now moved to 100 peers
