### ISSUE TITLE
DB buckets have duplicate keys

### ISSUE THREAD

**Issue by nazarhussain** [ChainSafe/lodestar#5753]
### Describe the bug

There are duplicate keys assigned to db buckets which could lead to unintended behavior. 

### Expected behavior

There should not be a key used twice for any bucket. Unless specified with a good reason. 

### Steps to reproduce

https://github.com/ChainSafe/lodestar/blob/7e34c46de5e4046eff5bdab045eba0a5bd65ff7a/packages/beacon-node/src/db/buckets.ts#L44

https://github.com/ChainSafe/lodestar/blob/7e34c46de5e4046eff5bdab045eba0a5bd65ff7a/packages/beacon-node/src/db/buckets.ts#L23

### Operating system

Linux

### Lodestar version or commit hash

1.9.x

**Comment by dapplion** [comment]
There must exist a unit test ensuring no duplication, I'm impressed typescript allows this lol

Collusion of db buckets will brick Lodestar, here we are lucky that networks with blobs (devnets only currently) never compute a genesis state. Must be fixed and ensure to never happen again
