### ISSUE TITLE
Do not subscribe to short-lived subnets too early

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5757]
### Problem description

Right now when we have an aggregation duty at epoch n, we'll subscribe to the 1st slot of epoch `n-1` which force us to process a lot of attestations unnecessarily

cc @dapplion 

### Solution description

Investigate a good value (`x` slot) to subscribe to subnet in advance

**Comment by dapplion** [comment]
Marking as high as small parameter `x slot` will reduce significantly the bandwidth and compute requirements of the node

**Comment by twoeths** [comment]
On stable 1 validator node, got this short lived subscription:

2023-07-26 13:25:36 | Jul-26 06:25:36.070[network]       verbose: Subscribe to gossipsub topic topic=/eth2/628941ef/beacon_attestation_39/ssz_snappy

the metric says we have stable mesh peers from 6:26:00

<img width="1305" alt="Screenshot 2023-07-26 at 14 41 31" src="https://github.com/ChainSafe/lodestar/assets/10568965/18c235ab-676a-48b1-857a-431ebafaed6b">

== it takes 24s = 2 slots to get stable subnet mesh peers on goerli

**Comment by dapplion** [comment]
@tuyennhv note that the scrape interval is 24 seconds, so the error of your measurement is 24 sec. It may be some value between 0 and 24 sec.

**Comment by twoeths** [comment]
another example on 1 validator node of unstable:

```
2023-07-25 22:23:12 | Jul-25 15:23:12.143[network]       verbose: Subscribe to gossipsub topic topic=/eth2/628941ef/beacon_attestation_52/ssz_snappy
```
<img width="1289" alt="Screenshot 2023-07-26 at 14 59 34" src="https://github.com/ChainSafe/lodestar/assets/10568965/47c8cbc2-6793-4fa0-9b99-110ddcf4fd0e">

===> it takes from ~~0~~ 11s to 33s to get stable mesh peers on goerli
