### ISSUE TITLE
Properly handle block forks

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#578]
Right now, we maintain the `latestState`, which is the state after processing the latest received block. We're always using this to progress the chain.
This means we cannot process legitimate blocks that are not descendants of the latest block we've seen.

eg:
```
block A -----> block B
         \
          \
           \
            \
             > block C
```
If we receive block C after processing block B, we currently cannot process it, since we're not using the state at block A, only using the new `latestState` (post-block B).

We should instead fetch the (non-latest) state needed to process a block if we need to.

**Comment by twoeths** [comment]
Here's what I understand:
+ When we receive block C, get parent block which is block A in this case, then we can get `stateRoot` of block A then get BeaconState from there and process with that.
+ If the parent block is not found then we put it in the queue

Is this enough or do we have any blockers @wemeetagain ?

**Comment by wemeetagain** [comment]
This should be enough
We'd probably want to be careful about places we're currently using `latestState`. In some cases, we actually want to be using the head of the chain according to the fork choice (the post-state of the head of the chain). Since we would now be handling forking properly, it would be important to actually be calling the fork choice appropriately and not just blindly using `latestState`.
