### ISSUE TITLE
Increase target peers to 100, max peers to 110

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5799]
### Problem description

Gradually all nodes will subscribe to exactly 2 subnets per node due to https://github.com/ethereum/consensus-specs/pull/3312 so it'll not easy to find enough subnet peers

### Solution description

We should track different things:
- Is it over 110 peers at some time, what's the consequence of that #5732
- Network volume, especially when we join a sync committee, only do it once we resolve #5741 ?
- Track time to publish a message, especially messages on core topics. See https://github.com/ChainSafe/js-libp2p-gossipsub/pull/451

### Additional context

Also other clients already increased to 100 peers (lighthouse, nimbus), lodestar should do the same

**Comment by dapplion** [comment]
@tuyennhv we should review the flood publish strategy into publishing to only a subset of subscribed peers. Can you review other clients strategies? Nimbus runs nodes with 2500 peers and has very reasonable outbound bandwidth

**Comment by philknows** [comment]
- blocked on #5732

**Comment by twoeths** [comment]
need to figure out if it causes more delay when publishing block or not when increasing to 100 peers because we send published messages to all peers, see #6596

**Comment by twoeths** [comment]
need to also take heap snapshot of network thread (when it's >= 2GB) + main thread (after increase target peers to 100). See https://github.com/ChainSafe/lodestar/pull/6556#issuecomment-2017692440
