### ISSUE TITLE
Updating the Validator Manager Contract?

### ISSUE THREAD

**Issue by aunyks** [ChainSafe/lodestar#58]
It seems like the [Validator Registration Contract](https://github.com/ChainSafeSystems/lodestar_chain/blob/master/solidity/contracts/ValidatorRegistration.sol) is in this repo to remain consistent with the VMC contract defined in [the current Beacon Chain specification](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#vyper-code). If this is the case, should it be updated to account for new contract fields?

**Comment by GregTheGreek** [comment]
@aunyks it definitely has not been updated, we've been putting a lot of focus on supplementary repos (fixed-num, BLS, SSZ)
And would love the help !

**Comment by aunyks** [comment]
Sounds good! I'll look into it

**Comment by GregTheGreek** [comment]
I'm reopening this, because it is a legitimate issue. If you end up doing it, just close it with your PR :)

**Comment by aunyks** [comment]
Ah, okay cool.

**Comment by aunyks** [comment]
I don't think I've explicit said so, but I'm working on this right now.

**Comment by GregTheGreek** [comment]
I assumed so! 

Im building the start functionality right now #60 so this will be great help! I'll stub my functions for the time being

**Comment by aunyks** [comment]
#66 was closed which *should* remove a blocker for start functionality.
