### ISSUE TITLE
Backup for Metrics server

### ISSUE THREAD

**Issue by Aminechakr** [ChainSafe/lodestar#5801]
As a backup strategy we want to persist metrics data on a storage bucket. Solution need to be cost efficient.

Data to be backed up : 

- Grafana volume
- Loki volume
- Kuma volume
- Prometheus volume

**Comment by dapplion** [comment]
I don't think this issue belongs here, @philknows can you transfer?

**Comment by jonpurdy** [comment]
I am creating a new repo for generic infrastructure and will move this today.
