### ISSUE TITLE
Strategy for managing bootnode ENRs

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#5838]
After thinking about changes done in https://github.com/ChainSafe/lodestar/pull/5834 a bit more I am not sure it is correct to pin the genesis and bootnode file URLs by commit hash. If we pin the files we might as well just copy and paste the enr and not rely on github at all, by pinning the URLs we get the worst of both worlds
- we have to update source code to update bootnodes and
- we rely on files provided by github

Looking at the static `bootEnrs` for mainnet it seems like the last update was 3 years ago (https://github.com/ChainSafe/lodestar/pull/1806)
https://github.com/ChainSafe/lodestar/blob/549aa03a40e4090d752e7275d3e29046e6214b4b/packages/cli/src/networks/mainnet.ts#L9

@dapplion I noticed most of the updates to network configration in past PRs was done by you. For example for goerli/prater in PR https://github.com/ChainSafe/lodestar/pull/2188 you specified a unpinned URL to fetch from github and empty `bootEnrs = []` but in case of gnosis we have both unpinned URLs and hard coded `bootEnrs` (https://github.com/ChainSafe/lodestar/pull/4979). Would be great to quickly explain the rationale for this
- when do we specify hard coded enrs in `bootEnrs`?
- when should hard coded `bootEnrs` be updated in the code?
- do we want to always fetch the latest list from github?

In my opinion, we should either not fetch data from github at all to prevent issues like https://github.com/ChainSafe/lodestar/issues/5833 (or risk of github outages) or we should unpin the files again to not have to update the source code to fetch updated list of ENRs.

**Note:** In case of github outage we just log an error but if github provides us with invalid ENRs and users have `--network.connectToDiscv5Bootnodes` set then their beacon node will fail on startup (https://github.com/ChainSafe/lodestar/issues/5833)
https://github.com/ChainSafe/lodestar/blob/549aa03a40e4090d752e7275d3e29046e6214b4b/packages/cli/src/networks/index.ts#L106-L109

Discv5 just ignores invalid ENRs when adding the enr [addEnr](https://github.com/ChainSafe/discv5/blob/75304d5a067f0ec2af839a280265b3d489bd4829/src/service/service.ts#L282-L288).

Regarding both those cases, I think we might be fine if we just pull latest files from github as connectToDiscv5Bootnodes is mostly meant for advanced use cases like devnets and a hidden flag. But I would like some discussion on when the hard coded values should be updated as it case of github outage we solely rely on those.

I also noticed that Lighthouse is planning to deprecate their two old bootnodes (see https://github.com/eth-clients/eth2-networks/pull/88), maybe it make sense to update hard coded `bootEnrs` at least once before every hard fork.

**Comment by dapplion** [comment]
Agree that pinned bootnodes files do not make sense. I don't have a strong on opinion for best solution, as long as we have a hardcoded set of trusted bootnodes we can dynamically pull

**Comment by nflaig** [comment]
I would suggest we do the following then
- always pull unpinned / latest version of files from github
- more frequent updates to hard coded values (once per hard fork)
- if a set of bootnodes is likely to change frequently then only pull from github (only for non-critical testnets)
