### ISSUE TITLE
Potential Discv5 Memory Leak

### ISSUE THREAD

**Issue by matthewkeil** [ChainSafe/lodestar#5839]
### Describe the bug

I noticed something in the memory panels once they were broken out by tread.  There is an external object memory leak, or what appears to be, in the discv5 panel.  See below. 

`feat1-lg1x` on 3day timeline
![Screenshot 2023-08-02 at 2 45 06 PM](https://github.com/ChainSafe/lodestar/assets/18608739/1b20e1b1-f9c9-4f47-a7b6-4a1110c7d4d8)

`stable-lg1x` on 30day timeline
![Screenshot 2023-08-02 at 2 49 27 PM](https://github.com/ChainSafe/lodestar/assets/18608739/b0f2049d-b7a9-4a8a-9678-ae734ea0c9c1)

### Expected behavior

All memory values should be roughly stable over time, especially on longer timeframes.

### Operating system

Linux

### Lodestar version or commit hash

stable and branches from stable

**Comment by wemeetagain** [comment]
![Screenshot from 2024-10-15 12-50-44](https://github.com/user-attachments/assets/2f57d49d-0f55-4085-a6b5-0f9a8018770f)

No longer an issue
