### ISSUE TITLE
Typo 'LHV' -> 'LVH'?

### ISSUE THREAD

**Issue by Yc-Chen** [ChainSafe/lodestar#5844]
### Describe the bug

I saw such code in places like https://github.com/ChainSafe/lodestar/blob/5739caf64cd9b7ec2acff602f6b2d2aa75281c21/packages/beacon-node/src/chain/blocks/index.ts#L87

```
if (segmentExecStatus.execAborted !== null) {
      if (segmentExecStatus.invalidSegmentLHV !== undefined) {
        this.forkChoice.validateLatestHash(segmentExecStatus.invalidSegmentLHV);
      }
      throw segmentExecStatus.execAborted.execError;
    }
```

### Expected behavior

Could it meant to be 'LVH' instead of 'LHV'?

### Operating system

Linux

### Lodestar version or commit hash

5739caf64cd9b7ec2acff602f6b2d2aa75281c21

**Comment by g11tech** [comment]
thanks @Yc-Chen for reporting this :pray: here is the fix: 
 - https://github.com/ChainSafe/lodestar/pull/5850
