### ISSUE TITLE
Improve recomputeForkChoiceHead

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5852]
### Describe the bug

In mainnet node it could take up to 0.5s to `recomputeForkChoiceHead`

<img width="1085" alt="Screenshot 2023-08-06 at 15 10 27" src="https://github.com/ChainSafe/lodestar/assets/10568965/f23cce32-037a-4649-946d-4fce2eb27229">

and it takes 6% of cpu in total

<img width="1314" alt="Screenshot 2023-08-06 at 15 22 50" src="https://github.com/ChainSafe/lodestar/assets/10568965/262bfb37-e9d5-42e9-8b09-2d56a1b076ee">

while out benchmark says <= 100ms

see https://github.com/ChainSafe/lodestar/pull/5836#issuecomment-1666767135

### Expected behavior

Get back to the level of v1.9.x

<img width="1298" alt="Screenshot 2023-08-06 at 15 12 01" src="https://github.com/ChainSafe/lodestar/assets/10568965/0357c7e4-92bc-442e-9852-dd321ac937e9">

### Operating system

Linux

### Lodestar version or commit hash

v1.10.0

**Comment by twoeths** [comment]
this could be because we processed so many attestations in v1.10.0 compared to v1.9.2

<img width="797" alt="Screenshot 2023-08-06 at 15 15 45" src="https://github.com/ChainSafe/lodestar/assets/10568965/316aaa14-f274-497b-ac0f-c6ac4237ee1d">

also looks like the benchmark test does not go with this number, need to update it

**Comment by twoeths** [comment]
this is part of the effort to handle more validators coming to ethereum, see #5855

**Comment by twoeths** [comment]
for 2M validator network, this could be up to 8s on 2M validator devnet

<img width="823" alt="Screenshot 2023-08-09 at 10 15 40" src="https://github.com/ChainSafe/lodestar/assets/10568965/8363a6ac-f605-44cc-8203-a162299cd331">

**Comment by twoeths** [comment]
[0810_updateHead_perf_test.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/12308374/0810_updateHead_perf_test.cpuprofile.zip)

this issue is caused by `getAncestor()` call, we iterate too much from a node until finalized node to check if a node is descendant of finalized node

<img width="1320" alt="Screenshot 2023-08-10 at 10 03 03" src="https://github.com/ChainSafe/lodestar/assets/10568965/e9143cf8-84ab-4fe9-95d9-7b51e05f96a3">

**Comment by dapplion** [comment]
@tuyennhv please research the following:
- when changing finalized create a new nodes vector that includes only descendant of finalized
- keep a mapping of the node index changes and update all indexes

With this we pay a higher ocassional cost, but then we never have to check if descedant of finalized. My concern is that finalized checkpoint can change at times where the node is hot. But it should be worth it to benchmark how expensive this remapping operation is
