### ISSUE TITLE
Lodestar on bigboy network (2M indexes)

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#5855]
Devops carried out a test to help clients prepare for very big networks. This issue is an epic to track different workstreams. Lodestar in particular showed the following pain points:

### Long epoch transitions

Epoch transitions regularly took 7-8 seconds, and 2 run per epoch. This took too many cycles off the main thread causing cascading issues. In current mainnet epoch transitions take 1 sec, so on a 2.1M it should be ~2.5 sec.
- Why is the epoch transition 3x slows than it should?
- Can the state transition be optimized more?
- Why there were 2 runs per epoch instead of 1?

### Head size 10-15 GB

The initial anchor CachedBeaconState takes 2.6GB. Since the network was not finalizing there were probably forks maxing the cache, but I could not assert this.
- https://github.com/ChainSafe/lodestar/issues/5857

### Long fork-choice runs

Re-computing the head takes 1 second, which is in line with observations on mainnet. However, 1 second is too long and not acceptable, and will cause attesters to vote for the wrong head.
- Can the re-compute head be optimized more?

### Very few peers

The nodes where visibility overloaded, probably causing long response times to network messages. We have not checked with other operators if the nodes were actively banning Lodestar or not, just a hypothesis. 
- TODO investigate more

**Comment by wemeetagain** [comment]
closing as stale
- epoch transition has been optimized heavily since then
- n-historical-states now on by default
- fork choice optimized since then
