### ISSUE TITLE
Low peers in test mainnet node

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5891]
### Describe the bug

Sometimes peers dropped to below 40 even without a restart, this is test mainnet node in unstable group

<img width="811" alt="Screenshot 2023-08-16 at 09 33 53" src="https://github.com/ChainSafe/lodestar/assets/10568965/c7c8d240-9722-4517-8ba8-c93d72e1f5bc">

Same metric in stable mainnet node

<img width="799" alt="Screenshot 2023-08-16 at 09 34 23" src="https://github.com/ChainSafe/lodestar/assets/10568965/4ccba0a2-b3a0-419e-9646-c14345f3d231">

### Expected behavior

Peers should not drop below 49 like in stable mainnet node

### Operating system

Linux

### Lodestar version or commit hash

unstable

**Comment by twoeths** [comment]
the earliest time I see this issue is Jul 17 (after we migrated to libp2p 0.45.x on Jul 04), this was not at the time node was restarted

<img width="775" alt="Screenshot 2023-08-16 at 14 40 00" src="https://github.com/ChainSafe/lodestar/assets/10568965/2cfd95a1-901a-46fe-87c9-988b380bbc7c">

that should be part of v1.10.0, however I didn't see it in stable mainnet node

**Comment by twoeths** [comment]
state transition is going crazy in the unstable mainnet node

<img width="1275" alt="Screenshot 2023-08-16 at 20 02 45" src="https://github.com/ChainSafe/lodestar/assets/10568965/db203d52-d6cd-4724-8062-586a05d6a8df">

that's one of the reason incoming/outgoing ping requests takes more than 5s

<img width="1580" alt="Screenshot 2023-08-16 at 20 05 02" src="https://github.com/ChainSafe/lodestar/assets/10568965/23b48135-51b4-43fd-8d17-9d41ae45a748">

hope this one helps #2115 (already see the state transition time coming down there on the beta node @matthewkeil )

**Comment by dapplion** [comment]
@tuyennhv what's the histogram of epoch transition avg time?

**Comment by twoeths** [comment]
@dapplion  this is unstable mainnet node in the last 2 days

<img width="796" alt="Screenshot 2023-08-18 at 11 45 41" src="https://github.com/ChainSafe/lodestar/assets/10568965/23333e25-0991-484c-838a-3aad249a421b">

this is same node in `feat1` (we deployed worker thread in the middle)

<img width="801" alt="Screenshot 2023-08-18 at 11 48 23" src="https://github.com/ChainSafe/lodestar/assets/10568965/1cd01beb-e9b0-412e-bdd6-7c65ab72bce8">

epoch transition itself is not slow, it's just the `gc` time I think. Switching to worker thread resolves the issue.

**Comment by twoeths** [comment]
still an issue with `v1.11`

**Comment by twoeths** [comment]
Unstable mainnet node peer count has been table during team retreat (node was not restarted at that time)

<img width="843" alt="Screenshot 2023-11-25 at 08 18 23" src="https://github.com/ChainSafe/lodestar/assets/10568965/4a4f695f-1fde-4a48-99f4-9bf151ab8b3c">

closing the issue
