### ISSUE TITLE
e2e test never finish

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5914]
### Describe the bug

Sometimes e2e tests never finish in CI environment, for example

https://github.com/ChainSafe/lodestar/actions/runs/5969671307/job/16195943714?pr=5912

### Expected behavior

no issue

### Operating system

Linux

### Lodestar version or commit hash

v1.10.0

**Comment by philknows** [comment]
Looks like @matthewkeil already made #5913
