### ISSUE TITLE
Versions of other clients / tools in CI tests

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#5942]
We should discuss what versions of other clients / tools we want to use in e2e and sim tests.

Currently, we use stable / fixed versions
https://github.com/ChainSafe/lodestar/blob/6ac8c07023bc72c7ef54a6ea66884790793eda21/.github/workflows/test-sim.yml#L20-L23
https://github.com/ChainSafe/lodestar/blob/6ac8c07023bc72c7ef54a6ea66884790793eda21/packages/validator/test/e2e/web3signer.test.ts#L20

Using stable (or even pinned) versions has the benefit that test runs are deterministic and test failures likely indicate an issue on Lodestar. However, there is a benefit of detecting interop issues as early as possible, e.g. recent libp2p issue with LH dropping mplex.

We could also use a different strategy based on how stable the dev branch / latest image of each client we test against is. Another option would be to test against different versions, e.g. unstable and stable LH version, this would make it easier to figure out that the tests are failing due to some transient / untested bug on their unstable branch and not due to a change done in Lodestar.

Due to the fact that devnets usually use unstable / dev versions I would rather tend towards testing against those in our CI.

Previous discussion on the topic [in discord](https://discord.com/channels/593655374469660673/605818244036821012/1141743814407618692).

**Comment by dapplion** [comment]
A CI step that runs on commit push must use deterministic versions. To ensure that Lodestar works with new releases there should be a new workflow that runs on a cron job (say, daily) against un-pinned version

**Comment by nflaig** [comment]
We are using pinned versions everywhere now and CI runs seem to be deterministic. Further testing via Kurtosis is tracked by https://github.com/ChainSafe/lodestar/issues/6692 already which we might wanna run on a cron job (daily) against un-pinned versions.
