### ISSUE TITLE
ECMAScript Explicit Resource Management 

### ISSUE THREAD

**Issue by nazarhussain** [ChainSafe/lodestar#5978]
### Problem description

Typescript 5.2 had introduced new ECMAScript feature called **Explicit Resource Management**, which is explicitly designed to cleanup resources with the help of following new structures. `using`, `Disposable`, `AsyncDisposable`, `DisposableStack` and `AsyncDisposableStack`. 

Our source code compromises of a lot of such cases where we need to cleanup a resources and we use `.close` methods on most of interfaces for that purpose. We should rather use this new design pattern. to cleanup the code. 

### Solution description

That's the pattern we can follow for code structure which occopy the network or io resources. 

```ts
const res = { [Symbol.dispose]() {} };
const asyncRes = { [Symbol.asyncDispose]() {} };
const iter = { [Symbol.iterator]() { return [res, asyncRes].values(); } };
const asyncIter = { [Symbol.asyncIterator]() { return [res, asyncRes].values(); } };
```

### Additional context

https://github.com/tc39/proposal-explicit-resource-management
https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/#using-declarations-and-explicit-resource-management

**Comment by wemeetagain** [comment]
Closing this issue since we are now using this pattern
