### ISSUE TITLE
Network worker thread vs child process

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#5981]
Metrics when running the network in a child process (**feat1**) vs a worker thread (**stable**). Beacon nodes have `--subscribeAllSubnets` flag set and `--network.useWorker` is enabled now by default as well. Both instances are on **v1.11.1**, the branch for running the network in a child process can be found here https://github.com/ChainSafe/lodestar/compare/unstable...nflaig/network-worker-process2.

### Event loop lag NETWORK WORKER

The top 1% percentile (p99) and max event loop lag seems to be significantly reduced when using a child process, however this might not be that relevant. There is no real difference in average event loop lag (p50) and even the top 10% percentile (p90) is almost the same.

#### Child process (feat1-mainnet-hzax41)
![image](https://github.com/ChainSafe/lodestar/assets/38436224/099e63c1-73d6-46b5-bb5c-bcff9044d80e)

#### Worker thread (stable-mainnet-hzax41)
![image](https://github.com/ChainSafe/lodestar/assets/38436224/6d49a871-fbe9-4560-970e-ce70797a67c8)

### Event loop lag BEACON

Main thread event loop lag is down as well if child process is used

#### Child process (feat1-mainnet-hzax41)
![image](https://github.com/ChainSafe/lodestar/assets/38436224/db79b3eb-0916-4d33-8392-a8b323faa692)

#### Worker thread (stable-mainnet-hzax41)
![image](https://github.com/ChainSafe/lodestar/assets/38436224/728fadce-856e-4a3f-b09d-f902830ec856)

### Prometheus scrape duration

The scrape duration is a lot higher when using a child process, likely releated to increased IPC latency and serialization / deserialization as currently the raw txt payload is serialized to base64 which is not ideal.

#### Child process (feat1-mainnet-hzax41)
![image](https://github.com/ChainSafe/lodestar/assets/38436224/f2963f2e-136a-4262-8ed4-dfa820f66a46)

#### Worker thread (stable-mainnet-hzax41)
![image](https://github.com/ChainSafe/lodestar/assets/38436224/29180be3-1fdb-4ef0-b943-fa784ceadb4c)

### Attnet mesh peers per subnet

Mesh peers seems to be much lower (possibly related to higher gossip validaton job wait time?)

#### Child process (feat1-mainnet-hzax41)

![image](https://github.com/ChainSafe/lodestar/assets/38436224/4c2c7f8d-a278-43d8-990c-6f459a88062a)

#### Worker thread (stable-mainnet-hzax41)

![image](https://github.com/ChainSafe/lodestar/assets/38436224/1e237394-d049-41c4-aa01-fc21c3c25b65)

### Peer connection length

Peer connection length looks pretty good on both sides, maybe slightly better when using a child process

#### Child process (feat1-mainnet-hzax41)

![image](https://github.com/ChainSafe/lodestar/assets/38436224/3688023a-ae3f-469a-9f5c-8a96ca3460ea)

#### Worker thread (stable-mainnet-hzax41)

![image](https://github.com/ChainSafe/lodestar/assets/38436224/b8f46da9-9325-4cc6-9a16-480b46d78387)

### Gossip validation queue

Job wait time and queue length looks much better when using a worker thread. This might be related to IPC and serdes latency added when using a child process. Latency metrics are required to further investigate this.

#### Child process (feat1-mainnet-hzax41)

![image](https://github.com/ChainSafe/lodestar/assets/38436224/b3f68832-8252-491b-ac67-abe50b0fea6b)

#### Worker thread (stable-mainnet-hzax41)

![image](https://github.com/ChainSafe/lodestar/assets/38436224/2401e237-4cc4-4f8f-b296-e6ef49f14397)

**Comment by matthewkeil** [comment]
### feat1-mainnet-hzax41
```sh
Run 1 > Performance counter stats for process id '618640,619487':
                  
            91,871      cgroup-switches           #  854.090 /sec                   
            92,730      context-switches          #  862.076 /sec                   
        107,540.34 msec cpu-clock                 #    1.792 CPUs utilized          
             2,158      cpu-migrations            #   20.062 /sec                   
               164      major-faults              #    1.525 /sec                   
           316,122      minor-faults              #    2.939 K/sec                  
           316,286      page-faults               #    2.940 K/sec                  
        107,591.49 msec task-clock                #    1.793 CPUs utilized          

 Run 2 > Performance counter stats for process id '618640,619487':

            86,502      cgroup-switches           #  783.767 /sec                   
            87,324      context-switches          #  791.215 /sec                   
        110,341.80 msec cpu-clock                 #    1.839 CPUs utilized          
             2,480      cpu-migrations            #   22.470 /sec                   
                 0      major-faults              #    0.000 /sec                   
            78,257      minor-faults              #  709.062 /sec                   
            78,257      page-faults               #  709.062 /sec                   
        110,392.09 msec task-clock                #    1.840 CPUs utilized          

Run 3 > Performance counter stats for process id '618640,619487':

            81,966      cgroup-switches           #  772.642 /sec                   
            82,845      context-switches          #  780.928 /sec                   
        106,060.35 msec cpu-clock                 #    1.768 CPUs utilized          
             2,363      cpu-migrations            #   22.275 /sec                   
                 2      major-faults              #    0.019 /sec                   
            59,663      minor-faults              #  562.406 /sec                   
            59,665      page-faults               #  562.424 /sec                   
        106,110.39 msec task-clock                #    1.768 CPUs utilized          
```

### unstable-mainnet-hzax41

`sudo perf stat -e "alignment-faults,bpf-output,cgroup-switches,context-switches,cpu-clock,cpu-migrations,emulation-faults,major-faults,minor-faults,page-faults,task-clock" -p $(pgrep -f 'packages/cli/bin/lodestar beacon') sleep 60`

```sh
Run 1 > Performance counter stats for process id '2756979':

           119,495      cgroup-switches           #    1.074 K/sec                  
           121,360      context-switches          #    1.090 K/sec                  
        111,269.89 msec cpu-clock                 #    1.854 CPUs utilized          
             1,447      cpu-migrations            #   13.001 /sec                   
                 0      major-faults              #    0.000 /sec                   
           432,655      minor-faults              #    3.887 K/sec                  
           432,655      page-faults               #    3.887 K/sec                  
        111,324.50 msec task-clock                #    1.855 CPUs utilized     

Run 2 > Performance counter stats for process id '2756979':

           106,443      cgroup-switches           #    1.002 K/sec                  
           107,095      context-switches          #    1.008 K/sec                  
        106,170.99 msec cpu-clock                 #    1.769 CPUs utilized          
             1,436      cpu-migrations            #   13.522 /sec                   
                 0      major-faults              #    0.000 /sec                   
           176,550      minor-faults              #    1.662 K/sec                  
           176,550      page-faults               #    1.662 K/sec                  
        106,221.85 msec task-clock                #    1.770 CPUs utilized    

Run 3 > Performance counter stats for process id '2756979':

           101,934      cgroup-switches           #  995.981 /sec                   
           102,425      context-switches          #    1.001 K/sec                  
        102,320.43 msec cpu-clock                 #    1.705 CPUs utilized          
             1,409      cpu-migrations            #   13.767 /sec                   
                 0      major-faults              #    0.000 /sec                   
           192,906      minor-faults              #    1.885 K/sec                  
           192,906      page-faults               #    1.885 K/sec                  
        102,370.17 msec task-clock                #    1.706 CPUs utilized          
```

**Comment by dapplion** [comment]
> Significant reduction in event loop lag when using a child process

Not that much actually, the average is the same. Only in the top 1% percentile 100ms -> 230ms. I'm not sure if the max is really representative.

**Comment by nflaig** [comment]
> Not that much actually, the average is the same. Only in the top 1% percentile 100ms -> 230ms. I'm not sure if the max is really representative.

Very good point, would be interesting to find out what is causing those high peaks, maybe busy main thread throttling the worker? Based on @matthewkeil perf results https://github.com/ChainSafe/lodestar/issues/5981#issuecomment-1731170907, it seems like there are a lot less context switches and faults when using a child process.

**Comment by nflaig** [comment]
The performance of the network seems to be really good now when using a worker thread, switching to child process adds other bottlenecks like IPC while the benefits are not worth it.
