### ISSUE TITLE
Representing bytes in Javascript

### ISSUE THREAD

**Issue by Mikerah** [ChainSafe/lodestar#6]
While implementing ssz in JS, I have been representing bytes as arrays. Currently, in this repository, bytes are represented using strings.

I would like to start a discussion as to what is a good way to represent bytes so that while implementing both ssz and the beacon chain spec, we are consistent.

**Comment by darrenlangley** [comment]
I agree with the approach that using TypedArrays (using ArrayBuffer underlying) is the best approach for working with bytes in Javascript.

I have also been working on an implementation of ssz, check it out:
https://github.com/darrenlangley/ssz-js/blob/master/src/simpleSerialize.js

It uses ArrayBuffer and DataView to make sure the correct bytes are created.

**Comment by Mikerah** [comment]
We have been using Buffers in Js in order to represent bytes.
Closing.
