### ISSUE TITLE
Startup function

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/lodestar#60]
**Is your feature request related to a problem? Please describe.**
By creating the startup functionality we will be able to begin testing the whole system as the pieces come together.

**Describe the solution you'd like**
Realistically, some functionalities will need to be stubbed, as we are still having some type related issues (primarily bytes #59).

**How to**
I am working on creating a start function (i.e the main entry point for the beacon chain) that will add an event listener to the deposit contract on ETH1.0. I'll have to get the old logs from the contract, and the continue to look for the new contracts. When the `ChainStart` log is emitted then my function will need to execute the `get_initial_beacon_state` function (not implemented, but I will have it implemented for my PR). At this point we will have the base state for the beacon chain and to avoid submitting an extensive pr i will stop at this point.

**Comment by GregTheGreek** [comment]
I'll be working on this.

**Comment by ansermino** [comment]
Can you elaborate on what functionality you aim implement?

**Comment by GregTheGreek** [comment]
Yep - I'll update my Issue.

**Comment by GregTheGreek** [comment]
updated

**Comment by GregTheGreek** [comment]
Currently working on this in [this branch](https://github.com/ChainSafeSystems/lodestar_chain/tree/greg/startup), but I am running into a few blockers:
1) Not 100% if I'm making the web3 calls in an efficient manner
2) I need to use a contract to test with, I'm thinking of importing the vyper contract and then writing a few tests to simulate it. May also just create a simulation directory to show the deposits happen live which could help down the road. Not sure how much different this is then just writing tests..

**Comment by ansermino** [comment]
Is there a reason for using web3 over ethersjs? I know some of us would prefer the latter

**Comment by GregTheGreek** [comment]
I'm using ethers*, web3 was more of a generalization of it all

**Comment by mpetrunic** [comment]
@GregTheGreek I would like to start working on this.

First thing I would add something like:
```
lodestar dev
```
which would start ganache server on private network with 10 predefined accounts with huge balance. It would also deploy deposit contract.

Second command would be:
```
lodestar deposit --contract <contractAdddress> --privateKey <privatekey>
```
that would deposit 32 ethers to deposit contract.

After that, I could start lodestar node with some configuration to connect to private network.

**Comment by GregTheGreek** [comment]
That would would be awesome, 100% with you on everything. 

I think something nifty that we would need to do would be to try and fill the deposit contract so `chainstart` event can be emitted!

**Comment by wemeetagain** [comment]
It may be useful to include a forked version of the deposit contract bytecode, where we've reduced the number of full deposits necessary to trigger an eth2genesis log. (we have a forked deposit contract repo here: https://github.com/ChainSafe/deposit_contract)
In the real contract its 65536 deposits or thereabouts, which takes a long time to actually process, even on a private ganache server.
I ran into this problem with https://github.com/ChainSafe/lodestar/blob/master/tests/eth1/deploy.ts which is why its currently a "disabled" test. (that test was originally supposed to test triggering an eth2genesis log, but it proved to take waaaay too long to practically add.)

**Comment by GregTheGreek** [comment]
good point! that would take a really long time to spam ... lol

**Comment by Mikerah** [comment]
On startup, we will also need to start listening for messages. This is mainly p2p stuff. I can rebase to my current branch once this has started.

**Comment by mpetrunic** [comment]
@Mikerah I haven't implemented cli method to start beacon node (yet) , but my approach was to execute [this](https://github.com/ChainSafe/lodestar/blob/master/src/node/index.ts) which should also start p2p from what I can tell.

**Comment by Mikerah** [comment]
@mpetrunic If that's how your planning to do it, then it should be fine.

**Comment by GregTheGreek** [comment]
@wemeetagain built out all the plumbing for the services so we should be good to roll out everytinh via cli
