### ISSUE TITLE
Use chainsafe/eslint-config

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#6011]
### Problem description

Our repos all use slightly different linting rules. There's a bit of maintenance friction that can be mitigated.

### Solution description

Evaluate, contribute to, and use the chainsafe eslint-config here and in our other repos.
We should upstream as many linter rules as we can (as many rules as makes sense).

### Additional context

See https://github.com/ChainSafe/eslint-config

**Comment by philknows** [comment]
We should use all this in our packages for the benefit of all ChainSafe users

**Comment by philknows** [comment]
cc: @mpetrunic . Thoughts?

**Comment by philknows** [comment]
To continue on this discussion and if we proceed to use this instead, we should consider how it will affect these:

https://github.com/ChainSafe/lodestar/issues/5566
https://github.com/ChainSafe/lodestar/issues/5505
https://github.com/ChainSafe/lodestar/issues/5242
https://github.com/ChainSafe/lodestar/issues/3929

Bump for opinion from @mpetrunic

**Comment by nflaig** [comment]
I am not sure having all lint config in a module is that great as it is less flexible. Lodestar is a huge codebase and different from libraries in some ways. Of course we could just override lint rules were needed but then we lose most of the advantages anyways of reusing from a module and at the same time have less transparency on the lint rules as they are not part of the codebase.

**Comment by wemeetagain** [comment]
I think flexibility isn't so much of a concern here because rules don't change very often.
But flexibility is definitely the tradeoff. The benefit would be consistency.

Also not convinced that lint rules should be different in libraries, can't really think of a case where that should happen.

**Comment by wemeetagain** [comment]
closing since we're now using biome

@nazarhussain it may be worthwhile to bring the biome vs eslint discussion to the chainsafe/eslint-config repo.
