### ISSUE TITLE
beaconBlocksByRange doesn't respect startSlot

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#602]
**Describe the bug**

When requesting blocks by range with start:1, it will return block with slot 0 and onward.
When requesting blocks by range with start: 2, it will return block with slot 2 and onward.

**Expected behavior**

If start:1 block with slot 0 should not be returned

**Comment by aunyks** [comment]
To reproduce this do I just start a client locally and make that RPC call, or did you do another way?

**Comment by mpetrunic** [comment]
I discovered this while syncing. I think you need to create test case with same method calls as in that rpc call response.

**Comment by aunyks** [comment]
I'll investigate.
