### ISSUE TITLE
`ForkName` cannot be used as index type for `sszAllForksLightClient` namespace

### ISSUE THREAD

**Issue by acolytec3** [ChainSafe/lodestar#6024]
### Describe the bug

The `sszAllForksLightClient` namespace export in `@lodestar/types` cannot be indexed by a value of type `ForkName` since `sszAllForksLightClient` does not include `phase0` so Typescript complains.  

### Expected behavior

I should be able to use a value of type `ForkName` (or some alternative like LightClientForkName) as an index type `allForksLightClient` namespace.

### Steps to reproduce

1. `git clone https://github.com/ethereumjs/ultralight.git`
2. `npm i` from the repo root
3. `cd packages/cli`
4. `npx ts-node-esm scripts/bootstrapFinder.ts`

### Additional context

Produces errors like below
![image](https://github.com/ChainSafe/lodestar/assets/17355484/cd7d9b53-8a9c-4243-b451-ebbc8e9d4b3e)

I have to use `//@ts-ignore` in places like [this](https://github.com/ethereumjs/ultralight/blob/d2a2cb48d6526babc9f8a80b8c8c12957786f398/packages/cli/scripts/bootstrapFinder.ts#L37) in order to use the `ForkName` value provided from some Light Client data structure provided by the lodestar API when using the `sszAllForksLightClientSSZTypes` namespace.

### Operating system

Linux

### Lodestar version or commit hash

Lodestar version 1.11.0

**Comment by acolytec3** [comment]
cc @g11tech this is the issue you and I discussed a while back.  Seems like a likely solution would be to create a new `LightClientForkName` enum that we could cast `ForkName` to when we know/can be confident the data type we're getting back from `@lodestar/api` should be a fork with light client data structures included in it.

**Comment by acolytec3** [comment]
I've partially solved it within Ultralight in this [PR](https://github.com/ethereumjs/ultralight/pull/475)

**Comment by g11tech** [comment]
Ahh yea, I will look into this

**Comment by wemeetagain** [comment]
@acolytec3 I think this may be resolved in newer versions? We refactored our types a while ago.

**Comment by acolytec3** [comment]
Thanks! Will take a look at some point.  Our current setup is stable but we need to clean up how we handle the forks for the future.  Will close here for now.
