### ISSUE TITLE
lodestar/prover eth_getBlockByNumber doesn't work correctly

### ISSUE THREAD

**Issue by rdvorkin** [ChainSafe/lodestar#6032]
### Describe the bug

getExecutionPayloadForBlockNumber gets called here https://github.com/ChainSafe/lodestar/blob/unstable/packages/prover/src/proof_provider/payload_store.ts#L97
with min blocknumber stored and the requested blocknumber
But getExecutionPayloadForBlockNumber seems to accept a beacon slot and not min block as parameter, therefore later in the code it tries to fetch a beacon block for an el block number and fails
https://github.com/ChainSafe/lodestar/blob/unstable/packages/prover/src/utils/consensus.ts#L82
https://github.com/ChainSafe/lodestar/blob/unstable/packages/prover/src/utils/consensus.ts#L14

### Expected behavior

using the verified provider to call eth_getBlockByNumber should work 

### Steps to reproduce

```typescript
import Web3 from “web3”;
import { createVerifiedExecutionProvider, LCTransport } from “@lodestar/prover”;
import { LogLevel } from “@lodestar/logger”;
const network = “mainnet”;
const beaconApiUrl = “https://lodestar-mainnet.chainsafe.io”;
const elRpcUrl = “https://lodestar-mainnetrpc.chainsafe.io”;
const checkpoint =
 “0xcc8251d86c07d31c2afd7edda6df5896d7b8b721b4402557f1a8de4a5965ae09”;
const { provider, proofProvider } = createVerifiedExecutionProvider(
 new Web3.providers.HttpProvider(elRpcUrl),
 {
  transport: LCTransport.Rest,
  urls: [beaconApiUrl],
  network: network,
  wsCheckpoint: checkpoint,
  logLevel: LogLevel.info,
 }
);
const verifiedWeb3 = new Web3(provider);
const blockNum = 17956161;
const verifiedBlock = await verifiedWeb3.eth.getBlock(blockNum);
console.log(verifiedBlock);

```

### Operating system

macOS

### Lodestar version or commit hash

1.11.1

**Comment by wemeetagain** [comment]
cc @nazarhussain

**Comment by jeluard** [comment]
@rdvorkin You might want to give a try to this [branch](https://github.com/ChainSafe/lodestar/pull/6442). Let me know if it helps! We'll merge this soon in `unstable`.
