### ISSUE TITLE
Handling environment variables prefixed with `LODESTAR`

### ISSUE THREAD

**Issue by hamidmuslih** [ChainSafe/lodestar#6045]
### Problem description

Recently, Stakewise faced an issue of deploying the Lodestar CL client on K8s.  

They prefixed `lodestar` word in the helm release name which was breaking the deployment. More specifically, the pod was throwing the below error. 
```
✖ Unknown argument:
```

We found out that K8s provide some predefined environmental variables based on the helm release name inside the pod and also the Lodestar binary picks any environmental variable that is prefixed with the `LODESTAR` word, therefore, it was breaking the deployment. 

### Solution description

As per discussion with Nico, we may need to recheck this behavior and see how to improve it as well as document it.  

### Additional context

As Nico pointed out, here is how Geth is handling a similar issue:
- https://github.com/ethereum/go-ethereum/pull/28119

**Comment by nflaig** [comment]
Closing as this issue is now documented, see [Troubleshooting Lodestar](https://chainsafe.github.io/lodestar/faqs/#troubleshooting-lodestar)
