### ISSUE TITLE
Implement POST endpoints for validators and validator_balances

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#6058]
- https://github.com/ethereum/beacon-APIs/pull/367

**Comment by lazyfuhrer** [comment]
Hey May I work on this issue ? @nflaig

**Comment by nflaig** [comment]
That would be great, I assigned the issue to you

**Comment by lazyfuhrer** [comment]
Great, but I see the PR you mentioned is already merged. Is it relevant now ?

**Comment by philknows** [comment]
Hi @lazyfuhrer , if you're still working on this and have any questions on how to potentially implement this, please feel free to join the ChainSafe Discord and find us on the lodestar group of channels!

**Comment by nflaig** [comment]
This is really straight forward to implement and we should consider including that in the next release as for example Teku VC calls this API by default and has to fallback to GET API if it gets a 404.

Related issue https://github.com/Consensys/teku/issues/8118#issuecomment-2043814649
