### ISSUE TITLE
Importing `@lodestar/types` fails, it's unusable

### ISSUE THREAD

**Issue by mbaranovski** [ChainSafe/lodestar#6076]
### Describe the bug

Importing `@lodestar/types` fails, cannot make it work.

### Expected behavior

One can import and use the `@lodestar/types` module

### Steps to reproduce

1. Clone repo: https://github.com/mbaranovski/deleteme
2. Run `npm i`
3. Run `npm run test`
4. Obeserve `ERROR: src/main.ts:5:21 - error TS2307: Cannot find module '@lodestar/types' or its corresponding type declarations.`
5. Change `moduleResolution` in `tsconfig.json` to `node`, re-run 3. and observe: `Cannot find module '@lodestar/types' from 'src/main.ts'`

### Operating system

macOS

### Lodestar version or commit hash

@lodestar/types 1.11.3

**Comment by mbaranovski** [comment]
I had to do a full conversion to ESM modules for the Jest to start working. I followed this [guide](https://www.ryanmr.com/posts/swc-esm-jest-config/).
Pasting my files in case someone has similar issues.

package.json - must include `"type": "module"`
tsconfig.json
```
{
  "compilerOptions": {
    "target": "es2022",
    "module": "NodeNext",
    "lib": ["ES2022"],
    "moduleResolution": "NodeNext",
    "rootDir": "./",
    "outDir": "build",
    "allowSyntheticDefaultImports": true,
    "importHelpers": true,
    "alwaysStrict": true,
    "sourceMap": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitAny": false,
    "noImplicitThis": false,
    "strictNullChecks": false,
    "baseUrl": "./",
    "paths": {
      "@/*": ["src/*"]
    }
  }
}
```

setup-jest.js
```
import * as td from 'testdouble'
import { jest } from '@jest/globals'
import matchers from 'jest-extended'

expect.extend(matchers)

afterEach(function () {
  td.reset()
  jest.useRealTimers()
})
```

jest.config.cjs
```
module.exports = {
  transform: {
    '^.+\\.(t|j)sx?$': '@swc/jest',
  },
  extensionsToTreatAsEsm: ['.ts', '.tsx'],
  setupFilesAfterEnv: ['<rootDir>/setup-jest.js'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^(\\.{1,2}/.*)\\.js$': '$1',
  },
  resetMocks: true,
  workerThreads: true,
}
```

### Important
You need to run tests with `node --experimental-vm-modules ./node_modules/jest/bin/jest.js`

**Comment by nflaig** [comment]
I quickly looked at this yesterday but couldn't figure it out, wanted to look at it again today but glad you figured out a solution and thanks for sharing it here.

We recently started to migrate from mocha to vitest, and jest was also considered as an option ,see https://github.com/ChainSafe/lodestar/pull/6028 for details.

This PR highlights the following for jest
> As of latest version of Jest 29.7 the Jest support for [ESM modules are still experimental ](https://jestjs.io/docs/ecmascript-modules)while the Vitest is all build on EMS and support it natively.

Maybe there is a simpler way to make your setup work, @nazarhussain might have some suggestions.

Wondering if there is anything we could do on our end to make this less painful, but I guess at some point ESM will be the default everywhere and those issues will go away..
