### ISSUE TITLE
Rejected Voluntary Exit on mainnet

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#6077]
### Describe the bug

Investigate rejected voluntary exit on mainnet nodes

<img width="1301" alt="Screenshot 2023-10-31 at 19 53 05" src="https://github.com/ChainSafe/lodestar/assets/10568965/3cbc06c7-55af-4ece-b861-cb8802f3af7d">

### Expected behavior

No rejected messages, or find out what's the reason

### Operating system

Linux

### Lodestar version or commit hash

v1.11.3

**Comment by wemeetagain** [comment]
closing as stale
