### ISSUE TITLE
Increasing event loop lag on network thread

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#6078]
### Describe the bug

`set_immediate` event loop lag keeps increasing until the node is restarted

<img width="1297" alt="Screenshot 2023-10-31 at 20 05 40" src="https://github.com/ChainSafe/lodestar/assets/10568965/a80f6f52-3802-42c9-a9fb-ab10f5b16cf1">

### Expected behavior

consistent event loop lag

### Operating system

Linux

### Lodestar version or commit hash

v1.11.3

**Comment by twoeths** [comment]
this is respective to `gc pause time rate` metric

<img width="1309" alt="Screenshot 2023-10-31 at 20 08 24" src="https://github.com/ChainSafe/lodestar/assets/10568965/f2b6789a-c2a6-4a2a-aceb-59ad8346d957">

**Comment by twoeths** [comment]
note that this issue only happens with mainnet nodes with connected validators, not with test mainnet node (even through it connects through all subnets)

**Comment by wemeetagain** [comment]
closing this issue since the behavior is no longer seen.
Instead, now, heap/gc/event loop lag increase _but_ plateau after a while

![Screenshot from 2024-10-22 15-11-46](https://github.com/user-attachments/assets/adb8cdd9-b6cb-497c-a0d6-c922a55134d4)
