### ISSUE TITLE
Spiked external memory on network thread

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#6106]
### Describe the bug

Since at least v1.11.0, this happens randomly on network thread

<img width="836" alt="Screenshot 2023-11-14 at 08 14 36" src="https://github.com/ChainSafe/lodestar/assets/10568965/4f657ea4-8722-48e4-8a0d-9fd7b220a085">

when that happened gc spiked a bit too

<img width="814" alt="Screenshot 2023-11-14 at 08 15 12" src="https://github.com/ChainSafe/lodestar/assets/10568965/adb1880b-b296-40e9-a2ca-d3b8838df852">

### Expected behavior

stable external memory on network thread

### Operating system

Linux

### Lodestar version or commit hash

v1.11.0

**Comment by twoeths** [comment]
still an issue with v1.13 and potentially v1.14

<img width="1324" alt="Screenshot 2024-01-12 at 18 24 48" src="https://github.com/ChainSafe/lodestar/assets/10568965/86ae5740-9203-4fb2-889a-9dc3cb3488ac">

need to double check after `batchPublish` option is available https://github.com/ChainSafe/js-libp2p-gossipsub/pull/480

note that I don't see this issue with test mainnet nodes (nodes with no validator) so perhaps it's the issue in publish flow

**Comment by wemeetagain** [comment]
closing as stale, no longer visible in metrics
