### ISSUE TITLE
AttesterSlashings causes `gc` spiked on mainnet nodes

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#6112]
### Describe the bug

This is on the stable and unstable mainnet node, since ~~v1.12.0~~ Nov 14 `gc` rate increased significantly

<img width="1335" alt="Screenshot 2023-11-17 at 09 31 31" src="https://github.com/ChainSafe/lodestar/assets/10568965/eb6da9e9-d104-442b-b040-bcd41d0f860e">

Epoch transition increased at the same time

<img width="839" alt="Screenshot 2023-11-19 at 05 59 40" src="https://github.com/ChainSafe/lodestar/assets/10568965/ce288607-3e9e-4364-957e-20f1bac425f5">

However it's significantly better on the 1k and md16 md64 goerli node 

<img width="1331" alt="Screenshot 2023-11-17 at 09 32 21" src="https://github.com/ChainSafe/lodestar/assets/10568965/0c1144d3-a452-4ef2-8cfc-7150f3f3f91d">

### Expected behavior

`gc` rate is the same or less compared to v1.11.x, or give an explanation on the difference

### Operating system

Linux

### Lodestar version or commit hash

v1.12.0

**Comment by twoeths** [comment]
Update: need to ignore 1k, md16, md64 nodes due to the spiked epoch transition time issue https://github.com/ChainSafe/lodestar/issues/6063

**Comment by twoeths** [comment]
This may not link to v1.12.0, could be because node processes more AtterterSlashing messages recently on mainnet. Found this on a node of 64 validators:

<img width="1332" alt="Screenshot 2023-11-17 at 16 49 28" src="https://github.com/ChainSafe/lodestar/assets/10568965/69d62890-9f0c-4abc-b12c-00465817a511">

This links to the recent high AttesterSlashing messages

<img width="1334" alt="Screenshot 2023-11-17 at 16 49 58" src="https://github.com/ChainSafe/lodestar/assets/10568965/6e8acd88-8e2a-4ed7-9419-fb81c13adab0">

note that AtterterSlashing uses BigInt which may cause memory and performance issue to our node, see #5892

**Comment by twoeths** [comment]
also the `gc` increased at the same time

<img width="1341" alt="Screenshot 2023-11-17 at 17 21 48" src="https://github.com/ChainSafe/lodestar/assets/10568965/6edf4998-f31c-470d-be10-0ddbed9d38eb">

**Comment by twoeths** [comment]
Confirm that there are a lot of validators get slashed on Nov 14 https://beaconcha.in/validators/slashings

**Comment by twoeths** [comment]
node wasn't able to recover since Nov 14

<img width="1343" alt="Screenshot 2023-11-21 at 13 01 43" src="https://github.com/ChainSafe/lodestar/assets/10568965/9174c0cf-000b-4bd6-a12e-6ca86ab89528">

<img width="1331" alt="Screenshot 2023-11-21 at 13 01 57" src="https://github.com/ChainSafe/lodestar/assets/10568965/cad780e6-23f8-4e03-bb0f-8decf033de44">

**Comment by wemeetagain** [comment]
@twoeths can this be closed?

**Comment by twoeths** [comment]
yes we upgraded NodeJS so not sure BigInt is an issue, and haven't seen this for a while
