### ISSUE TITLE
Unexpected reserved word

### ISSUE THREAD

**Issue by realsteel85** [ChainSafe/lodestar#6117]
### Describe the bug

 Started Lodestar Consensus Validator Client (Goerli).
Nov 21 10:53:09 testnet lodestar[646414]: file:///usr/local/bin/lodestar/packages/cli/bin/lodestar.js:3
Nov 21 10:53:09 testnet lodestar[646414]: await import("../lib/index.js");
Nov 21 10:53:09 testnet lodestar[646414]: ^^^^^
Nov 21 10:53:09 testnet lodestar[646414]: SyntaxError: Unexpected reserved word
Nov 21 10:53:09 testnet lodestar[646414]:     at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
Nov 21 10:53:09 testnet lodestar[646414]:     at async link (internal/modules/esm/module_job.js:42:21)
Nov 21 10:53:09 testnet systemd[1]: lodestarvalidator.service: Main process exited, code=exited, status=1/FAILURE

### Expected behavior

Start lodestar validator

### Steps to reproduce

1 `
[Unit]
Description=Lodestar Consensus Validator Client (Goerli)
Wants=network-online.target
After=network-online.target
[Service]
User=lodestarvalidator
Group=lodestarvalidator
Type=simple
Restart=always
RestartSec=5
WorkingDirectory=/usr/local/bin/lodestar
ExecStart=/usr/local/bin/lodestar/lodestar validator \
  --network goerli \
  --dataDir /var/lib/lodestar/validators \
  --suggestedFeeRecipient 0xxx \
  --graffiti "<yourgraffiti>"
[Install]
WantedBy=multi-user.target
`
2 `sudo systemctl start lighthousevalidator.service`

### Operating system

Linux

### Lodestar version or commit hash

v1.12

**Comment by nflaig** [comment]
What's your node version? See [prerequisites](https://chainsafe.github.io/lodestar/install/source/#prerequisites)

**Comment by realsteel85** [comment]
V20.9.0 (default)

When i run in direct (as sudo)
sudo ./lodestar validator   --network goerli   --dataDir /var/lib/lodestar/validators   --suggestedFeeRecipient 0xXX  --graffiti "<yourgraffiti>"

file:///home/ewart/lodestar/packages/cli/bin/lodestar.js:3
await import("../lib/index.js");
^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

**Comment by nflaig** [comment]
> When i run in direct (as sudo)

could you please check what node version is installed for your root user or for the `lodestarvalidator` user which is the one that runs Lodestar

**Comment by E1458** [comment]
Ubuntu 22.04.3 LTS, node v20.10.0. Git cloned the current head and built from source: yarn install, yarn run build, no error. Set up a systemd service running as a dedicated user 'lodestar'. I get exactly the same error at the same location as reported by @realsteel85. I even re-installed node again (via nvm) under the user 'lodestar' but no good.  

-EDIT: I think I overlooked this part of the documentation: "_Node Version Manager (NVM) will only install NodeJS for use with the active user. If you intend on setting up Lodestar to run under another user, we recommend using [NodeSource's source for NodeJS](https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions) so you can install NodeJS globally._". After installing the "NodeSource" as directed, the error is gone and Lodestar is running OK.

**Comment by nflaig** [comment]
Nvm does not work well with systemd, there are [workarounds](https://gist.github.com/joepie91/73ce30dd258296bd24af23e9c5f761aa) to make it work but as you noted @E1458 the easiest solution is to install node globally.

@realsteel85 your globally installed node version is likely outdated

**Comment by realsteel85** [comment]
fixed, thnxs
