### ISSUE TITLE
"Eth-Consensus-Version" header absent in eth/v2/debug/beacon/states/{state_id} response

### ISSUE THREAD

**Issue by jshufro** [ChainSafe/lodestar#6123]
### Describe the bug

```
curl -H "Accept: application/octet-stream;q=1,application/json;q=0.9" -Ssv "http://consensus:5052/eth/v2/debug/beacon/states/finalized" > /dev/null                          
*   Trying 172.21.0.12:5052...
* Connected to consensus (172.21.0.12) port 5052
> GET /eth/v2/debug/beacon/states/finalized HTTP/1.1
> Host: consensus:5052
> User-Agent: curl/8.4.0
> Accept: application/octet-stream;q=1,application/json;q=0.9
> 
< HTTP/1.1 200 OK
< vary: Origin
< access-control-allow-origin: *
< content-type: application/octet-stream
< content-length: 213503710
< Date: Thu, 23 Nov 2023 04:46:56 GMT
< Connection: keep-alive
< Keep-Alive: timeout=72
< 
{ [14263 bytes data]
* Connection #0 to host consensus left intact
```

### Expected behavior

`Eth-Consensus-Version` header should be set, as required by https://ethereum.github.io/beacon-APIs/#/Debug/getStateV2

![image](https://github.com/ChainSafe/lodestar/assets/116244/d3ef8f21-1a24-4894-b30c-311e56f51672)

### Operating system

Linux

### Lodestar version or commit hash

v1.12.0

**Comment by nflaig** [comment]
Did you face issues with that after updating the go http client? Same issue happens with the latest checkpointz version which also expects the `Eth-Consensus-Version` header to be set (https://github.com/ChainSafe/lodestar/issues/6124).

We are not following the spec here, this will be addressed by API rework done in https://github.com/ChainSafe/lodestar/pull/6080

**Comment by jshufro** [comment]
Well, I was hitting this error, then I upgraded the attestantio http client so I could toggle the EnforceJson switch which sets `Accept` to exclude ssz, and then I hit the `Invalid string length` one.

I switched my holesky test environment to nimbus for now. Only 3300 validators were down while i migrated :laughing:

**Comment by nflaig** [comment]
> I switched my holesky test environment to nimbus for now. Only 3300 validators were down while i migrated 😆

Sorry to hear that, we have a fix ready for it and might already include that in a hotfix release. Our current API design is lacking a bit, with https://github.com/ChainSafe/lodestar/pull/6080 there will be a bunch of improvements and we will be able to verify that all headers required by spec are set correctly.
