### ISSUE TITLE
Checkpointz v0.18.0 requires "Eth-Consensus-Version" header

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#6124]
### Describe the bug

Latest version of [checkpointz](https://github.com/ethpandaops/checkpointz) requires `Eth-Consensus-Version` header to be set in `eth/v2/debug/beacon/states/{state_id}` response.

Checkpointz errors
```
time="2023-11-15T14:48:17Z" level=error msg="No longer attempting to download historical block - too many failures" failure_count=5 module=beacon/default slot=346240
time="2023-11-15T14:48:29Z" level=error msg="Failed to check for genesis" error="failed to request signed beacon block: failed to parse consensus version: no consensus version header" module=beacon/default
time="2023-11-15T14:48:32Z" level=error msg="Failed to check for new serving checkpoint" error="failed to request signed beacon block: failed to parse consensus version: no consensus version header" module=beacon/default
time="2023-11-15T14:48:44Z" level=error msg="Failed to check for genesis" error="failed to request signed beacon block: failed to parse consensus version: no consensus version header" module=beacon/default
time="2023-11-15T14:48:59Z" level=error msg="Failed to check for genesis" error="failed to request signed beacon block: failed to parse consensus version: no consensus version header" module=beacon/default
time="2023-11-15T14:49:03Z" level=error msg="Failed to check for new serving checkpoint" error="failed to request signed beacon block: failed to parse consensus version: no consensus version header" module=beacon/default
time="2023-11-15T14:49:14Z" level=error msg="Failed to check for genesis" error="failed to request signed beacon block: failed to parse consensus version: no consensus version header" module=beacon/default
2023/11/15 14:49:19 http: panic serving 51.159.85.94:21844: runtime error: invalid memory address or nil pointer dereference
goroutine 692 [running]:
net/http.(*conn).serve.func1()
```

Due to this issue we cannot upgrade the checkpoint sync providers to the latest version.

### Expected behavior

`Eth-Consensus-Version` header should be set

### Additional context

Related [discussion with devops team](https://discord.com/channels/593655374469660673/1174355544350408805)

### Operating system

Linux

### Lodestar version or commit hash

v1.12.0

**Comment by pk910** [comment]
Please fix this issue before pushing a new release :)

Lodestar didn't serve SSZ responses earlier, which worked fine with `go-eth2-client`.
Lodestar now serves SSZ responses, but misses the `Eth-Consensus-Version` header, which is actually worse than not serving SSZ at all.
Subsequent libraries like `go-eth2-client` now fail for all endpoints that support SSZ as they do not know how to decode SSZ encoded stuff without the proper version information.

**Comment by nflaig** [comment]
> Please fix this issue before pushing a new release :)

We have a fix ready for it and might already include that in a hotfix release as this affects quite a lot of users.
