### ISSUE TITLE
Update references to consensus spec

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#6127]
> It might be worth updating the consensus-specs link to so that they both point to their respective master branches.

I don't think it good to point to master branch unless there are no tagged versions. We have a bunch of references to the consensus spec, e.g. in the README
https://github.com/ChainSafe/lodestar/blob/3f3a207643f6c35ae4b3cfe683cd167cfe70a2c3/README.md?plain=1#L8

All those references are kinda outdated as we already test against v1.4.0 (which has no major release yet) but could at least update to v1.3.0
https://github.com/ChainSafe/lodestar/blob/3f3a207643f6c35ae4b3cfe683cd167cfe70a2c3/packages/beacon-node/test/spec/specTestVersioning.ts#L18

_Originally posted by @nflaig in https://github.com/ChainSafe/lodestar/issues/6126#issuecomment-1824524736_

**Comment by philknows** [comment]
Yeah the problem with pointing to master is that a lot of references in our code point to a specific tagged version of the consensus-specs for greater accuracy. We should be more proactive with updating these references though, outside of hard forks or another significant milestones (~1/year at this rate).

**Comment by philknows** [comment]
I'll track this for around January. We should aim to do this sometime around each hard fork. Given that January/February we will be starting the transition to Deneb, we should update then.
