### ISSUE TITLE
v1.12: memory leak in network thread for nodes with connected validators

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#6129]
### Describe the bug

Since v1.12.0, there is a memory leak happing on a lot of nodes

<img width="833" alt="Screenshot 2023-11-27 at 09 28 04" src="https://github.com/ChainSafe/lodestar/assets/10568965/872f5486-f7ad-4007-a540-48877047bd35">

while on a test mainnet node with no validator there is no issue

<img width="839" alt="Screenshot 2023-11-27 at 09 30 41" src="https://github.com/ChainSafe/lodestar/assets/10568965/195f7949-f07f-4135-b940-055d8610ea42">

### Expected behavior

no memory leak

### Operating system

Linux

### Lodestar version or commit hash

v1.12.0

**Comment by twoeths** [comment]
at the same time, there is clearly a leak in network thread

<img width="839" alt="Screenshot 2023-11-27 at 10 04 33" src="https://github.com/ChainSafe/lodestar/assets/10568965/693a7bad-0687-4440-b8da-a5e731070336">

**Comment by twoeths** [comment]
the initial chart in Memory Overview is a sum of main thread + discv5 + network. Looks like the memory leaks only happen on network thread since v1.12 cc @wemeetagain

**Comment by philknows** [comment]
Fixed by #6156
