### ISSUE TITLE
Produce phase0 beacon block body once

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#6159]
### Problem description

Right now if both builder and execution block are configured, we produce beacon block body twice. 

### Solution description

We should be able to do it once to speed up the publish process. Also look into other steps to see if we can publish block faster to reduce our reorg percentage https://reorg.pics/

cc @nazarhussain @g11tech

**Comment by g11tech** [comment]
ahh yes, it makes sense now that we have the race from two sources in the beacon itself :+1:
