### ISSUE TITLE
Implement get deposit snapshot API

### ISSUE THREAD

**Issue by jeluard** [ChainSafe/lodestar#6165]
### Problem description

Beacon API v2.4.0 spec requires get deposit snapshot API
- https://github.com/ethereum/beacon-APIs/pull/245

### Solution description

Implement the following route:
- https://ethereum.github.io/beacon-APIs/#/Beacon/getDepositSnapshot

**Comment by nflaig** [comment]
- Duplicate of https://github.com/ChainSafe/lodestar/issues/5697 (see reference in issue for more context)
