### ISSUE TITLE
Improve API schema validation for tests

### ISSUE THREAD

**Issue by jeluard** [ChainSafe/lodestar#6168]
[Beacon APIs v2.4.0](https://github.com/ethereum/beacon-APIs/releases/tag/v2.4.0) introduce a new node [example](https://github.com/ethereum/beacon-APIs/blob/master/apis/node/health.yaml) that do not pass currently on lodestar. 

At first glance it looks related to a [limitation](https://github.com/ChainSafe/lodestar/blob/unstable/packages/api/test/utils/checkAgainstSpec.ts#L68) of the testing framework with schema validation.

```shell
  1) getHealth
       getHealth_request:
     Error: Invalid request against spec schema

/query/syncing_status - must be integer

{"query":{"syncing_status":"206"}}

{"type":"object","properties":{"query":{"type":"object","properties":{"syncing_status":{"type":"integer","minimum":1,"maximum":599}},"required":["syncing_status"]}},"required":["query"]}
```

**Comment by wemeetagain** [comment]
closing as stale
