### ISSUE TITLE
Investigate `--builder.urls` usage

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#6181]
Builder is a bit of an outlier right now, we allow to set multiple URLs via `--builder.urls` but only use the first URL (`opts.urls[0]`). I opted to only log the URL which is actually used.

@g11tech Is it intentional that we don't allow a fallback for the builder? I guess mev-boost is already doing the multiplexing and builder flow is stateful which makes fallback logic a bit problematic.

Maybe we want to reflect that in the CLI as well as currently it looks like it supports multiple urls

![image](https://github.com/ChainSafe/lodestar/assets/38436224/3feb859b-0374-4e33-afc5-df38029f36d7)

_Originally posted by @nflaig in https://github.com/ChainSafe/lodestar/pull/6175#discussion_r1423131914_

**Comment by g11tech** [comment]
Right because of the multiplexing by mev boost , may be we can still multiplex on top but we haven't felt the need so far
