### ISSUE TITLE
BlockV3 API does not return `Eth-Consensus-Version`

### ISSUE THREAD

**Issue by michaelsproul** [ChainSafe/lodestar#6202]
### Describe the bug

Lodestar doesn't return the mandatory `Eth-Consensus-Version` header for [`/eth/v3/validator/blocks/{slot}`](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Validator/produceBlockV3). I'm using the SSZ version of the endpoint.

### Expected behavior

Lodestar should include all mandatory headers.

### Steps to reproduce

I'm running blockdreamer against Lodestar with `v3 = true`.

### Operating system

Linux

### Lodestar version or commit hash

v1.13.0-rc.0

**Comment by michaelsproul** [comment]
Ok so I think I worked out that Lodestar doesn't support the SSZ endpoints. But even the JSON v3 endpoint does not return this header.

**Comment by ensi321** [comment]
> Ok so I think I worked out that Lodestar doesn't support the SSZ endpoints. But even the JSON v3 endpoint does not return this header.

Thanks for pointing this out. As far as I know, `produceBlockV3` doesn't return any of the 4 headers in the spec.

Just curious why you specifically mention `Eth-Consensus-Version`. Is it because blockdreamer doesn't read the other 3 headers, or is it simply because `Eth-Consensus-Version` is the first header it looks for?

**Comment by michaelsproul** [comment]
Yeah, I'm reworking the blockV3 HTTP client in LH (and consequently blockdreamer) and getting it to read the consensus header to work out how to to parse the response. I'm now re-reworking it to get it to read the JSON values instead/as well. This will hopefully enable blockdreamer to start working with Lodestar immediately, which may detect other issues. I also found a Lighthouse bug in the process (we weren't returning the metadata fields in the JSON response, _just_ the headers).

**Comment by nflaig** [comment]
yeah, we are not setting proper headers right now and ssz responses are also not supported for all required apis. We are working on a refactoring that will address both those issues https://github.com/ChainSafe/lodestar/pull/6080.

Recently added a fix to add consensus version header to get state and block apis (https://github.com/ChainSafe/lodestar/pull/6152, it's not pretty), could add a quick hotfix to do the same for produceBlockV3 if it that helps out.
