### ISSUE TITLE
Confirmation rule prerequisite

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#6257]
### Problem description

We need some forkchoice changes for the safe execution of the confirmation rule, here's the main PR https://github.com/ethereum/consensus-specs/pull/3339

### Solution description

specified in https://github.com/ethereum/consensus-specs/pull/3431

**Comment by philknows** [comment]
Consensus spec PR will get merged shortly with spec release around Monday. We need to get this out for mainnet fork of Deneb @tuyennhv. Mainnet fork date bit of a moving target depending on testnet performance.
