### ISSUE TITLE
Schedule Chiado testnet Deneb fork (Jan 31)

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#6284]
## Description

Chiado Dencun fork is scheduled

```diff
+DENEB_FORK_VERSION: 0x0400006f
+DENEB_FORK_EPOCH: 516608 # Wed Jan 31 2024 18:15:40 GMT+0000
```

- https://github.com/gnosischain/configs/pull/26

Some config values differ from mainnet

```diff
MAX_REQUEST_BLOCKS_DENEB: 128
# MAX_REQUEST_BLOCKS_DENEB * MAX_BLOBS_PER_BLOCK
MAX_REQUEST_BLOB_SIDECARS: 768
# `2**14` (= 16384 epochs, ~15 days)
-MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS: 4096
+MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS: 16384
# `6`
BLOB_SIDECAR_SUBNET_COUNT: 6
# [New in Deneb:EIP7514]
-MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT: 8
+MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT: 2
```

No preset values differ from mainnet

```diff
FIELD_ELEMENTS_PER_BLOB: 4096
# `uint64(2**12)` (= 4096)
MAX_BLOB_COMMITMENTS_PER_BLOCK: 4096
# `uint64(6)`
MAX_BLOBS_PER_BLOCK: 6
# `floorlog2(get_generalized_index(BeaconBlockBody, 'blob_kzg_commitments')) + 1 + ceillog2(MAX_BLOB_COMMITMENTS_PER_BLOCK)` = 4 + 1 + 12 = 17
KZG_COMMITMENT_INCLUSION_PROOF_DEPTH: 17
```

https://github.com/gnosischain/specs/blob/master/consensus/preset/gnosis/deneb.yaml

**Comment by nflaig** [comment]
What about `MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT`, this seems to be lower on gnosis 2 vs. 8 on mainnet

[mainnet/config.yaml#L77-L78](https://github.com/gnosischain/configs/blob/ff5fbe9aecbf28df9beedb662920eeee537629b0/mainnet/config.yaml#L77-L78)
```yaml
# [New in Deneb:EIP7514] 2*
MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT: 2
```

**Comment by dapplion** [comment]
Updated PR diff and upstream Chiado config, it's was not fully up to date sorry about that! Now it's good to go

**Comment by nflaig** [comment]
It might be better if we extend the chiado config from the gnosis config instead of mainnet in Lodestar, I have to give this another review but I am assuming both networks override the same values

https://github.com/ChainSafe/lodestar/blob/551fd8e4553d07c835e31e2b7939ab5f18c5f95f/packages/config/src/chainConfig/networks/chiado.ts#L7-L8

**Comment by dapplion** [comment]
> It might be better if we extend the chiado config from the gnosis config instead of mainnet in Lodestar

That's a great idea and could save against some edge cases
