### ISSUE TITLE
Complete shuffle() helper function

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/lodestar#63]
The `shuffle()` helper function has been started but not finished:

https://github.com/ChainSafeSystems/lodestar_chain/blob/bbc223926df7d20e0fa6875cad051a4cfe790719/beaconChain/helpers/stateTransitionHelpers.ts#L25-L57

@GregTheGreek whats the blocker on this?

**Comment by GregTheGreek** [comment]
The main blocker was handling bytes (per our conversation a earlier this week) #62 actually implemented it using Buffers, but have a read through the comments and throw in your two sense.

**Comment by GregTheGreek** [comment]
Closed per #62
