### ISSUE TITLE
Handle non-integer builder.boostFactor

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#6302]
We should handle non-integer  builder boost factor especially considering our docs reference the formula that can easily result in a non-integer output.

Possible solutions:
- round or truncate to integer value, possibly w/ warn log
- throw friendly error and shutdown, include documentation update to highlight that

---

> Looks good to me now, applied suggestions from @g11tech and fixed example to use an integer value as `--builder.boostFactor` does not support floating point numbers

_Originally posted by @nflaig in https://github.com/ChainSafe/lodestar/pull/6295#pullrequestreview-1822218092_

**Comment by philknows** [comment]
Should probably do this for the next release for the full feature to be implemented properly.
