### ISSUE TITLE
Incorrect total block value in publish block log

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#6316]
### Describe the bug

The `totalBlockValue` printed out when publish is wrong

```
info: Published block slot=7414120, validator=0x8955…5c2c, graffiti=Lodestar-v1.14.0/d7ca290, executionPayloadSource=engine, executionPayloadBlinded=false, executionPayloadValue=0.01908 ETH, consensusBlockValue=0.02732 ETH, totalBlockValue=27329242.01908 ETH, strictFeeRecipientCheck=false, builderSelection=executiononly, api=produceBlockV3
info: Published block slot=7414416, validator=0x86c0…b87c, graffiti=Lodestar-v1.14.0/d7ca290, executionPayloadSource=engine, executionPayloadBlinded=false, executionPayloadValue=0.00628 ETH, consensusBlockValue=0.02464 ETH, totalBlockValue=24646563.00628 ETH, strictFeeRecipientCheck=false, builderSelection=executiononly, api=produceBlockV3
```

The issue is likely related to https://github.com/ChainSafe/lodestar/pull/6286 as it looks like we missed to remove `gweiToWei` conversion.

https://github.com/ChainSafe/lodestar/blob/d7ca290d173dfa82b2977f3e94df6e5e8d12ef3e/packages/validator/src/services/block.ts#L225-L226

But it needs to be confirmed that this fixes the issue and if there are other places that need to be updated.

### Expected behavior

Should print out correct total block value

### Steps to reproduce

Produce a block with `produceBlockV3` api

### Additional context

- https://github.com/ChainSafe/lodestar/pull/6286

### Operating system

Linux

### Lodestar version or commit hash

d7ca290d173dfa82b2977f3e94df6e5e8d12ef3e

**Comment by nflaig** [comment]
Might also be worth to confirm that `consensusBlockValue` is  correct, I am seeing a lot lower values on https://goerli.beaconcha.in/ but possibly related to the current network conditions and non-finality.

**Comment by ensi321** [comment]
> But it needs to be confirmed that this fixes the issue and if there are other places that need to be updated.

My bad. Took a second look this seems to be the only place I missed. Will do a more thorough testing to confirm.


> Might also be worth to confirm that `consensusBlockValue` is correct, I am seeing a lot lower values on https://goerli.beaconcha.in/ but possibly related to the current network conditions and non-finality.

Not too familiar with the beaconcha.in UI, can you point me where the block proposer reward is? The `Tx Reward` only counts the payload value.

With the two blocks you mentioned, I looked at the consensus income of their proposers.
For slot 7414120, the [proposer](https://goerli.beaconcha.in/validator/462443#charts) has a consensus income of 0.02896 ETH on that day, minus other duties ~0.002ETH so its reward for proposing that block should be around 0.02696ETH which is close to what we have.
For slot 7414416, the [proposer](https://goerli.beaconcha.in/validator/461984#charts) has a consensus income of 0.02628 ETH on that day, minus other duties ~0.002ETH so its reward for proposing that block should be around 0.02428ETH which is close to what we have.

**Comment by nflaig** [comment]
> can you point me where the block proposer reward is?

I don't think they have a per block consensus reward, I also just looked at the Daily Income panel which shows a different, more correct value now. From [their api docs](https://goerli.beaconcha.in/api/v1/docs/index.html#/) I also don't see a way to get the rewards.

I guess the best way to confirm this is to compare the rewards APIs of clients and see if results are the same. But based on current data I don't see an issue with the calculation we have.
