### ISSUE TITLE
Performance issue getting eth1DataAndDeposits for block production

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#6335]
### Describe the bug

It takes up to 5.84s to get `eth1DataAndDeposit` for block production for a mainnet node

<img width="1331" alt="Screenshot 2024-01-22 at 11 14 46" src="https://github.com/ChainSafe/lodestar/assets/10568965/07ff1172-d466-4e6a-afdb-a860a5e93a19">

### Expected behavior

this issue rarely happen, actually it's the 1st time I see it takes >1s, most of the time it should take <=50ms

### Operating system

Linux

### Lodestar version or commit hash

v1.14.0

**Comment by nazarhussain** [comment]
> actually it's the 1st time I see it takes >1s

@tuyennhv Should we not wait additional occurrence with such hype to mark it a bug? If it's just once ever, there could not some non-code related issue.

**Comment by twoeths** [comment]
> Should we not wait additional occurrence with such hype to mark it a bug? If it's just once ever, there could not some non-code related issue.

I believe it's a code issue, we should try to reproduce it in a benchmark test first instead of waiting for new occurrences

**Comment by philknows** [comment]
Can you confirm @tuyennhv that we're no longer seeing this? I took a look at some of our mainnet Lido nodes and it doesn't seem to be that bad on v1.16

**Comment by twoeths** [comment]
haven't seen this issue for a while, closing now. Will reopen if we see it again
