### ISSUE TITLE
Error: Unable to fetch weak subjectivity state: This operation was aborted

### ISSUE THREAD

**Issue by ZhDg1998** [ChainSafe/lodestar#6360]
I am using Docker Compose to install and run Lodestar as a beacon node, but I encountered the following issue during runtime. Here is my Docker Compose configuration:
![1706347471410](https://github.com/ChainSafe/lodestar/assets/41477084/78fe5e39-e7f6-419f-9090-bcd7657e1b3c)

However, the logs of Lodestar contain the following errors:
![1706347539692](https://github.com/ChainSafe/lodestar/assets/41477084/c93fa3ca-6241-4701-ac51-d97d3a190eb5)

anyone can solve ?

**Comment by nflaig** [comment]
> anyone can solve ?

I don't see any issue in your configuration. I have just tested this an was able to download state from https://checkpoint.gnosischain.com.

Maybe there was an issue with the checkpoint sync server.

**Comment by ZhDg1998** [comment]
> > anyone can solve ?
> 
> I don't see any issue in your configuration. I have just tested this an was able to download state from https://checkpoint.gnosischain.com.
> 
> Maybe there was an issue with the checkpoint sync server.

What can I do? Just wait? It was fine before, very strange.

**Comment by nflaig** [comment]
> What can I do? Just wait? It was fine before, very strange.

The checkpoint server seems fine, maybe there are other issues with your network. The download should be really fast as the state for gnosis chain is not that big, bit strange that it is running into a timeout.

Other option would be to remove `--checkpointSyncUrl` flag and let the node sync by itself, or at least you would see if your node is able to connect to peers

**Comment by ZhDg1998** [comment]
> > What can I do? Just wait? It was fine before, very strange.
> 
> The checkpoint server seems fine, maybe there are other issues with your network. The download should be really fast as the state for gnosis chain is not that big, bit strange that it is running into a timeout.
> 
> Other option would be to remove `--checkpointSyncUrl` flag and let the node sync by itself, or at least you would see if your node is able to connect to peers

thanks for your help,i'll try to remove and wait ,thanks again!

**Comment by ZhDg1998** [comment]
after i remove flag:
this is lodestar log:
![1706351443032](https://github.com/ChainSafe/lodestar/assets/41477084/237bea54-8edb-42e4-acc5-b2e62f13c8d1)
![1706351513581](https://github.com/ChainSafe/lodestar/assets/41477084/e12d839f-9098-45b7-a483-ff8f1d809644)

and erigon log:
![1706351478421](https://github.com/ChainSafe/lodestar/assets/41477084/e2fc77f3-ffda-44f4-9fb0-eb796b3e50cf)
![1706351537734](https://github.com/ChainSafe/lodestar/assets/41477084/e19ebf12-5103-42f3-b57c-6ee1c4d6f239)

**Comment by nflaig** [comment]
It looks like your node has issues connecting to peers as well. Based on the logs it looks like a networking issue, see also the Erigon error.

I am honestly not sure how to resolve this without knowing more details about your setup, it does not look like an issue with the client itself.

Better to move this discussion to discord as github is not great to debug such issues, could make sense to bring this up in eth-staker or gnosis discord, maybe someone had a similar issue before.

And feel free to join the [Chainsafe discord](https://discord.gg/tvdwcAz4), can continue debugging in #lodestar-help channel if you are not able to find a solution for this.
