### ISSUE TITLE
Add known issues page to docs

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#6378]
As discussed in standup, we should set up a known issues page to mentioned common issues and make them searchable in the docs.

e.g. good candidate to start with is to document k8s / helm behavior in combination with Lodestar env vars
- https://github.com/ChainSafe/lodestar/issues/6045

**Comment by philknows** [comment]
I started on a draft template on an FAQs page. I'd like to make this page somewhat visually appealing as there may be a lot of content in here that should be easily discoverable and accessible. Was thinking of using admonitions such as this, but unsure if the question should remain in the title at all. Open for comments.
<img width="1268" alt="Screenshot 2024-01-30 at 5 31 43 PM" src="https://github.com/ChainSafe/lodestar/assets/58080811/b7b2e94c-6ed9-4d4b-80e1-034fbf19711f">

**Comment by nflaig** [comment]
> but unsure if the question should remain in the title at all

if we can formulate a precise title which is not too long I think that is likely the best solution

I am also not sure if for this specific issue a Question is the right term, because when you encounter this issue you don't even know it is related to environment variables as the error is really ambiguous.

The title would be rather something like "Unknown arguments error on Kubernetes" (or similar), and then we explain why it happens and how to resolve it.

> make this page somewhat visually appealing as there may be a lot of content in here

Might be a bit verbose if we expect a lot of content to be listed here, generally a fan of simplicitly but if visual elemnts support readability I am all for it
