### ISSUE TITLE
Ignore known blocks submitted through API

### ISSUE THREAD

**Issue by eth2353** [ChainSafe/lodestar#6397]
### Describe the bug

I believe this is a similar issue to #6021 - the beacon node API returns an error ( `BLOCK_ERROR_ALREADY_KNOWN` ) when a validator client submits a block that the beacon node has already seen. We see this happening in our DVT setup.

### Expected behavior

Ideally it would not return with an error status code, since nothing went "really wrong".  Would be great if this error could be "ignored" too.

### Additional context

`Error: BLOCK_ERROR_ALREADY_KNOWN`
`error: Gossip validations failed while publishing the block broadcastValidation=gossip, blockRoot=0x7d24e12894a9cfd45aaf2dd3639c472cba9768c49ca7efba8329f5c0e7309162, bodyRoot=0x920d9d0b98ebe4aaaeb5e8ad91b7eef64b7f55e011877f8a2e31cfc275f0adad, blockLocallyProduced=false, slot=939786, code=BLOCK_ERROR_ALREADY_KNOWN, root=0x7d24e12894a9cfd45aaf2dd3639c472cba9768c49ca7efba8329f5c0e7309162`
`error: Req req-8xfv publishBlindedBlockV2 error code=BLOCK_ERROR_ALREADY_KNOWN, root=0x7d24e12894a9cfd45aaf2dd3639c472cba9768c49ca7efba8329f5c0e7309162`

### Operating system

Linux

### Lodestar version or commit hash

v1.15.0/5d93a62

**Comment by nflaig** [comment]
Thanks for reporting this!

I thought this was already covered by https://github.com/ChainSafe/lodestar/pull/5714 and https://github.com/ChainSafe/lodestar/pull/5405 but it looks like we only ignore if we publish a blinded block. Should be easy to fix.
