### ISSUE TITLE
override default libp2p pubsub message-id to be content-addressed 

### ISSUE THREAD

**Issue by ColinSchwarz** [ChainSafe/lodestar#643]
v0.9.4: (ethereum/eth2.0-specs#1538)

**Comment by twoeths** [comment]
Waiting for https://github.com/ChainSafe/lodestar/pull/610

**Comment by twoeths** [comment]
Need to rework once this PR is merged and gossipsub-js released: https://github.com/ChainSafe/gossipsub-js/pull/67
