### ISSUE TITLE
add quick clarifying note on STATUS message

### ISSUE THREAD

**Issue by ColinSchwarz** [ChainSafe/lodestar#644]
v0.9.4:  (ethereum/eth2.0-specs#1540)

**Comment by twoeths** [comment]
Probably we only need to add the same note to our implementation.

**Comment by twoeths** [comment]
Oh it seems like we haven't implemented this
```
Once the handshake completes, the client with the lower finalized_epoch or head_slot (if the clients have equal finalized_epochs) SHOULD request beacon blocks from its counterparty via the BeaconBlocksByRange request.
```

**Comment by twoeths** [comment]
That initial `BeaconBlocksByRange` was done in `FastSync`.

@mpetrunic can we close this issue?

**Comment by mpetrunic** [comment]
yeah, it's seems that it gets refresh, haven't really figured out why
