### ISSUE TITLE
Update retry function

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#6447]
Current behavior of `retry` function is confusing, we have a option called `retries` but it actually means attempts and not retries, i.e. `retries=1`, will just call the function once.

https://github.com/ChainSafe/lodestar/blob/4c09412ed2c8a94b585d5dba1fe94bc9e2d56a35/packages/utils/src/retry.ts#L27

We should consider renaming this option to either `attempts` or follow more common pattern used in other libraries such as [retry](https://www.npmjs.com/package/retry) and [retry-request](https://www.npmjs.com/package/retry-request) which if `retries=1` will call the function and on failure will retry it once.

**Comment by FaybianB** [comment]
@nflaig May I be assigned this issue?
