### ISSUE TITLE
Rss increased since around Feb 07

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#6468]
### Describe the bug

this is unstable mainnet node

<img width="1328" alt="Screenshot 2024-02-22 at 09 33 57" src="https://github.com/ChainSafe/lodestar/assets/10568965/03cc1261-a641-48c9-a05c-6f7ffcad1e2a">

### Expected behavior

rss should be around ~7GB like in stable node

<img width="1318" alt="Screenshot 2024-02-22 at 09 35 38" src="https://github.com/ChainSafe/lodestar/assets/10568965/28e6ec18-9fb0-4400-9e27-beecebc42425">

### Operating system

Linux

### Lodestar version or commit hash

unstable

**Comment by philknows** [comment]
I started seeing some very spiky RSS around this time too... much more severe starting Feb 6. And the only major thing done around that time was upgrading gossipsub here https://github.com/ChainSafe/lodestar/pull/6399 🤔

**Comment by twoeths** [comment]
yes got similar issues in the past when we upgrade gossipsub. If it's consistently takes not much higher memory than previous version then it's acceptable with lodestar, otherwise it needs to be investigated

**Comment by matthewkeil** [comment]
Profiles from `1.16.1-rc.1`

[v1.16.0-rc.1_feat1-lg1k-hzax41_network.cpuprofile](https://github.com/ChainSafe/lodestar/files/14476535/v1.16.0-rc.1_feat1-lg1k-hzax41_network.cpuprofile)
[v1.16.0-rc.1_feat1-mainnet-hzax41_network.cpuprofile](https://github.com/ChainSafe/lodestar/files/14476536/v1.16.0-rc.1_feat1-mainnet-hzax41_network.cpuprofile)
[v1.16.0-rc.1_feat1-md64-hzax41_network.cpuprofile](https://github.com/ChainSafe/lodestar/files/14476537/v1.16.0-rc.1_feat1-md64-hzax41_network.cpuprofile)
[v1.16.0-rc.1_feat1-lg1k-hzax41_main.cpuprofile](https://github.com/ChainSafe/lodestar/files/14476539/v1.16.0-rc.1_feat1-lg1k-hzax41_main.cpuprofile)
[v1.16.0-rc.1_feat1-mainnet-hzax41_main.cpuprofile](https://github.com/ChainSafe/lodestar/files/14476541/v1.16.0-rc.1_feat1-mainnet-hzax41_main.cpuprofile)
[v1.16.0-rc.1_feat1-md64-hzax41_main.cpuprofile](https://github.com/ChainSafe/lodestar/files/14476542/v1.16.0-rc.1_feat1-md64-hzax41_main.cpuprofile)

**Comment by philknows** [comment]
Do you have a commit ID for these ones @matthewkeil ? We don't "officially" have a 1.16.1-rc.1 tagged to reference.

**Comment by matthewkeil** [comment]
@philknows it is sha fda3b19

**Comment by wemeetagain** [comment]
closing as stale
