### ISSUE TITLE
Split ssz and bls into separate repos

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#650]
SSZ and BLS are both more suitable as separate repos, as they get regularly on a different cycle than lodestar and have mostly separate concerns from lodestar.

We should split out ssz and bls into separate repos (like they once were :disappointed: )

**Comment by twoeths** [comment]
https://github.com/ChainSafe/lodestar/pull/663

**Comment by twoeths** [comment]
Is this done @wemeetagain ?

**Comment by wemeetagain** [comment]
:+1:  this has been completed
