### ISSUE TITLE
Migrate to docusaurus

### ISSUE THREAD

**Issue by jeluard** [ChainSafe/lodestar#6517]
Migrate existing [docs](https://github.com/ChainSafe/lodestar/tree/unstable/docs) (using [mkdocs](https://www.mkdocs.org/)) to [docusaurus](https://docusaurus.io/). Find details about the rationale [here](https://github.com/ChainSafe/lodestar/discussions/6493#discussioncomment-8631313).

Following items have to be done:

* [x] https://github.com/ChainSafe/lodestar/pull/6533
* [ ] https://github.com/ChainSafe/lodestar/issues/6550
* [ ] https://github.com/ChainSafe/lodestar/issues/6548 (see https://github.com/ChainSafe/lodestar/pull/6559)
* [x] https://github.com/ChainSafe/lodestar/issues/6549
* [ ] https://github.com/ChainSafe/lodestar/issues/6547
* [ ] https://github.com/ChainSafe/lodestar/issues/6575
* [x] https://github.com/ChainSafe/lodestar/pull/6566
* [x] https://github.com/ChainSafe/lodestar/pull/6560

# Link redirection

Docs are currently hosted as [gh-pages](https://github.com/ChainSafe/lodestar/tree/gh-pages). If we keep this hosting, redirect will have to be handled at the website level (as opposed to HTTP level).

* https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects

# Resources

* https://handbook.chainsafe.io/development/documentation/
* https://github.com/lerna/lerna/tree/main/website
* https://github.com/Consensys/doc.teku
* https://github.com/risc0/risc0/tree/main/website
* https://github.com/facebook/docusaurus/tree/main/website

**Comment by philknows** [comment]
Related #5961

**Comment by wemeetagain** [comment]
closing as complete
