### ISSUE TITLE
Grafana shows warning if metric name does not follow naming convention

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#6627]
Grafana now shows a warning on panels that use PromQL queries that use functions like `rate()` which only work on counters but the metric name does not suggest that it is a counter.

![image](https://github.com/ChainSafe/lodestar/assets/38436224/abc359cc-3041-4722-9fcd-2684b14188e3)

We have plenty of metrics like this, e.g. attestation summary on validator monitor dashboard

https://github.com/ChainSafe/lodestar/blob/3076b4cbe34bbe4ebadb005f78f90c256ab31aae/packages/beacon-node/src/metrics/metrics/lodestar.ts#L1009-L1010

To get rid of the warning and more strictly follow [Prometheus best practices](https://prometheus.io/docs/practices/naming/) we would have to update the metric name

```diff
-validator_monitor_prev_epoch_attestation_summary
+validator_monitor_prev_epoch_attestation_summary_total
```

I am not sure if it's worth fixing as it would break existing dashboards but the warnings might also be confusing to users and it would generally be good to follow the recommended naming convention.

**Comment by nflaig** [comment]
Those warnings seem to be gone on the latest Grafana release, I don't think it's worth to rename all of those metrics but we should make sure to follow best practices when naming new metrics.

**Comment by StremCipher** [comment]
@nflaig can you provide the version of Prometheus and Grafana in which they resolved the warnings??
because i can still see those warnings in my grafana 
for my case these were the versions.
prometheus v : 2.52.0
grafana v : 11.1.4

**Comment by nflaig** [comment]
> @nflaig can you provide the version of Prometheus and Grafana in which they resolved the warnings??

Right it seems like they show up on v11.1.x again, I honestly can't remember what version they were gone again but in any case I think it's not worth renaming the metrics as it would force users to re-import the modified dashboards.

We should definitely make sure to properly name all new metrics from now on.
