### ISSUE TITLE
Custom logger

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/lodestar#67]
**Is your feature request related to a problem? Please describe.**
Currently there is no standardized way to log anything.

**Describe the solution you'd like**
We should implement a custom logger.

**Comment by aunyks** [comment]
Something like [this](https://github.com/ethereumjs/ethereumjs-client/blob/master/lib/logging.js)?

**Comment by GregTheGreek** [comment]
Yeah! We've created our own in the past, I know @ansermino has one?

**Comment by ansermino** [comment]
I usually just reimplement based on the needs of the project. Definitely would be a good addition

**Comment by tynes** [comment]
You should check out https://github.com/bcoin-org/blgr
Minimal dependencies, nice api, works great in both node.js and the browser
