### ISSUE TITLE
Fix req/resp stream lifecycle

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#675]
According to spec, we are suppose to close(reset?!) stream after we are finished sending response.

See: https://github.com/ethereum/eth2.0-specs/blob/v0.9.4/specs/networking/p2p-interface.md#reqresp-interaction

**Comment by mpetrunic** [comment]
https://github.com/ChainSafe/lodestar/pull/671#discussion_r385248089

**Comment by twoeths** [comment]
I pulled the Snappy Compression branch, debugged and found out we're good.

If I send each request 1 by 1, I can clearly see that a new stream is created per request and old stream was closed:

```
@@@ unit test sending request 1
### Server side libp2p handle - num stream: 3 - details - [ { id: 'i0', timeline: { open: 1583124905402, close: null } },
  { id: 'r0', timeline: { open: 1583124905412, close: null } },
  { id: 'r1', timeline: { open: 1583124905418, close: null } } ]
@@@ unit test received response 1
@@@ unit test sending request 2
### Server side libp2p handle - num stream: 3 - details - [ { id: 'i0', timeline: { open: 1583124905402, close: null } },
  { id: 'r0', timeline: { open: 1583124905412, close: null } },
  { id: 'r2', timeline: { open: 1583124905434, close: null } } ]
@@@ unit test received response 2
@@@ unit test sending request 3
### Server side libp2p handle - num stream: 3 - details - [ { id: 'i0', timeline: { open: 1583124905402, close: null } },
  { id: 'r0', timeline: { open: 1583124905412, close: null } },
  { id: 'r3', timeline: { open: 1583124905440, close: null } } ]
@@@ unit test received response 3
@@@ unit test sending request 4
### Server side libp2p handle - num stream: 3 - details - [ { id: 'i0', timeline: { open: 1583124905402, close: null } },
  { id: 'r0', timeline: { open: 1583124905412, close: null } },
  { id: 'r4', timeline: { open: 1583124905447, close: null } } ]
@@@ unit test received response 4
@@@ unit test sending request 5
### Server side libp2p handle - num stream: 3 - details - [ { id: 'i0', timeline: { open: 1583124905402, close: null } },
  { id: 'r0', timeline: { open: 1583124905412, close: null } },
  { id: 'r5', timeline: { open: 1583124905453, close: null } } ]
@@@ unit test received response 5
    ✓ can handle multiple block requests from connected peers at the same time (53ms)
```

Analyse: request 1 sent => create stream r1 => request 2 sent => stream r1 was not there and stream r2 created => ...

**Comment by twoeths** [comment]
If I send 5 requests concurrently, I see that there are 7 open streams. Although I can't explain why there are 2 first streams, I think we're good enough by:
+ Opening a new stream per request
+ Closing stream after a response is sent

**Comment by mpetrunic** [comment]
I think only issue is that we arent closing streams. I would say 2 extra streams are encription and protocol negotiation

**Comment by twoeths** [comment]
From https://github.com/libp2p/js-libp2p-mplex, what we have to do is to handle `onStreamEnd`. And that's what libp2p does so we don't have to do anything as I debugged 
![image](https://user-images.githubusercontent.com/10568965/75652221-19ba3800-5c8d-11ea-9888-c65149ecad93.png)

**Comment by mpetrunic** [comment]
If you set env DEBUG=libp2p:mplex you can see stream logs. Seems like everything gets closed at the end but still:
- after we decode first request we are suppose to call break so initiator cannot send any more request using same stream
- we might need to handle errors and call stream.close/stream.abort/stream.reset (we need unit tests with invalid data to check if stream gets reseted if we throw error)

**Comment by twoeths** [comment]
> after we decode first request we are suppose to call break so initiator cannot send any more request using same stream

is this to conform to the spec `The requester MUST close the write side of the stream once it finishes writing the request message. At this point, the stream will be half-closed.`?

**Comment by mpetrunic** [comment]
yeah

**Comment by twoeths** [comment]
I believe the spec comes from libp2p spec https://github.com/libp2p/specs/tree/master/mplex .
According to the spec, in order to half close, one side should send `CloseReceiver (3) or CloseInitiator (4) flag` and that's exactly what I debugged inside libp2p-mplex:

![image](https://user-images.githubusercontent.com/10568965/75861771-6d18bb80-5e30-11ea-8dcd-c1a1b24c2750.png)

What it does is to send `CLOSE` flag to the other side after we finish sending our request.
So I think libp2p-mplex does the job for us. (because it has to follow its own spec anyway :))

**Comment by mpetrunic** [comment]
We can close this for now and reopen if we see some issues
