### ISSUE TITLE
Expose async iterable resources

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#682]
Currently, we return `Promise<XXX[]>` in network and db apis.

We should instead return an `AsyncIterable<XXX[]>` so that consumers may begin processing items immediately, rather than awaiting all items to be fetched/returned.

**Comment by twoeths** [comment]
This is great.

How about do not drop the old APIs which return Promise<Array>, just add new APIs which return AsyncIterable? Depending on different scenarios, consumers may choose which APIs to use.

**Comment by wemeetagain** [comment]
Sure, makes sense to support both. We can most likely build the non-streaming api from the streaming api (like we're currently doing in req/resp)
