### ISSUE TITLE
Consider enabling debug namespace by default

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#6822]
Vouch requires debug api to be enabled as it uses the state to determine the validators statuses. This means it is required [to pass --rest.namespace flag](https://github.com/attestantio/vouch?tab=readme-ov-file#lodestar) to work with Lodestar. All other clients have debug apis enabled by default.

**Comment by nflaig** [comment]
I've seen it several times as well that people run into issues using ethdo with Lodestar, as it also relies on state api to retrieve validator information.

Considering this, and the fact that the validators api is also enabled by default which has the same implications in terms of being a potential DoS vector, I think there is no real downside enabling debug by default. The beacon api is generally assumed to be a trusted api, protected by either not exposing it at all (only to validator client) or via proxy which adds additional access control.

For public beacon nodes, we need to consider another strategy, e.g. disabling some apis, or at least do not allow JSON responses for validators and state api.

**Comment by philknows** [comment]
We should discuss this if there’s enough people at #6809 . We were previously hesitant about having it enabled but can see the value it brings.

**Comment by nflaig** [comment]
To add to what we already discussed, our public nodes already have debug namespace enabled explicitly, so we really only negatively affect Vouch users and solo stakers using ethdo with Lodestar.

For stakers, we already make it pretty clear that the beacon api should not be exposed publicly (via warning log) and by default we bind the rest.address to localhost only. Imo there are more sensitive apis that need to be protected than the debug api, e.g. [prepareBeaconProposer](https://ethereum.github.io/beacon-APIs/#/ValidatorRequiredApi/prepareBeaconProposer) which would allow an attacker to steal execution rewards by changing the fee recipient.
