### ISSUE TITLE
v1.19.0-rc.0 high gc time

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#6826]
### Describe the bug

v1.19.0-rc.0 shows high gc time on the mainnet node

<img width="1316" alt="Screenshot 2024-05-29 at 15 00 52" src="https://github.com/ChainSafe/lodestar/assets/10568965/970790e0-4ccb-4b73-9016-7ed0eff9411c">

while it's consistently <3% on the stable mainnet node (v1.18.0)
<img width="1310" alt="Screenshot 2024-05-29 at 15 01 23" src="https://github.com/ChainSafe/lodestar/assets/10568965/433d054c-51e8-42d8-b81b-25871d7e2d6f">

this leads to high epoch transition time

<img width="1327" alt="Screenshot 2024-05-29 at 15 02 34" src="https://github.com/ChainSafe/lodestar/assets/10568965/1c9a415c-6a1e-4d60-8cdb-8dcdebefe220">

vs stable

<img width="1322" alt="Screenshot 2024-05-29 at 15 03 08" src="https://github.com/ChainSafe/lodestar/assets/10568965/c0faeb73-de9b-4516-86c9-48efae385e8f">

### Expected behavior

Metrics should be the same or better than v1.18.0

### Operating system

Linux

### Lodestar version or commit hash

v1.19.0-rc.0

**Comment by wemeetagain** [comment]
closing since we've released 1.19
