### ISSUE TITLE
Convenience script to further simplify binary installation

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#6866]
From https://github.com/ChainSafe/lodestar/issues/3633#issuecomment-2044650621, we should look into providing a convenience script to further simplify binary installation.

Similar to https://github.com/celestiaorg/docs/pull/1524

**Comment by varunguleriaCodes** [comment]
Hi @nflaig, @ensi321 I'd like to work on this! Just to confirm, task would be to create a script with functionality similar to what is defined in binary.yml under github/workflows?

**Comment by nflaig** [comment]
> Hi [@nflaig](https://github.com/nflaig), [@ensi321](https://github.com/ensi321) I'd like to work on this! Just to confirm, task would be to create a script with functionality similar to what is defined in binary.yml under github/workflows?

It should be similar to https://github.com/celestiaorg/docs/pull/1524, meaning a user just has to run a single command to install Lodestar
