### ISSUE TITLE
Remove Mention of Gitter in Issue Templates

### ISSUE THREAD

**Issue by aunyks** [ChainSafe/lodestar#688]
The issue templates (`.github/ISSUE_TEMPLATE/*`) mention consulting Gitter with questions before opening issues. They should instead direct people to our [Discord Server](https://discordapp.com/invite/aMxzVcr) (`https://discordapp.com/invite/aMxzVcr`).

**Comment by lastmjs** [comment]
Has this been completed? I just looked through the templates, and it looks like Gitter isn't mentioned anymore. People are directed to discord, but there is no link. Perhaps the link should be included?

**Comment by dapplion** [comment]
Gitter is not mentioned anywhere across the codebase as of now. This issue may be closed.
