### ISSUE TITLE
Verify gossiped block signature bug

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#692]
To reproduce:
- create following test cases:
   - received block from previous epoch
   - receive block from future epoch

We should fetch state matching block slot or advance latest state to block slot.
I guess we should not propagate very old blocks or blocks that are more than one epoch in future.

**Comment by twoeths** [comment]
There is more validation check as in spec v0.10.0 https://github.com/ChainSafe/lodestar/issues/707

**Comment by twoeths** [comment]
If the received block is too old we simply ignore it as in current check
```
// ignore if we have this block already
    if (await this.db.block.has(root)) {
      return false;
    }
```

If it's in the future we should follow the spec v.0.10.0 by implementing the above issue.

So for this issue, mainly we need to give correct state to validate block signature.

**Comment by mpetrunic** [comment]
You could still receive old block that will pass this check (we havent seen that block before) either by bug or by attacker

**Comment by twoeths** [comment]
You're right. Just found that it's part of spec 0.11 https://github.com/ethereum/eth2.0-specs/pull/1616

Do you want to implement that in this issue or wait for 0.11 spec?

**Comment by mpetrunic** [comment]
I would implement now, it should be one liner :smiley:
