### ISSUE TITLE
Unnecessary log during EL Sync

### ISSUE THREAD

**Issue by nazarhussain** [ChainSafe/lodestar#6925]
### Describe the bug

Syncing a fresh node, lodestar with nethermind, getting these logs every 2 secs or so.

```
lodestar_beacon-1  | Jun-30 15:47:01.582[eth1]             info: Eth1Provider is back online oldState=ERROR, newState=ONLINE
```

nethermind is still syncing, but this repeats every 2 sec.

### Expected behavior

Reduce the noise in logs. 

### Additional context

https://discord.com/channels/593655374469660673/593655641445367808/1256999786037645403

### Operating system

Linux

### Lodestar version or commit hash

unstable

**Comment by nflaig** [comment]
This has been a known problem for a while, see related issue
- https://github.com/ChainSafe/lodestar/issues/6469

**Comment by nazarhussain** [comment]
Closing in favor of #6469
