### ISSUE TITLE
Set proper user-agent in validator client http requests

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#6959]
This is not that important but we could consider setting proper user-agent header as this might help debug issues (or adding workarounds).

Right now, we just set (fetch default)
```
User-Agent: node
```

We already set the Lodestar version in http requests to builder

**Comment by KaloyanTanev** [comment]
Thanks for that one, it was really helpful for running distributed validators.

**Comment by nflaig** [comment]
> Thanks for that one, it was really helpful for running distributed validators.

I wasn't sure if anyone even cares about the user-agent header but that's great to hear, thanks for the feedback
