### ISSUE TITLE
bug in `aggregateVote.numAggregateSig`

### ISSUE THREAD

**Issue by djrtwo** [ChainSafe/lodestar#7]
# Issue
`aggregateVote.numAggregateSig` currently incorrectly uses the length of `aggregate_sig` to get the number of aggregate signatures. 
https://github.com/ChainSafeSystems/lodestar_chain/blob/a270c7a577a3deda88f96cebb41bc3f173e26b1d/lodestar_chain/state/aggregateVote.js#L36-L38

`aggregate_sig` is in fact always just the length of 2 so this fails.

# Proposed Implementation
You can use the number of `1`s in the bitfield to get the length. If you need the length often, you might consider some sort of helper attribute that caches this results.

**Comment by djrtwo** [comment]
I'm not 100% sure what `aggregateVote` is being used for. Maybe it is just a relic of a previous version of the spec.

That said, this logic around BLS aggregate signatures still holds when used in other data structures.

**Comment by Mikerah** [comment]
Hi Danny,

Thank you so much for submitting an issue. We do indeed have relics of the previous spec in this repo. We are going to be going over the repo, and creating issues to make sure I follow your advice on making it easier for others to contribute.

**Comment by GregTheGreek** [comment]
I think this can be closed due to #39
