### ISSUE TITLE
Consider relicensing project to a more permissive license

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#70]
Consider using the LGPL.

This would protect derivative versions of the beacon chain under LGPL, but allow it to be imported/used as a library without forcing the linking project to be GPL.

**Comment by ansermino** [comment]
@wemeetagain Thanks for the suggestion, @ChainSafe is looking into this. How familiar are you with the finer details of LGPL?

**Comment by wemeetagain** [comment]
hey @ansermino .

I'm not a license expert or lawyer or anything.

Really, I just noticed etherem/web3 uses LGPL and got curious and did a bit of googling on the subject and thought I'd spur discussion. :)

My lay interpretation is that it may be overkill to use GPL for web-based libraries in many cases, because it would mean that any website incorporating this codebase would need to GPL their entire frontend (or at least the js bits).

The LGPL seems to be like the GPL for any derivative versions of the codebase (eg: if a company wants to fork lodestar to add new features that fork must be LGPL), but stops short of software that "uses" the codebase (eg: a website that includes lodestar as part of a larger webapp does not need to be LGPL).

Not super familiar with the finer details or any gotchas, though, so I'm sure this would have to get cleared with "the legal dept".

**Comment by ansermino** [comment]
@wemeetagain thank you for spurring discussion! always welcome here :D 

Yes it does seem to have some advantages for a project such as this. To stay on the safe side I believe @ChainSafe is reaching out to some pros to get the full picture. Will update here on any headway.
