### ISSUE TITLE
 Add eager attestation broadcasting to optimize attestation propagation in the normal case

### ISSUE THREAD

**Issue by ColinSchwarz** [ChainSafe/lodestar#705]
https://github.com/ethereum/eth2.0-specs/pull/1555

**Comment by twoeths** [comment]
Need to implement a way for Beacon Node to inform Validators on new blocks. See details in #764

**Comment by twoeths** [comment]
SSE event is implemented in https://github.com/ChainSafe/lodestar/pull/777, ready to implement EventSource in validator.
