### ISSUE TITLE
Implement engine_getBlobsV1

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#7114]
### Problem description

Reference: https://github.com/ethereum/execution-apis/pull/559

Recently there have been calls to raise the blob target/max parameters for scaling DA. However, taking into consideration that some bandwidth/resource constrained validators are reportedly at their limits, we need to find ways to help alleviate this constraint before adding more demands for the most honest type of validator: home stakers building local blocks with 6 blobs and limited upload bandwidth.

### Solution description

It's likely alongside Gossipsub 1.2 features such as `IDONTWANT` and APIs like [`engine_getBlobsV1`](https://github.com/ethereum/execution-apis/pull/559) could help [alleviate some bandwidth concerns](https://x.com/terencechain/status/1839661686472716340) so we can get better information about where blob limitations currently stand. 

With #7077 already testing Gossipsub, we should prioritize supporting this as some execution clients have already implemented this feature for use. 

### Additional context

Teku analysis: https://hackmd.io/@dsjdqQDBRp66btjRzfxjbw/r1OuFG7AA
Lighthouse blog describing this optimization: https://blog.sigmaprime.io/peerdas-distributed-blob-building.html

**Comment by philknows** [comment]
Spec merged!

**Comment by philknows** [comment]
Will we be able to include metrics here @g11tech that capture how many blobs were retrieved from the mempool out of the ones you actually tried to retrieve over the wire? I think this might be useful to data collection, especially since we also produce a lot of local blocks due to our min-bid.

**Comment by nflaig** [comment]
> hat capture how many blobs were retrieved from the mempool out of the ones you actually tried to retrieve over the wire?

I would expect this to have a higher impact on low bandwidth nodes and improve block import times there, potentially improving head vote accuracy / timeliness.
