### ISSUE TITLE
Implement beacon API `/eth/v1/debug/fork_choice` endpoint

### ISSUE THREAD

**Issue by Savid** [ChainSafe/lodestar#7124]
### Problem description

Looks like [`/eth/v1/debug/fork_choice`](https://ethereum.github.io/beacon-APIs/#/Debug/getDebugForkChoice) from the beacon API spec is not [fully implemented](https://github.com/ChainSafe/lodestar/blob/unstable/packages/api/src/beacon/routes/debug.ts#L119).

### Solution description

Implement [`/eth/v1/debug/fork_choice`](https://ethereum.github.io/beacon-APIs/#/Debug/getDebugForkChoice)

**Comment by nflaig** [comment]
Duplicate https://github.com/ChainSafe/lodestar/issues/5700

**Comment by nflaig** [comment]
I've put a PR to add the endpoint to Lodestar https://github.com/ChainSafe/lodestar/pull/7127, we really just haven't added it because it was a nice "good first issue" but it has been sitting around for a while.. should be part of our next release.

Curious what are you using it for?

**Comment by Savid** [comment]
Awesome! thanks for that.

> Curious what are you using it for?

For our [forky](https://github.com/ethpandaops/forky) tool
