### ISSUE TITLE
Allow filtering of validators by top-level validator status

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#7141]
Right now, Lodestar does not support filtering response of [getStateValidators](https://ethereum.github.io/beacon-APIs/#/Beacon/getStateValidators) by top-level validator statuses such as `active` as we only consider the more accurate sub statuses like `active_ongoing`, `active_exiting` and `active_slashed`.

As per beacon-api spec we should support `active`, `pending`, `exited`, and `withdrawal` ([validators.yaml#L38](https://github.com/ethereum/beacon-APIs/blob/e7f7d70423b0abfe9d9f33b701be2ec03e44eb02/apis/beacon/states/validators.yaml#L38)).

Related code
https://github.com/ChainSafe/lodestar/blob/955f4569289d66e0a2ee171dfa7bd9984ce57ba7/packages/beacon-node/src/api/impl/beacon/state/utils.ts#L132

**Comment by vladmarusyk** [comment]
Hello!

I would like to contribute to this issue as part of Hacktoberfest. Could you please add the `hacktoberfest` label to the issue so my contribution can count toward Hacktoberfest?

Thank you!
