### ISSUE TITLE
Fork streaming API

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#715]
Eventsource for fork updates

**Comment by wemeetagain** [comment]
unstale

**Comment by dapplion** [comment]
Could this be spec-ed first to be implemented?

**Comment by dapplion** [comment]
Related to https://github.com/ChainSafe/lodestar/issues/320

**Comment by wemeetagain** [comment]
Something like:
An EventSource that listens for chain `fork` events, emits a `Fork` object.

**Comment by wemeetagain** [comment]
closing in favor of standard eventsource api #1209
