### ISSUE TITLE
Make `MAX_REQUEST_BLOB_SIDECARS` and `MAX_BLOBS_PER_BLOCK` configurable

### ISSUE THREAD

**Issue by ensi321** [ChainSafe/lodestar#7172]
### Problem description

In ethereum/consensus-specs#3817, `MAX_BLOBS_PER_BLOCK` is moved from preset to config. 

This poses a challenge in Lodestar since [`BlobSidecarsByRootRequest`](https://github.com/ChainSafe/lodestar/blob/de0d6ab89b575ad20c593acf20d7c97d2c884ab1/packages/types/src/deneb/sszTypes.ts#L65) - a fixed length ssz container depends on it but `types` package has no access to `chain.config`.
### 

### Solution description

I believe this is the only place in the spec has a ssz container for which its definition relies on a variable from config.

We can either make a one time exception and define `BlobSidecarsByRootRequest` ssz in `beacon-node` or further refactor to be more future proof if such scenario happens again.

cc. @g11tech

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
