### ISSUE TITLE
Lodestar sends `engine_getClientVersionV1` request with invalid 4-byte `DATA` encoding

### ISSUE THREAD

**Issue by tersec** [ChainSafe/lodestar#7217]
### Describe the bug

```
Nov  5 16:00:12.488 2024 REQUEST 
{
  "jsonrpc": "2.0",
  "id": 2,
  "method": "engine_getClientVersionV1",
  "params": [
    {
      "code": "LS",
      "name": "Lodestar",
      "version": "v1.22.0/1531b19",
      "commit": "1531b19"
    }
  ]
}
```

From `snooper-engine` on `devops@lodestar-nimbusel-1.mekong-devnet-0.ethpandaops.io`

https://github.com/ethereum/execution-apis/blob/v1.0.0-beta.4/src/engine/identification.md#clientversionv1 documents that this `commit` is a
> `DATA`, 4 bytes - first four bytes of the latest commit hash of this build e.g. `fa4ff922`

And https://github.com/ethereum/execution-apis/blob/v1.0.0-beta.4/src/engine/common.md#encoding specifies that:
> Values of a field of `DATA` type **MUST** be encoded as a hexadecimal string with a `0x` prefix matching the regular expression `^0x(?:[a-fA-F0-9]{2})*$`.

Which `1531b19` does not match.

### Expected behavior

Use correct `DATA` encoding

### Operating system

Linux

### Lodestar version or commit hash

Lodestar network=testnet, version=v1.22.0/1531b19, commit=1531b19

**Comment by nflaig** [comment]
@tersec I also noticed when images are build via ethpandaops builder, the commit is only 7 characters. Does this also cause issues for you or was the main problem that we didn't add the 0x-prefix?

I've put up an issue for that as well https://github.com/ethpandaops/eth-client-docker-image-builder/issues/212 but if it causes trouble with nimbusel we might need to look into a workaround in Lodestar for this as well.
