### ISSUE TITLE
Expose headStateRoot in fork choice

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#723]
Currently, we only expose the head block root in our fork choice module.
It would be more convenient and efficient to also expose the state root.
(we have a pattern many places in the code where we operate on the head state)

**Comment by twoeths** [comment]
So I suppose when we add block to our forkchoice, we need to give `stateRoot` along with `blockRoot` and each node should track `stateRoot` as well?

**Comment by wemeetagain** [comment]
Yeah, I had thought we were already doing this, and it was just a matter of exposing it, guess not.
We would need to do as you say, add it to the fork choice "node" and add it to `addBlock`
