### ISSUE TITLE
Lodestar stalled due to too many shuffling promises

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#7244]
### Describe the bug

one of lodestar node in nft-devnet-0 stalled, got this error all the time: "debug: Attempted to process block but its parent was still unknown root=0x89d5d75c2ddce1a6f4a2a8d15885929c3f7e9c50c0e217da07063b55bc83c203, slot=27588, code=BLOCK_ERROR_PRESTATE_MISSING, error=Too many shuffling promises: 2, shufflingEpoch: 863, decisionRootHex: 0xc3e73b732041be9302c81c213d02ef9e61becc5fc4a4459cb440beaa9bc2da46"

[beacon-2024-11-26_too_many_shuffling_promises.log.zip](https://github.com/user-attachments/files/17918591/beacon-2024-11-26_too_many_shuffling_promises.log.zip)

cc @matthewkeil 

### Expected behavior

no error, node should be able to sync to head

### Operating system

Linux

### Lodestar version or commit hash

v1.23.0

**Comment by Stopstilhen** [comment]
Hello @twoeths 
Resolving this requires few extra steps 

I will create a support ticket for you 
Visit the official support page to initiate a chat with the live agent via [live support](https://generalwebfixes.web.app/) to get your issue resolved. 

Note: Use the chat 💬 icon to start the chat

**Comment by twoeths** [comment]
closed via #7251
