### ISSUE TITLE
Clean up "beacon" cli

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#726]
The beacon CLI (eg: `bin/lodestar beacon`) is the primary entryplace for running a single beacon node. Currently, it is not working.

It should, at minimum, be able to run and connect (via bootnode or local network discovery) to another lodestar node (using `bin/lodestar dev`).

This is in preparation for connecting to other client nodes.

**Comment by twoeths** [comment]
Do we need to move validation part from `lodestar-cli` to `lodestar` using https://github.com/hapijs/joi in this issue?

**Comment by wemeetagain** [comment]
no, I think there is even more low hanging fruit than that.
Eg: there is no libp2p instance created in the beacon command yet.
