### ISSUE TITLE
Create run-time type definitions of our interfaces

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#74]
Unfortunately, typescript interfaces do not appear to be available/exist at run time.
This means that we don't have access to the type information necessary to properly serialize the data.

There is a dependency here, between our "types" and our ssz library that we should be aware of.
Our ssz library assumes a type object with a `fields` key, which it uses to serialize each field. (See [here](https://github.com/ChainSafeSystems/ssz-js/blob/master/src/index.js#L90))

Here is an example that can show the issue:
```javascript
interface ProposalSignedData {
  // Slot number
  slot: uint64;
  // Shard number (`BEACON_CHAIN_SHARD_NUMBER` for beacon chain)
  shard: uint64;
  // Block hash
  blockHash: hash32;
}

const data: ProposalSignedData = {
  slot: 0,
  shard: 0,
  blockHash: 0,
};

const serializedData: Uint8Array = ssz.serialize(data, ???); // <--- problem here
```

Perhaps a way forward would be to create a "type" object for each interface.
Something that would play nicely with ssz-js:
```javascript
const ProposalSignedData = {
  fields: [
    ['slot', 'uint64'],
    ['shard', 'uint64'],
    ['blockHash', 'hash32'],
  ],
};

// from above, problem fixed
const serializedData: Uint8Array = ssz.serialize(data, ProposalSignedData);
```

See also how the python implementation deals with this, eg: [here](https://github.com/ethereum/beacon_chain/blob/master/beacon_chain/state/block.py#L19)

**Comment by JonathanLorimer** [comment]
@wemeetagain The most straightforward solution I can see is to create a Class that directly mimics the interface and include that on the data object. for example:

```javascript

const proposalSignedDataClass = Class {
  constructor(){
    this.slot: 'uint64'
    this.shard: 'uint64'
    this.blockHash: 'hash32'
  }
}

interface ProposalSignedData {
  // Slot number
  slot: uint64;
  // Shard number (`BEACON_CHAIN_SHARD_NUMBER` for beacon chain)
  shard: uint64;
  // Block hash
  blockHash: hash32;
  // runtime interface
  proposalSignedDataClass: object
}

const data: ProposalSignedData = {
  slot: 0,
  shard: 0,
  blockHash: 0,
  new proposalSignedDataClass()
};

const serializedData: Uint8Array = ssz.serialize(data, ???);
```

Looks like we had similar ideas here

**Comment by wemeetagain** [comment]
@JonathanLorimer 
Agree, this looks like a good solution. Would just modify your proposal to include the ordering of the fields, since object fields are unordered.

something like:
```javascript
const proposalSignedDataClass = Class {
  constructor(){
    this.slot = 'uint64'
    this.shard = 'uint64'
    this.blockHash = 'hash32'
    this.fields = ['slot', 'shard', 'blockHash']
  }
}
```

**Comment by JonathanLorimer** [comment]
Yeah, that looks great. The fields array is a really nice touch. I would suggest using a factory function because I think its more terse, but that is really just an implementation detail.
```javascript
const proposalSignedDataClass = () =>({
    slot = 'uint64'
    shard = 'uint64'
    blockHash = 'hash32'
    fields = ['slot', 'shard', 'blockHash']
  })
}
```

**Comment by GregTheGreek** [comment]
Also looking into using classes to manage the state of the beacon chain. Mutating state functions will probably need to be re written a bit but it will help.
