### ISSUE TITLE
Add DB

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/lodestar#78]
**Is your feature request related to a problem? Please describe.**
In order to keep track of the state we should add support for a DB.

**Describe the solution you'd like**
One option would be to implement [level-js](https://github.com/Level/level-js) which is a key-value pairing that is an implementation of the google leveldb.

EDIT: Clarified this is a discussion.

**Comment by Mikerah** [comment]
Shouldn't we decide which DB to go with first? I understand that the main one that other implementers are going with is LevelDB but is that enough of a reason to also go with LevelDB?

**Comment by GregTheGreek** [comment]
@Mikerah This is a discussion on what to use. I have suggested leveldb.

**Comment by wemeetagain** [comment]
Closing from #126 

If we want to support another database, we can create a new class that implements the methods in `src/db/index.ts`.
