### ISSUE TITLE
[0.11]: Handle new spec test format

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#782]
I notice spec tests are failing in spec 0.11.1 tests because the test format is changed.

Refer to https://github.com/ethereum/eth2.0-specs/releases

**Comment by wemeetagain** [comment]
I think our npm-published tests didn't get git lfs initialized before being published. @mpetrunic 
```bash
# from project root
$ cat node_modules/@chainsafe/eth2-spec-tests/tests/minimal/phase0/genesis/initialization/pyspec_tests/initialize_beacon_state_from_eth1/meta.yaml
version https://git-lfs.github.com/spec/v1
oid sha256:3b584c7a0ae9db0bb9c323211b92179df5ed7e6bfbcd9f48a5db2854e05b71b5
size 21

```

**Comment by mpetrunic** [comment]
oh god, Ill update spec tests

**Comment by wemeetagain** [comment]
updated, `0.11.1-fixed`
