### ISSUE TITLE
empty bitfield init error

### ISSUE THREAD

**Issue by djrtwo** [ChainSafe/lodestar#8]
# Issue
`getEmptyBitfield` in bitfield.js is return an incorrect value. The following code returns strings like `"x00x00x00x00x00"`.
https://github.com/ChainSafeSystems/lodestar_chain/blob/a270c7a577a3deda88f96cebb41bc3f173e26b1d/lodestar_chain/utils/bitfield.js#L19
The intention here is to initialize a byte array or some sort of bytes representation with the correct number of 0 bytes.

# Proposed Implementation
Not sure the best way to represent bytes in javascript. Will need to dig around for best practices on this.

**Comment by darrenlangley** [comment]
From what I have found - using ArrayBuffer as the underlying object is the most consistent way to use bytes in Javascript. You then use either DataView or the TypedArrays to create and manipulate the ArrayBuffer.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray

For example, this would give you 1 byte with all zeros in the buffer:
```
let view = new DataView(new ArrayBuffer(1))
view.setUint8(0, 0)

```

**Comment by Mikerah** [comment]
I agree with @darrenlangley. Using TypedArrays is how I have been doing it in ssz.
