### ISSUE TITLE
Add test to validate runtime/compiletime interfaces

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/lodestar#83]
A simple test to validate that the runtime variables actually match up with the compile time interfaces.

**Comment by GregTheGreek** [comment]
I've been playing around with this idea... and i think it might make more sense to seperate the interfaces from the run-time variables, or rename the vars accordingly. Reason being we can't import both, and to make tests for them makes it quite difficult..

**Comment by ansermino** [comment]
why are there 3 of us assigned to this?

**Comment by wemeetagain** [comment]
I can take this if yall want.

Typescript doesn't exist at runtime, so unless we want to separately write a test for each type by hand (we don't), you can't just do something like:
```typescript
// file 1
export interface a {}
export interface b {}
export interface c {}

// file 2
import interfaces from "./file1"

for (let i in interfaces) { // error here, interfaces don't actually exist!
  ...
}
```

Unfortunately, a real solution is a little hairy (we need to manually parse our types files to suss out the interface definitions) but I'm prototyping something now.

**Comment by GregTheGreek** [comment]
@ansermino No idea how/why i did that.

**Comment by GregTheGreek** [comment]
I was playing around with this @wemeetagain https://stackoverflow.com/questions/14425568/interface-type-check-with-typescript
