### ISSUE TITLE
Import / Export constants

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/lodestar#84]
Per @wemeetagain:
> This may be a good opportunity to remove the uint/bytes duplicate types/vars from types/block.ts and types/state.ts and import/export these instead.
> [...] it would be nice to import/export constants and enums from constants/index.ts like we're now doing with types/index.ts.

TODO:
- [x] Consolidate and Remove duplicate alias types (probably move into constants) (PR: #91 )
- [x] Import / Export constants/enums

@wemeetagain Assigned, you because im not sure if you already started or not, otherwise happy to take it on myself.

**Comment by wemeetagain** [comment]
Haven't started working on this, I'm looking at #83 right now, feel free to do this one.

**Comment by wemeetagain** [comment]
I'm working on the first bullet point here
