### ISSUE TITLE
Remove redundant check in is_valid_indexed_attestation [non-substantive] 

### ISSUE THREAD

**Issue by ColinSchwarz** [ChainSafe/lodestar#846]
https://github.com/ethereum/eth2.0-specs/pull/1738

**Comment by twoeths** [comment]
We don't have the removed check in the spec
```
if not len(indices) <= MAX_VALIDATORS_PER_COMMITTEE:
        return False
```
in `isValidIndexedAttestation` so we're fine, nothing to do for this.
