### ISSUE TITLE
Complete helper functions

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/lodestar#86]
I browsed through the spec/our code, and found a few helper functions that are not yet implemented. I won't get to these for a bit as I'm currently working on writing further tests.

If you plan to work on one of the following please comment.

(Does not include validator helpers)

- [x] hash
- [x] hashTreeRoot
- [x] slotToEpoch
- [ ] getPreviousEpoch
- [x] getCurrentEpoch
- [x] getEpochStartSlot
- [x] isActiveValidator
- [x] getActiveValidatorIndices
- [x] getPermutedIndex
- [x] split
- [x] getEpochCommitteeCount
- [x] getShuffling
- [x] getPreviousEpochCommitteeCount
- [x] getCurrentEpochCommitteeCount
- [x] getNextEpochCommitteeCount
- [x] getCrosslinkCommittessAtSlot
- [x] getBlockRoot
- [x] getRandaoMix
- [x] getActiveIndexRoot
- [ ] generateRoot
- [x] getBeaconProposerIndex
- [x] merkleRoot
- [x] getAttestationParticipants
- [x] isPowerOfTwo
- [x] intToBytes1, intToBytes2... (to be handled by Buffer)
- [ ] bytesToInt (to be handled by Buffer)
- [x] getEffectiveBalance
- [x] getTotalBalance
- [x] getForkVersion
- [x] getDomain
- [x] getBitfieldBit
- [ ] verifyBitfield
- [ ] verifySlashableAttestation
- [x] isDoubleVote
- [x] isSurroundVote
- [x] integerSquareRoot (intSqrt)
- [x] getEntryExitEffectEpoch
- [ ] blsVerify
- [ ] blsVerifyMultiple
- [ ] blsAggregatePubkeys
- [x] validateProofOfPossession
- [x] processDeposit

**Comment by ansermino** [comment]
Working on `getBitfieldBit` & `getAttestationParticipants`

**Comment by GregTheGreek** [comment]
Closing since this is very out-of-date and roughly speaking already complete
