### ISSUE TITLE
peer:connect event

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#864]
This is what happened when I tried to connect to dev node in CI:
```
@chainsafe/lodestar-cli: 2020-05-03 08:26:26  [NETWORK]       verbose: peer connected 16Uiu2HAmCojveBaNkVRngrB5E9ZGFC1q2RbnC8nBg4u8iTacce8U inbound
@chainsafe/lodestar-cli: 2020-05-03 08:26:26  [NETWORK]       verbose: peer connected 16Uiu2HAm6JNp5Zqo6izsZzZMUCSiStumVQMuLUEAiqw3UBXExecd inbound
@chainsafe/lodestar-cli: 2020-05-03 08:26:26  [NETWORK]       verbose: peer connected 16Uiu2HAm6JNp5Zqo6izsZzZMUCSiStumVQMuLUEAiqw3UBXExecd inbound
@chainsafe/lodestar-cli: 2020-05-03 08:26:26  [NETWORK]       verbose: peer connected 16Uiu2HAmCojveBaNkVRngrB5E9ZGFC1q2RbnC8nBg4u8iTacce8U inbound
```
There are 2 issues:
1. Events are duplicate
2. The middle events should have `outbound` directions instead of `inbound`
The 2nd issue does not happen in my local environment, the log is like
```
verbose: peer connected 16Uiu2HAmVBR4Hr3cNAY5hMnGM5HGWnDY6UwwJCqZ9V8wLd4R82EY inbound
2020-05-03 17:02:39  [NETWORK]       verbose: peer connected 16Uiu2HAmBGTT19Hba2owRjFu2bZFAm6f3NTTy46rdHYxAUNz3K5S outbound
2020-05-03 17:02:39  [NETWORK]       verbose: peer connected 16Uiu2HAmBGTT19Hba2owRjFu2bZFAm6f3NTTy46rdHYxAUNz3K5S outbound
2020-05-03 17:02:39  [NETWORK]       verbose: peer connected 16Uiu2HAmVBR4Hr3cNAY5hMnGM5HGWnDY6UwwJCqZ9V8wLd4R82EY inbound
```

**Comment by mpetrunic** [comment]
is autoDial true?

**Comment by twoeths** [comment]
It's true as in `createNodeJsLibp2p`. The issue is mainly direction is not correct (always `inbound`), and it happens in CI only, not in my local env.

**Comment by mpetrunic** [comment]
If autodial is true, that connection is probably correct as multiple peer discovery contacts node on it's own. I suggest turning it off in ci and connecting them mannually

**Comment by twoeths** [comment]
It works if I connect 2 dev nodes manually. And the duplication seems to come from 2 different discovery methods: Bootstrap and MDNS.
