### ISSUE TITLE
GraphQL API

### ISSUE THREAD

**Issue by lastmjs** [ChainSafe/lodestar#882]
**Is your feature request related to a problem? Please describe.**

Traditionally Ethereum clients have exposed their APIs through JSON RPC, or perhaps REST. Though functional, there are some drawbacks to this approach. One of the main drawbacks IMO is requiring developers to learn yet another protocol for requests. Each application that exposes an API over http has different rules and syntax. GraphQL provides a solution to some of these drawbacks, mostly through its standard and flexible query language.

**Describe the solution you'd like**

Like Geth has done with their Ethereum client, I would love to see a GraphQL API exposed, along with the current REST API. I would be happy to consider doing this work myself.

**Comment by wemeetagain** [comment]
Hi @lastmjs , love the idea.
Eth2 as a whole is trying to standardize the APIs across clients here: https://github.com/ethereum/eth2.0-APIs/
I believe what we have so far matches that spec.
It's still a work in progress, here's the agenda from the last API call: https://github.com/ethereum/eth2.0-pm/issues/143
here's our API related code: https://github.com/ChainSafe/lodestar/tree/master/packages/lodestar/src/api

**Comment by lastmjs** [comment]
Awesome, so is it best to try to get a GraphQL API standardized through that channel then before any implementation here? Should this issue remain open?

**Comment by mpetrunic** [comment]
GraphQL won't be standardized across clients, you can read about reasoning here: https://github.com/ethereum/eth2.0-specs/issues/1012

It will be additional feature that some clients expose.

**Comment by mpetrunic** [comment]
Oh, I think arguments against GraphQL wasn't int that issue(there is only why REST api was decided), I think arguments against starting with standardized graphql was in api call somewhere

**Comment by wemeetagain** [comment]
Yeah, I think we can implement this in parallel to standardization. It seems from the call notes that there was some interest in GraphQL, but maybe not as an officially standardized API. (You might ask about interest in the eth2 discord)
In any case, I'm sure working through what the schema should be would be a helpful exercise for everyone.

**Comment by mpetrunic** [comment]
It would be cool to use https://github.com/IBM/openapi-to-graphql to generate graphql schema from rest openapi definition in api spec repo
