### ISSUE TITLE
Enable strict null checking

### ISSUE THREAD

**Issue by lastmjs** [ChainSafe/lodestar#885]
As I was fixing this issue: https://github.com/ChainSafe/lodestar/issues/880, I realized that the main `tsconfig.json` has `strictNullChecks` set to false. I believe that if this had been set to true, then the issue from https://github.com/ChainSafe/lodestar/issues/880 would already have been apparent. There are probably many more hidden problems of a similar nature lurking in the codebase.

We need to remove `strictNullCheck`: false from `tsconfig.json`. This will probably cause a massive amount of TypeScripte errors throughout the entire codebase. The longer we wait, the harder it will be to make the switch.

Also it might be good to have a null/undefined strategy if there isn't one already. Such as always using undefined, always using null, or deciding when to use each. There's also the option of never using undefined or null if possible, such as creating types that are more descriptive, i.e. `NOT_SET`.

Example:

```typescript
  public clock: IBeaconClock | "NOT_SET";
```
You could also say "NOT_INITIALIZED", "NOT_STARTED", or something. I have found this to be a pretty nice way to do things, not without its own problems of course. `null` and `undefined` are just such problematic and broad types.

**Comment by wemeetagain** [comment]
unstale

**Comment by dapplion** [comment]
I will start to tackle this issue progressively up to the bigger packages to prevent creating too many conflicts at once. I'll follow the topological order of this repo's packages

```
lion@lion-gram:~/Code/eth2.0/lodestar$ ./node_modules/.bin/lerna list --toposort
lerna notice cli v3.20.2
@chainsafe/lodestar-params
@chainsafe/lodestar-utils
@chainsafe/lodestar-spec-test-util
@chainsafe/lodestar-types
@chainsafe/lodestar-config
@chainsafe/lodestar-beacon-state-transition
@chainsafe/lodestar-validator
@chainsafe/lodestar
@chainsafe/lodestar-cli
```
