### ISSUE TITLE
Process eth1 deposit logs in bulk

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#889]
**Is your feature request related to a problem? Please describe.**

We are currently fetching every eth1 block and deposit to check if it forms genesis.

**Describe the solution you'd like**

Fetch deposit event logs in bulk (from deployedAt block till currentBlock-ETH1_FOLLOW_DISTANCE), while processing logs if we reach MIN_GENESIS_ACTIVE_VALIDATOR_COUNT deposits, start fetching eth1 blocks belonging to deposit and emit then to test if it forms valid genesis state.

**Describe alternatives you've considered**

We could also estimate which block number is most close to minimal eth1_timestamp to satisfy condition MIN_GENESIS_TIME condition and start processing eth1 blocks if there is enough deposits and block timestamp satisfies MIN_GENESIS_TIME

**Additional context**

**Comment by twoeths** [comment]
I prefer the alternative as it'll help detect genesis state quickly well even years after genesis time when we want to setup a new node.

**Comment by mpetrunic** [comment]
Oh it's not really alternative, deposit processing is more urgent, second thing could just help a bit reducing number of nodes we are processing

**Comment by wemeetagain** [comment]
@tuyennhv take a look at #883. Our bottleneck is actually here right now.
The eth1 processing side can also be much faster (but its currently at ~1sec per block), but its not actually whats practically stopping us from genesis via eth1. Because we recreate a beacon state every block, with more and more deposits, it ends up quickly outpacing the eth1 block-processing overhead.

**Comment by mpetrunic** [comment]
I was thinking a bit, I don't think we are covering all required scenarios, so I'll summarize here. Correct me if I'm wrong somewhere:

### **We aren't block producer**

1.1. **Starting from genesis file**
- We should disable deposit and eth1 block processing and deposit tree building (we don't have genesis deposits in tree anyways).

1.2. **Manually creating genesis**
- Process bulk deposit events from deployedAt block until first block that satisfies min genesis time constraint
- start processing eth1 blocks until genesis
- stop listening on eth1 blocks (we could continue building deposit tree from eth2 block deposits)

### **We are block producers**

2.1 **Starting from genesis file**
- We should bulk process deposit events from deployedAt until genesisState.eth1Data.blockHash so we have deposit tree till genesis
- sync eth2 (this will build deposit tree from eth2 block deposits indirectly)
- after we sync start processing eth1 blocks for eth1 data votes

2.2 **Manually creating genesis**
-  Process bulk deposit events from deployedAt block until first block that satisfies min genesis time constraint
- start processing eth1 blocks until genesis
- sync (which will build deposit tree)
- start listening eth1 blocks again

**Comment by twoeths** [comment]
How do we distinguish a node being a block producer or not? I thought we always assume we are block producers because a validator may connect to our node and become proposer later.

**Comment by mpetrunic** [comment]
> How do we distinguish a node being a block producer or not? I thought we always assume we are block producers because a validator may connect to our node and become proposer later.

I think cayman already added eth1 flag, if not, should be easy to add

**Comment by twoeths** [comment]
> sync eth2 (this will build deposit tree from eth2 block deposits indirectly)

I can't find the place doing that, can show help show it?

**Comment by twoeths** [comment]
> sync eth2 (this will build deposit tree from eth2 block deposits indirectly)

I don't think we can build deposit root tree from eth2 blocks as we need all deposit roots of all deposit events, deposit data inside eth2 blocks may not be all deposit data roots in eth1. So we have to always scan eth1 to store all deposit roots.

**Comment by mpetrunic** [comment]
> > sync eth2 (this will build deposit tree from eth2 block deposits indirectly)
> 
> I don't think we can build deposit root tree from eth2 blocks as we need all deposit roots of all deposit events, deposit data inside eth2 blocks may not be all deposit data roots in eth1. So we have to always scan eth1 to store all deposit roots.

In what case deposit event won't be in block? Even with invalid signature it can be included

**Comment by twoeths** [comment]
It's hard to prove all deposit data will be included in eth2 blocks or not, at least what I see is we have `await db.processBlockOperations(block);` in post block processor, if next time our node becomes block proposer we may miss some deposit data (due to forkchoice switches the head and we did not recover the deleted deposit data for example).

Anyway, we only have DepostData in our Block, what we need is the index of DepositData as well (which is only available in IDepositEvent) so that we can store in deposit root tree. So I think we still need to get all deposit events from eth1 ourself anyway.
