### ISSUE TITLE
Backup/restore memory data when shutdown/startup

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#911]
This is a continuation of #910  and #898 
+ On shutdown, persist state cache and forkchoice
+ On startup, restore state cache and forkchoice

Need to also handle the case where node is not shutdown properly (by a crash for example): start from all unfinalzied blocks and process block by block to generate state cache and forkchoice again.

**Comment by wemeetagain** [comment]
We shouldn't persist the state cache but just rebuild the state cache from latest finalized state (in archive). We can recreate all states since we persist all blocks.
