### ISSUE TITLE
Bump gossipsub to v1.1 and note extended validator enums for gossip conditions 

### ISSUE THREAD

**Issue by ColinSchwarz** [ChainSafe/lodestar#961]
https://github.com/ethereum/eth2.0-specs/pull/1796

https://github.com/ethereum/eth2.0-specs/pull/1828

**Comment by dapplion** [comment]
@wemeetagain Is this resolved?

**Comment by twoeths** [comment]
@dapplion we mostly implement the logic in the spec but for old gossip version.
Once we release gossip 1.1 and decide to use it in lodestar, there is a small modification in lodestar to make it work so let's keep this issue open.

**Comment by twoeths** [comment]
should be done in #1206
