### ISSUE TITLE
Investigate using bigints for all uint64 types

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#970]
Currently, we represent `Slot` and `Epoch` as a `number`, even though it is defined as a `Uint64`. In practice this has been ok,because we start from 0 and increment these values slowly.

One wrinkle to that assumption, `FAR_FUTURE_EPOCH`.We get around that by representing it as `infinity`.

We've also had pain running ssz spec tests and fuzz tests that exercise the higher bits of epoch and slot.

We'd like to explore changing these types from `number` to `bigint`.

**Comment by dapplion** [comment]
@wemeetagain Should internal types in the beacon-state-transition function that represent Unix timestamps be also converted to BigInt? For example in this function when should the BigInt -> Number casting happen if any?
```js
export function computeTimeAtSlot(config: IBeaconConfig, slot: Slot, genesisTime: Number64): Number64 {
  return genesisTime + Number(slot) * config.params.SECONDS_PER_SLOT;
}
```

**Comment by wemeetagain** [comment]
I think any internal types that don't touch ssz-defined datastructures can remain numbers, if they are naturally so.

I think the spirit of this issue is to have a more literal conformance to https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#custom-types which defines all numbers in eth2 datastructures as uint64.

**Comment by dapplion** [comment]
Last attempt on https://github.com/ChainSafe/lodestar/pull/1011 required massive changes everywhere on the code, so it was discarded. Maybe it would be best to discuss the strategy on how to deal with key issues such as how to use bigint for array indexing beforehand
