### ISSUE TITLE
Syncing Witti: Failed to send status

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#972]
Seeing lots of this error:
```
2020-05-28 09:48:00  [NETWORK]         error: failed to send status(ssz_snappy) to peer 16Uiu2HAm3xiixF2zKFNB9a5ZHHD8uoLhCZw4fzz6gdSw9b7s8t58. Error: stream ended before 1 bytes became available
    at /home/cayman/Code/lodestar/node_modules/it-reader/index.js:37:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/cayman/Code/lodestar/node_modules/it-length-prefixed/src/decode.js:80:20
    at async oneChunk (/home/cayman/Code/lodestar/node_modules/multistream-select/src/multistream.js:12:20)
    at async Object.exports.read (/home/cayman/Code/lodestar/node_modules/multistream-select/src/multistream.js:34:15)
    at async module.exports (/home/cayman/Code/lodestar/node_modules/multistream-select/src/select.js:21:19)
    at async ClassIsWrapper.newStream [as _newStream] (/home/cayman/Code/lodestar/node_modules/libp2p/src/upgrader.js:251:40)
    at async ClassIsWrapper.newStream (/home/cayman/Code/lodestar/node_modules/libp2p-interfaces/src/connection/connection.js:172:34)
```

**Comment by twoeths** [comment]
I don't see the above error if I detect witti genesis state myself and use witty config instead of mainnet.yaml

**Comment by twoeths** [comment]
ah if I restart again then  I can see the above error

**Comment by twoeths** [comment]
I can reproduce the issue with simpler code:
```
const request = await this.createStatus();
    const peerInfo = new PeerInfo(PeerId.createFromB58String("16Uiu2HAmK3aw5p4Uw7RYRFeUcL4u1pg3u6JN8MnyT5wRshNLvHqU"));
    peerInfo.multiaddrs.add("/ip4/176.9.51.216/tcp/9500");
    await this.network.reqResp.status(peerInfo, request);
```

**Comment by twoeths** [comment]
The issue happens at protocol negotiation, we tried to dial using the protocol `/eth2/beacon_chain/req/status/1/ssz_snappy` but got exception, we are not able to get a stream to send anything.

```
@@@@@@@@@@ 1 DEBUGGING STATUS issue
@@@ sendRequestStream: about to dial to peerInfo protocol=/eth2/beacon_chain/req/status/1/ssz_snappy
@@@ libp2p dialProtocol
@@@ libp2p dialProtocol getConnection
@@@ libp2p dialProtocol done getConnection
2020-06-02 11:38:17  [NODE]             info: Started rest api server on http://127.0.0.1:9596
@@@ select: write ["/multistream/1.0.0", "/noise"]
@@@ select: read "/multistream/1.0.0"
@@@ select: response= /multistream/1.0.0 checking if it supports /noise
@@@ select: read next response= "na"
@@@ select: trying other protocol write "/secio/1.0.0"
@@@ select: trying other protocol, read "/secio/1.0.0" for "/secio/1.0.0"
@@@ select: write ["/multistream/1.0.0", "/mplex/6.7.0"]
@@@ select: read "/multistream/1.0.0"
@@@ select: response= /multistream/1.0.0 checking if it supports /mplex/6.7.0
@@@ select: read next response= "/mplex/6.7.0"
@@@ libp2p newStream calling mss.select protocols [ '/ipfs/id/1.0.0' ]
@@@ select: write ["/multistream/1.0.0", "/ipfs/id/1.0.0"]
@@@ libp2p dialProtocol AWAITING connection.newStream and 20000ms
@@@ libp2p newStream calling mss.select protocols [ '/eth2/beacon_chain/req/status/1/ssz_snappy' ]
@@@ select: write ["/multistream/1.0.0", "/eth2/beacon_chain/req/status/1/ssz_snappy"]
2020-06-02 11:38:19  [NETWORK]         error: failed to send status(ssz_snappy) to peer 16Uiu2HAmK3aw5p4Uw7RYRFeUcL4u1pg3u6JN8MnyT5wRshNLvHqU. Error: stream ended before 1 bytes became available
    at /Users/tuyennguyen/Projects/workshop/lodestar/node_modules/it-reader/index.js:37:9
```

**Comment by twoeths** [comment]
From the log above, we can see that the node `/ip4/176.9.51.216/tcp/9500` does not support `/noise` so it uses `secio`, still don't know why it does not response correctly after we send `"/eth2/beacon_chain/req/status/1/ssz_snappy"`, if it does not support it should response back `"na"`.

**Comment by mpetrunic** [comment]
I don't think it's about noise/secio, libp2p falbacks automatically if peer doesn't support one, as you can see it negotiated secio.
This error can happen for two reasons:
1. peer closed connection either by user or network
2. peer doesn't support eth2 protocol (either compression or format since format

My best guess is that snappy isn't supported and we aren't trying to fallback with ssz without compression. I'll ask around if guys from lighthouse knows on which stack this peer is running

**Comment by twoeths** [comment]
Some more information: 
+ since I can reproduce the issue consistently, we can ignore 1)
+ I also tried `ssz` instead of `ssz_snappy` and still see the same issue.
+ since it happens at the time of protocol negotiation, same issue happens if we send `ping` instead of `status`

**Comment by mpetrunic** [comment]
It would be nice if we had enr of that peer, maybe it's not eth2 peer or some peer like Johnnys that crawls network and doesn't serve requets :smile: 

Maybe we are blacklisted, try to change your peer id

**Comment by twoeths** [comment]
> Maybe we are blacklisted, try to change your peer id

you're right, if I setup new peer id then I don't see the issue anymore

**Comment by mpetrunic** [comment]
Should we close this issue or convert it so we implement some kind of blacklist ourselves so we don't try to dial those peers constantly?

**Comment by twoeths** [comment]
I prefer closing this and open a new issue linked to this one.
