### ISSUE TITLE
[non-substantive] Clarify genesis finalized checkpoint root 

### ISSUE THREAD

**Issue by ColinSchwarz** [ChainSafe/lodestar#998]
https://github.com/ethereum/eth2.0-specs/pull/1867

**Comment by wemeetagain** [comment]
non-substantive, no code change

**Comment by wemeetagain** [comment]
We aren't/weren't actually doing this. ~This should be merged to master, to conform asap.~

**Comment by wemeetagain** [comment]
Fixed with #1102
